### PR TITLE
Issue #14654: fix catch parameter wrong indentation

### LINKED ISSUE #14654: incompatibility with google-java-format: CatchFormalParameter is indented by 4 spaces instead of 2
```bash
$ curl -L -O -s https://github.com/checkstyle/checkstyle/releases/download/checkstyle-10.14.1/checkstyle-10.14.1-all.jar
$ curl -L -O -s https://github.com/google/google-java-format/releases/download/v1.21.0/google-java-format-1.21.0-all-deps.jar
$ echo 'class CatchFormalParameterIndention{void test(){try{throw new UnsupportedOperationException();} catch(@SuppressWarnings("PMD.AvoidCatchingGenericException") Exception e){java.util.logging.Logger.getAnonymousLogger().severe(e.toString());}}}' > CatchFormalParameterIndention.java
$ cat CatchFormalParameterIndention.java
class CatchFormalParameterIndention{void test(){try{throw new UnsupportedOperationException();} catch(@SuppressWarnings("PMD.AvoidCatchingGenericException") Exception e){java.util.logging.Logger.getAnonymousLogger().severe(e.toString());}}}
$ java -jar google-java-format-1.21.0-all-deps.jar --replace CatchFormalParameterIndention.java
$ javac CatchFormalParameterIndention.java
$ cat CatchFormalParameterIndention.java
class CatchFormalParameterIndention {
  void test() {
    try {
      throw new UnsupportedOperationException();
    } catch (
        @SuppressWarnings("PMD.AvoidCatchingGenericException")
        Exception e) {
      java.util.logging.Logger.getAnonymousLogger().severe(e.toString());
    }
  }
}
$ RUN_LOCALE="-Duser.language=en -Duser.country=US"
$ java $RUN_LOCALE -jar checkstyle-10.14.1-all.jar -c /google_checks.xml CatchFormalParameterIndention.java
Starting audit...
[WARN] /private/tmp/CatchFormalParameterIndention.java:6:9: 'catch' child has incorrect indentation level 8, expected level should be 4. [Indentation]
Audit done.
```

---

Code formatted by `google-java-format` (the de-facto standard Google Java Style formatter) should be compatible with the `google_checks.xml` configuration out-of-the-box.

### PR DESCRIPTION
**Pull request by mohitsatr**
fixes #14654 

Diff Regression config: https://gist.githubusercontent.com/mohitsatr/d55485b980e5c7ae9c883ba8f79dcbd6/raw/c824102d90368dbd060f41a1f6bda249cdcf0a5b/master_google_style.xml

Diff Regression projects: https://gist.githubusercontent.com/mohitsatr/68b0817ac52ff7773d35585ee12fc1cc/raw/f9c7774ca78df1f48f34bf30799bd3952abd9e2a/list-of-projects.properties

### CODE REVIEW

**Comment by mohitsatr** [comment]
Github, generate report for Indentation/all-examples-in-one

**Comment by romani** [comment]
do not forget to add code to ITs of google style, to let formatter do formatting on code and checkstyle run on same file.


https://github.com/checkstyle/checkstyle/blob/d73922d7ecf3870964a6d3524000dc2c140d8491/.github/workflows/google-java-format.yml#L48


be aware of files that are excluded due to conflict of formatter and checkstyle:
https://github.com/checkstyle/checkstyle/blob/d73922d7ecf3870964a6d3524000dc2c140d8491/.ci/google-java-format.sh#L45

if you put a lot of samples to ITs of google it will be good prove that formatter and checkstyle validate same code and not conflicting with each other

**Comment by mohitsatr** [comment]
Github, generate report

**Comment by mohitsatr** [comment]
Github, generate report

**Comment by romani** [comment]
@mohitsatr , is it still wip ?

**Comment by mohitsatr** [comment]
yes, I was busy researching for proposal. i will get to back to it as soon as Im done with that

**Comment by mohitsatr** [comment]
@Zopsss @romani ready for review

**Comment by mohitsatr** [comment]
Github, generate report

**Comment by mohitsatr** [comment]
nevermind, I'm checking the diffs

**Comment by mohitsatr** [comment]
there are conflicts created by the google-formatter.   
```
   public void test1() {
     try {
       System.out.println("try0");
     } catch (NullPointerException
-| IllegalArgumentException t) { // violation '.* incorrect indentation level 0, expected .* 8.'
+        | IllegalArgumentException
+            t) { // violation '.* incorrect indentation level 0, expected .* 8.'
     }
   }
```   
even though I have specified wrong indentation in violation message, it thinks code's formatted wrong.

```   
        System.out.println("try");
     } catch (
         @SuppressWarnings("PMD.AvoidCatchingGenericException")
-    Exception e) { // violation '.* incorrect indentation level 4, expected .* 8.'
+        Exception e) { // violation '.* incorrect indentation level 4, expected .* 8.'
       java.util.logging.Logger.getAnonymousLogger().severe(e.toString());
     }
```

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/AbstractExpressionHandler.java [hunk 1]
```diff
@@ -290,9 +297,9 @@ private void checkLinesIndent(DetailAstSet astSet,
             // indentation is absorbed by the nesting
 
             IndentLevel theLevel = indentLevel;
-            if (firstLineMatches
-                || firstLine > mainAst.getLineNo() && shouldIncreaseIndent()) {
-                theLevel = new IndentLevel(indentLevel, getBasicOffset());
+            if ((firstLineMatches || firstLine > mainAst.getLineNo())
+                    && shouldIncreaseIndent()) {
+                theLevel = new IndentLevel(indentLevel, indentCheck.getLineWrappingIndentation());
```
Comment (mohitsatr) [inline src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/AbstractExpressionHandler.java:302]: sdf

**Comment by mohitsatr** [comment]
@romani @Zopsss please review

**Comment by romani** [comment]
google formatter is more strict and opinionated.
Please apply patch from google formatter, our goal is to not put violation that what google formatter say is good.

in regular test area Inputs we can have any crazy indentations and see how Check place violation on it.

in IT for google style, we apply auto-formatter first, and must not produce any violation on what formatter did with code.
There might some defects in formatter also, and we should report to them and we will think what to do.

**Comment by romani** [comment]
formatter is still red, please fix.

**Comment by mohitsatr** [comment]
I suppose pitest one is not related to my changes ?

**Comment by Zopsss** [comment]
Yes it is not related to your PR.

**Comment by romani** [comment]
from semaphore:
https://checkstyle.semaphoreci.com/jobs/a7fb1b76-14ec-4825-9c9d-30672bee1b69#L836

```
> Task :postgresql:checkstyleMain 04:22
[ant:checkstyle] [ERROR] /home/semaphore/checkstyle/.ci-temp/pgjdbc/pgjdbc/src/main/java/org/postgresql/util/PasswordUtil.java:69:9: 'try' child has incorrect indentation level 8, expected level should be 10. [Indentation] 04:22
[ant:checkstyle] [ERROR] /home/semaphore/checkstyle/.ci-temp/pgjdbc/pgjdbc/src/main/java/org/postgresql/util/PasswordUtil.java:70:9: 'try' child has incorrect indentation level 8, expected level should be 10. [Indentation] 04:22
[ant:checkstyle] [ERROR] /home/semaphore/checkstyle/.ci-temp/pgjdbc/pgjdbc/src/main/java/org/postgresql/util/PasswordUtil.java:71:9: 'try' child has incorrect indentation level 8, expected level should be 10. [Indentation] 04:22
[ant:checkstyle] [ERROR] /home/semaphore/checkstyle/.ci-temp/pgjdbc/pgjdbc/src/main/java/org/postgresql/util/PasswordUtil.java:72:9: 'try' child has incorrect indentation level 8, expected level should be 10. [Indentation]
```

**Comment by sdavids** [comment]
Just a small nitpick:

_parameters_ is not spelled correctly in the commit message

**Comment by mohitsatr** [comment]
> please sen PR to pgjdbc

done https://github.com/pgjdbc/pgjdbc/pull/3611

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/AbstractExpressionHandler.java (hunk 1 above)
Comment (romani) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/AbstractExpressionHandler.java:302]: @mohitsatr , please add such code to Inputs.
All new violations or changes in diff report should be distinct-compacted to our Inputs.

**Comment by romani** [comment]
Ok, reports are same, let's extend Inputs and be prepared for merge

**Review by romani — CHANGES_REQUESTED** [review]
Items

File: src/it/resources-noncompilable/com/google/checkstyle/test/chapter4formatting/rule4841indentation/InputMultilineStatementsCorrect.java [hunk 2]
```diff
@@ -0,0 +1,52 @@
...
+        + simplePropertyUpdateScript;
+  }
+
+  void testConditionals(boolean result) {
+    int zk = result
+        ? 0 :
+        1;
+  }
+
+  int testMultilineifCondition(int newState, int tableName) { //indent:2 exp:2
```
[the remark this answers is not in the document]
Comment (mohitsatr) [reply src/it/resources-noncompilable/com/google/checkstyle/test/chapter4formatting/rule4841indentation/InputMultilineStatementsCorrect.java]: done

File: src/it/resources-noncompilable/com/google/checkstyle/test/chapter4formatting/rule4841indentation/InputMultilineStatementsCorrect.java [hunk 3]
```diff
@@ -0,0 +1,52 @@
...
+    final String simplePropertyUpdateScript = "";
+    return """
+        def newInstance = params.instance;
+        def existingInstance = ctx._source;
+        """
+        + simplePropertyUpdateScript;
+  }
+
+  void testConditionals(boolean result) {
+    int zk = result
```
[the remark this answers is not in the document]
Comment (mohitsatr) [reply src/it/resources-noncompilable/com/google/checkstyle/test/chapter4formatting/rule4841indentation/InputMultilineStatementsCorrect.java]: done

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/AbstractExpressionHandler.java (hunk 1 above)
Comment (mohitsatr) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/AbstractExpressionHandler.java:302]: done

**Comment by mohitsatr** [comment]
I don't understand why javac11 is failing even though javac17 has passed successfully.

**Comment by romani** [comment]
jdk version matters a lot, this syntax is for jdk17
```
src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/indentation/indentation/InputIndentationMultilineStatements.java:56: error: unclosed string literal
    final String simpleProperty = """
                                    ^

```

File: src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/indentation/indentation/InputIndentationMultilineStatements.java [hunk 4]
```diff
@@ -0,0 +1,76 @@
+// non-compiled with javac: Compilable with Java17                            //indent:0 exp:0
```
Comment (romani) [inline src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/indentation/indentation/InputIndentationMultilineStatements.java:1]: `//non-compiled with javac: Compilable with Java17`

remove space after `//` to allow java compilation on jdk11 to skip this file

**Review by romani — CHANGES_REQUESTED** [review]
item:

File: src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/indentation/indentation/InputIndentationMultilineStatements.java (hunk 4 above)
Comment (mohitsatr) [reply src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/indentation/indentation/InputIndentationMultilineStatements.java]: done. thanks

**Review by romani — APPROVED** [review]
thanks a lot !!!


@Aziz-755, can you review this PR ?

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/CatchHandler.java [hunk 5]
```diff
@@ -46,8 +46,12 @@ public CatchHandler(IndentationCheck indentCheck,
      */
     private void checkCondExpr() {
         final DetailAST condAst = getMainAst().findFirstToken(TokenTypes.LPAREN)
-            .getNextSibling();
-        checkExpressionSubtree(condAst, getIndent(), true, true);
+                .getNextSibling();
+        IndentLevel level = getIndent();
+        if (isOnStartOfLine(condAst)) {
+            level = new IndentLevel(getIndent(), getIndentCheck().getLineWrappingIndentation());
```
Comment (Aziz-755) [inline src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/CatchHandler.java:52]: Minor: `getIndent()` is called twice. In my opinion, reusing the `level` variable improves clarity

File: src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/indentation/indentation/InputIndentationMultilineStatements.java
Comment (Aziz-755) [inline src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/indentation/indentation/InputIndentationMultilineStatements.java:1]: Please align the //indent comments vertically for this file

File: src/test/resources/com/puppycrawl/tools/checkstyle/checks/indentation/indentation/InputIndentationCatchParametersOnNewLine.java
Comment (Aziz-755) [inline src/test/resources/com/puppycrawl/tools/checkstyle/checks/indentation/indentation/InputIndentationCatchParametersOnNewLine.java:1]: and here too ( //indent )

**Review by Aziz-755 — CHANGES_REQUESTED** [review]
Great work! 
Just minors

File: src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/indentation/indentation/InputIndentationMultilineStatements.java [hunk 6]
```diff
@@ -0,0 +1,76 @@
...
+      flag = 1; //indent:6 exp:6
+    } //indent:4 exp:4
+    return flag; //indent:4 exp:4
+  } //indent:2 exp:2
+
+  private String test5() {                                             //indent:2 exp:2
+    final String simpleProperty = """
+        s
+        """;                                                          //indent:8 exp:8
+    return ("""
```
Comment (romani) [inline src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/indentation/indentation/InputIndentationMultilineStatements.java:59]: Please use this syntax 
https://github.com/checkstyle/checkstyle/commit/ecf60db4e34d24ecb634441534037f7427d913c0#diff-ab3a1f402a35d6a380d75bc16518202959ba0c8ae4bea4e4d3e4991ffd2ff7fdR70

And use verifyWarn method.
@Prarthana-Ramesh, FYI, your improvement is now in use.

**Review by romani — CHANGES_REQUESTED** [review]
Items

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/CatchHandler.java (hunk 5 above)
Comment (mohitsatr) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/CatchHandler.java:52]: done all

File: src/test/resources/com/puppycrawl/tools/checkstyle/checks/indentation/indentation/InputIndentationCatchParametersOnNewLine.java [hunk 7]
```diff
@@ -0,0 +1,67 @@
...
+        Exception e) {                                                        //indent:8 exp:8
+      java.util.logging.Logger.getAnonymousLogger().severe(e.toString());     //indent:6 exp:6
+    }                                                                         //indent:4 exp:4
+  }                                                                           //indent:2 exp:2
+
+  void test3() {                                                              //indent:2 exp:2
+    try {                                                                     //indent:4 exp:4
+      System.out.println("try");                                              //indent:6 exp:6
+    } catch (                                                                 //indent:4 exp:4
+            @SuppressWarnings("PMD.AvoidCatchingGenericException")          //indent:12 exp:8 warn
```
Comment (romani) [inline src/test/resources/com/puppycrawl/tools/checkstyle/checks/indentation/indentation/InputIndentationCatchParametersOnNewLine.java:48]: please fix vertical alignment of trailing comment

File: src/test/resources/com/puppycrawl/tools/checkstyle/checks/indentation/indentation/InputIndentationCatchParametersOnNewLine.java [hunk 8]
```diff
@@ -0,0 +1,67 @@
...
+ */                                                                           //indent:1 exp:1
+
+package com.puppycrawl.tools.checkstyle.checks.indentation.indentation;       //indent:0 exp:0
+
+public class InputIndentationCatchParametersOnNewLine {                       //indent:0 exp:0
+  public void test1() {                                                       //indent:2 exp:2
+    try {                                                                     //indent:4 exp:4
+      System.out.println("try0");                                             //indent:6 exp:6
+    } catch (NullPointerException                                             //indent:4 exp:4
+| IllegalArgumentException t) {                                              //indent:0 exp:8 warn
```
Comment (romani) [inline src/test/resources/com/puppycrawl/tools/checkstyle/checks/indentation/indentation/InputIndentationCatchParametersOnNewLine.java:22]: please fix vertical alignment of trailing comment

File: src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/indentation/indentation/InputIndentationMultilineStatements.java [hunk 9]
```diff
@@ -0,0 +1,82 @@
+//non-compiled with javac: Compilable with Java17                            //indent:0 exp:0
+package com.puppycrawl.tools.checkstyle.checks.indentation.indentation;       //indent:0 exp:0
```
Comment (romani) [inline src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/indentation/indentation/InputIndentationMultilineStatements.java:2]: please fix vertical alignment of trailing comment

File: src/test/resources/com/puppycrawl/tools/checkstyle/checks/indentation/indentation/InputIndentationCatchParametersOnNewLine.java [hunk 10]
```diff
@@ -0,0 +1,67 @@
...
+    } catch (                                                                 //indent:4 exp:4
+        @SuppressWarnings("PMD.AvoidCatchingGenericException")                //indent:8 exp:8
+    Exception e) {                                                           //indent:4 exp:8 warn
+      java.util.logging.Logger.getAnonymousLogger().severe(e.toString());     //indent:6 exp:6
+    }                                                                         //indent:4 exp:4
+
+    try {                                                                     //indent:4 exp:4
+      System.out.println("try1");                                             //indent:6 exp:6
+    } catch (                                                                 //indent:4 exp:4
+    @SuppressWarnings("PMD.AvoidCatchingGenericException")                  //indent:4 exp:8 warn
```
Comment (romani) [inline src/test/resources/com/puppycrawl/tools/checkstyle/checks/indentation/indentation/InputIndentationCatchParametersOnNewLine.java:38]: please fix vertical alignment of trailing comment

File: src/test/resources/com/puppycrawl/tools/checkstyle/checks/indentation/indentation/InputIndentationCatchParametersOnNewLine.java [hunk 11]
```diff
@@ -0,0 +1,67 @@
...
+| IllegalArgumentException t) {                                              //indent:0 exp:8 warn
+    }                                                                         //indent:4 exp:4
+  }                                                                           //indent:2 exp:2
+
+  void test2() {                                                              //indent:2 exp:2
+    try {                                                                     //indent:4 exp:4
+      System.out.println("try");                                              //indent:6 exp:6
+    } catch (                                                                 //indent:4 exp:4
+        @SuppressWarnings("PMD.AvoidCatchingGenericException")                //indent:8 exp:8
+    Exception e) {                                                           //indent:4 exp:8 warn
```
Comment (romani) [inline src/test/resources/com/puppycrawl/tools/checkstyle/checks/indentation/indentation/InputIndentationCatchParametersOnNewLine.java:31]: please fix vertical alignment of trailing comment

File: src/it/resources-noncompilable/com/google/checkstyle/test/chapter4formatting/rule4841indentation/InputMultilineStatementsCorrect.java [hunk 12]
```diff
@@ -0,0 +1,52 @@
...
+        + simplePropertyUpdateScript;
+  }
+
+  void testConditionals(boolean result) {
+    int collect = result
+        ? 0 :
+        1;
+  }
+
+  int testIfConditionMultiline(int newState, int tableName) { //indent:2 exp:2
```
Comment (romani) [inline src/it/resources-noncompilable/com/google/checkstyle/test/chapter4formatting/rule4841indentation/InputMultilineStatementsCorrect.java:41]: please remove trailing comment

**Review by romani — CHANGES_REQUESTED** [review]
last last:

**Review by Aziz-755 — APPROVED** [review]

**Comment by Aziz-755** [comment]
Looks good !

File: src/test/resources/com/puppycrawl/tools/checkstyle/checks/indentation/indentation/InputIndentationCatchParametersOnNewLine.java (hunk 7 above)
Comment (mohitsatr) [reply src/test/resources/com/puppycrawl/tools/checkstyle/checks/indentation/indentation/InputIndentationCatchParametersOnNewLine.java:48]: done all. 
just curious, can we somehow automate alignment of comments? it's quite tedious doing manually :smiling_face_with_tear:

**Review by romani — APPROVED** [review]
Thanks a lot!!!!

>just curious, can we somehow automate alignment of comments? it's quite tedious doing manually 🥲

Please create issue on this, it should be trivial, we parsing this comment, so we definitely know it's position, but there might be exceptions.
