### PR TITLE
Issue #6508: Do not fail NewlineAtEndOfFile check with LF_CR_CRLF if file consists only of a newline character

### LINKED ISSUE #6508: NewlineAtEndOfFile with LF_CR_CRLF does not work properly
```
/var/tmp $ cat config.xml
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
        "-//Checkstyle//DTD Checkstyle Configuration 1.3//EN"
        "https://checkstyle.org/dtds/configuration_1_3.dtd">
<module name="Checker">
    <module name="NewlineAtEndOfFile">
        <property name="lineSeparator" value="lf_cr_crlf"/>
    </module>
</module>

/var/tmp $ xxd foo.properties
00000000: 0a                                       .

/var/tmp $ java -Duser.language=en -Duser.country=US -jar checkstyle-8.18-all.jar -c config.xml foo.properties
Starting audit...
[ERROR] D:\Sourcecode\other\discord-logger\tmp\foo.properties:1: File does not end with a newline. [NewlineAtEndOfFile]
Audit done.
Checkstyle ends with 1 errors.
```

---------------

With a file that only contains a linefeed character the `NewlineAtEndOfFile` check fails, because `NewlineAtEndOfFile` with `LF_CR_CRLF` requires to have at least two characters in the file with CS 8.18, even when technically only the latter is checked actually.
Expected would be no violation.

https://checkstyle.org/property_types.html#lineSeparator 
`lf_cr_crlf` is "lf, cr or crlf" in other words ANY

### PR DESCRIPTION
**Pull request by Vampire**
Fixes #6508

### CODE REVIEW

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/LineSeparatorOption.java [hunk 1]
```diff
@@ -42,7 +42,7 @@
      * Matches CR, LF and CRLF line separators.
      * Only the length is used - the actual value is ignored.
      */
-    LF_CR_CRLF("##"),
```
Comment (romani) [inline src/main/java/com/puppycrawl/tools/checkstyle/checks/LineSeparatorOption.java]: comment above should be fixed.

Comment (Vampire) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/LineSeparatorOption.java]: Fixed in what regard?
The comment is still valid.
Only the length of the enum argument is used, but the value `#` is ignored.

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/LineSeparatorOption.java [hunk 2]
```diff
@@ -69,8 +69,7 @@ public boolean matches(byte... bytes) {
         if (this == LF_CR_CRLF) {
             // this silently assumes LF and CR are of length 1
             // CRLF always matches LF, so CRLF isn't tested
-            result = LF.matches(Arrays.copyOfRange(bytes, 1, 2))
```
[the remark this answers is not in the document]
Comment (Vampire) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/LineSeparatorOption.java]: Fixed in what regard?
The comment is still valid.
The code still silently assumes that CR and LF are of length 1, we just don't need the sub-array anymore as the pattern is also of length 1 now.

File: src/test/java/com/puppycrawl/tools/checkstyle/checks/NewlineAtEndOfFileCheckTest.java [hunk 3]
```diff
@@ -180,6 +180,18 @@ public void testFileWithEmptyLineOnly() throws Exception {
...
 
+    @Test
+    public void testFileWithEmptyLineOnlyWithLfCrCrlf() throws Exception {
+        final DefaultConfiguration checkConfig =
+                createModuleConfig(NewlineAtEndOfFileCheck.class);
+        checkConfig.addAttribute("lineSeparator", LineSeparatorOption.LF_CR_CRLF.toString());
+        final String[] expected = CommonUtil.EMPTY_STRING_ARRAY;
+        verify(
+                createChecker(checkConfig),
+                getPath("InputNewlineAtEndOfFileNewlineAtEnd.txt"),
```
Comment (rnveach) [inline src/test/java/com/puppycrawl/tools/checkstyle/checks/NewlineAtEndOfFileCheckTest.java]: > /var/tmp $ xxd foo.properties
00000000: 0a       

The test case between the issue and here is different. `InputNewlineAtEndOfFileNewlineAtEnd` will have `\n` or `\r\n` depending on the OS.

Does the issue still happen with this file even though the file is longer than 1 byte?
Do we want to use a file that is the same line encoding on all OSes that is controlled through the `.gitattributes` file like `InputNewlineAtEndOfFileLf`?

**Comment by rnveach** [comment]
@Vampire please also provide regression for your change.

**Comment by Vampire** [comment]
Jenkins dead?

File: .gitattributes [hunk 4]
```diff
@@ -1,5 +1,6 @@
 /src/test/resources/com/puppycrawl/tools/checkstyle/checks/newlineatendoffile/InputNewlineAtEndOfFileLf.java eol=lf
 /src/test/resources/com/puppycrawl/tools/checkstyle/checks/newlineatendoffile/InputNewlineAtEndOfFileCrlf.java eol=crlf
 /src/test/resources/com/puppycrawl/tools/checkstyle/checks/newlineatendoffile/InputNewlineAtEndOfFileCr.java -text
+/src/test/resources/com/puppycrawl/tools/checkstyle/checks/newlineatendoffile/InputNewlineAtEndOfFileNewlineAtEnd.txt eol=lf
```
Comment (rnveach) [inline .gitattributes]: Please don't convert an existing file to only be a specific line ending.
Either use an existing one or create a new one and put `Lf` on the end of the file name like the others to denote its ending.

Comment (Vampire) [reply .gitattributes]: Ok, I renamed it, as like mentioned before, the other test using it also needs it like that or will break as soon as #4074 gets fixed.

**Comment by Vampire** [comment]
Regression report: http://kautler.net/cs-regression-6508/

**Comment by Vampire** [comment]
Is the snyk hanging or something?

**Comment by rnveach** [comment]
> Is the snyk hanging or something?

It looks like it. I don't have access to it and asked @romani to provide me access.

File: .gitattributes (hunk 4 above)
Comment (rnveach) [reply .gitattributes]: > Ok, I renamed it

Like I said, don't convert an existing file. It is probably testing something specific since appveyor will automatically convert files not mentioned in `.gitattributes` to `\r\n`.
Please just make a whole new file.

Comment (Vampire) [reply .gitattributes]: I'm sorry, but I don't get it.
The test tests, that the check works properly if the file only consists of an empty line with the line separator option set to LF.
If #4074 gets fixed, this test will still be green on systems where the files get checked out with LF but fail on systems where the files get checked out with CRLF endings.
Updating the expected result doesn't sound like the correct way to me, it intermixes two tests, the test that the check works properly on a file consisting only of an empty line and that LF does not match CRLF.
Imho it is better to test the one aspect in the test that it is about and have a different test that tests the bug that #4074 is about.

Comment (rnveach) [reply .gitattributes]: > If #4074 gets fixed, this test will still be green

Ok, I thought you were saying this test would fail once another issue is worked on. I misunderstood what you meant.

We still need the 2 different input files, one goes to the git's default and one that is forced to LF.

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/LineSeparatorOption.java (hunk 1 above)
Comment (romani) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/LineSeparatorOption.java]: you are right.

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/LineSeparatorOption.java (hunk 2 above)
[the remark this answers is not in the document]
Comment (romani) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/LineSeparatorOption.java]: you are right

**Comment by romani** [comment]
```
hexdump src/test/resources/com/puppycrawl/tools/checkstyle/checks/newlineatendoffile/InputNewlineAtEndOfFileNewlineAtEnd.txt
0000000 0a
0000001
```

LF is 0A

**Comment by romani** [comment]
@Vampire , please finish discussion with @rnveach.
Sorry for lang delay with acceptance of such simple fix.

File: .gitattributes (hunk 4 above)
Comment (Vampire) [reply .gitattributes]: > Ok, I thought you were saying this test would fail once another issue is worked on. I misunderstood what you meant.

No you didn't. o_O
That is **exactly** what I am saying.
The test we are talking about verifies that the check works properly if the parameter is set to `LF` and the file consists solely of `LF`.
Currently this works also if the file consists of `CR` followed by `LF` due to the mentioned issue.
If the mentioned issue gets fixed, then this test will fail on checkouts that use CRLF line endings.
By using the same file here, this will not happen.

> We still need the 2 different input files, one goes to the git's default and one that is forced to LF.

I can surely do this, I just want you to first understand what I am saying, as you obviously didn't yet, so that you can decide with the correct facts in mind that I'm stating. :-)

Comment (rnveach) [reply .gitattributes]: > this test will still be green on systems where the files get checked out with LF but fail on systems where the files get checked out with CRLF endings.

We will have to make the expected result conditional if we go forward with different line endings on the same OS.

> Imho it is better to test the one aspect in the test that it is about and have a different test that tests the bug that #4074 is about.

Thats what we are doing isn't it? We are adding a new file that is LF only and 4074 will add a new file that is CRLF only (if there isn't one). All I am saying is there is a 3rd file which is basically AUTO line endings and it shouldn't be touched in the scope of this PR. It is testing something else and should remain as it is.

> I just want you to first understand what I am saying, as you obviously didn't yet, so that you can decide with the correct facts in mind that I'm stating.

I am not sure we are on the same page with this long discussion. Lets move on and not slow down the PR.
We should create a new file and not rename the old one.

Comment (Vampire) [reply .gitattributes]: > > Imho it is better to test the one aspect in the test that it is about and have a different test that tests the bug that #4074 is about.
> 
> Thats what we are doing isn't it? We are adding a new file that is LF only and 4074 will add a new file that is CRLF only (if there isn't one). All I am saying is there is a 3rd file which is basically AUTO line endings and it shouldn't be touched in the scope of this PR. It is testing something else and should remain as it is.

I don't think so.
Despite its name, the test `testFileWithEmptyLineOnly` tests how the check behaves with `LineSeparatorOption.LF` set and a file that only consists of an empty line.
If you currently check out on a system with `CR` line endings, this test already fails, as it is a bug that the test is green with `CRLF ` line endings (which will be fixed with #4074).
The test imho is not there to test that the check behaves properly with different line endings, or the test should use files with different line endings to verify it works properly with them.

> We should create a new file and not rename the old one.

Well, as you wish, I pushed an update.

Comment (rnveach) [reply .gitattributes]: > the test should use files with different line endings to verify it works properly with them

There should be a separate test for each kind of line ending. So in the end we should have atleast 20 tests ( 4 file line endings LF, CRLF, CR, system x 5 options crlf, cr, lf, lf_cr_crlf, system).
`system` will always be the hardest to test since it can pass on 1 system and fail on another.

> out on a system with CR line endings, this test already fails

MacOS is CR line endings right? We already have MacOS in the CI and it is passing. Why isn't it failing if that is the case?

Comment (Vampire) [reply .gitattributes]: OS X nowadays is LF too.
Older versions were CR.
