### PR TITLE
Issue #14963: Add new property to skip unnamed parameters in FinalPar…

### LINKED ISSUE #14963: Add Check Support for Java 21 Unnamed Variables & Patterns Syntax: FinalParameter
child of #14942 

I have read check documentation: https://checkstyle.org/checks/misc/finalparameters.html#FinalParameters
I have downloaded the latest checkstyle from: https://checkstyle.org/cmdline.html#Download_and_Run
I have executed the cli and showed it below, as cli describes the problem better than 1,000 words

```
PS D:\CS\test> javac src/Test.java
PS D:\CS\test> cat src/Test.java
import java.util.PriorityQueue;
import java.util.Queue;

class Test {
    void test() {
        Queue<Integer> q = new PriorityQueue<>();
        q.add(1);
        for (Integer _ : q) {  // violation
            q.poll();
        }
        try {
            int x = 1 / 0;
        } catch (Exception _) {       // violation
            System.out.println("division by zero");
        }
    }
}

PS D:\CS\test> cat config.xml
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
          "-//Puppy Crawl//DTD Check Configuration 1.3//EN"
          "http://www.puppycrawl.com/dtds/configuration_1_3.dtd">

<module name="Checker">
    <property name="charset" value="UTF-8"/>
 <module name="TreeWalker">
    <module name="FinalParameters">
        <property name="tokens" value="FOR_EACH_CLAUSE, LITERAL_CATCH"/>
    </module>
 </module>
</module>
PS D:\CS\test> java  -jar checkstyle-10.14.2-all.jar -c config.xml  src/Test.java
Starting audit...
[ERROR] D:\CS\test\src\Test.java:8:14: Parameter _ should be final. [FinalParameters]
[ERROR] D:\CS\test\src\Test.java:13:18: Parameter _ should be final. [FinalParameters]
Audit done.
Checkstyle ends with 2 errors.


```
---

**Describe what you expect in detail.**

check doc : 

> Rationale: Changing the value of parameters during the execution of the method's algorithm can be confusing and should be avoided. A great way to let the Java compiler prevent this coding style is to declare parameters final.

JLS:

> If a declaration does not include an identifier, but instead includes the reserved keyword _ (underscore), then the entity cannot be referred to by name.

So I consider this as a false positive unnamed variables can't be referred to by name and Their value can't change so there is no point to require it to be final

---

### PR DESCRIPTION
**Pull request by mahfouz72**
closes #14963:   

Diff Regression config: https://gist.githubusercontent.com/mahfouz72/afd57aa6e51ca161b7927acd959e5211/raw/25589ae66b95b075875747c055df30118c0861d3/check.xml

Diff Regression patch config: https://gist.githubusercontent.com/mahfouz72/33967bf86e4a29cafa429771b0e95808/raw/72f89107ab1b81c270885ee5042ccaf535221089/check_patch.xml

Diff Regression projects: https://gist.githubusercontent.com/mahfouz72/a3d0af030c8f5efd0d8a39f2c14750bc/raw/a3424ad9b6f722e5de1a927e3d85e383101b2b93/projects-to-test-on.properties

Report Label: property is false

### CODE REVIEW

**Comment by mahfouz72** [comment]
github, generate report

**Comment by mahfouz72** [comment]
github, generate site

**Comment by mahfouz72** [comment]
github, generate report

**Comment by mahfouz72** [comment]
https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/e53d9a2_2024010200/reports/diff/checkstyle/index.html#A3 This exception due to record pattern syntax in enhanced for that is no longer compilable syntax. It was in preview and removed in the final release

**Comment by nrmancuso** [comment]
> https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/e53d9a2_2024010200/reports/diff/checkstyle/index.html#A3 This exception due to record pattern syntax in enhanced for that is no longer compilable syntax. It was in preview and removed in the final release

Please always show this sort of thing via javac.

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/FinalParametersCheck.java [hunk 1]
```diff
@@ -48,6 +48,13 @@
  * Default value is {@code false}.
  * </li>
  * <li>
+ * Property {@code ignoreUnnamedParameters} -
```
Comment (nrmancuso) [inline src/main/java/com/puppycrawl/tools/checkstyle/checks/FinalParametersCheck.java:51]: Not really for this line, but please add a new example that shows how this property works, with a brief explanation about why someone may want to use it.

**Review by nrmancuso — CHANGES_REQUESTED** [review]
Code looks good, one item:

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/FinalParametersCheck.java (hunk 1 above)
Comment (mahfouz72) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/FinalParametersCheck.java:51]: should we always do this?  I think we introduced new properties in other PRs without adding new examples for it

Comment (nrmancuso) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/FinalParametersCheck.java:51]: > should we always do this?

Maybe not always, but probably most of the time.

**Comment by mahfouz72** [comment]
github, generate site

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/FinalParametersCheck.java (hunk 1 above)
Comment (mahfouz72) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/FinalParametersCheck.java:51]: @nrmancuso

**Comment by mahfouz72** [comment]
github, generate site

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/FinalParametersCheck.java (hunk 1 above)
Comment (mahfouz72) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/FinalParametersCheck.java:51]: @nrmancuso done

File: src/xdocs-examples/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/finalparameters/Example4.java [hunk 2]
```diff
@@ -0,0 +1,45 @@
...
+    }
+  }
+
+  void testForEachParameters() {
+    int[] l = {1, 2, 3};
+    int x = 0;
+    for (int number: l) { // violation, 'Parameter number should be final'
+      System.out.println(number);
+    }
+    for (int _: l) {  // ok, unnamed catch parameter is ignored, it can't be used
```
Comment (nrmancuso) [inline src/xdocs-examples/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/finalparameters/Example4.java:39]: Looks like copypasta
```suggestion
    for (int _: l) {  // ok, unnamed enhanced for loop variable, it is implicitly final
```

**Review by nrmancuso — CHANGES_REQUESTED** [review]
Last item:

File: src/xdocs-examples/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/finalparameters/Example4.java (hunk 2 above)
Comment (mahfouz72) [reply src/xdocs-examples/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/finalparameters/Example4.java]: > Looks like copypasta

Yes :) thank you. Updated the above comment also to be consistent in wording.
`it can't be used` =>` it is implicitly final`

**Review by nrmancuso — APPROVED** [review]

File: src/xdocs/checks/misc/finalparameters.xml [hunk 3]
```diff
@@ -144,6 +152,57 @@ public class Example3 {
   public void methodOne(final int x) { }
   public void methodTwo(int x) { }
   public static void main(String[] args) { } // violation, 'args should be final'
+}
+        </source>
+        <p id="Example4-config">
+          To configure the check to enforce final parameters for catch and
+          for-each blocks while ignoring unnamed parameters.
+          Since unnamed parameters cannot be read from or written to,
+          marking them as final is unnecessary:
```
Comment (rnveach) [inline src/xdocs/checks/misc/finalparameters.xml:161]: The wording is a bit weird. We usually say "To configure...: config example" (notice no period so it is a complete thought), but instead there is another sentence with an explanation instead of a config, making the first sentence not really a complete sentence since it says "To configure" without showing them how to configure.

I would remove the second sentence, replace the period of the first sentence with `:`, and use the Java code comments as a way to convey the reason you tried to show in the second sentence. If you really needed to explain more, it should be done before "To configure" or after the Java example IMO.

File: src/xdocs/checks/misc/finalparameters.xml [hunk 4]
```diff
@@ -144,6 +152,57 @@ public class Example3 {
...
+    try {
+      int x = 1 / 0;
+    }
+    catch (Exception e) { // violation, 'Parameter e should be final'
+      System.out.println(e);
+    }
+    try {
+      int x = 1 / 0;
+    }
+    catch (Exception _) { // ok, unnamed catch parameter, it is implicitly final
```
Comment (rnveach) [inline src/xdocs/checks/misc/finalparameters.xml:189]: Add another example with a `final` unnamed and just say it is ok to have the final declared.

**Review by rnveach — CHANGES_REQUESTED** [review]

**Comment by rnveach** [comment]
@romani @nrmancuso
https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/e53d9a2_2024010200/reports/diff/checkstyle/index.html#A3
https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/e53d9a2_2024010200/reports/diff/checkstyle/index.html#A8
https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/e53d9a2_2024010200/reports/diff/checkstyle/index.html#A10
Regression found an exception.

@mahfouz72 Move exception in master to new issue. Our checks should not throw an exception on compilable code.

**Comment by rnveach** [comment]
Maybe I am not finding all the regressions. I should see regression of:
* Base is default with all tokens, Patch is default with `ignoreUnnamedParameters` set to true with all tokens (expecting unnamed differences only)
* Base is default with all tokens, Patch is default with `ignoreUnnamedParameters` set to false with all tokens (expecting no differences)

**Comment by mahfouz72** [comment]
> If it is no longer compilable, why is it still in our repo and still marked as compilable ("Compilable with Java20")? Is this also something we should discuss removing?

I suggested somewhere that we should open an issue to remove the no longer compilable code in our repo. Such code was a preview in some version we supported it but it was removed. So I am good with this as an issue

File: src/xdocs/checks/misc/finalparameters.xml (hunk 3 above)
Comment (mahfouz72) [reply src/xdocs/checks/misc/finalparameters.xml]: done completely removed it the code examples and code comments speak well for this point.

File: src/xdocs/checks/misc/finalparameters.xml (hunk 4 above)
Comment (mahfouz72) [reply src/xdocs/checks/misc/finalparameters.xml:187]: done

**Comment by mahfouz72** [comment]
github, generate report

**Comment by mahfouz72** [comment]
github, generate report

**Comment by rnveach** [comment]
https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/22a829d_2024194022/reports/diff/index.html
Change in exceptions is fine. I am asking more questions outside of this.

https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/22a829d_2024183400/reports/diff/index.html

https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/22a829d_2024183400/reports/diff/openjdk17/index.html#A2
This is an interesting case. Method parameters can't be unnamed, but this file isn't compilable. Pre-java 9 they could use `_` as a named method parameter. Point of ignoring property is for Java 21+ projects to use and like I said they can't have a unnamed method parameter, so this behavior seems ok to me.

**Review by rnveach — APPROVED** [review]
