### PR TITLE
Fix NPE in RedundantModifierCheck

### LINKED ISSUE #8299: RedundantModifierCheck throws NullPointerException
Check documentation: 
[RedundantModifier](https://checkstyle.sourceforge.io/config_modifier.html#RedundantModifier)

````
$ cat TestClass.java
import java.io.IOException;
import java.io.OutputStreamWriter;
import java.io.Writer;
import java.net.Socket;
import java.nio.charset.StandardCharsets;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Locale;
import java.util.concurrent.Callable;

public class DaytimeTask implements Runnable, Callable<Void> {
  private static final String UTF_8 = StandardCharsets.UTF_8.name();
  private final Socket connection;

  DaytimeTask(Socket connection) {
    this.connection = connection;
  }

  @Override
  public Void call() {
    run();
    return null;
  }

  @Override
  @SuppressWarnings("PMD.LawOfDemeter")
  public void run() {
    try (Writer out =
             new OutputStreamWriter(connection.getOutputStream(), UTF_8);
         connection;) {
      Date now = new Date();
      SimpleDateFormat format =
          new SimpleDateFormat("yy-MM-dd hh:mm:ss Z", Locale.getDefault());
      out.write(ProcessHandle.current().pid() + " " + format.format(now)
                + "\r\n");
      out.flush();
    } catch (IOException ex) {
      System.err.println(ex);
    }
  }
}

$ cat TestConfig.xml
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
          "-//Puppy Crawl//DTD Check Configuration 1.3//EN"
          "https://checkstyle.org/dtds/configuration_1_3.dtd">

<module name="Checker">
    <property name="charset" value="UTF-8"/>

    <module name="TreeWalker">
    <module name="RedundantModifier" />
    </module>
</module>

$ java -jar checkstyle-8.33-all.jar -c TestConfig.xml TestClass.java
Starting audit...
com.puppycrawl.tools.checkstyle.api.CheckstyleException: Exception was thrown while processing TestClass.java
    at com.puppycrawl.tools.checkstyle.Checker.processFiles(Checker.java:311)
    at com.puppycrawl.tools.checkstyle.Checker.process(Checker.java:221)
    at com.puppycrawl.tools.checkstyle.Main.runCheckstyle(Main.java:408)
    at com.puppycrawl.tools.checkstyle.Main.runCli(Main.java:331)
    at com.puppycrawl.tools.checkstyle.Main.execute(Main.java:190)
    at com.puppycrawl.tools.checkstyle.Main.main(Main.java:125)
Caused by: java.lang.NullPointerException
    at com.puppycrawl.tools.checkstyle.checks.modifier.RedundantModifierCheck.checkForRedundantModifier(RedundantModifierCheck.java:424)
    at com.puppycrawl.tools.checkstyle.checks.modifier.RedundantModifierCheck.processResources(RedundantModifierCheck.java:413)
    at com.puppycrawl.tools.checkstyle.checks.modifier.RedundantModifierCheck.visitToken(RedundantModifierCheck.java:237)
    at com.puppycrawl.tools.checkstyle.TreeWalker.notifyVisit(TreeWalker.java:340)
    at com.puppycrawl.tools.checkstyle.TreeWalker.processIter(TreeWalker.java:451)
    at com.puppycrawl.tools.checkstyle.TreeWalker.walk(TreeWalker.java:278)
    at com.puppycrawl.tools.checkstyle.TreeWalker.processFiltered(TreeWalker.java:151)
    at com.puppycrawl.tools.checkstyle.api.AbstractFileSetCheck.process(AbstractFileSetCheck.java:87)
    at com.puppycrawl.tools.checkstyle.Checker.processFile(Checker.java:337)
    at com.puppycrawl.tools.checkstyle.Checker.processFiles(Checker.java:298)
    ... 5 more
Checkstyle ends with 1 errors.
````

---------------

Describe what you expect in detail.

Checkstyle should complete successfully either emitting violations or no error messages when there are none. No NullPointerException as above must occur.

--------------

First reported at Checkstyle Google group:

https://groups.google.com/forum/m/#!topic/checkstyle/OZvmwJypxvI

Links to additional files throwing similar exception in Google Group post.

### PR DESCRIPTION
**Pull request by strkkk**
Resolves #8299 
Reg report (no diff): https://strkkk.github.io/checkstyle/8299/index.html

### CODE REVIEW

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/modifier/RedundantModifierCheck.java [hunk 1]
```diff
@@ -270,27 +270,9 @@ private void checkInterfaceModifiers(DetailAST ast) {
...
-        DetailAST modifier = modifiers.getFirstChild();
-
-        while (modifier != null && modifier.getType() == TokenTypes.ANNOTATION) {
-            modifier = modifier.getNextSibling();
-        }
-
-        return modifier;
+        TokenUtil.findFirstTokenByPredicate(
+            modifiers, mod -> mod.getType() != TokenTypes.ANNOTATION
+        ).ifPresent(modifier -> log(modifier, MSG_KEY, modifier.getText()));
```
Comment (pbludov) [inline src/main/java/com/puppycrawl/tools/checkstyle/checks/modifier/RedundantModifierCheck.java:275]: I can't say for sure, but I don't like this. I would like to see the closing parenthesis on the previous line. There is a chain, but no indentation.

Comment (romani) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/modifier/RedundantModifierCheck.java:275]:
```
        TokenUtil.findFirstTokenByPredicate(
                modifiers, mod -> mod.getType() != TokenTypes.ANNOTATION)
            .ifPresent(modifier -> log(modifier, MSG_KEY, modifier.getText()));
```

I do not have strong opinion on this for now.
