### PR TITLE
Issue #12291: fix bound condition in EmptyForInitializerPadCheck

### LINKED ISSUE #12291: EmptyForInitializerPad: ArrayIndexOutOfBoundsException
Identified at https://github.com/checkstyle/checkstyle/pull/12277 ,

````
$ cat TestClass.java
public class TestClass {
    void method() {
for (
;;) {}
    }
}

$ cat TestConfig.xml
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
          "-//Puppy Crawl//DTD Check Configuration 1.3//EN"
          "https://checkstyle.org/dtds/configuration_1_3.dtd">

<module name="Checker">
    <property name="charset" value="UTF-8"/>

    <module name="TreeWalker">
         <module name="EmptyForInitializerPad">
         </module>
    </module>
</module>

$ java -jar checkstyle-10.3.4-all.jar -c TestConfig.xml TestClass.java
Starting audit...
com.puppycrawl.tools.checkstyle.api.CheckstyleException: Exception was thrown while processing TestClass.java
    at com.puppycrawl.tools.checkstyle.Checker.processFiles(Checker.java:307)
    at com.puppycrawl.tools.checkstyle.Checker.process(Checker.java:224)
    at com.puppycrawl.tools.checkstyle.Main.runCheckstyle(Main.java:416)
    at com.puppycrawl.tools.checkstyle.Main.runCli(Main.java:339)
    at com.puppycrawl.tools.checkstyle.Main.execute(Main.java:196)
    at com.puppycrawl.tools.checkstyle.Main.main(Main.java:131)
Caused by: java.lang.ArrayIndexOutOfBoundsException: origin(0) > fence(-1)
    at java.base/java.util.Spliterators.checkFromToBounds(Spliterators.java:387)
    at java.base/java.util.Spliterators.spliterator(Spliterators.java:239)
    at java.base/java.util.Arrays.spliterator(Arrays.java:5521)
    at java.base/java.util.Arrays.stream(Arrays.java:5663)
    at com.puppycrawl.tools.checkstyle.utils.CodePointUtil.hasWhitespaceBefore(CodePointUtil.java:54)
    at com.puppycrawl.tools.checkstyle.checks.whitespace.EmptyForInitializerPadCheck.visitToken(EmptyForInitializerPadCheck.java:157)
    at com.puppycrawl.tools.checkstyle.TreeWalker.notifyVisit(TreeWalker.java:336)
    at com.puppycrawl.tools.checkstyle.TreeWalker.processIter(TreeWalker.java:407)
    at com.puppycrawl.tools.checkstyle.TreeWalker.walk(TreeWalker.java:274)
    at com.puppycrawl.tools.checkstyle.TreeWalker.processFiltered(TreeWalker.java:155)
    at com.puppycrawl.tools.checkstyle.api.AbstractFileSetCheck.process(AbstractFileSetCheck.java:98)
    at com.puppycrawl.tools.checkstyle.Checker.processFile(Checker.java:335)
    at com.puppycrawl.tools.checkstyle.Checker.processFiles(Checker.java:294)
    ... 5 more
Checkstyle ends with 1 errors.
````

I am expecting no violation.

### PR DESCRIPTION
**Pull request by strkkk**
Closes #12291 

Diff Regression config: https://gist.githubusercontent.com/strkkk/26466254f89c32d8f1a6bd53b6f5b251/raw/ebedd8493b5744621e68e25d3c3f5398958eeaf1/config_single.xml

Report (clean): https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/a33ccb6_2022154627/reports/diff/index.html

### CODE REVIEW

**Comment by strkkk** [comment]
CI failure is not related to changes

**Review by romani — APPROVED** [review]
Ok to merge

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/EmptyForInitializerPadCheck.java [hunk 1]
```diff
@@ -152,7 +152,7 @@ public void visitToken(DetailAST ast) {
             final int[] line = getLineCodePoints(lineIdx);
             final int before = ast.getColumnNo() - 1;
             // don't check if semi at beginning of line
-            if (!CodePointUtil.hasWhitespaceBefore(before, line)) {
+            if (ast.getColumnNo() > 0 && !CodePointUtil.hasWhitespaceBefore(before, line)) {
```
Comment (pbludov) [inline src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/EmptyForInitializerPadCheck.java:155]: Why not `if (before >= 0 &&` ?

For me it looks more clear.

Comment (strkkk) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/EmptyForInitializerPadCheck.java:155]: It can be both, but for current code pitest coverage is a little bit better.
Current code `>> Generated 2392 mutations Killed 2380 (99%)`
You suggestion `>> Generated 2391 mutations Killed 2378 (99%)`

**Review by pbludov — APPROVED** [review]
