### PR TITLE
Issue #12766: CommitValidationTest fails on revert commits

### LINKED ISSUE #12766: CommitValidationTest fails on revert commits
Commit: 26cadbb6772aa6ca85d6e95a9bff5d5366ca0430
Message: `Revert "doc: release notes for 10.8.0"`
Pipeline fail: https://dev.azure.com/romanivanovjr/romanivanovjr/_build/results?buildId=13264&view=logs&j=c902ebb4-c9f8-5f09-4e17-ff78fbbc842e&t=9ca98c81-ff64-58f0-9d03-a23ac1c4a111&l=795
```
[ERROR] Failures: 
[ERROR]   CommitValidationTest.testCommitMessageHasProperStructure:183 Commit 26cadbb6772aa6ca85d6e95a9bff5d5366ca0430 message: "Revert "doc: release notes for 10.8.0"\n\nThis reverts commit ff8bcc73c3c22161656794c969bb28a8cb09595f.\n" is invalid
Proper commit message should adhere to the following rules:
    1) Must match one of the following patterns:
        ^Issue #\d+: .*$
        ^Pull #\d+: .*$
        ^(minor|config|infra|doc|spelling|dependency|supplemental): .*$
    2) It contains only one line of text
    3) Must not end with a period, space, or tab
    4) Commit message should be less than or equal to 200 characters

The rule broken was: 1
[INFO] 
[ERROR] Tests run: 3931, Failures: 1, Errors: 0, Skipped: 2

```

### PR DESCRIPTION
**Pull request by stoyanK7**
Resolves #12766

### CODE REVIEW

File: src/test/java/com/puppycrawl/tools/checkstyle/internal/CommitValidationTest.java [hunk 1]
```diff
@@ -206,7 +223,11 @@ private static int validateCommitMessage(String commitMessage) {
         final String trimRight = commitMessage.replaceAll("[\\r\\n]+$", "");
         final int result;
 
-        if (!ACCEPTED_COMMIT_MESSAGE_PATTERN.matcher(message).matches()) {
+        if (message.matches(REVERT_COMMIT_MESSAGE_REGEX_PATTERN)) {
+            // revert commits are excluded from validation
+            result = 0;
+        }
+        else if (!ACCEPTED_COMMIT_MESSAGE_PATTERN.matcher(message).matches()) {
```
Comment (stoyanK7) [inline src/test/java/com/puppycrawl/tools/checkstyle/internal/CommitValidationTest.java:230]: As commented in the original issue https://github.com/checkstyle/checkstyle/issues/12766#issuecomment-1445427789,
revert commits violate two of the commit message rules. It would be easier to exclude them like this.

**Review by romani — APPROVED** [review]
Ok to merge
