### PR TITLE
Issue #8291: Checkstyle freezes on deeply nested lambdas

### LINKED ISSUE #8291: Checkstyle freezes on deeply nested lambdas
Identified at https://github.com/checkstyle/contribution/issues/483 ,

````
$ cat TestClass.java
import java.util.concurrent.Callable;

class TestClass {
    void test() {
        m(null, () -> m(null, () -> m(null, () -> m(null, () -> m(null, () -> m(null, () -> m(null,
                () -> m(null, () -> m(null, () -> m(null, () -> m(null, () -> m(null, () -> m(null,
                () -> m(null, () -> m(null, () -> m(null, () -> m(null, () -> m(null, () -> m(null,
                () -> m(null, () -> m(null, () -> m(null, () -> m(null, () -> m(null, () -> m(null,
                () -> m(null, () -> m(null, () -> m(null, () -> m(null, () -> m(null, () -> m(null,
                (Callable<String>)null)))))))))))))))))))))))))))))));
    }
    static class A0 { }
    static class A1 { }
    static class A2 { }
    static class A3 { }
    static class A4 { }
    <Z extends A0> Z m(A0 t, Callable<Z> ct) { return null; }
    <Z extends A1> Z m(A1 t, Callable<Z> ct) { return null; }
    <Z extends A2> Z m(A2 t, Callable<Z> ct) { return null; }
    <Z extends A3> Z m(A3 t, Callable<Z> ct) { return null; }
    <Z extends A4> Z m(A4 t, Callable<Z> ct) { return null; }
    <Z> Z m(Object o, Callable<Z> co) { return null; }
}

$ cat TestConfig.xml
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
          "-//Puppy Crawl//DTD Check Configuration 1.3//EN"
          "https://checkstyle.org/dtds/configuration_1_3.dtd">

<module name = "Checker">
    <property name="charset" value="UTF-8"/>

    <!-- do not change severity to 'error', as that will hide errors caused by exceptions -->
    <property name="severity" value="warning"/>

    <!-- haltOnException is required for exception fixes and reporting of all exceptions -->
    <property name="haltOnException" value="false"/>

    <!-- BeforeExecutionFileFilters is required for sources of java9 -->
    <module name="BeforeExecutionExclusionFileFilter">
        <property name="fileNamePattern" value="module\-info\.java$" />
    </module>

    <module name="TreeWalker">
         <module name="Indentation"/>

         <!-- Example of sevntu.checkstyle Check usage -->
         <!-- <module name="NestedSwitchCheck"/> -->

         <!-- usuppress javadoc parsing errors, as we test Check not a parser -->
         <module name="SuppressionXpathSingleFilter">
            <property name="message" value="Javadoc comment at column \d+ has parse error"/>
         </module>
    </module>
    <!-- Example of filter -->
    <!--
    <module name="SeverityMatchFilter">
        <property name="severity" value="warning"/>
        <property name="acceptOnMatch" value="false"/>
    </module>
    -->

    <!-- as we run on regression even on non-compiled files we need to skip exceptions on them -->
    <module name="SuppressionSingleFilter">
      <property name="message" value="Exception occurred while parsing"/>
      <property name="checks" value="Checker"/>
    </module>
</module>


$ java -jar checkstyle-8.33-all.jar -c TestConfig.xml TestClass.java
Starting audit...
````

Checkstyle completely freezes after that and does not respond. It does not seem related to the check being run but the AST.

### PR DESCRIPTION
**Pull request by nmancus1**
Closes #8291.

Note that no functional changes to existing code have been made; I have only included the test case from the issue and removed the associated file filters.

### CODE REVIEW

**Comment by nmancus1** [comment]
This PR must not be merged until https://github.com/checkstyle/checkstyle/pull/10280 is merged.

**Comment by rnveach** [comment]
> compilation for this one file increases mvn clean verify time by about 5 minutes 

Are you saying it takes 5 minutes to parse this input by Checkstyle? If not, then how much time is needed just for parsing?

**Comment by nmancus1** [comment]
> Are you saying it takes 5 minutes to parse this input by Checkstyle?

All test inputs, unless placed in non-compilable directories with `//non-compiled with javac` comment, are compiled. To compile this file, it takes a very long time (5+ minutes).

> If not, then how much time is needed just for parsing?

```bash

➜  src cat Test.java
//non-compiled with javac: exceeds time limits in CI
package com.puppycrawl.tools.checkstyle.javaparser;

import java.util.concurrent.Callable;

/**
 * This file is able to be compiled by Java 8, but takes a very long time.
 */
public class Test {
    void test() {
        m(null, () -> m(null, () -> m(null, () -> m(null, () -> m(null, () -> m(null, () -> m(null,
                () -> m(null, () -> m(null, () -> m(null, () -> m(null, () -> m(null, () -> m(null,
                () -> m(null, () -> m(null, () -> m(null, () -> m(null, () -> m(null, () -> m(null,
                () -> m(null, () -> m(null, () -> m(null, () -> m(null, () -> m(null, () -> m(null,
                () -> m(null, () -> m(null, () -> m(null, () -> m(null, () -> m(null, () -> m(null,
                (Callable<String>)null)))))))))))))))))))))))))))))));
    }
    static class A0 { }
    static class A1 { }
    static class A2 { }
    static class A3 { }
    static class A4 { }
    <Z extends A0> Z m(A0 t, Callable<Z> ct) { return null; }
    <Z extends A1> Z m(A1 t, Callable<Z> ct) { return null; }
    <Z extends A2> Z m(A2 t, Callable<Z> ct) { return null; }
    <Z extends A3> Z m(A3 t, Callable<Z> ct) { return null; }
    <Z extends A4> Z m(A4 t, Callable<Z> ct) { return null; }
    <Z> Z m(Object o, Callable<Z> co) { return null; }
}

➜  src time java -jar checkstyle-8.46-SNAPSHOT-all.jar -t Test.java
...
java -jar checkstyle-8.46-SNAPSHOT-all.jar -t Test.java  1.36s user 0.15s system 220% cpu 0.684 total


```

**Comment by romani** [comment]
@nmancus1 , please resolve conflict.

**Comment by romani** [comment]
```

no-exception-lucene-and-others-javadoc
failed 2 hours ago in 14m 59s


 Error:  Java heap space -> [Help 1]
java.lang.OutOfMemoryError: Java heap space
    at sun.nio.cs.StreamEncoder.write (StreamEncoder.java:133)
```

restarted but strange.

**Review by romani — APPROVED** [review]
Ok to merge, no functional code changes

**Review by esilkensen — APPROVED** [review]

**Comment by rnveach** [comment]
@romani This is ok?
> To compile this file, it takes a very long time (5+ minutes).

**Comment by nmancus1** [comment]
@rnveach

From https://github.com/checkstyle/checkstyle/pull/10436#issue-697920485: 

>  I have placed the test input in the non-compilable folder

**Comment by romani** [comment]
It is ok to keep it in non compilable

File: src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/javaparser/InputJavaParserNoFreezeOnDeeplyNestedLambdas.java [hunk 1]
```diff
@@ -0,0 +1,29 @@
+//non-compiled with javac: exceeds time limits in CI
```
Comment (pbludov) [inline src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/javaparser/InputJavaParserNoFreezeOnDeeplyNestedLambdas.java:1]: This bug was fixed in JDK10:
https://bugs.java.com/bugdatabase/view_bug.do?bug_id=8078093

Please try `Compilable with Java16` here. It compiles fine on my PC with JDK16.

**Review by pbludov — CHANGES_REQUESTED** [review]
Please try to set up the compilation with javac16.

File: src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/javaparser/InputJavaParserNoFreezeOnDeeplyNestedLambdas.java (hunk 1 above)
Comment (nmancus1) [reply src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/javaparser/InputJavaParserNoFreezeOnDeeplyNestedLambdas.java]: Awesome, this worked. Thanks a lot!

**Comment by romani** [comment]
@nmancus1 , please resolve conflict
