### PR TITLE
Issue #9086: ForceStrictCondition should not affect individual array elements

### LINKED ISSUE #9086: ForceStrictCondition should not affect individual array elements.
Extended from https://github.com/checkstyle/checkstyle/pull/8083#discussion_r534196175

javac Test.java 
```
No output
```

$ cat Test.java
```java
@InputIndentationAnnArrInit2.Foo({ //indent:0 exp:0
            @InputIndentationAnnArrInit2.Bar, //indent:12 exp:>=2 // should not allow this indentation.
            // because the element should only follow arrayInit, LineWrapping and basicOffset
            //  and no other except that
            // moreover, currently it is also following forceStrictCondition, due to which
            // the results/checkstyle output is changed with 
            // changing value of forceStrictCondition which should not be, because
            // it is not a lineWrapped element but an array child.
}) //indent:0 exp:0

// helper code
class InputIndentationAnnArrInit2 { //indent:0 exp:0
  @interface Foo { //indent:2 exp:2
    Bar[] value() default {}; //indent:4 exp:4

    String[] values() default {"Hello", "Checkstyle"}; //indent:4 exp:4
  } //indent:2 exp:2

  @interface Bar {} //indent:2 exp:2
} //indent:0 exp:0
```

$ cat config.xml
```xml
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
          "-//Puppy Crawl//DTD Check Configuration 1.3//EN"
          "http://www.puppycrawl.com/dtds/configuration_1_3.dtd">

<module name="Checker">
    <property name="charset" value="UTF-8"/>

    <module name="TreeWalker">
    <module name="Indentation">
      <property name="arrayInitIndent" value="2" />
      <property name="basicOffset" value="2"/>
      <property name="braceAdjustment" value="0"/>
      <property name="caseIndent" value="4"/>
      <property name="throwsIndent" value="4"/>
      <property name="lineWrappingIndentation" value="8"/>
    </module>
    </module>
</module>
```

# Actual Behaviour
$ java -jar checkstyle-8.38-all.jar -c config.xml Test.java 
```
Starting audit...
Audit done.
```

# Expected Behaviour
Error on line 2
```
Starting audit...
[ERROR] /Test.java:2:13: 'annotation array initialization' child has incorrect indentation level 12,
          expected level should be one of the following: 2, 8, 35, 41. [Indentation]
Audit done.
Checkstyle ends with 1 errors.
```

<details><summary>Verbal</summary>
<p>

**Concise description:**
Currently after merging PR #8083, annotation array initialization is supporting forceStrictCondition false and true properties.
Though the element indentation is made more flexible now, but it is somewhere not relatable to documentation of checkstyle upon array init indentation. 
The array elements should follow arrayinit Indentation and thus it should not care by forceStrictCondition.
because according to documentation: 
> Force strict indent level in line wrapping case. If value is true, line wrap indent have to be same as lineWrappingIndentation parameter. If value is false, line wrap indent could be bigger on any value user would like.

ForceStrictCondition should only be useful with lineWrapping.

**Describe the solution**
remove support for flexible indent levels for array children, they should follow pattern before merging PR #8038 for arrayInitializations.

**A doubt**
In array Initilizations we were following arrayInit, basicOffset, and linewrapping, so that user could get some flexibilty with their config, or for making the placements of children less confusing. But since we were using lineWrapping there, can't we have it benefits of forceStrictCondition false and  any indent level after minimum requirement.

</p>
</details>

### PR DESCRIPTION
**Pull request by Abhishek-kumar09**
Fixes #9086 
 Reverted to code point where we were not following forceStrictCondition for annotation array-elements.
Reverted to commit: https://github.com/Abhishek-kumar09/checkstyle/commit/543f240b13c90f7eec991824eb82ff1622d4e301 from Issue #5951 .

Diff Regression projects: https://gist.githubusercontent.com/Abhishek-kumar09/717190a7e2e06f4747b9c622692d4b99/raw/93fe7739cbdc52d7d17273a12d2b92328812c504/projects-to-test-on.properties
Diff Regression config: https://gist.githubusercontent.com/Abhishek-kumar09/57961e5808a1495433051701ff921494/raw/e7a3d51cabe1f918782b547a40763a9152743691/gconfig.xml

### CODE REVIEW

**Comment by romani** [comment]
@Abhishek-kumar09 , please resolve CI failures and please provide regression report.

File: src/test/java/com/puppycrawl/tools/checkstyle/checks/indentation/IndentationCheckTest.java [hunk 1]
```diff
@@ -1107,78 +1127,16 @@ public void testInvalidArrayInitWithChecker()
...
-                14, 12),
+                    14, 12),
             "128:15: " + getCheckMessage(MSG_CHILD_ERROR_MULTI, "annotation array initialization",
-                14, "16, 28, 30"),
+                    14, "16, 28, 30"),
             "129:9: " + getCheckMessage(MSG_ERROR_MULTI, "annotation array initialization rcurly",
                 8, "12, 16"),
             "131:13: " + getCheckMessage(MSG_CHILD_ERROR, "annotation array initialization",
-                12, 16),
+                    12, 16),
```
Comment (romani) [inline src/test/java/com/puppycrawl/tools/checkstyle/checks/indentation/IndentationCheckTest.java:1139]: please avoid updating unrelated lines

**Review by romani — CHANGES_REQUESTED** [review]
items:

**Comment by romani** [comment]
wercker failed https://app.wercker.com/checkstyle/checkstyle/runs/build/5fd14349237ec900082a7a3d?step=5fd1439864bf970008d236e0 

with 
```
Running Checkstyle on src/main/java ... with excludes {**/.ci-temp/**/*,**/resources-noncompilable/**/asttreestringprinter/**/*,**/resources-noncompilable/**/filefilters/**/*,**/resources-noncompilable/**/main/**/*,**/resources-noncompilable/**/suppressionsstringprinter/**/*,**/resources-noncompilable/**/gui/**/*,**/resources-noncompilable/**/javadocpropertiesgenerator/**/*,src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/javaparser/InputJavaParser.java,**/InputAllEscapedUnicodeCharacters.java,**/resources-noncompilable/**/javaparser/InputJavaParser.java,**/resources-noncompilable/**/checks/imports/unusedimports/InputUnusedImportsSingleWordPackage.java}
Running command: mvn -e --batch-mode site -Dcheckstyle.config.location=checks-nonjavadoc-error.xml -Dcheckstyle.excludes=**/.ci-temp/**/*,**/resources-noncompilable/**/asttreestringprinter/**/*,**/resources-noncompilable/**/filefilters/**/*,**/resources-noncompilable/**/main/**/*,**/resources-noncompilable/**/suppressionsstringprinter/**/*,**/resources-noncompilable/**/gui/**/*,**/resources-noncompilable/**/javadocpropertiesgenerator/**/*,src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/javaparser/InputJavaParser.java,**/InputAllEscapedUnicodeCharacters.java,**/resources-noncompilable/**/javaparser/InputJavaParser.java,**/resources-noncompilable/**/checks/imports/unusedimports/InputUnusedImportsSingleWordPackage.java -Dcheckstyle.version=8.39-SNAPSHOT
[INFO] Error stacktraces are turned on.
[INFO] Scanning for projects...
[INFO] 
[INFO] ----------------< com.github.sevntu.checkstyle:sample >-----------------
[INFO] Building sample 0.0.1-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- maven-site-plugin:3.3:site (default-site) @ sample ---
[INFO] configuring report plugin org.apache.maven.plugins:maven-site-plugin:3.3
[INFO] configuring report plugin org.apache.maven.plugins:maven-project-info-reports-plugin:2.7
[INFO] configuring report plugin org.apache.maven.plugins:maven-checkstyle-plugin:3.1.1
[INFO] configuring report plugin org.apache.maven.plugins:maven-jxr-plugin:2.5
[WARNING] No project URL defined - decoration links will not be relativized!
[INFO] Rendering site with org.apache.maven.skins:maven-default-skin:jar:1.0 skin.
[INFO] Skipped "Source Xref" report, file "xref/index.html" already exists for the English version.
[INFO] Generating "About" report    --- maven-project-info-reports-plugin:2.7
[INFO] Generating "Plugin Management" report    --- maven-project-info-reports-plugin:2.7
[INFO] Generating "Distribution Management" report    --- maven-project-info-reports-plugin:2.7
[INFO] Generating "Dependency Information" report    --- maven-project-info-reports-plugin:2.7
[INFO] Generating "Source Repository" report    --- maven-project-info-reports-plugin:2.7
[INFO] Generating "Mailing Lists" report    --- maven-project-info-reports-plugin:2.7
[INFO] Generating "Issue Tracking" report    --- maven-project-info-reports-plugin:2.7
[INFO] Generating "Continuous Integration" report    --- maven-project-info-reports-plugin:2.7
[INFO] Generating "Project Plugins" report    --- maven-project-info-reports-plugin:2.7
[INFO] Generating "Project License" report    --- maven-project-info-reports-plugin:2.7
[INFO] Generating "Project Team" report    --- maven-project-info-reports-plugin:2.7
[INFO] Generating "Project Summary" report    --- maven-project-info-reports-plugin:2.7
[INFO] Generating "Dependencies" report    --- maven-project-info-reports-plugin:2.7
[INFO] Generating "Checkstyle" report    --- maven-checkstyle-plugin:3.1.1
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  27.106 s
[INFO] Finished at: 2020-12-09T21:49:38Z
[INFO] ------------------------------------------------------------------------
---------------------------------------------------
constituent[0]: file:/usr/share/maven/conf/logging/
constituent[1]: file:/usr/share/maven/lib/maven-embedder-3.6.3.jar
constituent[2]: file:/usr/share/maven/lib/plexus-interpolation-1.25.jar
constituent[3]: file:/usr/share/maven/lib/slf4j-api-1.7.29.jar
constituent[4]: file:/usr/share/maven/lib/jansi-1.17.1.jar
constituent[5]: file:/usr/share/maven/lib/maven-resolver-impl-1.4.1.jar
constituent[6]: file:/usr/share/maven/lib/plexus-sec-dispatcher-1.4.jar
constituent[7]: file:/usr/share/maven/lib/maven-builder-support-3.6.3.jar
constituent[8]: file:/usr/share/maven/lib/maven-resolver-util-1.4.1.jar
constituent[9]: file:/usr/share/maven/lib/commons-lang3-3.8.1.jar
constituent[10]: file:/usr/share/maven/lib/maven-slf4j-provider-3.6.3.jar
constituent[11]: file:/usr/share/maven/lib/wagon-provider-api-3.3.4.jar
constituent[12]: file:/usr/share/maven/lib/maven-resolver-transport-wagon-1.4.1.jar
constituent[13]: file:/usr/share/maven/lib/commons-io-2.5.jar
constituent[14]: file:/usr/share/maven/lib/maven-artifact-3.6.3.jar
constituent[15]: file:/usr/share/maven/lib/jcl-over-slf4j-1.7.29.jar
constituent[16]: file:/usr/share/maven/lib/javax.inject-1.jar
constituent[17]: file:/usr/share/maven/lib/maven-resolver-spi-1.4.1.jar
constituent[18]: file:/usr/share/maven/lib/plexus-utils-3.2.1.jar
constituent[19]: file:/usr/share/maven/lib/maven-compat-3.6.3.jar
constituent[20]: file:/usr/share/maven/lib/maven-model-3.6.3.jar
constituent[21]: file:/usr/share/maven/lib/maven-resolver-api-1.4.1.jar
constituent[22]: file:/usr/share/maven/lib/maven-shared-utils-3.2.1.jar
constituent[23]: file:/usr/share/maven/lib/commons-cli-1.4.jar
constituent[24]: file:/usr/share/maven/lib/maven-settings-builder-3.6.3.jar
constituent[25]: file:/usr/share/maven/lib/maven-model-builder-3.6.3.jar
constituent[26]: file:/usr/share/maven/lib/wagon-http-3.3.4-shaded.jar
constituent[27]: file:/usr/share/maven/lib/jsoup-1.12.1.jar
constituent[28]: file:/usr/share/maven/lib/plexus-component-annotations-2.1.0.jar
constituent[29]: file:/usr/share/maven/lib/maven-resolver-connector-basic-1.4.1.jar
constituent[30]: file:/usr/share/maven/lib/maven-plugin-api-3.6.3.jar
constituent[31]: file:/usr/share/maven/lib/maven-settings-3.6.3.jar
constituent[32]: file:/usr/share/maven/lib/org.eclipse.sisu.inject-0.3.4.jar
constituent[33]: file:/usr/share/maven/lib/maven-repository-metadata-3.6.3.jar
constituent[34]: file:/usr/share/maven/lib/guava-25.1-android.jar
constituent[35]: file:/usr/share/maven/lib/guice-4.2.1-no_aop.jar
constituent[36]: file:/usr/share/maven/lib/jsr250-api-1.0.jar
constituent[37]: file:/usr/share/maven/lib/plexus-cipher-1.7.jar
constituent[38]: file:/usr/share/maven/lib/maven-resolver-provider-3.6.3.jar
constituent[39]: file:/usr/share/maven/lib/cdi-api-1.0.jar
constituent[40]: file:/usr/share/maven/lib/wagon-file-3.3.4.jar
constituent[41]: file:/usr/share/maven/lib/org.eclipse.sisu.plexus-0.3.4.jar
constituent[42]: file:/usr/share/maven/lib/maven-core-3.6.3.jar
---------------------------------------------------
Exception in thread "main" java.lang.Error: Error was thrown while processing /pipeline/source/.ci-temp/contribution/checkstyle-tester/src/main/java/local-checkstyle/target/test-classes/com/puppycrawl/tools/checkstyle/detailastimpl/InputDetailAstImplJustToMakeStackoverflowError.java
  at com.puppycrawl.tools.checkstyle.Checker.processFiles(Checker.java:319)
  at com.puppycrawl.tools.checkstyle.Checker.process(Checker.java:221)
  at org.apache.maven.plugins.checkstyle.exec.DefaultCheckstyleExecutor.executeCheckstyle(DefaultCheckstyleExecutor.java:202)
  at org.apache.maven.plugins.checkstyle.AbstractCheckstyleReport.executeReport(AbstractCheckstyleReport.java:533)
  at org.apache.maven.plugins.checkstyle.CheckstyleReport.executeReport(CheckstyleReport.java:57)
  at org.apache.maven.reporting.AbstractMavenReport.generate(AbstractMavenReport.java:255)
  at org.apache.maven.plugins.site.ReportDocumentRenderer.renderDocument(ReportDocumentRenderer.java:219)
  at org.apache.maven.doxia.siterenderer.DefaultSiteRenderer.renderModule(DefaultSiteRenderer.java:319)
  at org.apache.maven.doxia.siterenderer.DefaultSiteRenderer.render(DefaultSiteRenderer.java:135)
  at org.apache.maven.plugins.site.SiteMojo.renderLocale(SiteMojo.java:175)
  at org.apache.maven.plugins.site.SiteMojo.execute(SiteMojo.java:138)
  at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
  at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:210)
  at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156)
  at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148)
  at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
  at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
  at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
  at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
  at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
  at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
  at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
  at org.apache.maven.cli.MavenCli.execute(MavenCli.java:957)
  at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:289)
  at org.apache.maven.cli.MavenCli.main(MavenCli.java:193)
  at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.base/java.lang.reflect.Method.invoke(Method.java:566)
  at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:282)
  at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:225)
  at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:406)
  at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)
Caused by: java.lang.StackOverflowError
  at com.puppycrawl.tools.checkstyle.checks.whitespace.ParenPadCheck.processExpression(ParenPadCheck.java:350)
......
  at com.puppycrawl.tools.checkstyle.checks.whitespace.ParenPadCheck.processExpression(ParenPadCheck.java:353)
  at com.puppycrawl.tools.checkstyle.checks.whitespace.ParenPadCheck.processExpression(ParenPadCheck.java:353)
Caught: groovy.lang.GroovyRuntimeException: Error: !
groovy.lang.GroovyRuntimeException: Error: !
  at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
  at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
  at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
  at launch.executeCmd(launch.groovy:329)
  at launch.executeCmd(launch.groovy:322)
  at launch$executeCmd$3.callCurrent(Unknown Source)
  at launch.runMavenExecution(launch.groovy:246)
  at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at launch$_generateCheckstyleReport_closure2.doCall(launch.groovy:97)
  at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at launch.generateCheckstyleReport(launch.groovy:72)
  at launch$generateCheckstyleReport$1.callCurrent(Unknown Source)
  at launch.run(launch.groovy:10)
  at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
```

strange and looks unrelated.
restarted.

**Comment by Abhishek-kumar09** [comment]
@romani  Other issues are due to issue not approved.

**Comment by romani** [comment]
@Abhishek-kumar09 , please update issue description as I requested, and I will put approval label.
It will be very helpful for second reviewer.

File: src/test/java/com/puppycrawl/tools/checkstyle/checks/indentation/IndentationCheckTest.java (hunk 1 above)
Comment (romani) [reply src/test/java/com/puppycrawl/tools/checkstyle/checks/indentation/IndentationCheckTest.java:1139]: @Abhishek-kumar09 , please do

**Comment by romani** [comment]
@Abhishek-kumar09 , please provide diff report, as last point before merge, to be completely sure there is no regression.

**Comment by Abhishek-kumar09** [comment]
Github, generate report

File: src/test/java/com/puppycrawl/tools/checkstyle/checks/indentation/IndentationCheckTest.java (hunk 1 above)
Comment (Abhishek-kumar09) [reply src/test/java/com/puppycrawl/tools/checkstyle/checks/indentation/IndentationCheckTest.java]: really sorry for doing it late. 
Done.

**Comment by Abhishek-kumar09** [comment]
Github, generate report.

**Comment by Abhishek-kumar09** [comment]
Github, generate report

**Comment by romani** [comment]
reports looks good.

**Review by romani — APPROVED** [review]
ok to merge

**Review by pbludov — APPROVED** [review]

File: .ci/wercker.sh [hunk 2]
```diff
@@ -61,10 +61,10 @@ no-error-pgjdbc)
   CS_POM_VERSION=$(mvn -e -q -Dexec.executable='echo' -Dexec.args='${project.version}' \
                      --non-recursive org.codehaus.mojo:exec-maven-plugin:1.3.1:exec)
   echo CS_version: ${CS_POM_VERSION}
-  checkout_from https://github.com/pgjdbc/pgjdbc.git
+  checkout_from https://github.com/Abhishek-kumar09/pgjdbc.git
```
Comment (strkkk) [inline .ci/wercker.sh:64]: is this line should be like this? I think there should be no user forks

Comment (romani) [reply .ci/wercker.sh:64]: We can keep it for a little, as @Abhishek-kumar09 become frequent contributor.
PR to pgjdbc will be created after merge.

There are two updates to this project for indentation. So we will provide single PR to them.

**Review by strkkk — APPROVED** [review]
