### PR TITLE
Issue #9540: New property to allow emtpy switch cases in whitespaceAr…

### LINKED ISSUE #9540: WhitespaceAround on enhanced switch empty block
I have read check documentation: https://checkstyle.org/config_xxxxxx.html#NameOfAffectedCheck
I have downloaded the latest checkstyle from: https://checkstyle.org/cmdline.html#Download_and_Run
I have executed the cli and showed it below, as cli describes the problem better than 1,000 words

```bash
/var/tmp $ javac YOUR_FILE.java
#[[MAKE SURE THERE IS SUCCESSFUL COMPILATION]]
```

/var/tmp $ cat config.xml
```xml
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC "-//Puppy Crawl//DTD Check Configuration 1.3//EN"
        "http://checkstyle.sourceforge.net/dtds/configuration_1_3.dtd">

<?xml version="1.0"?>
<!DOCTYPE module PUBLIC "-//Puppy Crawl//DTD Check Configuration 1.3//EN"
        "http://checkstyle.sourceforge.net/dtds/configuration_1_3.dtd">

<module name="Checker">
    <property name="charset" value="UTF-8"/>
    <property name="haltOnException" value="true"/>
    <property name="severity" value="error"/>

    <module name="FileTabCharacter">
        <property name="eachLine" value="true"/>
    </module>
    <module name="NewlineAtEndOfFile"/>
    <module name="SuppressWarningsFilter"/>
    <module name="UniqueProperties"/>

    <module name="TreeWalker">
        <module name="SuppressWarningsHolder"/>

        <module name="WhitespaceAround">
            <property name="allowEmptyCatches" value="true"/>
            <property name="allowEmptyConstructors" value="true"/>
            <property name="allowEmptyMethods" value="true"/>
            <property name="allowEmptyLambdas" value="true"/>
            <property name="allowEmptyLoops" value="true"/>
            <property name="allowEmptyTypes" value="true"/>
            <property name="ignoreEnhancedForColon" value="false"/>
        </module>
    </module>
</module>
```

/var/tmp $ cat YOUR_FILE.java
```java
public class WhitespaceAround {
    private void switchTest() {
        switch ("foo") {
            case "A" -> {}
            case "B" -> System.out.println("B");
            default -> System.out.println("other");
        }
    }
}
```
/var/tmp $ RUN_LOCALE="-Duser.language=en -Duser.country=US"
/var/tmp $ java $RUN_LOCALE -jar checkstyle-X.XX-all.jar -c config.xml YOUR_FILE.java
```bash
Starting audit...
[ERROR] /private/var/tmp/WhitespaceAround.java:4:25: '{' is not followed by whitespace. [WhitespaceAround]
[ERROR] /private/var/tmp/WhitespaceAround.java:4:26: '}' is not preceded with whitespace. [WhitespaceAround]
Audit done.
Checkstyle ends with 2 errors.
```

For Windows users, please use `type` instead of `cat` and run

```cmd
set RUN_LOCALE="-Duser.language=en -Duser.country=US"
java %RUN_LOCALE% -jar checkstyle-X.XX-all.jar -c config.xml YOUR_FILE.java
```

in place of the last 2 commands above.

---
My expectation was that one of the allowEmpty* properties would stop the violation  on the line 
```java
case "A" -> {}
```

---

Still not clear ???
see example - https://checkstyle.org/report_issue.html#How_to_report_a_bug.3F

ATTENTION: FAILURE TO FOLLOW THE ABOVE TEMPLATE WILL RESULT IN THE ISSUE BEING CLOSED.

### PR DESCRIPTION
**Pull request by mahfouz72**
closes #9540 

Diff Regression config: https://gist.githubusercontent.com/mahfouz72/afd57aa6e51ca161b7927acd959e5211/raw/d7940108d4e9f8d3a89325a881212c12c0e6d3ac/check.xml

Diff Regression patch config: https://gist.githubusercontent.com/mahfouz72/33967bf86e4a29cafa429771b0e95808/raw/b8befd31e1674f8173133fc872ddabc912d445ab/check_patch.xml

Diff Regression projects: https://gist.githubusercontent.com/mahfouz72/297d7353d2d0bcec178e1b098109cd9e/raw/562a7e3ed6b091258b4f0f0603933e96d1938a87/projects-to-test-on.properties

### CODE REVIEW

**Comment by mahfouz72** [comment]
Github, generate report for WhitespaceAround/all-examples-in-one

**Comment by mahfouz72** [comment]
Github, generate report for WhitespaceAround/all-examples-in-one

**Comment by mahfouz72** [comment]
@romani do you have idea why the generation failed?

**Comment by rnveach** [comment]
```
[main] INFO com.github.checkstyle.difftool.DiffTool - Testing Checkstyle started
[main] ERROR com.github.checkstyle.difftool.DiffTool - Failed to create source directory: src/main/java
[main] ERROR com.github.checkstyle.difftool.DiffTool - Failed to create repository directory: repositories
...
[main] ERROR com.github.checkstyle.difftool.DiffTool - pom_template.xml not found in classpath.
[main] ERROR com.github.checkstyle.difftool.DiffTool - Error processing projects: Resource 'pom_template.xml' not found in classpath
...
[main] ERROR com.github.checkstyle.difftool.DiffTool - Error: reports/diff
```

This is the GSoC project. It is using a new AI translated groovy to Java program. It is concerning it runs through so many errors.

**Comment by romani** [comment]
Sorry, workflow is broken by recent update.
Please use old workflow trigger.

**Comment by relentless-pursuit** [comment]
> https://github.com/checkstyle/checkstyle/actions/runs/10997947902/job/30535766488#step:13:722
> 
> ```
> [main] ERROR com.github.checkstyle.difftool.DiffTool - pom_template.xml not found in classpath.
> [main] ERROR com.github.checkstyle.difftool.DiffTool - Error processing projects: Resource 'pom_template.xml' not found in classpath
> ...
> [main] INFO com.github.checkstyle.difftool.DiffTool - Testing Checkstyle started
> [main] ERROR com.github.checkstyle.difftool.DiffTool - Failed to create source directory: src/main/java
> [main] ERROR com.github.checkstyle.difftool.DiffTool - Failed to create repository directory: repositories
> ...
> [main] ERROR com.github.checkstyle.difftool.DiffTool - pom_template.xml not found in classpath.
> [main] ERROR com.github.checkstyle.difftool.DiffTool - Error processing projects: Resource 'pom_template.xml' not found in classpath
> ...
> [main] ERROR com.github.checkstyle.difftool.DiffTool - Error: reports/diff
> ```
> 
> This is the GSoC project. It is still a work in progress. It is using a new AI translated groovy to Java program.
> 
> It is concerning it runs through so many errors. https://github.com/checkstyle/test-configs/blob/main/diff-java-tool/src/main/java/com/github/checkstyle/difftool/DiffTool.java#L1418-L1428

There is an issue with release. Once, Romani is back, we can re-do the release and test it again. Any change to this repo is thouroughly tested in all the PRs and links to the tests and runner attached.

**Comment by relentless-pursuit** [comment]
And, @rnveach, it would be glad if you can participate in the reviews and test it once. I haven't seen you using the workflow once though. If you used, and had concerns, i would be happy to address any errors. I can assure the AI translated code has been doing it's job fine so far.

**Comment by rnveach** [comment]
> i would be glad if you can participate in the reviews and test it once.

I am not being allowed to seriously review anything, nor have there been any real attempts at a conversation.
https://github.com/checkstyle/checkstyle/discussions/15650

Me and another admin tried to assist in planning your project out, but we were denied and were told to let the mentor do whatever he wants.

>  I haven't seen you using the workflow once though. 

I have not used it. I do not really plan to in the future. I have my own little empire I have set up to do more and faster regression with multi-threading support. I don't mind having to create my own configs as I have been doing this for years.
https://github.com/rnveach/contribution/tree/rvmaster/checkstyle-tester

The last time I brought anything for this was when I was pointing out the lack of documentation and how to introduce users to it. Without good documentation, there is nothing to point users to on how to use it for the various purposes which are needed.

>  I can assure that the AI translated code has been doing it's job fine so far.

If we are given a chance to accept or reject this, which looks like we won't be given such a choice, I have a hard time accepting since it is done by AI. Since you don't understand what it does, otherwise I assume you wouldn't be using AI, we can't have any real certainty that it is doing things "fine". I already pointed to code above where it is printing out tons of errors, but is continuing on without caring. While those errors may be "false" because you aren't checking if the directory exists or not first, it is concerning that it isn't stopping the process. If it wasn't for something else finally failing, it could have gone through completely and turned green success. I think it should only be accepted if someone really looks it over, and I don't think anyone will want to do that on a program that big.

I will admit I have been using AI myself to do custom coding for languages I do not know, like bash, and explain the language some but I do know enough and have seen AI fail miserably in trying to write code. I may be fine to use it either to explain things to me, or do 1-off pieces no one will see, but I don't really feel it belongs in these type of places.

**Comment by romani** [comment]
@mahfouz72 , please use `OR as alternate` from https://github.com/checkstyle/test-configs/tree/main/WhitespaceAround/all-examples-in-one#all-examples-in-one-configs

**Comment by nrmancuso** [comment]
Let's keep the conversation here on topic, @rnveach @romani @relentless-pursuit please open a discussion for the test tool and move this there.

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/WhitespaceAroundCheck.java [hunk 1]
```diff
@@ -46,7 +46,8 @@
  * <p>
  * may optionally be exempted from the policy using the {@code allowEmptyMethods},
  * {@code allowEmptyConstructors}, {@code allowEmptyTypes}, {@code allowEmptyLoops},
- * {@code allowEmptyLambdas} and {@code allowEmptyCatches} properties.
+ * {@code allowEmptyLambdas}, {@code allowEmptyCatches}
+ * and {@code allowEmptySwitchCase} properties.
```
Comment (nrmancuso) [inline src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/WhitespaceAroundCheck.java:50]: The JLS should be our source of truth when referring to language elements. This property should be called `allowEmptySwitchBlock`. Please see https://docs.oracle.com/javase/specs/jls/se21/html/jls-14.html#jls-14.11.1

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/WhitespaceAroundCheck.java [hunk 2]
```diff
@@ -473,6 +481,16 @@ public void setAllowEmptyCatches(boolean allow) {
         allowEmptyCatches = allow;
     }
 
+    /**
+     * Setter to allow empty switch case and default bodies.
```
Comment (nrmancuso) [inline src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/WhitespaceAroundCheck.java:485]:
```suggestion
     * Setter to allow empty switch case and default blocks and block statements.
```

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/WhitespaceAroundCheck.java [hunk 3]
```diff
@@ -720,6 +739,32 @@ private boolean isEmptyCatch(DetailAST ast, int parentType) {
...
+                isEmptyBlock(ast, parent.getType(), TokenTypes.SWITCH_RULE);
+
+        final boolean isEmptyCaseGroupCheckedFromLcurly = isEmptyBlock(ast,
+                grandParent.getType(), TokenTypes.CASE_GROUP);
+
+        final boolean isEmptyCaseGroupCheckFromRcurly =
+                parent.getFirstChild().getType() == TokenTypes.RCURLY
+                  && grandParent.getParent().getType() == TokenTypes.CASE_GROUP;
+
+        return allowEmptySwitchCase && (isEmptyCaseInSwitchRule
```
Comment (nrmancuso) [inline src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/WhitespaceAroundCheck.java:764]: We should try to avoid all these other method calls if this property is false (i.e. delegate to another method or use predicates).

File: src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/whitespace/whitespacearound/InputWhitespaceAroundSwitchCasesParensWithAllowEmptySwitchCase.java
Comment (nrmancuso) [inline src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/whitespace/whitespacearound/InputWhitespaceAroundSwitchCasesParensWithAllowEmptySwitchCase.java:1]: Not just for this file/test case, please add the following cases where appropriate:
 - multiple empty blocks
 - multiple line empty blocks
 - block with only a empty statement inside `{;}`
 - nested empty blocks `{{{}}}`

**Review by nrmancuso — CHANGES_REQUESTED** [review]
Please correct the spelling in the commit message and PR title.

Items:

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/WhitespaceAroundCheck.java (hunk 1 above)
Comment (mahfouz72) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/WhitespaceAroundCheck.java:50]: > The body of both a switch statement and a switch expression ([§15.28](https://docs.oracle.com/javase/specs/jls/se21/html/jls-15.html#jls-15.28)) is called a switch block.

I think this name means `switch(x) {}` not 
```
switch(x) {
  case 1: {}
}
```
`allowEmptySwitchLabel` ?

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/WhitespaceAroundCheck.java (hunk 2 above)
Comment (mahfouz72) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/WhitespaceAroundCheck.java:485]: I started with this wording but then I decided to change it to keep consistency with the other properties (all have the word "bodies"). What do you think?

```
    /** Allow empty constructor bodies. */
    private boolean allowEmptyConstructors;
    /** Allow empty method bodies. */
    private boolean allowEmptyMethods;
    /** Allow empty class, interface and enum bodies. */
    private boolean allowEmptyTypes;
    /** Allow empty loop bodies. */
    private boolean allowEmptyLoops;
    /** Allow empty lambda bodies. */
    private boolean allowEmptyLambdas;
    /** Allow empty catch bodies. */
    private boolean allowEmptyCatches;
    /** Allow empty switch case and default bodies. */
    private boolean allowEmptySwitchCase;
```

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/WhitespaceAroundCheck.java (hunk 1 above)
Comment (nrmancuso) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/WhitespaceAroundCheck.java:50]: The token that represents `{}` is called either a block (for -> switch) or block statement (for traditional : ).

File: src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/whitespace/whitespacearound/InputWhitespaceAroundSwitchCasesParensWithAllowEmptySwitchCase.java
Comment (mahfouz72) [reply src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/whitespace/whitespacearound/InputWhitespaceAroundSwitchCasesParensWithAllowEmptySwitchCase.java:1]: done

**Comment by mahfouz72** [comment]
github, generate report

**Comment by relentless-pursuit** [comment]
> Report generation failed on phase "make_report", step "Generate report".Link: https://github.com/checkstyle/checkstyle/actions/runs/11021043956

https://github.com/checkstyle/test-configs/issues/141

We saw this OOM issue while testing. The regression-report.yml is back to normal, but won't help much in this case as it will continue to lead to OOM.

**Comment by nrmancuso** [comment]
@mahfouz72 we can generate two separate reports: one with all projects except openjdk, and one with only openjdk, to help avoid OOM.

**Comment by mahfouz72** [comment]
github, generate report

**Comment by mahfouz72** [comment]
github, generate report

**Comment by mahfouz72** [comment]
github, generate site

**Comment by romani** [comment]
Github, generate report for WhitespaceAround/all-examples-in-one

**Comment by romani** [comment]
GitHub, generate report by config from src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/whitespace/whitespacearound/InputWhitespaceAroundSwitchCasesParensWithAllowEmptySwitchBlockStatements.java

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/WhitespaceAroundCheck.java (hunk 2 above)
Comment (nrmancuso) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/WhitespaceAroundCheck.java:485]: It's not that big a deal, but I would prefer being "correct" than consistent in this case. Up to you.

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/WhitespaceAroundCheck.java [hunk 4]
```diff
@@ -720,6 +739,38 @@ private boolean isEmptyCatch(DetailAST ast, int parentType) {
...
+
+            final boolean isEmptyCaseInSwitchRule =
+                    isEmptyBlock(ast, parent.getType(), TokenTypes.SWITCH_RULE);
+
+            final boolean isEmptyCaseGroupCheckedFromLcurly = isEmptyBlock(ast,
+                    grandParent.getType(), TokenTypes.CASE_GROUP);
+
+            final boolean isEmptyCaseGroupCheckFromRcurly =
+                    parent.getFirstChild().getType() == TokenTypes.RCURLY
+                      && grandParent.getParent().getType() == TokenTypes.CASE_GROUP;
```
Comment (nrmancuso) [inline src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/WhitespaceAroundCheck.java:765]: Help me to understand what these are, it is not obvious why we should care about from lcurly, rcurly.

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/WhitespaceAroundCheck.java [hunk 5]
```diff
@@ -720,6 +739,38 @@ private boolean isEmptyCatch(DetailAST ast, int parentType) {
...
+    /**
+     * Tests if the given {@code DetailAst} is part of an allowed empty
+     * switch case or default block.
+     *
+     * @param ast the {@code DetailAst} to test.
+     * @return {@code true} if {@code ast} makes up part of an allowed
+     *         empty switch case or default block.
+     */
+    private boolean isEmptySwitchBlockStatement(DetailAST ast) {
+        boolean isEmptySwitchBlockStatement = false;
```
Comment (nrmancuso) [inline src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/WhitespaceAroundCheck.java:751]: We should be avoiding a mutable variable here, I don't think there is any real need for this to be mutable.

File: src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/whitespace/whitespacearound/InputWhitespaceAroundSwitchCasesParensWithAllowEmptySwitchBlockStatements.java
Comment (nrmancuso) [inline src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/whitespace/whitespacearound/InputWhitespaceAroundSwitchCasesParensWithAllowEmptySwitchBlockStatements.java:1]: Test cases look good, thank you.

**Review by nrmancuso — CHANGES_REQUESTED** [review]
Few more things to consider:

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/WhitespaceAroundCheck.java (hunk 4 above)
Comment (mahfouz72) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/WhitespaceAroundCheck.java:765]: The default implementation of `isEmptyBlock()` [when we have a `RCURLY` is to check that the grandparent is equal to the token we want to match with it](https://github.com/checkstyle/checkstyle/blob/f187bc86640851d6bde1dc81a8fce49d0069dff1/src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/WhitespaceAroundCheck.java#L642-L644) (which is `CASE_GROUP` in this example). 


        |       |   |--CASE_GROUP -> CASE_GROUP [5:12]
        |       |   |   |--LITERAL_CASE -> case [5:12]
        |       |   |   |   |--EXPR -> EXPR [5:17]
        |       |   |   |   |   `--NUM_INT -> 4 [5:17]
        |       |   |   |   `--COLON -> : [5:18]
        |       |   |   `--SLIST -> SLIST [5:20]         <------- grandparent but we need to match with case groupt
        |       |   |       `--SLIST -> { [5:20]
        |       |   |           `--RCURLY -> } [5:21]


So I had to make a custom implementation for this special case and check the parent of the grand parent   `grandParent.getParent().getType() == TokenTypes.CASE_GROUP;`



In the `SLIST` part [we just check that the second and the third arguments are equal](https://github.com/checkstyle/checkstyle/blob/f187bc86640851d6bde1dc81a8fce49d0069dff1/src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/WhitespaceAroundCheck.java#L647-L649) and [we are sure that this will be true because I am passing the grandparent as the second parameter](https://github.com/checkstyle/checkstyle/blob/f187bc86640851d6bde1dc81a8fce49d0069dff1/src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/WhitespaceAroundCheck.java#L761)


In the case of `->` syntax, we don't have these exceptions because the grandparent of rcurly is `SWITCH_RULE` not that extra `SLIST`

```
        |       |   |--SWITCH_RULE -> SWITCH_RULE [8:12]
        |       |   |   |--LITERAL_CASE -> case [8:12]
        |       |   |   |   `--EXPR -> EXPR [8:17]
        |       |   |   |       `--NUM_INT -> 3 [8:17]
        |       |   |   |--LAMBDA -> -> [8:19]
        |       |   |   `--SLIST -> { [8:22]
        |       |   |       `--RCURLY -> } [8:23]

```

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/WhitespaceAroundCheck.java (hunk 5 above)
Comment (mahfouz72) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/WhitespaceAroundCheck.java]: done

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/WhitespaceAroundCheck.java (hunk 4 above)
Comment (nrmancuso) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/WhitespaceAroundCheck.java:765]: Thanks for the explanation, I was hoping to think of a better name here, but nothing comes to mind 😂let’s roll with it

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/WhitespaceAroundCheck.java [hunk 6]
```diff
@@ -102,6 +103,11 @@
  * Default value is {@code false}.
  * </li>
  * <li>
+ * Property {@code allowEmptySwitchBlockStatements} - Allow empty switch case and default bodies.
```
[the remark this answers is not in the document]
Comment (nrmancuso) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/WhitespaceAroundCheck.java:106]: @mahfouz72 ping

[the remark this answers is not in the document]
Comment (mahfouz72) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/WhitespaceAroundCheck.java]: done

**Review by nrmancuso — APPROVED** [review]

**Comment by romani** [comment]
GitHub, generate report by config from src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/whitespace/whitespacearound/InputWhitespaceAroundSwitchCasesParensWithAllowEmptySwitchBlockStatements.java

File: src/xdocs/checks/whitespace/whitespacearound.xml [hunk 7]
```diff
@@ -108,6 +109,13 @@ try {
               <td><code>false</code></td>
               <td>4.0</td>
             </tr>
+            <tr>
+              <td>allowEmptySwitchBlockStatements</td>
+              <td>Allow empty switch blocks and block statements.</td>
+              <td><a href="../../property_types.html#boolean">boolean</a></td>
+              <td><code>false</code></td>
+              <td>10.18.2</td>
```
Comment (romani) [inline src/xdocs/checks/whitespace/whitespacearound.xml:117]: Please bump version.
https://checkstyle.org/releasenotes.html#Release_10.18.2

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/WhitespaceAroundCheck.java [hunk 8]
```diff
@@ -720,6 +740,41 @@ private boolean isEmptyCatch(DetailAST ast, int parentType) {
...
+        if (allowEmptySwitchBlockStatements) {
+            final DetailAST parent = ast.getParent();
+            final DetailAST grandParent = parent.getParent();
+
+            final boolean isEmptyCaseInSwitchRule =
+                    isEmptyBlock(ast, parent.getType(), TokenTypes.SWITCH_RULE);
+
+            final boolean isEmptyCaseGroupCheckedFromLcurly = isEmptyBlock(ast,
+                    grandParent.getType(), TokenTypes.CASE_GROUP);
+
```
Comment (romani) [inline src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/WhitespaceAroundCheck.java:763]:
```
final boolean isEmptyCaseGroupCheckedFromLcurly =
            isEmptyBlock(ast, grandParent.getType(), TokenTypes.CASE_GROUP);
```

To match previous statement in view.

**Review by romani — CHANGES_REQUESTED** [review]
Items

**Comment by romani** [comment]
Github, generate report for configs in PR description

**Comment by romani** [comment]
github, generate report

**Comment by romani** [comment]
Github, generate report for configs in PR description

**Comment by romani** [comment]
Github, generate report for configs in PR description

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/WhitespaceAroundCheck.java (hunk 8 above)
Comment (mahfouz72) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/WhitespaceAroundCheck.java:763]: done

File: src/xdocs/checks/whitespace/whitespacearound.xml (hunk 7 above)
Comment (mahfouz72) [reply src/xdocs/checks/whitespace/whitespacearound.xml]: done

**Review by romani — APPROVED** [review]
Ok to merge if CI pass

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/WhitespaceAroundCheck.java [hunk 9]
```diff
@@ -473,6 +482,16 @@ public void setAllowEmptyCatches(boolean allow) {
         allowEmptyCatches = allow;
     }
 
+    /**
+     * Setter to allow empty switch blocks and block statements.
+     *
+     * @param allow {@code true} to allow empty switch case and default blocks.
+     * @since 10.18.3
```
Comment (romani) [inline src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/WhitespaceAroundCheck.java:489]: New property can not be bumped in bug fix version.
We need 10.19

**Review by romani — CHANGES_REQUESTED** [review]
Almost missed

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/WhitespaceAroundCheck.java (hunk 9 above)
Comment (mahfouz72) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/WhitespaceAroundCheck.java]: done

**Review by romani — APPROVED** [review]

**Comment by romani** [comment]
We running low on maintainers ability to review.
I am merging PR.
