### PR TITLE
Issue #17167: fp when switch is not wrapped

### LINKED ISSUE #17167: checkstyle expects different indentation for switch cases.
Hi, this is essentially a duplicate of #17163 I just tried to make it as minimal as possible.

```bash
/var/tmp $ javac YOUR_FILE.java
Yes it compiles

/var/tmp $ cat config.xml
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
  "-//Checkstyle//DTD Checkstyle Configuration 1.3//EN"
  "https://checkstyle.org/dtds/configuration_1_3.dtd">
<module name="Checker">
  <module name="TreeWalker">
    <property name="skipFileOnJavaParseException" value="true"/>
    <property name="javaParseExceptionSeverity" value="info"/>
    <module name="Indentation">
      <property name="basicOffset" value="2"/>
      <property name="braceAdjustment" value="0"/>
      <property name="caseIndent" value="2"/>
      <property name="throwsIndent" value="2"/>
      <property name="lineWrappingIndentation" value="2"/>
      <property name="arrayInitIndent" value="2"/>
    </module>
  </module>
  <property name="fileExtensions" value="java, properties, xml"/>
  <property name="charset" value="UTF-8"/>
  <property name="severity" value="warning"/>
</module>


/var/tmp $ cat YOUR_FILE.java
package de.playo;

import java.lang.reflect.Proxy;

public class Main {

  public static void main(String[] args0) {
    var serviceAFakeInstance = (String) Proxy.newProxyInstance(
      null,
      new Class[]{String.class},
      (proxy, method, args) -> switch (method.getName()) {
        case "hashCode" -> 123456789;
        case "equals" -> args[0] == proxy;
        case "toString" -> "FakeInstanceServiceA";
        default -> throw new IllegalArgumentException(method.getName());
      });
    System.out.println(serviceAFakeInstance);
  }
}


/var/tmp $ RUN_LOCALE="-Duser.language=en -Duser.country=US"
/var/tmp $ java $RUN_LOCALE -jar checkstyle-X.XX-all.jar -c config.xml YOUR_FILE.java
Starting audit...
[WARN] C:\Users\A\IdeaProjects\checkstyle-test\.\src\main\java\de\playo\Main.java:12:9: 'case' child has incorrect indentation level 8, expected level should be 10. [Indentation]
[WARN] C:\Users\A\IdeaProjects\checkstyle-test\.\src\main\java\de\playo\Main.java:13:9: 'case' child has incorrect indentation level 8, expected level should be 10. [Indentation]
[WARN] C:\Users\A\IdeaProjects\checkstyle-test\.\src\main\java\de\playo\Main.java:14:9: 'case' child has incorrect indentation level 8, expected level should be 10. [Indentation]
[WARN] C:\Users\A\IdeaProjects\checkstyle-test\.\src\main\java\de\playo\Main.java:15:9: 'case' child has incorrect indentation level 8, expected level should be 10. [Indentation]
[WARN] C:\Users\A\IdeaProjects\checkstyle-test\.\src\main\java\de\playo\Main.java:16:7: 'switch rcurly' has incorrect indentation level 6, expected level should be 8. [Indentation]
Audit done.

```

**Describe what you expect in detail.**
The indentation looks fine to me and adding two more levels does not look right. This config worked before 10.24.X

### PR DESCRIPTION
**Pull request by Aziz-755**
fixes #17167

### CODE REVIEW

**Comment by Aziz-755** [comment]
Github, generate report for Indentation/all-examples-in-one

**Comment by romani** [comment]
@0utplay, 
Can you help us validate that this fix actually covers all your problems.

To build jar from this PR, please read https://github.com/checkstyle/checkstyle/pull/17135#issuecomment-2970252097

Thanks s lot in advance

**Comment by Aziz-755** [comment]
The fix is not done, I still need to do some work. I'll do it ASAP

**Comment by 0utplay** [comment]
Hi, just give me another ping and I will test it :)

**Comment by Aziz-755** [comment]
Github, generate report for Indentation/all-examples-in-one

**Comment by Aziz-755** [comment]
Github, generate report for Indentation/all-examples-in-one

**Comment by Aziz-755** [comment]
Fix is ready for testing.
@0utplay could you please validate that the fix covers all your problems. Thanks!

File: src/it/resources-noncompilable/com/google/checkstyle/test/chapter4formatting/rule4841indentation/InputLambdaAndChildOnTheSameLine.java [hunk 1]
```diff
@@ -0,0 +1,65 @@
...
+        case B3 -> r != R.R1;
+        case B4 -> false;
+        case B5 -> throw new IllegalStateException("Unexpected: " + b);
+      };
+      case A2, A3 ->
+          switch (b) {
+            case B1 -> r.isOk();
+            case B2, B3 -> false;
+            case B4 -> true;
+            case B5 -> throw new RuntimeException("Oops: " + b);
```
Comment (romani) [inline src/it/resources-noncompilable/com/google/checkstyle/test/chapter4formatting/rule4841indentation/InputLambdaAndChildOnTheSameLine.java]: Please use some English word to avoid dealing with spelling

File: src/it/resources-noncompilable/com/google/checkstyle/test/chapter4formatting/rule4841indentation/InputLambdaAndChildOnTheSameLineCorrect.java
Comment (romani) [inline src/it/resources-noncompilable/com/google/checkstyle/test/chapter4formatting/rule4841indentation/InputLambdaAndChildOnTheSameLineCorrect.java:1]: Not sure why we need this file.
src/it/resources-noncompilable/com/google/checkstyle/test/chapter4formatting/rule4841indentation/InputLambdaAndChildOnTheSameLine.java already has no violations.
We usually add Correct file in case sibling has violations, and it needs  to be excluded from formatter.
Please add violations to src/it/resources-noncompilable/com/google/checkstyle/test/chapter4formatting/rule4841indentation/InputLambdaAndChildOnTheSameLine.java or just remove src/it/resources-noncompilable/com/google/checkstyle/test/chapter4formatting/rule4841indentation/InputLambdaAndChildOnTheSameLineCorrect.java

**Review by romani — CHANGES_REQUESTED** [review]
Non functional tems

**Comment by romani** [comment]
@Aziz-755 , can you check behavior on trinodb
https://github.com/checkstyle/checkstyle/issues/17163#issuecomment-2953491406
Looks like we have access to their sources, and it is them reporting this issue initially.

We can add their codebase to our CI, no leak problems happening again, and no special reports required to trigger

**Comment by 0utplay** [comment]
> Fix is ready for testing. @0utplay could you please validate that the fix covers all your problems. Thanks!

Hi, I just tried all of our previous failures. These are now fixed. I could not validate that no new issues arose as we are using the gradle checkstyle plugin.

**Comment by Aziz-755** [comment]
> @Aziz-755 , can you check behavior on trinodb [#17163 (comment)](https://github.com/checkstyle/checkstyle/issues/17163#issuecomment-2953491406) Looks like we have access to their sources, and it is them reporting this issue initially.
> 
> We can add their codebase to our CI, no leak problems happening again, and no special reports required to trigger

I have checked the behavior on the reported [file](https://github.com/trinodb/trino/blob/3da377228dd6f7a05eda7e9216407bff59099919/core/trino-spi/src/main/java/io/trino/spi/function/ScalarFunctionAdapter.java#L166 ) and the false positives are gone. 

If testing checkstyle on the whole project is needed could you please share a guide how can I run checkstyle on a project ? ( I am only familiar with a single file 😅 )

File: src/it/resources-noncompilable/com/google/checkstyle/test/chapter4formatting/rule4841indentation/InputLambdaAndChildOnTheSameLine.java (hunk 1 above)
Comment (Aziz-755) [reply src/it/resources-noncompilable/com/google/checkstyle/test/chapter4formatting/rule4841indentation/InputLambdaAndChildOnTheSameLine.java]: Done

File: src/it/resources-noncompilable/com/google/checkstyle/test/chapter4formatting/rule4841indentation/InputLambdaAndChildOnTheSameLineCorrect.java
Comment (Aziz-755) [reply src/it/resources-noncompilable/com/google/checkstyle/test/chapter4formatting/rule4841indentation/InputLambdaAndChildOnTheSameLineCorrect.java:1]: Thanks for the explanation! I have deleted src/it/resources-noncompilable/com/google/checkstyle/test/chapter4formatting/rule4841indentation/InputLambdaAndChildOnTheSameLineCorrect.java

**Comment by romani** [comment]
Example for other projects 
https://github.com/checkstyle/checkstyle/commit/57962fa01580dbafcb87492b7f1e4f398f37c825

Version override looks like possible at 
https://github.com/trinodb/trino/blob/b4b2d9a3d285efca71298acea8f181d775b964bd/pom.xml#L190

**Comment by Aziz-755** [comment]
I tested the changes on the TrinoDB project. I ran Checkstyle 10.25.0 (before the changes) and Checkstyle 10.25.1-SNAPSHOT-all (after the changes) using the following two commands:

```
D:\Working on Checkstyle>java -jar checkstyle-10.25.1-SNAPSHOT-all.jar -c config.xml trino\ > outputUsing-checkstyle-10.25.1-SNAPSHOT-all

D:\Working on Checkstyle>java -jar checkstyle-10.25.0-all.jar -c config.xml trino\ > outputUsing-checkstyle-10.25.0-all
``` 
[outputUsing-checkstyle-10.25.0-all.txt](https://github.com/user-attachments/files/20785368/outputUsing-checkstyle-10.25.0-all.txt)
[outputUsing-checkstyle-10.25.1-SNAPSHOT-all.txt](https://github.com/user-attachments/files/20785369/outputUsing-checkstyle-10.25.1-SNAPSHOT-all.txt)

You can find the output files attached. All false positives related to this issue have been removed. I also noticed the presence of other violations related to `switch `statements, and in my opinion, they are valid.
