### PR TITLE
Issue #9142: finalize

### LINKED ISSUE #9142: Infra: migrate to Truth in tests
We [agreed](https://github.com/checkstyle/checkstyle/issues/7239#issuecomment-560147839) to use [Truth](https://github.com/google/truth) in tests. It is more readable and produces better diffs on failure.

This is how a regular unit test should be written:
```java
    @Test
    public void testFomeMethod() {
        assertWithMessage("Human-readable assertion")
            .that(someClass.method(arg1, arg2))
            .isTrue()
            .contains(...)
            .isInstanceOf(...)
    }
```
Assertion starts with `assertWithMessage(...)`, followed by `that` and number of [assertions](https://truth.dev/benefits#readable-assertions).

For asserting exceptions:

```java
    @Test
    public void testMethodThrowsException() {
        final SomeExceptionType exception =  assertThrows(SomeExceptionType.class, () -> {
            someClass.someMethod(args);
        });
        assertWithMessage("Invalid exception message")
            .that(exception)
            .hasMessageThat()
                .isEqualTo("The expected message");
        assertWithMessage("Invalid inner exception")
            .that(exception)
            .hasCauseThat()
                .isInstanceOf(...)
                .hasMessageThat()
                    ...;
    }
```

### PR DESCRIPTION
**Pull request by rnveach**
Closes #9142

Doing a search on `org.junit.jupiter.api.Assertions` only provides the following results:
````
M:\checkstyleWorkspace\checkstyle\src\test\java\com\puppycrawl\tools\checkstyle\ant\CheckstyleAntTaskTest.java (1 hit)
	Line 23: import static org.junit.jupiter.api.Assertions.assertThrows;
  M:\checkstyleWorkspace\checkstyle\src\test\java\com\puppycrawl\tools\checkstyle\checks\header\HeaderCheckTest.java (1 hit)
	Line 25: import static org.junit.jupiter.api.Assertions.assertThrows;
  M:\checkstyleWorkspace\checkstyle\src\test\java\com\puppycrawl\tools\checkstyle\checks\imports\ImportControlLoaderTest.java (1 hit)
	Line 23: import static org.junit.jupiter.api.Assertions.assertThrows;
  M:\checkstyleWorkspace\checkstyle\src\test\java\com\puppycrawl\tools\checkstyle\checks\javadoc\AbstractJavadocCheckTest.java (1 hit)
	Line 30: import static org.junit.jupiter.api.Assertions.assertDoesNotThrow;
  M:\checkstyleWorkspace\checkstyle\src\test\java\com\puppycrawl\tools\checkstyle\checks\regexp\RegexpOnFilenameCheckTest.java (1 hit)
	Line 25: import static org.junit.jupiter.api.Assertions.assertThrows;
  M:\checkstyleWorkspace\checkstyle\src\test\java\com\puppycrawl\tools\checkstyle\ConfigurationLoaderTest.java (1 hit)
	Line 23: import static org.junit.jupiter.api.Assertions.assertThrows;
  M:\checkstyleWorkspace\checkstyle\src\test\java\com\puppycrawl\tools\checkstyle\DefaultLoggerTest.java (1 hit)
	Line 23: import static org.junit.jupiter.api.Assertions.assertThrows;
  M:\checkstyleWorkspace\checkstyle\src\test\java\com\puppycrawl\tools\checkstyle\PropertyCacheFileTest.java (1 hit)
	Line 23: import static org.junit.jupiter.api.Assertions.assertThrows;
  M:\checkstyleWorkspace\checkstyle\src\test\java\com\puppycrawl\tools\checkstyle\utils\ChainedPropertyUtilTest.java (1 hit)
	Line 24: import static org.junit.jupiter.api.Assertions.assertThrows;
  M:\checkstyleWorkspace\checkstyle\src\test\java\com\puppycrawl\tools\checkstyle\utils\CommonUtilTest.java (1 hit)
	Line 25: import static org.junit.jupiter.api.Assertions.assertThrows;
  M:\checkstyleWorkspace\checkstyle\src\test\java\com\puppycrawl\tools\checkstyle\xpath\AttributeNodeTest.java (1 hit)
	Line 23: import static org.junit.jupiter.api.Assertions.assertThrows;
````

### CODE REVIEW

File: src/test/java/com/puppycrawl/tools/checkstyle/filters/SuppressionsLoaderTest.java [hunk 1]
```diff
@@ -75,7 +73,9 @@ public void testLoadFromUrl() throws Exception {
             }
         }
 
-        assumeTrue(actualFilterSet != null, "No Internet connection.");
```
Comment (pbludov) [inline src/test/java/com/puppycrawl/tools/checkstyle/filters/SuppressionsLoaderTest.java:78]: assumeXXX should not be replaced with an assert.
This test requires an internet connection, which may not be available.
This can be replaced with `if`, but an `assume` method is better, since it will output the reason to the tests log.

File: src/test/java/com/puppycrawl/tools/checkstyle/DefaultLoggerTest.java [hunk 2]
```diff
@@ -223,7 +222,9 @@ public void testFinishLocalSetup() {
     @Test
     public void testLanguageIsValid() {
         final String language = DEFAULT_LOCALE.getLanguage();
-        assumeFalse(language.isEmpty(), "Locale not set");
+        assertWithMessage("Locale not set")
```
Comment (pbludov) [inline src/test/java/com/puppycrawl/tools/checkstyle/DefaultLoggerTest.java:225]: same

File: src/test/java/com/puppycrawl/tools/checkstyle/DefaultLoggerTest.java [hunk 3]
```diff
@@ -235,7 +236,9 @@ public void testLanguageIsValid() {
     @Test
     public void testCountryIsValid() {
         final String country = DEFAULT_LOCALE.getCountry();
-        assumeFalse(country.isEmpty(), "Locale not set");
+        assertWithMessage("Locale not set")
```
Comment (pbludov) [inline src/test/java/com/puppycrawl/tools/checkstyle/DefaultLoggerTest.java:239]: same

File: src/test/java/com/puppycrawl/tools/checkstyle/DefaultLoggerTest.java [hunk 4]
```diff
@@ -248,8 +251,9 @@ public void testCountryIsValid() {
     @Test
     public void testLocaleIsSupported() throws Exception {
         final String language = DEFAULT_LOCALE.getLanguage();
-        assumeFalse(language.isEmpty() || Locale.ENGLISH.getLanguage().equals(language),
-                "Custom locale not set");
+        assertWithMessage("Custom locale not set")
```
Comment (pbludov) [inline src/test/java/com/puppycrawl/tools/checkstyle/DefaultLoggerTest.java:254]: same

**Review by pbludov — CHANGES_REQUESTED** [review]

File: src/test/java/com/puppycrawl/tools/checkstyle/filters/SuppressionsLoaderTest.java (hunk 1 above)
Comment (rnveach) [reply src/test/java/com/puppycrawl/tools/checkstyle/filters/SuppressionsLoaderTest.java:78]: I am not understanding why it can't be replaced. Can you provide clarification on why we can't use assume here?

File: config/import-control-test.xml [hunk 5]
```diff
@@ -17,7 +17,9 @@
   <!-- Disallow hamcrest and only allow Truth -->
   <disallow pkg="org.hamcrest.CoreMatchers"/>
   <disallow pkg="org.hamcrest.MatcherAssert"/>
-  <!-- until https://github.com/checkstyle/checkstyle/issues/9142 -->
+  <!-- Disallow most assertions for Truth -->
+  <allow class="org.junit.jupiter.api.Assertions.assertThrows"/>
```
Comment (romani) [inline config/import-control-test.xml:21]: My English is not good to read it properly.
What about
`Disallow Junit assert in favor of Truth asserts in few exceptions`

Comment (rnveach) [reply config/import-control-test.xml:21]: Done.

**Review by romani — APPROVED** [review]

File: src/it/java/org/checkstyle/base/AbstractItModuleTestSupport.java [hunk 6]
```diff
@@ -251,22 +250,28 @@ protected final void verify(Checker checker,
             for (int i = 0; i < expected.length; i++) {
                 final String expectedResult = messageFileName + ":" + expected[i];
                 final String actual = lnr.readLine();
-                assertEquals(expectedResult, actual, "error message " + i);
+                assertWithMessage("error message " + i)
```
Comment (pbludov) [inline src/it/java/org/checkstyle/base/AbstractItModuleTestSupport.java:253]: It is better to use formatted message here: 
```java
assertWithMessage("error message %s", i)
```

File: src/it/java/org/checkstyle/base/AbstractItModuleTestSupport.java [hunk 7]
```diff
@@ -251,22 +250,28 @@ protected final void verify(Checker checker,
...
 
                 String parseInt = removeDeviceFromPathOnWindows(actual);
                 parseInt = parseInt.substring(parseInt.indexOf(':') + 1);
                 parseInt = parseInt.substring(0, parseInt.indexOf(':'));
                 final int lineNumber = Integer.parseInt(parseInt);
-                assertTrue(previousLineNumber == lineNumber
-                                || theWarnings.remove((Integer) lineNumber),
-                        "input file is expected to have a warning comment on line number "
-                                        + lineNumber);
+                assertWithMessage("input file is expected to have a warning comment on line number "
```
Comment (pbludov) [inline src/it/java/org/checkstyle/base/AbstractItModuleTestSupport.java:261]: same

File: src/it/java/org/checkstyle/base/AbstractItModuleTestSupport.java [hunk 8]
```diff
@@ -251,22 +250,28 @@ protected final void verify(Checker checker,
...
+                    .that(previousLineNumber == lineNumber
+                            || theWarnings.remove((Integer) lineNumber))
+                    .isTrue();
                 previousLineNumber = lineNumber;
             }
 
-            assertEquals(expected.length,
-                    errs, "unexpected output: " + lnr.readLine());
-            assertEquals(0, theWarnings.size(), "unexpected warnings " + theWarnings);
+            assertWithMessage("unexpected output: " + lnr.readLine())
```
Comment (pbludov) [inline src/it/java/org/checkstyle/base/AbstractItModuleTestSupport.java:269]: same

File: src/it/java/org/checkstyle/base/AbstractItModuleTestSupport.java [hunk 9]
```diff
@@ -251,22 +250,28 @@ protected final void verify(Checker checker,
...
+                .that(errs)
+                .isEqualTo(expected.length);
+            assertWithMessage("unexpected warnings " + theWarnings)
```
Comment (pbludov) [inline src/it/java/org/checkstyle/base/AbstractItModuleTestSupport.java:272]: same

File: src/test/java/com/puppycrawl/tools/checkstyle/utils/CheckUtilTest.java [hunk 10]
```diff
@@ -154,7 +153,8 @@ public void testGetAccessModifierFromModifiersTokenWrongTokenType() {
 
         try {
             CheckUtil.getAccessModifierFromModifiersToken(modifiers);
-            fail(IllegalArgumentException.class.getSimpleName() + " was expected.");
+            assertWithMessage(IllegalArgumentException.class.getSimpleName() + " was expected.")
```
Comment (pbludov) [inline src/test/java/com/puppycrawl/tools/checkstyle/utils/CheckUtilTest.java:156]: same

File: src/test/java/com/puppycrawl/tools/checkstyle/utils/CheckUtilTest.java [hunk 11]
```diff
@@ -452,9 +452,9 @@ private static DetailAST getNode(DetailAST root, int type) {
         final Optional<DetailAST> node = findTokenInAstByPredicate(root,
             ast -> ast.getType() == type);
 
-        if (!node.isPresent()) {
-            fail("Cannot find node of specified type: " + type);
-        }
+        assertWithMessage("Cannot find node of specified type: " + type)
```
Comment (pbludov) [inline src/test/java/com/puppycrawl/tools/checkstyle/utils/CheckUtilTest.java:455]: same

**Review by pbludov — CHANGES_REQUESTED** [review]
One minor change please

File: src/it/java/org/checkstyle/base/AbstractItModuleTestSupport.java (hunk 6 above)
Comment (rnveach) [reply src/it/java/org/checkstyle/base/AbstractItModuleTestSupport.java:253]: What is better about it? The readability or is there some performance?

Comment (pbludov) [reply src/it/java/org/checkstyle/base/AbstractItModuleTestSupport.java:253]: Both `assertWithMessage("error message %s", i)` and `assertWithMessage("error message " + i) have the same readability and performance.

The difference is that `"error message " + i` is actually `String.concat("error message "), i.toString())`. And this `.toString()' method can (in theory) have side effects. For example, it may throw an NPE, which will cause the test to fail for no clear reason.

This is absolutely inapplicable to any primitive type such as `int`, but this is a style issue. If we all agree to use this style, it will avoid possible problems in the future.

Comment (rnveach) [reply src/it/java/org/checkstyle/base/AbstractItModuleTestSupport.java:253]: What about https://github.com/checkstyle/checkstyle/pull/11151#discussion_r777310160 ?

File: src/test/java/com/puppycrawl/tools/checkstyle/filters/SuppressionsLoaderTest.java (hunk 1 above)
Comment (pbludov) [reply src/test/java/com/puppycrawl/tools/checkstyle/filters/SuppressionsLoaderTest.java]: false conditions in `assume` methods will not break the build. It simply reports that the test is ignored due to "Text".
false condition in `assert` methods will break the build.

**Comment by rnveach** [comment]
@pbludov all done

**Review by pbludov — APPROVED** [review]
