### PR TITLE
Issue #15263: Add conditional expressions flag to UnnecessaryParenthe…

### LINKED ISSUE #15263: UnnecessaryParenthesesCheck does not flag unnecessary parentheses in conditional expression
I have read check documentation: https://checkstyle.org/checks/coding/unnecessaryparentheses.html#UnnecessaryParentheses
I have downloaded the latest checkstyle from: https://checkstyle.org/cmdline.html#Download_and_Run
I have executed the cli and showed it below, as cli describes the problem better than 1,000 words

---

```
PS D:\CS\test> javac src/Test.java
PS D:\CS\test> cat config.xml
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
          "-//Checkstyle//DTD Checkstyle Configuration 1.3//EN"
          "https://checkstyle.org/dtds/configuration_1_3.dtd">

<module name="Checker">
  <property name="haltOnException" value="true"/>
  <module name="TreeWalker">
    <module name="UnnecessaryParentheses">
    </module>
  </module>
</module>
PS D:\CS\test> cat src/Test.java

public class Test {
    void test(int x) {
        boolean a = (x == 3); // violation
        boolean b = (!(x == 3)); // violation

        boolean c = (x == 3) ? (x == 3) : (!(x == 3));  // expected 3 violations
    }

}
PS D:\CS\test> java  -jar checkstyle-10.17.0-all.jar -c config.xml  src/Test.java
Starting audit...
[ERROR] D:\CS\test\src\Test.java:4:21: Unnecessary parentheses around assignment right-hand side. [UnnecessaryParentheses]
[ERROR] D:\CS\test\src\Test.java:5:21: Unnecessary parentheses around assignment right-hand side. [UnnecessaryParentheses]
Audit done.
Checkstyle ends with 2 errors.


```
---

**Describe what you expect in detail.**

`UnnecessaryParentheses` should flag unnecessary parentheses in conditional expressions. We should add `Question` to the acceptable tokens or something.

---

### PR DESCRIPTION
**Pull request by MohanadKh03**
fixes #15263 
Diff Regression config: https://gist.githubusercontent.com/MohanadKh03/62962eb95063d4cbbba210c35f9c56fe/raw/13b3d39dacefd54e6a3638f2920608d1616e570b/config.xml

### CODE REVIEW

**Comment by MohanadKh03** [comment]
GitHub, generate report

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnnecessaryParenthesesCheck.java [hunk 1]
```diff
@@ -386,6 +388,7 @@ public int[] getDefaultTokens() {
             TokenTypes.BNOT,
             TokenTypes.POST_INC,
             TokenTypes.POST_DEC,
+            TokenTypes.LPAREN,
```
Comment (mahfouz72) [inline src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnnecessaryParenthesesCheck.java:391]: IMO, adding `LPAREN` as an acceptable token to this check feels odd.  See all the tokens in this array, you will notice that they are operators. So, I expected the fix to be by adding `TokenTypes.QUESTION`, Have you tried this way?

Comment (MohanadKh03) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnnecessaryParenthesesCheck.java:391]: Honestly I tried both options yes but thought that there would be a problem with inner conditional expressions like `(a > b) ? //doSth1 : (c > d) ? //doSth2 : //doSth3`
But after visualizing the AST again turns out `Question` would still be a parent to an `LPAREN` even if it's an inner expression.
So I think it wouldnt matter both ways but you are right it's a bit odd to have `LPAREN` i should probably switch it to have `QUESTION` and check over its children to check if exists any 'LPAREN` then i'd log it.
 WDYT ?

Comment (mahfouz72) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnnecessaryParenthesesCheck.java:391]: `y == 3 ? (3) : (4) `  we have to think about paren in this example also. This will most likely get covered under `QUESTION` also

```
        |       |           `--QUESTION -> ? [3:25]
        |       |               |--LPAREN -> ( [3:16]
        |       |               |--EQUAL -> == [3:19]
        |       |               |   |--IDENT -> y [3:17]
        |       |               |   `--NUM_INT -> 3 [3:22]
        |       |               |--RPAREN -> ) [3:23]
        |       |               |--LPAREN -> ( [3:27]
        |       |               |--NUM_INT -> 3 [3:28]
        |       |               |--RPAREN -> ) [3:29]
        |       |               |--COLON -> : [3:31]
        |       |               |--LPAREN -> ( [3:33]
        |       |               |--NUM_INT -> 4 [3:34]
        |       |               `--RPAREN -> ) [3:35]
```

Comment (MohanadKh03) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnnecessaryParenthesesCheck.java:391]: > !(a>b) ? 3 : 4 
> In this example, this is not unnecessary parens.

I think this is not a problem because LPAREN will not be a direct child to QUESTION so it will not be caught as unnecessary parens

```
        |           `--QUESTION -> ? [3:17]
        |       |               |--LNOT -> ! [3:10]
        |       |               |   |--LPAREN -> ( [3:11]
        |       |               |   |--GT -> > [3:13]
        |       |               |   |   |--IDENT -> a [3:12]
        |       |               |   |   `--IDENT -> b [3:14]
        |       |               |   `--RPAREN -> ) [3:15]
        |       |               |--NUM_INT -> 3 [3:19]
        |       |               |--COLON -> : [3:21]
        |       |               `--NUM_INT -> 4 [3:23]
```
 
 > This will most likely get covered under QUESTION also
 
 
Yup it will not be a problem any direct LPAREN is always an unnecessary one **even if there is a ``!`` it will be the one directly below ``QUESTION``**

So do you think this is the appropriate way ? To check if there is a direct LPAREN child covererd below QUESTION ? IMO and as far as I have tried visualizing all the possible cases it's always the case , QUESTION -> LPAREN (direct child)

Comment (mahfouz72) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnnecessaryParenthesesCheck.java:391]: IMO, the best way to be sure is to code, create an input file with many edge cases, and run tests. This way everything will be more concrete and we can spot any gaps. we can always improve based on what we find.

Comment (MohanadKh03) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnnecessaryParenthesesCheck.java]: done 
Added QUESTION instead and covered its cases and also added a new input file , although a lot of the edge cases are covered in many files as well

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnnecessaryParenthesesCheck.java [hunk 2]
```diff
@@ -679,6 +688,31 @@ private static boolean isLambdaSingleParameterSurrounded(DetailAST ast) {
...
+            directChild = directChild.getNextSibling();
+        }
+        final List<DetailAST> surroundedChildren = new ArrayList<>();
+        for (DetailAST child : allChildren) {
+            if (child.getType() == TokenTypes.LPAREN
+                    && !TokenUtil.isOfType(child.getNextSibling(), LITERALS)) {
+                surroundedChildren.add(child);
+            }
+        }
+        return surroundedChildren;
```
Comment (mahfouz72) [inline src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnnecessaryParenthesesCheck.java:713]: Return it as `unmodifiableList` using `Collections.unmodifiableList(childern);`

File: src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/unnecessaryparentheses/InputUnnecessaryParenthesesConditionalExpression.java [hunk 3]
```diff
@@ -0,0 +1,31 @@
...
+package com.puppycrawl.tools.checkstyle.checks.coding.unnecessaryparentheses;
+
+public class InputUnnecessaryParenthesesConditionalExpression {
+    void method() {
+        int w = 5;
+        int x = (w == 3) ? (3) : (4);
+        // 3 violations above
+        //  'Unnecessary parentheses around expression'
+        //  'Unnecessary parentheses around expression'
+        //  'Unnecessary parentheses around expression'
```
Comment (mahfouz72) [inline src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/unnecessaryparentheses/InputUnnecessaryParenthesesConditionalExpression.java:23]: The last 2 messages should be: 
```
Unnecessary parentheses around literal '3'.
Unnecessary parentheses around literal '4'.
```

I think the messages content is not being checked by our parser because you missed `:` after `// 3 violations above`. It should be: 

```
        // 3 violations above:
        //                'Unnecessary parentheses around expression'
        //                'Unnecessary parentheses around literal '3'.
        //                'Unnecessary parentheses around literal '4'.
```

please fix all where possible

File: src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/unnecessaryparentheses/InputUnnecessaryParenthesesOperatorsAndCasts.java [hunk 4]
```diff
@@ -102,9 +108,7 @@ private void print(int arg)
 
     private int f7() {
         String f;
-
```
Comment (mahfouz72) [inline src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/unnecessaryparentheses/InputUnnecessaryParenthesesOperatorsAndCasts.java:105]: Most probably the next reviewer will ask you to revert these unrelated changes.

**Review by mahfouz72 — CHANGES_REQUESTED** [review]
Thanks, Direction is good 
Items

File: src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/unnecessaryparentheses/InputUnnecessaryParenthesesOperatorsAndCasts.java (hunk 4 above)
Comment (MohanadKh03) [reply src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/unnecessaryparentheses/InputUnnecessaryParenthesesOperatorsAndCasts.java:105]: Oh these are because of the 120 lines rule , It would get broken if they were reverted back

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnnecessaryParenthesesCheck.java [hunk 5]
```diff
@@ -679,6 +688,31 @@ private static boolean isLambdaSingleParameterSurrounded(DetailAST ast) {
...
+            allChildren.add(directChild);
+            directChild = directChild.getNextSibling();
+        }
+        final List<DetailAST> surroundedChildren = new ArrayList<>();
+        for (DetailAST child : allChildren) {
+            if (child.getType() == TokenTypes.LPAREN
+                    && !TokenUtil.isOfType(child.getNextSibling(), LITERALS)) {
+                surroundedChildren.add(child);
+            }
+        }
```
[the remark this answers is not in the document]
Comment (MohanadKh03) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnnecessaryParenthesesCheck.java]: done

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnnecessaryParenthesesCheck.java (hunk 2 above)
Comment (MohanadKh03) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnnecessaryParenthesesCheck.java]: done

File: src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/unnecessaryparentheses/InputUnnecessaryParenthesesConditionalExpression.java (hunk 3 above)
Comment (MohanadKh03) [reply src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/unnecessaryparentheses/InputUnnecessaryParenthesesConditionalExpression.java]: done

File: src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/unnecessaryparentheses/InputUnnecessaryParenthesesOperatorsAndCasts.java (hunk 4 above)
Comment (romani) [reply src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/unnecessaryparentheses/InputUnnecessaryParenthesesOperatorsAndCasts.java:105]: Thanks for sharing a reason.
I am ok to keep deletions, we are not extending Input with new code, but lines are growing due to more violations in file.

**Review by mahfouz72 — APPROVED** [review]
Thanks, but we still need to generate reports

**Comment by MohanadKh03** [comment]
GitHub, generate report

**Comment by romani** [comment]
We will wait for final repo

**Comment by MohanadKh03** [comment]
IMO it really is aggressive but isnt the point of the check is to rule out all unnecessary parentheses ? I think it is always subjective to like using parentheses in code for readability even if it , syntactically speaking , does not make a difference if there are parentheses or not

Like with using bitwise operators I think it's more readable to have brackets in this example 
``((a && b) || c))`` but this check still rules it as a violation because it should rule out the unnecessary checks **IMO unnecessary means in a way that does not affect the code if it's removed** 
This checks's strictness actually mentioned here https://github.com/checkstyle/checkstyle/issues/10946 before and I think it's kind of a tradeoff whether to have strict-unnecessary vs readability especially since it's really subjective but if we go full-unnecessary mode like how the bitwise operators is ruled out then i'd say we have to rule it out for conditional expressions as well

**Comment by MohanadKh03** [comment]
Hey @romani You closed/reopened at the same day so I was wondering WDYT is it too strict / aggressive to add ?

**Comment by romani** [comment]
It was inaccurate, pressing on phone. PR is still good. But unfortunately I lost track of it, thanks a lot for pinning. I will meditate for a bit, and will make decision on next 1-2 days. 

Please move forward, and choose other issue to contribute.

**Comment by romani** [comment]
> IMO it really is aggressive but isnt the point of the check is to rule out all unnecessary parentheses ? 

yes, it is goal of this Check. BUT there is default behavior and custom behavior.
default behavior is based on some subjective understanding of coding style, in most Checks default mode is not very aggressive.
In custom behavior users can do anything they want.
Check defines target  of validation by "tokens".

if users wants to activate this Checks, he will read more on it, to get maximum from it.
If user hesitant, better to not frustrate him on controversial cases, us he might simply disable whole Check. So by making default to be aggressive we potentially decrease usage of Check and can even "kill" it.

We can make example in xdoc pages on how to do this, so users will find it decently quickly.


---------

After looking at may case in diff report.
I see that most people like placing `()` on expression before `?`. It looks like help to parse by brain.

**I am voting for not placing this token `QUESTION` as default to this Check.**

@rnveach , @nrmancuso please vote.

One more exercise we can do to prove our subjective idea on default behavior.
In your report we see diff in pmd/spottbugs projects (team that is crazy about code quality) we can send PR to them and see it they accept it.
And people who are less crazy on quality - spring-integration .

if 2 out of 3 accept PR with removal of `()` it means we can do it as default and Check will be mostly welcomed by engineers.

**Comment by MohanadKh03** [comment]
@romani Pinging as a reminder of what's next ? Should we send the PR to pmd,spotbugs and spring-integration ?

**Comment by romani** [comment]
@rdiachenko , please share your opinion on how you like new behavior and if you agree to make it default.

@MohanadKh03 , please send PR to PMD or spotbugs, to test feedback.
you can fix not all cases in their code base, but several, you can share link to report with all to let them see whole picture.

**Comment by romani** [comment]
@MohanadKh03, of you have no time for extra PRs , let's trust my experience and just remove tokens from default and put example on how to enable such validation.
With this we will merge this PR quickly.

**Comment by MohanadKh03** [comment]
@romani Yeah my bad I didnt have time for exploring PMD/Spotbugs . Alright ill work on it and the examples should obviously include the token parameter right ?

**Comment by romani** [comment]
Yes. What is not enabled by default , is good to show users in examples. Users love examples.

**Comment by MohanadKh03** [comment]
Apologies I have made a mistake while rebasing .. Going to fix rn

**Comment by romani** [comment]
Please see commands and videos on how to change PR and rebase https://checkstyle.org/beginning_development.html#Starting_Development

**Comment by MohanadKh03** [comment]
Yes I did I just had problems with mixed old branches into my fork's master which messed things up. Apologies again for the CI spam

**Comment by romani** [comment]
Please always run `mvn clean verify ` on your local before pushing.
It catching most frequent issues. It will speedup collaboration, less pressure on CI

**Comment by MohanadKh03** [comment]
Ah yes I did so .. the first CI problem was due to having been far away from master that is why there was a mess in rebasing

**Comment by MohanadKh03** [comment]
Ok my bad seems there indeed was a problem while running ``mvn clean verify``
It is kind of weird though the CI and even locally it says that at line 381 there is an additional space 9 spaces and that i should delete one space of it to be 8 even though it already is 8 so somehow it is being modified while running ``mvn clean verify`` 
https://github.com/checkstyle/checkstyle/blob/64cabf0b77c5dedef1e7ad6ddb6b256c8bae01d6/src/xdocs/checks/coding/unnecessaryparentheses.xml#L381-L407
This is due to ``org.codehaus.mojo``'s ``xml-maven-plugin`` in the ``check-format`` goal 

After some debugging it seems that the file is being modified while running ``mvn clean verify`` only
When I run only this ``mvn clean org.codehaus.mojo:xml-maven-plugin:1.1.0:check-format`` it does not have an error and does not modify the file but when using ``mvn clean verify`` it seems to modify the ``unnecessaryparentheses.xml`` in one of its steps ? Not sure why this happens , Can you please refer me to where I can check for this problem ? @romani

File: src/xdocs/checks/coding/unnecessaryparentheses.xml.template [hunk 6]
```diff
@@ -117,6 +117,21 @@ if ((++f) &gt; g &amp;&amp; a) { // violation, unnecessary paren
                  value="resources/com/puppycrawl/tools/checkstyle/checks/coding/unnecessaryparentheses/Example2.java"/>
           <param name="type" value="code"/>
         </macro>
+         <p id="Example3-config">
```
Comment (mahfouz72) [inline src/xdocs/checks/coding/unnecessaryparentheses.xml.template:120]: delete a space here

Comment (MohanadKh03) [reply src/xdocs/checks/coding/unnecessaryparentheses.xml.template]: done
Thanks a lot

**Comment by romani** [comment]
GitHub, generate website

**Comment by romani** [comment]
Github, generate report for configs in PR description

**Comment by MohanadKh03** [comment]
@romani Is this xwiki problem related to a certain change I have done ? I tried to debug the script thats failing but cant really get what this really means
 ```[INFO] XWiki Platform - WebSocket ......................... FAILURE [  0.248 s]```

**Comment by romani** [comment]
This is Not related failure, we have it from today in all other PRs. I will ignore it.

**Review by romani — APPROVED** [review]
Ok to merge
