### PR TITLE
Issue #8266: fix false positive for MissingMethodCheck for private in…

### LINKED ISSUE #8266: MissingJavadocMethod flagging private methods even target scope is public methods only
https://checkstyle.sourceforge.io/config_javadoc.html#MissingJavadocMethod

```
$ javac CheckstylePrivateMethodTest.java
$ 
```
```
$ cat config.xml
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
          "-//Checkstyle//DTD Checkstyle Configuration 1.3//EN"
          "https://checkstyle.org/dtds/configuration_1_3.dtd">

<module name = "Checker">
    <module name="TreeWalker">
        <module name="MissingJavadocMethod">
            <property name="scope" value="public"/>
            <property name="minLineCount" value="2"/>
            <property name="tokens" value="METHOD_DEF"/>
        </module>
    </module>
</module>
```

```
$ cat CheckstylePrivateMethodTest.java
public interface CheckstylePrivateMethodTest {
  private static void whyIsMissingJavadocMethodBeingFlagged() {
    System.out.println();
    System.out.println();
    System.out.println();
    System.out.println();
  }
}
```

```
$ java -jar checkstyle-8.32-all.jar -c config.xml CheckstylePrivateMethodTest.java
Starting audit...
[ERROR] CheckstylePrivateMethodTest.java:2:3: Missing a Javadoc comment. [MissingJavadocMethod]
Audit done.
Checkstyle ends with 1 errors.

```
---------------
Expected - no violation.

When an interface has a private static method that goes beyond the line limit, it gets flagged as needing a javadoc comment, even though private methods are supposed to be exempt.

--------------

### PR DESCRIPTION
**Pull request by strkkk**
…terface methods

Resolves #8266 

Reg report: https://strkkk.github.io/checkstyle/8266/checkstyle/index.html

It looks like that fix is also discovered and fixed another false positives like https://strkkk.github.io/checkstyle/8266/checkstyle/xref/checkstyle/contribution/checkstyle-tester/repositories/checkstyle/src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/grammar/java9/InputAdvanceJava9TryWithResources.java.html#L9

### CODE REVIEW

**Comment by strkkk** [comment]
@romani Please take a look at issue, it is not approved

**Comment by romani** [comment]
@strkkk , please update description of issue to strictly follow issue template.

**Comment by strkkk** [comment]
@romani done

**Comment by strkkk** [comment]
@romani ping

File: src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/javadoc/missingjavadocmethod/InputMissingJavadocMethodInterfacePrivateMethod.java [hunk 1]
```diff
@@ -0,0 +1,11 @@
+//non-compiled with javac: Compilable with Java9
+// private method in interface
+
+package com.puppycrawl.tools.checkstyle.checks.javadoc.missingjavadocmethod;
+
+public interface InputMissingJavadocMethodInterfacePrivateMethod {
+
+    private static void myPrivateMethod() {
```
Comment (romani) [inline src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/javadoc/missingjavadocmethod/InputMissingJavadocMethodInterfacePrivateMethod.java:8]: Please add test case with new violation that is found by regression report https://strkkk.github.io/checkstyle/8266/checkstyle/index.html#A3

Comment (strkkk) [reply src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/javadoc/missingjavadocmethod/InputMissingJavadocMethodInterfacePrivateMethod.java:8]: done
