### PR TITLE
Issue #7297: Fix EmptyLineSeparator skips single line comments under …

### LINKED ISSUE #7297: EmptyLineSeparator skips single line comments under package
Similar to #4763 but with single line comment.
from https://github.com/checkstyle/checkstyle/pull/7251#issuecomment-554067904_

```
cat Test.java
package test;
// violation is expected

import java.lang;

class Test {}

cat config.xml
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
          "-//Puppy Crawl//DTD Check Configuration 1.3//EN"
          "http://www.puppycrawl.com/dtds/configuration_1_3.dtd">

<module name="Checker">
    <property name="charset" value="UTF-8"/>
    

    <module name="TreeWalker">
        <module name="EmptyLineSeparatorCheck">
		<property name="tokens" value="PACKAGE_DEF,IMPORT"/>
    </module>
    </module>
</module>

java -jar checkstyle-8.20-all.jar -c config.xml TestClass.java
Starting audit...
Audit done.

```

expected: violation

### PR DESCRIPTION
**Pull request by AkMo3**
Closes #7297 

```
$ cat Test.java 
package test;
// violation is expected

import java.lang;

class Test {}

$ cat config.xml 
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
          "-//Puppy Crawl//DTD Check Configuration 1.3//EN"
          "http://www.puppycrawl.com/dtds/configuration_1_3.dtd">

<module name="Checker">
    <property name="charset" value="UTF-8"/>
    <module name="TreeWalker">
        <module name="EmptyLineSeparatorCheck">
		<property name="tokens" value="PACKAGE_DEF,IMPORT"/>
    </module>
    </module>
</module>       
                                                                                                                                                      
$ java -jar checkstyle-8.42-SNAPSHOT-all.jar -c config.xml Test.java 
Starting audit...
[ERROR] /home/akmo/GitHub/Test/NewLineSeperator/Test.java:2:1: '//' should be separated from previous statement. [EmptyLineSeparator]
Audit done.
Checkstyle ends with 1 errors.

```

Diff Regression config: https://raw.githubusercontent.com/AkMo3/akmo3.github.io/master/Issue7297/config-FIX_EMPTY_LINE_AFTER_PACKAGE-20210323145757.xml
Diff Regression projects: https://raw.githubusercontent.com/AkMo3/akmo3.github.io/master/Issue9010/projects-to-test-on.properties

### CODE REVIEW

**Comment by AkMo3** [comment]
GitHub, generate report

**Comment by AkMo3** [comment]
@strkkk Sir, please review.

**Comment by strkkk** [comment]
@AkMo3 report looks good, please fix ci issues

P.S. it is better to avoid multiple check instances in same config for report in such cases, you could take one from bug description.

**Comment by AkMo3** [comment]
GitHub, generate report

**Review by strkkk — APPROVED** [review]

**Comment by AkMo3** [comment]
GitHub, generate report

**Comment by AkMo3** [comment]
@strkkk Sir,
While resolving pitest I discovered at this check currently skip Javadoc comments also. Proof :
```
$ cat Test2.java 
package test;
/**
 * violation expected at line above.
 *
 */

import java.util.Arrays;
import java.util.Objects;

public class Test2{
}

$ cat config.xml 
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
          "-//Puppy Crawl//DTD Check Configuration 1.3//EN"
          "http://www.puppycrawl.com/dtds/configuration_1_3.dtd">

<module name="Checker">
    <property name="charset" value="UTF-8"/>
    <module name="TreeWalker">
        <module name="EmptyLineSeparatorCheck">
		<property name="tokens" value="PACKAGE_DEF,IMPORT"/>
    </module>
    </module>
</module>
                                                                                                                                                            
$ java -jar checkstyle-8.42-SNAPSHOT-all.jar -c config.xml Test2.java
Starting audit...
Audit done.
````
I have removed condition of checking just single line comments, now the check also fix skipping of javadoc comments.

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/EmptyLineSeparatorCheck.java [hunk 1]
```diff
@@ -575,11 +575,26 @@ private void processPackage(DetailAST ast, DetailAST nextToken) {
...
         if (!hasEmptyLineAfter(ast)) {
             log(nextToken, MSG_SHOULD_BE_SEPARATED, nextToken.getText());
         }
     }
 
+    /**
+     * Checks if there is another element at next line of package declaration.
+     *
+     * @param ast Package ast.
+     * @return true, if there is a element.
```
Comment (pbludov) [inline src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/EmptyLineSeparatorCheck.java:591]: "a element" -> "an element"

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/EmptyLineSeparatorCheck.java [hunk 2]
```diff
@@ -575,11 +575,26 @@ private void processPackage(DetailAST ast, DetailAST nextToken) {
...
+     */
+    private static boolean isLineEmptyAfterPackage(DetailAST ast) {
```
Comment (pbludov) [inline src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/EmptyLineSeparatorCheck.java:593]: Why is this method called `isLineEmptyAfterPackage`?
It can be used with any other element. This method checks if an element is followed by a blank line. It should be something like `hasEmptyLineAfter`.
Wait, we already have this method! But it is hardcoded to ignore any comments.
This is done for a reason, to allow a Javadoc __before__ package definition.
I really ask you to spend a little time to find out if it is possible to use the `isPrecededByJavadoc` method instead of `isComment` in this method.

**Review by pbludov — CHANGES_REQUESTED** [review]

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/EmptyLineSeparatorCheck.java (hunk 2 above)
Comment (AkMo3) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/EmptyLineSeparatorCheck.java:593]: > Why is this method called isLineEmptyAfterPackage? It can be used with any other element.


No Sir, this can't be used as here we are checking empty line after the `lastChild` of `AST`. But this cannot be used for others as not every AST declaration is as such. Eg - `METHOD_DEF` . 
______________________________________________________________________________________

The already present `hasEmptyLineAfter` is hard coded to ignore comments to allow trailing comments that are valid.
Eg: https://github.com/checkstyle/checkstyle/blob/13481f2c410e4944ecf5ab93ec49948a523a0c82/src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/emptylineseparator/InputEmptyLineSeparator.java#L20
 I am not able to make any relation with Javadoc comment with this method, please correct me if I am wrong.

Also, I have found some corner cases that I have missed before. I am generating a new report for them. Please check.

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/EmptyLineSeparatorCheck.java (hunk 1 above)
Comment (AkMo3) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/EmptyLineSeparatorCheck.java]: Done

**Comment by AkMo3** [comment]
GitHub, generate report

**Comment by AkMo3** [comment]
@pbludov @strkkk Please confirm the latest report is fine or not. Also, Please restart semaphore.

**Comment by strkkk** [comment]
> Please restart semaphore.

done.

I am not sure about this changes. For example https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/d660ff2_2021103444/reports/diff/Hbase/index.html#A1

This violation was reported on import? If yes, it sounds weird that it says that comment should be separated from previous statement.

**Comment by AkMo3** [comment]
> This violation was reported on import? If yes, it sounds weird that it says that comment should be separated from previous statement.

This was expected from my side. The reason is `nextToken` in process package in import token. This is the reason the violation is on import rather than javadoc comment. https://github.com/checkstyle/checkstyle/blob/40332c5921ab6eae6b80468562f8621be572c848/src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/EmptyLineSeparatorCheck.java#L567-L581

**Comment by strkkk** [comment]
@AkMo3 Best way to demostrate things is via test inputs. I suggest to add tests for config with tokens = PACKAGE_DEF and other with tokens = IMPORT. This will show what are violations for package and for import separately. To be honest, I am a bit lost in this violations.

**Comment by AkMo3** [comment]
```
 $ cat Test2.java 
package test;
/**
 * violation expected at line above.
 *
 */
import java.util.Arrays;
import java.util.Objects;

public class Test2{
}

 $ cat package.xml 
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
          "-//Puppy Crawl//DTD Check Configuration 1.3//EN"
          "http://www.puppycrawl.com/dtds/configuration_1_3.dtd">

<module name="Checker">
    <property name="charset" value="UTF-8"/>
    <module name="TreeWalker">
        <module name="EmptyLineSeparatorCheck">
		<property name="tokens" value="PACKAGE_DEF"/>
    </module>
    </module>
</module>

 $ cat Import.xml 
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
          "-//Puppy Crawl//DTD Check Configuration 1.3//EN"
          "http://www.puppycrawl.com/dtds/configuration_1_3.dtd">

<module name="Checker">
    <property name="charset" value="UTF-8"/>
    <module name="TreeWalker">
        <module name="EmptyLineSeparatorCheck">
		<property name="tokens" value="IMPORT"/>
    </module>
    </module>
</module>

 $ java -jar checkstyle-8.42-SNAPSHOT-all.jar -c Import.xml Test2.java 
Starting audit...
Audit done.

$ java -jar checkstyle-8.42-SNAPSHOT-all.jar -c package.xml Test2.java 
Starting audit...
[ERROR] /home/akmo/GitHub/Test/NewLineSeperator/Test2.java:2:1: '/*' should be separated from previous statement. [EmptyLineSeparator]
Audit done.
Checkstyle ends with 1 errors.

$ java -jar OldJar.jar -c Import.xml Test2.java                       
Starting audit...
Audit done.

$ java -jar OldJar.jar -c package.xml Test2.java 
Starting audit...
[ERROR] /home/akmo/GitHub/Test/NewLineSeperator/Test2.java:6:1: 'import' should be separated from previous statement. [EmptyLineSeparator]
Audit done.
Checkstyle ends with 1 errors.
```

@strkkk Do you want be include such tests in code also or just for here?

**Comment by strkkk** [comment]
@AkMo3 I think it is better to extend test cases.

What is interesting that this code
```
package test;
/**
 * violation expected at line above.
 *
 */
import java.util.Arrays;
```
does not produce violation for import token.

**Comment by AkMo3** [comment]
@strkkk The violation in all cases will be on `PACKAGE_DEF` only because of this 
https://github.com/checkstyle/checkstyle/blob/a45641c18dbef7294dceeddce1134cde62b7ed14/src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/EmptyLineSeparatorCheck.java#L413-L415

**Comment by AkMo3** [comment]
@pbludov Sir, can you please review the changes.

**Review by pbludov — APPROVED** [review]

**Comment by AkMo3** [comment]
@rnveach Kindly review this and #9539

**Comment by romani** [comment]
I am merging this as @rnveach do not have time to do review for now.

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/EmptyLineSeparatorCheck.java [hunk 3]
```diff
@@ -575,11 +575,46 @@ private void processPackage(DetailAST ast, DetailAST nextToken) {
                 log(ast, MSG_SHOULD_BE_SEPARATED, ast.getText());
             }
         }
-        if (!hasEmptyLineAfter(ast)) {
+        if (isLineEmptyAfterPackage(ast)) {
+            final DetailAST elementAST = getViolationASTForPackage(ast);
```
Comment (romani) [inline src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/EmptyLineSeparatorCheck.java:579]: `getViolationAstForPackage`

`elementAst`

please update all other cases with AST to Ast that you introduced in this PR.

**Review by romani — CHANGES_REQUESTED** [review]
items:

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/EmptyLineSeparatorCheck.java (hunk 3 above)
Comment (AkMo3) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/EmptyLineSeparatorCheck.java]: Done

**Review by romani — APPROVED** [review]

**Comment by romani** [comment]
`[ERROR] [checkstyle] [ERROR] /Users/runner/work/1/s/src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/EmptyLineSeparatorCheck.java:303:1: Total number of methods is 35 (max allowed is 34). [MethodCount]`

CI should pass

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/EmptyLineSeparatorCheck.java [hunk 4]
```diff
@@ -411,7 +411,10 @@ public void visitToken(DetailAST ast) {
             processMultipleLinesInside(ast);
         }
         if (ast.getType() == TokenTypes.PACKAGE_DEF) {
-            checkCommentInModifiers(ast);
+            final Optional<DetailAST> comment = findCommentUnder(ast);
```
Comment (romani) [inline src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/EmptyLineSeparatorCheck.java:414]: lets keep it 

but lets remove util methods , that are already in our Utils classes
https://github.com/checkstyle/checkstyle/blob/c0290eee78318428e2b14432968de34f34ee92e0/src/main/java/com/puppycrawl/tools/checkstyle/utils/TokenUtil.java#L209
we can reuse util method

candidates:
https://github.com/checkstyle/checkstyle/blob/98d1a3edf17c42766fed1acb7c1002a682d9c8c7/src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/EmptyLineSeparatorCheck.java#L911-L925

**Review by romani — CHANGES_REQUESTED** [review]
items:

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/EmptyLineSeparatorCheck.java (hunk 4 above)
Comment (AkMo3) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/EmptyLineSeparatorCheck.java]: Done. Removed `isComment()`.

**Comment by romani** [comment]
I need to start again discussion on cases like
https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/d660ff2_2021103444/reports/diff/Hbase/index.html#A2

I see discussion about it at https://github.com/checkstyle/checkstyle/pull/9707#issuecomment-805813913 but I do not see explanation why we loosing violation on "import" that is not separated from comment by empty line

**Comment by romani** [comment]
if we demand empty line between package and comment (new behavior).
we should demand empty line between import and comment (old behavior).
do be consistent in behavior.

**Comment by AkMo3** [comment]
Sir, I guess there was never a violation from this check before import statements. 
```
$ cat config.xml 
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
          "-//Puppy Crawl//DTD Check Configuration 1.3//EN"
          "https://checkstyle.org/dtds/configuration_1_3.dtd">
<module name="Checker">
  <module name="TreeWalker">
        <module name="EmptyLineSeparator"/>
  </module>
</module>

$ cat Test.java 
package com.puppycrawl.tools.checkstyle.checks.whitespace.emptylineseparator;

/**
 * Config:
 * allowMultipleEmptyLinesInsideClassMembers = false
 */
import java.util.*;

public class Test {
}

$ java -jar checkstyle-8.41.1-all.jar -c config.xml Test.java       
Starting audit...
Audit done.

$ java -jar checkstyle-8.42-SNAPSHOT-all.jar -c config.xml Test.java 
Starting audit...
Audit done.
```
In https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/d660ff2_2021103444/reports/diff/Hbase/index.html#A2 the violation is actually for the `PACKAGE_DEF` node, but it was incorrectly shown at line 19. The violation will always be in package def only as I have explained in [#9707 Comment](https://github.com/checkstyle/checkstyle/pull/9707#issuecomment-806715996).
But I totally agree that documentation and message should be changed. I would send a separate PR for that issue.

**Comment by romani** [comment]
yes, you are right.
Message and doc is confusing, could be improved separatey.

**Review by romani — APPROVED** [review]
