### PR TITLE
Issue #11720: Kill surviving mutation in VariableDeclarationUsageDistanceCheck in getFirstNodeInsideIfBlock

### LINKED ISSUE #11720: Pitest: Kill all surviving mutations
This will be main tracker issue for killing surviving mutations before we begin work in https://github.com/checkstyle/checkstyle/issues/11719

Now that we have diff report generation as github action, let's modify the procedure from  https://github.com/checkstyle/checkstyle/issues/7797#issue-577522554 a bit to speed this up:

1. Disable all CI first as separate commit(See example at https://github.com/checkstyle/checkstyle/pull/11721). This will help to not waste credits.
2. Pick one single surviving mutation from pitest.sh.
3. Send PR with a single hardcoded mutation only.
4. Generate diff report with hardcoded mutation.
5. Share link to initial commit with hardcoded mutation and initial diff report in PR description. This is in lieu of separate branch/ etc. in previous issue at #7797. 

HARDCODED MUTATION WILL NOT BE IN FINAL PR.

We will have one of three outcomes for each mutation (in order of preference):
1. Find a case that kills the mutation via diff report, add new test in existing PR
2. Safely (no regressions) modify code to be covered, in existing PR
3. Safely (no regressions) remove code to be covered, in existing PR

Case (2) and (3) required a detailed analysis and discussion in issue before making any changes.

-----------------------------------

**We will not be pursuing surviving mutations in IndentationCheck or gui package .**

### PR DESCRIPTION
**Pull request by Vyom-Yadav**
Closes #11720

Check documentation: https://checkstyle.sourceforge.io/config_coding.html#VariableDeclarationUsageDistance

### Diff Reports (Contains diff, Issue for NPE at #11973):

- validateBetweenScopesFalse: https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/78d2c37_2022195745/reports/diff/index.html
- validateBetweenScopesTrue: https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/3fe931a_2022125544/reports/diff/index.html

### Rationale

There is no need to loop and check all the statements in the `if-else` chain at once, just check the current statement, the next statement (if present), and the outer method i.e. `calculateDistanceBetweenScopes` will iterate over the remaining branches, we just add the head of the remaining branches to `variableUsageExpressions` for it to be analyzed in the next iteration.

Also support for `if` statements without `{}` was added, it rationale is present below. 
Previous Logic:
```java
private static DetailAST getFirstNodeInsideIfBlock(
        DetailAST block, DetailAST variable) {
    DetailAST firstNodeInsideBlock = null;


    if (!isVariableInOperatorExpr(block, variable)) {
        DetailAST currentNode = block.getLastChild();
        final List<DetailAST> variableUsageExpressions =
                new ArrayList<>();


        while (currentNode != null
                && currentNode.getType() == TokenTypes.LITERAL_ELSE) {
            final DetailAST previousNode =
                    currentNode.getPreviousSibling();


            // Checking variable usage inside IF block.
            if (isChild(previousNode, variable)) {
                variableUsageExpressions.add(previousNode);
            }


            // Looking into ELSE block, get its first child and analyze it.
            currentNode = currentNode.getFirstChild();


            if (currentNode.getType() == TokenTypes.LITERAL_IF) {
                currentNode = currentNode.getLastChild();
            }
            else if (isChild(currentNode, variable)) {
                variableUsageExpressions.add(currentNode);
                currentNode = null;
            }
        }


        // If IF block doesn't include ELSE then analyze variable usage
        // only inside IF block.
        if (currentNode != null
                && isChild(currentNode, variable)) {
            variableUsageExpressions.add(currentNode);
        }


        // If variable usage exists in several related blocks, then
        // firstNodeInsideBlock = null, otherwise if variable usage exists
        // only inside one block, then get node from
        // variableUsageExpressions.
        if (variableUsageExpressions.size() == 1) {
            firstNodeInsideBlock = variableUsageExpressions.get(0);
        }
    }


    return firstNodeInsideBlock;
}
```
If we see the initial logic, we get the if statements last-child, for if statements without `{}`, it will be:
```java
if (true)    
    method();
```
AST-
```
LITERAL_IF -> if 
   |--LPAREN -> ( 
   |--EXPR -> EXPR 
   |   `--LITERAL_TRUE -> true 
   |--RPAREN -> ) 
   |--EXPR -> EXPR 
   |   `--METHOD_CALL -> ( 
   |       |--IDENT -> method 
   |       |--ELIST -> ELIST 
   |       `--RPAREN -> ) 
   `--SEMI -> ; 
```
Now the last child is `SEMI` and the according to the logic, it was supposed to be if statements body.
The logic was built for if statements with `{}` where the last child is `SLIST` i.e. if statement's body.
```
LITERAL_IF -> if 
  |--LPAREN -> ( 
  |--EXPR -> EXPR 
  |   `--LITERAL_TRUE -> true 
  |--RPAREN -> ) 
  `--SLIST -> { 
      |--EXPR -> EXPR 
      |   `--METHOD_CALL -> ( 
      |       |--IDENT -> method 
      |       |--ELIST -> ELIST 
      |       `--RPAREN -> ) 
      |--SEMI -> ; 
      `--RCURLY -> } 
```
Cases like this in combination with `else` were missing, support for that was added.

---

### Generating reports again:

Diff Regression config: https://gist.githubusercontent.com/Vyom-Yadav/98dceb63a79f4833e85fff9b2e1464a6/raw/a06fa3c8f525c4466a67c1ee057d4ed843db2301/my_checks.xml
Report label: validateBetweenScopesTrue

### CODE REVIEW

**Comment by Vyom-Yadav** [comment]
Github, generate report

**Comment by Vyom-Yadav** [comment]
Github, generate report

**Comment by Vyom-Yadav** [comment]
Github, generate report

**Review by nick-mancuso — CHANGES_REQUESTED** [review]
@Vyom-Yadav are we able to cleanly separate changes here into two PRs?

**Comment by Vyom-Yadav** [comment]
> @Vyom-Yadav are we able to cleanly separate changes here into two PRs?

We can, but it is not recommended, the `if` conditions are related to each other, just removing one branch at a time can be done but it doesn't make any sense to do so, having complete correct logic that is related to each other in one PR is better IMO, but still if needed, I can split this into two :)

**Comment by Vyom-Yadav** [comment]
Github, generate report

**Comment by nick-mancuso** [comment]
@Vyom-Yadav why such a large discrepancy between reports?

**Comment by Vyom-Yadav** [comment]
> @Vyom-Yadav why such a large discrepancy between reports?

I added support for `if` statements without `{ }`, that's why there is this difference, in many cases, the distance is increased by one as earlier `if` statements without `{ }` were not supported.

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/VariableDeclarationUsageDistanceCheck.java [hunk 1]
```diff
@@ -762,36 +762,25 @@ private static DetailAST getFirstNodeInsideIfBlock(
...
-                    variableUsageExpressions.add(previousNode);
-                }
+            final Optional<DetailAST> slistToken = TokenUtil
+                .findFirstTokenByPredicate(block, token -> token.getType() == TokenTypes.SLIST);
+            final DetailAST currentNode = block.getLastChild();
+            DetailAST previousNode = currentNode.getPreviousSibling();
 
-                // Looking into ELSE block, get its first child and analyze it.
-                currentNode = currentNode.getFirstChild();
+            // Is if statement without '{}'
```
Comment (nick-mancuso) [inline src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/VariableDeclarationUsageDistanceCheck.java:770]: If this comment applies to condition to enter `if` block, it is better to move comment inside block and combine with other comment.

**Review by nick-mancuso — CHANGES_REQUESTED** [review]
Item:

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/VariableDeclarationUsageDistanceCheck.java (hunk 1 above)
Comment (Vyom-Yadav) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/VariableDeclarationUsageDistanceCheck.java]: Done, made the condition more clear.

File: src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/variabledeclarationusagedistance/InputVariableDeclarationUsageDistanceGeneral2.java [hunk 2]
```diff
@@ -63,4 +63,36 @@ void method() throws Exception {
             a.equals("");
         }
     }
+
```
Comment (nick-mancuso) [inline src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/variabledeclarationusagedistance/InputVariableDeclarationUsageDistanceGeneral2.java:66]: Please add test cases similar to https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/3fe931a_2022125544/reports/diff/openjdk17/xref/home/runner/work/checkstyle/checkstyle/contribution/checkstyle-tester/repositories/openjdk17/test/hotspot/jtreg/vmTestbase/jit/t/t091/t091.java.html#L58 (a bunch of consecutive `if` statements without block), where we have acceptable usage and violations. Also, I am having a hard time figuring out which `if` statement we missed previously; the one immediately preceding the `if` statement where we use the variable?

**Review by nick-mancuso — CHANGES_REQUESTED** [review]
Item:

File: src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/variabledeclarationusagedistance/InputVariableDeclarationUsageDistanceGeneral2.java (hunk 2 above)
Comment (Vyom-Yadav) [reply src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/variabledeclarationusagedistance/InputVariableDeclarationUsageDistanceGeneral2.java:66]: > Please add test cases similar to........

Done.

>Also, I am having a hard time figuring out which if statement we missed previously; the one immediately preceding the if statement where we use the variable?

I will make it clear which `if` statements we missed-

Previous Logic:
```java
private static DetailAST getFirstNodeInsideIfBlock(
        DetailAST block, DetailAST variable) {
    DetailAST firstNodeInsideBlock = null;


    if (!isVariableInOperatorExpr(block, variable)) {
        DetailAST currentNode = block.getLastChild();
        final List<DetailAST> variableUsageExpressions =
                new ArrayList<>();


        while (currentNode != null
                && currentNode.getType() == TokenTypes.LITERAL_ELSE) {
            final DetailAST previousNode =
                    currentNode.getPreviousSibling();


            // Checking variable usage inside IF block.
            if (isChild(previousNode, variable)) {
                variableUsageExpressions.add(previousNode);
            }


            // Looking into ELSE block, get its first child and analyze it.
            currentNode = currentNode.getFirstChild();


            if (currentNode.getType() == TokenTypes.LITERAL_IF) {
                currentNode = currentNode.getLastChild();
            }
            else if (isChild(currentNode, variable)) {
                variableUsageExpressions.add(currentNode);
                currentNode = null;
            }
        }


        // If IF block doesn't include ELSE then analyze variable usage
        // only inside IF block.
        if (currentNode != null
                && isChild(currentNode, variable)) {
            variableUsageExpressions.add(currentNode);
        }


        // If variable usage exists in several related blocks, then
        // firstNodeInsideBlock = null, otherwise if variable usage exists
        // only inside one block, then get node from
        // variableUsageExpressions.
        if (variableUsageExpressions.size() == 1) {
            firstNodeInsideBlock = variableUsageExpressions.get(0);
        }
    }


    return firstNodeInsideBlock;
}
```
If we see the initial logic, we get the if statements last-child, for if statements without `{}`, it will be:
```java
if (true)    
    method();
```
AST-
```
LITERAL_IF -> if 
   |--LPAREN -> ( 
   |--EXPR -> EXPR 
   |   `--LITERAL_TRUE -> true 
   |--RPAREN -> ) 
   |--EXPR -> EXPR 
   |   `--METHOD_CALL -> ( 
   |       |--IDENT -> method 
   |       |--ELIST -> ELIST 
   |       `--RPAREN -> ) 
   `--SEMI -> ; 
```
Now the last child is `SEMI` and the according to the logic, it was supposed to be if statements body.
The logic was built for if statements with `{}` where the last child is `SLIST` i.e. if statement's body.
```
LITERAL_IF -> if 
  |--LPAREN -> ( 
  |--EXPR -> EXPR 
  |   `--LITERAL_TRUE -> true 
  |--RPAREN -> ) 
  `--SLIST -> { 
      |--EXPR -> EXPR 
      |   `--METHOD_CALL -> ( 
      |       |--IDENT -> method 
      |       |--ELIST -> ELIST 
      |       `--RPAREN -> ) 
      |--SEMI -> ; 
      `--RCURLY -> } 
```
Cases like this in combination with `else` were missing, support for that was added.

Comment (nick-mancuso) [reply src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/variabledeclarationusagedistance/InputVariableDeclarationUsageDistanceGeneral2.java:66]: Please add this analysis to the PR description to explain change in behavior of check.

Comment (Vyom-Yadav) [reply src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/variabledeclarationusagedistance/InputVariableDeclarationUsageDistanceGeneral2.java:66]: Done.

**Review by nick-mancuso — APPROVED** [review]

**Review by pbludov — APPROVED** [review]

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/VariableDeclarationUsageDistanceCheck.java [hunk 3]
```diff
@@ -761,36 +761,25 @@ private static DetailAST getFirstNodeInsideIfBlock(
...
-                final DetailAST previousNode =
-                        currentNode.getPreviousSibling();
-
-                // Checking variable usage inside IF block.
-                if (isChild(previousNode, variable)) {
-                    variableUsageExpressions.add(previousNode);
-                }
+            final Optional<DetailAST> slistToken = TokenUtil
+                .findFirstTokenByPredicate(block, token -> token.getType() == TokenTypes.SLIST);
+            final DetailAST currentNode = block.getLastChild();
```
Comment (baratali) [inline src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/VariableDeclarationUsageDistanceCheck.java:766]: can you please rename it to `lastNode` (since there is no loop anymore and it has only one value)?

File: src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/variabledeclarationusagedistance/InputVariableDeclarationUsageDistanceGeneral2.java [hunk 4]
```diff
@@ -63,4 +63,52 @@ void method() throws Exception {
...
+        if (true)
+            a++;
+        if (true)
+            b++;
+        if (false)
+            c++;
+        if (true)
+            d++;
+    }
```
Comment (baratali) [inline src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/variabledeclarationusagedistance/InputVariableDeclarationUsageDistanceGeneral2.java:113]: When `return` is the first statement in `if` the last child is not `SEMI`:
```java
if (true) return a;
```
```
LITERAL_IF -> if [3:8]
|--LPAREN -> ( [3:11]
|--EXPR -> EXPR [3:12]
|  `--LITERAL_TRUE -> true [3:12]
|--RPAREN -> ) [3:16]
`--LITERAL_RETURN -> return [3:18]
    |--EXPR -> EXPR [3:25]
    |  `--IDENT -> a [3:25]
    `--SEMI -> ; [3:26]
```
And it doesn't catch a violation in such code:
```java
    String testReturn() {
        int a = 1; // violation
        System.out.println();
        System.out.println();
        System.out.println();
        if (true)
            return String.valueOf(a);

        return null;
    }
```
Can you please add it to the inputs too?

**Review by baratali — CHANGES_REQUESTED** [review]

File: src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/variabledeclarationusagedistance/InputVariableDeclarationUsageDistanceGeneral2.java (hunk 4 above)
Comment (Vyom-Yadav) [reply src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/variabledeclarationusagedistance/InputVariableDeclarationUsageDistanceGeneral2.java:113]: I tested it, it won't give a violation, the `if` statement evaluations works correctly, but this is considered by check logic as an initialization sequence 
(`isInitializationSequence = true`), so it does not give a violation finally at:
https://github.com/checkstyle/checkstyle/blob/f4ab4aa20d27153bb9489315644cfb2a4c8b9e3c/src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/VariableDeclarationUsageDistanceCheck.java#L417-L418

Comment (Vyom-Yadav) [reply src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/variabledeclarationusagedistance/InputVariableDeclarationUsageDistanceGeneral2.java]: I added a similar example as proof of working on current changes.

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/VariableDeclarationUsageDistanceCheck.java (hunk 3 above)
Comment (Vyom-Yadav) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/VariableDeclarationUsageDistanceCheck.java]: Done.
