### PR TITLE
Manually parse the Ant configUrl field into a URL

### LINKED ISSUE #4449: Ant's configUrl requires a full URL - relative paths don't work
Background in Issue #3119:

As I understand it, you should be able to specify a relative path (to a resource on the classpath) in the `configUrl` attribute of the Ant task. However I'm getting an error when I attempt to do so, and instead have to specify the full resource URL (`jar:file:PATH_TO_JAR!/PATH_TO_RESOURCE`), which is brittle and overspecified.

---------------

```
$ ant -version
Apache Ant(TM) version 1.10.1 compiled on February 2 2017

$ hg diff
diff -r 57a890e81233 build.xml
--- a/build.xml Sat Jun 10 15:06:52 2017 -0700
+++ b/build.xml Tue Jun 13 09:18:42 2017 -0700
@@ -124,7 +124,7 @@

     <!-- Checkstyle -->
     <target name="checkstyle" depends="build-test" description="Style linter">
-      <checkstyle configUrl="jar:file:lib/checkstyle-7.8.1-all.jar!/google_checks.xml" maxWarnings="0">
+      <checkstyle configUrl="/google_checks.xml" maxWarnings="0">
         <fileset dir="${core.src}" includes="**/*.java"/>
       </checkstyle>
       <checkstyle configUrl="jar:file:lib/checkstyle-7.8.1-all.jar!/google_checks.xml" maxWarnings="0">

$ ant checkstyle
Buildfile: /.../build.xml

init:

build:

build-test:

checkstyle:

BUILD FAILED
/.../build.xml:127: java.net.MalformedURLException: no protocol: /google_checks.xml
	at java.net.URL.<init>(URL.java:593)
	at java.net.URL.<init>(URL.java:490)
	at java.net.URL.<init>(URL.java:439)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.apache.tools.ant.IntrospectionHelper$11.set(IntrospectionHelper.java:1206)
	at org.apache.tools.ant.IntrospectionHelper$AttributeSetter.setObject(IntrospectionHelper.java:1512)
	at org.apache.tools.ant.IntrospectionHelper.setAttribute(IntrospectionHelper.java:412)
	at org.apache.tools.ant.RuntimeConfigurable.maybeConfigure(RuntimeConfigurable.java:528)
	at org.apache.tools.ant.RuntimeConfigurable.maybeConfigure(RuntimeConfigurable.java:464)
	at org.apache.tools.ant.Task.maybeConfigure(Task.java:202)
	at org.apache.tools.ant.UnknownElement.configure(UnknownElement.java:200)
	at org.apache.tools.ant.UnknownElement.maybeConfigure(UnknownElement.java:164)
	at org.apache.tools.ant.Task.perform(Task.java:347)
	at org.apache.tools.ant.Target.execute(Target.java:435)
	at org.apache.tools.ant.Target.performTasks(Target.java:456)
	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1405)
	at org.apache.tools.ant.Project.executeTarget(Project.java:1376)
	at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
	at org.apache.tools.ant.Project.executeTargets(Project.java:1260)
	at org.apache.tools.ant.Main.runBuild(Main.java:857)
	at org.apache.tools.ant.Main.startAnt(Main.java:236)
	at org.apache.tools.ant.launch.Launcher.run(Launcher.java:287)
	at org.apache.tools.ant.launch.Launcher.main(Launcher.java:113)

Total time: 0 seconds
```

Checkstyle runs successfully without this local mod (i.e. with the fully-qualified URL). I see this same error on both OSX and Windows.

### PR DESCRIPTION
**Pull request by dimo414**
so that invalid URLs can be treated as resource paths. Fixes #4449.

### CODE REVIEW

**Comment by rnveach** [comment]
@dimo414 CI must pass. Code style and code coverage are failing.
Please keep number of commits at 1.

**Comment by dimo414** [comment]
Sorry, I mistakenly only ran `mvn test` before. `mvn verify` now passes locally.

**Comment by dimo414** [comment]
Hmm, seems like AppVeyor still [isn't happy](https://ci.appveyor.com/project/Checkstyle/checkstyle/build/7966/job/2n8bd1sljtgkogbv), though I'm not sure why. I can't replicate the failure locally. Any pointers?

**Comment by rnveach** [comment]
appveyor is a windows machine. It is failing on code coverage. Travis has same failure, so most likely you are not getting coverage of your new `catch` for MalformedURLException .

**Comment by dimo414** [comment]
Odd, I added `testConfigurationByResource()` to detect that case, and verified locally that it enters the `catch` block. I'll try to verify on a Windows machine later.

File: src/main/java/com/puppycrawl/tools/checkstyle/ant/CheckstyleAntTask.java [hunk 1]
```diff
@@ -244,16 +245,23 @@ public void setConfig(File file) {
...
 
     /**
      * Sets URL to the configuration.
      * @param url the URL of the configuration to use
      */
-    public void setConfigUrl(URL url) {
-        setConfigLocation(url.toExternalForm());
+    public void setConfigUrl(String url) {
+        try {
+            setConfigLocation(new URL(url).toExternalForm());
```
Comment (romani) [inline src/main/java/com/puppycrawl/tools/checkstyle/ant/CheckstyleAntTask.java]: no need to do instantiation of URL here  `final URI uri = CommonUtils.getUriByFilename(config);` , string could stored as is , to be processed at
https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/ConfigurationLoader.java#L179

conversion to URL/URI - https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/utils/CommonUtils.java#L372

Comment (dimo414) [inline src/main/java/com/puppycrawl/tools/checkstyle/ant/CheckstyleAntTask.java]: Not clear what you're suggesting - do you want me to use `CommonUtils.getUriByFilename()` instead, or are you saying `setConfigUrl()` should simply be:

```
public void setConfigUrl(String url) {
    setConfigLocation(url);
}
```
?

I think that the latter would be a breaking change for callers that rely on `.toExternalForm()` being called, but if that doesn't concern you I can change it to that.

**Comment by dimo414** [comment]
I've not been able to replicate this on my Windows 10 machine - I run into a number of other seemingly unrelated failures (e.g. in `AstRegressionTest`).

**Comment by romani** [comment]
@dimo414 , please share some logs from your local windows to let us help you.

Attention: please read https://github.com/checkstyle/checkstyle/issues/4449#issuecomment-310078283

File: src/main/java/com/puppycrawl/tools/checkstyle/ant/CheckstyleAntTask.java (hunk 1 above)
Comment (romani) [inline src/main/java/com/puppycrawl/tools/checkstyle/ant/CheckstyleAntTask.java]: we are decided to go further with breaking compatibility changes, please read https://github.com/checkstyle/checkstyle/issues/4449#issuecomment-310078283

**Comment by dimo414** [comment]
Ok, I've swapped everything to `setConfig(String)` as suggested in the bug thread.

File: src/main/java/com/puppycrawl/tools/checkstyle/ant/CheckstyleAntTask.java [hunk 2]
```diff
@@ -230,42 +229,13 @@ public void setFile(File file) {
...
-     */
-    private void setConfigLocation(String location) {
+    public void setConfig(String file) {
         if (configLocation != null) {
-            throw new BuildException("Attributes 'config' and 'configURL' "
-                    + "must not be set at the same time");
+            throw new BuildException("Attribute 'config' has already been set");
         }
-        configLocation = location;
+        configLocation = file;
```
Comment (rnveach) [inline src/main/java/com/puppycrawl/tools/checkstyle/ant/CheckstyleAntTask.java]: Please rename `configLocation` to `config` so it is seen as a bean.
We are already starting to do this with checks, so reflection utilities will recognize them and tie them together.

Comment (romani) [inline src/main/java/com/puppycrawl/tools/checkstyle/ant/CheckstyleAntTask.java]: please make method argument to be `public void setConfig(String config) {`
to make it similar to
`public static Configuration loadConfiguration(String config, ....` [as here](https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/ConfigurationLoader.java#L160)

**Comment by romani** [comment]
Travis failures "The forked VM terminated without properly saying goodbye." could be ignored, known instability problem.

**Comment by romani** [comment]
Please also rebase on latest master, we did travis fix, it should pass.

File: src/main/java/com/puppycrawl/tools/checkstyle/ant/CheckstyleAntTask.java (hunk 2 above)
Comment (dimo414) [inline src/main/java/com/puppycrawl/tools/checkstyle/ant/CheckstyleAntTask.java]: Done and done - I'd used setConfig(String file) since that's what you suggested in https://github.com/checkstyle/checkstyle/issues/4449#issuecomment-310078283, but this certainly makes more sense.

**Comment by rnveach** [comment]
@dimo414 you have test failures and checkstyle errors.

**Comment by dimo414** [comment]
Sorry, that was sloppy - I can't get Checkstyle to build on my Windows box so I just made the requested changes. I'll try to fix them.

**Comment by romani** [comment]
> I can't get Checkstyle to build on my Windows box

did you share with us your build log with problem ? We have CI for Windows build and we have some team members on Windows, all problems resolved a while ago.

**Comment by dimo414** [comment]
Ok, fixed the test failure, but the requested changes (to name the field and the parameter both `config`) conflict, according to CheckStyle:

    [checkstyle] [ERROR] /tmp/github/checkstyle/src/main/java/com/puppycrawl/tools/checkstyle/ant/CheckstyleAntTask.java:394:33: 'config' hides a field. [HiddenField]

How would you like me to proceed? Rename one or the other? Or is there a way to suppress this?

**Comment by romani** [comment]
> How would you like me to proceed?

unfortunate case, but public names are above in priority.
Please rename local variable `config` to `configuration`.

**Comment by dimo414** [comment]
Ok, `mvn verify` passes, hopefully CI likes it.
