### PR TITLE
Issue #6887: SuppressWithPlainTextCommentFilter ignores messageFormat

### LINKED ISSUE #6887: SuppressWithPlainTextCommentFilter ignores messageFormat when matching on ID
```
$ cat TestText.sql
-- CSOFF tabs
	SELECT * FROM users -- won't warn here if there is a tab character on line
-- CSON tabs

$ cat TestConfig.xml
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
          "-//Puppy Crawl//DTD Check Configuration 1.3//EN"
          "http://www.puppycrawl.com/dtds/configuration_1_3.dtd">

<module name="Checker">
    <property name="charset" value="UTF-8"/>
    <property name="severity" value="warning"/>
    <property name="haltOnException" value="false"/>
    <property name="fileExtensions" value="sql"/>
    <module name="FileTabCharacterCheck">
        <property name="id" value="tabs"/>
    </module>
    <module name="SuppressWithPlainTextCommentFilter">
        <property name="offCommentFormat" value="CSOFF tabs"/>
        <property name="onCommentFormat" value="CSON tabs"/>
        <property name="checkFormat" value="^tabs$"/>
        <property name="messageFormat" value="NonMatchingMessage"/>
    </module>
</module>

$ java -jar checkstyle-8.22-all.jar -c TestConfig.xml TestText.sql
Starting audit...
Audit done.
```

---------------

Identified in https://github.com/checkstyle/checkstyle/pull/6876#discussion_r300830774, this is an edge case where if the filter matches on the module ID (`tabs`) rather than the source name (`FileTabCharacterCheck`), the `messageFormat` is ignored. 

In the example above, the configured `"NonMatchingMessage"` message format does not match the `"File contains tab characters (this is the first instance)."` message, so the violation should not be suppressed.

Expected output:
```
$ java -jar checkstyle-8.22-all.jar -c TestConfig.xml TestText.sql
Starting audit...
[WARN] TestText.sql:2:1: File contains tab characters (this is the first instance). [tabs]
Audit done.
```

### PR DESCRIPTION
**Pull request by esilkensen**
This PR fixes #6887, updating the suppression `isMatch` logic to always check the message format (instead of only when the event source format matches). It adds a test case that would fail with the current master code.

Previous PR's applied the same logic to SuppressionCommentFilter (#6882) and SuppressWithNearbyCommentFilter (#6876).

### CODE REVIEW

File: src/main/java/com/puppycrawl/tools/checkstyle/filters/SuppressWithPlainTextCommentFilter.java [hunk 1]
```diff
@@ -588,6 +578,46 @@ private boolean isInScopeOfSuppression(AuditEvent event) {
...
+        /**
+         * Checks whether the {@link AuditEvent} message matches the message format.
+         * @param event {@link AuditEvent} instance.
+         * @return true if the {@link AuditEvent} message matches the message format.
+         */
+        private boolean isMessageMatch(AuditEvent event) {
+            final boolean match;
+            if (eventMessageRegexp == null) {
+                match = true;
+            }
```
Comment (romani) [inline src/main/java/com/puppycrawl/tools/checkstyle/filters/SuppressWithPlainTextCommentFilter.java]: Please make it like `boolean match = true;` and test `eventMessageRegexp != null`

Comment (esilkensen) [reply src/main/java/com/puppycrawl/tools/checkstyle/filters/SuppressWithPlainTextCommentFilter.java]: Ah, good call - I should have done it that way in the other two filters as well (SuppressionComment and SuppressWithNearbyComment) - I’d be happy to update those too if you’d like, if a minor change like that to align all 3 makes sense in this PR. But I understand if better to leave those alone in this PR.

Comment (romani) [reply src/main/java/com/puppycrawl/tools/checkstyle/filters/SuppressWithPlainTextCommentFilter.java]: No, let's do simple refactoring (no functional changes) for others in separate PR in commit message as "minor:"
