### PR TITLE
Issue #11605: Fix false positive for generic constructor without access modifier in InvalidJavadocPosition

### LINKED ISSUE #11605: InvalidJavadocPosition: false positive for the generic constructor without access modifier
Check documentation: https://checkstyle.sourceforge.io/config_javadoc.html#InvalidJavadocPosition

/var/tmp $ javac Test.java

/var/tmp $ cat Test.java
```
public class Test {
    /**
    * Test       
    */
    <E extends Enum> Test(E a) {
    }
}
```

/var/tmp $ cat config.xml
```
<!DOCTYPE module PUBLIC
        "-//Puppy Crawl//DTD Check Configuration 1.3//EN"
        "http://www.puppycrawl.com/dtds/configuration_1_3.dtd">
<module name="Checker">
    <module name="TreeWalker">
        <module name="InvalidJavadocPosition"/>
    </module>
</module>

```
/var/tmp $ RUN_LOCALE="-Duser.language=en -Duser.country=US"
/var/tmp $ java $RUN_LOCALE -jar checkstyle-X.XX-all.jar -c config.xml Test.java
````
Starting audit...                                                                                                                                                                                       
[ERROR] C:\Projects\checkstyle\Test.java:2:5: Javadoc comment is placed in the wrong location. [InvalidJavadocPosition]                                                                                 
Audit done.                                                                                                                                                                                             
Checkstyle ends with 1 errors.            
````

Expected: no validation error

### PR DESCRIPTION
**Pull request by stoyanK7**
Resolves #11605

---
Diff Regression config: https://gist.githubusercontent.com/stoyanK7/b3ab8c5d2245108a5366c5263e7079dc/raw/2b7519866985771115f2c6b31fad5070a1fb38b1/config.xml

### CODE REVIEW

**Comment by stoyanK7** [comment]
Github, generate report

File: src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/invalidjavadocposition/InputInvalidJavadocPosition.java [hunk 1]
```diff
@@ -65,4 +65,16 @@ void method() {
...
+class GenericConstructor {
+    /** valid */
+    <E extends String> GenericConstructor(E a) {}
+
+    /** valid */
+    private <E extends String> GenericConstructor() {}
+
+    private class InnerClass {
+        /** valid */
+        <E extends String> InnerClass() {}
```
Comment (strkkk) [inline src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/invalidjavadocposition/InputInvalidJavadocPosition.java:77]: please add violation examples

**Review by strkkk — CHANGES_REQUESTED** [review]

**Comment by strkkk** [comment]
circleci failure looks unrelated, I cannot restart job since my account is restricted

File: src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/invalidjavadocposition/InputInvalidJavadocPosition.java (hunk 1 above)
Comment (stoyanK7) [reply src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/invalidjavadocposition/InputInvalidJavadocPosition.java:85]: Done!

Comment (strkkk) [reply src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/invalidjavadocposition/InputInvalidJavadocPosition.java:85]: @stoyanK7 please add example like this (javadoc on same line)
```
/** javadoc */ <E extends String> InnerClass() {}
```

Comment (stoyanK7) [reply src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/invalidjavadocposition/InputInvalidJavadocPosition.java:85]: Done!

**Review by strkkk — APPROVED** [review]

**Review by pbludov — APPROVED** [review]

**Comment by stoyanK7** [comment]
Github, rebase

**Comment by romani** [comment]
Github, generate report

File: src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/invalidjavadocposition/InputInvalidJavadocPosition.java [hunk 2]
```diff
@@ -65,4 +65,26 @@ void method() {
         /** violation */ @Deprecated int variable3; // violation
     }
 }
+class GenericConstructor {
+    /** valid */
+    <E extends String> GenericConstructor(E a) {}
+
+    </** violation */E extends String>  GenericConstructor(E a, E b) {} // violation
```
Comment (romani) [inline src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/invalidjavadocposition/InputInvalidJavadocPosition.java:72]: Please add message to trailing comment, sorry that not all inputs migrated to such model

File: src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/invalidjavadocposition/InputInvalidJavadocPosition.java [hunk 3]
```diff
@@ -65,4 +65,26 @@ void method() {
...
+
+    <E extends String> /** violation */ GenericConstructor(E a, E b, E c) {} // violation
```
Comment (romani) [inline src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/invalidjavadocposition/InputInvalidJavadocPosition.java:74]: To avoid confusion:
Violation -> invalid.

**Review by romani — CHANGES_REQUESTED** [review]
Items

File: src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/invalidjavadocposition/InputInvalidJavadocPosition.java (hunk 2 above)
Comment (stoyanK7) [reply src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/invalidjavadocposition/InputInvalidJavadocPosition.java]: Done!

Comment (stoyanK7) [reply src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/invalidjavadocposition/InputInvalidJavadocPosition.java]: drone/pr should pass if you restart it, I think

File: src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/invalidjavadocposition/InputInvalidJavadocPosition.java (hunk 3 above)
Comment (stoyanK7) [reply src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/invalidjavadocposition/InputInvalidJavadocPosition.java]: @romani ping

**Review by romani — APPROVED** [review]
Ok to merge

**Review by rnveach — APPROVED** [review]
