### PR TITLE
Issue #17309: Add resources-noncompilable to the compilation

### LINKED ISSUE #17309: Google-style: Add resources-noncompilable inputs to the compilation by latest jdk
detected at https://github.com/checkstyle/checkstyle/pull/17288#issuecomment-3027726337

error of google formatter execution.
```
 src/it/resources-noncompilable/com/google/checkstyle/test/chapter4formatting/
    rule462horizontalwhitespace/InputWhitespaceAroundArrowCorrect.java:16:20: 
error: : or -> expected
      case String s when (s.equals("a")) -> {}

```

this is due gap in our complication coverage.

There is no comment what jdk should be used to compile
https://github.com/checkstyle/checkstyle/blob/02cbc39d617d231e8b5b84ce5b5d30752c4108d1/src/it/resources-noncompilable/com/google/checkstyle/test/chapter4formatting/rule462horizontalwhitespace/InputWhitespaceAroundArrowCorrect.java#L1-L4

 "non-compiled" usually means non-compiled by jdk11 but compiled by some latest jdk. And we have a just another gap here.

Expected:
Add such folders to CI for compilation on **all javac** CI jobs
https://github.com/checkstyle/checkstyle/blob/02cbc39d617d231e8b5b84ce5b5d30752c4108d1/.ci/validation.sh#L582-L585

### PR DESCRIPTION
**Pull request by mohitsatr**
fixes #17309

### CODE REVIEW

**Comment by mohitsatr** [comment]
https://github.com/checkstyle/checkstyle/blob/02c727f3c64b5a29286e7caeacb34c0b672af29f/.ci/validation.sh#L549

`enable-preview` is only available in javac 21 but the flag is turned on in every javac jobs. when try to run the workflow locally, it result in error.

```
$ ./.ci/validation.sh javac17
error: invalid source release 17 with --enable-preview
  (preview language features are only supported for release 21)
```

File: src/it/resources-noncompilable/com/google/checkstyle/test/chapter4formatting/rule462horizontalwhitespace/InputFormattedWhitespaceAroundArrow.java [hunk 1]
```diff
@@ -1,40 +1,48 @@
...
+      case Point(int x, int xy) when !(x >= 0 && y >= 0) -> {}
       default-> // violation ''->' is not preceded with whitespace.'
         {}
     }
-
     int x = switch (o) {
       case String s -> {
         switch (o2) {
-          case Integer newInt-> { // violation ''->' is not preceded with whitespace.'
+          case Integer nin when nin == 0-> { // violation ''->' is not preceded with whitespace.'
```
Comment (romani) [inline src/it/resources-noncompilable/com/google/checkstyle/test/chapter4formatting/rule462horizontalwhitespace/InputFormattedWhitespaceAroundArrow.java]: We need to rename this variable `nin` to avoid spelling error.
You can use `i`

**Review by romani — CHANGES_REQUESTED** [review]
Items

File: src/it/resources-noncompilable/com/google/checkstyle/test/chapter4formatting/rule462horizontalwhitespace/InputFormattedWhitespaceAroundArrow.java (hunk 1 above)
Comment (mohitsatr) [reply src/it/resources-noncompilable/com/google/checkstyle/test/chapter4formatting/rule462horizontalwhitespace/InputFormattedWhitespaceAroundArrow.java]: done.

**Review by romani — APPROVED** [review]
Thanks a lo
