### PR TITLE
Issue #9163: workaround for stack overflow tests

### LINKED ISSUE #9163: Minimize the stack size used for unit tests
After #5820 there is some inputs to prove that our checks don't fail with deep nested AST in the repo. The problem is that these inputs now cause [errors in CI](https://app.wercker.com/checkstyle/checkstyle/runs/build/5ff3492ec0593d001ddb5170?step=5ff3496d5405fc000975d1cc).

As possible solution, we can set the stack size with `-Xss` command line parameter to some small value, allowing us to minimize such input files. We can make the input files big enough to prove that our checks do not suffer from stack overflow, but other CI will not fall.

_Originally posted by @pbludov in https://github.com/checkstyle/checkstyle/issues/9149#issuecomment-755148414_

### PR DESCRIPTION
**Pull request by pbludov**
Fixes #9163 by reducing the number of lines in all `InputXXXNoStackOverflowError.java`

### CODE REVIEW

File: src/test/java/com/puppycrawl/tools/checkstyle/internal/utils/TestUtil.java [hunk 1]
```diff
@@ -40,6 +44,16 @@
 
 public final class TestUtil {
 
+    /**
+     * The stack size used in {@link #executeWithLimitedStackSize(Executable)}.
+     * This value should be as small as possible.
+     *
+     * @see <a href="https://www.baeldung.com/jvm-configure-stack-sizes">
+     *      Configuring Stack Sizes in the JVM</a>
+     * @noinspection MultiplyOrDivideByPowerOfTwo
```
Comment (pbludov) [inline src/test/java/com/puppycrawl/tools/checkstyle/internal/utils/TestUtil.java:53]: IDEA suggests to replace `144 * 1024` with `144 << 10`, but in such case is makes code less readable.

Comment (strkkk) [reply src/test/java/com/puppycrawl/tools/checkstyle/internal/utils/TestUtil.java:53]: I suggest to change it to number with good description in javadoc instead of mystic calculations, thus will eliminate all warmings

File: src/test/java/com/puppycrawl/tools/checkstyle/internal/utils/TestUtil.java [hunk 2]
```diff
@@ -237,4 +251,19 @@ public static int adjustFlushCountForOutputStreamClose(int flushCount) {
...
+     *
+     * @param executable the method to execute
+     * @see <a href="https://docs.oracle.com/javase/specs/jvms/se15/html/jvms-2.html#jvms-2.5.2">
+     *      JVMS &sect;2.5.2</a>
+     */
+    public static void executeWithLimitedStackSize(Executable executable) {
+        final Thread thread = new Thread(null, () -> {
+            assertDoesNotThrow(executable, "No exception expected");
+        }, "LimitedStackThread", MINIMAL_STACK_SIZE);
+        assertDoesNotThrow(() -> thread.join(10000),
```
Comment (strkkk) [inline src/test/java/com/puppycrawl/tools/checkstyle/internal/utils/TestUtil.java:265]: method name is `executeWithLimitedStackSize` but in fact time is limited as well, since there is a timeout for join.
btw, I wonder is there some library tool for such things instead of creating your own wrapper for parallel execution?

Comment (romani) [reply src/test/java/com/puppycrawl/tools/checkstyle/internal/utils/TestUtil.java:265]: `executeWithLimitedStackSizeAndTimeout`

**Review by romani — APPROVED** [review]
let speedup merging of this PR, this problem damages most other PRs

File: src/test/java/com/puppycrawl/tools/checkstyle/internal/utils/TestUtil.java (hunk 2 above)
Comment (pbludov) [reply src/test/java/com/puppycrawl/tools/checkstyle/internal/utils/TestUtil.java]: done

File: src/test/java/com/puppycrawl/tools/checkstyle/internal/utils/TestUtil.java (hunk 1 above)
Comment (pbludov) [reply src/test/java/com/puppycrawl/tools/checkstyle/internal/utils/TestUtil.java:53]: done

**Review by strkkk — APPROVED** [review]

**Comment by rnveach** [comment]
> Code like
verify(checkConfig, path, expected);
becomes
TestUtil.executeWithLimitedStackSize(() -> verify(checkConfig, path, expected));

The reason that this issue was created was we written a test that passed CI in the PR stage and was merged with no issue. We later found out that it did not work on all machines, more specifically machines with a small stack size. It is basically a machine specific issue that we can't tell if it will happen again in the future or not.

When we were talking and creating this issue, I was under the impression we would apply this minimal stack size to all tests, not just specific ones. Especially when @romani said `create special execution on low stack`.

I mean how can we know that we will run into this issue or not in the future? It is already been shown we can miss it once. 

We can't visualize stack sizes from just reading the code or the test. We can't guarantee we will see this during a PR. A special verify method makes no sense as we can't possibly know when specific code may run into a stack issue to apply to any tests.

@romani @pbludov @strkkk 
It makes more sense that we either make all tests work with minimal stacks or we just fix the test that is at the heart of this issue and come back to expanding tests to minimal stacks.

I say we don't chance this happening again and apply this change for all tests.

I say we take `TestUtil.executeWithLimitedStackSizeAndTimeout` and embed the minimal stack into `AbstractModuleTestSupport` inside `protected void verify(Checker checker, File[] processedFiles, String messageFileName, String... expected)`.

**Comment by romani** [comment]
I created https://github.com/checkstyle/checkstyle/issues/9253
to make simple CI jobs with clear definition of stack size.

But we still need this PR to be merged as our test Inputs are problematic.

**Comment by rnveach** [comment]
See https://github.com/checkstyle/checkstyle/issues/9253#issuecomment-774761543 , wrapping execution in a lambda looks like it might things worse. One point is Exceptions seem to go missing.

**Comment by romani** [comment]
@pbludov, please keep only input update in this PR, let's merge it

**Comment by pbludov** [comment]
> @pbludov, please keep only input update in this PR, let's merge it

done

**Review by rnveach — APPROVED** [review]

**Comment by rnveach** [comment]
TC is just a timeout.
