### PR TITLE
Issue #15058: New Check UnusedCatchParameterShouldBeUnnamed

### LINKED ISSUE #15058: Add Check Support for Java 21 Unnamed Variables & Patterns Syntax: New Check UnusedCatchParameterShouldBeUnnamed
child of #14942 
violate the non-use of the catch parameters. They should be unnamed.

---

**Config**

```XML
$ cat config.xml 
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
        "-//Checkstyle//DTD Checkstyle Configuration 1.3//EN"
        "https://checkstyle.org/dtds/configuration_1_3.dtd">

<module name="Checker">
    <module name="TreeWalker">
        <module name="UnusedCatchParameterShouldBeUnnamed"/>
    </module>
</module>
```

---

**Example**

```Java
 public class Test {
    void test(Object obj) {
        try {
            int x = 1 / 0;
        } catch (Exception e) {   // violation
            System.out.println("error");
        }
        try {
            int x = 1 / 0;
        } catch (Exception _) {
            System.out.println("error");
        }
    }
}
```

---

**Expected Output**

```PowerShell
$ java -jar checkstyle-10.19.0-all.jar -c config.xml Test.java 
Starting audit...
[ERROR] D:\Test.java:5:28:Unused catch parameter should be unnamed [UnusedCatchParameterShouldBeUnnamed]
Audit done.
Checkstyle ends with 1 errors.
```

>How we could suppress violations in this check for (ignore|ignored) naming convention

https://github.com/checkstyle/checkstyle/issues/15058#issuecomment-2254523431

### PR DESCRIPTION
**Pull request by mahfouz72**
closes #15058 

New module config: https://gist.githubusercontent.com/mahfouz72/afd57aa6e51ca161b7927acd959e5211/raw/3290828c8bb75105d18940f38a97265806b6a8bb/check.xml

### CODE REVIEW

**Comment by mahfouz72** [comment]
github, generate site

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedCatchParameterShouldBeUnnamedCheck.java [hunk 1]
```diff
@@ -0,0 +1,307 @@
...
+        return new int[] {
+            TokenTypes.LITERAL_CATCH,
+            TokenTypes.IDENT,
+        };
+    }
+
+    @Override
+    public void beginTree(DetailAST rootAST) {
+        catchParameter = null;
+    }
```
Comment (mahfouz72) [inline src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedCatchParameterShouldBeUnnamedCheck.java:117]:
```XML
 <suppressedMutations>
+  <mutation unstable="false">
+    <sourceFile>UnusedCatchParameterShouldBeUnnamedCheck.java</sourceFile>
+    <mutatedClass>com.puppycrawl.tools.checkstyle.checks.coding.UnusedCatchParameterShouldBeUnnamedCheck</mutatedClass>
+    <mutatedMethod>beginTree</mutatedMethod>
+    <mutator>org.pitest.mutationtest.engine.gregor.mutators.experimental.MemberVariableMutator</mutator>
+    <description>Removed assignment to member variable catchParameter</description>
+    <lineContent>catchParameter = null;</lineContent>
+  </mutation>
```

I can't think of a check execution scenario that will kill this mutation. 

When the check leaves a `LITERAL_CATCH` token, it logs a violation if the catch parameter was not used. After this, the `catchParameter` field is not accessed again until the next `LITERAL_CATCH` token is encountered and a new `catchParameter` instance is created.

This design ensures that the state of the `catchParameter` field is always fresh for each catch block, and the state from one catch block does not affect the processing of the next.  Therefore, even if the check processes multiple files, the state leakage from one file into the next will not affect the final output. But I am not sure about the multithreading

do you think it is safe if we removed `beignTree()` or any ideas to kill mutations using a normal check execution?

File: config/checkstyle-checks.xml [hunk 2]
```diff
@@ -581,6 +581,14 @@
     <module name="UnnecessarySemicolonAfterTypeMemberDeclaration"/>
     <module name="UnnecessarySemicolonInEnumeration"/>
     <module name="UnnecessarySemicolonInTryWithResources"/>
+    <module name="UnusedCatchParameterShouldBeUnnamed">
+      <!--
+        We should not use this check until we migrate to
+        java 21. Unnamed catch parameters will not compile on older
+        java versions.
+      -->
```
Comment (romani) [inline config/checkstyle-checks.xml:589]: We will not use it, because we are very explicit in handling of exceptions, never ignored.
If it ever going to happen, I would like `ignore` as name, to be very very explicit and done on ou purpose .

**Review by romani — CHANGES_REQUESTED** [review]
Item:

File: config/checkstyle-checks.xml (hunk 2 above)
Comment (mahfouz72) [reply config/checkstyle-checks.xml:589]: actually, we have a bunch of violations in our codebase, ideally, we should solve all of these and declare the catch parameter as unnamed (`_`) but we can't use this syntax now. I don't understand what stops us from using this check in the future?

> to be very very explicit and done on ou purpose .

according to Java 21 and above, if you want to be very very explicit that it is ignored on purpose you should declare it as unnamed.

```
[ERROR] [checkstyle] [ERROR] D:\CS\checkstyle\src\it\java\com\google\checkstyle\test\base\AbstractGoogleModuleTestSupport.java:203:16: Unused catch parameter 'ex' should be unnamed. [UnusedCatchParameterShouldBeUnnamed]
[ERROR] [checkstyle] [ERROR] D:\CS\checkstyle\src\it\java\org\checkstyle\base\AbstractCheckstyleModuleTestSupport.java:38:20: Unused catch parameter 'ignore' should be unnamed. [UnusedCatchParameterShouldBeUnnamed]
[ERROR] [checkstyle] [ERROR] D:\CS\checkstyle\src\main\java\com\puppycrawl\tools\checkstyle\LocalizedMessage.java:119:16: Unused catch parameter 'ignored' should be unnamed. [UnusedCatchParameterShouldBeUnnamed]
[ERROR] [checkstyle] [ERROR] D:\CS\checkstyle\src\main\java\com\puppycrawl\tools\checkstyle\Main.java:852:24: Unused catch parameter 'ignored' should be unnamed. [UnusedCatchParameterShouldBeUnnamed]
[ERROR] [checkstyle] [ERROR] D:\CS\checkstyle\src\main\java\com\puppycrawl\tools\checkstyle\PackageObjectFactory.java:314:16: Unused catch parameter 'ignore' should be unnamed. [UnusedCatchParameterShouldBeUnnamed]
[ERROR] [checkstyle] [ERROR] D:\CS\checkstyle\src\main\java\com\puppycrawl\tools\checkstyle\PackageObjectFactory.java:362:16: Unused catch parameter 'ignored' should be unnamed. [UnusedCatchParameterShouldBeUnnamed]
[ERROR] [checkstyle] [ERROR] D:\CS\checkstyle\src\main\java\com\puppycrawl\tools\checkstyle\XMLLogger.java:330:24: Unused catch parameter 'ignored' should be unnamed. [UnusedCatchParameterShouldBeUnnamed]
[ERROR] [checkstyle] [ERROR] D:\CS\checkstyle\src\main\java\com\puppycrawl\tools\checkstyle\checks\NewlineAtEndOfFileCheck.java:137:16: Unused catch parameter 'ignored' should be unnamed. [UnusedCatchParameterShouldBeUnnamed]
[ERROR] [checkstyle] [ERROR] D:\CS\checkstyle\src\main\java\com\puppycrawl\tools\checkstyle\checks\regexp\MultilineDetector.java:115:16: Unused catch parameter 'ignored' should be unnamed. [UnusedCatchParameterShouldBeUnnamed]
[ERROR] [checkstyle] [ERROR] D:\CS\checkstyle\src\main\java\com\puppycrawl\tools\checkstyle\site\SiteUtil.java:1245:20: Unused catch parameter 'ignored' should be unnamed. [UnusedCatchParameterShouldBeUnnamed]
[ERROR] [checkstyle] [ERROR] D:\CS\checkstyle\src\main\java\com\puppycrawl\tools\checkstyle\utils\CommonUtil.java:232:16: Unused catch parameter 'ignored' should be unnamed. [UnusedCatchParameterShouldBeUnnamed]
[ERROR] [checkstyle] [ERROR] D:\CS\checkstyle\src\main\java\com\puppycrawl\tools\checkstyle\utils\CommonUtil.java:378:16: Unused catch parameter 'ignored' should be unnamed. [UnusedCatchParameterShouldBeUnnamed]
[ERROR] [checkstyle] [ERROR] D:\CS\checkstyle\src\main\java\com\puppycrawl\tools\checkstyle\utils\FilterUtil.java:48:16: Unused catch parameter 'ignored' should be unnamed. [UnusedCatchParameterShouldBeUnnamed]
[ERROR] [checkstyle] [ERROR] D:\CS\checkstyle\src\test\java\com\puppycrawl\tools\checkstyle\checks\coding\FinalLocalVariableCheckTest.java:258:16: Unused catch parameter 'ex' should be unnamed. [UnusedCatchParameterShouldBeUnnamed]
[ERROR] [checkstyle] [ERROR] D:\CS\checkstyle\src\test\java\com\puppycrawl\tools\checkstyle\checks\coding\IllegalInstantiationCheckTest.java:158:16: Unused catch parameter 'ex' should be unnamed. [UnusedCatchParameterShouldBeUnnamed]
[ERROR] [checkstyle] [ERROR] D:\CS\checkstyle\src\test\java\com\puppycrawl\tools\checkstyle\checks\coding\IllegalTypeCheckTest.java:426:16: Unused catch parameter 'ex' should be unnamed. [UnusedCatchParameterShouldBeUnnamed]
[ERROR] [checkstyle] [ERROR] D:\CS\checkstyle\src\test\java\com\puppycrawl\tools\checkstyle\checks\coding\MatchXpathCheckTest.java:188:16: Unused catch parameter 'ignored' should be unnamed. [UnusedCatchParameterShouldBeUnnamed]
[ERROR] [checkstyle] [ERROR] D:\CS\checkstyle\src\test\java\com\puppycrawl\tools\checkstyle\checks\coding\MatchXpathCheckTest.java:208:16: Unused catch parameter 'ignored' should be unnamed. [UnusedCatchParameterShouldBeUnnamed]
[ERROR] [checkstyle] [ERROR] D:\CS\checkstyle\src\test\java\com\puppycrawl\tools\checkstyle\checks\coding\ModifiedControlVariableCheckTest.java:121:16: Unused catch parameter 'ex' should be unnamed. [UnusedCatchParameterShouldBeUnnamed]
[ERROR] [checkstyle] [ERROR] D:\CS\checkstyle\src\test\java\com\puppycrawl\tools\checkstyle\checks\coding\ModifiedControlVariableCheckTest.java:129:16: Unused catch parameter 'ex' should be unnamed. [UnusedCatchParameterShouldBeUnnamed]
[ERROR] [checkstyle] [ERROR] D:\CS\checkstyle\src\test\java\com\puppycrawl\tools\checkstyle\checks\coding\ReturnCountCheckTest.java:126:16: Unused catch parameter 'ex' should be unnamed. [UnusedCatchParameterShouldBeUnnamed]
[ERROR] [checkstyle] [ERROR] D:\CS\checkstyle\src\test\java\com\puppycrawl\tools\checkstyle\checks\coding\ReturnCountCheckTest.java:134:16: Unused catch parameter 'ex' should be unnamed. [UnusedCatchParameterShouldBeUnnamed]
[ERROR] [checkstyle] [ERROR] D:\CS\checkstyle\src\test\java\com\puppycrawl\tools\checkstyle\filters\SuppressionFilterTest.java:263:16: Unused catch parameter 'ignored' should be unnamed. [UnusedCatchParameterShouldBeUnnamed]
[ERROR] [checkstyle] [ERROR] D:\CS\checkstyle\src\test\java\com\puppycrawl\tools\checkstyle\filters\SuppressionsLoaderTest.java:227:16: Unused catch parameter 'ignored' should be unnamed. [UnusedCatchParameterShouldBeUnnamed]
[ERROR] [checkstyle] [ERROR] D:\CS\checkstyle\src\test\java\com\puppycrawl\tools\checkstyle\internal\AllChecksTest.java:450:20: Unused catch parameter 'ex' should be unnamed. [UnusedCatchParameterShouldBeUnnamed]
[ERROR] [checkstyle] [ERROR] D:\CS\checkstyle\src\test\java\com\puppycrawl\tools\checkstyle\internal\CommitValidationTest.java:306:16: Unused catch parameter 'ignored' should be unnamed. [UnusedCatchParameterShouldBeUnnamed]
[ERROR] [checkstyle] [ERROR] D:\CS\checkstyle\src\test\java\com\puppycrawl\tools\checkstyle\internal\XdocsPagesTest.java:1355:20: Unused catch parameter 'ignored' should be unnamed. [UnusedCatchParameterShouldBeUnnamed]
[ERROR] [checkstyle] [ERROR] D:\CS\checkstyle\src\test\java\com\puppycrawl\tools\checkstyle\internal\XdocsPagesTest.java:1815:24: Unused catch parameter 'ignore' should be unnamed. [UnusedCatchParameterShouldBeUnnamed]
[ERROR] [checkstyle] [ERROR] D:\CS\checkstyle\src\test\java\com\puppycrawl\tools\checkstyle\internal\XdocsPagesTest.java:1888:20: Unused catch parameter 'ignore' should be unnamed. [UnusedCatchParameterShouldBeUnnamed]
[ERROR] [checkstyle] [ERROR] D:\CS\checkstyle\src\test\java\com\puppycrawl\tools\checkstyle\internal\utils\CheckUtil.java:286:16: Unused catch parameter 'ignored' should be unnamed. [UnusedCatchParameterShouldBeUnnamed]
```

Comment (mahfouz72) [reply config/checkstyle-checks.xml:589]: we also could update this check to ignore the names "ignore" and "ignored" and not be violated

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedCatchParameterShouldBeUnnamedCheck.java [hunk 3]
```diff
@@ -0,0 +1,307 @@
...
+ * <li>
+ * {@code unused.catch.parameter}
+ * </li>
+ * </ul>
+ *
+ * @since 10.18.0
+ *
+ */
+
+@FileStatefulCheck
```
Comment (nrmancuso) [inline src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedCatchParameterShouldBeUnnamedCheck.java:72]: Is there no way to make this check stateless? I can't imagine that it is that crazy to just check LITERAL_CATCH only, and find the parameter name.

**Review by nrmancuso — CHANGES_REQUESTED** [review]
Item to discuss before anything else:

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedCatchParameterShouldBeUnnamedCheck.java (hunk 1 above)
Comment (nrmancuso) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedCatchParameterShouldBeUnnamedCheck.java:117]: Remove it

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedCatchParameterShouldBeUnnamedCheck.java [hunk 4]
```diff
@@ -0,0 +1,307 @@
...
+     */
+    private void visitCatchParameter(DetailAST catchAst) {
+        final DetailAST catchParameterAst = catchAst.findFirstToken(TokenTypes.PARAMETER_DEF);
+        final String catchParameterName =
+                catchParameterAst.findFirstToken(TokenTypes.IDENT).getText();
+
+        if (!"_".equals(catchParameterName)) {
+            catchParameter = new CatchParameter(catchParameterName,
+                                    catchAst, catchParameterAst);
+        }
```
Comment (nrmancuso) [inline src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedCatchParameterShouldBeUnnamedCheck.java:148]: Why not just assign this always, then check at the end if the catch parameter is unnamed?

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedCatchParameterShouldBeUnnamedCheck.java [hunk 5]
```diff
@@ -0,0 +1,307 @@
...
+            log(catchParameter.getParameterDefAst(),
+                    MSG_UNUSED_CATCH_PARAMETER,
+                    catchParameter.getName());
+        }
+    }
+
+    /**
+     * Maintains information about the catch parameter.
+     */
+    private static final class CatchParameter {
```
Comment (nrmancuso) [inline src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedCatchParameterShouldBeUnnamedCheck.java:228]:
```suggestion
    private static final class CatchParameterDetails {
```

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedCatchParameterShouldBeUnnamedCheck.java [hunk 6]
```diff
@@ -0,0 +1,307 @@
...
+
+        /**
+         * Ast of type {@link TokenTypes#PARAMETER_DEF} to use it when logging.
+         */
+        private final DetailAST parameterDefAst;
+
+        /**
+         * Is the variable used.
+         */
+        private boolean used;
```
Comment (nrmancuso) [inline src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedCatchParameterShouldBeUnnamedCheck.java:249]:
```suggestion
        private boolean isUsed;
```

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedCatchParameterShouldBeUnnamedCheck.java [hunk 7]
```diff
@@ -0,0 +1,307 @@
...
+        /**
+         * The scope of the catch parameter is determined by the ast of type
+         * {@link TokenTypes#LITERAL_CATCH}.
+         */
+        private final DetailAST scope;
+
+        /**
+         * Ast of type {@link TokenTypes#PARAMETER_DEF} to use it when logging.
+         */
+        private final DetailAST parameterDefAst;
```
Comment (nrmancuso) [inline src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedCatchParameterShouldBeUnnamedCheck.java:244]:
```suggestion
        private final DetailAST parameterDefinition;
```

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedCatchParameterShouldBeUnnamedCheck.java [hunk 8]
```diff
@@ -0,0 +1,307 @@
...
+    public void beginTree(DetailAST rootAST) {
+        catchParameter = null;
+    }
+
+    @Override
+    public void visitToken(DetailAST ast) {
+        if (ast.getType() == TokenTypes.LITERAL_CATCH) {
+            visitCatchParameter(ast);
+        }
+        else {
```
Comment (nrmancuso) [inline src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedCatchParameterShouldBeUnnamedCheck.java:124]:
```suggestion
        else if (...Check.isCatchParameterIdentifier(ast)) {
```

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedCatchParameterShouldBeUnnamedCheck.java [hunk 9]
```diff
@@ -0,0 +1,307 @@
...
+            visitIdent(ast);
```
Comment (nrmancuso) [inline src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedCatchParameterShouldBeUnnamedCheck.java:125]:
```suggestion
            visitICatchParameterIdentifier(ast);
```

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedCatchParameterShouldBeUnnamedCheck.java [hunk 10]
```diff
@@ -0,0 +1,307 @@
...
+    /**
+     * A key is pointing to the warning message text in "messages.properties"
+     * file.
+     */
+    public static final String MSG_UNUSED_CATCH_PARAMETER = "unused.catch.parameter";
+
+    /**
+     * An array of unacceptable parent of ast of type {@link TokenTypes#IDENT}.
+     */
+    private static final int[] UNACCEPTABLE_PARENT_OF_IDENT = {
```
Comment (nrmancuso) [inline src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedCatchParameterShouldBeUnnamedCheck.java:84]: `UNACCEPTABLE` <- this always bothers me, why is it unacceptable? Can we think of some more descriptive name for this?

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedCatchParameterShouldBeUnnamedCheck.java [hunk 11]
```diff
@@ -0,0 +1,307 @@
...
+     * and check if it is a candidate for a catch parameter usage.
+     *
+     * @param identAST token representing {@link TokenTypes#IDENT}
+     */
+    private void visitIdent(DetailAST identAST) {
+        final boolean isCatchParameter = identAST.getParent().getParent()
+                                                .getType() == TokenTypes.LITERAL_CATCH;
+
+        if (!isCatchParameter
+                && (!TokenUtil.isOfType(identAST.getParent(), UNACCEPTABLE_PARENT_OF_IDENT)
```
Comment (nrmancuso) [inline src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedCatchParameterShouldBeUnnamedCheck.java:162]: Conceptually, is this condition part of determining if something is a isCatchParameterIdentifier? If so, we should add it to the static method I suggested above.

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedCatchParameterShouldBeUnnamedCheck.java [hunk 12]
```diff
@@ -0,0 +1,307 @@
...
+
+    /**
+     * Check if the given {@link TokenTypes#IDENT} is a child of a dot operator
+     * and should be checked for usage.
+     *
+     * @param identAst token representing {@link TokenTypes#IDENT}
+     * @return true if the given {@link TokenTypes#IDENT} is a child of a dot operator
+     *     and should be checked for usage.
+     */
+    private static boolean shouldCheckDotChild(DetailAST identAst) {
```
Comment (nrmancuso) [inline src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedCatchParameterShouldBeUnnamedCheck.java:176]: What is a dotChild? Like, is this a qualified name?

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedCatchParameterShouldBeUnnamedCheck.java [hunk 13]
```diff
@@ -0,0 +1,307 @@
...
+
+    /**
+     * Check the given {@link TokenTypes#IDENT} and
+     * register it as used if it is the catch parameter.
+     *
+     * @param identAst token representing {@link TokenTypes#IDENT}
+     */
+    private void checkIdentifier(DetailAST identAst) {
+        if (catchParameter != null
+                && !isLeftHandSideValue(identAst)
```
Comment (nrmancuso) [inline src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedCatchParameterShouldBeUnnamedCheck.java:190]: So we don't count reassignment as usage? Judging by the test cases below, we currently do. What am I missing?

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedCatchParameterShouldBeUnnamedCheck.java [hunk 14]
```diff
@@ -0,0 +1,307 @@
...
+                && identAst != parent.getLastChild();
+    }
+
+    /**
+     * Log the catch parameter if it is not used after
+     * leaving its scope.
+     *
+     * @param scopeAst ast of the current scope
+     */
+    private void logUnusedCatchParameter(DetailAST scopeAst) {
```
Comment (nrmancuso) [inline src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedCatchParameterShouldBeUnnamedCheck.java:214]: This method name doesn't really make sense (we don't always log here), I think we can just add this method body to the leaveToken method.

**Review by nrmancuso — CHANGES_REQUESTED** [review]
First pass:

File: config/checkstyle-checks.xml (hunk 2 above)
Comment (nrmancuso) [reply config/checkstyle-checks.xml:589]: > we also could update this check to ignore the names "ignore" and "ignored" and not be violated

It is better to use some suppression for this; in Java 21+ the correct way to do this will be unnamed variables.

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedCatchParameterShouldBeUnnamedCheck.java [hunk 15]
```diff
@@ -0,0 +1,307 @@
...
+    }
+
+    /**
+     * Visit ast of type {@link TokenTypes#LITERAL_CATCH}
+     * and set the catch parameter.
+     *
+     * @param catchAst token representing {@link TokenTypes#LITERAL_CATCH}
+     */
+    private void visitCatchParameter(DetailAST catchAst) {
+        final DetailAST catchParameterAst = catchAst.findFirstToken(TokenTypes.PARAMETER_DEF);
```
[the remark this answers is not in the document]
Comment (mahfouz72) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedCatchParameterShouldBeUnnamedCheck.java:141]: This CatchParameter class is just a holder for parameter details. why would we add a method related to AST in this class

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedCatchParameterShouldBeUnnamedCheck.java [hunk 16]
```diff
@@ -0,0 +1,307 @@
...
+        /**
+         * The name of the catch parameter.
+         */
+        private final String name;
+
+        /**
+         * The scope of the catch parameter is determined by the ast of type
+         * {@link TokenTypes#LITERAL_CATCH}.
+         */
+        private final DetailAST scope;
```
[the remark this answers is not in the document]
Comment (mahfouz72) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedCatchParameterShouldBeUnnamedCheck.java:239]: yea, I was having it as `SLIST`  but pitest was complaining (and it is expected mutation can't be killed) so I left it as  `LITERAL_CATCH`.

File: config/checkstyle-checks.xml (hunk 2 above)
Comment (romani) [reply config/checkstyle-checks.xml:589]: please do wording like:
```
Unnamed catch parameters will not compile on
        java versions before 21. As we migrate to jdk 21 
   we will use xpath to avoid violation on names like 'ignored'. 
```

Comment (romani) [reply config/checkstyle-checks.xml:589]: please add xpath test to show that Check able to suppress by name.

Please add this xpath to issue description to let users know of migrational workaround or just workaround on existing pattern. So users can start to use it rightaway, and deal with old code later on.

Comment (romani) [reply config/checkstyle-checks.xml:589]: >ReturnCountCheckTest.java:126:16: Unused catch parameter 'ex' should be unnamed. 

this is bad, and user should decided to put `ignore`/`ignored` or `_` .

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedCatchParameterShouldBeUnnamedCheck.java (hunk 13 above)
Comment (mahfouz72) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedCatchParameterShouldBeUnnamedCheck.java:190]: Yes we don't count reassignment as usage. here is its test case : https://github.com/checkstyle/checkstyle/blob/c50d03687247b8f5e303845ded14a7ef0d346abe/src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/unusedcatchparametershouldbeunnamed/InputUnusedCatchParameterShouldBeUnnamed.java#L49-L53


>  Judging by the test cases below, we currently do.

can you point to this?

Comment (mahfouz72) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedCatchParameterShouldBeUnnamedCheck.java:190]: Note I don't consider the test case below to be a reassignment.

https://github.com/checkstyle/checkstyle/blob/c50d03687247b8f5e303845ded14a7ef0d346abe/src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/unusedcatchparametershouldbeunnamed/InputUnusedCatchParameterShouldBeUnnamed.java#L55-L60

File: src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/unusedcatchparametershouldbeunnamed/InputUnusedCatchParameterShouldBeUnnamed.java
[the remark this answers is not in the document]
Comment (mahfouz72) [reply src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/unusedcatchparametershouldbeunnamed/InputUnusedCatchParameterShouldBeUnnamed.java:1]: done 

> Nested try catch in catch block with usage/nonusage of outer parameter

I noticed that the check is not working for nested we just save in instance and overwrite it :) it should be list

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedCatchParameterShouldBeUnnamedCheck.java (hunk 15 above)
[the remark this answers is not in the document]
Comment (mahfouz72) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedCatchParameterShouldBeUnnamedCheck.java]: done

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedCatchParameterShouldBeUnnamedCheck.java (hunk 4 above)
Comment (mahfouz72) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedCatchParameterShouldBeUnnamedCheck.java]: done

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedCatchParameterShouldBeUnnamedCheck.java (hunk 6 above)
Comment (mahfouz72) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedCatchParameterShouldBeUnnamedCheck.java]: done

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedCatchParameterShouldBeUnnamedCheck.java (hunk 8 above)
Comment (mahfouz72) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedCatchParameterShouldBeUnnamedCheck.java]: done

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedCatchParameterShouldBeUnnamedCheck.java (hunk 9 above)
Comment (mahfouz72) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedCatchParameterShouldBeUnnamedCheck.java]: I removed this method

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedCatchParameterShouldBeUnnamedCheck.java (hunk 10 above)
Comment (mahfouz72) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedCatchParameterShouldBeUnnamedCheck.java]: This list means that if these tokens are ident parents then this ident can't be a candidate for catch parameter ident. I renamed it to `INVALID_CATCH_PARAM_IDENT_PARENTS`

Note: DOT can be a parent but we exclude it as invalid because it needs further check in `shouldCheckDotChild`

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedCatchParameterShouldBeUnnamedCheck.java (hunk 11 above)
Comment (mahfouz72) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedCatchParameterShouldBeUnnamedCheck.java]: done

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedCatchParameterShouldBeUnnamedCheck.java (hunk 12 above)
Comment (mahfouz72) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedCatchParameterShouldBeUnnamedCheck.java:169]: something like. if the ident is the first child of the dot(left of it), then it is a candidate for catch parameter, if it is not (right of dot) then it can't be catch parameter ident, and it is anything else like `this.e` or `super.e`

```
`--DOT -> . [7:35]
     |--LITERAL_THIS -> this [7:31]
     `--IDENT -> e [7:36]        <-- not first child, can't be a candidate for the catch parameter
```

```
 |--DOT -> . [7:13]
     |--IDENT -> e [7:12]  first child, a candidate for the catch parameter
     `--IDENT -> printStackTrace [7:14]
```

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedCatchParameterShouldBeUnnamedCheck.java (hunk 14 above)
Comment (mahfouz72) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedCatchParameterShouldBeUnnamedCheck.java]: done

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedCatchParameterShouldBeUnnamedCheck.java (hunk 6 above)
Comment (mahfouz72) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedCatchParameterShouldBeUnnamedCheck.java]: `[WARNING] PMD Failure: com.puppycrawl.tools.checkstyle.checks.coding.CatchParameterDetails:211 Rule:AvoidFieldNameMatchingMethodName Priority:3 Field isUsed has the same name as a method.`

reverted to used. Do you agree? I am not with changing the method name from `isUsed()`

File: config/checkstyle-checks.xml (hunk 2 above)
Comment (nrmancuso) [reply config/checkstyle-checks.xml:589]: > > ReturnCountCheckTest.java:126:16: Unused catch parameter 'ex' should be unnamed.
> 
> this is bad, and user should decided to put `ignore`/`ignored` or `_` .

Please restate this, I do not understand what this means.

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedCatchParameterShouldBeUnnamedCheck.java (hunk 6 above)
Comment (nrmancuso) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedCatchParameterShouldBeUnnamedCheck.java:211]: I am good with reverting it, it's not a big deal

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedCatchParameterShouldBeUnnamedCheck.java (hunk 13 above)
Comment (nrmancuso) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedCatchParameterShouldBeUnnamedCheck.java]: https://github.com/checkstyle/checkstyle/pull/15358#discussion_r1691830997 is weird to me.If we were to make `e` unnamed, we would have to remove this reassignment (even though it does nothing). I suppose I am good with this, let's get this check into the hands of users and go from there.

Comment (nrmancuso) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedCatchParameterShouldBeUnnamedCheck.java]: Leaving this one unresolved so others can see.

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedCatchParameterShouldBeUnnamedCheck.java (hunk 12 above)
Comment (nrmancuso) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedCatchParameterShouldBeUnnamedCheck.java:169]: We need to name this something meaningful, like `isMethodInvocation``?

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedCatchParameterShouldBeUnnamedCheck.java [hunk 17]
```diff
@@ -0,0 +1,269 @@
...
+     * @param identAST token representing {@link TokenTypes#IDENT}
+     * @return true if the given {@link TokenTypes#IDENT} is a catch parameter ident candidate
+     */
+    private static boolean isCatchParameterIdentifierCandidate(DetailAST identAST) {
+        // we should ignore the ident if it is in the exception declaration
+        final boolean catchParameterDeclaration = identAST.getParent().getParent()
+                                                .getType() == TokenTypes.LITERAL_CATCH;
+
+        return !catchParameterDeclaration
+                && (!TokenUtil.isOfType(identAST.getParent(), INVALID_CATCH_PARAM_IDENT_PARENTS)
```
[the remark this answers is not in the document]
Comment (nrmancuso) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedCatchParameterShouldBeUnnamedCheck.java:157]:
```suggestion
  return !isCatchParameterDeclaration && (hasValidParentToken || isMethodInvocation);
```

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedCatchParameterShouldBeUnnamedCheck.java [hunk 18]
```diff
@@ -0,0 +1,269 @@
...
+    /**
+     * Visit ast of type {@link TokenTypes#IDENT}
+     * and check if it is a candidate for a catch parameter identifier.
+     *
+     * @param identAST token representing {@link TokenTypes#IDENT}
+     * @return true if the given {@link TokenTypes#IDENT} is a catch parameter ident candidate
+     */
+    private static boolean isCatchParameterIdentifierCandidate(DetailAST identAST) {
+        // we should ignore the ident if it is in the exception declaration
+        final boolean catchParameterDeclaration = identAST.getParent().getParent()
```
Comment (nrmancuso) [inline src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedCatchParameterShouldBeUnnamedCheck.java:153]:
```suggestion
        final boolean isCatchParameterDeclaration = identAST.getParent().getParent()
```

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedCatchParameterShouldBeUnnamedCheck.java [hunk 19]
```diff
@@ -0,0 +1,269 @@
...
+                && identAst == parent.getFirstChild();
+    }
+
+    /**
+     * Check if the given {@link TokenTypes#IDENT} is a left hand side value.
+     *
+     * @param identAst token representing {@link TokenTypes#IDENT}
+     * @return true if the given {@link TokenTypes#IDENT} is a left hand side value.
+     */
+    private static boolean isLeftHandSideValue(DetailAST identAst) {
```
Comment (nrmancuso) [inline src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedCatchParameterShouldBeUnnamedCheck.java:181]:
```suggestion
    private static boolean isLeftHandOfAssignment(DetailAST identAst) {
```

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedCatchParameterShouldBeUnnamedCheck.java [hunk 20]
```diff
@@ -0,0 +1,269 @@
...
+            catchParameters.stream()
+                    .filter(parameter -> parameter.getName().equals(ast.getText()))
+                    .findFirst()
+                    .ifPresent(CatchParameterDetails::registerAsUsed);
+        }
+    }
+
+    @Override
+    public void leaveToken(DetailAST ast) {
+        final CatchParameterDetails catchParameter = catchParameters.peekLast();
```
Comment (nrmancuso) [inline src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedCatchParameterShouldBeUnnamedCheck.java:133]: Let's use this like a stack instead, I think more people will be familiar with it

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedCatchParameterShouldBeUnnamedCheck.java [hunk 21]
```diff
@@ -0,0 +1,269 @@
...
+        };
+    }
+
+    @Override
+    public void visitToken(DetailAST ast) {
+        if (ast.getType() == TokenTypes.LITERAL_CATCH) {
+            final CatchParameterDetails catchParameter = new CatchParameterDetails(ast);
+            catchParameters.add(catchParameter);
+        }
+        else if (isCatchParameterIdentifierCandidate(ast) && !isLeftHandSideValue(ast)) {
```
Comment (nrmancuso) [inline src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedCatchParameterShouldBeUnnamedCheck.java:123]:
```suggestion
        else if (isCatchParameterIdentifierCandidate(ast) && !isLeftHandSideValue(ast)) {
            // we do not count reassignment as usage
```

File: src/main/resources/com/puppycrawl/tools/checkstyle/meta/checks/coding/UnusedCatchParameterShouldBeUnnamedCheck.xml [hunk 22]
```diff
@@ -0,0 +1,39 @@
...
+     &lt;li&gt;
+         Improves code readability by clearly indicating which parameters are unused.
+     &lt;/li&gt;
+     &lt;li&gt;
+         Follows Java conventions for denoting unused parameters with an underscore ({@code _})
+     &lt;/li&gt;
+     &lt;li&gt;
+         Helps developers quickly identify parameters that are intentionally ignored,
+         reducing potential confusion and aiding in code maintenance.
+     &lt;/li&gt;
```
Comment (nrmancuso) [inline src/main/resources/com/puppycrawl/tools/checkstyle/meta/checks/coding/UnusedCatchParameterShouldBeUnnamedCheck.xml:23]:
```suggestion
```

I think this one is redundant

File: src/main/resources/com/puppycrawl/tools/checkstyle/meta/checks/coding/UnusedCatchParameterShouldBeUnnamedCheck.xml [hunk 23]
```diff
@@ -0,0 +1,39 @@
+<?xml version="1.0" encoding="UTF-8"?>
+<checkstyle-metadata>
+   <module>
+      <check fully-qualified-name="com.puppycrawl.tools.checkstyle.checks.coding.UnusedCatchParameterShouldBeUnnamedCheck"
+             name="UnusedCatchParameterShouldBeUnnamed"
+             parent="com.puppycrawl.tools.checkstyle.TreeWalker">
+         <description>&lt;p&gt;
+ Ensures that catch parameters that are not used are declared as unnamed parameter.
```
Comment (nrmancuso) [inline src/main/resources/com/puppycrawl/tools/checkstyle/meta/checks/coding/UnusedCatchParameterShouldBeUnnamedCheck.xml:8]:
```suggestion
 Ensures that catch parameters that are not used are declared as an unnamed variable.
```

**Review by nrmancuso — CHANGES_REQUESTED** [review]
Last from me:

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedCatchParameterShouldBeUnnamedCheck.java (hunk 17 above)
[the remark this answers is not in the document]
Comment (mahfouz72) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedCatchParameterShouldBeUnnamedCheck.java]: done

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedCatchParameterShouldBeUnnamedCheck.java (hunk 18 above)
Comment (mahfouz72) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedCatchParameterShouldBeUnnamedCheck.java]: done

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedCatchParameterShouldBeUnnamedCheck.java (hunk 19 above)
Comment (mahfouz72) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedCatchParameterShouldBeUnnamedCheck.java]: done

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedCatchParameterShouldBeUnnamedCheck.java (hunk 20 above)
Comment (mahfouz72) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedCatchParameterShouldBeUnnamedCheck.java]: done

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedCatchParameterShouldBeUnnamedCheck.java (hunk 21 above)
Comment (mahfouz72) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedCatchParameterShouldBeUnnamedCheck.java]: done

File: src/main/resources/com/puppycrawl/tools/checkstyle/meta/checks/coding/UnusedCatchParameterShouldBeUnnamedCheck.xml (hunk 22 above)
Comment (mahfouz72) [reply src/main/resources/com/puppycrawl/tools/checkstyle/meta/checks/coding/UnusedCatchParameterShouldBeUnnamedCheck.xml]: done

File: src/main/resources/com/puppycrawl/tools/checkstyle/meta/checks/coding/UnusedCatchParameterShouldBeUnnamedCheck.xml (hunk 23 above)
Comment (mahfouz72) [reply src/main/resources/com/puppycrawl/tools/checkstyle/meta/checks/coding/UnusedCatchParameterShouldBeUnnamedCheck.xml]: done

**Comment by mahfouz72** [comment]
github, generate report

**Review by nrmancuso — APPROVED** [review]
I have spot checked the report, there is far too many violations to check all of them. This is a good first implementation that we can build on, let's get this check into the hands of users.

Great work!

File: config/checkstyle-checks.xml (hunk 2 above)
Comment (romani) [reply config/checkstyle-checks.xml:589]: I meant we will fix this `ReturnCountCheckTest.java:126:16` to be named `ignored`. But it will be in future.

Comment (romani) [reply config/checkstyle-checks.xml:589]: Wording of comment should be as I suggested at https://github.com/checkstyle/checkstyle/pull/15358/files#r1691538791

File: src/it/java/org/checkstyle/suppressionxpathfilter/XpathRegressionUnusedCatchParameterShouldBeUnnamedTest.java [hunk 24]
```diff
@@ -0,0 +1,120 @@
...
+import org.junit.jupiter.api.Test;
+
+import com.puppycrawl.tools.checkstyle.DefaultConfiguration;
+import com.puppycrawl.tools.checkstyle.checks.coding.UnusedCatchParameterShouldBeUnnamedCheck;
+
+public class XpathRegressionUnusedCatchParameterShouldBeUnnamedTest
+        extends AbstractXpathTestSupport {
+
+    private final String checkName = UnusedCatchParameterShouldBeUnnamedCheck.class
+                                                .getSimpleName();
```
Comment (romani) [inline src/it/java/org/checkstyle/suppressionxpathfilter/XpathRegressionUnusedCatchParameterShouldBeUnnamedTest.java:35]:
```
rivate final String checkName = 
        UnusedCatchParameterShouldBeUnnamedCheck.class.getSimpleName();
```

**Review by romani — CHANGES_REQUESTED** [review]
2 items above to  be done:
https://github.com/checkstyle/checkstyle/pull/15358#discussion_r1691538791
https://github.com/checkstyle/checkstyle/pull/15358#discussion_r1691544092

the only item from me:

**Comment by nrmancuso** [comment]
> 2 items above to be done: [#15358 (comment)](https://github.com/checkstyle/checkstyle/pull/15358#discussion_r1691538791) [#15358 (comment)](https://github.com/checkstyle/checkstyle/pull/15358#discussion_r1691544092)

done

https://github.com/checkstyle/checkstyle/issues/15058#issuecomment-2254523431

File: src/main/resources/com/puppycrawl/tools/checkstyle/checks/coding/messages_fr.properties [hunk 25]
```diff
@@ -35,7 +35,7 @@ missing.ctor=Il manque un constructeur à la classe.
 missing.package.declaration=Déclaration de package manquante.
 missing.super.call=La méthode ''{0}'' devrait appeler ''super.{0}''.
 missing.switch.default=Il manque le cas "default" dans le bloc "switch".
-missing.switch.nullcase=Switch utilisant des types de r�f�rence doit avoir un cas nul.
+missing.switch.nullcase=Switch utilisant des types de r f rence doit avoir un cas nul.
```
Comment (romani) [inline src/main/resources/com/puppycrawl/tools/checkstyle/checks/coding/messages_fr.properties:38]: Unrelated messes are affected.
Unicode symbols are replaced to space, not good.
There are few updates like this

**Review by romani — CHANGES_REQUESTED** [review]
Items

File: src/main/resources/com/puppycrawl/tools/checkstyle/checks/coding/messages_fr.properties (hunk 25 above)
Comment (nrmancuso) [reply src/main/resources/com/puppycrawl/tools/checkstyle/checks/coding/messages_fr.properties]: Weird, fixed

**Review by romani — APPROVED** [review]
Ok to merge

**Comment by nrmancuso** [comment]
@rnveach ping

**Comment by romani** [comment]
This PR should be rebased, as I just merged another new Check

**Comment by romani** [comment]
rebased in web, and CI should fail due to numbers of Check count.

**Comment by nrmancuso** [comment]
> rebased in web, and CI should fail due to numbers of Check count.

fixed

File: src/xdocs/checks/coding/unusedcatchparametershouldbeunnamed.xml [hunk 26]
```diff
@@ -0,0 +1,121 @@
...
+        </ul>
+        <p>
+          See the <a href="https://docs.oracle.com/en/java/javase/21/docs/specs/unnamed-jls.html">
+          Java Language Specification</a>
+          for more information about unnamed variables.
+        </p>
+        <p>
+          <b>Attention</b>: This check should be activated only on source code that is
+          compiled by jdk21 or higher;
+          unnamed catch parameters come out as the first preview in Java 21.
```
Comment (rnveach) [inline src/xdocs/checks/coding/unusedcatchparametershouldbeunnamed.xml:35]: `come out` => `came out`

**Review by rnveach — CHANGES_REQUESTED** [review]
still reviewing

File: src/xdocs/checks/coding/unusedcatchparametershouldbeunnamed.xml (hunk 26 above)
Comment (mahfouz72) [reply src/xdocs/checks/coding/unusedcatchparametershouldbeunnamed.xml]: done

File: src/xdocs/checks/coding/unusedcatchparametershouldbeunnamed.xml [hunk 27]
```diff
@@ -0,0 +1,121 @@
...
+        <p>
+          Rationale:
+        </p>
+        <ul>
+          <li>
+            Improves code readability by clearly indicating which parameters are unused.
+          </li>
+          <li>
+            Follows Java conventions for denoting unused parameters with an
+            underscore (<code>_</code>)
```
[the remark this answers is not in the document]
Comment (mahfouz72) [reply src/xdocs/checks/coding/unusedcatchparametershouldbeunnamed.xml]: done

File: src/main/resources/com/puppycrawl/tools/checkstyle/checks/coding/messages_fi.properties [hunk 28]
```diff
@@ -64,8 +64,9 @@ unnecessary.paren.literal=Tarpeettomia sulkuja noin kirjaimellisesti ''{0}''.
 unnecessary.paren.return=Tarpeettomia sulkuja noin paluuarvo.
 unnecessary.paren.string=Tarpeettomia sulkuja noin merkkijono {0}.
 unnecessary.semicolon=Tarpeeton puolipiste.
+unused.catch.parameter=Käyttämättömän saalisparametrin "{0}" tulee olla nimeämätön.
 unused.local.var=Käyttämätön paikallinen muuttuja ''{0}''.
-unused.named.local.var=K�ytt�m�t�n nimetty paikallinen muuttuja ''{0}''.
+unused.named.local.var=K ytt m t n nimetty paikallinen muuttuja ''{0}''.
```
Comment (rnveach) [inline src/main/resources/com/puppycrawl/tools/checkstyle/checks/coding/messages_fi.properties:69]: Why was this changed?

File: src/main/resources/com/puppycrawl/tools/checkstyle/checks/coding/messages_fr.properties (hunk 25 above)
Comment (rnveach) [inline src/main/resources/com/puppycrawl/tools/checkstyle/checks/coding/messages_fr.properties:38]: Same.

File: src/main/resources/com/puppycrawl/tools/checkstyle/checks/coding/messages_pt.properties [hunk 29]
```diff
@@ -64,8 +64,9 @@ unnecessary.paren.literal=Parênteses desnecessários em torno do literal ''{0}'
 unnecessary.paren.return=Parênteses desnecessários em torno do valor de retorno.
 unnecessary.paren.string=Parênteses desnecessários em torno da cadeia {0}.
 unnecessary.semicolon=Ponto-e-vírgula desnecessário.
+unused.catch.parameter=O parâmetro catch não utilizado ''{0}'' não deve ter nome.
 unused.local.var=Variável local não utilizada '' {0} ''.
-unused.named.local.var=Vari�vel local nomeada n�o utilizada '' {0} ''.
+unused.named.local.var=Vari vel local nomeada n o utilizada '' {0} ''.
```
Comment (rnveach) [inline src/main/resources/com/puppycrawl/tools/checkstyle/checks/coding/messages_pt.properties:69]: Same.

File: src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/unusedcatchparametershouldbeunnamed/InputUnusedCatchParameterShouldBeUnnamed.java [hunk 30]
```diff
@@ -0,0 +1,118 @@
...
+        }
+        catch (Exception A) {  // violation
+           A a;
+        }
+
+        try {
+            int x = 1/ 0;
+        }
+        catch (Exception A) {  // violation
+           Object a = new A();
```
Comment (rnveach) [inline src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/unusedcatchparametershouldbeunnamed/InputUnusedCatchParameterShouldBeUnnamed.java:73]: Is there an example of an anonymous class where it has a method with its own try/catch of the same name and it is used?

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedCatchParameterShouldBeUnnamedCheck.java [hunk 31]
```diff
@@ -0,0 +1,270 @@
...
+                    .filter(parameter -> parameter.getName().equals(ast.getText()))
+                    .findFirst()
+                    .ifPresent(CatchParameterDetails::registerAsUsed);
+        }
+    }
+
+    @Override
+    public void leaveToken(DetailAST ast) {
+        final CatchParameterDetails catchParameter = catchParameters.peek();
+        if (catchParameter != null && ast.equals(catchParameter.getEnclosingCatchClause())) {
```
Comment (rnveach) [inline src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedCatchParameterShouldBeUnnamedCheck.java:131]: Couldn't we drop the `!= null` if we blocked this all off by an AST type equals catch check? Would also do less checks (peek and equals) when it isn't the catch token.

**Review by rnveach — CHANGES_REQUESTED** [review]

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedCatchParameterShouldBeUnnamedCheck.java [hunk 32]
```diff
@@ -0,0 +1,270 @@
...
+     * @param identifierAst token representing {@link TokenTypes#IDENT}
+     * @return true if the given {@link TokenTypes#IDENT} could be a catch parameter identifier
+     */
+    private static boolean isCatchParameterIdentifierCandidate(DetailAST identifierAst) {
+        // we should ignore the ident if it is in the exception declaration
+        final boolean isCatchParameterDeclaration =
+                identifierAst.getParent().getParent().getType() == TokenTypes.LITERAL_CATCH;
+
+        final boolean hasValidParentToken =
+                !TokenUtil.isOfType(identifierAst.getParent(), INVALID_CATCH_PARAM_IDENT_PARENTS);
```
[the remark this answers is not in the document]
Comment (nrmancuso) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedCatchParameterShouldBeUnnamedCheck.java:154]: This should not compile.

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedCatchParameterShouldBeUnnamedCheck.java [hunk 33]
```diff
@@ -0,0 +1,270 @@
...
+    }
+
+    @Override
+    public void visitToken(DetailAST ast) {
+        if (ast.getType() == TokenTypes.LITERAL_CATCH) {
+            final CatchParameterDetails catchParameter = new CatchParameterDetails(ast);
+            catchParameters.push(catchParameter);
+        }
+        else if (isCatchParameterIdentifierCandidate(ast) && !isLeftHandOfAssignment(ast)) {
+            // we do not count reassignment as usage
```
[the remark this answers is not in the document]
Comment (nrmancuso) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedCatchParameterShouldBeUnnamedCheck.java:120]: The reassignment is never used in this case. What is the point in keeping it around?

[the remark this answers is not in the document]
Comment (rnveach) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedCatchParameterShouldBeUnnamedCheck.java:120]: > The reassignment is never used in this case

How do we know unless we are tracking it also? When it talks about re-assignment, I thought we meant weird code like:
````
} catch (Exception e) {
  Except t = e;
  t.printStackTrace();
}
````

Also my example has the type, but I assume it can also be re-assigned a field outside the scope or a field.

[the remark this answers is not in the document]
Comment (mahfouz72) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedCatchParameterShouldBeUnnamedCheck.java:120]:
```
} catch (Exception e) {
  Except t = e;
  t.printStackTrace();
}
```
but this is not an LHS assignment. My code should not violate this example because `e` is actually used (another variable used its value)

```
} catch (Exception e) {
  e = t;  // e is a LHS value and it is not used
  t.printStackTrace();
}
```
ideally, we should remove the reassignment and make 'e' unamed.

[the remark this answers is not in the document]
Comment (mahfouz72) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedCatchParameterShouldBeUnnamedCheck.java:120]: https://github.com/checkstyle/checkstyle/blob/827ccf0a7da00b12d3480027540569203c389555/src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/unusedcatchparametershouldbeunnamed/InputUnusedCatchParameterShouldBeUnnamed.java#L52-L60

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedCatchParameterShouldBeUnnamedCheck.java [hunk 34]
```diff
@@ -0,0 +1,270 @@
...
+        TokenTypes.DOT,
+        TokenTypes.LITERAL_NEW,
+        TokenTypes.METHOD_CALL,
+        TokenTypes.TYPE,
+    };
+
+    /**
+     * Keeps track of the catch parameters in a block.
+     */
+    private final Deque<CatchParameterDetails> catchParameters = new ArrayDeque<>();
```
[the remark this answers is not in the document]
Comment (mahfouz72) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedCatchParameterShouldBeUnnamedCheck.java:93]: Yes but we should be sure that we will never leave any date behind from file to file; [as we always pop the top of the stack ](https://github.com/mahfouz72/checkstyle/blob/827ccf0a7da00b12d3480027540569203c389555/src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedCatchParameterShouldBeUnnamedCheck.java#L137)when we leave the catch token. So, when we finish the file (leave all tokens) by then we should have an empty stack.

Does it make sense to clear the collection even if we are sure that it will always be cleared using other ways (`pop()`s in this example

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedCatchParameterShouldBeUnnamedCheck.java (hunk 32 above)
[the remark this answers is not in the document]
Comment (mahfouz72) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedCatchParameterShouldBeUnnamedCheck.java:154]: Yes. 

```
D:\CS\test
cat src/Test.java
import java.util.Arrays;
import java.util.List;

public class Test {
    void test() {
        List<Integer> numbers = Arrays.asList(1, 2, 3);
        try {
            int x = 1 / 0;
        } catch (Exception e) {
            numbers = numbers.stream()
                .map(e -> 0)
                .toList();
        }
    }
}
D:\CS\test
javac src/Test.java
src\Test.java:11: error: variable e is already defined in method test()
                .map(e -> 0)
                     ^
1 error
```

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedCatchParameterShouldBeUnnamedCheck.java [hunk 35]
```diff
@@ -0,0 +1,270 @@
...
+                    .ifPresent(CatchParameterDetails::registerAsUsed);
+        }
+    }
+
+    @Override
+    public void leaveToken(DetailAST ast) {
+        final CatchParameterDetails catchParameter = catchParameters.peek();
+        if (catchParameter != null && ast.equals(catchParameter.getEnclosingCatchClause())) {
+            if (!"_".equals(catchParameter.getName()) && !catchParameter.isUsed()) {
+                log(catchParameter.getParameterDefinition(),
```
[the remark this answers is not in the document]
Comment (mahfouz72) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedCatchParameterShouldBeUnnamedCheck.java:133]: I don't know what is best practice here (logging on the name or the parameter def token). but I tried to keep consistency with `UnusedLocalVariableCheck`.[ It logs on the type of the variable](https://github.com/checkstyle/checkstyle/blob/15b5b73406f9ec8311625bb26baf8530ef8eca4d/src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java#L427) not its name (ident)

Do you think it will be more precise it we log on the ident token ?

File: src/it/java/org/checkstyle/suppressionxpathfilter/XpathRegressionUnusedCatchParameterShouldBeUnnamedTest.java [hunk 36]
```diff
@@ -0,0 +1,120 @@
...
+
+        final String[] expectedViolation = {
+            "10:16: " + getCheckMessage(UnusedCatchParameterShouldBeUnnamedCheck.class,
+                    UnusedCatchParameterShouldBeUnnamedCheck.MSG_UNUSED_CATCH_PARAMETER,
+                    "e"),
+        };
+
+        final List<String> expectedXpathQueries = Arrays.asList(
+                "/COMPILATION_UNIT/CLASS_DEF[./IDENT"
+                + "[@text='InputXpathUnusedCatchParameterShouldBeUnnamedSimple']]"
```
[the remark this answers is not in the document]
Comment (mahfouz72) [reply src/it/java/org/checkstyle/suppressionxpathfilter/XpathRegressionUnusedCatchParameterShouldBeUnnamedTest.java:59]: please check is it good now?

File: src/main/resources/com/puppycrawl/tools/checkstyle/checks/coding/messages_fi.properties (hunk 28 above)
Comment (mahfouz72) [reply src/main/resources/com/puppycrawl/tools/checkstyle/checks/coding/messages_fi.properties]: idk, restored

File: src/main/resources/com/puppycrawl/tools/checkstyle/checks/coding/messages_fr.properties (hunk 25 above)
Comment (mahfouz72) [reply src/main/resources/com/puppycrawl/tools/checkstyle/checks/coding/messages_fr.properties]: done

File: src/main/resources/com/puppycrawl/tools/checkstyle/checks/coding/messages_pt.properties (hunk 29 above)
Comment (mahfouz72) [reply src/main/resources/com/puppycrawl/tools/checkstyle/checks/coding/messages_pt.properties]: done

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedCatchParameterShouldBeUnnamedCheck.java (hunk 31 above)
Comment (mahfouz72) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedCatchParameterShouldBeUnnamedCheck.java]: Yeah good, done

I changed the condition to be `ast == catch' if we leave a catch token then we are sure that there is a catch parameter in the stack

File: src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/unusedcatchparametershouldbeunnamed/InputUnusedCatchParameterShouldBeUnnamed.java (hunk 30 above)
Comment (mahfouz72) [reply src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/unusedcatchparametershouldbeunnamed/InputUnusedCatchParameterShouldBeUnnamed.java:73]: I am not sure but do you mean something like this?

https://github.com/mahfouz72/checkstyle/blob/b0371828cfebfe14b569d80f54f44af9ad99c8af/src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/unusedcatchparametershouldbeunnamed/InputUnusedCatchParameterShouldBeUnnamedNested.java#L102-L111

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedCatchParameterShouldBeUnnamedCheck.java (hunk 34 above)
[the remark this answers is not in the document]
Comment (rnveach) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedCatchParameterShouldBeUnnamedCheck.java:93]: > Does it make sense to clear the collection even if we are sure that it will always be cleared using other ways (pop()s in this example

But you can't be sure. You are only sure your check processes good granted everything external doesn't fail, however you can't guarantee external things won't fail. If another check has an NPE, and halt on exception is turned off, it will leave that file without calling anymore leave tokens and start the next file with data left on the stack.

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedCatchParameterShouldBeUnnamedCheck.java (hunk 33 above)
[the remark this answers is not in the document]
Comment (rnveach) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedCatchParameterShouldBeUnnamedCheck.java:120]: Sorry, I got the side of the assignment wrong. I see, it is still unused even though it was re-assigned.

File: src/main/resources/com/puppycrawl/tools/checkstyle/checks/coding/messages_fr.properties (hunk 25 above)
Comment (mahfouz72) [reply src/main/resources/com/puppycrawl/tools/checkstyle/checks/coding/messages_fr.properties]: please see there is still something weird.

```
-missing.switch.nullcase=Switch utilisant des types de référence doit avoir un cas nul.
+missing.switch.nullcase=Switch utilisant des types de référence doit avoir un cas nul.
```

what is the difference

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedCatchParameterShouldBeUnnamedCheck.java (hunk 34 above)
[the remark this answers is not in the document]
Comment (mahfouz72) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedCatchParameterShouldBeUnnamedCheck.java:93]: Yea, got it. Done

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedCatchParameterShouldBeUnnamedCheck.java (hunk 35 above)
[the remark this answers is not in the document]
Comment (rnveach) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedCatchParameterShouldBeUnnamedCheck.java:138]: I am not sure this has really come up.

I would expect we send the AST which is being violated as bad. Maybe some special filter will look at this AST and do more processing. Parameter def and it's ident probably have the same line/column, so most of our processes won't care.

> UnusedLocalVariableCheck.[ It logs on the type of the variable](https://github.com/checkstyle/checkstyle/blob/15b5b73406f9ec8311625bb26baf8530ef8eca4d/src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java#L427) not its name (ident)

That is odd and doesn't make any sense. This has a different column number. At least your current makes a bit more sense.

@nrmancuso What do you think?

File: src/it/java/org/checkstyle/suppressionxpathfilter/XpathRegressionUnusedCatchParameterShouldBeUnnamedTest.java (hunk 36 above)
[the remark this answers is not in the document]
Comment (rnveach) [reply src/it/java/org/checkstyle/suppressionxpathfilter/XpathRegressionUnusedCatchParameterShouldBeUnnamedTest.java:59]: See https://github.com/checkstyle/checkstyle/blob/464a2c165101a45d1d976cf65501f859ff8fcab4/src/it/java/org/checkstyle/suppressionxpathfilter/XpathRegressionUnusedLocalVariableTest.java#L53-L56 as what I would consider good.

File: src/main/resources/com/puppycrawl/tools/checkstyle/checks/coding/messages_fr.properties (hunk 25 above)
Comment (rnveach) [reply src/main/resources/com/puppycrawl/tools/checkstyle/checks/coding/messages_fr.properties]: I am not sure but git diff doesn't lie. it may be something with the whitespace you can only see with a hex editor.

For example, Japanese character set has a special whitespace which doesn't match the ASCII whitespace.

File: src/main/resources/com/puppycrawl/tools/checkstyle/checks/coding/messages_pt.properties (hunk 29 above)
Comment (rnveach) [reply src/main/resources/com/puppycrawl/tools/checkstyle/checks/coding/messages_pt.properties]: Not done on GH.

File: src/main/resources/com/puppycrawl/tools/checkstyle/checks/coding/messages_fi.properties (hunk 28 above)
Comment (rnveach) [reply src/main/resources/com/puppycrawl/tools/checkstyle/checks/coding/messages_fi.properties]: Not done on GH.

File: src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/unusedcatchparametershouldbeunnamed/InputUnusedCatchParameterShouldBeUnnamed.java (hunk 30 above)
Comment (rnveach) [reply src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/unusedcatchparametershouldbeunnamed/InputUnusedCatchParameterShouldBeUnnamed.java:73]: Yes, but put that block inside the catch and have both catch be the same variable name.

I am basically looking for a way to confuse your check with flagging something it shouldn't or vice versa.

Example (lazy indentation):
````
            try {
                int y = 1 / 0;
            } catch (Exception ex) { // should be violation

    // nested inside anonymous class
    Runnable runnable = new Runnable() {
        @Override
        public void run() {
            try {
                int x = 1 / 0;
            } catch (Exception ex) { // should be ok
                System.out.println(ex.getMessage());
            }
        }
    };

            }
````

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedCatchParameterShouldBeUnnamedCheck.java (hunk 34 above)
[the remark this answers is not in the document]
Comment (rnveach) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedCatchParameterShouldBeUnnamedCheck.java:93]: See `isStatefulFieldClearedDuringBeginTree` to applease the pitest gods.

File: src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/unusedcatchparametershouldbeunnamed/InputUnusedCatchParameterShouldBeUnnamed.java (hunk 30 above)
Comment (mahfouz72) [reply src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/unusedcatchparametershouldbeunnamed/InputUnusedCatchParameterShouldBeUnnamed.java:73]: done

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedCatchParameterShouldBeUnnamedCheck.java (hunk 34 above)
[the remark this answers is not in the document]
Comment (mahfouz72) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedCatchParameterShouldBeUnnamedCheck.java:93]: done

File: src/main/resources/com/puppycrawl/tools/checkstyle/checks/coding/messages_fr.properties (hunk 25 above)
Comment (mahfouz72) [reply src/main/resources/com/puppycrawl/tools/checkstyle/checks/coding/messages_fr.properties]: @nrmancuso Please help, how did you fix it before? In https://github.com/checkstyle/checkstyle/pull/15358#discussion_r1694261409

copy/paste from old branch is not working it substitutes the non-ascii with space or git diff produces differences even if the text is identical. very weird and frustrating

Comment (rnveach) [reply src/main/resources/com/puppycrawl/tools/checkstyle/checks/coding/messages_fr.properties]: In the FR file, `référence` is the issue.

Your PR has the hex:
`72 C3 A9 66 C3 A9 72 65 6E 63 65`
Master has the hex:
`72 E9 66 E9 72 65 6E 63 65`

According to ChatGPT ( and I agree with it's findings) :
> The sequence 72 C3 A9 66 C3 A9 72 65 6E 63 65 is the UTF-8 encoding, where each 'é' is represented by the two-byte sequence C3 A9.
> The sequence 72 E9 66 E9 72 65 6E 63 65 is the Latin-1 encoding, where each 'é' is represented by the single byte E9.
> In both cases, the byte sequences represent the same string "référence", but they are encoded differently according to the specified character encoding schemes.

Whatever you are using to edit these files is changing the encoding.

Comment (romani) [reply src/main/resources/com/puppycrawl/tools/checkstyle/checks/coding/messages_fr.properties]: I noticed this kind of updates on one of previous PRs, Nick unintentionally damaged Unicode, root reason was not found, we just reversed and moved forward.

**Comment by mahfouz72** [comment]
github, generate report

**Comment by mahfouz72** [comment]
@rnveach @nrmancuso do we agree to suppress this? adding a non-nullity condition will be a surviving mutation

```
  <checkerFrameworkError unstable="false">
    <fileName>src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedCatchParameterShouldBeUnnamedCheck.java</fileName>
    <specifier>dereference.of.nullable</specifier>
    <message>dereference of possibly-null reference catchParameter</message>
    <lineContent>if (!&quot;_&quot;.equals(catchParameter.getName()) &amp;&amp; !catchParameter.isUsed()) {</lineContent>
  </checkerFrameworkError>
```

File: src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/unusedcatchparametershouldbeunnamed/InputUnusedCatchParameterShouldBeUnnamed.java (hunk 30 above)
Comment (mahfouz72) [reply src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/unusedcatchparametershouldbeunnamed/InputUnusedCatchParameterShouldBeUnnamed.java:73]: https://github.com/mahfouz72/checkstyle/blob/be69edc8c69a195ef25c897afc6c6d50b3c79f90/src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/unusedcatchparametershouldbeunnamed/InputUnusedCatchParameterShouldBeUnnamedNested.java#L101-L114

File: src/it/java/org/checkstyle/suppressionxpathfilter/XpathRegressionUnusedCatchParameterShouldBeUnnamedTest.java (hunk 36 above)
[the remark this answers is not in the document]
Comment (mahfouz72) [reply src/it/java/org/checkstyle/suppressionxpathfilter/XpathRegressionUnusedCatchParameterShouldBeUnnamedTest.java:59]: done

File: src/main/resources/com/puppycrawl/tools/checkstyle/checks/coding/messages_pt.properties (hunk 29 above)
Comment (mahfouz72) [reply src/main/resources/com/puppycrawl/tools/checkstyle/checks/coding/messages_pt.properties]: done on GH

File: src/main/resources/com/puppycrawl/tools/checkstyle/checks/coding/messages_fr.properties (hunk 25 above)
Comment (mahfouz72) [reply src/main/resources/com/puppycrawl/tools/checkstyle/checks/coding/messages_fr.properties]: done on GH

File: src/main/resources/com/puppycrawl/tools/checkstyle/checks/coding/messages_fi.properties (hunk 28 above)
Comment (mahfouz72) [reply src/main/resources/com/puppycrawl/tools/checkstyle/checks/coding/messages_fi.properties]: done on GH

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedCatchParameterShouldBeUnnamedCheck.java (hunk 35 above)
[the remark this answers is not in the document]
Comment (nrmancuso) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedCatchParameterShouldBeUnnamedCheck.java:138]: If we are calling the check `...Catchparameter...`, we should place violations on the catch parameter, not just the identifier. Grammar for reference: https://docs.oracle.com/javase/specs/jls/se21/html/jls-14.html#jls-CatchFormalParameter

```
TryStatement:
  try Block Catches
  try Block [Catches] Finally

TryWithResourcesStatement
  Catches:
  CatchClause {CatchClause}

CatchClause:
  catch ( CatchFormalParameter ) Block

CatchFormalParameter:
  {VariableModifier} CatchType VariableDeclaratorId

CatchType:
  UnannClassType {| ClassType}

Finally:
  finally Block
```

[the remark this answers is not in the document]
Comment (nrmancuso) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedCatchParameterShouldBeUnnamedCheck.java:138]: @mahfouz72 please add some modifiers in front of some of the types (final) to make sure that we are indeed placing violations on the right thing.

[the remark this answers is not in the document]
Comment (mahfouz72) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedCatchParameterShouldBeUnnamedCheck.java:138]: Done.  

```
        try {
            int x = 1/ 0;
        }
        catch (final Exception e) {  // violation

        }
        -LITERAL_CATCH -> catch [17:8]
|       |       |       |--LPAREN -> ( [17:14]
|       |       |       |--PARAMETER_DEF -> PARAMETER_DEF [17:15]  <--- we log this
|       |       |       |   |--MODIFIERS -> MODIFIERS [17:15]
|       |       |       |   |   `--FINAL -> final [17:15]
|       |       |       |   |--TYPE -> TYPE [17:21]
|       |       |       |   |   `--IDENT -> Exception [17:21]
|       |       |       |   `--IDENT -> e [17:31]
```

**Comment by nrmancuso** [comment]
> @rnveach @nrmancuso do we agree to suppress this? adding a non-nullity condition will be a surviving mutation
> 
> ```
>   <checkerFrameworkError unstable="false">
>     <fileName>src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedCatchParameterShouldBeUnnamedCheck.java</fileName>
>     <specifier>dereference.of.nullable</specifier>
>     <message>dereference of possibly-null reference catchParameter</message>
>     <lineContent>if (!&quot;_&quot;.equals(catchParameter.getName()) &amp;&amp; !catchParameter.isUsed()) {</lineContent>
>   </checkerFrameworkError>
> ```

We can probably make all static analysis happy and also be a bit more expressive:
```java
            final Optional<CatchParameterDetails> unusedCatchParameter = Optional.ofNullable(catchParameters.peek())
                    .filter(p -> !"_".equals(p.getName()))
                    .filter(p -> !p.isUsed());

            unusedCatchParameter.ifPresent(catchParameterDetails ->
                    log(catchParameterDetails.getParameterDefinition(),
                            MSG_UNUSED_CATCH_PARAMETER,
                            catchParameterDetails.getName()));
```

File: src/it/java/org/checkstyle/suppressionxpathfilter/XpathRegressionUnusedCatchParameterShouldBeUnnamedTest.java (hunk 36 above)
[the remark this answers is not in the document]
Comment (rnveach) [reply src/it/java/org/checkstyle/suppressionxpathfilter/XpathRegressionUnusedCatchParameterShouldBeUnnamedTest.java:59]: Still not done.

Use:
````
                "/COMPILATION_UNIT/CLASS_DEF[./IDENT"
                        + "[@text='InputXpathUnusedCatchParameterShouldBeUnnamedSimple']]"
                        + "/OBJBLOCK/METHOD_DEF[./IDENT[@text='test']]/SLIST/LITERAL_TRY/"
                        + "LITERAL_CATCH/PARAMETER_DEF[./IDENT[@text='e']]",
                "/COMPILATION_UNIT/CLASS_DEF["
                        + "./IDENT[@text='InputXpathUnusedCatchParameterShouldBeUnnamedSimple']]"
                        + "/OBJBLOCK/METHOD_DEF[./IDENT[@text='test']]/SLIST/"
                        + "LITERAL_TRY/LITERAL_CATCH/PARAMETER_DEF[./IDENT[@text='e']]/MODIFIERS",
                "/COMPILATION_UNIT/CLASS_DEF["
                        + "./IDENT[@text='InputXpathUnusedCatchParameterShouldBeUnnamedSimple']]"
                        + "/OBJBLOCK/METHOD_DEF[./IDENT[@text='test']]/SLIST/LITERAL_TRY/"
                        + "LITERAL_CATCH/PARAMETER_DEF[./IDENT[@text='e']]"
                        + "/TYPE[./IDENT[@text='Exception']]",
                "/COMPILATION_UNIT/CLASS_DEF"
                        + "[./IDENT[@text='InputXpathUnusedCatchParameterShouldBeUnnamedSimple']]"
                        + "/OBJBLOCK/METHOD_DEF[./IDENT[@text='test']]/SLIST/LITERAL_TRY"
                        + "/LITERAL_CATCH/PARAMETER_DEF[./IDENT[@text='e']]"
                        + "/TYPE/IDENT[@text='Exception']"
````

[the remark this answers is not in the document]
Comment (mahfouz72) [reply src/it/java/org/checkstyle/suppressionxpathfilter/XpathRegressionUnusedCatchParameterShouldBeUnnamedTest.java]: done

File: src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/unusedcatchparametershouldbeunnamed/InputUnusedCatchParameterShouldBeUnnamedNested.java [hunk 37]
```diff
@@ -0,0 +1,117 @@
...
+                System.out.println("infinity");
+            }
+            System.out.println("infinity");
+        }
+    }
+
+    void testNestedInsideAnonClass() {
+        try {
+            int x = 1 / 0;
+        } catch (Exception e) { // violation
```
Comment (rnveach) [inline src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/unusedcatchparametershouldbeunnamed/InputUnusedCatchParameterShouldBeUnnamedNested.java:104]: One more variation of this:
`````
    void testNestedInsideAnonClass() {
        try {
            int x = 1 / 0;
        } catch (final Exception e) { // should not be violation
            Runnable runnable = new Runnable() {
                @Override
                public void run() {
                    try {
                        int x = 1 / 0;
                    } catch (Exception ex) {
                        System.out.println(e.getMessage());
                    }
                }
            };
        }
    }
````

**Review by rnveach — CHANGES_REQUESTED** [review]

File: src/it/java/org/checkstyle/suppressionxpathfilter/XpathRegressionUnusedCatchParameterShouldBeUnnamedTest.java (hunk 36 above)
[the remark this answers is not in the document]
Comment (rnveach) [reply src/it/java/org/checkstyle/suppressionxpathfilter/XpathRegressionUnusedCatchParameterShouldBeUnnamedTest.java]: Thank you.

File: src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/unusedcatchparametershouldbeunnamed/InputUnusedCatchParameterShouldBeUnnamedNested.java (hunk 37 above)
Comment (mahfouz72) [reply src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/unusedcatchparametershouldbeunnamed/InputUnusedCatchParameterShouldBeUnnamedNested.java]: done with the four variations :).
moved to separate input file

**Comment by mahfouz72** [comment]
@rnveach ping

File: src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedCatchParameterShouldBeUnnamedCheckTest.java [hunk 38]
```diff
@@ -0,0 +1,147 @@
...
+
+        final DetailAstImpl child = new DetailAstImpl();
+        child.setType(TokenTypes.PARAMETER_DEF);
+
+        final DetailAstImpl ident = new DetailAstImpl();
+        ident.setType(TokenTypes.IDENT);
+        ident.setText("e");
+        child.addChild(ident);
+
+        ast.addChild(child);
```
Comment (rnveach) [inline src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedCatchParameterShouldBeUnnamedCheckTest.java:136]: Why can't we use this method of obtaining AST?
https://github.com/checkstyle/checkstyle/blob/1f85c8e9860b24235536b41ca9605c69945d3af4/src/test/java/com/puppycrawl/tools/checkstyle/checks/metrics/ClassFanOutComplexityCheckTest.java#L332-L336

File: src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/unusedcatchparametershouldbeunnamed/InputUnusedCatchParameterShouldBeUnnamedNested.java (hunk 37 above)
Comment (rnveach) [reply src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/unusedcatchparametershouldbeunnamed/InputUnusedCatchParameterShouldBeUnnamedNested.java]: Point to the file and lines please.

**Review by rnveach — CHANGES_REQUESTED** [review]

File: src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/unusedcatchparametershouldbeunnamed/InputUnusedCatchParameterShouldBeUnnamedNested.java (hunk 37 above)
Comment (rnveach) [reply src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/unusedcatchparametershouldbeunnamed/InputUnusedCatchParameterShouldBeUnnamedNested.java]: Point to file and lines please

Comment (mahfouz72) [reply src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/unusedcatchparametershouldbeunnamed/InputUnusedCatchParameterShouldBeUnnamedNested.java]: https://github.com/checkstyle/checkstyle/blob/4867842d1e57e1605138eea29e109e99a601c00c/src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/unusedcatchparametershouldbeunnamed/InputUnusedCatchParameterShouldBeUnnamedInsideAnonClass.java

This file has all four variations from your example. Please let me know if I misunderstood you. You meant variation when the inner exception is used/outer is not used and vise versa right?

File: src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedCatchParameterShouldBeUnnamedCheckTest.java (hunk 38 above)
Comment (mahfouz72) [reply src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedCatchParameterShouldBeUnnamedCheckTest.java]: done

File: src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/unusedcatchparametershouldbeunnamed/InputUnusedCatchParameterShouldBeUnnamedNested.java (hunk 37 above)
Comment (rnveach) [reply src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/unusedcatchparametershouldbeunnamed/InputUnusedCatchParameterShouldBeUnnamedNested.java]: Relook at my example here. Top catch and inner catch have different catch parameter names, and inner get message uses top catch's name. The examples I see in the input file you showed are all the same variable name.

Comment (mahfouz72) [reply src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/unusedcatchparametershouldbeunnamed/InputUnusedCatchParameterShouldBeUnnamedNested.java]: Yeah my bad I didn't notice the different names. Done 
https://github.com/checkstyle/checkstyle/blob/66e0f2a3c2cf19a4849ac2f4c714e2590519f450/src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/unusedcatchparametershouldbeunnamed/InputUnusedCatchParameterShouldBeUnnamedInsideAnonClass.java#L83-L113

Is there any extra confusions ? :)

Comment (rnveach) [reply src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/unusedcatchparametershouldbeunnamed/InputUnusedCatchParameterShouldBeUnnamedNested.java]: Nope. I think I am good.

**Review by rnveach — APPROVED** [review]

**Comment by rnveach** [comment]
Rebasing to ensure no issues on merge.

**Comment by rnveach** [comment]
https://github.com/checkstyle/contribution/pull/883#discussion_r1704832575

**Comment by mahfouz72** [comment]
@rnveach done
