### PR TITLE
Issue #13167: Fix NPE in UnusedLocalVariable check

### LINKED ISSUE #13167: Null pointer Exception in UnusedLocalVariableCheck
I have read check documentation: https://checkstyle.org/config_coding.html#UnusedLocalVariable
I have downloaded the latest checkstyle from: https://checkstyle.org/cmdline.html#Download_and_Run
I have executed the cli and showed it below, as cli describes the problem better than 1,000 words

```
kevin@inspiron-15-5510:~/Desktop/check_style$ cat Test.java
import javax.swing.*;
import java.awt.*;
import java.util.function.Supplier;

public class Test {
   private final NotNullLazyValue<JComponent> myComponent = NotNullLazyValue.lazy(() -> {
      JPanel results = new JPanel(new GridBagLayout()) {};
       return results;
   });
}
class NotNullLazyValue<T> {
    public NotNullLazyValue() {
    }
    public static <T> NotNullLazyValue<T> lazy(Supplier<T> supplier) {
        return new NotNullLazyValue<>();
    }
}

kevin@inspiron-15-5510:~/Desktop/check_style$ javac Test.java

kevin@inspiron-15-5510:~/Desktop/check_style$ cat config.xml 
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC "-//Checkstyle//DTD Checkstyle Configuration 1.3//EN" "https://checkstyle.org/dtds/configuration_1_3.dtd">

<module name="Checker">
    <property name="charset" value="UTF-8" />
    <property name="severity" value="warning" />
    <property name="haltOnException" value="false" />

    <module name="TreeWalker">

        <module name="UnusedLocalVariable">
        </module>

    </module>
</module>

kevin@inspiron-15-5510:~/Desktop/check_style$ java -jar /home/kevin/Downloads/checkstyle-10.12.0-all.jar -c config.xml Test.java
Starting audit...
[ERROR] /home/kevin/Desktop/check_style/Test.java:1: Got an exception - java.lang.NullPointerException: Cannot invoke "com.puppycrawl.tools.checkstyle.api.DetailAST.getType()" because "parentAst" is null
        at com.puppycrawl.tools.checkstyle.checks.coding.UnusedLocalVariableCheck.getBlockContainingLocalAnonInnerClass(UnusedLocalVariableCheck.java:480)
        at com.puppycrawl.tools.checkstyle.checks.coding.UnusedLocalVariableCheck.visitLocalAnonInnerClass(UnusedLocalVariableCheck.java:404)
        at com.puppycrawl.tools.checkstyle.checks.coding.UnusedLocalVariableCheck.visitToken(UnusedLocalVariableCheck.java:312)
        at com.puppycrawl.tools.checkstyle.TreeWalker.notifyVisit(TreeWalker.java:335)
        at com.puppycrawl.tools.checkstyle.TreeWalker.processIter(TreeWalker.java:406)
        at com.puppycrawl.tools.checkstyle.TreeWalker.walk(TreeWalker.java:273)
        at com.puppycrawl.tools.checkstyle.TreeWalker.processFiltered(TreeWalker.java:154)
        at com.puppycrawl.tools.checkstyle.api.AbstractFileSetCheck.process(AbstractFileSetCheck.java:98)
        at com.puppycrawl.tools.checkstyle.Checker.processFile(Checker.java:334)
        at com.puppycrawl.tools.checkstyle.Checker.processFiles(Checker.java:293)
        at com.puppycrawl.tools.checkstyle.Checker.process(Checker.java:223)
        at com.puppycrawl.tools.checkstyle.Main.runCheckstyle(Main.java:415)
        at com.puppycrawl.tools.checkstyle.Main.runCli(Main.java:338)
        at com.puppycrawl.tools.checkstyle.Main.execute(Main.java:195)
        at com.puppycrawl.tools.checkstyle.Main.main(Main.java:130)
 [Checker]
Audit done.
Checkstyle ends with 1 errors.
kevin@inspiron-15-5510:~/Desktop/check_style$ 
```
---

# Describe what you expect in detail.
Should Not throw Null pointer Exception

---

### PR DESCRIPTION
**Pull request by Vyom-Yadav**
Resolves #13167

### CODE REVIEW

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java [hunk 1]
```diff
@@ -462,15 +462,34 @@ private static boolean isNonLocalTypeDeclaration(DetailAST typeDeclAst) {
...
+     * @param ast ast node
+     * @return {@code true} if ast is nested under tokens of type
+     *         {@link UnusedLocalVariableCheck#CONTAINERS_FOR_ANON_INNERS}
+     *         or {@link TokenTypes#LAMBDA}
+     */
+    public static boolean isTokenNestedUnderContainerForAnonInners(DetailAST ast) {
+        boolean result = false;
+        DetailAST parentAst = ast.getParent();
+        while (parentAst != null) {
+            if (TokenUtil.isOfType(parentAst, CONTAINERS_FOR_ANON_INNERS)
```
Comment (nrmancuso) [inline src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java:487]: Please rename this collection to something like `CLASS_BODY_DECLARATION_TOKENS` in a separate commit first, `container` is nonsense in this context. Then update the method naming, etc. appropriately.

**Review by nrmancuso — CHANGES_REQUESTED** [review]
Item:

File: src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/unusedlocalvariable/InputUnusedLocalVariableLambdaExpression.java [hunk 2]
```diff
@@ -0,0 +1,92 @@
...
+public class InputUnusedLocalVariableLambdaExpression {
+    private final LambdaTest<String> myComponent = LambdaTest.lazy(() -> {
+        String foo = ""; // ok
+        String hoo = ""; // violation
+        new Runnable() {
+            String hoo = "";
+
+            @Override
+            public void run() {
+                String j = hoo; // violation
```
Comment (romani) [inline src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/unusedlocalvariable/InputUnusedLocalVariableLambdaExpression.java:20]: Please define violation messages

**Review by romani — CHANGES_REQUESTED** [review]
Items

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java (hunk 1 above)
Comment (romani) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java:487]: @rdiachenko , please step in to help review.

File: src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/unusedlocalvariable/InputUnusedLocalVariableLambdaExpression.java (hunk 2 above)
Comment (Vyom-Yadav) [reply src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/unusedlocalvariable/InputUnusedLocalVariableLambdaExpression.java:20]: We do not define violation messages when the check has only one kind of violation message.

Comment (romani) [reply src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/unusedlocalvariable/InputUnusedLocalVariableLambdaExpression.java:20]: Hmm, I thought We started in all places to make it clear that violation message meaningful on a line, and it doesn't not create extra effort on new message addition.

@rnveach , do you remember what is our rule for this now?

Comment (nrmancuso) [reply src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/unusedlocalvariable/InputUnusedLocalVariableLambdaExpression.java:20]: We should have violation message for all violations, regardless of number of messages in check. This is a good sanity check, and will also alleviate extra work in the future if we add a new message.

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java [hunk 3]
```diff
@@ -462,15 +462,34 @@ private static boolean isNonLocalTypeDeclaration(DetailAST typeDeclAst) {
...
             }
             currentAst = currentAst.getParent();
-            result = currentAst;
+        }
+        return result;
+    }
+
+    /**
+     * Whether the ast is nested under tokens of type
+     * {@link UnusedLocalVariableCheck#CONTAINERS_FOR_ANON_INNERS} or {@link TokenTypes#LAMBDA}.
```
Comment (nrmancuso) [inline src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java:476]: Please remove mentions of specific tokens, such a list is bound to get outdated/ignored, and is an implementation detail that the caller should not have to worry about.

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java [hunk 4]
```diff
@@ -462,15 +462,34 @@ private static boolean isNonLocalTypeDeclaration(DetailAST typeDeclAst) {
...
+     *
+     * @param ast ast node
+     * @return {@code true} if ast is nested under tokens of type
+     *         {@link UnusedLocalVariableCheck#CONTAINERS_FOR_ANON_INNERS}
+     *         or {@link TokenTypes#LAMBDA}
```
Comment (nrmancuso) [inline src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java:481]: Same as above.

**Review by nrmancuso — CHANGES_REQUESTED** [review]
Another item as you push changes for collection:

File: src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/unusedlocalvariable/InputUnusedLocalVariableLambdaExpression.java (hunk 2 above)
Comment (rnveach) [reply src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/unusedlocalvariable/InputUnusedLocalVariableLambdaExpression.java:20]: @romani @nrmancuso If it was written down somewhere (either in code or the top of issues) or controlled by CI, then it doesn't exist. If this should be a rule, then a test should enforce it.

https://github.com/checkstyle/checkstyle/issues/11214
> Single Check might have multiple violations messages, we need to see exact violation message if Check has multiple messages, to be sure that violation of correct type is placed at right line.

I consider this the main issue for this and it is documented only for checks with multiple messages. I scanned some of the checks listed and did not see any single message checks.

https://github.com/checkstyle/checkstyle/blob/2335abaea101774a23d0bdaf55f19e4f0cad0d37/src/test/java/com/puppycrawl/tools/checkstyle/bdd/InlineConfigParser.java#L118-L119
It is even documented in code that it is only for checks with multiple messages.

====================

I was not involved in the discussions or the decision to do this, so I don't know anything more than, as I said, what is written.

Comment (romani) [reply src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/unusedlocalvariable/InputUnusedLocalVariableLambdaExpression.java:20]: Thanks a lot.
If code checks for not single message, let's keep it and Finish phase of migration to update multiple messages Checks first.
And maybe be later we will do same update for single-message, we will vote on this later on.

I recall this review item for now.

Comment (romani) [reply src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/unusedlocalvariable/InputUnusedLocalVariableLambdaExpression.java:20]: Thanks a lot.
If code checks for not single message, let's keep it and Finish phase of migration to update multiple messages Checks first.
And maybe be later we will do same update for single-message, we will vote on this later on.

I recall this review item for now.

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java (hunk 1 above)
Comment (Vyom-Yadav) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java:422]: Created https://github.com/checkstyle/checkstyle/pull/14090 to change the variable name.

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java [hunk 5]
```diff
@@ -397,16 +397,18 @@ private static boolean isNonLocalTypeDeclaration(DetailAST typeDeclAst) {
...
-        while (!TokenUtil.isOfType(currentAst, CONTAINERS_FOR_ANON_INNERS)) {
-            if (currentAst.getType() == TokenTypes.LAMBDA
-                    && currentAst.getParent()
-                    .getParent().getParent().getType() == TokenTypes.OBJBLOCK) {
-                result = currentAst;
-                break;
+        DetailAST topMostLambdaAst = null;
+        while (currentAst != null && !TokenUtil.isOfType(currentAst, CONTAINERS_FOR_ANON_INNERS)) {
+            if (currentAst.getType() == TokenTypes.LAMBDA) {
+                topMostLambdaAst = currentAst;
```
Comment (Vyom-Yadav) [inline src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java:403]: This is a time-complexity mutation. The reason I have added this to the suppressions list is because removing this condition will make the entire `COMPILATION_UNIT` to be processed again. And having many nested lambdas can make the entire `COMPILATION_UNIT` be processed multiple times.

If the penalty was small, I would have inclined towards pitest, but processing the entire `COMPILATION_UNIT` multiple times isn't a wise option IMO.

**Comment by rnveach** [comment]
Regression for this PR: https://rveach.no-ip.org/checkstyle/regression/345/

1 NPE is removed, no other changes.

**Comment by rnveach** [comment]
As discussed, analysis is right at https://github.com/checkstyle/checkstyle/pull/13543#discussion_r1412796525 . This would be a very complex check, which I am unfamilar with, to fix pitest.

If we are good, I can write a reasoning for the suppression and create a new issue to resolve pitest suppressions. Maybe it can be done as part of the GSoC project.

**Comment by rnveach** [comment]
It seems to me this check has a check inside itself. We have [the first set of visits which is collecting information](https://github.com/checkstyle/checkstyle/blob/55f5c966bfa61b387110db6c4780f259a21676c8/src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java#L221-L255), then [we have a custom tree walker with its own visits using the information collected from the first](https://github.com/checkstyle/checkstyle/blob/55f5c966bfa61b387110db6c4780f259a21676c8/src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java#L614-L627). It is not re-walking the entire tree in both times, but this is what makes this check complex by itself.

**Comment by Vyom-Yadav** [comment]
Yeah, I remember some of these mutations to be like that. One mutation was particularly like processing the whole `COMPILATION_UNIT` again, so the statement that pitest suggests is actually to prevent that from happening. It's a shame I never got the time to complete this 😞.

 
> It seems to me this check has a check inside itself. We have [the first set of visits which is collecting information](https://github.com/checkstyle/checkstyle/blob/55f5c966bfa61b387110db6c4780f259a21676c8/src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java#L221-L255), then [we have a custom tree walker with its own visits using the information collected from the first](https://github.com/checkstyle/checkstyle/blob/55f5c966bfa61b387110db6c4780f259a21676c8/src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java#L614-L627). It is not re-walking the entire tree in both times, but this is what makes this check complex by itself.

Yeah, it does that. The reason for two traversals is that a class may be defined further down the AST but may be used before, so scoping, etc., becomes difficult in that scenario, particularly with anon inner classes.

**Comment by rdiachenko** [comment]
@Vyom-Yadav 

> And having many nested lambdas can make the entire `COMPILATION_UNIT` be processed multiple times.

Do you have any real examples with many nested lambdas? I'm interested in whether this is a genuine concern or just something we think is problematic when, in practice, it isn't.

> If the penalty was small, I would have inclined towards pitest, but processing the entire `COMPILATION_UNIT` multiple times isn't a wise option IMO.

What's the penalty? Do you have some numbers at hand?

**Comment by Vyom-Yadav** [comment]
> Do you have any real examples with many nested lambdas? I'm interested in whether this is a genuine concern or just something we think is problematic when, in practice, it isn't.

I don't know if there is some pattern using nested lambdas. It is not a rare case, that I'm sure. 

> What's the penalty? Do you have some numbers at hand?

Penalty is directly proportional to the number of nodes in the ast. It will traverse the entire ast again (maybe multiple times too).

**Comment by rdiachenko** [comment]
I didn't find a quick and clear way to test Checkstyle performance for the fix with/without optimisation, so I ended up running both versions against the following list of projects via regression diff report:

```
checkstyle|git|https://github.com/checkstyle/checkstyle.git|master|...|
sevntu-checkstyle|git|https://github.com/sevntu-checkstyle/sevntu.checkstyle|master||
checkstyle-sonar|git|https://github.com/checkstyle/sonar-checkstyle|master||
guava|git|https://github.com/google/guava|v28.2||

spotbugs|git|https://github.com/spotbugs/spotbugs|3.1.2||
pmd|git|https://github.com/pmd/pmd|pmd_releases/6.21.0|**/pmd/pmd-java/src/test/**/*,**/pmd/cpd/files/*
spoon|git|https://github.com/INRIA/spoon.git|spoon-core-10.1.0|**/src/test/resources/**/*
lombok-ast|git|https://github.com/rzwitserloot/lombok.ast|v0.2|**/lombok-ast/test/**/*

spring-framework|git|https://github.com/spring-projects/spring-framework|v4.1.6.RELEASE||
hibernate-orm|git|https://github.com/hibernate/hibernate-orm|4.2.19.Final|**/hibernate-orm/documentation/**/*
elasticsearch|git|https://github.com/elastic/elasticsearch|v1.5.2||
java-design-patterns|git|https://github.com/iluwatar/java-design-patterns|dd855a376bc025aa61f6816584f79eb9854fe5d7||
MaterialDesignLibrary|git|https://github.com/navasmdc/MaterialDesignLibrary|1.3||
Hbase|git|https://github.com/apache/hbase|1.1.0.1||
Orekit|git|https://github.com/CS-SI/Orekit|8.0.1||

# Projects which contain a lot of labmda expressions
infinispan|git|https://github.com/infinispan/infinispan|7.2.5.Final||
protonpack|git|https://github.com/poetix/protonpack|protonpack-1.7||
jOOL|git|https://github.com/jOOQ/jOOL|version-0.9.7||
RxJava|git|https://github.com/ReactiveX/RxJava|v1.0.9||
Vavr|git|https://github.com/vavr-io/vavr|v0.9.0||
```

For this check's config:

```
...
    <module name="TreeWalker">
         <module name="UnusedLocalVariable">
         </module>
    </module>
...
```

I thought if we had a performance problem, the unoptimised fix would give x-times higher processing time. Here are the actual numbers (I ran the regression diff report 3 times for each build and choose the median):

```
# optimised fix
time groovy diff.groovy -r /var/tmp/checkstyle \
-b master -p fixNullPointerExInUnusedLocalVar -c my_check.xml -l projects-to-test-on.properties

1434.43s user 71.09s system 225% cpu 11:08.89 total

# not optimised fix
time groovy diff.groovy -r /var/tmp/checkstyle \
-b master -p fixNullPointerExInUnusedLocalVar-wo-optim -c my_check.xml -l projects-to-test-on.properties

1417.58s user 70.16s system 224% cpu 11:03.38 total
```

There is no difference. I suggest we remove optimisation and use a [simplified fix](https://github.com/rdiachenko/checkstyle/commit/becac625e959642a658fa0b49ce943ea6fd76365) that avoids two `if (currentAst.getType() == TokenTypes.LAMBDA)` mutations.

**Comment by romani** [comment]
I would love to have no pitest suppression,  rather than nano optimization. In long run no pitest will be more beneficial.

**Comment by romani** [comment]
@nrmancuso , @rnveach , please share your opinion.

**Comment by rnveach** [comment]
I am ok for this PR as it is now or closing it.

I don't agree with applying the pitest mutations to the code since that would degrade this check more than it is. We should already look into the issue that it is reporting the same token 2x already.

**Comment by nrmancuso** [comment]
> @nrmancuso , @rnveach , please share your opinion.

My opinion is that we have already spent too much effort on this pitest suppression, let’s either merge or close this. I think it is personally ridiculous to traverse the entire AST up to the root node when we know that we can (and should) stop when we reach the enclosing anonymous class.

We are humans that can think and reason, not robots that only deal in pitest logic.

**Comment by romani** [comment]
All suppression in this PR smells badly.
https://github.com/checkstyle/checkstyle/issues/14894
we will unblock users from NPE, and will deal with better code later on.

**Review by romani — APPROVED** [review]
Ok to merge.
We will improve in separate PR
