### PR TITLE
Issue #9357: FinalClass now exempts private-only constructor classes that also have nested subclasses

### LINKED ISSUE #9357: FinalClass should exempt private-only constructor classes that also have nested subclasses
```bash
$ cat Test.java
```

```java
public class Test {

    public static final Test ONE = new Test() {
        @Override
        public int value() {
            return 1;
        }
    };

    private Test() {
    }

    public int value() {
        return 0;
    }
}
```

```bash
$ cat config.xml
```

```xml
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
        "-//Checkstyle//DTD Checkstyle Configuration 1.3//EN"
        "https://checkstyle.org/dtds/configuration_1_3.dtd">
<module name="Checker">
    <module name="TreeWalker">
        <module name="FinalClass"/>
    </module>
</module>
```

```bash
$ RUN_LOCALE="-Duser.language=en -Duser.country=US"
$ java $RUN_LOCALE -jar checkstyle-8.41-all.jar -c config.xml Test.java
Starting audit...
[ERROR] /Users/archie/bugs/checkstyle-A/Test.java:1:1: Class Test should be declared as final. [FinalClass]
Audit done.
Checkstyle ends with 1 errors.
```

The `FinalClass` module is doing it's job correctly in that it's detecting a non-final class with only private constructor(s), but it's not smart enough to realize that in some situations - e.g., this particular situation where you are defining nested classes within the outer class - it's not possible to make the class `final` because otherwise those nested classes would be impossible to write, because the compile would fail because you can't extend a final class.

Java allows nested classes to extend a class using a private superclass constructor. So the upshot is that `FinalClass` should make an exception when the class being checked contains any nested subclasses.

### PR DESCRIPTION
**Pull request by Vyom-Yadav**
Resolves #9357: FinalClass now exempts private-only constructor classes that also have nested subclasses
Note:- This will still give a violation if used inside the default package. Its fix is simple but writing an input class without package name is not permitted by checkstlye even if you write in the non-compilable resources folder. Code coverage will not be met without that.
Diff Regression projects: https://gist.githubusercontent.com/Vyom-Yadav/91807e6244cff60698d9e33e32ba2d51/raw/85355576c05c80e8b08752a62ba3a4076909d266/projects-to-test-on.properties
Diff Regression config: https://gist.githubusercontent.com/Vyom-Yadav/98dceb63a79f4833e85fff9b2e1464a6/raw/be2b54fe328d0024818fe8aa52def42eca798c34/my_checks.xml

### CODE REVIEW

**Comment by Vyom-Yadav** [comment]
@strkkk @rnveach There is an error in my local, I can't find why some help would be appreciated [log](https://gist.githubusercontent.com/Vyom-Yadav/411a2e93c49f9d7ae8411b974031e542/raw/de572fd8a2c02d952b33c6b100fe082dfac4d105/log2.txt)

**Comment by strkkk** [comment]
@Vyom-Yadav please fix ci, you have NPE somewhere in your code

**Comment by Vyom-Yadav** [comment]
I will fix coverage issues.

**Comment by Vyom-Yadav** [comment]
Github, generate report

**Comment by Vyom-Yadav** [comment]
I checked the report, it looks fine to me, all the violations removed were valid. @strkkk @rnveach Kindly review.

File: src/test/resources/com/puppycrawl/tools/checkstyle/checks/design/finalclass/InputFinalClass.java [hunk 1]
```diff
@@ -127,3 +129,52 @@ private SomeClass() {}
         private SomeClass() {}
     }
 }
+
+class test8 {
```
Comment (strkkk) [inline src/test/resources/com/puppycrawl/tools/checkstyle/checks/design/finalclass/InputFinalClass.java:133]: please use good class names (starts with capital letter)

Comment (strkkk) [inline src/test/resources/com/puppycrawl/tools/checkstyle/checks/design/finalclass/InputFinalClass.java:133]: please use good class names (starts with capital letter)

File: src/test/resources/com/puppycrawl/tools/checkstyle/checks/design/finalclass/InputFinalClass.java [hunk 2]
```diff
@@ -127,3 +129,52 @@ private SomeClass() {}
...
+    }
+
+    public int count() {
+        return 1;
+    }
+    public static final test ONE = new test("world");
+    public static final test6 TWO = new test6() {
+    };
+
+    public static void main(String[] args) {
```
Comment (strkkk) [inline src/test/resources/com/puppycrawl/tools/checkstyle/checks/design/finalclass/InputFinalClass.java:162]: is this code useful for test input? Please remove if not

File: src/test/resources/com/puppycrawl/tools/checkstyle/checks/design/finalclass/InputFinalClass.java [hunk 3]
```diff
@@ -127,3 +129,52 @@ private SomeClass() {}
...
+        foo.forEach(test::new);
+
+    }
+}
+
+interface Test1 {
+    ArrayList<String> foo = new ArrayList<>();
+}
+
+// abstract classes cannot be final, see bug #837012
```
Comment (strkkk) [inline src/test/resources/com/puppycrawl/tools/checkstyle/checks/design/finalclass/InputFinalClass.java:175]: `bug #837012`
bug in what project?

File: src/test/resources/com/puppycrawl/tools/checkstyle/checks/design/finalclass/InputFinalClass.java [hunk 4]
```diff
@@ -127,3 +129,52 @@ private SomeClass() {}
...
+abstract class test9 {
+    private test9() {
+    }
+}
```
Comment (strkkk) [inline src/test/resources/com/puppycrawl/tools/checkstyle/checks/design/finalclass/InputFinalClass.java:179]: Please add `// ok` and `// violation` comments to lines where should be a violation and where it is ok

File: src/test/resources/com/puppycrawl/tools/checkstyle/checks/design/finalclass/InputFinalClass.java [hunk 5]
```diff
@@ -127,3 +129,52 @@ private SomeClass() {}
...
+        ArrayList<String> foo = new ArrayList<>();
+        foo.add("world");
+        foo.forEach(test::new);
+
+    }
+}
+
+interface Test1 {
+    ArrayList<String> foo = new ArrayList<>();
+}
```
Comment (strkkk) [inline src/test/resources/com/puppycrawl/tools/checkstyle/checks/design/finalclass/InputFinalClass.java:173]: is this needed for test?

**Review by strkkk — CHANGES_REQUESTED** [review]

File: src/test/resources/com/puppycrawl/tools/checkstyle/checks/design/finalclass/InputFinalClass.java (hunk 1 above)
Comment (Vyom-Yadav) [reply src/test/resources/com/puppycrawl/tools/checkstyle/checks/design/finalclass/InputFinalClass.java]: Changed name.

Comment (Vyom-Yadav) [reply src/test/resources/com/puppycrawl/tools/checkstyle/checks/design/finalclass/InputFinalClass.java]: Changed name.

File: src/test/resources/com/puppycrawl/tools/checkstyle/checks/design/finalclass/InputFinalClass.java (hunk 2 above)
Comment (Vyom-Yadav) [reply src/test/resources/com/puppycrawl/tools/checkstyle/checks/design/finalclass/InputFinalClass.java:162]: Yes it is, needed for coverage with `LITERAL_NEW`

File: src/test/resources/com/puppycrawl/tools/checkstyle/checks/design/finalclass/InputFinalClass.java (hunk 3 above)
Comment (Vyom-Yadav) [reply src/test/resources/com/puppycrawl/tools/checkstyle/checks/design/finalclass/InputFinalClass.java]: Idk, it was mentioned above, just wanted it to be consistent so used the same, but removed it now.

File: src/test/resources/com/puppycrawl/tools/checkstyle/checks/design/finalclass/InputFinalClass.java (hunk 5 above)
Comment (Vyom-Yadav) [reply src/test/resources/com/puppycrawl/tools/checkstyle/checks/design/finalclass/InputFinalClass.java:171]: Yes for coverage.

File: src/test/resources/com/puppycrawl/tools/checkstyle/checks/design/finalclass/InputFinalClass.java (hunk 4 above)
Comment (Vyom-Yadav) [reply src/test/resources/com/puppycrawl/tools/checkstyle/checks/design/finalclass/InputFinalClass.java:177]: done.

**Review by strkkk — APPROVED** [review]

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/design/FinalClassCheck.java [hunk 6]
```diff
@@ -411,6 +438,15 @@ private boolean isDeclaredAsAbstract() {
             return declaredAsAbstract;
         }
 
+        /**
+         * Does class have a anonymous inner class.
```
Comment (pbludov) [inline src/main/java/com/puppycrawl/tools/checkstyle/checks/design/FinalClassCheck.java:442]: typo: `an anonymous`

**Review by pbludov — CHANGES_REQUESTED** [review]
Please fix the typo.

**Comment by pbludov** [comment]
Regression report is good.

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/design/FinalClassCheck.java (hunk 6 above)
Comment (Vyom-Yadav) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/design/FinalClassCheck.java]: done.

**Review by pbludov — APPROVED** [review]

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/design/FinalClassCheck.java [hunk 7]
```diff
@@ -168,6 +173,19 @@ public void visitToken(DetailAST ast) {
                 }
                 break;
 
+            case TokenTypes.LITERAL_NEW:
+                if (ast.getFirstChild() != null) {
+                    final ClassDesc currClass = classes.peek();
+                    final String qualifiedAnonInnerClassName =
+                            packageName + PACKAGE_SEPARATOR + ast.getFirstChild().getText();
```
Comment (rnveach) [inline src/main/java/com/puppycrawl/tools/checkstyle/checks/design/FinalClassCheck.java:180]: Unless the code is otherwise, this does not look correct.

The qualified path of the anonymous class should include the class and any further anonymous classes inside it.
So package "a" and class "B" with anonymous class "C" should have a qualified path of "a.B.C". And if there is a anonymous class inside that of "D" it should have a qualified path of "a.B.C.D".

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/design/FinalClassCheck.java [hunk 8]
```diff
@@ -168,6 +173,19 @@ public void visitToken(DetailAST ast) {
...
+                    if (currClass != null
+                            && qualifiedAnonInnerClassName.equals(currClass.getQualifiedName())
```
Comment (rnveach) [inline src/main/java/com/puppycrawl/tools/checkstyle/checks/design/FinalClassCheck.java:182]: Why is this not just `ast.getFirstChild().getText().equals(currClass.getName)` ?

I believe you can't import a 2nd class with the same name as the main class. In addition, if a anonymous class is nested inside itself, you it doesn't matter how nested it is unless it matches the current class name.

File: src/test/resources/com/puppycrawl/tools/checkstyle/checks/design/finalclass/InputFinalClass.java [hunk 9]
```diff
@@ -127,3 +129,50 @@ private SomeClass() {}
         private SomeClass() {}
     }
 }
+
+class TestAnonymousInnerClasses { // ok
+    public static final TestAnonymousInnerClasses ONE = new TestAnonymousInnerClasses() {
```
Comment (rnveach) [inline src/test/resources/com/puppycrawl/tools/checkstyle/checks/design/finalclass/InputFinalClass.java:134]: As mentioned above, show a case where `TestAnonymousInnerClasses` has a nested anonymous class of some class which is **NOT** `TestAnonymousInnerClasses`, which also has another nested anonymous class of `TestAnonymousInnerClasses`.

2 layer inception.

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/design/FinalClassCheck.java (hunk 7 above)
Comment (Vyom-Yadav) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/design/FinalClassCheck.java]: Yes, totally agreed, idk how I missed that, fixed it now. Yeah, the binary name starts to become `<outerclass>$<innerclass>`.

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/design/FinalClassCheck.java (hunk 8 above)
Comment (Vyom-Yadav) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/design/FinalClassCheck.java]: `currClass.getQualifiedName()` is something like `com.puupycrawl.tools.ClassA` whereas `ast.getFirstChild().getText().equals(currClass.getName)` is equal to `ClassA`. I did some changes, so now it is fine imo.

File: src/test/resources/com/puppycrawl/tools/checkstyle/checks/design/finalclass/InputFinalClass.java (hunk 9 above)
Comment (Vyom-Yadav) [reply src/test/resources/com/puppycrawl/tools/checkstyle/checks/design/finalclass/InputFinalClass.java:134]: done.

**Comment by Vyom-Yadav** [comment]
Github, generate report

**Comment by Vyom-Yadav** [comment]
> https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/5d5d201_2021053045/reports/diff/index.html

I checked the report, it looks fine to me, all the violations removed were invalid.

**Comment by Vyom-Yadav** [comment]
Github, generate web site

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/design/FinalClassCheck.java [hunk 10]
```diff
@@ -220,6 +247,21 @@ private void registerNestedSubclassToOuterSuperClasses(DetailAST classAst) {
...
+     * @param ast current ast.
+     * @param classDesc class to match.
+     * @return true if current class name matches anonymous inner
+     *         class name.
+     */
+    private boolean doesNameOfClassMatchAnonymousInnerClassName(DetailAST ast,
+                                                               ClassDesc classDesc) {
+        final String classNameExtractor = Pattern.quote(packageName + PACKAGE_SEPARATOR) + "|\\.";
+        final String[] className = classDesc.getQualifiedName().split(classNameExtractor);
+        return ast.getFirstChild().getText().equals(className[className.length - 1]);
```
Comment (rnveach) [inline src/main/java/com/puppycrawl/tools/checkstyle/checks/design/FinalClassCheck.java:262]: Similar to https://github.com/checkstyle/checkstyle/pull/9383#discussion_r595431022 , why can't `classNameExtractor` just be `\\.` ? Can you show an example where we must look at package name?

Comment (Vyom-Yadav) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/design/FinalClassCheck.java:261]: Yes, it can be, just wanted to keep the array size small ( which won't create a big difference, I know), changed it.

**Review by rnveach — APPROVED** [review]

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/design/FinalClassCheck.java [hunk 11]
```diff
@@ -168,6 +182,17 @@ public void visitToken(DetailAST ast) {
                 }
                 break;
 
+            case TokenTypes.LITERAL_NEW:
+                if (ast.getFirstChild() != null) {
+                    for (ClassDesc classDesc : classes) {
+                        if (ast.getLastChild().getType() == TokenTypes.OBJBLOCK
```
Comment (rnveach) [inline src/main/java/com/puppycrawl/tools/checkstyle/checks/design/FinalClassCheck.java:188]: `ast` check is in `for` loop, but it's value will not change between the loops.
This should be added into `if (ast.getFirstChild() != null) {` check instead. It only needs to be checked once.

**Review by rnveach — CHANGES_REQUESTED** [review]
Sorry doing 1 last look before merge and saw:

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/design/FinalClassCheck.java (hunk 11 above)
Comment (Vyom-Yadav) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/design/FinalClassCheck.java]: Sry my bad, done.

**Review by rnveach — APPROVED** [review]

**Comment by rnveach** [comment]
CI failure is unrelated.
