### PR TITLE
Issue # 11187: OperatorWrapCheck throws NPE on guarded patterns

### LINKED ISSUE #11187: `OperatorWrapCheck` throws NPE on guarded patterns
Link to check documentation: https://checkstyle.sourceforge.io/config_whitespace.html#OperatorWrap

Noticed in https://github.com/checkstyle/checkstyle/pull/11186  at https://github.com/checkstyle/checkstyle/runs/4785736479?check_suite_focus=true :

```

➜  javac --enable-preview --release 17 Test.java             
Note: Test.java uses preview features of Java SE 17.
Note: Recompile with -Xlint:preview for details.

➜  cat Test.java                                             
public class Test {
    String typeGuardAfterParenthesizedTrueSwitchStatement(Object o) {
        switch (o) {
            case (Integer i) && i == 0: o = String.valueOf(i); return "true";
            case ((Integer i) && i == 2): o = String.valueOf(i); return "second";
            case Object x: return "any";
        }
    }

    String typeGuardAfterParenthesizedTrueSwitchExpression(Object o) {
        return switch (o) {
            case (Integer i) && i == 0: o = String.valueOf(i); yield "true";
            case ((Integer i) && i == 2): o = String.valueOf(i); yield "second";
            case Object x: yield "any";
        };
    }

    String typeGuardAfterParenthesizedTrueIfStatement(Object o) {
        if (o != null && o instanceof ((Integer i) && i == 0)) {
            return "true";
        } else if (o != null && o instanceof (((Integer i) && i == 2)) && (o = i) != null) {
            return "second";
        } else {
            return "any";
        }
    }
}

➜  cat config.xml                                            
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
        "-//Checkstyle//DTD Checkstyle Configuration 1.3//EN"
        "https://checkstyle.org/dtds/configuration_1_3.dtd">
<module name="Checker">
    <module name="TreeWalker">
        <module name="OperatorWrap">
        </module>
    </module>
</module>

➜  java -jar checkstyle-9.3-SNAPSHOT-all.jar -c config.xml Test.java
Starting audit...
com.puppycrawl.tools.checkstyle.api.CheckstyleException: Exception was thrown while processing Test.java
        at com.puppycrawl.tools.checkstyle.Checker.processFiles(Checker.java:305)
        at com.puppycrawl.tools.checkstyle.Checker.process(Checker.java:224)
        at com.puppycrawl.tools.checkstyle.Main.runCheckstyle(Main.java:407)
        at com.puppycrawl.tools.checkstyle.Main.runCli(Main.java:330)
        at com.puppycrawl.tools.checkstyle.Main.execute(Main.java:189)
        at com.puppycrawl.tools.checkstyle.Main.main(Main.java:126)
Caused by: java.lang.NullPointerException: Cannot invoke "com.puppycrawl.tools.checkstyle.api.DetailAST.getType()" because "result" is null
        at com.puppycrawl.tools.checkstyle.checks.whitespace.OperatorWrapCheck.adjustParens(OperatorWrapCheck.java:452)
        at com.puppycrawl.tools.checkstyle.checks.whitespace.OperatorWrapCheck.getLeftNode(OperatorWrapCheck.java:394)
        at com.puppycrawl.tools.checkstyle.checks.whitespace.OperatorWrapCheck.isNewLineModeViolation(OperatorWrapCheck.java:345)
        at com.puppycrawl.tools.checkstyle.checks.whitespace.OperatorWrapCheck.visitToken(OperatorWrapCheck.java:308)
        at com.puppycrawl.tools.checkstyle.TreeWalker.notifyVisit(TreeWalker.java:335)
        at com.puppycrawl.tools.checkstyle.TreeWalker.processIter(TreeWalker.java:406)
        at com.puppycrawl.tools.checkstyle.TreeWalker.walk(TreeWalker.java:273)
        at com.puppycrawl.tools.checkstyle.TreeWalker.processFiltered(TreeWalker.java:154)
        at com.puppycrawl.tools.checkstyle.api.AbstractFileSetCheck.process(AbstractFileSetCheck.java:87)
        at com.puppycrawl.tools.checkstyle.Checker.processFile(Checker.java:331)
        at com.puppycrawl.tools.checkstyle.Checker.processFiles(Checker.java:292)
        ... 5 more
Checkstyle ends with 1 errors.


```

I would expect `OperatorWrapCheck` to process `Test.java` without throwing a null pointer exception.

We can remove file filter for this file from `openjdk17-excluded.files` in PR for this issue, and exclusion from any project files in contribution.

### PR DESCRIPTION
**Pull request by nmancus1**
Closes #11187

Diff Regression config: https://gist.githubusercontent.com/nmancus1/284f66dbf5a076b43708b7685ee9bd53/raw/c595fc26ae622509dadcd25ca6fe02b3db5ffaac/config.xml

Diff Regression projects: https://raw.githubusercontent.com/checkstyle/contribution/e34312d61da0b073f31339cfbf385f289b721fed/checkstyle-tester/projects-to-test-on-for-github-action.properties

Final report: https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/586d278_2022024156/reports/diff/index.html

No diffs now that #10848 is closed.

### CODE REVIEW

**Comment by nmancus1** [comment]
I am leaving this is draft until https://github.com/checkstyle/checkstyle/pull/11100 is merged

**Comment by nmancus1** [comment]
Github, generate report

**Comment by nmancus1** [comment]
CI failure is not related: `Connect to www.w3.org:80 [www.w3.org/128.30.52.100] failed: Connection timed out`

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/OperatorWrapCheck.java [hunk 1]
```diff
@@ -399,6 +402,21 @@ private static DetailAST getLeftNode(DetailAST node) {
...
+     * Ascends AST to determine if given node is part of a pattern
+     * definition.
+     *
+     * @param node the node to check
+     * @return true if node is in pattern definition
+     */
+    private static boolean isInPatternDefinition(DetailAST node) {
+        DetailAST parent = node.getParent();
+        while (parent != null && parent.getType() != TokenTypes.PATTERN_DEF) {
+            parent = parent.getParent();
```
Comment (rnveach) [inline src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/OperatorWrapCheck.java:415]: why not?
````
DetailAST parent = node;
do {
    parent = parent.getParent();
} while (parent != null && parent.getType() != TokenTypes.PATTERN_DEF);
````

Also we are passing through parents uncontrolled. It doesn't matter if we pass any other kind of def before hitting the pattern def?

Comment (nmancus1) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/OperatorWrapCheck.java:415]: > why not...

Please explain the advantage of this; to me the name of variable declared (`parent`) and initialization (`node.getParent();`) makes sense. Since we are checking operands, there is absolutely no chance that `node` is null (it will always have an operator as a parent).

>  It doesn't matter if we pass any other kind of def before hitting the pattern def?

To the check, no. And a local variable(pattern definition) will always have an enclosing block of some sort, so we certainly could just check for a method defintion, and stop there. But, I generally avoid this sort of "optimization" since pitest normally fails on this sort of thing.

Comment (romani) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/OperatorWrapCheck.java:415]: I do not know why, but my brain not always work quick on do-while structure. I prefer while loop in this case.

**Review by romani — APPROVED** [review]
last commit is ok to merge

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/OperatorWrapCheck.java (hunk 1 above)
Comment (rnveach) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/OperatorWrapCheck.java:415]: Not a big deal in this case, but I see the duplication of `getParent` and possibly an extra unnecessary condition check at the start of the loop and I think how to optimize it more. Hence the do-while version.

Comment (rnveach) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/OperatorWrapCheck.java:415]: > On second thought, I might be able to create a case to make this fail.

I am assuming this item is still TODO until told otherwise.

Comment (nmancus1) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/OperatorWrapCheck.java:416]: >On second thought, I might be able to create a case to make this fail.

Disregard this.

Replaced while with do-while.

**Comment by nmancus1** [comment]
Github, generate report

**Comment by nmancus1** [comment]
Github, generate report

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/OperatorWrapCheck.java (hunk 1 above)
Comment (rnveach) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/OperatorWrapCheck.java:416]: So I saw the update, but I am still not really seeing a conclusion to this item:
> It doesn't matter if we pass any other kind of def before hitting the pattern def?

For example, it doesn't matter if we pass through an anonymous class to get to the pattern def or patterns are such that we are either in it or not for what we stop on.

Comment (nmancus1) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/OperatorWrapCheck.java:416]: > anonymous class to get to the pattern def 

It is not possible to declare an anonymous class within a pattern definition.

>  patterns are such that we are either in it or not for what we stop on.

Please restate this, I am not sure that I understand what you are asking.

Comment (romani) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/OperatorWrapCheck.java:416]: Reminder. This is fix for exception, it should merged sooner. If we think there is some false positive, it is better to address in separate issue.

Comment (rnveach) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/OperatorWrapCheck.java:416]: I will approve the PR, but we have seen cases before where we either go too deep in the tree or go past too many key nodes when looking for "something" and we are accidentally pulling in nodes wrongly or passing things that should have stopped us. `branchContains` is one good example. https://github.com/checkstyle/checkstyle/issues/5124#issue-258583861 details the specifics of how it was going to far and wasn't be used carefully enough.

Whenever I see a loop where we are scanning up or down uncontrolled, I get concerned. I don't know the new Java syntax well, so I can't explain a possible situation to prompt a more meaningful conversation. I am just making sure this won't be an issue later.

**Comment by nmancus1** [comment]
Github, generate report

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/OperatorWrapCheck.java (hunk 1 above)
Comment (nmancus1) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/OperatorWrapCheck.java:416]: Condition is updated to exit on pattern def or expression node.

**Comment by nmancus1** [comment]
Github, rebase

**Comment by romani** [comment]
Regression , NPE is detected by CI.

**Comment by nmancus1** [comment]
Github, generate report

**Comment by nmancus1** [comment]
Github, generate report

**Review by rnveach — APPROVED** [review]

**Comment by rnveach** [comment]
Fix was merged
