### PR TITLE
Issue #13048: Disable indentation checking for the content of <pre> tag

### LINKED ISSUE #13048: JavadocTagContinuationIndentation check doesn't support arbitrary indentation on &lt;pre&gt; tags
I have read check documentation: https://checkstyle.org/config_javadoc.html#JavadocTagContinuationIndentation
I have downloaded the latest checkstyle from: https://checkstyle.org/cmdline.html#Download_and_Run
I have executed the cli and showed it below, as cli describes the problem better than 1,000 words

```bash
$ javac Test.java

$ cat test-checkstyle.xml
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
          "-//Checkstyle//DTD Checkstyle Configuration 1.3//EN"
          "https://checkstyle.org/dtds/configuration_1_3.dtd">
<module name = "Checker">
  <module name="TreeWalker">
    <module name="JavadocTagContinuationIndentation"/>
  </module>
</module>

$ cat Test.java 
/**
 * Test class.
 *
 * @apiNote
 *          This is the predefined indentation applied by Eclipse formatter to api/impl taglets.
 *          <pre>
 * Since &lt;pre> blocks retain leading whitespace, in order to avoid extra-indentation from being
 * added by the javadoc renderer, its content herein has to stick to the left margin of the comment
 * area. Unfortunately, checkstyle seems not to properly evaluate the context (&lt;pre> block) of
 * this content, and reports an error:
 *   "JavadocTagContinuationIndentation: Line continuation have incorrect indentation level,
 *   expected level should be 4"</pre>
 */
public class Test {
  public static void main(String[] args) {
  }
}

$ java -jar checkstyle-10.10.0-all.jar -c test-checkstyle.xml Test.java
Starting audit...
[ERROR] Test.java:7: Line continuation have incorrect indentation level, expected level should be 4. [JavadocTagContinuationIndentation]
[ERROR] Test.java:8: Line continuation have incorrect indentation level, expected level should be 4. [JavadocTagContinuationIndentation]
. . .
[ERROR] Test.java:12: Line continuation have incorrect indentation level, expected level should be 4. [JavadocTagContinuationIndentation]
Audit done.
Checkstyle ends with 6 errors.
```
---
CURRENT BEHAVIOR
Since &lt;pre&gt; blocks retain leading whitespace, in order to avoid extra-indentation from being added by the javadoc renderer, I have to stick their contents to the left margin of the comment area (like in `Test.java` here above) — here it is the intended result:
Test-javadoc

Unfortunately, _checkstyle seems not to properly evaluate the context (i.e., it is unable to detect such contents are in a pre-formatted block which should be excluded from indentation enforcement)_, and raises errors of non-continuous indentation.

BTW, if, conversely, I conform the indentation of the pre-formatted block to the checkstyle rule this way...
```bash
/**
 * Test class.
 *
 * @apiNote
 *          This is the predefined indentation applied by Eclipse formatter to api/impl taglets.
 *          <pre>
 *          Since &lt;pre> blocks retain leading whitespace, in order to avoid extra-indentation from being
 *          added by the javadoc renderer, its content herein has to stick to the left margin of the comment
 *          area. Unfortunately, checkstyle seems not to properly evaluate the context (&lt;pre> block) of
 *          this content, and reports an error:
 *            "JavadocTagContinuationIndentation: Line continuation have incorrect indentation level,
 *            expected level should be 4"</pre>
 */
public class Test_extraindent {
  public static void main(String[] args) {
  }
}
```
...the resulting HTML rendering is —unsurprisingly— unacceptably over-indented (the same happens when rendered directly from source code in the Javadoc view of Eclipse IDE):
Test_extraindent-javadoc

---
EXPECTED BEHAVIOR
Because of their inherent semantics, **pre-formatted blocks should be allowed arbitrary indentation**: once checkstyle detects an opening &lt;pre&gt; tag, it should automatically disable the `JavadocTagContinuationIndentation` check until it reaches its corresponding closing &lt;/pre&gt; tag.

### PR DESCRIPTION
**Pull request by mohitsatr**
fixes #13048

### CODE REVIEW

**Comment by mohitsatr** [comment]
Github, generate report for JavadocTagContinuationIndentation/all-examples-in-one

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocTagContinuationIndentationCheck.java [hunk 1]
```diff
@@ -178,14 +187,18 @@ private static List<DetailNode> getAllNewlineNodes(DetailNode descriptionNode) {
                 textNodes.addAll(getAllNewlineNodes(descriptionNodeChild));
             }
             else if (node.getType() == JavadocTokenTypes.HTML_ELEMENT_START
-                || node.getType() == JavadocTokenTypes.ATTRIBUTE) {
+                    || node.getType() == JavadocTokenTypes.ATTRIBUTE) {
```
Comment (Zopsss) [inline src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocTagContinuationIndentationCheck.java]: Please revert

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocTagContinuationIndentationCheck.java [hunk 2]
```diff
@@ -178,14 +187,18 @@ private static List<DetailNode> getAllNewlineNodes(DetailNode descriptionNode) {
...
                 textNodes.addAll(getAllNewlineNodes(node));
             }
-            if (node.getType() == JavadocTokenTypes.LEADING_ASTERISK) {
+            if (node.getType() == JavadocTokenTypes.LEADING_ASTERISK
+                    || node.getType() == JavadocTokenTypes.HTML_TAG_NAME) {
                 textNodes.add(node);
             }
```
Comment (Zopsss) [inline src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocTagContinuationIndentationCheck.java:186]: I am assuming that it'll add the whole node to the final list? Please correct me if I'm wrong.

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocTagContinuationIndentationCheck.java [hunk 3]
```diff
@@ -178,14 +187,18 @@ private static List<DetailNode> getAllNewlineNodes(DetailNode descriptionNode) {
...
             node = JavadocUtil.getNextSibling(node);
         }
+        if (node.getType() == JavadocTokenTypes.HTML_ELEMENT_END) {
+            textNodes.addAll(getAllNewlineNodes(node));
+        }
```
Comment (Zopsss) [inline src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocTagContinuationIndentationCheck.java]: Why do we need to recursively call the method again for ending html tag? Sorry I cannot debug the code as I don't have my laptop with me.

**Comment by Zopsss** [comment]
why did we had violation for closing tag? @mohitsatr @romani 

https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/a5d2c385d103d691ae5b4ea0d6e72e4cb86242a0_2025082607/reports/diff/openjdk21/index.html#A34

**Comment by Zopsss** [comment]
https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/a5d2c385d103d691ae5b4ea0d6e72e4cb86242a0_2025082607/reports/diff/openjdk21/index.html#A447

Line 276 was not marked as violation. Please add this case to our input and make sure it doesn't throw violation. @mohitsatr

**Comment by Zopsss** [comment]
please add this cases to our inputs:

https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/a5d2c385d103d691ae5b4ea0d6e72e4cb86242a0_2025082607/reports/diff/openjdk21/index.html#A475 ( Line 198-205 )

https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/a5d2c385d103d691ae5b4ea0d6e72e4cb86242a0_2025082607/reports/diff/openjdk21/index.html#A493 ( Line 110-112 )

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocTagContinuationIndentationCheck.java [hunk 4]
```diff
@@ -121,9 +121,18 @@ public int[] getRequiredJavadocTokens() {
...
             final List<DetailNode> textNodes = getAllNewlineNodes(ast);
+            boolean preTagIsActive = false;
             for (DetailNode newlineNode : textNodes) {
                 final DetailNode textNode = JavadocUtil.getNextSibling(newlineNode);
-                if (textNode.getType() != JavadocTokenTypes.NEWLINE && isViolation(textNode)) {
+                if (newlineNode.getType() == JavadocTokenTypes.HTML_TAG_NAME) {
+                    if ("pre".equals(newlineNode.getText())) {
+                        preTagIsActive = !preTagIsActive;
+                    }
+                    continue;
```
Comment (romani) [inline src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocTagContinuationIndentationCheck.java]: Please use "else" for next if ,  instead of continue.

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocTagContinuationIndentationCheck.java [hunk 5]
```diff
@@ -121,9 +121,18 @@ public int[] getRequiredJavadocTokens() {
     public void visitJavadocToken(DetailNode ast) {
         if (isBlockDescription(ast) && !isInlineDescription(ast)) {
             final List<DetailNode> textNodes = getAllNewlineNodes(ast);
+            boolean preTagIsActive = false;
             for (DetailNode newlineNode : textNodes) {
                 final DetailNode textNode = JavadocUtil.getNextSibling(newlineNode);
-                if (textNode.getType() != JavadocTokenTypes.NEWLINE && isViolation(textNode)) {
+                if (newlineNode.getType() == JavadocTokenTypes.HTML_TAG_NAME) {
+                    if ("pre".equals(newlineNode.getText())) {
+                        preTagIsActive = !preTagIsActive;
```
Comment (romani) [inline src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocTagContinuationIndentationCheck.java]: We need to differentiate open and closing PRE tags.

**Review by romani — CHANGES_REQUESTED** [review]
Items

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocTagContinuationIndentationCheck.java (hunk 3 above)
Comment (mohitsatr) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocTagContinuationIndentationCheck.java]: It's because of the way DetailAST is structured. try to debug and you will understand.

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocTagContinuationIndentationCheck.java (hunk 2 above)
Comment (mohitsatr) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocTagContinuationIndentationCheck.java:186]: Yes. 
Screenshot from 2025-09-08 16-46-56

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocTagContinuationIndentationCheck.java (hunk 4 above)
Comment (mohitsatr) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocTagContinuationIndentationCheck.java]: done

**Comment by mohitsatr** [comment]
Github, generate report for JavadocTagContinuationIndentation/all-examples-in-one

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocTagContinuationIndentationCheck.java (hunk 5 above)
Comment (mohitsatr) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocTagContinuationIndentationCheck.java]: It might be difficult to add HTML opening and closing tag to the list. 

we are also sure that there won't be any nested PRE tags. so the above approach seems good to me. 

wdyt?

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocTagContinuationIndentationCheck.java [hunk 6]
```diff
@@ -138,17 +145,42 @@ private static List<DetailNode> getAllNewlineNodes(DetailNode descriptionNode) {
...
+        if (ast.getType() == JavadocTokenTypes.HTML_ELEMENT) {
+            final DetailNode htmlTag = JavadocUtil.getFirstChild(node);
+            if (htmlTag.getType() == JavadocTokenTypes.HTML_TAG) {
+                final DetailNode htmlElementStart = JavadocUtil.getFirstChild(htmlTag);
+                node = JavadocUtil.findFirstToken(htmlElementStart,
+                    JavadocTokenTypes.HTML_TAG_NAME);
+
+            }
+        }
+        return "pre".equals(node.getText());
```
Comment (romani) [inline src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocTagContinuationIndentationCheck.java]: please do comparison with ignore case.

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocTagContinuationIndentationCheck.java (hunk 5 above)
Comment (romani) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocTagContinuationIndentationCheck.java]: please update logic to use open/closed tags and ingnorecase on tag comparison.
We can skip fight with nested PRE tags, if users complains we will improve far later on.

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocTagContinuationIndentationCheck.java
Comment (Zopsss) [inline src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocTagContinuationIndentationCheck.java:1]: we're almost there! Please update Check description to mention that this check skips pre tags.

File: src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadoctagcontinuationindentation/InputJavadocTagContinuationIndentationBlockTag.java [hunk 7]
```diff
@@ -61,7 +61,7 @@ public int identity(int x) {
      * @param args
      * {@code this} line is not correctly indented // violation
      *     {@code this}
-     * <pre>this line is not correctly indented</pre> // violation
+     * <pre>this line is not correctly indented</pre>
```
Comment (Zopsss) [inline src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadoctagcontinuationindentation/InputJavadocTagContinuationIndentationBlockTag.java]:
```suggestion
     * <pre>pre tags are skipped</pre>
```

File: src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadoctagcontinuationindentation/InputJavadocTagContinuationIndentationBlockTag.java [hunk 8]
```diff
@@ -73,7 +73,7 @@ public void multipleLines1(String args) {
      * @return false always
      * {@code this} line is not correctly indented // violation
      * {@code this} line is not correctly indented // violation
-     * <pre>this line is not correctly indented</pre> // violation
+     * <pre>this line is not correctly indented</pre>
```
Comment (Zopsss) [inline src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadoctagcontinuationindentation/InputJavadocTagContinuationIndentationBlockTag.java]: same as above

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocTagContinuationIndentationCheck.java [hunk 9]
```diff
@@ -81,9 +81,14 @@ public int[] getRequiredJavadocTokens() {
     public void visitJavadocToken(DetailNode ast) {
         if (isBlockDescription(ast) && !isInlineDescription(ast)) {
             final List<DetailNode> textNodes = getAllNewlineNodes(ast);
+            boolean isTextPreTagChildren = false;
             for (DetailNode newlineNode : textNodes) {
                 final DetailNode textNode = JavadocUtil.getNextSibling(newlineNode);
-                if (textNode.getType() != JavadocTokenTypes.NEWLINE && isViolation(textNode)) {
+                if (newlineNode.getType() == JavadocTokenTypes.HTML_TAG_NAME) {
+                    isTextPreTagChildren = !isTextPreTagChildren;
+                }
```
Comment (mohitsatr) [inline src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocTagContinuationIndentationCheck.java:96]: > update logic to use open/closed tags

@romani I'm having hard time understanding above. Do you want something like:

```
if (node.getType() == HTML_ELEMENT_START) {
  isTextPreTagChildren =  true;
}
else if (node.getType() == HTML_ELEMENT_END) {
  isTextPreTagChildren = false;
}

Comment (Zopsss) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocTagContinuationIndentationCheck.java:96]: this would be more easy to understand.

Comment (mohitsatr) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocTagContinuationIndentationCheck.java:96]: done

File: src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadoctagcontinuationindentation/InputJavadocTagContinuationIndentationBlockTag.java (hunk 8 above)
Comment (mohitsatr) [reply src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadoctagcontinuationindentation/InputJavadocTagContinuationIndentationBlockTag.java]: done

File: src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadoctagcontinuationindentation/InputJavadocTagContinuationIndentationBlockTag.java (hunk 7 above)
Comment (mohitsatr) [reply src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadoctagcontinuationindentation/InputJavadocTagContinuationIndentationBlockTag.java]: done

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocTagContinuationIndentationCheck.java
Comment (mohitsatr) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocTagContinuationIndentationCheck.java:1]: Let's do that in separate supplemental PR after this one merges. I will also include example of pre tag skipping

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocTagContinuationIndentationCheck.java (hunk 6 above)
Comment (mohitsatr) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocTagContinuationIndentationCheck.java]: done

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocTagContinuationIndentationCheck.java (hunk 5 above)
Comment (mohitsatr) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocTagContinuationIndentationCheck.java]: done

**Comment by mohitsatr** [comment]
Github, generate report for JavadocTagContinuationIndentation/all-examples-in-one

**Comment by mohitsatr** [comment]
@Zopsss the difference in last two reports.

https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/98a80e139814e56b37bfb54506c7a1482670f81c_2025143853/reports/diff/openjdk21/index.html#A1224
https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/98a80e139814e56b37bfb54506c7a1482670f81c_2025143853/reports/diff/openjdk21/index.html#A1262
https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/98a80e139814e56b37bfb54506c7a1482670f81c_2025143853/reports/diff/openjdk21/index.html#A1350

Previously we are ignoring Uppercased `PRE`.

**Comment by mohitsatr** [comment]
Github, generate report for JavadocTagContinuationIndentation/all-examples-in-one

**Comment by Zopsss** [comment]
Github, generate report for JavadocTagContinuationIndentation/all-examples-in-one

**Comment by mohitsatr** [comment]
No change in latest report! good to go

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocTagContinuationIndentationCheck.java (hunk 9 above)
Comment (Zopsss) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocTagContinuationIndentationCheck.java:96]: resolved.

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocTagContinuationIndentationCheck.java (hunk 5 above)
Comment (Zopsss) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocTagContinuationIndentationCheck.java]: resolved at https://github.com/checkstyle/checkstyle/pull/17729#discussion_r2338861204

File: src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadoctagcontinuationindentation/InputJavadocTagContinuationIndentationBlockTag.java (hunk 7 above)
Comment (Zopsss) [reply src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadoctagcontinuationindentation/InputJavadocTagContinuationIndentationBlockTag.java]: resolved.

File: src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadoctagcontinuationindentation/InputJavadocTagContinuationIndentationBlockTag.java (hunk 8 above)
Comment (Zopsss) [reply src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadoctagcontinuationindentation/InputJavadocTagContinuationIndentationBlockTag.java]: resolved.

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocTagContinuationIndentationCheck.java (hunk 6 above)
Comment (Zopsss) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocTagContinuationIndentationCheck.java]: changes are made ( https://github.com/checkstyle/checkstyle/pull/17729#issuecomment-3290714343 ). Resolved.

**Comment by Zopsss** [comment]
Please add this whole javadoc to our inputs: https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/ca638d873b3e21ddb48d4530c937fef8a62e3eba_2025060839/reports/diff/spoon/index.html#A10

**Comment by mohitsatr** [comment]
Github, generate report for JavadocTagContinuationIndentation/all-examples-in-one

**Comment by mohitsatr** [comment]
Github, generate report for JavadocTagContinuationIndentation/all-examples-in-one

**Comment by Zopsss** [comment]
good! We're now able to ignore whole content of pre tag mentioned at: https://github.com/checkstyle/checkstyle/pull/17729#issuecomment-3301469602

File: config/linkcheck-suppressions.txt [hunk 10]
```diff
@@ -831,7 +831,6 @@
 <a href="apidocs/com/puppycrawl/tools/checkstyle/xpath/iterators/ReverseDescendantIterator.html#%3Cinit%3E(net.sf.saxon.om.NodeInfo)">#%3Cinit%3E(net.sf.saxon.om.NodeInfo)</a>: doesn't exist.
 <a href="apidocs/com/puppycrawl/tools/checkstyle/xpath/iterators/ReverseListIterator.html#%3Cinit%3E(java.util.Collection)">#%3Cinit%3E(java.util.Collection)</a>: doesn't exist.
 <a href="apidocs/com/puppycrawl/tools/checkstyle/site/XdocsTemplateSink.CustomPrintWriter.html#%3Cinit%3E(java.io.Writer)">#%3Cinit%3E(java.io.Writer)</a>: doesn't exist.
-<a href="apidocs/constant-values.html#com.puppycrawl">#com.puppycrawl</a>: doesn't exist.
```
Comment (romani) [inline config/linkcheck-suppressions.txt:834]: Please remove it, I merged fix to this problem to master

**Review by romani — CHANGES_REQUESTED** [review]
Please update docs in this PR, let's keep it atomic to whole update 

Items:

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocTagContinuationIndentationCheck.java
Comment (romani) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocTagContinuationIndentationCheck.java:1]: Please do in this PR

**Comment by mohitsatr** [comment]
docs updated https://github.com/checkstyle/checkstyle/pull/17809

File: config/linkcheck-suppressions.txt (hunk 10 above)
Comment (mohitsatr) [reply config/linkcheck-suppressions.txt:834]: done

**Comment by romani** [comment]
please add doc to this PR to have all changes at one commit, to see whole picture of update.

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocTagContinuationIndentationCheck.java [hunk 11]
```diff
@@ -81,15 +81,36 @@ public int[] getRequiredJavadocTokens() {
...
     }
 
+    /**
+     * Checks if the given HTML_TAG is contained inside {@code <pre>} tag.
+     *
+     * @param htmlTag HTML_TAG
+     * @return {@code true} if {@code pre} tag is parent of the given tag, else {@code false}.
+     */
+    private static boolean isHtmlTagChildOfPreTag(DetailNode htmlTag) {
+        DetailNode node = htmlTag.getParent().getParent();
```
Comment (romani) [inline src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocTagContinuationIndentationCheck.java:124]: why two parents?

amount of html tags nesting can be any.
if it is structure of AST, please explain it in javadoc

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocTagContinuationIndentationCheck.java [hunk 12]
```diff
@@ -139,16 +162,47 @@ private static List<DetailNode> getAllNewlineNodes(DetailNode descriptionNode) {
...
+    /**
+     * Checks if the given HTML related node contains {@code <pre>} tag.
+     *
+     * @param ast the node to check
+     * @return {@code true} if the {@code <pre>} tag is inside the node, {@code false} otherwise
+     */
+    private static boolean containsPreTag(DetailNode ast) {
+        DetailNode node = ast;
+        if (node.getType() == JavadocTokenTypes.HTML_ELEMENT_END
+                || node.getType() == JavadocTokenTypes.HTML_ELEMENT_START) {
```
Comment (romani) [inline src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocTagContinuationIndentationCheck.java]: please make HTML_ELEMENT_START to be first in expression, just ease reading.

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocTagContinuationIndentationCheck.java [hunk 13]
```diff
@@ -106,8 +127,10 @@ private boolean isViolation(DetailNode textNode) {
         if (text.length() <= offset) {
             if (CommonUtil.isBlank(text)) {
                 final DetailNode nextNode = JavadocUtil.getNextSibling(textNode);
-                if (nextNode != null && nextNode.getType() != JavadocTokenTypes.NEWLINE) {
-                    // text is blank but line hasn't ended yet
+                // text is blank but line hasn't ended yet
+                if (nextNode != null && nextNode.getType() != JavadocTokenTypes.NEWLINE
+                        && !containsPreTag(nextNode)) {
+                    // don't include if followed with <pre> tag
```
Comment (romani) [inline src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocTagContinuationIndentationCheck.java]: remove this comment.

and  .... followed or contains ?

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocTagContinuationIndentationCheck.java [hunk 14]
```diff
@@ -81,15 +81,36 @@ public int[] getRequiredJavadocTokens() {
     public void visitJavadocToken(DetailNode ast) {
         if (isBlockDescription(ast) && !isInlineDescription(ast)) {
             final List<DetailNode> textNodes = getAllNewlineNodes(ast);
+            boolean isTextPreTagChildren = false;
             for (DetailNode newlineNode : textNodes) {
                 final DetailNode textNode = JavadocUtil.getNextSibling(newlineNode);
-                if (textNode.getType() != JavadocTokenTypes.NEWLINE && isViolation(textNode)) {
+                if (newlineNode.getType() == JavadocTokenTypes.HTML_ELEMENT_START
+                        || isHtmlTagChildOfPreTag(ast)) {
+                    isTextPreTagChildren = true;
```
Comment (romani) [inline src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocTagContinuationIndentationCheck.java:95]: logic is strange in reading.

it can be evaluated to:
`isTextPreTagChildren = newlineNode.getType() == JavadocTokenTypes.HTML_ELEMENT_START`

that is nonsense.
Please explain.

**Review by romani — CHANGES_REQUESTED** [review]
items:

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocTagContinuationIndentationCheck.java (hunk 11 above)
Comment (mohitsatr) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocTagContinuationIndentationCheck.java:124]: Two parents from the `HTML_TAG` should give us what we are looking for. I even added a condition earlier ([here](https://github.com/checkstyle/checkstyle/commit/29e742045a90c5bbaed58dd19370fdf9924e42db#diff-969a985979cb2232b341a5f1e733510cf58385daa7b077ff67f8a13af62ef8a7R110)):

```
if (node.getType == HTML_TAG) {
    node = htmlTag.getParent().getParent() 
    ...
    ...
}
```
but Pitest produced a mutation on the condition and removing the condition did not affect the tests and regression report.

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocTagContinuationIndentationCheck.java (hunk 13 above)
Comment (mohitsatr) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocTagContinuationIndentationCheck.java]: sorry for vagueness.

contains because `containsPreTag()` checks if `HTML` related JavadocToken is of `pre` tag

followed because this logic is for checking if there is other html tag after pre tag. Example:

```
* <pre><code>
*    def start() {
*   ....   
*   }
* </code></pre>
*

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocTagContinuationIndentationCheck.java (hunk 14 above)
Comment (mohitsatr) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocTagContinuationIndentationCheck.java:95]: If we come across `HTML_ELEMENT_START` or `HTML_ELEMENT_END` in the iteration, then it is 100% certain these are `pre` tag tokens.
When we get to `HTML_ELEMENT_START`, it means the `pre` tag is present in the javadoc. 
`isTextPreTagChildren` becomes true, implying following text is the contained inside `pre` tag. 

So we skip checking the next following lines until we get to `HTML_ELEMENT_END`.

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocTagContinuationIndentationCheck.java (hunk 12 above)
Comment (mohitsatr) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocTagContinuationIndentationCheck.java]: done

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocTagContinuationIndentationCheck.java (hunk 13 above)
Comment (mohitsatr) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocTagContinuationIndentationCheck.java]: javadoc updated.

**Comment by mohitsatr** [comment]
Github, generate website

**Comment by romani** [comment]
@mohitsatr , please fix CI

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocTagContinuationIndentationCheck.java
Comment (Zopsss) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocTagContinuationIndentationCheck.java:1]: Resolved

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocTagContinuationIndentationCheck.java [hunk 15]
```diff
@@ -35,6 +35,7 @@
  * throws a violation. A continuation line is when the description starts/spans past the line with
  * the tag. Default indentation required is at least 4, but this can be changed with the help of
  * properties below.
+ * Note: This check does not validate the indentation of lines inside {@code pre} tags.
```
Comment (Zopsss) [inline src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocTagContinuationIndentationCheck.java]: Note should be in it's own section. 

Example: https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/5ebe136_20250923113016/checks/annotation/annotationlocation.html

Comment (romani) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocTagContinuationIndentationCheck.java]: We have it like text in description https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/5ebe136_20250923113016/checks/javadoc/javadoctagcontinuationindentation.html#Description

But should be like https://checkstyle.org/checks/sizes/linelength.html#Notes

**Comment by mohitsatr** [comment]
Github, generate website

**Comment by romani** [comment]
I don't see bore section, did you add it to template?

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocTagContinuationIndentationCheck.java (hunk 15 above)
Comment (mohitsatr) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocTagContinuationIndentationCheck.java]: done

Comment (romani) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocTagContinuationIndentationCheck.java]: Please see comment below

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocTagContinuationIndentationCheck.java [hunk 16]
```diff
@@ -36,6 +36,12 @@
  * the tag. Default indentation required is at least 4, but this can be changed with the help of
  * properties below.
  * </div>
+ * <ul>
+ * <li>
+ * Notes:
+ * This check does not validate the indentation of lines inside {@code pre} tags.
+ * </li>
+ * </ul>
```
Comment (mohitsatr) [inline src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocTagContinuationIndentationCheck.java:44]: @romani I updated the javadoc here. shouldn't .xml files get updated too because of macros?

Comment (mohitsatr) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocTagContinuationIndentationCheck.java:44]: Nevermind. Got it. Notes section needs to added in .template file

**Comment by mohitsatr** [comment]
Github, generate website

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocTagContinuationIndentationCheck.java (hunk 15 above)
Comment (mohitsatr) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocTagContinuationIndentationCheck.java]: done

**Comment by romani** [comment]
we did it !!!!
