### PR TITLE
Issue #12765: CommitValidationTest should ignore the release process

### LINKED ISSUE #12765: CommitValidationTest should ignore the release process
Identified in gitter and at https://dev.azure.com/romanivanovjr/romanivanovjr/_build/results?buildId=13251&view=logs&j=c902ebb4-c9f8-5f09-4e17-ff78fbbc842e&t=9ca98c81-ff64-58f0-9d03-a23ac1c4a111&l=795 ,

`[ERROR]   CommitValidationTest.testCommitMessageHasProperStructure:183 Commit 97ae29bd44209dc6a7f2082516e4175726a9b77e message: "[maven-release-plugin] prepare for next development iteration\n" `

Admins were an ignored user but now they aren't since a recent update and have to follow the proper commit process.

However, the valid use of the release process should not fail the CommitValidationTest. It is the proper commit messaging we use for releases.

The test needs to be updated to not fail on valid release process commits.

### PR DESCRIPTION
**Pull request by stoyanK7**
Resolves #12765

I identified only 2 types release commit messages:
- `[maven-release-plugin] prepare for next development iteration`
- `[maven-release-plugin] prepare release checkstyle-10.8.0`

Proof that it works. First I checkout to faulty commit and run test so it fails. Then I apply this commit on top and run test again:
[Screencast from 23-02-23 22:18:54.webm](https://user-images.githubusercontent.com/23459549/221034936-20b3995a-f985-45d6-8975-c9648deba270.webm)

### CODE REVIEW

**Comment by stoyanK7** [comment]
Just a throwing this out there. These commit messages can be edited so they follow the `(minor|config|infra|doc|spelling|dependency|supplemental|whatever)` rule that checkstyle has:
 - https://maven.apache.org/maven-release/maven-release-plugin/prepare-mojo.html#scmcommentprefix
   > The message prefix to use for all SCM changes.
    Type: java.lang.String
    Since: 2.0-beta-5
    Required: No
    User Property: scmCommentPrefix
    Default: [maven-release-plugin]

 - https://maven.apache.org/maven-release/maven-release-plugin/prepare-mojo.html#scmdevelopmentcommitcomment
  >The SCM commit comment when setting pom.xml back to development. Defaults to "@{prefix} prepare for next development iteration". 
    Type: java.lang.String
    Since: 3.0.0-M1
    Required: No
    User Property: scmDevelopmentCommitComment
    Default: @{prefix} prepare for next development iteration

**Comment by nrmancuso** [comment]
> Just a throwing this out there. These commit messages can be edited so they follow the `(minor|config|infra|doc|spelling|dependency|supplemental|whatever)` rule that checkstyle has

This was my thinking, why not just make everything conform to the existing rules

File: src/test/java/com/puppycrawl/tools/checkstyle/internal/CommitValidationTest.java [hunk 1]
```diff
@@ -316,6 +319,7 @@ private static String getRulesForCommitMessageFormatting() {
                 + "    1) Must match one of the following patterns:\n"
                 + "        " + ISSUE_COMMIT_MESSAGE_REGEX_PATTERN + "\n"
                 + "        " + PR_COMMIT_MESSAGE_REGEX_PATTERN + "\n"
+                + "        " + RELEASE_COMMIT_MESSAGE_REGEX_PATTERN + "\n"
```
Comment (romani) [inline src/test/java/com/puppycrawl/tools/checkstyle/internal/CommitValidationTest.java:322]: I would not print this regexp to user.

**Review by romani — CHANGES_REQUESTED** [review]
Items

File: src/test/java/com/puppycrawl/tools/checkstyle/internal/CommitValidationTest.java (hunk 1 above)
Comment (stoyanK7) [reply src/test/java/com/puppycrawl/tools/checkstyle/internal/CommitValidationTest.java:322]: Done.

Comment (romani) [reply src/test/java/com/puppycrawl/tools/checkstyle/internal/CommitValidationTest.java]: There are Junit tests for this validation, please update them, all tests should be persistent if possible.

Comment (stoyanK7) [reply src/test/java/com/puppycrawl/tools/checkstyle/internal/CommitValidationTest.java]: Done. Added two test cases.

**Review by romani — APPROVED** [review]
Ok to merge

**Comment by stoyanK7** [comment]
Moving assertions to a new test because of PMD failure
https://dev.azure.com/romanivanovjr/romanivanovjr/_build/results?buildId=13285&view=logs&j=eb841e9f-6e1e-5c29-3ad5-74ec2c658069&t=a9b761e6-b8d5-50cf-467a-54967189cab2&l=1255
```
[INFO] PMD Failure: com.puppycrawl.tools.checkstyle.internal.CommitValidationTest:106 Rule:JUnitTestContainsTooManyAsserts Priority:3 Unit tests should not contain more than 11 assert(s)..
```

**Review by romani — APPROVED** [review]
