### PR TITLE
Issue #17158: fix invalid javadoc position for compact constructor

### LINKED ISSUE #17158: InvalidJavadocPosition false-positive for record compact constructor with package-private accessibility
I have read check documentation: https://checkstyle.org/checks/javadoc/invalidjavadocposition.html#InvalidJavadocPosition
I have downloaded the latest checkstyle from: https://checkstyle.org/cmdline.html#Download_and_Run
I have executed the cli and showed it below, as cli describes the problem better than 1,000 words

```bash
javac com\company\Testcase.java
```

```
java -jar checkstyle-10.25.0-all.jar -c /sun_checks.xml com\company\Testcase.java
Starting audit...
[ERROR] C:\Users\Gili\Documents\docker\core\src\main\java\com\company\Testcase.java:14:5: Javadoc comment is placed in the wrong location. [InvalidJavadocPosition]
Audit done.
Checkstyle ends with 1 errors.
```

```
java -jar checkstyle-10.25.0-all.jar -c /google_checks.xml com\company\Testcase.java
Starting audit...
[WARN] C:\Users\Gili\Documents\docker\core\src\main\java\com\company\Testcase.java:14:5: Javadoc comment is placed in the wrong location. [InvalidJavadocPosition]
Audit done.
```

```bash
type com\company\Testcase.java
package com.company;

/**
 * Some description.
 */
public class Testcase {
  /**
   * The configuration of a bind mount.
   *
   * @param containerPath a path on the container
   * @param options       mounting options
   */
  record BindMount(String containerPath, String... options) {
    /**
     * Creates a mount.
     *
     * @param containerPath a path on the container
     * @param options       mounting options
     * @throws NullPointerException     if any of the arguments are null
     */
    BindMount {
    }
  }
}
```

---

**Describe what you expect in detail.**
No warnings or errors.

---

PS: If you use a canonical constructor instead of a compact constructor, the error goes away. Similarly, if you use `public` accessibility instead of package-protected, the error goes away.

https://github.com/checkstyle/checkstyle/blob/b22b1b42e8ecc9f87b0a9fcd228157cdf2de1516/src/main/resources/google_checks.xml#L365

### PR DESCRIPTION
**Pull request by mohitsatr**
fixes #17158

### CODE REVIEW

**Comment by mohitsatr** [comment]
@romani I suppose these tests are old and I must write tests as we write them now for branch coverage purposes right?

https://github.com/checkstyle/checkstyle/blob/0b5361ccee07a5bb595d3dab525615815f130ab1/src/test/java/com/puppycrawl/tools/checkstyle/utils/BlockCommentPositionTest.java#L86-L92

https://github.com/checkstyle/checkstyle/blob/0b5361ccee07a5bb595d3dab525615815f130ab1/src/test/java/com/puppycrawl/tools/checkstyle/utils/BlockCommentPositionTest.java#L95-L102

**Comment by romani** [comment]
yes, we need coverage for new code in this PR  thought Inputs and real Check usage.

pure junit testing as you see it, does not contribute much to quality, as they migh be unrealistic and just test code for main code. One day in future we will convert all such pure unit testing to ent-to-end (Input based testing)

**Comment by mohitsatr** [comment]
Github, generate report for InvalidJavadocPosition/all-examples-in-one

File: src/main/java/com/puppycrawl/tools/checkstyle/utils/BlockCommentPosition.java [hunk 1]
```diff
@@ -263,6 +264,17 @@ private static boolean isOnTokenWithModifiers(DetailAST blockComment, int tokenT
...
+    /**
+     * Checks that block comment is on specified token without modifier.
+     *
+     * @param blockComment block comment start DetailAST
+     * @param tokenType parent token type
+     * @return true if block comment is on specified token without any modifier.
+     */
+    private static boolean isOnTokenWithoutModifiers(DetailAST blockComment, int tokenType) {
+        return blockComment.getParent().getType() == tokenType;
+    }
```
Comment (Zopsss) [inline src/main/java/com/puppycrawl/tools/checkstyle/utils/BlockCommentPosition.java]: How is this verifying that there's no modifiers? From my understanding, this method just checks if the block comment's parent is the specified token or not, it doesn't have to do anything with modifiers (?)

File: src/it/resources-noncompilable/com/google/checkstyle/test/chapter7javadoc/rule711generalform/InputJavadocPositionOnCompactConstructors.java
Comment (Zopsss) [inline src/it/resources-noncompilable/com/google/checkstyle/test/chapter7javadoc/rule711generalform/InputJavadocPositionOnCompactConstructors.java:1]: Just to be on the safe side, please also add this input case so we can ensure that no new false positive is introduced:

> PS: If you use a canonical constructor instead of a compact constructor, the error goes away. Similarly, if you use public accessibility instead of package-protected, the error goes away.

**Review by Zopsss — CHANGES_REQUESTED** [review]

File: src/main/java/com/puppycrawl/tools/checkstyle/utils/BlockCommentPosition.java (hunk 1 above)
Comment (mohitsatr) [reply src/main/java/com/puppycrawl/tools/checkstyle/utils/BlockCommentPosition.java]: Difference in AST is very minor. 

**With Modifier:** 
```
        |       |--COMPACT_CTOR_DEF -> COMPACT_CTOR_DEF [43:8]
        |       |   |--MODIFIERS -> MODIFIERS [43:8]
        |       |   |   |--SINGLE_LINE_COMMENT -> // [42:8]
        |       |   |   |   `--COMMENT_CONTENT ->  .... [42:10]
        |       |   |   `--LITERAL_PUBLIC -> public [43:8]
        |       |   |--IDENT -> MyRecord [43:15]
        |       |   `--SLIST -> { [43:24]
        |       |       `--RCURLY -> } [43:25]
        |       |--BLOCK_COMMENT_BEGIN -> /* [44:8]
        |       |   |--COMMENT_CONTENT -> * invalid comment.  [44:10]
        |       |   `--BLOCK_COMMENT_END -> */ [44:28]
        |       `--RCURLY -> } [45:4]
```

**Without Modifier:**
```     
     |       |--COMPACT_CTOR_DEF -> COMPACT_CTOR_DEF [31:8]
        |       |   |--MODIFIERS -> MODIFIERS [31:8]
        |       |   |--BLOCK_COMMENT_BEGIN -> /* [24:8]
        |       |   |   |--COMMENT_CONTENT -> *\n         * Creates a mount.\n         *\n...[24:10]
        |       |   |   `--BLOCK_COMMENT_END -> */ [30:9]
        |       |   |--IDENT -> BindMount [31:8]
        |       |   `--SLIST -> { [31:18]
        |       |       `--RCURLY -> } [32:8]
```


Initially there were more conditionals but because of branch coverage, this is the one we are left with. 
I thought regression would provide us more cases, but report is also clean. so I guess It works.

File: src/it/resources-noncompilable/com/google/checkstyle/test/chapter7javadoc/rule711generalform/InputJavadocPositionOnCompactConstructors.java
Comment (mohitsatr) [reply src/it/resources-noncompilable/com/google/checkstyle/test/chapter7javadoc/rule711generalform/InputJavadocPositionOnCompactConstructors.java:1]: done

File: src/main/java/com/puppycrawl/tools/checkstyle/utils/BlockCommentPosition.java (hunk 1 above)
Comment (Zopsss) [reply src/main/java/com/puppycrawl/tools/checkstyle/utils/BlockCommentPosition.java]: Resolved

File: src/it/java/com/google/checkstyle/test/chapter7javadoc/rule711generalform/GeneralFormTest.java [hunk 2]
```diff
@@ -38,7 +38,12 @@ public void testSingleLineJavadocAndInvalidJavadocPosition() throws Exception {
     @Test
     public void testSingleLineJavadocAndInvalidJavadocPositionFormatted() throws Exception {
         verifyWithWholeConfig(
-                getPath("InputFormattedSingleLineJavadocAndInvalidJavadocPosition.java"));
+            getPath("InputFormattedSingleLineJavadocAndInvalidJavadocPosition.java"));
```
Comment (romani) [inline src/it/java/com/google/checkstyle/test/chapter7javadoc/rule711generalform/GeneralFormTest.java]: revert , it is not required.

File: src/main/java/com/puppycrawl/tools/checkstyle/utils/BlockCommentPosition.java [hunk 3]
```diff
@@ -197,6 +197,7 @@ public static boolean isOnConstructor(DetailAST blockComment) {
      */
     public static boolean isOnCompactConstructor(DetailAST blockComment) {
         return isOnTokenWithModifiers(blockComment, TokenTypes.COMPACT_CTOR_DEF)
+                || isOnTokenWithoutModifiers(blockComment, TokenTypes.COMPACT_CTOR_DEF)
```
Comment (romani) [inline src/main/java/com/puppycrawl/tools/checkstyle/utils/BlockCommentPosition.java]: isOnTokenWithModifiers
isOnTokenWithoutModifiers

why they are opposite to each other?

Comment (mohitsatr) [reply src/main/java/com/puppycrawl/tools/checkstyle/utils/BlockCommentPosition.java]: there is a slight difference in AST when a modifier is omitted on the compact_ctor_def vs when it is not https://github.com/checkstyle/checkstyle/pull/17249#discussion_r2179317129. 

so two methods for checking these two possibilites. do you think It makes more sense to combine two methods into one ?

Comment (romani) [reply src/main/java/com/puppycrawl/tools/checkstyle/utils/BlockCommentPosition.java]: Something needs to rewritten in this method to make it clear.
Lets combine.

**Comment by mohitsatr** [comment]
Github, generate report for InvalidJavadocPosition/all-examples-in-one

File: src/it/java/com/google/checkstyle/test/chapter7javadoc/rule711generalform/GeneralFormTest.java (hunk 2 above)
Comment (mohitsatr) [reply src/it/java/com/google/checkstyle/test/chapter7javadoc/rule711generalform/GeneralFormTest.java]: done

File: src/main/java/com/puppycrawl/tools/checkstyle/utils/BlockCommentPosition.java (hunk 3 above)
Comment (mohitsatr) [reply src/main/java/com/puppycrawl/tools/checkstyle/utils/BlockCommentPosition.java]: done

File: src/main/java/com/puppycrawl/tools/checkstyle/utils/BlockCommentPosition.java [hunk 4]
```diff
@@ -258,7 +258,11 @@ private static boolean isOnPlainToken(DetailAST blockComment,
      * @return true if block comment is on specified token with modifiers
      */
     private static boolean isOnTokenWithModifiers(DetailAST blockComment, int tokenType) {
-        return blockComment.getParent().getType() == TokenTypes.MODIFIERS
+        final boolean compactConstructorWithoutModifier =
+            blockComment.getParent().getType() == TokenTypes.COMPACT_CTOR_DEF;
```
Comment (romani) [inline src/main/java/com/puppycrawl/tools/checkstyle/utils/BlockCommentPosition.java]: My bad.
Now code is even more weird.
We need to come back to your original version.
Can we use isOnPlainToken?

**Review by romani — CHANGES_REQUESTED** [review]
Items

File: src/main/java/com/puppycrawl/tools/checkstyle/utils/BlockCommentPosition.java (hunk 4 above)
Comment (romani) [reply src/main/java/com/puppycrawl/tools/checkstyle/utils/BlockCommentPosition.java]: Please add in Input, cases with annotation over record, and with modifiers.

File: src/main/java/com/puppycrawl/tools/checkstyle/utils/BlockCommentPosition.java (hunk 3 above)
Comment (romani) [reply src/main/java/com/puppycrawl/tools/checkstyle/utils/BlockCommentPosition.java]: Is was my bad. Please revert and we might use some other methods

File: src/main/java/com/puppycrawl/tools/checkstyle/utils/BlockCommentPosition.java (hunk 4 above)
Comment (mohitsatr) [reply src/main/java/com/puppycrawl/tools/checkstyle/utils/BlockCommentPosition.java]: > Can we use isOnPlainToken?

absolutely! this is exactly what we need. Thanks

Comment (mohitsatr) [reply src/main/java/com/puppycrawl/tools/checkstyle/utils/BlockCommentPosition.java]: > Please add in Input, cases with annotation over record, and with modifiers.

done.

**Comment by mohitsatr** [comment]
Github, generate report for InvalidJavadocPosition/all-examples-in-one

File: src/it/resources/com/google/checkstyle/test/chapter7javadoc/rule711generalform/InputJavadocPositionOnCompactConstructors.java [hunk 5]
```diff
@@ -0,0 +1,61 @@
...
+    /**
+     * The constructor for Mapping.
+     *
+     * @param from The source
+     * @param to   The destination
+     */
+    Mapping(String from, String to) {
+      this.from = from;
+      this.to = to;
+    }
```
Comment (Zopsss) [inline src/it/resources/com/google/checkstyle/test/chapter7javadoc/rule711generalform/InputJavadocPositionOnCompactConstructors.java]: please also add a canonical constructor with public modifier

File: src/it/resources/com/google/checkstyle/test/chapter7javadoc/rule711generalform/InputJavadocPositionOnCompactConstructorsWithAnnotation.java [hunk 6]
```diff
@@ -0,0 +1,46 @@
...
+  @SizeType(max = 2)
+  record BindMount(String containerPath) {
+
+    /**
+     * Creates a mount.
+     *
+     * @param containerPath a path on the container
+     */
+    @SizeType(max = 1)
+    BindMount {}
```
Comment (Zopsss) [inline src/it/resources/com/google/checkstyle/test/chapter7javadoc/rule711generalform/InputJavadocPositionOnCompactConstructorsWithAnnotation.java:24]: please also use public keyword with compact constructor. Similarly for canonical constructor with annotation, create two cases - one with public modifier and other without any modifier.

**Review by Zopsss — CHANGES_REQUESTED** [review]
please add below suggested cases to the Check's input files too.

File: src/it/resources/com/google/checkstyle/test/chapter7javadoc/rule711generalform/InputFormattedJavadocPositionOnCompactConstructors.java
Comment (Zopsss) [inline src/it/resources/com/google/checkstyle/test/chapter7javadoc/rule711generalform/InputFormattedJavadocPositionOnCompactConstructors.java:1]: can you also create a top-level record class? it is not necessary but it is always good to have all the cases covered

**Comment by Zopsss** [comment]
@mohitsatr let's resume working on this PR. It is almost ready to merge, only few changes are required :)

File: src/it/resources/com/google/checkstyle/test/chapter7javadoc/rule711generalform/InputFormattedJavadocPositionOnCompactConstructors.java
Comment (mohitsatr) [reply src/it/resources/com/google/checkstyle/test/chapter7javadoc/rule711generalform/InputFormattedJavadocPositionOnCompactConstructors.java:1]: done

File: src/it/resources/com/google/checkstyle/test/chapter7javadoc/rule711generalform/InputJavadocPositionOnCompactConstructorsWithAnnotation.java (hunk 6 above)
Comment (mohitsatr) [reply src/it/resources/com/google/checkstyle/test/chapter7javadoc/rule711generalform/InputJavadocPositionOnCompactConstructorsWithAnnotation.java:24]: done

File: src/it/resources/com/google/checkstyle/test/chapter7javadoc/rule711generalform/InputJavadocPositionOnCompactConstructors.java (hunk 5 above)
Comment (mohitsatr) [reply src/it/resources/com/google/checkstyle/test/chapter7javadoc/rule711generalform/InputJavadocPositionOnCompactConstructors.java]: done

File: src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/invalidjavadocposition/InputInvalidJavadocPositionOnCompactConstructors.java [hunk 7]
```diff
@@ -0,0 +1,66 @@
...
+    /**
+     * The configuration.
+     *
+     * @param text the text
+     */
+    public record MyRecord(String text) {
+
+        // violation 2 lines below 'Javadoc comment is placed in the wrong location.'
+        public MyRecord {}
+        /** invalid comment. */
```
Comment (romani) [inline src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/invalidjavadocposition/InputInvalidJavadocPositionOnCompactConstructors.java:42]: please add one more case like:
```
        // violation 2 lines below 'Javadoc comment is placed in the wrong location.'
        public MyRecord {
             /** invalid comment. */
        }
```

Comment (mohitsatr) [reply src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/invalidjavadocposition/InputInvalidJavadocPositionOnCompactConstructors.java:42]: done

**Review by romani — APPROVED** [review]
Ok to merge

File: src/it/resources/com/google/checkstyle/test/chapter7javadoc/rule711generalform/InputJavadocPositionOnCompactConstructorsWithAnnotation.java [hunk 8]
```diff
@@ -0,0 +1,99 @@
...
+    /**
+     * The constructor for Mapping.
+     *
+     * @param to The source
+     */
+    @SizeType(max = 3)
+    public Mapping2(String to) {
+      this.to = to;
+    }
+  }
```
Comment (Zopsss) [inline src/it/resources/com/google/checkstyle/test/chapter7javadoc/rule711generalform/InputJavadocPositionOnCompactConstructorsWithAnnotation.java]: The input file is for compact constructors but we have used canonical constructor here. I would suggest to split examples into 2 files - one for compact constructors and second for canonical constructor.

Sorry for asking this but it will make the inputs more manageable and it will also simplify the process of adding more cases in future for other contributors.

Comment (mohitsatr) [reply src/it/resources/com/google/checkstyle/test/chapter7javadoc/rule711generalform/InputJavadocPositionOnCompactConstructorsWithAnnotation.java]: > Sorry for asking this but it will make the inputs more manageable

no it does make sense.

Comment (mohitsatr) [reply src/it/resources/com/google/checkstyle/test/chapter7javadoc/rule711generalform/InputJavadocPositionOnCompactConstructorsWithAnnotation.java]: done

**Review by Zopsss — APPROVED** [review]
