### PR TITLE
Issue #6879: SuppressionCommentFilter ignores messageFormat

### LINKED ISSUE #6879: SuppressionCommentFilter ignores messageFormat when matching on ID
```
$ cat TestClass.java
package com.puppycrawl.tools.checkstyle.filters.suppressioncommentfilter;

public class InputSuppressionCommentFilter {
    // CSOFF naming
    public int ABC;
    // CSON naming
}

$ cat TestConfig.xml
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
          "-//Puppy Crawl//DTD Check Configuration 1.3//EN"
          "http://www.puppycrawl.com/dtds/configuration_1_3.dtd">

<module name="Checker">
    <property name="charset" value="UTF-8"/>
    <property name="severity" value="warning"/>
    <property name="haltOnException" value="false"/>
    <module name="TreeWalker">
        <module name="MemberName">
            <property name="id" value="naming"/>
        </module>
        <module name="SuppressionCommentFilter">
            <property name="offCommentFormat" value="CSOFF naming"/>
            <property name="onCommentFormat" value="CSON naming"/>
            <property name="checkFormat" value="^naming$"/>
            <property name="messageFormat" value="NonMatchingMessage"/>
        </module>
    </module>
</module>

$ java -jar checkstyle-8.22-all.jar -c TestConfig.xml TestClass.java
Starting audit...
Audit done.
```

---------------

Identified in https://github.com/checkstyle/checkstyle/pull/6876#discussion_r300830774, this is an edge case where if the filter matches on the module ID (`naming`) rather than the source name (`MemberName`), the `messageFormat` is ignored. 

In the example above, the configured `"NonMatchingMessage"` message format does not match the `"Name 'ABC' must match pattern ..."` message, so the violation should not be suppressed.

Expected output:
```
$ java -jar checkstyle-8.22-all.jar -c TestConfig.xml TestClass.java
Starting audit...
[WARN] TestClass.java:5:16: Name 'ABC' must match pattern '^[a-z][a-zA-Z0-9]*$'. [naming]
Audit done.
```

### PR DESCRIPTION
**Pull request by esilkensen**
The goal of this PR is to fix #6879 by updating the `isMatch` method in `SuppressionCommentFilter.Tag` so that it takes into account `messageFormat` when matching on module ID.

Related PR that does the same to `SuppressWithNearbyCommentFilter.Tag`: #6876

### CODE REVIEW

File: src/test/java/com/puppycrawl/tools/checkstyle/filters/SuppressionCommentFilterTest.java [hunk 1]
```diff
@@ -390,6 +390,50 @@ public void testSuppressById() throws Exception {
...
+    @Test
+    public void testSuppressByIdAndMessage() throws Exception {
+        final DefaultConfiguration filterConfig =
+            createModuleConfig(SuppressionCommentFilter.class);
+        filterConfig.addAttribute("offCommentFormat", "CSOFF (\\w+) \\(allow (\\w+)\\)");
+        filterConfig.addAttribute("onCommentFormat", "CSON (\\w+)");
+        filterConfig.addAttribute("checkFormat", "$1");
+        filterConfig.addAttribute("messageFormat", "$2");
+        final String[] suppressedViolationMessages = {
+            "18:17: "
```
Comment (esilkensen) [inline src/test/java/com/puppycrawl/tools/checkstyle/filters/SuppressionCommentFilterTest.java]: this is an example of a violation that is suppressed with the change in this PR
