### PR TITLE
Issue #15214: migrated section 5.1 to whole config testing and updated it on coverage table

### LINKED ISSUE #15214: Migrate google style guide tests to follow whole config testing approach
In #14937, all the google style guide tests were Migrated to `Chapter Wise Testing` approach. 

The goal of this issue is to migrate all the sections to follow whole config testing approach. In this type of approach, the input file will be tested against the whole google configuration and ensure that we follow all the rules of google style guide in our input files.

Example of problem with not-whole config validation - https://github.com/checkstyle/checkstyle/pull/15248#discussion_r1676836582

Following sections needs to be migrated:
- [x] 2.1 File name
- [x] 2.3.1 Whitespace characters
- [x] 2.3.2 Special escape sequences
- [x] 2.3.3 Non-ASCII characters
- [x] 3 Source file structure
- [x] 3.2 Package statement
- [x] 3.3.1 No wildcard imports
- [x] 3.3.2 No line-wrapping
- [x] 3.3.3 Ordering and spacing
- [x] 3.4.1 Exactly one top-level class declaration
- [x] 3.4.2.1 Overloads: never split
- [x] 4.1.1 Use of optional braces
- [x] 4.1.2 Nonempty blocks: K & R style
- [x] 4.1.3 Empty blocks: may be concise
- [x] 4.2 Block indentation: +2 spaces
- [x] 4.3 One statement per line
- [x] 4.4 Column limit: 100
- [x] 4.5.1 Where to break
- [x] 4.5.2 Indent continuation lines at least +4 spaces
- [x] 4.6.1 Vertical Whitespace
- [x] 4.6.2 Horizontal whitespace
- [x] 4.8.2.1 One variable per declaration
- [x] 4.8.2.2 Declared when needed
- [x] 4.8.3.2 No C-style array declarations
- [x] 4.8.4.1 Indentation
- [x] 4.8.4.2 Fall-through: commented
- [x] 4.8.4.3 Presence of the default label
- [x] 4.8.5.3 Methods And Constructors Annotations
- [x] 4.8.5.4 Field Annotations
- [x] 4.8.6.1 Block comment style
- [x] 4.8.7 Modifiers
- [x] 4.8.8 Numeric Literals
- [x] 5.2.1 Package names
- [x] 5.2.2 Class names
- [x] 5.2.3 Method names
- [x] 5.2.5 Non-constant field names
- [x] 5.2.6 Parameter names
- [x] 5.2.7 Local variable names
- [x] 5.2.8 Type variable names
- [x] 5.3 Camel case: defined
- [x] 6.2 Caught exceptions: not ignored
- [x] 6.4 Finalizers: not used
- [x] 7.1.1 General form
- [x] 7.1.2 Paragraphs
- [x] 7.1.3 Block tags
- [x] 7.2 The summary fragment
- [x] 7.3 Where Javadoc is used
- [x] 7.3.1 Exception: self-explanatory methods
- [x] 7.3.2 Exception: overrides
- [x] 7.3.4 Non-required Javadoc

### PR DESCRIPTION
**Pull request by Zopsss**
Fixes #15214 

It is final fix.

migrated section 5.1 to whole config testing additionally, updated it on coverage table: https://checkstyle.org/google_style.html#a5.1

removed the message, added module usage in place of it.

### CODE REVIEW

**Comment by romani** [comment]
Please fix commit message to reference correct issue.

File: src/it/resources/com/google/checkstyle/test/chapter5naming/rule51identifiernames/InputCatchParameterName.java [hunk 1]
```diff
@@ -1,65 +1,99 @@
...
+      //  'Catch parameter name 'eXX' must match pattern'
+      /* foo */
+    }
+    try {
+      /* foo */
+    } catch (Exception x_y_z) { // violation 'Catch parameter name 'x_y_z' must match pattern'
+    }
+    try {
+      /* foo */
+    } catch (Exception Ex) { // violation 'Catch parameter name 'Ex' must match pattern'
```
Comment (romani) [inline src/it/resources/com/google/checkstyle/test/chapter5naming/rule51identifiernames/InputCatchParameterName.java:96]: Please do us a favor and add what is written in style guide `name_, mName, s_name and kName.`
https://google.github.io/styleguide/javaguide.html#s5.1-identifier-names

It might be better to make new input, as existing is too much focused on Exceptions.

File: src/xdocs/google_style.xml [hunk 2]
```diff
@@ -1615,7 +1615,18 @@
                   <a href="styleguides/google-java-style-20220203/javaguide.html#s5.1-identifier-names">
                     5.1 Rules common to all identifiers</a>
                 </td>
-                <td>"5.2 Rules of identifier type" already includes this rule.
+                <td>
+                  <span class="wrapper inline">
+                    <img src="images/ok_green.png" alt="" />
+                  </span>
+                  <a href="checks/naming/catchparametername.html#CatchParameterName">CatchParameterName</a>
```
Comment (romani) [inline src/xdocs/google_style.xml:1622]: Please add comment `all other types of identifiers has special  section below `
It is not obvious why catchpatamernsme is covering this section.

**Review by romani — CHANGES_REQUESTED** [review]
Items

File: src/it/resources/com/google/checkstyle/test/chapter5naming/rule51identifiernames/InputCatchParameterName.java (hunk 1 above)
Comment (Zopsss) [reply src/it/resources/com/google/checkstyle/test/chapter5naming/rule51identifiernames/InputCatchParameterName.java:96]: done 

https://github.com/checkstyle/checkstyle/blob/603d83e65807027e570f63f39d64c087ffe30b41/src/it/resources/com/google/checkstyle/test/chapter5naming/rule51identifiernames/InputCatchParameterName.java#L98-L113

**Comment by Zopsss** [comment]
Check PR and Check no closed issue failing CIs can be ignored

**Comment by romani** [comment]
Both CIs are red on good reason, please fix.

**Comment by romani** [comment]
GitHub, generate website

**Review by romani — APPROVED** [review]
CI must be fix, but code update is good.

**Review by romani — APPROVED** [review]
I hope you see now how `until xxxxx` are useful

**Comment by Zopsss** [comment]
> I hope you see now how `until xxxxx` are useful

indeed very helpful

**Review by rdiachenko — APPROVED** [review]
lgtm

**Comment by romani** [comment]
@Zopsss , please fix CI

**Comment by Zopsss** [comment]
@romani done
