### PR TITLE
Issue #10747: MetadataGeneratorUtil now reports errors back to the users

### LINKED ISSUE #10747: JavadocMetadataScraper fails silently if it can't write the XML files
Identified through https://github.com/sevntu-checkstyle/sevntu.checkstyle/issues/857 ,

At https://github.com/checkstyle/checkstyle/blob/13481f2c410e4944ecf5ab93ec49948a523a0c82/src/main/java/com/puppycrawl/tools/checkstyle/meta/XmlMetaWriter.java#L179 , checkstyle will fail silently if there are no descriptions to write for the file it scrapped.

I was expecting the files to be generated, or give me an error why they couldn't be generated. Since there was no message and no files, this required me to debug through the code to find out why it wasn't generating my files or complaining.

I feel we should print an error message while continuing to process other files.

I also feel `MetadataGeneratorUtil` should report any errors back somehow so the client and calling tests can handle the situation appropriately.

### PR DESCRIPTION
**Pull request by Vyom-Yadav**
Continuing #10805 
Resolves #10747: MetadataGeneratorUtil now reports errors back to the users
Summary-
The previous PR #10805 added the support of logging a violation in `JavadocMetadataScraper` when the module doesn't contain javadoc description. As `JavadocMetadataScraper` is not a part of checkstyle_checks and we need metadata beforehand we execute it with the help of `MetadataGeneraotrUtilTest`. In this PR support was added to show the violations we logged in `JavadocMetadataScraper`.

A separate logger has been created to get rid of `Audit starting...` messages which are printed by the `DefaultLogger`. Inside the test, we capture the output silently and then compare it with the expected violations.

### CODE REVIEW

**Comment by Vyom-Yadav** [comment]
> I am making this class similar to `Main`
@rnveach Are you working on it, if not then can I start?

**Comment by rnveach** [comment]
You can start, I am not working on anything related to this.

File: src/test/java/com/puppycrawl/tools/checkstyle/meta/MetadataGeneratorUtilTest.java [hunk 1]
```diff
@@ -67,8 +73,30 @@ public void testMetadataFilesGenerationAllFiles() throws Exception {
...
+        final String[] expectedErrorMessages = {
+            "31: Description for 'AbstractSuper' is missing. [JavadocMetadataScraper]",
+            "41: Description for 'AbstractJavadoc' is missing. [JavadocMetadataScraper]",
+            "26: Description for 'AbstractAccessControlName' is missing. [JavadocMetadataScraper]",
+            "30: Description for 'AbstractName' is missing. [JavadocMetadataScraper]",
+            "43: Description for 'AbstractHeader' is missing. [JavadocMetadataScraper]",
+            "29: Description for 'AbstractParenPad' is missing. [JavadocMetadataScraper]",
+            "44: Description for 'AbstractClassCoupling' is missing. [JavadocMetadataScraper]",
+        };
+
```
Comment (Vyom-Yadav) [inline src/test/java/com/puppycrawl/tools/checkstyle/meta/MetadataGeneratorUtilTest.java:89]: @rnveach This does not support localization yet, I can fix that but for that, I would have to extend `AbstractModuleTestSupport` but it's util so It won't be a good extend https://github.com/checkstyle/checkstyle/pull/10840#discussion_r735152673

**Comment by Vyom-Yadav** [comment]
The current approach just gets the content of the output stream, performs some splitting on them to get the error messages, and asserts whether expected messages are equal to actual violations or not.

File: pom.xml [hunk 2]
```diff
@@ -899,6 +899,7 @@
                     <exclude>com.puppycrawl.tools.checkstyle.meta.ModuleDetails*</exclude>
                     <exclude>com.puppycrawl.tools.checkstyle.meta.JavadocMetadataScraper*</exclude>
                     <exclude>com.puppycrawl.tools.checkstyle.meta.XmlMeta*</exclude>
+                    <exclude>com.puppycrawl.tools.checkstyle.meta.MetadataGeneratorUtil*</exclude>
```
Comment (Vyom-Yadav) [inline pom.xml:902]: added as `shouldPrintToConsole` is never false in `MetadataGeneratorUtil`, this was to be used by other projects too, so that flag was added, can be removed if necessary.

File: pom.xml [hunk 3]
```diff
@@ -1519,6 +1520,7 @@
                 <exclude>**/Main.class</exclude>
                 <exclude>**/Main$CliOptions.class</exclude>
                 <exclude>**/JavadocPropertiesGenerator.class</exclude>
+                <exclude>**/MetadataGeneratorUtil.class</exclude>
```
Comment (Vyom-Yadav) [inline pom.xml:1523]: `System.out` is needed for adding an listener

File: src/test/java/com/puppycrawl/tools/checkstyle/meta/MetadataGeneratorUtilTest.java [hunk 4]
```diff
@@ -31,24 +31,38 @@
...
+import org.junit.jupiter.api.Assertions;
 import org.junit.jupiter.api.Test;
+import org.junit.jupiter.api.extension.ExtendWith;
 
+import com.puppycrawl.tools.checkstyle.AbstractModuleTestSupport;
 import com.puppycrawl.tools.checkstyle.internal.utils.CheckUtil;
 
-public final class MetadataGeneratorUtilTest {
+@ExtendWith(SystemOutGuard.class)
+public final class MetadataGeneratorUtilTest extends AbstractModuleTestSupport {
```
Comment (Vyom-Yadav) [inline src/test/java/com/puppycrawl/tools/checkstyle/meta/MetadataGeneratorUtilTest.java:44]: It is not a module but still extended for using `getCheckMessage(..)` otherwise, I had to hardcode it in English.

File: src/test/java/com/puppycrawl/tools/checkstyle/meta/MetadataGeneratorUtilTest.java [hunk 5]
```diff
@@ -67,8 +81,30 @@ public void testMetadataFilesGenerationAllFiles() throws Exception {
...
+            "26: " + getCheckMessage(MSG_DESC_MISSING, "AbstractAccessControlName"),
+        };
+
+        final String[] actualViolations = systemOut.getCapturedData().split("\\n");
+        final int javadocMetadataScraperLength = " [JavadocMetadataScraper]".length();
+        Arrays.setAll(actualViolations, id -> {
+            final String currString = actualViolations[id];
+            return currString.substring(currString.indexOf(':') + 1,
+                                        currString.length() - javadocMetadataScraperLength);
+        });
```
Comment (Vyom-Yadav) [inline src/test/java/com/puppycrawl/tools/checkstyle/meta/MetadataGeneratorUtilTest.java:104]: This is a simpler approach, could be replaced with a regex-based approach if need raised, regex that can be used `(?<=.):.*(?=\\s\\[)`  and then extract the required group.

**Comment by Vyom-Yadav** [comment]
@rnveach The order of output is changing, not sure why, either printing is happening in different threads or the output streams are different, I checked but couldn't find the possible cause, can you take a look once?

File: .ci/pitest.sh [hunk 6]
```diff
@@ -90,6 +90,8 @@ pitest-common)
   "DefaultLogger.java.html:<td class='covered'><pre><span  class='survived'>        if (closeError) {</span></pre></td></tr>"
   "DefaultLogger.java.html:<td class='covered'><pre><span  class='survived'>        if (closeInfo) {</span></pre></td></tr>"
   "DefaultLogger.java.html:<td class='covered'><pre><span  class='survived'>        if (severityLevel != SeverityLevel.IGNORE) {</span></pre></td></tr>"
+  "DefaultLogger.java.html:<td class='uncovered'><pre><span  class='survived'>        return errorWriter;</span></pre></td></tr>"
+  "DefaultLogger.java.html:<td class='uncovered'><pre><span  class='survived'>        return infoWriter;</span></pre></td></tr>"
```
Comment (Vyom-Yadav) [inline .ci/pitest.sh:94]: Needed for flushing streams while overriding some methods. Getter-setter for `infoWriter` and `errorWriter` have been added to flush the streams in the anonymous inner class. The anonymous inner class is needed to get rid of `audit started` and `audit done` messages.

**Comment by romani** [comment]
I do not understand why we need extend main logic to satisfy some requirements of test tool. 
I do not expect any changes in loggers that we use in main logic.
Please use logger that will be specific for this until.

**Comment by Vyom-Yadav** [comment]
> I do not understand why we need extend main logic to satisfy some requirements of test tool. I do not expect any changes in loggers that we use in main logic.

@romani I had to extend Default Logger to get rid of `Starting audit...` and `audit done..` messages.  
>  Please use logger that will be specific for this until.

So I should make a new logger called metadata logger?

**Comment by romani** [comment]
>  logger called metadata logger?

yes. It will not be our API, it will be very internal and we can do with it anything we want to serve what we need.

**Comment by romani** [comment]
@Vyom-Yadav , please finish this PR

**Comment by Vyom-Yadav** [comment]
I will try to complete this in the current week.

**Comment by Vyom-Yadav** [comment]
Can somebody share wercker failure

**Comment by Vyom-Yadav** [comment]
@rnveach @romani You may review.

**Comment by romani** [comment]
wercker failure is in Sonar - https://sonarcloud.io/dashboard?id=org.checkstyle%3Acheckstyle&pullRequest=10904
please address.

**Comment by Vyom-Yadav** [comment]
@romani It complains about using `System.out`, it needs to be suppressed, https://github.com/checkstyle/checkstyle/pull/10904#discussion_r768541599, I need it to show errors to the users.

File: src/main/java/com/puppycrawl/tools/checkstyle/meta/MetadataGeneratorUtil.java [hunk 7]
```diff
@@ -58,13 +61,18 @@ public static void generate(String path, String... moduleFolders)
...
+        final DefaultConfiguration defaultConfiguration =
+                new DefaultConfiguration("configuration");
         final DefaultConfiguration treeWalkerConfig =
                 new DefaultConfiguration(TreeWalker.class.getName());
         defaultConfiguration.addProperty("charset", StandardCharsets.UTF_8.name());
         defaultConfiguration.addChild(treeWalkerConfig);
         treeWalkerConfig.addChild(scraperCheckConfig);
         checker.configure(defaultConfiguration);
+
+        checker.addListener(new MetadataGeneratorLogger(System.out,
```
Comment (pbludov) [inline src/main/java/com/puppycrawl/tools/checkstyle/meta/MetadataGeneratorUtil.java:73]: Please replace `System.out` with a parameter.

Comment (Vyom-Yadav) [reply src/main/java/com/puppycrawl/tools/checkstyle/meta/MetadataGeneratorUtil.java:73]: Extract `System.out` to a variable and pass it as an argument or add a parameter to the `generate(..)` method and pass it as an argument in a test case?

Comment (pbludov) [reply src/main/java/com/puppycrawl/tools/checkstyle/meta/MetadataGeneratorUtil.java:73]: Pleas add a parameter to the generate(..) method

**Comment by Vyom-Yadav** [comment]
@pbludov If changes are alright can you assign the next reviewer?

**Review by pbludov — APPROVED** [review]

**Comment by nmancus1** [comment]
@Vyom-Yadav there is a lot of discussion spread throughout this PR, previous PR, and related issue. Please add comment to issue to state what part of the issue this PR solves, and summary of discussion around implementation with all necessary context.

**Comment by Vyom-Yadav** [comment]
@nmancus1 I shared a summary of all that had happened in the previous PR and what this PR covers, ping me if anything else is required.

File: src/main/java/com/puppycrawl/tools/checkstyle/meta/MetadataGeneratorUtil.java [hunk 8]
```diff
@@ -46,25 +49,31 @@ private MetadataGeneratorUtil() {
...
         JavadocMetadataScraper.resetModuleDetailsStore();
 
         final Checker checker = new Checker();
         checker.setModuleClassLoader(Checker.class.getClassLoader());
         final DefaultConfiguration scraperCheckConfig =
                         new DefaultConfiguration(JavadocMetadataScraper.class.getName());
-        final DefaultConfiguration defaultConfiguration = new DefaultConfiguration("configuration");
+        final DefaultConfiguration defaultConfiguration =
+                new DefaultConfiguration("configuration");
         final DefaultConfiguration treeWalkerConfig =
```
[the remark this answers is not in the document]
Comment (Vyom-Yadav) [reply src/main/java/com/puppycrawl/tools/checkstyle/meta/MetadataGeneratorUtil.java:67]: Done

File: src/test/java/com/puppycrawl/tools/checkstyle/MetadataGeneratorLoggerTest.java [hunk 9]
```diff
@@ -0,0 +1,112 @@
...
+import com.puppycrawl.tools.checkstyle.api.AuditEvent;
+import com.puppycrawl.tools.checkstyle.api.AutomaticBean;
+import com.puppycrawl.tools.checkstyle.api.SeverityLevel;
+import com.puppycrawl.tools.checkstyle.api.Violation;
+import com.puppycrawl.tools.checkstyle.internal.utils.CloseAndFlushTestByteArrayOutputStream;
+
+public class MetadataGeneratorLoggerTest {
+
+    @Test
+    public void testIgnoreSeverityLevel() {
```
[the remark this answers is not in the document]
Comment (Vyom-Yadav) [reply src/test/java/com/puppycrawl/tools/checkstyle/MetadataGeneratorLoggerTest.java:39]: >  Is it side effect of pitest?

Yes, to kill all the mutations and for code coverage.

File: src/test/java/com/puppycrawl/tools/checkstyle/meta/MetadataGeneratorUtilTest.java [hunk 10]
```diff
@@ -67,8 +92,33 @@ public void testMetadataFilesGenerationAllFiles() throws Exception {
                 .sorted()
                 .collect(Collectors.toCollection(LinkedHashSet::new));
         checkstyleModules.removeAll(modulesContainingNoMetadataFile);
-        assertWithMessage("Number of generated metadata files dont match with number of checkstyle "
-                + "module").that(metaFiles).isEqualTo(checkstyleModules);
+        assertWithMessage("Number of generated metadata files dont match with "
+                + "number of checkstyle module").that(metaFiles).isEqualTo(checkstyleModules);
```
[the remark this answers is not in the document]
Comment (Vyom-Yadav) [reply src/test/java/com/puppycrawl/tools/checkstyle/meta/MetadataGeneratorUtilTest.java]: Line length was exceeding, Done.

**Comment by Vyom-Yadav** [comment]
> Can you put example of how it works now in case of problem is detected in comparison to what was before.

**what was before:**
Before no error message was shown, they were logged in `JavadocMetadataScrapper` but not shown to the end-user as no logger was used to show the messages (listener wasn't added to checker config).

Now-
```
Expected and actual errors do not match
value of   : array.asList()
missing (1): 31: Description for 'AbstractSuperCheck' is missing.
---
expected   : [26: Description for 'AbstractAccessControlNameCheck' is missing., 29: Description for 'AbstractParenPadCheck' is missing., 30: Description for 'AbstractNameCheck' is missing., 31: Description for 'AbstractSuperCheck' is missing., 42: Description for 'AbstractJavadocCheck' is missing., 45: Description for 'AbstractClassCouplingCheck' is missing., 45: Description for 'AbstractHeaderCheck' is missing.]
but was    : [26: Description for 'AbstractAccessControlNameCheck' is missing., 29: Description for 'AbstractParenPadCheck' is missing., 30: Description for 'AbstractNameCheck' is missing., 42: Description for 'AbstractJavadocCheck' is missing., 45: Description for 'AbstractClassCouplingCheck' is missing., 45: Description for 'AbstractHeaderCheck' is missing.]
```

**Review by romani — APPROVED** [review]
ok to merge

File: src/test/java/com/puppycrawl/tools/checkstyle/MetadataGeneratorLoggerTest.java [hunk 11]
```diff
@@ -0,0 +1,112 @@
...
+        final OutputStream outputStream = new ByteArrayOutputStream();
+        final MetadataGeneratorLogger logger = new MetadataGeneratorLogger(outputStream,
+                AutomaticBean.OutputStreamOptions.CLOSE);
+        final AuditEvent event = new AuditEvent(this, "fileName",
+                new Violation(1, 2, "bundle", "key",
+                        null, SeverityLevel.IGNORE, null, getClass(), "customViolation"));
+        logger.finishLocalSetup();
+        logger.addError(event);
+        logger.auditFinished(event);
+        assertWithMessage("Expected Output")
```
Comment (nmancus1) [inline src/test/java/com/puppycrawl/tools/checkstyle/MetadataGeneratorLoggerTest.java:49]: `Expected no output`?

File: src/test/java/com/puppycrawl/tools/checkstyle/meta/MetadataGeneratorUtilTest.java [hunk 12]
```diff
@@ -28,29 +29,77 @@
...
+            "45: " + getCheckMessage(MSG_DESC_MISSING, "AbstractHeaderCheck"),
+            "42: " + getCheckMessage(MSG_DESC_MISSING, "AbstractJavadocCheck"),
+            "45: " + getCheckMessage(MSG_DESC_MISSING, "AbstractClassCouplingCheck"),
+            "26: " + getCheckMessage(MSG_DESC_MISSING, "AbstractAccessControlNameCheck"),
+            "30: " + getCheckMessage(MSG_DESC_MISSING, "AbstractNameCheck"),
+            "29: " + getCheckMessage(MSG_DESC_MISSING, "AbstractParenPadCheck"),
+        };
+
+        final String[] actualViolations = systemOut.getCapturedData().split("\\n");
+        final Pattern pattern = Pattern.compile("((?<=:)\\d.*:.*(?=\\s\\[))");
```
Comment (nmancus1) [inline src/test/java/com/puppycrawl/tools/checkstyle/meta/MetadataGeneratorUtilTest.java:89]: Can you come up with some more descriptive name for this pattern, or add a comment here?

**Review by nmancus1 — CHANGES_REQUESTED** [review]
Few thoughts:

File: src/main/java/com/puppycrawl/tools/checkstyle/MetadataGeneratorLogger.java [hunk 13]
```diff
@@ -0,0 +1,111 @@
...
+import com.puppycrawl.tools.checkstyle.api.SeverityLevel;
+
+/**
+ * Simple logger for metadata generator util.
+ */
+public class MetadataGeneratorLogger extends AutomaticBean implements AuditListener {
+
+    /**
+     * Where to write error messages.
+     **/
```
[the remark this answers is not in the document]
Comment (Vyom-Yadav) [reply src/main/java/com/puppycrawl/tools/checkstyle/MetadataGeneratorLogger.java]: Done

File: src/test/java/com/puppycrawl/tools/checkstyle/MetadataGeneratorLoggerTest.java (hunk 11 above)
Comment (Vyom-Yadav) [reply src/test/java/com/puppycrawl/tools/checkstyle/MetadataGeneratorLoggerTest.java]: Improved the message, should be fine now.

File: src/test/java/com/puppycrawl/tools/checkstyle/meta/MetadataGeneratorUtilTest.java (hunk 12 above)
Comment (Vyom-Yadav) [reply src/test/java/com/puppycrawl/tools/checkstyle/meta/MetadataGeneratorUtilTest.java]: changed to `violationExtractingPattern` fine?

Comment (nick-mancuso) [reply src/test/java/com/puppycrawl/tools/checkstyle/meta/MetadataGeneratorUtilTest.java]: Resolved.

File: src/test/java/com/puppycrawl/tools/checkstyle/MetadataGeneratorLoggerTest.java (hunk 11 above)
Comment (nick-mancuso) [reply src/test/java/com/puppycrawl/tools/checkstyle/MetadataGeneratorLoggerTest.java]: Resolved.

File: src/main/java/com/puppycrawl/tools/checkstyle/MetadataGeneratorLogger.java (hunk 13 above)
[the remark this answers is not in the document]
Comment (nick-mancuso) [reply src/main/java/com/puppycrawl/tools/checkstyle/MetadataGeneratorLogger.java]: Resolved.

**Review by nick-mancuso — APPROVED** [review]

**Review by rnveach — APPROVED** [review]
