### PR TITLE
Issue #8934: FinalLocalVariable throws a NPE on Switch expression in assignment 

### LINKED ISSUE #8934: FinalLocalVariable throws a NPE on Switch expression in assignment
Check documentation: https://checkstyle.sourceforge.io/config_coding.html#FinalLocalVariable

Discovered at https://github.com/checkstyle/checkstyle/pull/8920#pullrequestreview-518815743

FinalLocalVariable is throwing a NPE when a switch expression is used on the RHS of an assignment expression:

```
➜  src /usr/lib/jvm/java-14-openjdk/bin/javac --enable-preview --source 14 ExpressionSwitchBugs.java
➜  src cat config.xml                                                                               
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
        "-//Checkstyle//DTD Checkstyle Configuration 1.3//EN"
        "https://checkstyle.org/dtds/configuration_1_3.dtd">
<module name="Checker">
    <module name="TreeWalker">
        <module name="FinalLocalVariable"/>
    </module>
</module>
➜  src cat ExpressionSwitchBugs.java 
public class ExpressionSwitchBugs {
    private static final int staticValue = 2;
    private static final int staticField = switch(staticValue) {
        case 0 -> -1;
        case 2 -> 2;
        default -> 3;
    };
}
➜  src java -jar /home/nick/IdeaProjects/checkstyle/target/checkstyle-8.37-SNAPSHOT-all.jar -c config.xml ExpressionSwitchBugs.java
Starting audit...
com.puppycrawl.tools.checkstyle.api.CheckstyleException: Exception was thrown while processing ExpressionSwitchBugs.java
        at com.puppycrawl.tools.checkstyle.Checker.processFiles(Checker.java:311)
        at com.puppycrawl.tools.checkstyle.Checker.process(Checker.java:221)
        at com.puppycrawl.tools.checkstyle.Main.runCheckstyle(Main.java:408)
        at com.puppycrawl.tools.checkstyle.Main.runCli(Main.java:331)
        at com.puppycrawl.tools.checkstyle.Main.execute(Main.java:190)
        at com.puppycrawl.tools.checkstyle.Main.main(Main.java:125)
Caused by: java.lang.NullPointerException
        at com.puppycrawl.tools.checkstyle.checks.coding.FinalLocalVariableCheck.updateUninitializedVariables(FinalLocalVariableCheck.java:482)
        at com.puppycrawl.tools.checkstyle.checks.coding.FinalLocalVariableCheck.updateAllUninitializedVariables(FinalLocalVariableCheck.java:471)
        at com.puppycrawl.tools.checkstyle.checks.coding.FinalLocalVariableCheck.leaveToken(FinalLocalVariableCheck.java:345)
        at com.puppycrawl.tools.checkstyle.TreeWalker.notifyLeave(TreeWalker.java:357)
        at com.puppycrawl.tools.checkstyle.TreeWalker.processIter(TreeWalker.java:454)
        at com.puppycrawl.tools.checkstyle.TreeWalker.walk(TreeWalker.java:278)
        at com.puppycrawl.tools.checkstyle.TreeWalker.processFiltered(TreeWalker.java:151)
        at com.puppycrawl.tools.checkstyle.api.AbstractFileSetCheck.process(AbstractFileSetCheck.java:87)
        at com.puppycrawl.tools.checkstyle.Checker.processFile(Checker.java:337)
        at com.puppycrawl.tools.checkstyle.Checker.processFiles(Checker.java:298)
        ... 5 more
Checkstyle ends with 1 errors.

```
I would expect FinalLocalVariable to be able to successfully check this file.

### PR DESCRIPTION
**Pull request by anhminhtran235**
Fix #8934 

Turns out, assigning to `switch` is not the problem. In fact, wrapping `switch` inside a function `foo()` makes the problem disappear.
```
$ cat ExpressionSwitchBugs.java
public class ExpressionSwitchBugs {
    private static final int staticValue = 2;
    private void foo() {
        final int someVariable = switch (staticValue) {
            case 0 -> -1;
            case 2 -> 2;
            default -> 3;
        };
    }
}

java -jar .\checkstyle-8.37-all.jar -c config.xml ExpressionSwitchBugs.java
Starting audit...
Audit done.
```

Here's what went wrong in #8934:

The NPE occurs at line 482, when checkstyle is reading `case 0 -> -1;`
https://github.com/checkstyle/checkstyle/blob/3fc9dd98ad6ed963e2cfcd2e630f7031ec5b0c1e/src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/FinalLocalVariableCheck.java#L481-L482

Basically, when executing `line 482`, `currentScopeAssignedVariables` is an empty Deque => `.peek()` returns `null` => accessing `.iterator()` return NPE

`currentScopeAssignedVariables` is empty because **there are no scope yet**. The only place a new scope is added to `currentScopeAssignedVariables` is:
https://github.com/checkstyle/checkstyle/blob/3fc9dd98ad6ed963e2cfcd2e630f7031ec5b0c1e/src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/FinalLocalVariableCheck.java#L273-L274
 
But, 
```
public class ExpressionSwitchBugs {
...
}
```
is an `OBJBLOCK`, not a `SLIST` => `line 274` was never executed => there was no scope at the time `line 482` was executing. That explains why wrapping the `switch` inside a function `foo()` makes it work (Because foo() is a scope)

=> I fixed this bug by checking `if (!currentScopeAssignedVariables.isEmpty())` before executing `final Iterator<DetailAST> iterator = currentScopeAssignedVariables.peek().iterator();`

Test input was added inside the existing test file: `InputFinalLocalVariableCheckSwitchExpressions.java`

Diff Regression config: https://gist.githubusercontent.com/anhminhtran235/c74908614e3465fade5de3c1d33fad5e/raw/ec75fe33dd75befe6b23185b9521c93cebb1c18b/check.xml
Diff Regression projects: https://gist.githubusercontent.com/anhminhtran235/2da94f96d35ab9471624c5b6c4421c66/raw/82b014453ca421085199b4635f6a13c26a62941d/projects-to-test-on.properties

### CODE REVIEW

**Comment by anhminhtran235** [comment]
GitHub, generate report

**Comment by anhminhtran235** [comment]
@romani Do I need to add more projects to `projects-to-test-on.properties`?

**Comment by romani** [comment]
It is better to activate almost all, as non of them has new syntax yet, and we expect no difference in old syntax. Report most likely be empty, so it is fine to activate all.

**Comment by romani** [comment]
Wercker failed at sonar , here is violation https://sonarcloud.io/dashboard?id=org.checkstyle%3Acheckstyle&pullRequest=8959

**Comment by anhminhtran235** [comment]
> Wercker failed at sonar , here is violation https://sonarcloud.io/dashboard?id=org.checkstyle%3Acheckstyle&pullRequest=8959

Reduced indentation level to reduce "Cognitive Complexity".

**Comment by anhminhtran235** [comment]
GitHub, generate report

**Comment by anhminhtran235** [comment]
@romani Adding most projects slows down the generating-report process significantly as last time. Is there any particular project I should never add because it's too slow?

**Comment by nmancus1** [comment]
@romani  I also had trouble using jdk11 in regression:
```
➜  jdk11u git:(master) find . -name "NestedLambdaNoGenerics.java"
./test/langtools/tools/javac/lambda/speculative/NestedLambdaNoGenerics.java

```
Many of the files that caused issues in https://github.com/checkstyle/checkstyle/pull/8920 are also in the jdk11u repo.  I skipped this project in all regression tests for checks last summer.

**Comment by nmancus1** [comment]
@anhminhtran235  Please comment out the openjdk11 project and try again.  Failure from "generate report":

```
     [copy] Copying 67300 files to /home/runner/work/checkstyle/checkstyle/contribution/checkstyle-tester/src/main/java/openjdk11
Running 'mvn clean' on src/main/java ...
Running command: mvn --batch-mode clean
[INFO] Scanning for projects...
[INFO] 
[INFO] ----------------< com.github.sevntu.checkstyle:sample >-----------------
[INFO] Building sample 0.0.1-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ sample ---
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  0.188 s
[INFO] Finished at: 2020-11-04T18:37:15Z
[INFO] ------------------------------------------------------------------------
Running Checkstyle on src/main/java ... with excludes {}
Running command: mvn -e --batch-mode site -Dcheckstyle.config.location=diff_config.xml -Dcheckstyle.excludes= -Dcheckstyle.version=8.38-SNAPSHOT -Dcheckstyle.failsOnError=false
[INFO] Error stacktraces are turned on.
[INFO] Scanning for projects...
[INFO] 
[INFO] ----------------< com.github.sevntu.checkstyle:sample >-----------------
[INFO] Building sample 0.0.1-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- maven-site-plugin:3.3:site (default-site) @ sample ---
[INFO] configuring report plugin org.apache.maven.plugins:maven-site-plugin:3.3
[INFO] configuring report plugin org.apache.maven.plugins:maven-project-info-reports-plugin:2.7
[INFO] configuring report plugin org.apache.maven.plugins:maven-checkstyle-plugin:3.1.1
[INFO] configuring report plugin org.apache.maven.plugins:maven-jxr-plugin:2.5
Warning:  No project URL defined - decoration links will not be relativized!
[INFO] Rendering site with org.apache.maven.skins:maven-default-skin:jar:1.0 skin.
[INFO] Skipped "Source Xref" report, file "xref/index.html" already exists for the English version.
[INFO] Generating "About" report    --- maven-project-info-reports-plugin:2.7
[INFO] Generating "Plugin Management" report    --- maven-project-info-reports-plugin:2.7
[INFO] Generating "Distribution Management" report    --- maven-project-info-reports-plugin:2.7
[INFO] Generating "Dependency Information" report    --- maven-project-info-reports-plugin:2.7
[INFO] Generating "Source Repository" report    --- maven-project-info-reports-plugin:2.7
[INFO] Generating "Mailing Lists" report    --- maven-project-info-reports-plugin:2.7
[INFO] Generating "Issue Tracking" report    --- maven-project-info-reports-plugin:2.7
[INFO] Generating "Continuous Integration" report    --- maven-project-info-reports-plugin:2.7
[INFO] Generating "Project Plugins" report    --- maven-project-info-reports-plugin:2.7
[INFO] Generating "Project License" report    --- maven-project-info-reports-plugin:2.7
[INFO] Generating "Project Team" report    --- maven-project-info-reports-plugin:2.7
[INFO] Generating "Project Summary" report    --- maven-project-info-reports-plugin:2.7
[INFO] Generating "Dependencies" report    --- maven-project-info-reports-plugin:2.7
[INFO] Generating "Checkstyle" report    --- maven-checkstyle-plugin:3.1.1
Error: The operation was canceled.
```

**Comment by anhminhtran235** [comment]
@nmancus1 Thanks. openjdk11 commented out.

**Comment by anhminhtran235** [comment]
GitHub, generate report

**Comment by anhminhtran235** [comment]
Travis is not running. Do you guys know why?

**Comment by anhminhtran235** [comment]
@romani All checks have passed. Please review. 
Also, there seems to be a problem with openjdk11 project in regression as @nmancus1 has mentioned.

**Comment by romani** [comment]
GitHub, rebase

**Comment by romani** [comment]
@anhminhtran235 , please do https://github.com/checkstyle/checkstyle/issues/8934#issuecomment-718187821

I rebased your code to let your changes be above better openjdk validation

**Comment by anhminhtran235** [comment]
@romani I need some help with Git. My fork was 4 commits behind Checkstyle, so I do this to keep my fork up to date:
```
git fetch upstream
git rebase upstream/master
git push origin master --force
```
Now my master branch is even with Checkstyle, but this branch (`fix-switch-NPE`) is not. What should I do?
Should I do
```
git checkout fix-switch-NPE
git merge master
```
What should I do after `git merge master`? I messed up this once, so I want to make sure how to do it right.

**Comment by anhminhtran235** [comment]
Oh, actually I do `git checkout fix-switch-NPE` and then `git pull`, and everything is working. Is that because you rebased the code?

**Comment by romani** [comment]
https://checkstyle.org/beginning_development.html#Starting_Development

**Comment by anhminhtran235** [comment]
> https://checkstyle.org/beginning_development.html#Starting_Development

@romani  Thanks! That is super helpful. I forgot there is a git guide on checkstyle.org

> @anhminhtran235 , please do #8934 (comment)

Removed `ExpressionSwitchBugs.java` from `openjdk14-excluded.files`

File: src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/FinalLocalVariableCheckTest.java [hunk 1]
```diff
@@ -297,10 +297,10 @@ public void testReceiverParameter() throws Exception {
...
         final String[] expected = {
-            "12:19: " + getCheckMessage(MSG_KEY, "e"),
-            "50:19: " + getCheckMessage(MSG_KEY, "e"),
-            "88:19: " + getCheckMessage(MSG_KEY, "e"),
-            "122:19: " + getCheckMessage(MSG_KEY, "e"),
+            "19:19: " + getCheckMessage(MSG_KEY, "e"),
+            "57:19: " + getCheckMessage(MSG_KEY, "e"),
+            "95:19: " + getCheckMessage(MSG_KEY, "e"),
+            "129:19: " + getCheckMessage(MSG_KEY, "e"),
             };
```
Comment (romani) [inline src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/FinalLocalVariableCheckTest.java:304]: Please move new code block to the end of file so you will not have this change

File: src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/finallocalvariable/InputFinalLocalVariableCheckSwitchExpressions.java [hunk 2]
```diff
@@ -7,6 +7,13 @@
  * tokens = {VARIABLE_DEF}
  */
 public class InputFinalLocalVariableCheckSwitchExpressions {
+    private static final int staticValue = 2;
```
Comment (romani) [inline src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/finallocalvariable/InputFinalLocalVariableCheckSwitchExpressions.java:10]: Please extend Input for default config

**Review by romani — CHANGES_REQUESTED** [review]
Items:

File: src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/FinalLocalVariableCheckTest.java (hunk 1 above)
Comment (anhminhtran235) [reply src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/FinalLocalVariableCheckTest.java]: fixed

File: src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/finallocalvariable/InputFinalLocalVariableCheckSwitchExpressions.java (hunk 2 above)
Comment (anhminhtran235) [reply src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/finallocalvariable/InputFinalLocalVariableCheckSwitchExpressions.java]: Sorry, I don't understand what you mean. Could you please explain?

Comment (romani) [reply src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/finallocalvariable/InputFinalLocalVariableCheckSwitchExpressions.java]: if you pay attention to comment above class you will see that there is definition of Check config.

your bug is for default config of Check, without any modification in properties.
please create https://github.com/checkstyle/checkstyle/tree/master/src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/finallocalvariable
new file InputFinalLocalVariableCheckDefaultSwitchExpressions.java and use it for default config configuration., so new UT method should be created to use new file.

Comment (nmancus1) [reply src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/finallocalvariable/InputFinalLocalVariableCheckSwitchExpressions.java]: @romani this is the default config; during summer I thought that it might be a good idea to list the config regardless of whether it is default or not, which is why this file doesn't say `default`.  At some point in the future, the default could change, and then we would have to either update configs at the top of the input files or ... 

 I do agree that a new input and UT should be created.

File: src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/finallocalvariable/InputFinalLocalVariableCheckSwitchExpressions.java [hunk 3]
```diff
@@ -132,5 +132,12 @@ void foo4() throws Exception {
         }
 
     }
+
+    private static final int staticValue = 2;
+    private static final int staticField = switch(staticValue) {
+        case 0 -> -1;
+        case 2-> 2;
+        default -> 3;
+    };
```
Comment (nmancus1) [inline src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/finallocalvariable/InputFinalLocalVariableCheckSwitchExpressions.java:141]: As @romani stated in his items, please create a new UT and input file.  It would be good to show:

 -  violations: definitions where variable is not declared `final` but is never reassigned
 -  acceptable variable definitions (those that are declared `final` and never reassigned)
 - acceptable variable definitions (where the variable is not declared final AND is reassigned).

...  where a switch expression is on RHS of the assignment.   Try to put the code within methods, class blocks, constructors, etc. to make sure that we can successfully check all.

**Review by nmancus1 — CHANGES_REQUESTED** [review]
@anhminhtran235 thanks for finding the cause of this bug.
Item:

File: src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/finallocalvariable/InputFinalLocalVariableCheckSwitchExpressions.java (hunk 2 above)
Comment (nmancus1) [reply src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/finallocalvariable/InputFinalLocalVariableCheckSwitchExpressions.java]: > new file InputFinalLocalVariableCheckDefaultSwitchExpressions.java

Since the existing input has no switch *expressions* on RHS of variable definition, we could just call it  `InputFinalLocalVariableCheckSwitchAssignment.java` or something.

Comment (romani) [reply src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/finallocalvariable/InputFinalLocalVariableCheckSwitchExpressions.java]: default config should be `/* Config: default` 

definition of default is useful during review agree, I really hope one day we will convert UTs to be aligned with BDD concepts. It is project for future GSoCs.

Comment (anhminhtran235) [reply src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/finallocalvariable/InputFinalLocalVariableCheckSwitchExpressions.java]: fixed. I have added a separate UT, as well as `InputFinalLocalVariableCheckSwitchAssignment.java`. Thank you for your guidance.

File: src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/finallocalvariable/InputFinalLocalVariableCheckSwitchExpressions.java (hunk 3 above)
Comment (anhminhtran235) [reply src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/finallocalvariable/InputFinalLocalVariableCheckSwitchExpressions.java]: You're welcome @nmancus1. I have created a new UT and a new input file with violations and acceptable cases. I've also put a switch expression on RHS of the assignment,... like you suggested

File: src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/finallocalvariable/InputFinalLocalVariableCheckSwitchAssignment.java [hunk 4]
```diff
@@ -0,0 +1,59 @@
...
+                    }
+                    default -> 2;
+                };
+        };
+    }
+
+    public void foo() {
+        final int a = 0;
+
+        int b = switch(a) { // violation
```
Comment (romani) [inline src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/finallocalvariable/InputFinalLocalVariableCheckSwitchAssignment.java:39]: Please add test case for violation inside `case`

**Review by romani — CHANGES_REQUESTED** [review]
Item:

File: src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/finallocalvariable/InputFinalLocalVariableCheckSwitchAssignment.java (hunk 4 above)
Comment (anhminhtran235) [reply src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/finallocalvariable/InputFinalLocalVariableCheckSwitchAssignment.java:39]: fixed

**Review by romani — APPROVED** [review]

File: src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/FinalLocalVariableCheckTest.java [hunk 5]
```diff
@@ -307,4 +307,17 @@ public void testFinalLocalVariableSwitchExpressions() throws Exception {
...
     }
 
+    @Test
+    public void testFinalLocalVariableSwitchAssignment() throws Exception {
+        final DefaultConfiguration checkConfig = createModuleConfig(FinalLocalVariableCheck.class);
+        final String[] expected = {
+            "16:13: " + getCheckMessage(MSG_KEY, "a"),
+            "39:13: " + getCheckMessage(MSG_KEY, "b"),
+            "41:21: " + getCheckMessage(MSG_KEY, "x"),
+            };
```
Comment (nmancus1) [inline src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/FinalLocalVariableCheckTest.java:317]: Indentation: should be 8.

**Review by nmancus1 — CHANGES_REQUESTED** [review]
One minor item:

File: src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/FinalLocalVariableCheckTest.java (hunk 5 above)
Comment (anhminhtran235) [reply src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/FinalLocalVariableCheckTest.java]: fixed indentation

File: src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/FinalLocalVariableCheckTest.java [hunk 6]
```diff
@@ -301,10 +301,23 @@ public void testFinalLocalVariableSwitchExpressions() throws Exception {
             "50:19: " + getCheckMessage(MSG_KEY, "e"),
             "88:19: " + getCheckMessage(MSG_KEY, "e"),
             "122:19: " + getCheckMessage(MSG_KEY, "e"),
-            };
+        };
```
Comment (nmancus1) [inline src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/FinalLocalVariableCheckTest.java:304]: @anhminhtran235 please make this as separate commit, such as `minor: fix indentation` since this was not related to #8934. Some GSOC student must've missed this over the summer :)

File: src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/finallocalvariable/InputFinalLocalVariableCheckSwitchExpressions.java (hunk 3 above)
Comment (nmancus1) [reply src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/finallocalvariable/InputFinalLocalVariableCheckSwitchExpressions.java]: Resolved.

File: src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/FinalLocalVariableCheckTest.java (hunk 5 above)
Comment (nmancus1) [reply src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/FinalLocalVariableCheckTest.java]: Resolved.

File: src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/FinalLocalVariableCheckTest.java (hunk 6 above)
Comment (anhminhtran235) [reply src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/FinalLocalVariableCheckTest.java:304]: So should it be in this same PR, or in a different PR?

Comment (nmancus1) [reply src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/FinalLocalVariableCheckTest.java]: > So should it be in this same PR, or in a different PR?

In this PR, please. It is ok for a `minor` commit such as this that doesn't affect functionality.  Thanks for double checking, you are right, it is always a good practice to keep functional changes in separate issues/PRs.

Comment (anhminhtran235) [reply src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/FinalLocalVariableCheckTest.java:304]: I see. I just added a minor commit to fix indentation

Comment (nmancus1) [reply src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/FinalLocalVariableCheckTest.java:304]: @anhminhtran235 I forgot:  to pass Travis you will likely need to make it `minor: fix indentation(#8934)`, since one of our CI jobs tests for an issue number in your commits.  Thanks a lot.

Comment (anhminhtran235) [reply src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/FinalLocalVariableCheckTest.java:304]: Thanks @nmancus1. Commit name fixed.

Comment (nmancus1) [reply src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/FinalLocalVariableCheckTest.java:304]: Resolved.

**Comment by nmancus1** [comment]
@pbludov I approve of all changes, please remove my assignment.  Thanks!

**Review by pbludov — APPROVED** [review]
