### PR TITLE
Issue #12100: Review usages of BeforeAll in tests 

### LINKED ISSUE #12100: Review usages of `BeforeAll` in tests
We have discovered that `BeforeAll` used in conjunction with production static field modifications has allowed some surviving mutations that are false positives. From https://github.com/hcoles/pitest/issues/1081#issuecomment-1225447257:

> From a quick scan through the code I think this is "working as expected", as the test suite has hit a wrinkle with how static state works with coverage based mutation systems.

> Because this code is only run if there is no entry in the static BUNDLE_CACHE, the result of mutation testing will be highly dependent on the order in which tests are run. Adding or removing a test may completely change the order.

> If 20 tests could execute the line of code, only the first one to run (and the first ones to run after each time the cache is cleared) will actually execute the code. Only these tests will be linked by coverage to the mutation, so pitest will only select from this reduced set when the mutant is active.

In #12053 , we worked around this issue by using `BeforeEach`:

>@ZuevKirill95 Strangely using `@BeforeEach` instead of `@BeforeAll` kills the mutation, the issue for the same has been opened at https://github.com/hcoles/pitest/issues/1081.

>For now, you can use `@BeforeEach` to kill the mutation.

We should review all usages of `BeforeAll` to see if we have surviving mutations from this issue, and see if we can use `BeforeEach` instead. We should also consider forbidding usage of `BeforeAll` based on our findings, and probably at least restrict future usage of it.

```bash
➜  checkstyle git:(master) ag -Q "@BeforeAll"      
src/test/java/com/puppycrawl/tools/checkstyle/internal/CommitValidationTest.java
97:    @BeforeAll

src/test/java/com/puppycrawl/tools/checkstyle/internal/XpathRegressionTest.java
148:    @BeforeAll

src/test/java/com/puppycrawl/tools/checkstyle/internal/ArchUnitTest.java
35:    @BeforeAll

src/test/java/com/puppycrawl/tools/checkstyle/meta/XmlMetaReaderTest.java
37:    @BeforeAll

src/test/java/com/puppycrawl/tools/checkstyle/AbstractGuiTestSupport.java
38:    @BeforeAll

src/test/java/com/puppycrawl/tools/checkstyle/XpathFileGeneratorAuditListenerTest.java
67:    @BeforeAll

src/it/java/com/google/checkstyle/test/chapter5naming/rule528typevariablenames/MethodTypeParameterNameTest.java
41:    @BeforeAll


```

### PR DESCRIPTION
**Pull request by Vyom-Yadav**
Resolves #12100

### CODE REVIEW

**Comment by nick-mancuso** [comment]
@Vyom-Yadav please see CI failures, and we can now do this PR in scope of #12100

File: src/it/java/com/google/checkstyle/test/chapter5naming/rule528typevariablenames/MethodTypeParameterNameTest.java [hunk 1]
```diff
@@ -38,7 +38,7 @@ protected String getPackageLocation() {
         return "com/google/checkstyle/test/chapter5naming/rule528typevariablenames";
     }
 
-    @BeforeAll
+    @BeforeEach
     public static void setConfigurationBuilder() throws CheckstyleException {
```
Comment (rnveach) [inline src/it/java/com/google/checkstyle/test/chapter5naming/rule528typevariablenames/MethodTypeParameterNameTest.java:42]: BeforeEach cannot be static. I am not sure if pitest is actually running the method because of this but it is causing a CI failure.

File: src/test/java/com/puppycrawl/tools/checkstyle/internal/CommitValidationTest.java [hunk 2]
```diff
@@ -94,7 +94,7 @@ public class CommitValidationTest {
 
     private static List<RevCommit> lastCommits;
 
-    @BeforeAll
+    @BeforeEach
     public static void setUp() throws Exception {
         lastCommits = getCommitsToCheck();
```
Comment (rnveach) [inline src/test/java/com/puppycrawl/tools/checkstyle/internal/CommitValidationTest.java:99]: This should not be a before each. This is basically a caching method and is not even part of the pitest suite.

File: src/test/java/com/puppycrawl/tools/checkstyle/internal/XpathRegressionTest.java [hunk 3]
```diff
@@ -145,7 +144,7 @@ public class XpathRegressionTest extends AbstractModuleTestSupport {
     private Path javaDir;
     private Path inputDir;
 
-    @BeforeAll
+    @BeforeEach
     public static void setUpBeforeClass() throws IOException {
         simpleCheckNames = CheckUtil.getSimpleNames(CheckUtil.getCheckstyleChecks());
```
Comment (rnveach) [inline src/test/java/com/puppycrawl/tools/checkstyle/internal/XpathRegressionTest.java:149]: Same.

**Review by rnveach — CHANGES_REQUESTED** [review]

File: src/test/java/com/puppycrawl/tools/checkstyle/XpathFileGeneratorAuditListenerTest.java [hunk 4]
```diff
@@ -64,7 +64,7 @@ public class XpathFileGeneratorAuditListenerTest {
     private final CloseAndFlushTestByteArrayOutputStream outStream =
             new CloseAndFlushTestByteArrayOutputStream();
 
-    @BeforeAll
+    @BeforeEach
     public static void constructEvents() throws Exception {
```
Comment (rnveach) [inline src/test/java/com/puppycrawl/tools/checkstyle/XpathFileGeneratorAuditListenerTest.java:68]: This before is very questionable. It is not modifying any fields and is not doing any assertions. However, removing it results in test failures so obviously there is a pass by reference going on here.

`XpathFileGeneratorAstFilter#accept` is basically populated `XpathFileGeneratorAstFilter#MESSAGE_QUERY_MAP` with pre-filled values to be read in the actual tests.

It is possible to have random test order issues if a new test was added that erased this cache by mistake.

File: src/it/java/com/google/checkstyle/test/chapter5naming/rule528typevariablenames/MethodTypeParameterNameTest.java [hunk 5]
```diff
@@ -38,7 +38,7 @@ protected String getPackageLocation() {
...
         format = getModuleConfig("ClassTypeParameterName").getProperty("format");
```
Comment (rnveach) [inline src/it/java/com/google/checkstyle/test/chapter5naming/rule528typevariablenames/MethodTypeParameterNameTest.java:43]: I feel this before can just be completely removed and inlined.

Comment (Vyom-Yadav) [reply src/it/java/com/google/checkstyle/test/chapter5naming/rule528typevariablenames/MethodTypeParameterNameTest.java:43]: It throws an exception, better to be instantiated in the method.

File: src/test/java/com/puppycrawl/tools/checkstyle/XpathFileGeneratorAuditListenerTest.java (hunk 4 above)
Comment (Vyom-Yadav) [reply src/test/java/com/puppycrawl/tools/checkstyle/XpathFileGeneratorAuditListenerTest.java]: Reverted back to `@BeforeAll`

File: src/it/java/com/google/checkstyle/test/chapter5naming/rule528typevariablenames/MethodTypeParameterNameTest.java (hunk 5 above)
Comment (rnveach) [reply src/it/java/com/google/checkstyle/test/chapter5naming/rule528typevariablenames/MethodTypeParameterNameTest.java:43]: What is the exception?

File: src/test/java/com/puppycrawl/tools/checkstyle/XpathFileGeneratorAuditListenerTest.java (hunk 4 above)
Comment (rnveach) [reply src/test/java/com/puppycrawl/tools/checkstyle/XpathFileGeneratorAuditListenerTest.java]: IMO, a different way should be done instead of this. Like I said, this cause result in random test order issues which will affect pitest.

Comment (Vyom-Yadav) [reply src/test/java/com/puppycrawl/tools/checkstyle/XpathFileGeneratorAuditListenerTest.java]: Initialized them in a different way.

File: src/it/java/com/google/checkstyle/test/chapter5naming/rule528typevariablenames/MethodTypeParameterNameTest.java [hunk 6]
```diff
@@ -31,18 +31,22 @@
 public class MethodTypeParameterNameTest extends AbstractGoogleModuleTestSupport {
 
     private static final String MSG_KEY = "name.invalidPattern";
-    private static String format;
+    private static final String format = getFormat();
```
Comment (nrmancuso) [inline src/it/java/com/google/checkstyle/test/chapter5naming/rule528typevariablenames/MethodTypeParameterNameTest.java:34]: Why does this have to be a field? Can we just do:
```java
        final String format = checkConfig.getProperty("format");
```
in each unit test? I would rather throw an exception as part of the unit test than when we are initializing them.

File: src/test/java/com/puppycrawl/tools/checkstyle/internal/CommitValidationTest.java [hunk 7]
```diff
@@ -92,11 +92,15 @@ public class CommitValidationTest {
     private static final CommitsResolutionMode COMMITS_RESOLUTION_MODE =
             CommitsResolutionMode.BY_LAST_COMMIT_AUTHOR;
 
-    private static List<RevCommit> lastCommits;
+    private static final List<RevCommit> lastCommits = getLastCommits();
 
-    @BeforeAll
-    public static void setUp() throws Exception {
-        lastCommits = getCommitsToCheck();
+    public static List<RevCommit> getLastCommits() {
```
Comment (nrmancuso) [inline src/test/java/com/puppycrawl/tools/checkstyle/internal/CommitValidationTest.java:97]: Two questions:
1. Why is this method public?
2. Can we just get last commits in unit test methods?

File: src/test/java/com/puppycrawl/tools/checkstyle/internal/XpathRegressionTest.java [hunk 8]
```diff
@@ -138,22 +138,32 @@ public class XpathRegressionTest extends AbstractModuleTestSupport {
...
     );
 
-    private static Set<String> simpleCheckNames;
-    private static Map<String, String> allowedDirectoryAndChecks;
-    private static Set<String> internalModules;
+    private static final Set<String> simpleCheckNames = getSimpleCheckNames();
+    private static final Map<String, String> allowedDirectoryAndChecks =
+        getAllowedDirectoryAndChecks();
+
+    private static final Set<String> internalModules = getInternalModules();
```
Comment (nrmancuso) [inline src/test/java/com/puppycrawl/tools/checkstyle/internal/XpathRegressionTest.java:145]: Can we move initialization of these into the `BeforeEach` below (as well as content of methods that initialize them)?

**Review by nrmancuso — CHANGES_REQUESTED** [review]
Items:

File: src/it/java/com/google/checkstyle/test/chapter5naming/rule528typevariablenames/MethodTypeParameterNameTest.java (hunk 6 above)
Comment (rnveach) [reply src/it/java/com/google/checkstyle/test/chapter5naming/rule528typevariablenames/MethodTypeParameterNameTest.java:34]: https://github.com/checkstyle/checkstyle/blob/399f1b48b79731d65e824eb927971ef6174c3463/src/it/java/com/google/checkstyle/test/chapter5naming/rule51identifiernames/CatchParameterNameTest.java#L40

File: src/test/java/com/puppycrawl/tools/checkstyle/internal/XpathRegressionTest.java (hunk 8 above)
Comment (Vyom-Yadav) [reply src/test/java/com/puppycrawl/tools/checkstyle/internal/XpathRegressionTest.java:145]: We can, but why? Initializing `internalModules` doesn't throw an exception and initializing `simpleCheckNames` and `allowedDirectoryAndChecks` initially shouldn't cause any problem.

Comment (rnveach) [reply src/test/java/com/puppycrawl/tools/checkstyle/internal/XpathRegressionTest.java:145]: If this just initializes the values once, and they never change during test runs, then it doesn't make sense to run them in `BeforeEach` as it will just generate the same lists every time. `BeforeEach` should really be for areas that need to be reset or prepare for each run.

Comment (Vyom-Yadav) [reply src/test/java/com/puppycrawl/tools/checkstyle/internal/XpathRegressionTest.java:145]: They don't change during the tests.

Comment (nrmancuso) [reply src/test/java/com/puppycrawl/tools/checkstyle/internal/XpathRegressionTest.java]: > If this just initializes the values once, and they never change during test runs, then it doesn't make sense to run them in `BeforeEach` as it will just generate the same lists every time. `BeforeEach` should really be for areas that need to be reset or prepare for each run.

Agreed, let’s not do this.

File: src/it/java/com/google/checkstyle/test/chapter5naming/rule528typevariablenames/MethodTypeParameterNameTest.java (hunk 6 above)
Comment (Vyom-Yadav) [reply src/it/java/com/google/checkstyle/test/chapter5naming/rule528typevariablenames/MethodTypeParameterNameTest.java]: Done.

File: src/test/java/com/puppycrawl/tools/checkstyle/internal/CommitValidationTest.java (hunk 7 above)
Comment (Vyom-Yadav) [reply src/test/java/com/puppycrawl/tools/checkstyle/internal/CommitValidationTest.java]: Done.

File: src/test/java/com/puppycrawl/tools/checkstyle/internal/XpathRegressionTest.java (hunk 8 above)
Comment (Vyom-Yadav) [reply src/test/java/com/puppycrawl/tools/checkstyle/internal/XpathRegressionTest.java]: `PMD Failure: com.puppycrawl.tools.checkstyle.internal.XpathRegressionTest:154 Rule:AvoidThrowingRawExceptionTypes Priority:1 Avoid throwing raw exception types..`

Should I create a custom exception?

Comment (nrmancuso) [reply src/test/java/com/puppycrawl/tools/checkstyle/internal/XpathRegressionTest.java]: No, please avoid custom exceptions at all costs.

Comment (Vyom-Yadav) [reply src/test/java/com/puppycrawl/tools/checkstyle/internal/XpathRegressionTest.java]: I added it to the suppression list.

File: src/test/java/com/puppycrawl/tools/checkstyle/internal/XpathRegressionTest.java [hunk 9]
```diff
@@ -138,22 +137,32 @@ public class XpathRegressionTest extends AbstractModuleTestSupport {
...
+        }
+    }
 
-        allowedDirectoryAndChecks = simpleCheckNames
-                .stream()
-                .collect(Collectors.toMap(id -> id.toLowerCase(Locale.ENGLISH), id -> id));
+    private static Map<String, String> getAllowedDirectoryAndChecks() {
+        return SIMPLE_CHECK_NAMES
+            .stream()
+            .collect(Collectors.toMap(id -> id.toLowerCase(Locale.ENGLISH), id -> id));
```
Comment (nrmancuso) [inline src/test/java/com/puppycrawl/tools/checkstyle/internal/XpathRegressionTest.java:161]: `id -> id` can we use identity function here?

File: src/test/java/com/puppycrawl/tools/checkstyle/internal/XpathRegressionTest.java [hunk 10]
```diff
@@ -138,22 +137,32 @@ public class XpathRegressionTest extends AbstractModuleTestSupport {
...
 
-    @BeforeAll
-    public static void setUpBeforeClass() throws IOException {
-        simpleCheckNames = CheckUtil.getSimpleNames(CheckUtil.getCheckstyleChecks());
+    private static Set<String> getSimpleCheckNames() {
+        try {
+            return CheckUtil.getSimpleNames(CheckUtil.getCheckstyleChecks());
+        }
+        catch (IOException ex) {
+            throw new RuntimeException(ex);
```
Comment (nrmancuso) [inline src/test/java/com/puppycrawl/tools/checkstyle/internal/XpathRegressionTest.java:154]: Please use `ExceptionInInitializerError`

**Review by nrmancuso — CHANGES_REQUESTED** [review]
Items:

File: src/test/java/com/puppycrawl/tools/checkstyle/internal/XpathRegressionTest.java (hunk 9 above)
Comment (Vyom-Yadav) [reply src/test/java/com/puppycrawl/tools/checkstyle/internal/XpathRegressionTest.java]: Done.

File: src/test/java/com/puppycrawl/tools/checkstyle/internal/XpathRegressionTest.java (hunk 10 above)
Comment (Vyom-Yadav) [reply src/test/java/com/puppycrawl/tools/checkstyle/internal/XpathRegressionTest.java]: Done.

**Review by nrmancuso — COMMENTED** [review]
I am not sure if we are ready to forbid `BeforeAll`, but it seems like remaining usages are probably unnecessary. If we turn off these loggers for tests, we should probably do this in the pom or some property file (i.e. globally); especially since one of these is for ArchUnit and we shouldn't have to turn off this property in each ArchUnit test (and we haven't been). I am curious what others think. @romani @rnveach?

**Comment by rnveach** [comment]
We are turning off the loggers for this test, never turning them back on, and it is most likely leaking into other tests and not guaranteed that we are turning them off for all tests (depending on junit's random order). I feel this isn't safe and could cause some weird issue like what we have seen for pitest testing, so something should be done.

If we can disable these loggers for all tests like @nrmancuso said, that would be the best.

**Comment by romani** [comment]
> We have discovered that BeforeAll used in conjunction with production static field modifications has allowed some surviving mutations that are false positives

I confused, I see no updates in survivals. What is benefiting from this test update.
I ok with update, but goal is strange.

**Comment by Vyom-Yadav** [comment]
> I confused, I see no updates in survivals. What is benefiting from this test update.
I ok with update, but goal is strange.

Yes, we did not kill any mutations, but it could have been in-general problematic like rnveach has mentioned in the issue comment.

**Review by romani — APPROVED** [review]
Ok to merge

**Comment by romani** [comment]
Lets not finish,l annotation, we will try to recheck this during code review.

**Review by rnveach — CHANGES_REQUESTED** [review]
https://github.com/checkstyle/checkstyle/pull/12098#discussion_r955499871
This item is still left from my original review.

https://github.com/checkstyle/checkstyle/pull/12098#pullrequestreview-1103140612
Can we do this?

**Review by rnveach — COMMENTED** [review]
After talking with @romani , we are going to delay this PR until GSoC clears up since it no longer is looking related to GSoC or pitest and allow student to focus on more GSoC like Checker.

**Comment by nrmancuso** [comment]
@rnveach @Vyom-Yadav can we proceed?

**Comment by rnveach** [comment]
if @Vyom-Yadav 's time is scarce, I would like to finish resolved Checker to keep on 1 target.

**Comment by romani** [comment]
@Vyom-Yadav, please rebase.

**Comment by rnveach** [comment]
I am still waiting for my previous review items to be finished.
https://github.com/checkstyle/checkstyle/pull/12098#pullrequestreview-1103171646

File: src/test/java/com/puppycrawl/tools/checkstyle/XpathFileGeneratorAuditListenerTest.java (hunk 4 above)
Comment (Vyom-Yadav) [reply src/test/java/com/puppycrawl/tools/checkstyle/XpathFileGeneratorAuditListenerTest.java]: Given the design of `XpathFileGeneratorAstFilter`, the only option is to populate the map in a static block, changed to that.

**Review by rnveach — APPROVED** [review]

**Review by nrmancuso — APPROVED** [review]
@Vyom-Yadav thanks a lot for wrapping this up
