### PR TITLE
Issue #13205: Add links to examples' paragraphs

### LINKED ISSUE #13205: Add links to examples paragraphs
From https://github.com/checkstyle/checkstyle/pull/13112#discussion_r1225682976
> As the discussion in discord, should these PRs add the ID to connect the xdoc and input together?

This is a good idea but I cannot add `id` prop directly to a `source` tag
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-site-plugin:3.12.1:site (default-site) on project checkstyle: Error parsing '/home/stoyan/open-source/checkstyle/src/xdocs/config_blocks.xml': Error validating the model: Error:
[ERROR]   Public ID: null
[ERROR]   System ID: null
[ERROR]   Line number: 85
[ERROR]   Column number: 26
[ERROR]   Message: cvc-complex-type.3.2.2: Attribute 'id' is not allowed to appear in element 'source'.
```

An option here is to create an invisible div above the example.
```diff
+        <div id="Example1.config" style="display:none;"></div>
        <source>
&lt;module name=&quot;AvoidNestedBlocks&quot;/&gt;
        </source>
```

In addition to this, I see there is a task at https://github.com/orgs/checkstyle/projects/5 to investigate the ability to set links for any place we think. 

Why don't we combine those two?

### PR DESCRIPTION
**Pull request by stoyanK7**
Resolves #13205

---

Adds anchors to paragraphs that have an ID starting with `Example`. For now, this applies to `WhitespaceAfter`'s paragraphs because only they have such IDs. But as we transfer more xdocs to templates, others will get IDs too.

### CODE REVIEW

**Comment by stoyanK7** [comment]
Github, generate site

**Comment by stoyanK7** [comment]
https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/dda7ce3_2023115310/checks/whitespace/whitespaceafter.html#Properties

https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/dda7ce3_2023115310/checks/whitespace/whitespaceafter.html#Example1-config

https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/dda7ce3_2023115310/checks/whitespace/whitespaceafter.html#Example2-config

https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/dda7ce3_2023115310/checks/whitespace/whitespaceafter.html#Example2-code

**Comment by nrmancuso** [comment]
From the issue:
>We can add a check to ensure all examples have an anchor. I imagine a big file of suppressions being made and gradually removing them as examples are moved to tests.

Should the above be part of this PR? How can we achieve this?

**Comment by stoyanK7** [comment]
@nrmancuso https://github.com/checkstyle/checkstyle/pull/13456 deals with this.

**Review by romani — APPROVED** [review]
ok to merge

File: src/site/resources/js/anchors.js [hunk 1]
```diff
@@ -56,6 +56,25 @@
             anchor.appendChild(a);
             anchorItem.appendChild(anchor);
         });
+
+        var exampleDivs = document.querySelectorAll('p[id^="Example"]');
```
Comment (nrmancuso) [inline src/site/resources/js/anchors.js:60]: I really have no knowledge of JS syntax/best practices, but is there some way to make these final? `var` -> `val` (by quick google search)? Or is this not generally done?

**Review by nrmancuso — CHANGES_REQUESTED** [review]
Item:

File: src/site/resources/js/anchors.js (hunk 1 above)
Comment (stoyanK7) [reply src/site/resources/js/anchors.js:60]: We can do `const`. It's pretty common actually. I just noticed the other code not doing it and followed.

Comment (stoyanK7) [reply src/site/resources/js/anchors.js]: Done. Changed all to `const`.

**Comment by stoyanK7** [comment]
Github, generate site

**Review by nrmancuso — APPROVED** [review]

**Review by rnveach — APPROVED** [review]
