### PR TITLE
Issue #8873: RequireThis: Incorrectly triggers for record fields in compact constructor

### LINKED ISSUE #8873: RequireThis: Incorrectly triggers for record fields in compact constructor
Check documentation: https://checkstyle.org/config_coding.html#RequireThis

```
/var/tmp $ javac --enable-preview --release 14 RequireThisRecord.java
Note: RequireThisRecord.java uses preview language features.
Note: Recompile with -Xlint:preview for details.
```

`/var/tmp $ cat checkstyle-recordthis.xml`
```xml
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
          "-//Checkstyle//DTD Checkstyle Configuration 1.3//EN"
          "https://checkstyle.org/dtds/configuration_1_3.dtd">

<module name="Checker">
    <property name="charset" value="UTF-8"/>

    <property name="severity" value="${severity}" default="warning"/>

    <property name="fileExtensions" value="java, properties, xml"/>
    <!-- Excludes all 'module-info.java' files              -->
    <!-- See https://checkstyle.org/config_filefilters.html -->
    <module name="BeforeExecutionExclusionFileFilter">
        <property name="fileNamePattern" value="module\-info\.java$"/>
    </module>

    <module name="TreeWalker">
        <module name="RequireThis">
            <property name="validateOnlyOverlapping" value="false"/>
        </module>
    </module>
</module>
```

`/var/tmp $ cat RequireThisRecord.java`
```java
import java.util.Map;

record RequireThisRecord(String name, Map<String, String> items) {

    public RequireThisRecord {
        if (name == null) {
            name = "<unknown>";
        }
        items = Map.copyOf(items);
    }

}
```

```
/var/tmp $ RUN_LOCALE="-Duser.language=en -Duser.country=US"
/var/tmp $ java $RUN_LOCALE -jar checkstyle-8.36.2-all.jar -c checkstyle-recordthis.xml RequireThisRecord.java
Starting audit...
[WARN] RequireThisRecord.java:6:13: Reference to instance variable 'name' needs "this.". [RequireThis]
[WARN] RequireThisRecord.java:7:13: Reference to instance variable 'name' needs "this.". [RequireThis]
[WARN] RequireThisRecord.java:9:9: Reference to instance variable 'items' needs "this.". [RequireThis]
[WARN] RequireThisRecord.java:9:28: Reference to instance variable 'items' needs "this.". [RequireThis]
Audit done.

```
---------------

I'm back again :) been playing with records some more in Configurate, and came across this issue. The `RequireThis` check seems to treat accesses in the record constructor as acting on the backing fields, not the (implicit) constructor parameters, so it expects them to be qualified with `this.`. However, adding `this.` to the variables results in a compile-time error, so this check should not trigger an error.

From [the JLS section on records](https://docs.oracle.com/javase/specs/jls/se15/preview/specs/records-jls.html#jls-8.10), section 8.10.4:

> It is a compile-time error if an assignment occurs (16) to a field corresponding to a record component of the record class in the body of the compact constructor.
>
> All fields corresponding to the record components of the record class are implicitly initialized to the value of the corresponding formal parameter after the body of the compact constructor. These fields are implicitly initialized in the order that they are declared in the record component list.

I came across this as part of some work I'm doing locally to validate the API -- the full original class that caused the error is at https://gist.github.com/zml2008/5f6de6484eed5b9d8451c5e1625f8572

### PR DESCRIPTION
**Pull request by anhminhtran235**
Fix #8873 
This PR disables `requireThis` in COMPACT_CTOR_DEF, since `this` cannot be used in COMPACT_CTOR_DEF in Java 15 as mentioned [here](https://github.com/checkstyle/checkstyle/issues/8873#issuecomment-720129384).

As mentioned [here](https://github.com/checkstyle/checkstyle/issues/8873#issuecomment-723726379), not printing error message when `ast` is in `COMPACT_CTOR_DEF` solves the problem in #8873

Also, 4 violations in `testRecordsAsTopLevel()` are no longer violations, so I removed them.

Diff Regression config: https://gist.githubusercontent.com/anhminhtran235/bf0e177285c39256dd7e3217d8dae9e1/raw/55ff82d4be5a21d610e83da86dba7835eea2560d/config.xml
Diff Regression projects: https://gist.githubusercontent.com/anhminhtran235/2da94f96d35ab9471624c5b6c4421c66/raw/82b014453ca421085199b4635f6a13c26a62941d/projects-to-test-on.properties

### CODE REVIEW

**Comment by anhminhtran235** [comment]
GitHub, generate report

**Comment by anhminhtran235** [comment]
@romani wrecker is failing. Could you please take a look?

**Comment by romani** [comment]
From wercker:

>fetch failed to pull image maven: API error (500): {"message":"toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit"}

I related to your code changes.

**Comment by anhminhtran235** [comment]
> I related to your code changes.
@romani I don't think it relates to my code change. I force pushed with a minor change in java docs comment and it's working again.
Also, travis keeps pending recently. Do you know why?

**Comment by romani** [comment]
Travis doing migration to new domain, free executions are delaying in queue  for limited resources.

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/RequireThisCheck.java [hunk 1]
```diff
@@ -510,6 +511,21 @@ private AbstractFrame getFieldWithoutThis(DetailAST ast, int parentType) {
...
+     * Return whether ast is in a COMPACT_CTOR_DEF.
+     *
+     * @param ast The token to check
+     * @return true if ast is in a COMPACT_CTOR_DEF, false otherwise
+     */
+    private static boolean isInCompactConstructor(DetailAST ast) {
+        boolean isInCompactCtor = false;
+        if (ast.getParent() != null) {
+            isInCompactCtor = ast.getParent().getType() == TokenTypes.COMPACT_CTOR_DEF
+                                || isInCompactConstructor(ast.getParent());
```
Comment (pbludov) [inline src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/RequireThisCheck.java:524]: This can be easily replaced with a loop. How deep this recursion can be?

Comment (anhminhtran235) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/RequireThisCheck.java]: You are right. I have replaced it with a loop.
The recursion can reasonably be up to 6-8 level deep, depending on how many nested loops, nested expressions there are.

Comment (anhminhtran235) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/RequireThisCheck.java]: @pbludov The code has been fixed. Please review

**Review by esilkensen — APPROVED** [review]

**Comment by anhminhtran235** [comment]
@pbludov Item has been fixed. Please review when you have time. Thank you

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/RequireThisCheck.java [hunk 2]
```diff
@@ -510,6 +511,25 @@ private AbstractFrame getFieldWithoutThis(DetailAST ast, int parentType) {
...
 
+    /**
+     * Return whether ast is in a COMPACT_CTOR_DEF.
+     *
+     * @param ast The token to check
+     * @return true if ast is in a COMPACT_CTOR_DEF, false otherwise
+     */
+    private static boolean isInCompactConstructor(DetailAST ast) {
+        boolean isInCompactCtor = false;
+        DetailAST tempAst = ast;
```
Comment (pbludov) [inline src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/RequireThisCheck.java:522]: This variable can be initialized with `ast.getParent()`, so the loop simplifies to
```java
 DetailAST tempAst = ast.getParent();
 while (tempAst != null) {
   if (tempAst.getType() == TokenTypes.COMPACT_CTOR_DEF) {
   ...
```
also, `tempAst` can be renamed to `parent` for readability.

**Review by pbludov — CHANGES_REQUESTED** [review]
Please do this small change

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/RequireThisCheck.java (hunk 2 above)
Comment (anhminhtran235) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/RequireThisCheck.java]: fixed

**Review by pbludov — APPROVED** [review]

File: src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/requirethis/InputRequireThisRecordCompactCtors.java [hunk 3]
```diff
@@ -0,0 +1,17 @@
+//non-compiled with javac: Compilable with Java14
```
Comment (nmancus1) [inline src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/requirethis/InputRequireThisRecordCompactCtors.java:1]: @romani @pbludov should we consider creating a `javac15` CI run for input files, similar to https://github.com/checkstyle/checkstyle/blob/be3dab2a74df0abd0712df01cd93e0ad9223ee21/.ci/travis/travis.sh#L118?  Since the changes in this PR relate to jdk15 syntax, and we already have an open issue for jdk15 specific syntax (#8989), this might be a good idea.

**Review by nmancus1 — APPROVED** [review]
@anhminhtran235 looks good.  It is tough to keep up with all the changes between jdk versions, especially with preview features.  Thanks a lot for your contribution.

File: src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/requirethis/InputRequireThisRecordCompactCtors.java (hunk 3 above)
Comment (romani) [reply src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/requirethis/InputRequireThisRecordCompactCtors.java:1]: We we need this execution in CI

Comment (romani) [reply src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/requirethis/InputRequireThisRecordCompactCtors.java:1]: https://github.com/checkstyle/checkstyle/issues/9007

**Comment by romani** [comment]
If CI is green, ok to merge.

**Comment by anhminhtran235** [comment]
@nmancus1 I agree. New JDK versions create a lot of edge cases we originally don't have. Thank you for reviewing my PR.

**Comment by romani** [comment]
@anhminhtran235 , Travis failing on job that verify that PR is not rebased for long time.
Please keep it as practice, if you push some new changes, do not forget to pull latest master and rebase.
