### PR TITLE
Issue #11374: Fix false positive related to anon inner classes in UnusedLocalVariableCheck

### LINKED ISSUE #11374: False Positive: UnusedLocalVariableCheck
I have read check documentation: https://checkstyle.sourceforge.io/config_coding.html#UnusedLocalVariable
I have downloaded the latest checkstyle from: https://checkstyle.org/cmdline.html#Download_and_Run
I have executed the cli and showed it below, as cli describes the problem better than 1,000 words

```bash
/var/tmp $ javac Test.java

/var/tmp $ cat config.xml
```
```xml
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
        "-//Checkstyle//DTD Checkstyle Configuration 1.3//EN"
        "https://checkstyle.org/dtds/configuration_1_3.dtd">
<module name="Checker">
    <module name="TreeWalker">
        <module name="UnusedLocalVariable"/>
    </module>
</module>
```
```
/var/tmp $ cat Test.java
```
```java
public class Test {

    static class m {
        static class h {
            public int a = 12;
        }
    }

    class j {
        void method() {
            int a = 22;
            m.h obj = new m.h() {
                int j = a + 12;
            };
            obj.getClass();
        }

        static class m {
            static class h {
            }
        }
    }
}
```
```
/var/tmp $ RUN_LOCALE="-Duser.language=en -Duser.country=US"
/var/tmp $ java $RUN_LOCALE -jar checkstyle-10.0-all.jar -c config.xml Test.java
Starting audit...
[ERROR] /var/tmp/Test.java:11:13: Unused local variable 'a'. [UnusedLocalVariable]
Audit done.
Checkstyle ends with 1 errors.

```
---

**Describe what you expect in detail.**
```
/var/tmp $ RUN_LOCALE="-Duser.language=en -Duser.country=US"
/var/tmp $ java $RUN_LOCALE -jar checkstyle-10.0-all.jar -c config.xml Test.java
Starting audit...
Audit done.
```

---

Discovered while working on #11365, the source has been identified, the fix has been done locally, will be pushed soon.

### PR DESCRIPTION
**Pull request by kkoutsilis**
Aims to close #11374
Based on abandoned #12795

### CODE REVIEW

**Comment by romani** [comment]
Github, generate report for UnusedLocalVariable/all-examples-in-one

**Comment by romani** [comment]
Extra Test coverage is required 

>
```<description>removed conditional - replaced equality check with true</description>
+    <lineContent>if (idx == minLength - 1 &amp;&amp; shouldCountBeUpdatedAtLastCharacter</lineContent>`
``

https://github.com/checkstyle/checkstyle/actions/runs/12084878265/job/33700973334?pr=15969

File: src/main/java/com/puppycrawl/tools/checkstyle/utils/CheckUtil.java [hunk 1]
```diff
@@ -496,6 +496,47 @@ public static int typeDeclarationNameMatchingCount(String patternClass,
...
+     * is encountered.
+     * This is necessary because pattern class can include anonymous inner classes, unlike regular
+     * inheritance where nested classes cannot be extended.
+     * </p>
+     *
+     * @param patternTypeDeclaration type declaration to match against
+     * @param typeDeclarationToBeMatched type declaration to be matched
+     * @return the type declaration matching count
+     */
+    public static int getAnonSuperTypeMatchingCount(String patternTypeDeclaration,
```
Comment (romani) [inline src/main/java/com/puppycrawl/tools/checkstyle/utils/CheckUtil.java:517]: This method looks very specific to Check, please consider to move it to Check.
We discourage until methods, and ok only if there is already few Checks are going to use it.

**Review by romani — CHANGES_REQUESTED** [review]
Items

File: src/main/java/com/puppycrawl/tools/checkstyle/utils/CheckUtil.java (hunk 1 above)
Comment (kkoutsilis) [reply src/main/java/com/puppycrawl/tools/checkstyle/utils/CheckUtil.java]: Moved `getAnonSuperTypeMatchingCount` to `UnusedLocalVariableCheck`, and also `typeDeclarationNameMatchingCount` to `FinalClassCheck` as it's the only class that uses this method now.

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/design/FinalClassCheck.java [hunk 2]
```diff
@@ -263,7 +263,7 @@ private void registerExtendedClass(String qualifiedClassName,
         final String superClassName = getSuperClassName(currentClass.getTypeDeclarationAst());
         if (superClassName != null) {
             final ToIntFunction<ClassDesc> nestedClassCountProvider = classDesc -> {
-                return CheckUtil.typeDeclarationNameMatchingCount(qualifiedClassName,
+                return typeDeclarationNameMatchingCount(qualifiedClassName,
```
Comment (romani) [inline src/main/java/com/puppycrawl/tools/checkstyle/checks/design/FinalClassCheck.java:266]: Please move this change to separate PR, let's not make this PR heavy  in changes to let us review and merge quickly.

**Review by romani — CHANGES_REQUESTED** [review]
Items

**Comment by romani** [comment]
@kkoutsilis, do you need any help with CI problems?

**Comment by kkoutsilis** [comment]
> @kkoutsilis, do you need any help with CI problems?

Hey @romani, I didn't have time to mess around with it, will set some time aside this weekend and if I need help I'll let you know, thanks🙂

**Comment by romani** [comment]
Rebased in web UI to let ci pass.

**Comment by romani** [comment]
Github, generate report for UnusedLocalVariable/all-examples-in-one

**Comment by kkoutsilis** [comment]
I don't think I killed the mutations yet, but working on it

**Comment by kkoutsilis** [comment]
Should be good now, let's see if the CI agrees

**Comment by romani** [comment]
Github, generate report for UnusedLocalVariable/all-examples-in-one

**Comment by romani** [comment]
@Vyom-Yadav, please glance if you still around.

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java [hunk 3]
```diff
@@ -647,20 +647,61 @@ private static TypeDeclDesc getTheNearestClass(String outerTypeDeclName,
...
         if (diff == 0) {
             diff = Integer.compare(firstTypeDecl.getDepth(), secondTypeDecl.getDepth());
         }
         return diff;
     }
 
+    /**
+     * Calculates and returns the type declaration matching count when
+     * {@code typeDeclarationToBeMatched} is considered to be the superclass of an anonymous inner
+     * class.
```
Comment (romani) [inline src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java:667]: can it be ?
```
     * Calculates the type declaration matching count for the superclass of an anonymous inner
     * class.
```

**Review by romani — CHANGES_REQUESTED** [review]
only minor comments:

File: src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/unusedlocalvariable/InputUnusedLocalVariableAnonInnerClasses2.java [hunk 4]
```diff
@@ -0,0 +1,55 @@
...
+            int a = 1000;
+            int s = 13; // violation, 'Unused local variable'
+            int q = 14;
+            m.h obj = new m.h() {
+                @Override
+                void method() {
+                    Integer.valueOf(a + s);
+                }
+
+                m.h obj = new m.h() { // ok, inst var
```
[the remark this answers is not in the document]
Comment (kkoutsilis) [reply src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/unusedlocalvariable/InputUnusedLocalVariableAnonInnerClasses2.java]: [Addressed]( https://github.com/checkstyle/checkstyle/compare/cf6d56c9d7895e7dc3b9fbf1eebd377cbca20d39..29c8ef5a1215145f06875b79bb75fd1830f765f2)

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java [hunk 5]
```diff
@@ -647,20 +647,61 @@ private static TypeDeclDesc getTheNearestClass(String outerTypeDeclName,
...
+     * This is necessary because pattern class can include anonymous inner classes, unlike regular
+     * inheritance where nested classes cannot be extended.
+     * </p>
+     *
+     * @param patternTypeDeclaration type declaration to match against
+     * @param typeDeclarationToBeMatched type declaration to be matched
+     * @return the type declaration matching count
+     */
+    private static int getAnonSuperTypeMatchingCount(String patternTypeDeclaration,
+                                                    String typeDeclarationToBeMatched) {
```
[the remark this answers is not in the document]
Comment (kkoutsilis) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java]: [Addressed]( https://github.com/checkstyle/checkstyle/compare/cf6d56c9d7895e7dc3b9fbf1eebd377cbca20d39..29c8ef5a1215145f06875b79bb75fd1830f765f2)

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java (hunk 3 above)
Comment (kkoutsilis) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java:666]: [Addressed]( https://github.com/checkstyle/checkstyle/compare/cf6d56c9d7895e7dc3b9fbf1eebd377cbca20d39..29c8ef5a1215145f06875b79bb75fd1830f765f2)

**Review by romani — APPROVED** [review]
Ok to merge

**Comment by Vyom-Yadav** [comment]
I'll take a look on the weekend.

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java [hunk 6]
```diff
@@ -647,20 +647,60 @@ private static TypeDeclDesc getTheNearestClass(String outerTypeDeclName,
      * @param secondTypeDecl second input type declaration
      * @return difference between type declaration name matching count
      */
-    private static int getTypeDeclarationNameMatchingCountDiff(String outerTypeDeclName,
+    private static int getAnonTypeDeclarationNameMatchingCountDiff(String outerTypeDeclName,
```
Comment (nrmancuso) [inline src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java:650]: Similar to above, we are exposing implementation details in the method name, and it doesn't really help us to understand what this method does at a conceptual level or why we care about it.  Additionally, using `diff` and `match` in the name is misleading; once we are comparing depths, we really aren't talking about a "diff" any longer.

Please make this method signature to be `private static int calculateTypeDeclarationDistance(String outerTypeName, TypeDeclDesc firstType, TypeDeclDesc secondType)`.

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java [hunk 7]
```diff
@@ -647,20 +647,60 @@ private static TypeDeclDesc getTheNearestClass(String outerTypeDeclName,
...
+            getAnonSuperTypeMatchingCount(
                 outerTypeDeclName, secondTypeDecl.getQualifiedName()),
-            CheckUtil.typeDeclarationNameMatchingCount(
+            getAnonSuperTypeMatchingCount(
                 outerTypeDeclName, firstTypeDecl.getQualifiedName()));
         if (diff == 0) {
             diff = Integer.compare(firstTypeDecl.getDepth(), secondTypeDecl.getDepth());
         }
         return diff;
     }
```
Comment (nrmancuso) [inline src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java:662]: While we are here, we can also refactor this method a bit to use immutable data and make what we are doing more clear:

```java
    final int firstMatchCount = countMatchingQualifierChars(outerTypeName, firstType.getQualifiedName());
    final int secondMatchCount = countMatchingQualifierChars(outerTypeName, secondType.getQualifiedName());

    final int matchDistance = Integer.compare(secondMatchCount, firstMatchCount);

    final int result;
    if (matchDistance == 0) {
        result = Integer.compare( firstType.getDepth(),  secondType.getDepth());
    } else {
        result = matchDistance;
    }

    return result;
```

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java [hunk 8]
```diff
@@ -647,20 +647,60 @@ private static TypeDeclDesc getTheNearestClass(String outerTypeDeclName,
...
+     * @param patternQualifiedName type declaration to match against
+     * @param matchingQualifiedName type declaration to be matched
+     * @return the type declaration matching count
+     */
+    private static int getAnonSuperTypeMatchingCount(String patternQualifiedName,
+                                                    String matchingQualifiedName) {
+        final int typeDeclarationToBeMatchedLength = matchingQualifiedName.length();
+        final int minLength = Math
+                .min(typeDeclarationToBeMatchedLength, patternQualifiedName.length());
+        final boolean shouldCountBeUpdatedAtLastCharacter =
```
Comment (nrmancuso) [inline src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java:686]: Why do we care about this? This code is not obvious to me.

**Review by nrmancuso — CHANGES_REQUESTED** [review]
Items:

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java [hunk 9]
```diff
@@ -631,10 +631,10 @@ private boolean hasSameNameAsSuperClass(String superClassName, TypeDeclDesc type
      * @param typeDeclWithSameName typeDeclarations which have the same name as the super class
      * @return the nearest class
      */
-    private static TypeDeclDesc getTheNearestClass(String outerTypeDeclName,
+    private static TypeDeclDesc getTheNearestClassOfAnonInnerClass(String outerTypeDeclName,
```
Comment (nrmancuso) [inline src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java:634]: Shouldn’t this be `getClosestMatchingTypeDeclaration`?

Comment (nrmancuso) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java:634]: The naming conventions in this check really make this difficult to understand: the type we use for nearly all the heavy lifting is called `TypeDeclDesc`, but we nearly always name the variables with `class`.

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java [hunk 10]
```diff
@@ -647,20 +647,60 @@ private static TypeDeclDesc getTheNearestClass(String outerTypeDeclName,
...
+     * is encountered.
+     * This is necessary because pattern class can include anonymous inner classes, unlike regular
+     * inheritance where nested classes cannot be extended.
+     * </p>
+     *
+     * @param patternQualifiedName type declaration to match against
+     * @param matchingQualifiedName type declaration to be matched
+     * @return the type declaration matching count
+     */
+    private static int getAnonSuperTypeMatchingCount(String patternQualifiedName,
```
[the remark this answers is not in the document]
Comment (romani) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java:681]: `AnonSuper` imply that usage of it not general or at least we don't want to think if it could be general.

Naming "count......" Is good.

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java (hunk 6 above)
Comment (romani) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java:650]: If we name it a bit more general, could it be problem of misusage? Non of arguments imply that implementation is designed for annon type only for now.
If someone wants to make general method, he can create with general name and do appreciate implementation.

Just think on this one more time, this had concerns with names even in original PR.
I don't want to let this PR stuck again. 
If you really see it should be changed , just confirm one more time, and we will do it.

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java (hunk 9 above)
Comment (romani) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java:634]: >getClosestMatchingTypeDeclaration

Ok, Do you fully dislike `OfAnonInner` clarification in name?

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java (hunk 6 above)
Comment (nrmancuso) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java:650]: The existing name tells me everything except for what this method actually does 😂

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java (hunk 9 above)
Comment (nrmancuso) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java:634]: I don’t know why it matters.

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java (hunk 10 above)
[the remark this answers is not in the document]
Comment (nrmancuso) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java:681]: Why can’t it be general? This is my point.

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java (hunk 9 above)
Comment (romani) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java:634]: It is very specific method with very specific implementation

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java (hunk 10 above)
[the remark this answers is not in the document]
Comment (romani) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java:681]: We have no goal to make it general now, if someone wants, he can improve it to be general in separate PR, but current implementation is limited.

**Comment by nrmancuso** [comment]
I've left my review, @romani do with it what you will

**Comment by romani** [comment]
@kkoutsilis , please apply suggestions from @nrmancuso.

**Comment by kkoutsilis** [comment]
> @kkoutsilis , please apply suggestions from @nrmancuso.

Hey @romani, will look into it hopefully this weekend

**Comment by kkoutsilis** [comment]
Hey @romani, I believe I renamed all the methods as @nrmancuso suggested. Sorry for any inconvenience this PR has caused. If there are further changes required please let me know and I will try to apply as soon as I can. I have limited time for the next week or so.

**Review by romani — APPROVED** [review]

**Review by nrmancuso — APPROVED** [review]
Good stuff @kkoutsilis, thanks a lot for your contribution
