### PR TITLE
Issue #12020: False positive in RightCurly with 'alone_or_singleline'

### LINKED ISSUE #12020: False positive in RightCurly with 'alone_or_singleline' RightCurlyOption in try/catch
I have read check documentation: https://checkstyle.org/checks/blocks/rightcurly.html#RightCurly

Related documentation: https://checkstyle.org/property_types.html#RightCurlyOption

From `alone_or_singleline`:
> The brace must be alone on the line, yet single-line format of block is allowed. 

I have downloaded the latest checkstyle from: https://checkstyle.org/cmdline.html#Download_and_Run
I have executed the cli and showed it below, as cli describes the problem better than 1,000 words

```bash
/var/tmp $ javac RCurlyTest.java

/var/tmp $ cat config.xml
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
    "-//Checkstyle//DTD Checkstyle Configuration 1.3//EN"
    "https://checkstyle.org/dtds/configuration_1_3.dtd">

<module name="Checker">
    <property name="severity" value="error"/>
    <property name="tabWidth" value="4"/>
    <property name="fileExtensions" value="java, properties, xml"/>

    <module name="TreeWalker">
        <module name="RightCurly">
            <property name="option" value="alone_or_singleline"/>
        </module>
    </module>
</module>

/var/tmp $ cat RCurlyTest.java
public class RCurlyTest {
	public static void main(String args[]) {
		try { System.out.println(args[0]); } catch (Exception e) {}
	}
}

/var/tmp $ RUN_LOCALE="-Duser.language=en -Duser.country=US"
/var/tmp $ java $RUN_LOCALE -jar checkstyle-10.3.1-all.jar -c config.xml RCurlyTest.java
Starting audit...
[ERROR] [...]/RCurlyTest.java:3:44: '}' at column 38 should be alone on a line. [RightCurly]
Audit done.
Checkstyle ends with 1 errors.
```
---

**Describe what you expect in detail.**

Since the whole try..catch construct is in a single line, I expect the RightCurly test to pass (i.e. no errors raised).

As a side-note. Column number in the error message seems to be wrong when tabs are used in the source file. In the above example you can see that:

 * RCurlyTest.java:3:44 is correct and honours the top level tabWidth property in the config.xml file
 * However the message incorrectly refers to "column 38"

### PR DESCRIPTION
**Pull request by mahfouz72**
Resolves #12020:  
tryBlock at single line was raising a violation in `ALONE_OR_SINGLELINE`  option

Diff Regression config: https://gist.githubusercontent.com/mahfouz72/b3282ceb40c5ca4a56ede9f6c5194a3f/raw/bb787f9f9d73023e38b43faae582a6e4f9d6d20d/rightcurly.xml

[report](https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/9179d1b_2024114344/reports/diff/index.html) expected difference. violation has been removed for all single line try-catch blocks when `ALONE_OR_SINGLELINE`  option

### CODE REVIEW

File: src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/rightcurly/InputRightCurlyTryWithResourceAloneSingle.java [hunk 1]
```diff
@@ -31,9 +31,6 @@ void test() throws IOException {
         try (BufferedReader br1 = new BufferedReader(null);
                 BufferedReader br2 = new BufferedReader(br1)) { ; }
         catch (IOException e) { ; }
-        try (BufferedReader br1 = new BufferedReader(null);
-                // violation below ''}' at column 64 should be alone on a line'
-                BufferedReader br2 = new BufferedReader(br1)) {} catch (IOException e) { ; }
```
Comment (mahfouz72) [inline src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/rightcurly/InputRightCurlyTryWithResourceAloneSingle.java:36]: Is this supposed to be a violation and not treated as one block in a single line? because after my changes the check detects this as a single block on a line so, no violation. all the similar cases for other tokens are not detected as violation also examples:

```
PS D:\test> cat config.xml
<?xml version="1.0"?>
    <property name="charset" value="UTF-8"/>

 <module name="TreeWalker">
        <module name="RightCurly">
            <property name="option" value="alone_or_singleline"/>
        </module>
    </module>
</module>
PS D:\test> cat src/Test.java
public class Test {

    public static void main(String[] args) {
        if (true
                && false ) { } else { }

        do {int a = 5;
        int x = 7;
        int m = 3;} while (true);
    }
    public int add (int n
            , int m
            , int x) {  return n + m + x;}
}

PS D:\test> java  -jar checkstyle-10.13.0-all.jar -c config.xml src/Test.java
Starting audit...
Audit done.
PS D:\test> 

```
so if these cases are supposed to be a violation. I can fix it but in this PR? or open new issue

**Comment by mahfouz72** [comment]
Github, generate report

File: src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/rightcurly/InputRightCurlyTestAloneOrSingleline.java [hunk 2]
```diff
@@ -10,6 +10,9 @@
 
 package com.puppycrawl.tools.checkstyle.checks.blocks.rightcurly;
 
+import java.io.BufferedReader;
+import java.io.IOException;
+
 public class InputRightCurlyTestAloneOrSingleline {
```
Comment (rnveach) [inline src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/rightcurly/InputRightCurlyTestAloneOrSingleline.java:16]: Move new test to a whole new file. We don't like modifying existing tests and causing line differences.

File: src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/rightcurly/InputRightCurlyTryWithResourceAloneSingle.java (hunk 1 above)
Comment (rnveach) [inline src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/rightcurly/InputRightCurlyTryWithResourceAloneSingle.java:36]: Test input code should not be removed. It should stay as is, and either be a violation or not.

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/blocks/RightCurlyCheck.java [hunk 3]
```diff
@@ -328,9 +328,12 @@ private static boolean isBlockAloneOnSingleLine(Details details) {
             nextToken = Details.getNextToken(nextToken);
         }
 
-        if (nextToken != null && nextToken.getType() == TokenTypes.DO_WHILE) {
-            final DetailAST doWhileSemi = nextToken.getParent();
-            nextToken = Details.getNextToken(doWhileSemi);
+        if (nextToken != null && (nextToken.getType() == TokenTypes.DO_WHILE
+                || nextToken.getType() == TokenTypes.LITERAL_FINALLY
+                || nextToken.getType() == TokenTypes.LITERAL_CATCH)) {
+
```
Comment (rnveach) [inline src/main/java/com/puppycrawl/tools/checkstyle/checks/blocks/RightCurlyCheck.java:334]: Remove empty line.

**Review by rnveach — CHANGES_REQUESTED** [review]

File: src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/rightcurly/InputRightCurlyTryWithResourceAloneSingle.java (hunk 1 above)
Comment (rnveach) [reply src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/rightcurly/InputRightCurlyTryWithResourceAloneSingle.java:36]: This is alone or singleline. The try isn't a single line obviously, but is it alone? If it is alone, then no violation is expected.

> alone 	The brace must be alone on the line.

This does not look to be alone, so a violation is expected IMO.

**Comment by rnveach** [comment]
https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/9179d1b_2024114344/reports/diff/apache-ant/index.html#A1
https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/9179d1b_2024114344/reports/diff/apache-ant/xref/home/runner/work/checkstyle/checkstyle/.ci-temp/contribution/checkstyle-tester/repositories/apache-ant/src/tests/junit/org/apache/tools/ant/taskdefs/optional/EchoPropertiesTest.java.html#L236

The option is alone or single line. I am expecting no violations if the code is EITHER on a single line or if its right curly is alone. Everything on this one line looks to be on a single line.

This looks like what is reported in issue unless I am missing something.

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/blocks/RightCurlyCheck.java (hunk 3 above)
Comment (mahfouz72) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/blocks/RightCurlyCheck.java]: @rnveach done

File: src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/rightcurly/InputRightCurlyTryWithResourceAloneSingle.java (hunk 1 above)
Comment (mahfouz72) [reply src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/rightcurly/InputRightCurlyTryWithResourceAloneSingle.java:36]: @rnveach done

File: src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/rightcurly/InputRightCurlyTestAloneOrSingleline.java (hunk 2 above)
Comment (mahfouz72) [reply src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/rightcurly/InputRightCurlyTestAloneOrSingleline.java]: done

File: src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/rightcurly/InputRightCurlyTryWithResourceAloneSingle.java (hunk 1 above)
Comment (mahfouz72) [reply src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/rightcurly/InputRightCurlyTryWithResourceAloneSingle.java]:
```
private static boolean isBlockAloneOnSingleLine(Details details) {
       .......
        return TokenUtil.areOnSameLine(details.lcurly, details.rcurly)
            && (nextToken == null || !TokenUtil.areOnSameLine(details.rcurly, nextToken)
                || isRightcurlyFollowedBySemicolon(details));
    }
```
this is the code to detect a single block in a line it is checking if the rcurly and lcurly in single line and the rcurly and the next token is not in the same line

so in this case 
```
try( x = 5;
                 y = 6) {} catch {}
                           l r
```
the rcurly and lcurly on same line so single block in a line

Comment (mahfouz72) [reply src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/rightcurly/InputRightCurlyTryWithResourceAloneSingle.java]: the reason for this was detected as a violation before because the check wasn't even try to  detect try-catch block as block in a single line but this is not the case now as after this PR the check detect it as a single line so no violation

Comment (mahfouz72) [reply src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/rightcurly/InputRightCurlyTryWithResourceAloneSingle.java]: I will open a new issue for this as this problem is not a part of the issue

Comment (rnveach) [reply src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/rightcurly/InputRightCurlyTryWithResourceAloneSingle.java]: I don't know what I am being pinged in this section for.

**Review by rnveach — APPROVED** [review]

File: src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/rightcurly/InputRightCurlyTryWithResourceAloneSingle.java (hunk 1 above)
Comment (mahfouz72) [reply src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/rightcurly/InputRightCurlyTryWithResourceAloneSingle.java]: to review the new issue if it should be approved

Comment (rnveach) [reply src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/rightcurly/InputRightCurlyTryWithResourceAloneSingle.java]: I don't review issues for approval. That is @romani

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/blocks/RightCurlyCheck.java [hunk 4]
```diff
@@ -328,9 +328,11 @@ private static boolean isBlockAloneOnSingleLine(Details details) {
             nextToken = Details.getNextToken(nextToken);
         }
 
-        if (nextToken != null && nextToken.getType() == TokenTypes.DO_WHILE) {
-            final DetailAST doWhileSemi = nextToken.getParent();
-            nextToken = Details.getNextToken(doWhileSemi);
+        if (nextToken != null && (nextToken.getType() == TokenTypes.DO_WHILE
+                || nextToken.getType() == TokenTypes.LITERAL_FINALLY
+                || nextToken.getType() == TokenTypes.LITERAL_CATCH)) {
```
Comment (nrmancuso) [inline src/main/java/com/puppycrawl/tools/checkstyle/checks/blocks/RightCurlyCheck.java:333]: Let's do a favor for the next person to come across this code: please extract these tokens to some descriptively named collection, and do something like this:
```suggestion
        final int[] myAwesomeCollection = {TokenTypes.DO_WHILE, ...};
        if (TokenUtil.isOfType(nextToken, myAwesomeCollection) {
```

I am wondering why there isn't more tokens in this condition (LITERAL_FOR, LITERAL_IF, etc.), so it would be good to point it out by the name of this collection.

**Review by nrmancuso — CHANGES_REQUESTED** [review]
Item:

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/blocks/RightCurlyCheck.java (hunk 4 above)
Comment (mahfouz72) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/blocks/RightCurlyCheck.java:333]: > please extract these tokens to some descriptively named collection,

@nrmancuso done I like this update but I am not sure what descriptive name could be nothing on my mind. we just checking this tokens as we have  to get parent first before getting the next token so ...? 🤔 




> I am wondering why there isn't more tokens in this condition

yea I was wondering the same but I analyzed it and it turned out that if the next token is IF or for then it is ok we don't need to update it as it will never be a second of block of related group of blocks ( no relation between If and for and its previous tokens) 
but in case that let's say the next token is a catch (the current token is try) then we have update the next token to be the one after the catch as try-catch block is treated as one block in alone or single line option consider this
```
try{ }catch{ }
```
when we want to validate that try is a block on single line we have to check that is not in the same line with the next token to its next token (it may be method braces or something else)
but consider` for( ... ) if( )` no relation between this two and they can't both be considered as block alone on single line so that's why if the next token is If or for we leave it as it is and not get its next token

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/blocks/RightCurlyCheck.java [hunk 5]
```diff
@@ -328,9 +328,10 @@ private static boolean isBlockAloneOnSingleLine(Details details) {
             nextToken = Details.getNextToken(nextToken);
         }
 
-        if (nextToken != null && (nextToken.getType() == TokenTypes.DO_WHILE
-                || nextToken.getType() == TokenTypes.LITERAL_FINALLY
-                || nextToken.getType() == TokenTypes.LITERAL_CATCH)) {
+        final int[] tokensToCheck = {
+            TokenTypes.DO_WHILE, TokenTypes.LITERAL_FINALLY, TokenTypes.LITERAL_CATCH,
+        };
+        if (TokenUtil.isOfType(nextToken, tokensToCheck)) {
```
Comment (nrmancuso) [inline src/main/java/com/puppycrawl/tools/checkstyle/checks/blocks/RightCurlyCheck.java:334]:
```suggestion
        // sibling tokens should be allowed on a single line
        final int[] tokensWithBlockSibling = {
            TokenTypes.DO_WHILE,
            TokenTypes.LITERAL_FINALLY,
            TokenTypes.LITERAL_CATCH,
        };
        
        if (TokenUtil.isOfType(nextToken, tokensWithBlockSibling)) {
```

**Review by nrmancuso — CHANGES_REQUESTED** [review]
Last item:

**Comment by nrmancuso** [comment]
Github, generate report

**Review by nrmancuso — APPROVED** [review]
Thank you very much @mahfouz72 !!
