### PR TITLE
Issue #15034: Add new input file for pattern matching for switch in N…

### LINKED ISSUE #15034: Add Check Support for Java 21 Pattern Matching for Switch Syntax: NeedBraces
child of https://github.com/checkstyle/checkstyle/issues/14961

I have read check documentation: https://checkstyle.org/checks/blocks/needbraces.html
I have downloaded the latest checkstyle from: https://checkstyle.org/cmdline.html#Download_and_Run
I have executed the cli and showed it below, as cli describes the problem better than 1,000 words

```
PS D:\CS\test> cat config.xml                                                   
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
        "-//Puppy Crawl//DTD Check Configuration 1.3//EN"
        "http://www.puppycrawl.com/dtds/configuration_1_3.dtd">
<module name="Checker">
    <property name="charset" value="UTF-8"/>
    <module name="TreeWalker">
        <module name="NeedBraces">
            <property name="tokens" value="LITERAL_CASE, LITERAL_DEFAULT"/>
        </module>
    </module>
</module>
PS D:\CS\test> cat src/Test.java                                                
record ColoredPoint(int p, int x, String c) { }
record Rectangle(ColoredPoint upperLeft, ColoredPoint lowerRight) { }

public class Test {

    void test(Object obj) {
        switch (obj) {
            case ColoredPoint(_, _, _):
            case Rectangle(_, _) : // violation
                break;
            default : // expected violation
        }
        switch (obj) {
            case ColoredPoint(int x, _, _) when (x >= 2)   // violation
                    :
                break;
            case ColoredPoint(int x, _, _)    // violation
                    when(x >= 2) :
                break;
            case ColoredPoint(int x, _, _)
                    when(x >= 2) : {}
            break;
            default :   // expected violation
        }
        switch (obj) {
            case ColoredPoint(int x, _, _) when (x >= 2) // violation
                    -> throw new RuntimeException();
            case ColoredPoint(int x, _, _)
                    when(x >= 2) -> {}
            default -> throw new RuntimeException();  // violation
        }
    }
}
PS D:\CS\test> java  -jar checkstyle-10.17.0-all.jar -c config.xml src/Test.java
Starting audit...
[ERROR] D:\CS\test\src\Test.java:9:13: 'case' construct must use '{}'s. [NeedBraces]
[ERROR] D:\CS\test\src\Test.java:14:13: 'case' construct must use '{}'s. [NeedBraces]
[ERROR] D:\CS\test\src\Test.java:17:13: 'case' construct must use '{}'s. [NeedBraces]
[ERROR] D:\CS\test\src\Test.java:26:13: 'case' construct must use '{}'s. [NeedBraces]
[ERROR] D:\CS\test\src\Test.java:30:13: 'default' construct must use '{}'s. [NeedBraces]
Audit done.
Checkstyle ends with 5 errors.
PS D:\CS\test> 

```

---
Describe what you want in detail

we are ok here. This can be closed or add an input file for cases with `when`

### PR DESCRIPTION
**Pull request by mahfouz72**
closes #15034

### CODE REVIEW

File: src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/blocks/needbraces/InputNeedBracesPatternMatchingForSwitch.java [hunk 1]
```diff
@@ -0,0 +1,100 @@
...
+
+            default :  // violation
+                yield 0;
+        };
+
+        int b =  switch (o) {
+            case Integer i when (i == 0) -> i;
+            case String s when(s.equals("a")) -> s.length();  // violation
+            case Point(int x, int y ) when(x>=0 && y >=0) ->  // violation
+                x + y;
```
Comment (mahfouz72) [inline src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/blocks/needbraces/InputNeedBracesPatternMatchingForSwitch.java:91]: 2 false positives, we can't have braces here, otherwise we need to introduce an unnecessary yield.

```Java
            case String s when(s.equals("a")) -> {s.length();} // non-compliant, Switch expression rule should produce result in all execution paths
            case String s when(s.equals("a")) -> {yield s.length();} // compliant but unnecessary yield
```

interesting that line 88 is ok (and this is expected) while line 89 and 90 is violations

Comment (mahfouz72) [reply src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/blocks/needbraces/InputNeedBracesPatternMatchingForSwitch.java:91]: https://github.com/checkstyle/checkstyle/pull/15321#discussion_r1684288238

Comment (mahfouz72) [reply src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/blocks/needbraces/InputNeedBracesPatternMatchingForSwitch.java]: added until comment

File: src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/blocks/needbraces/InputNeedBracesPatternMatchingForSwitch.java [hunk 2]
```diff
@@ -0,0 +1,101 @@
...
+                break;
+            }
+            case String s when(s.equals("a")) : {
+                System.out.println("a");
+                break;
+            }
+            case Point(int x, int y ) when(x>=0 && y >=0) : {
+                System.out.println("point");
+                break;
+                }
```
Comment (nrmancuso) [inline src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/blocks/needbraces/InputNeedBracesPatternMatchingForSwitch.java:44]: Please fix indentation here and anywhere else.

File: src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/blocks/needbraces/InputNeedBracesPatternMatchingForSwitch.java [hunk 3]
```diff
@@ -0,0 +1,101 @@
...
+         switch (o) {
+            case Integer i when (i == 0) : {
+                System.out.println("zero");
+                break;
+            }
+            case String s when(s.equals("a")) : {
+                System.out.println("a");
+                break;
+            }
+            case Point(int x, int y ) when(x>=0 && y >=0) : {
```
Comment (nrmancuso) [inline src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/blocks/needbraces/InputNeedBracesPatternMatchingForSwitch.java:41]:
```suggestion
            case Point(int x, int y ) when (x>=0 && y >=0) : {
```
Please fix all of these

File: src/test/java/com/puppycrawl/tools/checkstyle/checks/blocks/NeedBracesCheckTest.java [hunk 4]
```diff
@@ -276,4 +276,47 @@ public void testNeedBracesSwitchExpression() throws Exception {
...
+            "90:13: " + getCheckMessage(MSG_KEY_NEED_BRACES, "case"),
+            "91:13: " + getCheckMessage(MSG_KEY_NEED_BRACES, "case"),
+        };
+        verifyWithInlineConfigParser(
+                getNonCompilablePath("InputNeedBracesPatternMatchingForSwitch.java"),
+            expected);
+    }
+
+    @Test
+    public void testPatternMatchingForSwitch2() throws Exception {
```
Comment (nrmancuso) [inline src/test/java/com/puppycrawl/tools/checkstyle/checks/blocks/NeedBracesCheckTest.java:303]: Please never do this; test names should do a good job of describing what we are testing; we can draw inspiration from configurations, specific code under test, etc.

File: src/test/java/com/puppycrawl/tools/checkstyle/checks/blocks/NeedBracesCheckTest.java [hunk 5]
```diff
@@ -276,4 +276,47 @@ public void testNeedBracesSwitchExpression() throws Exception {
...
+            "55:13: " + getCheckMessage(MSG_KEY_NEED_BRACES, "case"),
+            "58:13: " + getCheckMessage(MSG_KEY_NEED_BRACES, "case"),
+            "61:13: " + getCheckMessage(MSG_KEY_NEED_BRACES, "default"),
+            "74:13: " + getCheckMessage(MSG_KEY_NEED_BRACES, "case"),
+            "80:13: " + getCheckMessage(MSG_KEY_NEED_BRACES, "case"),
+            "83:13: " + getCheckMessage(MSG_KEY_NEED_BRACES, "default"),
+            "90:13: " + getCheckMessage(MSG_KEY_NEED_BRACES, "case"),
+        };
+        verifyWithInlineConfigParser(
+                getNonCompilablePath("InputNeedBracesPatternMatchingForSwitch2.java"),
```
Comment (nrmancuso) [inline src/test/java/com/puppycrawl/tools/checkstyle/checks/blocks/NeedBracesCheckTest.java:318]: Same for file naming, it should be consistent with the test method name.

**Review by nrmancuso — CHANGES_REQUESTED** [review]
Items:

File: src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/blocks/needbraces/InputNeedBracesPatternMatchingForSwitch.java (hunk 2 above)
Comment (mahfouz72) [reply src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/blocks/needbraces/InputNeedBracesPatternMatchingForSwitch.java]: done

File: src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/blocks/needbraces/InputNeedBracesPatternMatchingForSwitch.java (hunk 3 above)
Comment (mahfouz72) [reply src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/blocks/needbraces/InputNeedBracesPatternMatchingForSwitch.java]: done

File: src/test/java/com/puppycrawl/tools/checkstyle/checks/blocks/NeedBracesCheckTest.java (hunk 4 above)
Comment (mahfouz72) [reply src/test/java/com/puppycrawl/tools/checkstyle/checks/blocks/NeedBracesCheckTest.java]: done

File: src/test/java/com/puppycrawl/tools/checkstyle/checks/blocks/NeedBracesCheckTest.java (hunk 5 above)
Comment (mahfouz72) [reply src/test/java/com/puppycrawl/tools/checkstyle/checks/blocks/NeedBracesCheckTest.java]: done

**Review by nrmancuso — APPROVED** [review]
