### PR TITLE
Issue #13012: fix loading with non-ascii symbols in path

### LINKED ISSUE #13012: Checkstyle fails with "Path contains invalid character" if path to config file contains non-ascii characters
If the config file is in a location that contains non-ascii characters, then checkstyle fails:

```bash
% ls
checkstyle-10.9.3-all.jar	checkstyle.xml
% cat checkstyle.xml 
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
  "-//Puppy Crawl//DTD Check Configuration 1.3//EN"
  "configuration_1_3.dtd">
<module name="Checker">
</module>
% mkdir a
% cp checkstyle.xml a
% java -jar checkstyle-10.9.3-all.jar -c a/checkstyle.xml .
Starting audit...
Audit done.
% mkdir æ
% cp checkstyle.xml æ
% java -jar checkstyle-10.9.3-all.jar -c æ/checkstyle.xml .
com.puppycrawl.tools.checkstyle.api.CheckstyleException: unable to parse configuration stream
	at com.puppycrawl.tools.checkstyle.ConfigurationLoader.loadConfiguration(ConfigurationLoader.java:324)
	at com.puppycrawl.tools.checkstyle.ConfigurationLoader.loadConfiguration(ConfigurationLoader.java:266)
	at com.puppycrawl.tools.checkstyle.Main.runCheckstyle(Main.java:380)
	at com.puppycrawl.tools.checkstyle.Main.runCli(Main.java:338)
	at com.puppycrawl.tools.checkstyle.Main.execute(Main.java:195)
	at com.puppycrawl.tools.checkstyle.Main.main(Main.java:130)
Caused by: com.sun.org.apache.xerces.internal.util.URI$MalformedURIException: Path contains invalid character: æ
	at java.xml/com.sun.org.apache.xerces.internal.util.URI.initializePath(URI.java:1110)
	at java.xml/com.sun.org.apache.xerces.internal.util.URI.initialize(URI.java:583)
	at java.xml/com.sun.org.apache.xerces.internal.util.URI.<init>(URI.java:336)
	at java.xml/com.sun.org.apache.xerces.internal.util.URI.<init>(URI.java:299)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLEntityManager.expandSystemIdStrictOff1(XMLEntityManager.java:2393)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLEntityManager.expandSystemId(XMLEntityManager.java:2239)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLEntityManager.resolveEntityAsPerStax(XMLEntityManager.java:996)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$DTDDriver.dispatch(XMLDocumentScannerImpl.java:1142)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$DTDDriver.next(XMLDocumentScannerImpl.java:1040)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$PrologDriver.next(XMLDocumentScannerImpl.java:943)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:605)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:534)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:888)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:824)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1216)
	at java.xml/com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:635)
	at com.puppycrawl.tools.checkstyle.XmlLoader.parseInputSource(XmlLoader.java:81)
	at com.puppycrawl.tools.checkstyle.ConfigurationLoader.parseInputSource(ConfigurationLoader.java:196)
	at com.puppycrawl.tools.checkstyle.ConfigurationLoader.loadConfiguration(ConfigurationLoader.java:315)
	... 5 more
Checkstyle ends with 1 errors.

```

I would have expected checkstyle to work the same, regardless of what characters were used in the path.

See also https://issues.apache.org/jira/browse/MCHECKSTYLE-425 , where Michael Osipov suggests it´s due to use of URI#toString where URI#toASCIIString should have been used.

------

From plugin issue:

While I can reproduce it, it is not a bug in maven plugin. The issue is with Checkstyle itself. Unfortunately, Sun – back then – decided to print gargabe output with URI#toString() instead of doing the right thing. #toString() produces invalid URIs. One must ALWAYS use #toASCIIString(). Never rely on #toString(). I checked the code of Checkstyle and it unfortunately does on many occasions. File an issue there and have it fixed.

Affected files:

Name	Line	Text	Path
AbstractAutomaticBean.java	24	 import java.net.URI;	D:\Entwicklung\Projekte\checkstyle\src\main\java\com\puppycrawl\tools\checkstyle
AbstractHeaderCheck.java	28	 import java.net.URI;	D:\Entwicklung\Projekte\checkstyle\src\main\java\com\puppycrawl\tools\checkstyle\checks\header
ImportControlCheck.java	22	 import java.net.URI;	D:\Entwicklung\Projekte\checkstyle\src\main\java\com\puppycrawl\tools\checkstyle\checks\imports
ImportControlLoader.java	25	 import java.net.URI;	D:\Entwicklung\Projekte\checkstyle\src\main\java\com\puppycrawl\tools\checkstyle\checks\imports
ConfigurationLoader.java	23	 import java.net.URI;	D:\Entwicklung\Projekte\checkstyle\src\main\java\com\puppycrawl\tools\checkstyle
SuppressionsLoader.java	24	 import java.net.URI;	D:\Entwicklung\Projekte\checkstyle\src\main\java\com\puppycrawl\tools\checkstyle\filters
PropertyCacheFile.java	29	 import java.net.URI;	D:\Entwicklung\Projekte\checkstyle\src\main\java\com\puppycrawl\tools\checkstyle
CommonUtil.java	28	 import java.net.URI;	D:\Entwicklung\Projekte\checkstyle\src\main\java\com\puppycrawl\tools\checkstyle\utils
See: https://github.com/apache/maven/commit/8e0efaa107c5dab09a9dc0a0405a3bfbebecda3b

### PR DESCRIPTION
**Pull request by strkkk**
Closes #13012

Attempt number 3 to fix this issue

### CODE REVIEW

File: src/test/java/com/puppycrawl/tools/checkstyle/ConfigurationLoaderTest.java [hunk 1]
```diff
@@ -654,6 +654,20 @@ public void testLoadConfigurationFromClassPath() throws Exception {
...
+        final DefaultConfiguration config =
+                (DefaultConfiguration) ConfigurationLoader.loadConfiguration(
+                    getResourcePath("æ£µ¥/InputConfigurationLoaderModuleIgnoreSeverity.xml"),
+                        new PropertiesExpander(new Properties()), IgnoredModulesOptions.OMIT);
+
+        final Configuration[] children = config.getChildren();
+        final int length = children[0].getChildren().length;
+        assertWithMessage("Invalid children count")
+            .that(length)
+            .isEqualTo(0);
```
Comment (romani) [inline src/test/java/com/puppycrawl/tools/checkstyle/ConfigurationLoaderTest.java:668]: This very confusing, why  0 is good signal of data loading from file.
Let's check module name, or fact that severity property is ignore.

**Review by romani — CHANGES_REQUESTED** [review]
The only point to improve

File: src/test/java/com/puppycrawl/tools/checkstyle/ConfigurationLoaderTest.java (hunk 1 above)
Comment (strkkk) [reply src/test/java/com/puppycrawl/tools/checkstyle/ConfigurationLoaderTest.java:668]: I copied from test right above it. And 5 more tests with same assertion (children count is zero)
So it makes more sense to fix it in separate issue/commit/PR, since it is not relevant to this issue.

Imo it is not confusing, it means that file content is irrelevant, the only thing that matters is the fact that it was loaded without errors.

Comment (romani) [reply src/test/java/com/puppycrawl/tools/checkstyle/ConfigurationLoaderTest.java:668]: We should not have tests that don't care about content.
Let's break this bad practice of pure unit testing and simply run some validation on some Check and get any violation. In this case we will just be sure, whole checkstyle process works.

Comment (strkkk) [reply src/test/java/com/puppycrawl/tools/checkstyle/ConfigurationLoaderTest.java:668]: > Let's break this bad practice of pure unit testing and simply run some validation on some Check and get any violation. In this case we will just be sure, whole checkstyle process works.

Sorry, but that does not make any sense to me. This UT class is for testing configuration loader. **All** its tests test loading of the configuration and just verify presence of some nodes. From this point of view verification of the empty content is also a perfectly valid use case.

What you are talking about is a kind of end-to-end testing, not UT for specific class.

Comment (romani) [reply src/test/java/com/puppycrawl/tools/checkstyle/ConfigurationLoaderTest.java:668]: >All its tests test loading of the configuration and just verify presence of some nodes. From this point of view verification of the empty content is also a perfectly valid use case.

This two sentences contradict to each other.

If start in partial integration target of test - we should load config and briefly verify that content is loaded, severity=ignore is seen.
Or we just reuse end-to-end model and show that all is working for user.

Comment (strkkk) [reply src/test/java/com/puppycrawl/tools/checkstyle/ConfigurationLoaderTest.java:668]: > we just reuse end-to-end model and show that all is working for user

Once again, this does not make sense. This is UT for ConfigurationLoader, which is supposed to test configuration loading, not how whole checkstyle works.

> This two sentences contradict to each other.

They are not. Loading of the empty config can happen, this input is completely valid and accepted by code. So, code should be able to work with empty file and produce no error and empty configuration. Why I should not test the valid input and verify the result? who knows, may be empty config will produce some unexpected stuff in config?

> we should load config and briefly verify that content is loaded

This is exactly what happens here. No checks/filters in file - no nodes in config. The point is to check that loading completes without an exception.
If it makes you feel better, I can replace it with something like

```
        final Properties expectedPropertyValues = new Properties();
        expectedPropertyValues.setProperty("tabWidth", "2");
        expectedPropertyValues.setProperty("basedir", ".");
        expectedPropertyValues.setProperty("charset", "ASCII");
        verifyConfigNode(config, "Checker", 0, expectedPropertyValues);
```

Comment (romani) [reply src/test/java/com/puppycrawl/tools/checkstyle/ConfigurationLoaderTest.java:668]: I missing a point why not Check in config:
image

Comment (romani) [reply src/test/java/com/puppycrawl/tools/checkstyle/ConfigurationLoaderTest.java:668]: > IgnoredModulesOptions.OMIT);

please use different value EXECUTE.
and please check that in config we have MemberName with property.

File: src/test/java/com/puppycrawl/tools/checkstyle/utils/CommonUtilTest.java [hunk 2]
```diff
@@ -576,6 +576,14 @@ public void testIsCodePointWhitespace() {
                 .isFalse();
     }
 
+    @Test
+    public void testIsCreatingInputSourceFromFilename()
+            throws CheckstyleException {
+        final String filename =
+            "/" + getPackageLocation() + "/InputCommonUtilTest_empty_checks.xml";
+        assertThat(CommonUtil.sourceFromFilename(filename)).isNotNull();
```
Comment (romani) [inline src/test/java/com/puppycrawl/tools/checkstyle/utils/CommonUtilTest.java:584]: we discourage all pure unit test as much as possible.
Ideally we should have no of them, if any is required due to inability to test by upper level of classes, we need a comment that explains reason in details.

what tool force you to have it ?

**Review by romani — CHANGES_REQUESTED** [review]
items:

File: src/main/java/com/puppycrawl/tools/checkstyle/utils/CommonUtil.java [hunk 3]
```diff
@@ -593,5 +608,4 @@ public static boolean isCodePointWhitespace(int[] codePoints, int index) {
         final char character = Character.toChars(codePoints[index])[0];
         return Character.isWhitespace(character);
     }
-
```
Comment (romani) [inline src/main/java/com/puppycrawl/tools/checkstyle/utils/CommonUtil.java:596]: please restore it, we do not have Check for this, but all other classes have it, I do not remember why, but I like this extra space.

**Review by romani — CHANGES_REQUESTED** [review]
items:

File: src/test/java/com/puppycrawl/tools/checkstyle/ConfigurationLoaderTest.java (hunk 1 above)
Comment (strkkk) [reply src/test/java/com/puppycrawl/tools/checkstyle/ConfigurationLoaderTest.java]: I changed it to verify node

File: src/test/java/com/puppycrawl/tools/checkstyle/utils/CommonUtilTest.java (hunk 2 above)
Comment (strkkk) [reply src/test/java/com/puppycrawl/tools/checkstyle/utils/CommonUtilTest.java]: I dont remember, I removed it, lets see if something fails

File: src/main/java/com/puppycrawl/tools/checkstyle/utils/CommonUtil.java (hunk 3 above)
Comment (strkkk) [reply src/main/java/com/puppycrawl/tools/checkstyle/utils/CommonUtil.java]: done
