### PR TITLE
Issue #13988: Support unnamed variables

### LINKED ISSUE #13988: Checkstyle fails to parse unnamed variable
Reading: https://openjdk.org/jeps/456#:~:text=An%20unnamed%20variable%20is%20declared,parameter%20in%20a%20lambda%20expression.

> Summary
Enhance the Java programming language with unnamed variables and unnamed patterns, which can be used when variable declarations or nested patterns are required but never used. Both are denoted by the underscore character, _.

Example:
```bash
➜  src cat UnnamedVariable.java                        
public class UnnamedVariable {
    record R(int x) {}
    void m(Object o) {
        if (o instanceof R(_)) {}
    }
}
➜  src javac --release 21 --enable-preview UnnamedVariable.java 
Note: UnnamedVariable.java uses preview features of Java SE 21.
Note: Recompile with -Xlint:preview for details.
➜  src java -jar checkstyle-10.12.3-all.jar -t UnnamedVariable.java 
com.puppycrawl.tools.checkstyle.api.CheckstyleException: IllegalStateException occurred while parsing file /home/nick/IdeaProjects/tester/src/UnnamedVariable.java.
        at com.puppycrawl.tools.checkstyle.JavaParser.parse(JavaParser.java:105)
        at com.puppycrawl.tools.checkstyle.JavaParser.parseFileText(JavaParser.java:122)
        at com.puppycrawl.tools.checkstyle.JavaParser.parseFile(JavaParser.java:142)
        at com.puppycrawl.tools.checkstyle.AstTreeStringPrinter.printFileAst(AstTreeStringPrinter.java:65)
        at com.puppycrawl.tools.checkstyle.Main.runCli(Main.java:291)
        at com.puppycrawl.tools.checkstyle.Main.execute(Main.java:195)
        at com.puppycrawl.tools.checkstyle.Main.main(Main.java:130)
Caused by: java.lang.IllegalStateException: 4:26: mismatched input '(' expecting ')'
        at com.puppycrawl.tools.checkstyle.JavaParser$CheckstyleErrorListener.syntaxError(JavaParser.java:255)
        at org.antlr.v4.runtime.ProxyErrorListener.syntaxError(ProxyErrorListener.java:41)
        at org.antlr.v4.runtime.Parser.notifyErrorListeners(Parser.java:544)
        at org.antlr.v4.runtime.DefaultErrorStrategy.reportInputMismatch(DefaultErrorStrategy.java:327)
        at org.antlr.v4.runtime.DefaultErrorStrategy.reportError(DefaultErrorStrategy.java:139)
        at com.puppycrawl.tools.checkstyle.CheckstyleParserErrorStrategy.recoverInline(CheckstyleParserErrorStrategy.java:38)
        at org.antlr.v4.runtime.Parser.match(Parser.java:208)
        at com.puppycrawl.tools.checkstyle.grammar.java.JavaLanguageParser.parExpression(JavaLanguageParser.java:8753)
        at com.puppycrawl.tools.checkstyle.grammar.java.JavaLanguageParser.statement(JavaLanguageParser.java:6769)
        at com.puppycrawl.tools.checkstyle.grammar.java.JavaLanguageParser.blockStatement(JavaLanguageParser.java:6198)
        at com.puppycrawl.tools.checkstyle.grammar.java.JavaLanguageParser.block(JavaLanguageParser.java:6101)
        at com.puppycrawl.tools.checkstyle.grammar.java.JavaLanguageParser.methodBody(JavaLanguageParser.java:2940)
        at com.puppycrawl.tools.checkstyle.grammar.java.JavaLanguageParser.methodDeclaration(JavaLanguageParser.java:2898)
        at com.puppycrawl.tools.checkstyle.grammar.java.JavaLanguageParser.memberDeclaration(JavaLanguageParser.java:2745)
        at com.puppycrawl.tools.checkstyle.grammar.java.JavaLanguageParser.classBodyDeclaration(JavaLanguageParser.java:2671)
        at com.puppycrawl.tools.checkstyle.grammar.java.JavaLanguageParser.classBody(JavaLanguageParser.java:2477)
        at com.puppycrawl.tools.checkstyle.grammar.java.JavaLanguageParser.classDeclaration(JavaLanguageParser.java:1096)
        at com.puppycrawl.tools.checkstyle.grammar.java.JavaLanguageParser.types(JavaLanguageParser.java:753)
        at com.puppycrawl.tools.checkstyle.grammar.java.JavaLanguageParser.typeDeclaration(JavaLanguageParser.java:667)
        at com.puppycrawl.tools.checkstyle.grammar.java.JavaLanguageParser.compilationUnit(JavaLanguageParser.java:414)
        at com.puppycrawl.tools.checkstyle.JavaParser.parse(JavaParser.java:99)
        ... 6 more
Caused by: org.antlr.v4.runtime.InputMismatchException
        ... 22 more
Checkstyle ends with 1 errors.



```

### PR DESCRIPTION
**Pull request by nrmancuso**
Closes #13988

Link to spec: https://docs.oracle.com/javase/specs/jls/se21/preview/specs/unnamed-jls.html

Variable declarator grammar update:
```
VariableDeclaratorId:
    Identifier [Dims]
    _
```

Some important points regarding unnamed variables: 

>The keyword `_` (underscore) may be used in declarations in place of an identifier ([6.1](https://docs.oracle.com/javase/specs/jls/se21/preview/specs/unnamed-jls.html#jls-6.1)).

>If a declaration does not include an identifier, but instead includes the reserved keyword _ (underscore), then the entity cannot be referred to by name. The following kinds of entity may be declared using an underscore...

In order to maintain backwards compatibility and and avoid a massive amount of check updates, we will allow this token to be an identifier value only. For any checks in the future that we want to add support to for explicitly checking unnamed variables, it is simple to just verify that a given identifier matches `_`.

---------------------------------

Pattern component grammar has changed:
```
ComponentPatternList:
    ComponentPattern { , ComponentPattern }

ComponentPattern:
    Pattern
    UnnamedPattern

UnnamedPattern:
_

```

Some important points regarding unnamed pattern variables:
>A type pattern declares exactly one pattern variable. This pattern variable may be an unnamed pattern variable (denoted by` _`)...

Since the `_` in this case represents a pattern (which would otherwise be comprised of multiple tokens), we will introduce a new token, `UNNAMED_PATTERN_DEF`.

--------------------------------------

Switch label grammar has changed:
```
SwitchLabel:
    case CaseConstant {, CaseConstant}
    case null [, default]
    case CasePattern{, CasePattern } [ Guard ] <-- multiple case patterns are allowed now, as long as they use unnamed variables
    default
```

### CODE REVIEW

**Comment by nrmancuso** [comment]
We can begin review while I battle with checker.

**Comment by rnveach** [comment]
Good luck on your battle. Hope you win. :)

File: src/test/java/com/puppycrawl/tools/checkstyle/grammar/GeneratedJavaTokenTypesTest.java [hunk 1]
```diff
@@ -746,7 +752,7 @@ public void testTokenNumbering() {
                         + " 'GeneratedJavaTokenTypesTest' and verified"
                         + " that their old numbering didn't change")
             .that(tokenCount)
-            .isEqualTo(235);
+            .isEqualTo(237);
```
Comment (rnveach) [inline src/test/java/com/puppycrawl/tools/checkstyle/grammar/GeneratedJavaTokenTypesTest.java:755]: Nothing to do with your changes, but why is the count off by 12? Maybe we should add a note about missing numbers.

File: src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java [hunk 2]
```diff
@@ -6743,6 +6743,74 @@ public final class TokenTypes {
     public static final int EMBEDDED_EXPRESSION_END =
             JavaLanguageLexer.EMBEDDED_EXPRESSION_END;
 
+    /**
+     * The {@code _} reserved keyword. Appears as part of a variable definition in
+     * place of an identifier value, and is not used as a token type explicitly. This
+     * is to maintain backwards compatibility with older versions of Java that considered
+     * {@code _} to be a valid identifier. There is no reason to use this token type
+     * directly.
```
Comment (rnveach) [inline src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java:6751]: This makes me question why we are even adding this token to the public list and just don't want to hide this token away from the world. It looks like we already hide it from the AST display (please onfirm), so why even show this?

**Comment by rnveach** [comment]
I am also not seeing regression. We should at the least do antlr regression.

**Comment by nrmancuso** [comment]
> I am also not seeing regression. We should at the least do antlr regression.
I will be generating all reports, just wanted to make sure we are good with the AST

**Comment by rnveach** [comment]
I personally don't see any issues with the antlr.

File: src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java (hunk 2 above)
Comment (nrmancuso) [reply src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java:6751]: Good point, I will remove this :)

File: src/test/java/com/puppycrawl/tools/checkstyle/grammar/GeneratedJavaTokenTypesTest.java (hunk 1 above)
Comment (nrmancuso) [reply src/test/java/com/puppycrawl/tools/checkstyle/grammar/GeneratedJavaTokenTypesTest.java:755]: It's mostly in the test method below.

Comment (rnveach) [reply src/test/java/com/puppycrawl/tools/checkstyle/grammar/GeneratedJavaTokenTypesTest.java:755]: You referring to the 10 tokens in https://github.com/checkstyle/checkstyle/blob/b54de1e5de66de289ee52f6ad60067a116264c4e/src/test/java/com/puppycrawl/tools/checkstyle/grammar/GeneratedJavaTokenTypesTest.java#L765 ?

Comment (nrmancuso) [reply src/test/java/com/puppycrawl/tools/checkstyle/grammar/GeneratedJavaTokenTypesTest.java:755]: That, plus there’s at least one “placeholder” token in the lexer that’s had to take the place of some autogenerated tokens in ANTLR2  that don’t exist anymore. Let me find some links.

**Comment by nrmancuso** [comment]
@romani  please share your thoughts on AST before I generate reports

File: src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/grammar/java21/InputUnnamedVariableBasic.java [hunk 3]
```diff
@@ -0,0 +1,69 @@
...
+
+        p1.run(1, 2);
+        p2.run(1, 2);
+        p3.run(1, 2);
+        p4.run(1, 2);
+        p5.run(1, 2);
+
+        R r = new R(null);
+        if (r instanceof R _) {}
+        if (r instanceof R(_)) {}
```
[the remark this answers is not in the document]
Comment (romani) [reply src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/grammar/java21/InputUnnamedVariableBasic.java:37]: can we avoid new token and have:
```
|--RECORD_PATTERN_COMPONENTS
|   `--PATTERN_VARIABLE_DEF
|       `--IDENT -> _
```

[the remark this answers is not in the document]
Comment (nrmancuso) [reply src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/grammar/java21/InputUnnamedVariableBasic.java:37]: > can we avoid new token? and have:
> 
> ```
> |--RECORD_PATTERN_COMPONENTS
> |   `--PATTERN_VARIABLE_DEF
> |       `--IDENT -> _
> ```

This isn’t what is happening here though. The _ replaces at least a type and identifier.

[the remark this answers is not in the document]
Comment (romani) [reply src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/grammar/java21/InputUnnamedVariableBasic.java:37]: Ok I agree, structure wise it is very different, ok on new token.

What about name?

[the remark this answers is not in the document]
Comment (nrmancuso) [reply src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/grammar/java21/InputUnnamedVariableBasic.java:37]: Not all pattern tokens have prefix `PATTERN`:
```
➜  checkstyle git:(issue-13988) grep JavaLanguageLexer $(find . -name TokenTypes.java) | grep PATTERN
            JavaLanguageLexer.PATTERN_VARIABLE_DEF;
        JavaLanguageLexer.PATTERN_DEF;
        JavaLanguageLexer.RECORD_PATTERN_DEF;
            JavaLanguageLexer.RECORD_PATTERN_COMPONENTS;
            JavaLanguageLexer.UNNAMED_PATTERN_DEF;
```

Nor should they. Consider:
 - https://docs.oracle.com/javase/specs/jls/se21/html/jls-14.html#jls-RecordPattern
 - https://docs.oracle.com/javase/specs/jls/se21/html/jls-14.html#jls-TypePattern
 - https://docs.oracle.com/javase/specs/jls/se21/preview/specs/unnamed-jls.html#:~:text=UnnamedPattern-,UnnamedPattern%3A,-_

The JLS really doesn't use `Pattern` prefix at all, only `Pattern` as a single word.

**Comment by nrmancuso** [comment]
Link to report generation: https://github.com/nrmancuso/nrmancuso.github.io/actions/runs/7676650275

File: src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/grammar/java21/InputUnnamedVariableBasic.java (hunk 3 above)
[the remark this answers is not in the document]
Comment (romani) [reply src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/grammar/java21/InputUnnamedVariableBasic.java:37]: ok, agree, thanks a lot for details.

**Review by romani — APPROVED** [review]
ok to merge

**Comment by rnveach** [comment]
`run-inspections` is failing.

Let me know when regression is done. ( https://github.com/checkstyle/checkstyle/pull/14025#issuecomment-1913008183 )

**Comment by romani** [comment]
Inspections failed in multiple schema validation, know unstable rule. We need to disable it, too much distraction on it.

I restarted inspections.

**Comment by nrmancuso** [comment]
@rnveach ping

**Comment by rnveach** [comment]
@nrmancuso pong

File: src/test/java/com/puppycrawl/tools/checkstyle/grammar/GeneratedJavaTokenTypesTest.java (hunk 1 above)
Comment (rnveach) [reply src/test/java/com/puppycrawl/tools/checkstyle/grammar/GeneratedJavaTokenTypesTest.java:755]: This can be dropped if you haven't found any links. It could be good to just add this documentation in the code to be clearer, but it isn't required.

**Comment by rnveach** [comment]
> and new violations on files we couldn't previously parse.

It seems we could parse these files, just not correctly, as there is no exception being removed.

**Review by rnveach — APPROVED** [review]

File: src/test/java/com/puppycrawl/tools/checkstyle/grammar/GeneratedJavaTokenTypesTest.java (hunk 1 above)
Comment (nrmancuso) [reply src/test/java/com/puppycrawl/tools/checkstyle/grammar/GeneratedJavaTokenTypesTest.java]: Updated the PR with a minor commit to improve this whole test.

File: src/main/resources/com/puppycrawl/tools/checkstyle/grammar/java/JavaLanguageLexer.g4 [hunk 4]
```diff
@@ -168,7 +168,6 @@ LITERAL_CASE:            'case';
 LITERAL_CATCH:           'catch';
 LITERAL_CHAR:            'char';
 LITERAL_CLASS:           'class';
-LITERAL_CONST:           'const';
```
Comment (nrmancuso) [inline src/main/resources/com/puppycrawl/tools/checkstyle/grammar/java/JavaLanguageLexer.g4:169]: These are some leftover artifacts that we don't need. The original thinking was that Java might implement these keywords one day, and to have them here for some reason. They aren't doing us any good, and aren't used at all.

Comment (nrmancuso) [reply src/main/resources/com/puppycrawl/tools/checkstyle/grammar/java/JavaLanguageLexer.g4:169]: See here for details: https://docs.oracle.com/javase/specs/jls/se21/html/jls-3.html#jls-3.9:~:text=The%20keywords%20const%20and%20goto%20are%20reserved%2C%20even%20though%20they%20are%20not%20currently%20used

**Comment by romani** [comment]
Ok to merge extra lex tokens,.

**Review by rnveach — APPROVED** [review]
