### PR TITLE
Issue #6981: IT regression area input files Suppressed & Pattern validation updated to "InputXpath{Checkname}Xxx.java"

### LINKED ISSUE #6981: Enforce input naming convention in IT
Discovered at https://github.com/checkstyle/checkstyle/issues/6207 ,

Our UTs should have been checking the input files naming pattern but it was brought to light they aren't being checked.
I looked at the IT folder some and we don't have good input file names or their folder names too. It would require renaming all our files and folders there.

I believe this was missed because of the google folders and we just skipped them. Though they should be named `Input` even in google, I am not sure we forced the folder to match the name of the test like we did in `test` folder.

Test should be fixed to validate the IT folder some. Our regression area in IT should be fixed to match our pattern in Test folder.
Google and Sun area should atleast start with Input, but their folder structure follows a different pattern.

We cannot review a 1k file change in any timely matter. we just need the test, suppression, and the 1 example in this PR (2 commits). I would think this would ultimately need to be split among 50 PRs (20 files each) at the minimum.

### PR DESCRIPTION
**Pull request by MANISH-K-07**
Aims to close #6981 

~~PR not ready for review !!
[I was facing issues with mvn validations on local. ](https://matrix.to/#/!TnyOUUMSLLLwazyDHl:gitter.im/$KB82OsL1Wcygo11Z_EQXxROMd9lJmCWl43TSG61ghw4?via=gitter.im&via=matrix.org&via=mozilla.org) So, please excuse me while I use our integration workflows for verifying~~

Update : The pattern has been updated at `XpathRegressionTest#validateInputDirectory` to validate "`InputXpath{Checkname}Xxxx.java`". All existing old named modules have been suppressed.

<--Unrelated-->
Fun fact : Our IDEs have this keyboard shortcut `ctrl+shift+z` to single-line comment the line on which cursor is 😄

### CODE REVIEW

**Comment by MANISH-K-07** [comment]
@romani ,@rnveach @rnveach Please see if this matches your expectations :)

File: src/test/java/com/puppycrawl/tools/checkstyle/internal/XpathRegressionTest.java [hunk 1]
```diff
@@ -117,6 +117,149 @@ public class XpathRegressionTest extends AbstractModuleTestSupport {
 
     private static final Set<String> INTERNAL_MODULES = getInternalModules();
 
+    // Checks whose files need to be renamed to new pattern "InputXpath{Check}Xxx.java"
+    // till checkstyle issue
+    private static final Set<String> RENAME_INPUT_XPATH = Set.of(
```
Comment (MANISH-K-07) [inline src/test/java/com/puppycrawl/tools/checkstyle/internal/XpathRegressionTest.java:122]: > We are then good to completely swap old enforcement with new as it will be fixed as your list is worked on. The list must reference the issue to work on (until https://....) and complete it. I recommend to make this a new issue, we can mark it as easy

After your confirmation, I will create a new issue as suggested at https://github.com/checkstyle/checkstyle/pull/14595#discussion_r1518454112 and update comment above

**Review by rnveach — APPROVED** [review]
> [minor: Renamed IT executablestatementcount to new Pattern](https://github.com/checkstyle/checkstyle/pull/14713/commits/2c014b01a689f5223abe59bd69e1a98255d6a581)

This shouldn't be minor. Either connect it to this issue, or make it supplemental of this issue.

Also we need the new issue number in the code before this can be merged.

I am fine with everything else and will assign the admins.

**Review by romani — APPROVED** [review]
Ok to merge

**Comment by MANISH-K-07** [comment]
> Ok to merge

Sorry I closed and reopened by mistake..
I have attached the suppression list at Issue #14715

**Review by nrmancuso — APPROVED** [review]
Let's go!
