### PR TITLE
Issue #15769: fix false-positive indentation violations for block codes

### LINKED ISSUE #15769: google_checks.xml: remove xpath suppression and false-positive indentation violations for block codes
I have read check documentation: https://checkstyle.org/checks/misc/indentation.html
I have downloaded the latest checkstyle from: https://checkstyle.org/cmdline.html#Download_and_Run
I have executed the cli and showed it below, as cli describes the problem better than 1,000 words

Detected at https://github.com/checkstyle/checkstyle/issues/14294

In [google_checks.xml](https://github.com/checkstyle/checkstyle/blob/master/src/main/resources/google_checks.xml), [Indentation](https://checkstyle.org/checks/misc/indentation.html) module gives false-positive error for following type of blocks:

```
{
  int x = 99;
}
```

**Example:**

```java
/** Test... */
public class Test {
  private static void indentationIssue(int condition) {
    { // line 4, false-positive
      System.out.println("True");
    } // line 6, false-positive
  }

  { // good, no violation
    System.out.println("False");
  } // good, no violation

    { // line 13, expected
      System.out.println("False");
    } // line 15, expected

  class Inner {
    void test() {
      { // line 19, false-positive
        System.out.println("True");
      } // line 21, false-positive
    }
  }
}
```

```
$ java -jar .\checkstyle-10.18.2-all.jar -c .\google_checks.xml .\Test.java
Starting audit...
[WARN] C:\checkstyle testing\.\Test.java:4:5: 'block lcurly' has incorrect indentation level 4, expected level should be 6. [Indentation]
[WARN] C:\checkstyle testing\.\Test.java:6:5: 'block rcurly' has incorrect indentation level 4, expected level should be 6. [Indentation]
[WARN] C:\checkstyle testing\.\Test.java:13:5: 'block lcurly' has incorrect indentation level 4, expected level should be 2. [Indentation]
[WARN] C:\checkstyle testing\.\Test.java:14:7: 'block' child has incorrect indentation level 6, expected level should be 4. [Indentation]
[WARN] C:\checkstyle testing\.\Test.java:15:5: 'block rcurly' has incorrect indentation level 4, expected level should be 2. [Indentation]
[WARN] C:\checkstyle testing\.\Test.java:19:7: 'block lcurly' has incorrect indentation level 6, expected level should be 8. [Indentation]
[WARN] C:\checkstyle testing\.\Test.java:21:7: 'block rcurly' has incorrect indentation level 6, expected level should be 8. [Indentation]
Audit done.
```

@romani suggested to use suppression to suppress these false-positives until we find a way to fix it at: https://github.com/checkstyle/checkstyle/issues/14294#issuecomment-2408353743

The suppression is:

```xml
    <module name="SuppressionXpathSingleFilter">
      <property name="checks" value="Indentation"/>
      <property name="query" value="//SLIST/SLIST"/>
    </module>
    <module name="SuppressionXpathSingleFilter">
      <property name="checks" value="Indentation"/>
      <property name="query" value="//SLIST/SLIST/RCURLY"/>
    </module>
    <module name="Indentation">
      <property name="basicOffset" value="2"/>
      <property name="braceAdjustment" value="2"/>
      <property name="caseIndent" value="2"/>
      <property name="throwsIndent" value="4"/>
      <property name="lineWrappingIndentation" value="4"/>
      <property name="arrayInitIndent" value="2"/>
    </module>
```

Adding this suppression will suppress all indentation violations for above mentioned type of blocks whether they're correct or not but we need to use it till we find a fix.

---

As part of this issue, we need to find a way to fix this false-positive and remove the suppression.

### PR DESCRIPTION
**Pull request by mohitsatr**
fixes #15769 

Diff Regression config: https://gist.githubusercontent.com/mohitsatr/d55485b980e5c7ae9c883ba8f79dcbd6/raw/c824102d90368dbd060f41a1f6bda249cdcf0a5b/master_google_style.xml
Diff Regression patch config: https://gist.githubusercontent.com/mohitsatr/60d8725143067033c0ee8c8b8c6902c0/raw/e585f76bf1fe45a3eab04329b4f3ae01766aa394/google_checks_codeblock.xml

Diff Regression projects: https://gist.githubusercontent.com/mohitsatr/68b0817ac52ff7773d35585ee12fc1cc/raw/f9c7774ca78df1f48f34bf30799bd3952abd9e2a/list-of-projects.properties

### CODE REVIEW

**Comment by mohitsatr** [comment]
Github, generate report for indentation/all-examples-in-one

**Comment by mohitsatr** [comment]
Github, generate report for Indentation/all-examples-in-one

**Comment by romani** [comment]
@Zopsss , please do first review

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/BlockParentHandler.java [hunk 1]
```diff
@@ -157,14 +157,23 @@ private void checkLeftCurly() {
...
 
+    /**
+     * Checks if lcurly is a Code block.
+     *
+     * @return true if lcurly is a code block
+     */
+    private boolean checkIfCodeBlock() {
+        return getMainAst().getType() == TokenTypes.SLIST
+                && getParent() instanceof BlockParentHandler
+                && getParent().getParent() instanceof BlockParentHandler;
```
Comment (Zopsss) [inline src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/BlockParentHandler.java:174]: why `getParent().getParent()` is required?

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/BlockParentHandler.java [hunk 2]
```diff
@@ -157,14 +157,23 @@ private void checkLeftCurly() {
     protected IndentLevel curlyIndent() {
         final DetailAST lcurly = getLeftCurly();
         IndentLevel expIndentLevel = new IndentLevel(getIndent(), getBraceAdjustment());
-        if (!isOnStartOfLine(lcurly)
-            || lcurly.getParent().getType() == TokenTypes.INSTANCE_INIT) {
+        if (!isOnStartOfLine(lcurly) || checkIfCodeBlock()) {
```
Comment (Zopsss) [inline src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/BlockParentHandler.java:160]: is removing `lcurly.getParent().getType() == TokenTypes.INSTANCE_INIT` safe? can you tell me why was it used before?

File: src/test/resources/com/puppycrawl/tools/checkstyle/checks/indentation/indentation/InputIndentationCodeBlocks1.java [hunk 3]
```diff
@@ -0,0 +1,35 @@
...
+ * basicOffset = 2                                                          //indent:1 exp:1
+ * braceAdjustment = 2                                                      //indent:1 exp:1
+ * caseIndent = 2                                                           //indent:1 exp:1
+ * lineWrappingIndentation = 4                                              //indent:1 exp:1
+ * throwsIndent = 4                                                         //indent:1 exp:1
+ */                                                                         //indent:1 exp:1
+
+package com.puppycrawl.tools.checkstyle.checks.indentation.indentation; //indent:0 exp:0
+
+public class InputIndentationCodeBlocks1 { //indent:0 exp:0
```
Comment (Zopsss) [inline src/test/resources/com/puppycrawl/tools/checkstyle/checks/indentation/indentation/InputIndentationCodeBlocks1.java:13]: please add following cases right after class begins:

```java
  { //indent:2 exp:2
    System.out.println("True"); //indent:4 exp:4
  } //indent:2 exp:2
    { //indent:4 exp:2 warn
      System.out.println("False"); //indent:6 exp:4 warn
    } //indent:4 exp:2 warn
```

**Review by Zopsss — CHANGES_REQUESTED** [review]
item:

**Comment by mohitsatr** [comment]
Github, generate report

**Comment by mohitsatr** [comment]
first, we need to check regression on the project suggested here https://github.com/checkstyle/checkstyle/issues/14294#issuecomment-2408548213

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/BlockParentHandler.java (hunk 1 above)
Comment (mohitsatr) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/BlockParentHandler.java:174]: this condition is important in switch-cases blocks. 
```
      case ONE: (CaseHandler)
        { //indent:8 exp:8
          System.out.println("One"); //indent:10 exp:10
          break; //indent:10 exp:10
        } //indent:8 exp:8
``` 

```
|--CASE_GROUP -> CASE_GROUP [24:6]
|   |   |--LITERAL_CASE -> case [24:6]
|   |   |   |--EXPR -> EXPR [24:11]
|   |   |   |   `--IDENT -> ONE [24:11]
|   |   |   `--COLON -> : [24:14]
|   |   `--SLIST -> SLIST [25:8]
|   |       `--SLIST -> { [25:8]
|   |           |--EXPR -> EXPR [26:28]
```
without this extra check, `checkifBlockCode` returns True, causing a wrong indentation value.

Comment (mohitsatr) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/BlockParentHandler.java:174]: there is one weird behaviour. (not introduced by change in this PR)

Screenshot from 2025-03-14 11-48-43

Notice that 8 also happens to be valid indentation for 26 (`System.out..`) line . but isn't wrong ?

**Comment by mohitsatr** [comment]
@Zopsss in the regression config, we need to specify the google_style config as this issue is related to google-style right?

**Comment by Zopsss** [comment]
Yes, find diff between current master branch's google_checks.xml config and your modified google_checks.xml config. Check the generated report, if false positives/negatives are introduced then report them in your PR and try to fix them

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/BlockParentHandler.java (hunk 1 above)
Comment (Zopsss) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/BlockParentHandler.java:174]: > In regression reports , we might find problems with it.

yeah let's see how this performs in regression

Comment (Zopsss) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/BlockParentHandler.java:174]: > but isn't it wrong ? only 10 is valid, right ?

yup, this seems like a bug. Nice catch, please create a new issue for it.

**Comment by mohitsatr** [comment]
Github, generate report

**Comment by mohitsatr** [comment]
Github, generate report

**Comment by mohitsatr** [comment]
@Zopsss report generation exceeded 6 hours limit and got cancelled twice https://github.com/checkstyle/checkstyle/actions/runs/13871818479 ??

**Comment by Zopsss** [comment]
Sorry, even I'm seeing this error for the first time. 

@romani can you check what's the issue here?

**Comment by mohitsatr** [comment]
Github, generate report

**Comment by romani** [comment]
Please do not run on whole Google style config, just use intendtation module from it, nothing else.

**Comment by mohitsatr** [comment]
Github, generate report

**Comment by mohitsatr** [comment]
Github, generate report

**Comment by mohitsatr** [comment]
Error : Failed to execute goal org.apache.maven.plugins:maven-site-plugin:3.12.1:site (default-site) on project sample: Error generating maven-checkstyle-plugin:3.1.1:checkstyle report: Failed during checkstyle configuration: Exception was thrown while processing /home/runner/work/checkstyle/checkstyle/.ci-temp/contribution/checkstyle-tester/src/main/java/openjdk21/src/jdk.jlink/share/classes/module-info.java: IllegalStateException occurred while parsing file /home/runner/work/checkstyle/checkstyle/.ci-temp/contribution/checkstyle-tester/src/main/java/openjdk21/src/jdk.jlink/share/classes/module-info.java. 54:0: no viable alternative at input 'module': NoViableAltException -> [Help 1]

**Comment by mohitsatr** [comment]
```
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
          "-//Checkstyle//DTD Checkstyle Configuration 1.3//EN"
          "https://checkstyle.org/dtds/configuration_1_3.dtd">

<module name = "Checker">
    <property name="charset" value="UTF-8"/>

    <!-- do not change severity to 'error', as that will hide errors caused by exceptions -->
    <property name="severity" value="warning"/>

    <!-- haltOnException is required for exception fixes and reporting of all exceptions -->
    <property name="haltOnException" value="false"/>

    <!-- BeforeExecutionFileFilters is required for sources of java9 -->
    <module name="BeforeExecutionExclusionFileFilter">
        <property name="fileNamePattern" value="module\-info\.java$" />
    </module>

    <module name="TreeWalker">
         <!-- as we run on regression even on non-compiled files we need to skip exceptions on them -->
         <property name="skipFileOnJavaParseException" value="true"/>
         <property name="javaParseExceptionSeverity" value="ignore"/>

    
         
         <module name="Indentation">
             <property name="basicOffset" value="2"/>
             <property name="braceAdjustment" value="2"/>
             <property name="caseIndent" value="2"/>
             <property name="throwsIndent" value="4"/>
             <property name="lineWrappingIndentation" value="4"/>
             <property name="arrayInitIndent" value="2"/>
        </module>
         <!-- Suppression for block code until we find a way to detect them properly
         until https://github.com/checkstyle/checkstyle/issues/15769 -->
        <module name="SuppressionXpathSingleFilter">
           <property name="checks" value="Indentation"/>
           <property name="query" value="//SLIST[not(parent::CASE_GROUP)]/SLIST
                                   | //SLIST[not(parent::CASE_GROUP)]/SLIST/RCURLY"/>
        </module>

         <!-- suppress javadoc parsing errors, as we test Check not a parser -->
         <module name="SuppressionXpathSingleFilter">
            <property name="message" value="Javadoc comment at column \d+ has parse error"/>
         </module>
    </module>

</module>
```
@romani like this ?

**Comment by romani** [comment]
Yes

**Comment by mohitsatr** [comment]
Github, generate report

**Comment by romani** [comment]
diff is huge, please start copy all code from diff report to Input to have all distinct cases that we missed in Inputs.
Ideally we should have all in Inputs, and depend less on diff report.

**Comment by mohitsatr** [comment]
report is weird. there are diffs in switch and case blocks.

**Comment by mohitsatr** [comment]
we have already checked the regression using default indentation config https://github.com/checkstyle/checkstyle/pull/16515#issuecomment-2720881651

**Comment by Zopsss** [comment]
> only Hbase and camunda use google-style

Please go through their diff and add missing examples to our inputs. We can ignore other projects. 

Also if you're going to generate more regression reports then only include projects which uses google-style, other projects will not help us to find edge cases.

**Comment by mohitsatr** [comment]
Github, generate report

**Comment by mohitsatr** [comment]
Github, generate report

**Comment by mohitsatr** [comment]
@Zopsss in camunda project, violations on switch expression are fixed in https://github.com/checkstyle/checkstyle/pull/16418. these diffs did not show up in that PR's regression reports, mostly likely because of this suppression.
As for the Hbase project, there are not any new violations. diff is due to change in violation message.

File: src/test/resources/com/puppycrawl/tools/checkstyle/checks/indentation/indentation/InputIndentationCodeBlocks1.java (hunk 3 above)
Comment (mohitsatr) [reply src/test/resources/com/puppycrawl/tools/checkstyle/checks/indentation/indentation/InputIndentationCodeBlocks1.java:13]: done

**Comment by mohitsatr** [comment]
like I said , there is no violation change in Hbase project, do I still need to add examples from it to our input ??

**Comment by Zopsss** [comment]
> in camunda project, violations on switch expression are fixed in #16418. these diffs got removed that PR's regression report #16418 (comment)

Sorry I'm not able to understand why diff got removed. Were the violations in diff was false positives? And your PR fixed them?

> As for the Hbase project, there are not any new violations. diff is due to change in violation message.

Can you point out the PR where the violation message was changed?

**Comment by Zopsss** [comment]
> like I said , there is no violation change in Hbase project, do I still need to add examples from it to our input ??

Did we fixed some bug that's why the violation message was changed? Or is it something else? 

If the diff doesn't have any false-postivie/negative and if you don't find an example which is not in our input files then you don't need to add any new example. We'll be good to go

**Comment by romani** [comment]
@mohitsatr , please fix compilation problem https://app.circleci.com/pipelines/github/checkstyle/checkstyle/31749/workflows/70da813c-4d76-4d3a-a16f-5e33572194d9/jobs/850139

**Comment by mohitsatr** [comment]
diffes in the Hbase project is mainly due to the way they are formatting `for loops`
their loop braces have same indentation as `for` keyword
```
for (...)
{
  ..
}  
```
this is how we expect it to be:
```
for (...)
  {
     ..
  }
```

**Comment by mohitsatr** [comment]
now check is also giving correct violation
 
Screenshot from 2025-04-09 09-00-57

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/BlockParentHandler.java (hunk 1 above)
Comment (mohitsatr) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/BlockParentHandler.java:174]: should we? this check already has so many issues opened on it. 
https://github.com/checkstyle/checkstyle/pull/16131#issuecomment-2614179715

**Comment by romani** [comment]
@Zopsss , please finish review

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/BlockParentHandler.java (hunk 1 above)
Comment (Zopsss) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/BlockParentHandler.java:174]: @romani should we create an issue for this?

**Review by Zopsss — APPROVED** [review]
Sorry for the late review, LGTM! Thanks a lot for all the hard work!!!

**Comment by Zopsss** [comment]
@romani please merge the PR

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/BlockParentHandler.java (hunk 1 above)
Comment (romani) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/BlockParentHandler.java:174]: lets not open for now, we have too much already on this Check,

**Review by romani — APPROVED** [review]
Good step forward!!!
