### PR TITLE
Issue #7504: New Check UnusedLocalVariable

### LINKED ISSUE #7504: New Check: UnusedVariable
I'd like to request an unused variable module. The following should fail:

    public void foo() {
        Integer bar = 1;
        // This should fail since bar is not used
    }
    
Where as:

    public Integer foo() {
        Integer bar = 1;
        return bar
    }
    
Should not since it is used.

Thanks

### PR DESCRIPTION
**Pull request by Vyom-Yadav**
Partially Resolves #7504: New Check UnusedLocalVariable

Diff Regression config: https://gist.githubusercontent.com/Vyom-Yadav/98dceb63a79f4833e85fff9b2e1464a6/raw/95bad71f854a80ad29120a6bfb7bbd63c4eacded/my_checks.xml

Diff Regression patch config: https://gist.githubusercontent.com/Vyom-Yadav/273327b9c6cd6963b7dade792bc2c9c2/raw/2e98681b13d1f68e04bbfa10a18936c9851ea192/patch_config.xml

Final Report: 
~https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/21790c2_2021071214/reports/diff/index.html~
https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/e683dd9_2022092457/reports/diff/index.html

Diff between above mentioned reports(clean) - https://vyom-yadav.github.io/DiffReport/diffUnusedLocal/

---
Diff report for FullIdent(Clean) : https://vyom-yadav.github.io/DiffReport/diffFullIdent/

### CODE REVIEW

**Comment by Vyom-Yadav** [comment]
@romani @rnveach @strkkk @pbludov @nmancus1 Ignore the failing checks, for now, I will fix them.

While doing XpathRegressionTesting I found that the violations weren't being suppressed, I also tried to suppress the violations explicitly (jar file, config.xml, suppression.xml) but that too didn't work, what should be my next step regarding suppressions?

**Comment by pbludov** [comment]
It is better to fix the code to get rid of violations.
All these violations are easy to fix:
```
/checkstyle_sevntu_checks.xml ruleset.
[ERROR] src\main\java\com\puppycrawl\tools\checkstyle\checks\coding\UnusedLocalVariableCheck.java:[85,25] (extension) WhitespaceBeforeArrayInitializer: Array initializer should have whitespace before.
[ERROR] src\main\java\com\puppycrawl\tools\checkstyle\checks\coding\UnusedLocalVariableCheck.java:[148,17] (extension) MoveVariableInsideIf: Variable 'currAst' can be moved inside the block at line '149' to restrict runtime creation.
[ERROR] src\main\java\com\puppycrawl\tools\checkstyle\checks\coding\UnusedLocalVariableCheck.java:[170,9] (extension) MoveVariableInsideIf: Variable 'methodCallToken' can be moved inside the block at line '171' to restrict runtime creation.
[ERROR] src\main\java\com\puppycrawl\tools\checkstyle\checks\coding\UnusedLocalVariableCheck.java:[206,16] (extension) AvoidConditionInversion: Condition inversion could be avoided.
[ERROR] src\main\java\com\puppycrawl\tools\checkstyle\checks\coding\UnusedLocalVariableCheck.java:[219,9] (extension) CustomDeclarationOrder: Field definition in wrong order. Expected 'Field(private final)' then 'Field(private.*)'.
[ERROR] src\main\java\com\puppycrawl\tools\checkstyle\checks\coding\UnusedLocalVariableCheck.java:[222,9] (extension) CustomDeclarationOrder: Field definition in wrong order. Expected 'Field(private final)' then 'Field(private.*)'.
[ERROR] src\main\java\com\puppycrawl\tools\checkstyle\checks\coding\UnusedLocalVariableCheck.java:[228,9] (extension) CustomDeclarationOrder: Field definition in wrong order. Expected 'Field(private final)' then 'Field(private.*)'.
```

**Comment by Vyom-Yadav** [comment]
@pbludov Resolved those, anything regarding suppressions?

**Comment by nmancus1** [comment]
> anything regarding suppressions?

You are using the "old" logging method (line number, column number). Please use `public final void log(DetailAST ast, String key, Object... args)` to log actual AST so that XPath can find it.

File: src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheckTest.java [hunk 1]
```diff
@@ -0,0 +1,77 @@
...
+                new UnusedLocalVariableCheck();
+        final int[] expected = {
+            TokenTypes.DOT,
+            TokenTypes.VARIABLE_DEF,
+            TokenTypes.IDENT,
+            TokenTypes.SLIST,
+        };
+        assertArrayEquals(expected, checkObj.getRequiredTokens(),
+                "Default required tokens are invalid");
+    }
```
Comment (Vyom-Yadav) [inline src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheckTest.java:49]: @nmancus1 Is this needed, some tests adhere to this and some do not

Comment (nmancus1) [reply src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheckTest.java:49]: We are trying to use google truth wherever it is possible; I would just do something like:

```java
        assertWithMessage("Default required tokens are invalid")
                .that(actualTokens)
                .isEqualTo(expectedTokens);

```

**Comment by pbludov** [comment]
> @pbludov should we somehow limit the usage of "old" `log` method to help prevent this is in the future?

This is a good idea. Developers should be aware of this. We have a [check](https://github.com/checkstyle/checkstyle/blob/38df63e992c1270eac87d5e98d5d8cb281c4a20b/config/checkstyle_sevntu_checks.xml#L215) to forbid some method by its name and number of parameters.

 Unfortunately, the "old" `log` method is still used by Javadoc checks and filters. See #4830 for the details.
This means we should add an entry for `ForbidCertainMethodCheck` and suppress this violation for `*Flter` and `Javadoc*Check`.

File: src/main/java/com/puppycrawl/tools/checkstyle/api/DetailAST.java [hunk 2]
```diff
@@ -146,4 +146,6 @@
      * @return {@code true} if this AST has any children.
      */
     boolean hasChildren();
+
 }
+
```
Comment (strkkk) [inline src/main/java/com/puppycrawl/tools/checkstyle/api/DetailAST.java:151]: I dont think you need these changes with blank lines :)

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java [hunk 3]
```diff
@@ -0,0 +1,545 @@
...
+                throw new IllegalStateException(ast.toString());
+        }
+    }
+
+    @Override
+    public void leaveToken(DetailAST ast) {
+        if (TokenUtil.isOfType(ast.getType(), TokenTypes.SLIST, TokenTypes.EXPR,
+                TokenTypes.ELIST)) {
+            int size = variables.size();
+            while (size > 0 && variables.peek().getScopeOfVariable() == ast) {
```
Comment (strkkk) [inline src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java:170]: `size > 0` better to use `!variables.isEmpty()`

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java [hunk 4]
```diff
@@ -0,0 +1,545 @@
...
+        /**
+         * DetailAst of type {@link TokenTypes#VARIABLE_DEF}.
+         */
+        private final DetailAST variableAst;
+
+        /**
+         * The scope of variable is determined by the DetailAst of type
+         * {@link TokenTypes#SLIST} which is enclosing {@link VariableDesc#variableAst}.
+         */
+        private DetailAST scopeOfVariable;
```
Comment (strkkk) [inline src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java:395]: can be just `scope`

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java [hunk 5]
```diff
@@ -0,0 +1,545 @@
...
+
+        /**
+         * Is the variable used again.
+         */
+        private boolean isUsedAgain;
```
Comment (strkkk) [inline src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java:400]: `isUsed` is enough, same for getter names

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java [hunk 6]
```diff
@@ -0,0 +1,545 @@
...
+
+        /**
+         * Is the variable a pattern variable.
+         */
+        private boolean isPatternVariable;
```
Comment (strkkk) [inline src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java:405]: `isPattern` is enough

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java [hunk 7]
```diff
@@ -0,0 +1,545 @@
...
+            scopeOfPatternVariableIncludingLineAndColumn = new int[] {
+                scopeLineStart, scopeColumnStart, scopeLineEnd, scopeColumnEnd,
+            };
+        }
+    }
+
+    /**
+     * Index values for {@link VariableDesc#scopeOfPatternVariableIncludingLineAndColumn}.
+     */
+    private static class PatternVariableScope {
```
Comment (strkkk) [inline src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java:527]: may be make it as enum?

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java [hunk 8]
```diff
@@ -0,0 +1,545 @@
...
+     * value if it is used as the left operand of an assignment or as the
+     * operand of a stand-alone increment
+     *
+     * @param identAst DetailAst of type {@link TokenTypes#IDENT}
+     * @return True if identAst is used as a left-hand side value otherwise false.
+     */
+    private static boolean isLeftHandSideValue(DetailAST identAst) {
+        final DetailAST parent = identAst.getParent();
+        return TokenUtil.isOfType(parent.getType(), INCREMENT_AND_DECREMENT_KINDS)
+                || parent.getType() == TokenTypes.ASSIGN
```
Comment (strkkk) [inline src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java:372]: `parent.getType() == TokenTypes.ASSIGN` you can add assign token to existing array of INCREMENT_AND_DECREMENT tokens (and rename it)
it will be easier to read

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java [hunk 9]
```diff
@@ -0,0 +1,545 @@
...
+            result = true;
+        }
+        else {
+            if (isIdentPresentInTheScopeOfPatternVariable(identLine, identColumn,
+                    scopeOfPatternVariableIncludingLineAndColumn)) {
+                result = true;
+            }
+        }
+
+        return result;
```
Comment (strkkk) [inline src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java:248]: can be just
```
return variableDesc.getScopeOfVariable().getType() == TokenTypes.SLIST
   || isIdentPresentInTheScopeOfPatternVariable(identAst.getLineNo(), identAst.getColumnNo(),
                    scopeOfPatternVariableIncludingLineAndColumn)
```

File: src/main/java/com/puppycrawl/tools/checkstyle/api/DetailAST.java (hunk 2 above)
Comment (Vyom-Yadav) [reply src/main/java/com/puppycrawl/tools/checkstyle/api/DetailAST.java]: I added a method but later found a better way, must be a residue of that process, removed them now.

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java [hunk 10]
```diff
@@ -0,0 +1,545 @@
...
+ * <pre>
+ * &lt;module name=&quot;UnusedLocalVariable&quot;/&gt;
+ * </pre>
+ * <p>
+ * Example:
+ * </p>
+ * <pre>
+ * public void method(int a) {
+ *     int a = 10; // violation
+ * }
```
[the remark this answers is not in the document]
Comment (Vyom-Yadav) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java:47]: my bad, fixed it.

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java [hunk 11]
```diff
@@ -0,0 +1,545 @@
...
+    /**
+     * A key is pointing to the warning message text in "messages.properties"
+     * file.
+     */
+    public static final String MSG_UNUSED_LOCAL_VARIABLE = "unused.local.var";
+
+    /**
+     * An array of increment tokens.
+     */
+    private static final int[] INCREMENT_AND_DECREMENT_KINDS = {
```
[the remark this answers is not in the document]
Comment (Vyom-Yadav) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java]: Changed name.

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java (hunk 4 above)
Comment (Vyom-Yadav) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java]: done

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java (hunk 5 above)
Comment (Vyom-Yadav) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java]: done

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java (hunk 6 above)
Comment (Vyom-Yadav) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java]: Removed isPattern as no more needed.

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java (hunk 7 above)
Comment (Vyom-Yadav) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java:482]: Would be inconvenient to get values from enum IMO, as we would have to make a getter method inside enum.

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java (hunk 8 above)
Comment (Vyom-Yadav) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java:346]: The condition is different-
```
return TokenUtil.isOfType(parent.getType(), INCREMENT_AND_DECREMENT_TOKENS)
                || (parent.getType() == TokenTypes.ASSIGN
                && identAst != parent.getLastChild());
```

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java (hunk 9 above)
Comment (Vyom-Yadav) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java]: done.

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java (hunk 3 above)
Comment (Vyom-Yadav) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java]: done

**Comment by Vyom-Yadav** [comment]
I will give explanations, reports, etc. for suppressions.

**Comment by Vyom-Yadav** [comment]
Github, generate report

**Comment by Vyom-Yadav** [comment]
Github, generate report

**Comment by strkkk** [comment]
@Vyom-Yadav there are false positives in report, e.g.
https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/c36c2f9_2021201430/reports/diff/Vavr/xref/home/runner/work/checkstyle/checkstyle/contribution/checkstyle-tester/repositories/Vavr/vavr-test/src/main/java/io/vavr/test/Gen.java.html#L357 and https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/c36c2f9_2021201430/reports/diff/Vavr/xref/home/runner/work/checkstyle/checkstyle/contribution/checkstyle-tester/repositories/Vavr/vavr/src/test/java/io/vavr/concurrent/Concurrent.java.html#L38
there are other false positives with increment

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java (hunk 10 above)
[the remark this answers is not in the document]
Comment (strkkk) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java:49]: Even after fix is it still can be improved. This is not only example of reported violation - there can be ctor with unused variable, init blocks, etc.
Plus there may be example of some variable init as a result of method invocation.

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java (hunk 7 above)
Comment (strkkk) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java:584]: you can avoid using array + indices and make it more readable using object that encapsulates this data (line start, line end, etc). Where this info is needed, it will be like
```
patternVariableScope.getLine() == identLine
```
instead of current 
```
scopeOfPatternVariableIncludingLineAndColumn[
                    PatternVariableScope.LINE_START] == identLine
```

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java [hunk 12]
```diff
@@ -0,0 +1,595 @@
...
+     * @param variableDesc information about the local variable
+     * @param ancestorOfInstanceOfAst ancestor of DetailAst of type
+     *                                {@link TokenTypes#LITERAL_INSTANCEOF}
+     */
+    private static void setScopeOfPatternVariableExcludingLineAndColumn(
+            VariableDesc variableDesc, DetailAST ancestorOfInstanceOfAst) {
+
+        DetailAST ast = ancestorOfInstanceOfAst;
+        DetailAST grandParent = ast.getParent();
+        final boolean IsAFullScopeVariable = ast.getType() == TokenTypes.EXPR
```
Comment (strkkk) [inline src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java:396]: name starts with capital letter, thus ci is failing. Also pls avoid articles in names, just `isFullScopeVariable` or `isTernaryOpExpression` is enough

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java [hunk 13]
```diff
@@ -0,0 +1,595 @@
...
+        variables = new ArrayDeque<>();
+    }
+
+    @Override
+    public void visitToken(DetailAST ast) {
+        switch (ast.getType()) {
+            case TokenTypes.DOT:
+                final DetailAST firstDotOrMethodCallAst = getFirstDotOrMethodCallToken(ast);
+                if (firstDotOrMethodCallAst == null
+                        && ast.findFirstToken(TokenTypes.LITERAL_NEW) == null
```
Comment (pbludov) [inline src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java:144]: This can be simplified to
```java
                        && !TokenUtil.findFirstTokenByPredicate(ast, child -> {
                            return TokenUtil.isOfType(child,
                                    TokenTypes.LITERAL_NEW,
                                    TokenTypes.LITERAL_SUPER,
                                    TokenTypes.LITERAL_CLASS,
                                    TokenTypes.LITERAL_THIS);
                            }).isPresent()
```

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java [hunk 14]
```diff
@@ -0,0 +1,595 @@
...
+            default:
+                break;
+        }
+    }
+
+    @Override
+    public void leaveToken(DetailAST ast) {
+        if (TokenUtil.isOfType(ast.getType(),
+                IntStream.concat(Arrays.stream(SCOPES),
+                        Arrays.stream(SCOPES_EXCLUSIVE_TO_PATTERN_VARIABLES)).toArray())) {
```
Comment (pbludov) [inline src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java:187]: Please create a new field. Combining constant arrays in runtime is weird.

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java [hunk 15]
```diff
@@ -0,0 +1,595 @@
...
+     * {@link TokenTypes#METHOD_CALL} token which is the
+     * child of {@link TokenTypes#EXPR}.
+     *
+     * @param exprAst DetailAst of type {@link TokenTypes#EXPR}
+     * @return DetailAst of type {@link TokenTypes#DOT} or {@link TokenTypes#METHOD_CALL}
+     *         if present, otherwise null
+     */
+    private static DetailAST getFirstDotOrMethodCallToken(DetailAST exprAst) {
+        final DetailAST result;
+        final DetailAST dotToken = exprAst.findFirstToken(TokenTypes.DOT);
```
Comment (pbludov) [inline src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java:209]: Again, `findFirstTokenByPredicate` will be better here.
It looks like we need something like `TokenUtils.findFirstOfAny(DetailAst, int...)`;

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java (hunk 13 above)
Comment (Vyom-Yadav) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java]: done

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java (hunk 14 above)
Comment (Vyom-Yadav) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java]: removed as I will be writing a separate check for pattern variables

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java (hunk 15 above)
Comment (Vyom-Yadav) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java]: Did not create a new method, did it with `findFirstTokenByPredicate`

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java (hunk 12 above)
Comment (Vyom-Yadav) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java]: Field not required now

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java [hunk 16]
```diff
@@ -0,0 +1,326 @@
...
+        variables = new ArrayDeque<>();
+    }
+
+    @Override
+    public void visitToken(DetailAST ast) {
+        switch (ast.getType()) {
+            case TokenTypes.DOT:
+                final boolean checkIdentToken = !TokenUtil.findFirstTokenByPredicate(ast,
+                                dotAst -> {
+                                    return TokenUtil.isOfType(dotAst.getType(),
```
Comment (strkkk) [inline src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java:143]: there are plenty of invocations of TokenUtil.isOfType
Please note that there is no need to invoke getType() on ast, there is overloaded version of this method that accepts AST, so `TokenUtil.isOfType(dotAst.getType(),...)` can be `TokenUtil.isOfType(dotAst, ....)`
Same for other occurences

Comment (Vyom-Yadav) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java]: my bad, fixed it.

File: config/spotbugs-exclude.xml [hunk 17]
```diff
@@ -82,6 +82,7 @@
       <Class name="com.puppycrawl.tools.checkstyle.checks.coding.MatchXpathCheck"/>
       <Class name="com.puppycrawl.tools.checkstyle.checks.OuterTypeFilenameCheck" />
       <Class name="com.puppycrawl.tools.checkstyle.checks.regexp.RegexpCheck" />
+      <Class name="com.puppycrawl.tools.checkstyle.checks.coding.UnusedLocalVariableCheck"/>
```
Comment (Vyom-Yadav) [inline config/spotbugs-exclude.xml:85]: Complains about `private Deque<VariableDesc> variables;` but begin tree also acts as a constructor.

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java (hunk 7 above)
Comment (Vyom-Yadav) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java]: Will keep in mind, field not required anymore.

**Comment by Vyom-Yadav** [comment]
Github, generate report.

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java (hunk 10 above)
[the remark this answers is not in the document]
Comment (strkkk) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java:47]: @Vyom-Yadav please do not forget to update docs. It is also important part for users to see what check does.

By the way, code looks good to me so far, your work is also very good.

[the remark this answers is not in the document]
Comment (Vyom-Yadav) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java:47]: I will definitely update docs, was just waiting to make the check work fine and resolve the FP's and FN's first, I will go through the report once to make sure and update documentation simultaneously.

**Comment by Vyom-Yadav** [comment]
Github, generate report

**Comment by Vyom-Yadav** [comment]
Github, generate report

**Comment by Vyom-Yadav** [comment]
Github, generate report

**Comment by Vyom-Yadav** [comment]
The report is quite large so I will take some time to go through it, I tried to cover all cases but naturally can miss out on some, feel free to go through the report and share those cases.

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java (hunk 10 above)
[the remark this answers is not in the document]
Comment (Vyom-Yadav) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java:99]: @strkkk I updated docs, if you think some more examples need to be added, just ping me and I will add those test cases.

**Comment by Vyom-Yadav** [comment]
Github, generate report

**Comment by Vyom-Yadav** [comment]
Github, generate report

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java [hunk 18]
```diff
@@ -0,0 +1,447 @@
...
+        final int type = ast.getType();
+        if (type == TokenTypes.DOT) {
+            visitDotToken(ast);
+        }
+        else if (type == TokenTypes.VARIABLE_DEF) {
+            visitVariableDefToken(ast);
+        }
+        else if (type == TokenTypes.IDENT) {
+            visitIdentToken(ast);
+        }
```
Comment (Vyom-Yadav) [inline src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java:212]: Extracted to reduce cognitive complexity.

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java [hunk 19]
```diff
@@ -0,0 +1,447 @@
...
+ *     }
+ *
+ *     String convertValue(String newValue) {
+ *         String s = newValue.toLowerCase(); // violation
+ *         return newValue.toLowerCase();
+ *     }
+ *
+ *     void read() throws IOException {
+ *         BufferedReader reader = new BufferedReader(new InputStreamReader(System.in));
+ *         String s; // violation
```
Comment (strkkk) [inline src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java:75]: why it is a violation if it is used right next line?

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java [hunk 20]
```diff
@@ -0,0 +1,447 @@
...
+ * <p>
+ * Example:
+ * </p>
+ * <pre>
+ * class Test {
+ *
+ *     int a;
+ *
+ *     {
+ *         int k = 12; // violation
```
Comment (strkkk) [inline src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java:53]: why it is a violation if there is an increment next line?

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java [hunk 21]
```diff
@@ -0,0 +1,447 @@
...
+     * @param dotAst dotAst
+     */
+    private void visitDotToken(DetailAST dotAst) {
+        final boolean checkIdentToken = !TokenUtil.findFirstTokenByPredicate(dotAst,
+                        ast -> {
+                            return TokenUtil.isOfType(ast,
+                                    UNACCEPTABLE_CHILD_OF_DOT);
+                        })
+                .isPresent();
+        if (checkIdentToken) {
```
Comment (strkkk) [inline src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java:240]: it is better to use Optional#ifPresent

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java [hunk 22]
```diff
@@ -0,0 +1,447 @@
...
+    private void visitIdentToken(DetailAST identAst) {
+        final DetailAST parentAst = identAst.getParent();
+        if (!TokenUtil.isOfType(parentAst, UNACCEPTABLE_PARENT_OF_IDENT)) {
+            if (parentAst.getType() == TokenTypes.METHOD_REF) {
+                if (shouldCheckMethodRefIdent(identAst)) {
+                    checkIdentifierAst(identAst);
+                }
+            }
+            else {
+                checkIdentifierAst(identAst);
```
Comment (strkkk) [inline src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java:273]: this call is same as one in if above, I believe it can be simplified

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java (hunk 20 above)
Comment (Vyom-Yadav) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java:53]: The variable is used in standalone increment, it is considered as unused

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java (hunk 19 above)
Comment (Vyom-Yadav) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java:75]: The value is just assigned, it is never used. `(s = reader.readLine()) != null` is not using/reading the variable `s`, it is the result of the assignment expression that is compared to null

Comment (Vyom-Yadav) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java:75]: Though according to the [JLS](https://docs.oracle.com/javase/specs/jls/se11/html/jls-15.html#jls-15.26) 
>At run time, the result of the assignment expression is the value of the variable after the assignment has occurred. The result of an assignment expression is not itself a variable. 

But I checked this particular case with sonar lint and eclipse and they both reported the variable as unused, also why I think it is unused because we are-

- Not using it again inside or outside the loop again.

- We can replace it by `while(reader.readLine() != null){}`

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java (hunk 21 above)
Comment (Vyom-Yadav) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java:240]: ifPresent won't quite work in an intended way, the condition with `ifPresent(..)` would be something like
```
TokenUtil.findFirstTokenByPredicate(dotAst,
                        ast -> {
                            return !TokenUtil.isOfType(ast,
                                    UNACCEPTABLE_CHILD_OF_DOT);
                        })
                .ifPresent(ast -> checkIdentifierAst(dotAst.findFirstToken(TokenTypes.IDENT)));
```
I don't like this approach as first of all it doesn't work in this case and secondly, the lambda parameter is not used.
Why this doesn't work is due to the fact that `TokenUtil.findFirstTokenByPredicate(..)` stops when it finds the suitable token i.e. in this case `Every possible token - UNACCEPTABLE_CHILD_OF_DOT` and then it will call the method `checkIdentifierAst(..)`. 
Earlier it stopped when it found `UNACCEPTABLE_CHILD_OF_DOT`. Why this makes a difference can be explained by a simple example-
```
Class<Integer> b = int.class;
```
parses as (the portion we need)-
```
--EXPR -> EXPR
   `--DOT -> .
       |--LITERAL_INT -> int
       `--LITERAL_CLASS -> class
```
Now the method `TokenUtil.findFirstTokenByPredicate(..)` checks by traversing from sibling to sibling and will stop at `LITERAL_INT` as that comes under `Every possible token - UNACCEPTABLE_CHILD_OF_DOT` and will invoke the method `checkIdentifierAst(dotAst.findFirstToken(TokenTypes.IDENT))` which will give an NPE as `DOT` dosen't have a child of type `IDENT`.  

Originally what it's doing is traversing until it finds `UNACCEPTABLE_CHILD_OF_DOT` and then stop. I negated the whole boolean condition and checked the negated condition before calling `checkIdentifierAst(..)`.

So `ifPresent(..)` won't work but `ifPresentOrElse(..)` will work but we can't use it as it's Java 9+

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java (hunk 22 above)
Comment (Vyom-Yadav) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java]: done

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java (hunk 19 above)
Comment (strkkk) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java:75]: ok, but it still bother me. Such things with check that tries to be smart can lead to false positives

Comment (Vyom-Yadav) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java:75]: This case is only possible while using normal assign(`=`). Something like-
```
InputStreamReader a = new InputStreamReader(System.in);
String s = "foo";
while ((s += a.read()) != null) {
}
```
won't show any error.
I tried to cover every case, but if any false positive appears in the future I will surely fix it.

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java [hunk 23]
```diff
@@ -0,0 +1,449 @@
...
+ * <p>
+ * Violation Message Keys:
+ * </p>
+ * <ul>
+ * <li>
+ * {@code unused.local.var}
+ * </li>
+ * </ul>
+ *
+ * @since 9.2
```
Comment (strkkk) [inline src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java:113]: version has to be bumped

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java [hunk 24]
```diff
@@ -0,0 +1,449 @@
...
+     */
+    public static boolean shouldCheckIdentifierAst(DetailAST ast) {
+
+        boolean result = false;
+        if (ast.getType() == TokenTypes.IDENT) {
+            final DetailAST parent = ast.getParent();
+            if (parent.getType() != TokenTypes.METHOD_REF
+                    || parent.getFirstChild() == ast
+                    && parent.getLastChild().getType() != TokenTypes.LITERAL_NEW) {
+                result = true;
```
Comment (strkkk) [inline src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java:280]: can be simplified to 
```
result = parent.getType() != TokenTypes.METHOD_REF
                    || parent.getFirstChild() == ast
                    && parent.getLastChild().getType() != TokenTypes.LITERAL_NEW
```

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java [hunk 25]
```diff
@@ -0,0 +1,449 @@
...
+    }
+
+    /**
+     * Checks whether the DetailAst of type {@link TokenTypes#IDENT} is used as
+     * an operand of a stand-alone increment.
+     *
+     * @param identAst DetailAst of type {@link TokenTypes#IDENT}
+     * @return True if identAst is used as an operand of stand-alone increment otherwise false
+     */
+    private static boolean isStandAloneIncrement(DetailAST identAst) {
```
Comment (strkkk) [inline src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java:357]: name is a bit confusing. It is not only increment check, but also decrement and some others

File: src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/unusedlocalvariable/InputUnusedLocalVariable.java [hunk 26]
```diff
@@ -0,0 +1,186 @@
...
+    }
+
+    public void testChainedCalls() throws InterruptedException {
+        Obj p; // violation
+        Obj q = null; // ok
+        p = q.foo().p;
+        if(s instanceof String) {
+        }
+        Boolean r = false;
+        while(r.booleanValue() != true) {
```
Comment (strkkk) [inline src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/unusedlocalvariable/InputUnusedLocalVariable.java:85]: please also add some test case like
```
boolean b = false;
if (!b) {}
```

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java [hunk 27]
```diff
@@ -0,0 +1,449 @@
...
+        }
+    }
+
+    /**
+     * Visit ast of type {@link TokenTypes#DOT}.
+     *
+     * @param dotAst dotAst
+     */
+    private void visitDotToken(DetailAST dotAst) {
+        if (shouldCheckIdentifierAst(dotAst)) {
```
Comment (strkkk) [inline src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java:234]: `shouldCheckIdentifierAst(dotAst)` sounds confusing, please rename argument and method `visitDotToken` since there can be not only dot

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java (hunk 23 above)
Comment (Vyom-Yadav) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java]: done

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java (hunk 24 above)
Comment (Vyom-Yadav) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java]: done

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java (hunk 25 above)
Comment (Vyom-Yadav) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java]: done, renamed to `isStandAloneIncrementOrDecrement(..)`
>...and some others

The other tokens are present around the inc and dec operator so the method name shouldn't include them IMO

File: src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/unusedlocalvariable/InputUnusedLocalVariable.java (hunk 26 above)
Comment (Vyom-Yadav) [reply src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/unusedlocalvariable/InputUnusedLocalVariable.java:85]: Added few more examples

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java (hunk 27 above)
Comment (Vyom-Yadav) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java]: 1. I renamed it to `shouldCheckCurrentAndNestedIdentAst(DetailAST ast)`, renaming the argument of this method to something like `identOrDotAst` didn't feel right to me as every time it was used there was an ambiguity whether it is `ident` or `dot` ast.

2. It didn't rename the method `visitDotToken` since we are visiting dot token first and then checking it surrounding tokens using some methods, so it feels right to me.

If renaming in the first point doesn't work I can split the method into two separate methods, one for ident ast and the other for dot ast.

Comment (strkkk) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java]: you can always make arg name like `ast`, this is common way

Comment (Vyom-Yadav) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java]: Right now arg name for `shouldCheckCurrentAndNestedIdentAst(..)` is `ast`

Comment (strkkk) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java]: I mean here it is dotAst, but it is not correct (there can be ident). So just make it more abstract to avoid confusion.
In general, it is better to avoid specifying exact tokens in method/arg name unless it is 100% the only token that can be there. Otherwise, when arg is named like `dotAst` and we check its type to be IDENT, it is a bit confusing.

**Comment by strkkk** [comment]
Github, generate report

**Comment by strkkk** [comment]
Report looks ok.

Please address https://github.com/checkstyle/checkstyle/pull/10930#discussion_r760811361

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java (hunk 27 above)
Comment (Vyom-Yadav) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java]: Done, I refactored into two different methods to make more sense.

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java [hunk 28]
```diff
@@ -0,0 +1,457 @@
...
+     */
+    public static boolean shouldCheckIdentWithMethodRefParent(DetailAST identAst) {
+        final DetailAST parent = identAst.getParent();
+        boolean result = true;
+        if (parent.getType() == TokenTypes.METHOD_REF) {
+            result = parent.getFirstChild() == identAst
+                    && parent.getLastChild().getType() != TokenTypes.LITERAL_NEW;
+        }
+        return result;
+    }
```
Comment (Vyom-Yadav) [inline src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java:283]: Can refactor this into-
```
public static boolean shouldCheckIdentWithMethodRefParent(DetailAST identAst) {
        final DetailAST parent = identAst.getParent();
        return parent.getType() != TokenTypes.METHOD_REF || parent.getFirstChild() == identAst
                && parent.getLastChild().getType() != TokenTypes.LITERAL_NEW;
}
```
But readability is better before refactoring, after refactoring it becomes difficult to read and the condition is not that clear.

**Comment by Vyom-Yadav** [comment]
Github, generate report

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java [hunk 29]
```diff
@@ -0,0 +1,457 @@
...
+ *         } catch (Exception e) { // ok as e is an exception parameter
+ *         }
+ *     }
+ *
+ *     void loops() {
+ *         int j = 12;
+ *         for (int i = 0; j &lt; 11; i++) { // violation, unused local variable 'i'.
+ *         }
+ *         for (int p = 0; j &lt; 11; p++) // ok
+ *             p /= 2;
```
Comment (pbludov) [inline src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java:90]: Will be there a violation:

```java
for (int p = 0; j &lt; 11; p++) //violation?
   p++;
 ```

Comment (Vyom-Yadav) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java:90]: Yes, `p` is never used, it's only incremented.

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java [hunk 30]
```diff
@@ -0,0 +1,457 @@
...
+ *     }
+ *
+ *     Test(int a) { // ok as 'a' is a method parameter not a local variable
+ *         this.a = 12;
+ *     }
+ *
+ *     void method(int b) {
+ *         int a = 10; // violation
+ *         int[] arr = {1, 2, 3}; // violation
+ *         int[] anotherArr = {1}; // ok
```
[the remark this answers is not in the document]
Comment (Vyom-Yadav) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java:64]: That is a different check IMO, IntelliJ says the **components** are written but not read. [JLS](https://docs.oracle.com/javase/specs/jls/se17/html/jls-4.html#jls-4.12.3) mentions

> Array components are unnamed variables that are created and initialized to default values ([§4.12.5](https://docs.oracle.com/javase/specs/jls/se17/html/jls-4.html#jls-4.12.5)) whenever a new object that is an array is created ([§10 (Arrays)](https://docs.oracle.com/javase/specs/jls/se17/html/jls-10.html), [§15.10.2](https://docs.oracle.com/javase/specs/jls/se17/html/jls-15.html#jls-15.10.2)). The array components effectively cease to exist when the array is no longer referenced. 

These components are created by [accessing](https://docs.oracle.com/javase/specs/jls/se17/html/jls-10.html#jls-10.4) `anotherArr`, so we are accessing `anotherArr` but whether array components are unused should be considered as a separate check.

[the remark this answers is not in the document]
Comment (pbludov) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java:64]: Ok. Following the logic of this check, this variable is used.

**Review by strkkk — APPROVED** [review]

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java [hunk 31]
```diff
@@ -0,0 +1,457 @@
...
+    }
+
+    @Override
+    public int[] getRequiredTokens() {
+        return getDefaultTokens();
+    }
+
+    @Override
+    public void beginTree(DetailAST root) {
+        variables = new ArrayDeque<>();
```
[the remark this answers is not in the document]
Comment (Vyom-Yadav) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java:198]: Yes can be done but pitest will fail on `variables.clear()`.

If the rationale behind migrating from `beginTree` to `constructor` and `endTree` is removing the suppression then we would have to add the survived mutation in the ignore list, if the rationale is anything other than this then please specify, I will make the changes accordingly.

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java (hunk 20 above)
Comment (Vyom-Yadav) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java:53]: done

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java (hunk 31 above)
[the remark this answers is not in the document]
Comment (pbludov) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java:198]: I'm OK with current behavior.

**Review by pbludov — APPROVED** [review]

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java [hunk 32]
```diff
@@ -0,0 +1,457 @@
...
+     * @return True if identAst is used as an operand of stand-alone
+     *         increment or decrement otherwise false
+     */
+    private static boolean isStandAloneIncrementOrDecrement(DetailAST identAst) {
+        final DetailAST parent = identAst.getParent();
+        final DetailAST grandParent = parent.getParent();
+        return TokenUtil.isOfType(parent, INCREMENT_AND_DECREMENT_TOKENS)
+                && TokenUtil.isOfType(grandParent, TokenTypes.EXPR)
+                && (!TokenUtil.isOfType(grandParent.getParent(),
+                TokenTypes.ELIST, TokenTypes.INDEX_OP, TokenTypes.ASSIGN)
```
Comment (nmancus1) [inline src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java:371]: Could we extract this as some boolean with descriptive name?

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java [hunk 33]
```diff
@@ -0,0 +1,457 @@
...
+         * @return {@link VariableDesc#scope}.
+         */
+        public DetailAST getScope() {
+            return scope;
+        }
+
+        /**
+         * Is the variable used again or not.
+         *
+         * @return true if variable is used again else false;
```
Comment (nmancus1) [inline src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java:444]: Please remove `else false;`

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java [hunk 34]
```diff
@@ -0,0 +1,457 @@
...
+        private final String name;
+
+        /**
+         * DetailAst of type {@link TokenTypes#TYPE}.
+         */
+        private final DetailAST typeAst;
+
+        /**
+         * The scope of variable is determined by the DetailAst of type
+         * {@link TokenTypes#SLIST} which is enclosing the variable.
```
Comment (nmancus1) [inline src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java:392]: Seems to me that this could also be a `LITERAL_FOR`, by check logic above.

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java [hunk 35]
```diff
@@ -0,0 +1,457 @@
...
+         * Get the associated {@link VariableDesc#typeAst}.
+         *
+         * @return {@link VariableDesc#typeAst}
+         */
+        public DetailAST getTypeAst() {
+            return typeAst;
+        }
+
+        /**
+         * Get the associated {@link VariableDesc#scope}.
```
Comment (nmancus1) [inline src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java:433]: It would be better to not have to look at private class members to determine what a `scope` is in this context.

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java [hunk 36]
```diff
@@ -0,0 +1,457 @@
...
+         * Is the variable used again.
+         */
+        private boolean used;
+
+        /**
+         * Create a new VariableDesc instance.
+         *
+         * @param name name of the variable
+         * @param typeAst DetailAst of type {@link TokenTypes#TYPE}
+         * @param scope {@link VariableDesc#scope}
```
Comment (nmancus1) [inline src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java:406]: It would be better to not have to look at private class members to determine what a `scope` is in this context.

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java [hunk 37]
```diff
@@ -0,0 +1,457 @@
...
+         * Get the associated {@link VariableDesc#scope}.
+         *
+         * @return {@link VariableDesc#scope}.
+         */
+        public DetailAST getScope() {
+            return scope;
+        }
+
+        /**
+         * Is the variable used again or not.
```
Comment (nmancus1) [inline src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java:442]: `again` - to me, the variable is used or not. `again` sounds like a second usage.

File: src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/unusedlocalvariable/InputUnusedLocalVariable.java [hunk 38]
```diff
@@ -0,0 +1,204 @@
...
+
+
+*/
+
+package com.puppycrawl.tools.checkstyle.checks.coding.unusedlocalvariable;
+
+import java.util.ArrayList;
+import java.util.function.Predicate;
+
+public class InputUnusedLocalVariable {
```
Comment (nmancus1) [inline src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/unusedlocalvariable/InputUnusedLocalVariable.java:12]: Please add test cases for try with resources (passing and violation). Make sure to also have cases with multiple resources.

Comment (nmancus1) [inline src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/unusedlocalvariable/InputUnusedLocalVariable.java:12]: Please add test cases for try with resources (passing and violation). Make sure to also have cases with multiple resources.

**Review by nmancus1 — CHANGES_REQUESTED** [review]
Few items:

Edit: I noticed that the Javadoc shows an example of try with resources, but I do not see any test cases or logic necessary in check for `RESOURCE` tokens. Are we supporting this token? If so, we need to add this to default tokens. If not, it should be removed from examples in Javadoc.

https://github.com/checkstyle/checkstyle/blob/4bc137c125becdb6d66fdf6fa95fc2797b1783af/src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java#L78

File: src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/unusedlocalvariable/InputUnusedLocalVariable.java (hunk 38 above)
Comment (nmancus1) [reply src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/unusedlocalvariable/InputUnusedLocalVariable.java:12]: Disregard this if we are not supporting it.

Comment (Vyom-Yadav) [reply src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/unusedlocalvariable/InputUnusedLocalVariable.java:12]: Resources are automatically closed (unless you call `System.exit(..)` or turn off the power) so they cannot go unused, I didn't add them to the list of accepted tokens as there is no need for checking them, added the test case for them.

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java (hunk 37 above)
Comment (Vyom-Yadav) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java]: removed `again`

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java (hunk 34 above)
Comment (Vyom-Yadav) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java]: yes, `LITERAL_FOR` can be the parent, updated JavaDoc, `RESOURCES` can't be, for reason mentioned below.

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java (hunk 33 above)
Comment (Vyom-Yadav) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java]: removed

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java [hunk 39]
```diff
@@ -0,0 +1,457 @@
...
+    }
+
+    /**
+     * Checks whether the DetailAst of type {@link TokenTypes#IDENT} is
+     * used as left-hand side value. An identifier is being used as a left-hand side
+     * value if it is used as the left operand of an assignment or as an
+     * operand of a stand-alone increment or decrement.
+     *
+     * @param identAst DetailAst of type {@link TokenTypes#IDENT}
+     * @return True if identAst is used as a left-hand side value otherwise false.
```
[the remark this answers is not in the document]
Comment (Vyom-Yadav) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java]: done, removed `otherwise false`

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java [hunk 40]
```diff
@@ -0,0 +1,457 @@
...
+                || parent.getType() == TokenTypes.ASSIGN
+                && identAst != parent.getLastChild();
+    }
+
+    /**
+     * Checks whether the DetailAst of type {@link TokenTypes#IDENT} is used as
+     * an operand of a stand-alone increment or decrement.
+     *
+     * @param identAst DetailAst of type {@link TokenTypes#IDENT}
+     * @return True if identAst is used as an operand of stand-alone
```
[the remark this answers is not in the document]
Comment (Vyom-Yadav) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java]: done

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java (hunk 32 above)
Comment (Vyom-Yadav) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java:370]: Can be but the condition is quite complex for 30-40 characters, this line basically means-

- Is incremented or decremented and used as an argument (`foo.bar(++i);`)
- Is incremented or decremented and used for accessing array (`arr[++i]`)
- Is incremented or decremented and assigned to another variable (`int a = ++i;`)

`isUsedAsArgOrArrAccessorOrRHSAssignment(..)`
Doesn't look or sound good to me but I am open to suggestions

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java (hunk 35 above)
Comment (Vyom-Yadav) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java]: removed it.

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java (hunk 36 above)
Comment (Vyom-Yadav) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java:406]: removed it.

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java (hunk 35 above)
Comment (Vyom-Yadav) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java]: removed it

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java (hunk 39 above)
[the remark this answers is not in the document]
Comment (nmancus1) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java]: Resolved.

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java (hunk 40 above)
[the remark this answers is not in the document]
Comment (nmancus1) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java]: Resolved

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java (hunk 32 above)
Comment (nmancus1) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java:370]: All are children of `EXPR`, what do you think about `isUsedInExpression` ?

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java (hunk 33 above)
Comment (nmancus1) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java]: Resolved.

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java (hunk 34 above)
Comment (nmancus1) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java]: Resolved.

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java (hunk 35 above)
Comment (nmancus1) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java]: I should be more explicit; I think that the language used on private class member "The scope of variable is determined by..." and using the term "enclosing" is very descriptive, but this wording is not used in the constructor or accessor (the "API" of your `VariableDesc` class).

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java (hunk 37 above)
Comment (nmancus1) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java]: Resolved.

File: src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/unusedlocalvariable/InputUnusedLocalVariable.java (hunk 38 above)
Comment (nmancus1) [reply src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/unusedlocalvariable/InputUnusedLocalVariable.java:15]: Resolved.

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java (hunk 35 above)
Comment (Vyom-Yadav) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java]: Ah, sorry I didn't get it, changed it now.

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java (hunk 36 above)
Comment (Vyom-Yadav) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java]: Changed it.

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java (hunk 32 above)
Comment (Vyom-Yadav) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java:370]: `isUsedInExpr` would be misguiding, consider this example-
```
int a = 12;
++a;
```
parses as-
```
|--EXPR -> EXPR [9:8]
    `--INC -> ++ [9:8]
        `--IDENT -> a [9:10]
```
So `isUsedInExpression(..)` won't work but I get it debugging becomes quite tough with a blob of conditions, what about this-
```
private static boolean isIncrementedOrDecrementedOnRightHandSide(DetailAST grandParent) {
        return TokenUtil.isOfType(grandParent.getParent(),
                TokenTypes.ELIST, TokenTypes.INDEX_OP, TokenTypes.ASSIGN)
                && grandParent.getParent().getParent().getType() != TokenTypes.FOR_ITERATOR;
}
```
as all these conditions imply that the var is being incremented on the right-hand side of the expression. We can furthermore specify in the Javadoc comment what this actually means. Also, we can MAYBE replace IncrementedOrDecremented by variated or something [alike](https://english.stackexchange.com/questions/487090/increment-decrement-is-there-a-neutral-noun-like-crement)

Comment (nmancus1) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java:370]: > would be misguiding, consider this example...

According to logic in your check, the variable in your example is not "used". 

> Also, we can MAYBE replace IncrementedOrDecremented by variated or something alike...

A general term would just be postfix and prefix, at least this is shorter. `isPrefixOrPostfixOnRightHandSide`?

Either solution is good,

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java (hunk 36 above)
Comment (nmancus1) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java]: Resolved.

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java (hunk 32 above)
Comment (Vyom-Yadav) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java]: extracted to `isPrefixOrPostfixOnLeftHandSide` as I would have to negate the right-hand side condition (`!isPrefixOrPostfixOnRightHandSide(..)`).

Comment (nmancus1) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java]: > I would have to negate the right-hand side condition

Please explain why this is problematic. This makes sense to me, as you've described above.

return value of `isStandAloneIncrementOrDecrement` idea is the following, right?  

"variable should have parent that is inc/dec token AND variable should be part of an expression AND variable should not be used in that expression"

Comment (nmancus1) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java]: > "variable should have parent that is inc/dec token AND variable should be part of an expression AND variable should not be used in that expression"

If this is true, then why not:

```java
        return TokenUtil.isOfType(parent, INCREMENT_AND_DECREMENT_TOKENS)
                && TokenUtil.isOfType(grandParent, TokenTypes.EXPR)
                && !isUsedInExpression(identAst);
```
?

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java [hunk 41]
```diff
@@ -0,0 +1,473 @@
...
+
+    /**
+     * Checks whether the DetailAst of type {@link TokenTypes#IDENT} is used
+     * in prefix or postfix expression on the left-hand side.
+     *
+     * @param identAst DetailAst of type {@link TokenTypes#IDENT}
+     * @return true if identAst is used in prefix or postfix expression
+     *         on the left-hand side.
+     */
+    private static boolean isPrefixOrPostfixOnLeftHandSide(DetailAST identAst) {
```
Comment (nmancus1) [inline src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java:380]: At this point, we would know that we have an `EXPR` from condition on line 368. It would be good just to pass grandparent from `isStandAloneIncrementOrDecrement` here, and rename parameter to `expression`. This way, we can avoid a bunch of `.getParent()` calls.

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java (hunk 32 above)
Comment (Vyom-Yadav) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java]: > Please explain why this is problematic

It's fine, changed it to `isPrefixOrPostfixOnRightHandSide(..)`, had a faint memory that some check used to show an error when a method is just used once and is negated in that usage.

> variable should have parent that is inc/dec token AND variable should be part of an expression AND variable should not be used in that expression

This line sounds a bit confusing to me.

>  variable should have parent that is inc/dec token AND variable should be part of an expression 

it is fine till this point but the condition and should not be used in that expression sounds odd to me,
the word "used" would be confusing to understand as in this context it means `isConsideredUsedInExpr(..)` or specify in javadoc what used means here.

P.S.- My logic might not be making any sense but then it's just me

Comment (nmancus1) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java]:
```java
        x++; // not in expression, so not "used"
        System.out.println(y); // in method call expression, "used" (ELIST)
        int a = arr[w++]; // in assignment expression, "used" (INDEX_OP)
        int b = ++z; // in assignment expression, "used" (ASSIGN)

```

```
        |       |--EXPR -> EXPR [6:9]
        |       |   `--POST_INC -> ++ [6:9]
        |       |       `--IDENT -> x [6:8]
        |       |--SEMI -> ; [6:11]
        |       |--EXPR -> EXPR [7:26]
        |       |   `--METHOD_CALL -> ( [7:26]
        |       |       |--DOT -> . [7:18]
        |       |       |   |--DOT -> . [7:14]
        |       |       |   |   |--IDENT -> System [7:8]
        |       |       |   |   `--IDENT -> out [7:15]
        |       |       |   `--IDENT -> println [7:19]
        |       |       |--ELIST -> ELIST [7:27]
        |       |       |   `--EXPR -> EXPR [7:27]
        |       |       |       `--IDENT -> y [7:27]
        |       |       `--RPAREN -> ) [7:28]
        |       |--SEMI -> ; [7:29]
        |       |--VARIABLE_DEF -> VARIABLE_DEF [8:8]
        |       |   |--MODIFIERS -> MODIFIERS [8:8]
        |       |   |--TYPE -> TYPE [8:8]
        |       |   |   `--LITERAL_INT -> int [8:8]
        |       |   |--IDENT -> a [8:12]
        |       |   `--ASSIGN -> = [8:14]
        |       |       `--EXPR -> EXPR [8:19]
        |       |           `--INDEX_OP -> [ [8:19]
        |       |               |--IDENT -> arr [8:16]
        |       |               |--EXPR -> EXPR [8:21]
        |       |               |   `--POST_INC -> ++ [8:21]
        |       |               |       `--IDENT -> w [8:20]
        |       |               `--RBRACK -> ] [8:23]
        |       |--SEMI -> ; [8:24]
        |       |--VARIABLE_DEF -> VARIABLE_DEF [9:8]
        |       |   |--MODIFIERS -> MODIFIERS [9:8]
        |       |   |--TYPE -> TYPE [9:8]
        |       |   |   `--LITERAL_INT -> int [9:8]
        |       |   |--IDENT -> b [9:12]
        |       |   `--ASSIGN -> = [9:14]
        |       |       `--EXPR -> EXPR [9:16]
        |       |           `--INC -> ++ [9:16]
        |       |               `--IDENT -> z [9:18]

```

Comment (nmancus1) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java]: >should not be used in that expression sounds odd to me

Yes, I understand. It is "used" in higher ancestor expression, not grandparent

Comment (Vyom-Yadav) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java]: > // not in expression, so not "used"

This line is difficult to comprehend with respect to this AST

```
        |       |--EXPR -> EXPR [6:9]
        |       |   `--POST_INC -> ++ [6:9]
        |       |       `--IDENT -> x [6:8]
```
Someone who wants to make changes to this code in the future will not understand 
`not in expression, so not "used"` as it's right there "inside" the expression, maybe make it more clear by adding `not in the right-hand side expression, so not "used"` where we can specify what is considered to be a right-hand side expression.

Comment (nmancus1) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java]: I edited above comment, take a look

Comment (nmancus1) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java]: What about `hasExpressionAncestor`? I am good with current name, though, just trying to think of options.

Comment (Vyom-Yadav) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java]: > It is "used" in higher ancestor expression, not grandparent.

Ther is no expr node as an ancestor for `int b = ++z;`
```
        |--VARIABLE_DEF -> VARIABLE_DEF [12:8]
        |       |   |--MODIFIERS -> MODIFIERS [12:8]
        |       |   |--TYPE -> TYPE [12:8]
        |       |   |   `--LITERAL_INT -> int [12:8]
        |       |   |--IDENT -> b [12:12]
        |       |   `--ASSIGN -> = [12:14]
        |       |       `--EXPR -> EXPR [12:16]
        |       |           `--INC -> ++ [12:16]
        |       |               `--IDENT -> z [12:18]

```

Comment (nmancus1) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java]: `=` is expression by java grammar, but not checkstyle grammar :) This could be confusing difference for future maintainers, I agree

Comment (Vyom-Yadav) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java]: `isPrefixOrPostfixUsed` sounds good to me

Comment (nmancus1) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java]: I agree.

Comment (nmancus1) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java]: Resolved.

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java (hunk 41 above)
Comment (nmancus1) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java]: Resolved.

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java (hunk 32 above)
Comment (nmancus1) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java]: Resolved.

Comment (Vyom-Yadav) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java]: Changed it to `isPrefixOrPostfixVariableUsed` as it could also mean `isPrefixOrPostfixOperatorUsed`

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java (hunk 41 above)
Comment (Vyom-Yadav) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java]: done

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java (hunk 32 above)
Comment (nmancus1) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java]: Just had another thought; what about `isStandAloneUsed`? This avoids having both increment/decrement and prefix/postfix nomenclature in the same method, and continues to use the same term, 'standAlone'?

Comment (Vyom-Yadav) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java]: `isStandAloneUsed` sounds like it's talking about whether an operator or property called `StandAlone` is used, I think the current one is more expressive.

Comment (nmancus1) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java]: That makes sense. It would probably be good to use `isIncrementOrDecrementVariableUsed` to be consistent, it is only a few letters difference now.

Either way, you can resolve this.

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java [hunk 42]
```diff
@@ -0,0 +1,472 @@
...
+ * class Test {
+ *
+ *     int a;
+ *
+ *     {
+ *         int k = 12; // violation, assigned and updated but never used
+ *         k++;
+ *     }
+ *
+ *     Test(int a) { // ok as 'a' is a method parameter not a local variable
```
Comment (nmancus1) [inline src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java:57]: `method` -> `constructor`

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java [hunk 43]
```diff
@@ -0,0 +1,472 @@
...
+ *         String s = newValue.toLowerCase(); // violation
+ *         return newValue.toLowerCase();
+ *     }
+ *
+ *     void read() throws IOException {
+ *         BufferedReader reader = new BufferedReader(new InputStreamReader(System.in));
+ *         String s; // violation
+ *         while ((s = reader.readLine()) != null) {
+ *         }
+ *         try (BufferedReader reader1 = new BufferedReader(new FileReader("abc.txt"))) { // ok
```
Comment (nmancus1) [inline src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java:78]: please add explanation here, just an `// ok` comment leads me to believe that there exists a case where this could be a violation, maybe something like `resources are not checked` or `ok as reader1 is a resource`?

**Review by nmancus1 — CHANGES_REQUESTED** [review]
Few minor items:

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java (hunk 43 above)
Comment (Vyom-Yadav) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java]: done

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java (hunk 42 above)
Comment (Vyom-Yadav) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java]: done

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java (hunk 32 above)
Comment (Vyom-Yadav) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java]: Done

**Comment by Vyom-Yadav** [comment]
Github, generate report

**Comment by Vyom-Yadav** [comment]
Github, generate report

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java (hunk 32 above)
Comment (nmancus1) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java]: Resolved.

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java (hunk 41 above)
Comment (nmancus1) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java]: Resolved.

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java (hunk 42 above)
Comment (nmancus1) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java]: Resolved.

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java (hunk 43 above)
Comment (nmancus1) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java]: Resolved.

**Review by nmancus1 — APPROVED** [review]
I have not been able to review final diff report, due to report generation failure, but I do not want to hold up review on this PR from this. We can take a look at final report when we get report generation working again, or just manually generate a report and share it here.

File: src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheckTest.java (hunk 1 above)
Comment (nmancus1) [reply src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheckTest.java]: @Vyom-Yadav please resolve this item if you are satisfied.

**Comment by nmancus1** [comment]
Github, generate report

**Comment by nmancus1** [comment]
@Vyom-Yadav please either remove excluded files from your projects file, or use default projects file.

**Comment by Vyom-Yadav** [comment]
Github, generate report

**Comment by nmancus1** [comment]
@Vyom-Yadav please send PR to contibution repo like checkstyle/contribution#585 to add this check to regression testing configs

**Comment by Vyom-Yadav** [comment]
created PR at https://github.com/checkstyle/contribution/pull/586

**Review by romani — APPROVED** [review]
@Vyom-Yadav , good job, I reviewed report (for majority of case) and did not found any false positives.

**Comment by romani** [comment]
Github, rebase

**Comment by romani** [comment]
CI was fully green, rebased manually

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java [hunk 44]
```diff
@@ -0,0 +1,474 @@
...
+ *     }
+ *
+ *     Test(int a) {   // ok as 'a' is a constructor parameter not a local variable
+ *         this.a = 12;
+ *     }
+ *
+ *     void method(int b) {
+ *         int a = 10;             // violation
+ *         int[] arr = {1, 2, 3};  // violation
+ *         int[] anotherArr = {1}; // ok
```
Comment (rnveach) [inline src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java:64]: > That is a different check IMO

If this is the case, then we need the top documentation to mention that along with the pattern variables and why.

File: src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheckTest.java [hunk 45]
```diff
@@ -0,0 +1,102 @@
...
+
+import static com.google.common.truth.Truth.assertWithMessage;
+import static com.puppycrawl.tools.checkstyle.checks.coding.UnusedLocalVariableCheck.MSG_UNUSED_LOCAL_VARIABLE;
+
+import org.junit.jupiter.api.Test;
+
+import com.puppycrawl.tools.checkstyle.AbstractModuleTestSupport;
+import com.puppycrawl.tools.checkstyle.api.TokenTypes;
+
+public class UnusedLocalVariableCheckTest extends AbstractModuleTestSupport {
```
Comment (rnveach) [inline src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheckTest.java:30]: I am not seeing any input examples for do-while loops, lambda parameters, or pattern variables.
I am also not seeing any examples of various odd assignments like `<<=`, `>>=`, `-=`, `/=`, etc..

I would also like to see an example where a nested anonymous class has a variable name clash with the same named variable outside the anonymous class.

Also what about a variable name that matches the name of a package but is not the package used?
Example:
````
int checks = 0;
com.puppycrawl.tools.checkstyle.checks.coding.unusedlocalvariable.InputUnusedLocalVariable.testCallingMethods();
````

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java [hunk 46]
```diff
@@ -0,0 +1,474 @@
...
+        TokenTypes.POST_INC,
+        TokenTypes.POST_DEC,
+        TokenTypes.INC,
+        TokenTypes.DEC,
+    };
+
+    /**
+     * An array of scope tokens.
+     */
+    private static final int[] SCOPES = {
```
Comment (rnveach) [inline src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java:139]: why isn't LITERAL_DO needed here?

**Review by rnveach — CHANGES_REQUESTED** [review]

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java [hunk 47]
```diff
@@ -0,0 +1,516 @@
...
+    }
+
+    @Override
+    public int[] getRequiredTokens() {
+        return getDefaultTokens();
+    }
+
+    @Override
+    public void beginTree(DetailAST root) {
+        variables = new ArrayDeque<>();
```
Comment (rnveach) [inline src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java:198]: https://github.com/checkstyle/checkstyle/pull/10930/files#r754274388
https://github.com/checkstyle/checkstyle/pull/10930/files#r762410744
> we would have to add the survived mutation in the ignore list

Surviving mutation in this instance would be accurate because you have no code saying that we need to clear the list after the first file run. Pitest does not always mean tests can't be created.

I agree this should be changed as other suppression denotes, we should declare the instance as part of the constructor and not need to recreate the class for every file. Field should be cleared on begin tree, not for finishing it. We are only concerned about initializing the fields for the current file.

For creating a test, this is not the first time we have run into this. See https://github.com/checkstyle/checkstyle/blob/1128b5e1c44338b4414d6ec2e55707ac20984399/src/test/java/com/puppycrawl/tools/checkstyle/internal/utils/TestUtil.java#L145 and some examples on how to create a test for this to satisfy pitest.

**Review by rnveach — CHANGES_REQUESTED** [review]
Another item since previous comments are still being worked on.

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java (hunk 44 above)
Comment (Vyom-Yadav) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java:69]: Added to the top documentation.

File: src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheckTest.java (hunk 45 above)
Comment (Vyom-Yadav) [reply src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheckTest.java:37]: > I am not seeing any input examples for do-while loops, lambda parameters, or pattern variables.

Added examples for do-while loops, lambda parameters are not classified as local variables by [JLS](https://docs.oracle.com/javase/specs/jls/se17/html/jls-4.html#jls-4.12.3), pattern variables are not supported yet, I am working on that issue, fix is a bit complicated, discussed [here](https://github.com/checkstyle/checkstyle/issues/10969#issuecomment-982684864).

> I am also not seeing any examples of various odd assignments like <<=, >>=, -=, /=, etc..

Added those examples.

>I would also like to see an example where a nested anonymous class has a variable name clash with the same named variable outside the anonymous class.

Thanks for this one, this was not supported as instance variables were not stored but I added the support for them too.

> Also what about a variable name that matches the name of a package but is not the package used?

Added.

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java (hunk 46 above)
Comment (Vyom-Yadav) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java:144]: Actually at present `LITERAL_WHILE` and `LITERAL_IF` are also not needed, these token were left by mistake when I removed the partial support for pattern variables.
```
Object o = 12;
if(o instanceof String s) {} // scope is LITERAL_IF
while(o instanceof String s) {} // scope is LITERAL_WHILE
```
But LITERAL_DO can't be the scope as pattern variables introduced in while statements of do-while loops are not accessible in `do {}`
```
Object o = 12;
do {
     System.out.println(s); // s is not accessible here
                            // so scope of 's' would be LITERAL_WHILE
} while (o instanceof String s);
```

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java (hunk 47 above)
Comment (Vyom-Yadav) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java]: Done

**Comment by Vyom-Yadav** [comment]
Github, generate report

**Comment by Vyom-Yadav** [comment]
The difference in checkstyle project in diff report is due to updates in the master branch, I checked that locally with patch branch in the older diff report as base branch and curr branch as patch branch, no changes were noticed.
Link to the same - https://vyom-yadav.github.io/DiffReport/diff3/index.html

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java (hunk 46 above)
Comment (rnveach) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java:144]: I am confused then. I was not talking about LITERAL_DO from the prospect of pattern variables. The variable named scopes, so I thought this was a list of scopes to denote where the variable "lives" so it can be used for it's tracking of unused-ness.

So why are only these specific scopes needed?
Does the following type of code not cause an issue with scope in this check?
````
while (condition) {
   int var = 0; // unused
}
int var = 1; // used in different scope
System.out.println(var);
````

File: src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheckTest.java (hunk 45 above)
Comment (rnveach) [reply src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheckTest.java:37]: > lambda parameters are not classified as local variables by JLS

Yes, but what I am concerned about is name clashes. Yes your check shouldn't process lambda parameters, but what happens if a lambda parameter is given the same name as a local variable and the lambda parameter is used. Will your check accidentally assume the local variable is what is being used instead of the lambda? I want to make sure we have coverage for false positives.

> this was not supported as instance variables were not stored 

What about non-instance variables?
````
int var = 0; // unused
new MyClass() {
    public void myMethod() {
        int var = 1; // used but in different scope
        System.out.println(var);
    }
}
````

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java (hunk 46 above)
Comment (Vyom-Yadav) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java:144]: > So why are only these specific scopes needed?

We need `SLIST` for `{`, `LITERAL_FOR` for `for(int i=0;;);` and 
`OBJBLOCK` for instance var under `{`

> Does the following type of code not cause an issue with scope in this check?

Here the scope will not be LITERAL_WHILE, it will be SLIST(`{`), and `int var = 0;` will be popped out of the scope when we leave SLIST(`{`) so there won't be an issue.

File: src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheckTest.java (hunk 45 above)
Comment (Vyom-Yadav) [reply src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheckTest.java:37]: > Yes, but what I am concerned about is name clashes. Yes your check shouldn't process lambda parameters, but what happens if a lambda parameter is given the same name as a local variable and the lambda parameter is used.

If there is a local variable in-scope then the lambda parameter cannot have the same name.

> What about non-instance variables?

This will work fine, wont give any FP's.

**Comment by Vyom-Yadav** [comment]
I have a case to discuss, consider the following code-
```
class a {
    int a = 12;

    void method() {
        int a = 12; // unused
        a obj = new a() {
            void method() {
                a = 1; // instance var 'a' not local var
            }
        };
    }
}
```
Instance variable shadows the local var if having the same name. This is not supported yet but isn't difficult to support but there are complex cases involving anonymous inner classes, consider-
```
class b {
    int c = 12;
}

class a extends b {

    void method() {
        int c = 12; // unused
        a obj = new a() {
            void method() {
                c = 1; // instance var 'c'(inherited from super class) not local var
            }
        };
    }
}
```
Now, this class `b` could be declared after class `a`, class `b` could be deeply nested somewhere in the same file, above or below. So to support such a case, I would have to traverse all the classes and interfaces first, store their instance variables then traverse the whole AST again for normal checking whether a variable is used or not. Though this will have a limitation that cross-file checking will not be supported i.e. class `a` and `b` are in different files.
@nmancus1 @romani @rnveach @pbludov @strkkk Please share your thoughts.

**Comment by romani** [comment]
>Though this will have a limitation that cross-file checking will not be supported

We do not support any cross file validation. On any cases like this we should not make any violations.  If we are not sure, we should not put violation.

**Comment by rnveach** [comment]
Multi-file validation is https://github.com/checkstyle/checkstyle/issues/3540

**Comment by Vyom-Yadav** [comment]
> Better to support. We already have Checks that are java scope aware - RequireThis.

I will add the support, not that challenging,  was just sharing that we would have a traverse the whole AST twice in a single file to achieve that

**Comment by rnveach** [comment]
@Vyom-Yadav Would it help your code if you did something like https://github.com/checkstyle/checkstyle/issues/8126 first?

**Comment by romani** [comment]
You do not need to traverse twice, you listen for variable definition and do extra going up to understand scope of visibility of variable.

**Comment by Vyom-Yadav** [comment]
> You do not need to traverse twice, you listen for variable definition and do extra going up to understand scope of visibility of variable.

It isn't necessarily up, lets see an example-
```
class a extends b {

    void method() {
        int c = 12; // unused
        a obj = new a() {
            void method() {
                c = 1; // instance var 'c' not local var
            }
        };
    }
}

class Tea {
    int a;
}


class b {
    int c = 12;
}
```
Traversal hasn't even reached class `b` and its instance variables come into the play. Here even if we go with the _going up_ approach we would have to search for class `b` to store its instance variables. So we would have to traverse the AST twice.

**Comment by Vyom-Yadav** [comment]
> Would it help your code if you did something like #8126 first?

@rnveach It might have helped if I did it before I made this PR but now I have resolved the scope of all the variables, the case I mentioned above will also be added.

**Comment by romani** [comment]
> c = 1; // instance var 'c' not local var

please make sure you operate by compile-able source files, I do not think it is compile-able.
We can put some limitation is detection to not validate unused between classes.
Usually users are  not operating on all public fields, if they are .... they are in bigger trouble and non of tools going to help them.
Our primary goal is to not raise violation on line where it is not a problem. It is ok to skip problematic line and let other tool to deal with them or rely on humans.

**Comment by Vyom-Yadav** [comment]
> > c = 1; // instance var 'c' not local var
> 
> please make sure you operate by compile-able source files, I do not think it is compile-able. 

@romani 
Um, it is compilable, even with java 8, here is a running example-
```
$ javac a.java   
```

```
package TestP;

public class a extends b {

    public static void main(String[] args) {
        String c = "I'm in class a"; // unused
        a obj = new a() {
            @Override
            public String toString() {
                return c;
            }
        };
        System.out.println(obj);
    }
}


class b {
    String c = "I'm in class b";
}
```

Output-
```
I'm in class b
```

I am ok with skipping cases where classes extend each other, what about cases like these-
```
public class a { // b is nested inside a

    public static void main(String[] args) {
        String c = "I'm in class a"; // unused
        b obj = new a().new b() {
            @Override
            public String toString() {
                return c;
            }
        };
        System.out.println(obj);
    }

    class b {
        String c = "I'm in class b";
    }
}
```
OR
```
public class a { // b is a separate class

    public static void main(String[] args) {
        String c = "I'm in class a"; // unused
        b obj = new b() {
            @Override
            public String toString() {
                return c;
            }
        };
        System.out.println(obj);
    }
}

class b {
    String c = "I'm in class b";
}
```

**Comment by Vyom-Yadav** [comment]
@romani Please suggest.

**Comment by rnveach** [comment]
@Vyom-Yadav there is a file conflict.

File: src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/unusedlocalvariable/InputUnusedLocalVariable.java [hunk 48]
```diff
@@ -0,0 +1,283 @@
...
+        @Override
+        public void method() {
+        }
+    }
+
+    public void testDifferentAssignments() {
+        int a = 12; // violation
+        a = 13;
+        int b = 13; // ok
+        b /= 12;
```
Comment (rnveach) [inline src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/unusedlocalvariable/InputUnusedLocalVariable.java:206]: Why is `b` ok but `a` is basically the same thing and has a violation? Same with c and h?

Comment (Vyom-Yadav) [reply src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/unusedlocalvariable/InputUnusedLocalVariable.java:206]: `a` is simply assigned the value `13` but `b` is not simply assigned, `b = b/12` so `b` will be considered as used, same for others.

**Comment by rnveach** [comment]
@Vyom-Yadav Keep it at 1 commit. No merge commits.

**Comment by Vyom-Yadav** [comment]
> @Vyom-Yadav Keep it at 1 commit. No merge commits.

I was trying out GH Cli, give me a moment to fix this mess

**Comment by Vyom-Yadav** [comment]
@rnveach Sorted it out, can I get your opinion on https://github.com/checkstyle/checkstyle/pull/10930#issuecomment-1001075012 and https://github.com/checkstyle/checkstyle/pull/10930#issuecomment-1001110309, what do you expect for these cases?

**Comment by Vyom-Yadav** [comment]
https://github.com/checkstyle/checkstyle/pull/10930#issuecomment-1001110309 Didn't get any clarification on it so am adding support for all cases except classes extending each other.

**Comment by Vyom-Yadav** [comment]
@romani @rnveach Added support for local anon inner classes. There are methods that will be extracted to util after merging #10968. This approach is better than traversing the whole AST again, if we encounter a local anon inner class, we don't process that particular block save the topmost ast node of the block and process it while leaving `COMPILATION_UNIT`.

**Comment by Vyom-Yadav** [comment]
Github, generate report

**Comment by Vyom-Yadav** [comment]
Github, generate report

**Comment by Vyom-Yadav** [comment]
Github, generate report

**Comment by Vyom-Yadav** [comment]
@nmancus1 Could you review again, lot of changes have been made since the last review.

**Review by rnveach — APPROVED** [review]

**Comment by nmancus1** [comment]
@Vyom-Yadav wercker failure is in sonar: https://sonarcloud.io/project/issues?id=org.checkstyle%3Acheckstyle&open=AX5dYVkPY0PN-XIB_Rj8&pullRequest=10930&resolved=false&severities=MAJOR&sinceLeakPeriod=true .

Please also see TC failure.

**Comment by nmancus1** [comment]
Github, generate site

File: config/pmd.xml [hunk 49]
```diff
@@ -320,22 +320,27 @@
     <properties>
       <property name="maxmethods" value="20"/>
       <!-- The class PackageObjectFactory has many boilerplate methods.
-           JavadocMethodCheck is in the process of being rewritten. -->
+           JavadocMethodCheck is in the process of being rewritten.
+           UnusedLocalVariable has some methods that would be moved to util
```
Comment (nmancus1) [inline config/pmd.xml:324]: Please share link to discussion about this.

Comment (Vyom-Yadav) [reply config/pmd.xml:324]: There was no major discussion, https://github.com/checkstyle/checkstyle/pull/10930#issuecomment-1000910938 and some following comments, the methods that will be moved to util have it written in their Javadoc, example is mentioned below

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java [hunk 50]
```diff
@@ -0,0 +1,1153 @@
...
+        return Collections.min(classesWithSameName, (first, second) -> {
+            int diff = Integer.compare(
+                    classNameMatchingCount(outerClassName, second.getQualifiedName()),
+                    classNameMatchingCount(outerClassName, first.getQualifiedName()));
+            if (diff == 0) {
+                diff = Integer.compare(first.getDepth(), second.getDepth());
+            }
+            return diff;
+        });
+    }
```
Comment (Vyom-Yadav) [inline src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java:641]:
```
Duplicated, will be moved to util after merging
https://github.com/checkstyle/checkstyle/pull/10968
```
Though I can still move it to util, that will block that PR, there are 5-6 methods like this.

File: config/pmd.xml (hunk 49 above)
Comment (nmancus1) [reply config/pmd.xml:324]: Thanks for explaining. Let's make an issue for this now so that we do not forget. If you think that we can remove suppression for `ExcessiveClassLength` once methods are moved to util class, let's mention that in the issue as well. Then we can change the comments in this file to simple `until...`

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java [hunk 51]
```diff
@@ -0,0 +1,1154 @@
...
+     *
+     * @param obtainedClass super class of the anon inner class
+     * @param variablesStack stack of all the relevant variables in the scope
+     * @param literalNewAst ast node of type {@link TokenTypes#LITERAL_NEW}
+     */
+    private void modifyVariablesStack(ClassDesc obtainedClass,
+            Deque<VariableDesc> variablesStack,
+            DetailAST literalNewAst) {
+        if (obtainedClass != null) {
+            final Deque<VariableDesc> instAndClassVarDeque = classAstToClassDesc.get(
```
Comment (nmancus1) [inline src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java:634]: Can we do:

```
            final Deque<VariableDesc> instAndClassVarDeque = classesWithInstAndClassVar
                              .get(obtainedClass.getClassOrInterfaceAst())
                              .getUpdatedCopyOfVarStack(literalNewAst);


```

I think this is easier to read.

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java [hunk 52]
```diff
@@ -0,0 +1,1154 @@
...
+     * <a>https://github.com/checkstyle/checkstyle/pull/10968</a>
+     *
+     * @param className name of the class
+     * @return true if there is another class with same name.
+     * @noinspection CallToStringConcatCanBeReplacedByOperator
+     */
+    private List<ClassDesc> classesWithSameName(String className) {
+        return classAstToClassDesc.values().stream()
+                .filter(classDesc -> {
+                    return classDesc.getQualifiedName().endsWith(
```
Comment (nmancus1) [inline src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java:651]: Similar to above, can we do:

```
return classDesc.getQualifiedName()
        .endsWith(PACKAGE_SEPARATOR.concat(className));

```
?

File: config/pmd.xml (hunk 49 above)
Comment (Vyom-Yadav) [reply config/pmd.xml:324]: Also include the nested static class ClassDesc, final class check also contains a class called ClassDesc, we may merge both of these classes and extract it somewhere, there are some overlapping properties. I have also mentioned this in Javadoc of the class.

Comment (Vyom-Yadav) [reply config/pmd.xml:324]: @nmancus1 Created issue at  #11201

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java [hunk 53]
```diff
@@ -0,0 +1,1154 @@
...
+        TokenTypes.LITERAL_NEW,
+        TokenTypes.PATTERN_VARIABLE_DEF,
+        TokenTypes.METHOD_CALL,
+        TokenTypes.TYPE,
+    };
+
+    /**
+     * An array of blocks in which local anon inner classes can exist.
+     */
+    private static final int[] CONTAINERS_FOR_ANON_INNERS = {
```
Comment (nmancus1) [inline src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java:186]: Anonymous inner classes can be declared in compact constructors, why aren't they listed here?

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java [hunk 54]
```diff
@@ -0,0 +1,1148 @@
...
+            final DetailAST parentAst = identAst.getParent();
+            if (!TokenUtil.isOfType(parentAst, UNACCEPTABLE_PARENT_OF_IDENT)
+                    && shouldCheckIdentWithMethodRefParent(identAst)) {
+                checkIdentifierAst(identAst, variablesStack);
+            }
+        }
+    }
+
+    /**
+     * Visit ast of type {@link TokenTypes#CLASS_DEF}.
```
Comment (nmancus1) [inline src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java:400]: Description and name of method aren't consistent.

File: config/pmd.xml (hunk 49 above)
Comment (Vyom-Yadav) [reply config/pmd.xml]: @nmancus1 The confusion that whether we would be able to remove `MethodCount` suppression is due to this conflicting rule-
https://github.com/checkstyle/checkstyle/blob/fc65adcd5630e12ead59561abceb6794211c95f0/config/checkstyle_checks.xml#L794-L795

https://github.com/checkstyle/checkstyle/blob/fc65adcd5630e12ead59561abceb6794211c95f0/config/pmd.xml#L319-L321

Checkstyle has a limit of 34 and PMD has a limit of 20, we would be able to get under 34 but not under 20.

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java [hunk 55]
```diff
@@ -0,0 +1,1148 @@
...
+        TokenTypes.CTOR_DEF,
+        TokenTypes.STATIC_INIT,
+        TokenTypes.INSTANCE_INIT,
+    };
+
+    /**
+     * An array of class and interface and annotated interface tokens
+     * and enum.
+     */
+    private static final int[] CLASS_AND_INTERFACE = {
```
Comment (nmancus1) [inline src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java:197]: Can we use `TokenUtil.isTypeDeclaration()` instead of this array and `TokenUtil.isOfType()`? Are we excluding records for a reason?

**Review by nmancus1 — CHANGES_REQUESTED** [review]
Few items:

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java (hunk 53 above)
Comment (Vyom-Yadav) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java:186]: I missed records, added support for them now.

File: src/main/java/com/puppycrawl/tools/checkstyle/api/FullIdent.java [hunk 56]
```diff
@@ -85,7 +85,13 @@ private static void extractFullIdent(FullIdent full, DetailAST ast) {
                         || nextSibling.getType() == TokenTypes.ANNOTATIONS)
                     && isArrayTypeDeclaration(nextSibling);
 
-            if (ast.getType() == TokenTypes.DOT) {
+            // support for new class().new class2();
+            if (ast.getType() == TokenTypes.LITERAL_NEW
```
[the remark this answers is not in the document]
Comment (Vyom-Yadav) [reply src/main/java/com/puppycrawl/tools/checkstyle/api/FullIdent.java]: Done

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java (hunk 55 above)
Comment (Vyom-Yadav) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java]: Yes, we can use it, I missed records but they are now supported.

File: pom.xml [hunk 57]
```diff
@@ -3174,6 +3174,7 @@
               </targetClasses>
               <targetTests>
                 <param>com.puppycrawl.tools.checkstyle.api.*</param>
+                <param>com.puppycrawl.tools.checkstyle.checks.coding.UnusedLocalVariableCheckTest</param>
```
[the remark this answers is not in the document]
Comment (Vyom-Yadav) [reply pom.xml:3177]: Done

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java (hunk 52 above)
Comment (Vyom-Yadav) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java]: Done

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java (hunk 51 above)
Comment (Vyom-Yadav) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java]: Yes, it is definitely better. Done.

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java [hunk 58]
```diff
@@ -0,0 +1,1153 @@
...
+    }
+
+    /**
+     * Whether instance variable or class variable has private access modifier.
+     *
+     * @param varDefAst ast node of type {@link TokenTypes#VARIABLE_DEF}
+     * @return true if instance variable or class variable has private access modifier
+     */
+    private static boolean isPrivateInstanceVariable(DetailAST varDefAst) {
+        return CheckUtil.getAccessModifierFromModifiersToken(
```
[the remark this answers is not in the document]
Comment (Vyom-Yadav) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java]: Line length wasn't permitting, extracted to var, it looks better now.

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java (hunk 54 above)
Comment (Vyom-Yadav) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java]: Done, explicitly mentioned types to be clear.

**Comment by romani** [comment]
all CI is green except for  pitest ant failure:
`-CheckstyleAntTask.java.html:<td class='covered'><pre><span  class='survived'>            if (toFile == null || !useFile) {</span></pre></td></tr>`

restarted.

**Review by nmancus1 — CHANGES_REQUESTED** [review]
Few more:

File: config/pmd.xml (hunk 49 above)
Comment (nmancus1) [reply config/pmd.xml]: Thanks for explaining, is there some nuance of the pmd check that requires different maximum here?

Comment (Vyom-Yadav) [reply config/pmd.xml]: I don't think so, I would have accepted if it was 34 for PMD and 20 for CS as https://checkstyle.sourceforge.io/config_sizes.html#MethodCount calculated method count for only main type declaration parent, if there is a nested class and that has a method, it won't increase the count for the outer class whereas PMD on the other hand just calculated the total number of methods
https://pmd.github.io/latest/pmd_rules_java_design.html#toomanymethods (see the XPath Expr part).
I feel a new issue should be raised regarding this.

**Review by pbludov — APPROVED** [review]

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java [hunk 59]
```diff
@@ -0,0 +1,1144 @@
...
+    /** Package separator. */
+    private static final String PACKAGE_SEPARATOR = ".";
+
+    /**
+     * Keeps tracks of the variables declared in file.
+     */
+    private final Deque<VariableDesc> variables;
+
+    /**
+     * Keeps track of all the classes, interfaces, annotated interfaces, records
```
[the remark this answers is not in the document]
Comment (Vyom-Yadav) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java]: Yes, it is indeed very easy to miss, so I resorted to `type declarations`, the only place where I didn't use type declaration was for specifying the superclass of the anon inner class, yes an anon inner can be derived out of an interface but if I change it to super type declaration it sounds weird to me. Also, I kept the term class variables [jls](https://docs.oracle.com/javase/specs/jls/se17/html/jls-4.html#jls-4.12.3) properly defines it for us

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java [hunk 60]
```diff
@@ -0,0 +1,1144 @@
...
+            visitDotToken(ast, variables);
+        }
+        else if (type == TokenTypes.VARIABLE_DEF) {
+            visitVariableDefToken(ast);
+        }
+        else if (type == TokenTypes.IDENT) {
+            visitIdentToken(ast, variables);
+        }
+        else if (TokenUtil.isTypeDeclaration(type)) {
+            visitClassOrInterfaceToken(ast);
```
[the remark this answers is not in the document]
Comment (Vyom-Yadav) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java]: Done

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java [hunk 61]
```diff
@@ -0,0 +1,1144 @@
...
+            final DetailAST parentAst = identAst.getParent();
+            if (!TokenUtil.isOfType(parentAst, UNACCEPTABLE_PARENT_OF_IDENT)
+                    && shouldCheckIdentWithMethodRefParent(identAst)) {
+                checkIdentifierAst(identAst, variablesStack);
+            }
+        }
+    }
+
+    /**
+     * Visit ast of type {@link TokenTypes#CLASS_DEF} or {@link TokenTypes#ENUM_DEF} or
```
[the remark this answers is not in the document]
Comment (Vyom-Yadav) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java]: Done

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java [hunk 62]
```diff
@@ -0,0 +1,1144 @@
...
+     * {@link TokenTypes#INTERFACE_DEF} or {@link TokenTypes#ANNOTATION_DEF} or
+     * {@link TokenTypes#RECORD_DEF}.
+     *
+     * @param ast ast
```
[the remark this answers is not in the document]
Comment (Vyom-Yadav) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java]: > `@param ast ast` -> `@param ast type declaration ast`?

Done.
> I am not sure if register is the best word to use ....

There are only 2 methods which use the word register-
`registerAsUsed(..)`
`registerAsInstOrClassVar(..)`

They sound fine to me, suppose I am in a line where they are registering who is above 6ft, if I am above 6ft they would be like - "Ok you are above 6ft, let's put a tick  in front of his name or lets **register** him as taller than 6ft". I am open to other suggestions.

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java [hunk 63]
```diff
@@ -0,0 +1,1144 @@
...
+        for (int i = 0; i < length && patternClass.charAt(i) == classToBeMatched.charAt(i); ++i) {
+            if (patternClass.charAt(i) == packageSeparator) {
+                result = i;
+            }
+        }
+        return result;
+    }
+
+    /**
+     * Get qualified class name from given class Ast.
```
[the remark this answers is not in the document]
Comment (Vyom-Yadav) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java]: done

**Comment by romani** [comment]
azure is relaunched

File: pom.xml (hunk 57 above)
[the remark this answers is not in the document]
Comment (nmancus1) [reply pom.xml:3176]: Resolved.

File: src/main/java/com/puppycrawl/tools/checkstyle/api/FullIdent.java (hunk 56 above)
[the remark this answers is not in the document]
Comment (nmancus1) [reply src/main/java/com/puppycrawl/tools/checkstyle/api/FullIdent.java]: Resolved.

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java (hunk 58 above)
[the remark this answers is not in the document]
Comment (nmancus1) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java]: Resolved.

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java (hunk 51 above)
Comment (nmancus1) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java]: Resolved.

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java (hunk 52 above)
Comment (nmancus1) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java]: Resolved.

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java (hunk 53 above)
Comment (nmancus1) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java:186]: Resolved.

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java (hunk 54 above)
Comment (nmancus1) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java]: Resolved.

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java (hunk 55 above)
Comment (nmancus1) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java]: Resolved.

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java (hunk 59 above)
[the remark this answers is not in the document]
Comment (nmancus1) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java]: Resolved.

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java (hunk 60 above)
[the remark this answers is not in the document]
Comment (nmancus1) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java]: Resolved.

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java (hunk 61 above)
[the remark this answers is not in the document]
Comment (nmancus1) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java]: Resolved.

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java (hunk 62 above)
[the remark this answers is not in the document]
Comment (nmancus1) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java]: On second thought, perhaps I should follow my own advice: `Life has shown that it is better to be a bit more abstract`.

Resolved.

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java (hunk 63 above)
[the remark this answers is not in the document]
Comment (nmancus1) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java]: Resolved.

**Review by nmancus1 — APPROVED** [review]
