### PR TITLE
Issue #13830: Support Java 21 string template syntax

### LINKED ISSUE #13830: Support Java 21 string template syntax
I have executed the cli and showed it below, as cli describes the problem better than 1,000 words

```bash
❯ javac --enable-preview --release 21 src/main/java/HelloWorld.java
Note: src/main/java/HelloWorld.java uses preview features of Java SE 21.
Note: Recompile with -Xlint:preview for details.

/var/tmp $ cat config.xml
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC "-//Checkstyle//DTD Checkstyle Configuration 1.3//EN" "https://checkstyle.org/dtds/configuration_1_3.dtd">
<module name="Checker">

    <module name="NewlineAtEndOfFile">
        <property name="lineSeparator" value="lf"/>
    </module>

    <module name="TreeWalker">
        <module name="UnusedImports"/>
    </module>
</module>


/var/tmp $ cat YOUR_FILE.java
public class HelloWorld {
    public static void main(String[] args) {
        int x = 10;
        int y = 20;
        String result = STR."\{x} + \{y} = \{x + y}";
        System.out.println(result);
    }
}

/var/tmp $ RUN_LOCALE="-Duser.language=en -Duser.country=US"
/var/tmp $ java $RUN_LOCALE -jar checkstyle-X.XX-all.jar -c config.xml YOUR_FILE.java
> java $RUN_LOCALE -jar checkstyle-10.12.4-all.jar -c checkstyle.xml src/main/java/HelloWorld.java 

Starting audit...
com.puppycrawl.tools.checkstyle.api.CheckstyleException: Exception was thrown while processing src/main/java/HelloWorld.java
        at com.puppycrawl.tools.checkstyle.Checker.processFiles(Checker.java:309)
        at com.puppycrawl.tools.checkstyle.Checker.process(Checker.java:226)
        at com.puppycrawl.tools.checkstyle.Main.runCheckstyle(Main.java:415)
        at com.puppycrawl.tools.checkstyle.Main.runCli(Main.java:338)
        at com.puppycrawl.tools.checkstyle.Main.execute(Main.java:195)
        at com.puppycrawl.tools.checkstyle.Main.main(Main.java:130)
Caused by: com.puppycrawl.tools.checkstyle.api.CheckstyleException: IllegalStateException occurred while parsing file /home/xxx/VCS/own/checkstyle-java21-reproducer/src/main/java/HelloWorld.java.
        at com.puppycrawl.tools.checkstyle.JavaParser.parse(JavaParser.java:105)
        at com.puppycrawl.tools.checkstyle.TreeWalker.processFiltered(TreeWalker.java:152)
        at com.puppycrawl.tools.checkstyle.api.AbstractFileSetCheck.process(AbstractFileSetCheck.java:101)
        at com.puppycrawl.tools.checkstyle.Checker.processFile(Checker.java:337)
        at com.puppycrawl.tools.checkstyle.Checker.processFiles(Checker.java:296)
        ... 5 more
Caused by: java.lang.IllegalStateException: 6:32: mismatched input '}' expecting ';'
        at com.puppycrawl.tools.checkstyle.JavaParser$CheckstyleErrorListener.syntaxError(JavaParser.java:255)
        at org.antlr.v4.runtime.ProxyErrorListener.syntaxError(ProxyErrorListener.java:41)
        at org.antlr.v4.runtime.Parser.notifyErrorListeners(Parser.java:544)
        at org.antlr.v4.runtime.DefaultErrorStrategy.reportInputMismatch(DefaultErrorStrategy.java:327)
        at org.antlr.v4.runtime.DefaultErrorStrategy.reportError(DefaultErrorStrategy.java:139)
        at com.puppycrawl.tools.checkstyle.CheckstyleParserErrorStrategy.recoverInline(CheckstyleParserErrorStrategy.java:38)
        at org.antlr.v4.runtime.Parser.match(Parser.java:208)
        at com.puppycrawl.tools.checkstyle.grammar.java.JavaLanguageParser.blockStatement(JavaLanguageParser.java:6190)
        at com.puppycrawl.tools.checkstyle.grammar.java.JavaLanguageParser.block(JavaLanguageParser.java:6101)
        at com.puppycrawl.tools.checkstyle.grammar.java.JavaLanguageParser.methodBody(JavaLanguageParser.java:2940)
        at com.puppycrawl.tools.checkstyle.grammar.java.JavaLanguageParser.methodDeclaration(JavaLanguageParser.java:2898)
        at com.puppycrawl.tools.checkstyle.grammar.java.JavaLanguageParser.memberDeclaration(JavaLanguageParser.java:2745)
        at com.puppycrawl.tools.checkstyle.grammar.java.JavaLanguageParser.classBodyDeclaration(JavaLanguageParser.java:2671)
        at com.puppycrawl.tools.checkstyle.grammar.java.JavaLanguageParser.classBody(JavaLanguageParser.java:2477)
        at com.puppycrawl.tools.checkstyle.grammar.java.JavaLanguageParser.classDeclaration(JavaLanguageParser.java:1096)
        at com.puppycrawl.tools.checkstyle.grammar.java.JavaLanguageParser.types(JavaLanguageParser.java:753)
        at com.puppycrawl.tools.checkstyle.grammar.java.JavaLanguageParser.typeDeclaration(JavaLanguageParser.java:667)
        at com.puppycrawl.tools.checkstyle.grammar.java.JavaLanguageParser.compilationUnit(JavaLanguageParser.java:414)
        at com.puppycrawl.tools.checkstyle.JavaParser.parse(JavaParser.java:99)
        ... 9 more
Caused by: org.antlr.v4.runtime.InputMismatchException
        ... 23 more
Checkstyle ends with 1 errors.

```
in place of the last 2 commands above.

---

Java 21 is out, and it has the new [String Templates](https://openjdk.org/jeps/430) as a preview feature. I did not really go deeper but if the configuration is having **TreeWalker** module, with at least one entry, then the build fails with the above-mentioned error, and if it happens inside a Maven build it just fails. It fails at the following line: `String result = STR."\{x} + \{y} = \{x + y}";`

If the TreeWalker is not present or empty, it finishes successfuly. Will the Java 21 based preview features be supported in upcoming releases?

---

### PR DESCRIPTION
**Pull request by nrmancuso**
Closes #13830 

New grammar summary (from  [here](https://docs.oracle.com/javase/specs/jls/se21/preview/specs/string-templates-jls.html#jls-15.8)):
```
TemplateExpression:
    TemplateProcessor . TemplateArgument

TemplateProcessor:
    Expression

TemplateArgument:
    Template
    StringLiteral
    TextBlock

Template:
    StringTemplate
    TextBlockTemplate

StringTemplate:
    StringTemplateBegin EmbeddedExpression
      { StringTemplateMid EmbeddedExpression } StringTemplateEnd

TextBlockTemplate:
    TextBlockTemplateBegin EmbeddedExpression
      { TextBlockTemplateMid EmbeddedExpression } TextBlockTemplateEnd

EmbeddedExpression:
    [ Expression ]

```

Reading:
 - https://www.baeldung.com/java-21-string-templates#introduction-to-string-templates
 - https://howtodoinjava.com/java/java-string-templates/#:~:text=4.5.%20Multi%2Dline%20Expressions%20are%20Allowed

**Attention: mutliline strings delimited with only single `"` are possible.**

------------------------------------------

Link to reports: https://github.com/nrmancuso/nrmancuso.github.io/pull/56#issue-2034716783

Diff Regression projects: https://raw.githubusercontent.com/checkstyle/contribution/d1348582c72049059c64d46601ce6aaca45baae2/checkstyle-tester/projects-to-test-on-for-github-action.properties

Diff Regression config: https://gist.githubusercontent.com/nrmancuso/4e014025168093baa3f61986a32a96b7/raw/294f634d72297b7b318de79788ca2b153ab33bd2/base_config.xml

Diff Regression patch config: https://gist.githubusercontent.com/nrmancuso/fa9d105fd211d31124cb852aaac54f73/raw/fc90a8f543660dca8ea8acb4afe03e3eee75c76e/patch_config.xml

---------------------------------------------
Projects file: projects-to-test-on.properties
Patch branch: issue-13830

https://checkstyle-reports.s3.us-east-2.amazonaws.com/reports/issue-13830/2023-12-28-T-16-11-57/sevntu-check-regression_part_1/index.html

https://checkstyle-reports.s3.us-east-2.amazonaws.com/reports/issue-13830/2023-12-28-T-16-11-57/part4/index.html

https://checkstyle-reports.s3.us-east-2.amazonaws.com/reports/issue-13830/2023-12-28-T-16-11-57/part1/index.html

https://checkstyle-reports.s3.us-east-2.amazonaws.com/reports/issue-13830/2023-12-28-T-16-11-57/part5/index.html

https://checkstyle-reports.s3.us-east-2.amazonaws.com/reports/issue-13830/2023-12-28-T-16-11-57/sevntu-check-regression_part_2/index.html

https://checkstyle-reports.s3.us-east-2.amazonaws.com/reports/issue-13830/2023-12-28-T-16-11-57/part6/index.html

https://checkstyle-reports.s3.us-east-2.amazonaws.com/reports/issue-13830/2023-12-28-T-16-11-57/part2/index.html

https://checkstyle-reports.s3.us-east-2.amazonaws.com/reports/issue-13830/2023-12-28-T-16-11-57/part3/index.html

https://checkstyle-reports.s3.us-east-2.amazonaws.com/reports/issue-13830/2023-12-28-T-16-11-57/antlr-report/index.html

All differences are either new violations in files that we were not able to parse previously, or change in exception lines in noncompilable code.

### CODE REVIEW

File: src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/grammar/java21/InputStringTemplateBasic.java [hunk 1]
```diff
@@ -0,0 +1,49 @@
+//non-compiled with javac: Compilable with Java21
+package com.puppycrawl.tools.checkstyle.grammar.java21;
+
+public class InputStringTemplateBasic {
+    int x = 10;
+    int y = 20;
+
+    // most basic example, empty string template expression
+    String result1 = STR."";
```
Comment (nrmancuso) [inline src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/grammar/java21/InputStringTemplateBasic.java:9]:
```
        |--VARIABLE_DEF -> VARIABLE_DEF [9:4]
        |   |--MODIFIERS -> MODIFIERS [9:4]
        |   |--TYPE -> TYPE [9:4]
        |   |   `--IDENT -> String [9:4]
        |   |--IDENT -> result1 [9:11]
        |   |--ASSIGN -> = [9:19]
        |   |   `--EXPR -> EXPR [9:24]
        |   |       `--DOT -> . [9:24]
        |   |           |--IDENT -> STR [9:21]
        |   |           `--STRING_LITERAL -> "" [9:25]
```

File: src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/grammar/java21/InputStringTemplateBasic.java [hunk 2]
```diff
@@ -0,0 +1,49 @@
...
+
+    // simple single value interpolation
+    String result2 = STR. "x\{ x }x";
```
Comment (nrmancuso) [inline src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/grammar/java21/InputStringTemplateBasic.java:12]:
```
        |--VARIABLE_DEF -> VARIABLE_DEF [12:4]
        |   |--MODIFIERS -> MODIFIERS [12:4]
        |   |--TYPE -> TYPE [12:4]
        |   |   `--IDENT -> String [12:4]
        |   |--IDENT -> result2 [12:11]
        |   |--ASSIGN -> = [12:19]
        |   |   `--EXPR -> EXPR [12:24]
        |   |       `--DOT -> . [12:24]
        |   |           |--IDENT -> STR [12:21]
        |   |           `--STRING_TEMPLATE_BEGIN -> "x\{ [12:26]
        |   |               |--EMBEDDED_EXPRESSION -> EMBEDDED_EXPRESSION [12:31]
        |   |               |   `--IDENT -> x [12:31]
        |   |               `--STRING_TEMPLATE_END -> }x" [12:33]
        |   `--SEMI -> ; [12:36]
```

File: src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/grammar/java21/InputStringTemplateBasic.java [hunk 3]
```diff
@@ -0,0 +1,49 @@
...
+
+    // simple single value interpolation with a method call
+    String result3 = STR. "\{ y(y("y")) }";
```
Comment (nrmancuso) [inline src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/grammar/java21/InputStringTemplateBasic.java:15]:
```
       |--VARIABLE_DEF -> VARIABLE_DEF [15:4]
        |   |--MODIFIERS -> MODIFIERS [15:4]
        |   |--TYPE -> TYPE [15:4]
        |   |   `--IDENT -> String [15:4]
        |   |--IDENT -> result3 [15:11]
        |   |--ASSIGN -> = [15:19]
        |   |   `--EXPR -> EXPR [15:24]
        |   |       `--DOT -> . [15:24]
        |   |           |--IDENT -> STR [15:21]
        |   |           `--STRING_TEMPLATE_BEGIN -> "\{ [15:26]
        |   |               |--EMBEDDED_EXPRESSION -> EMBEDDED_EXPRESSION [15:31]
        |   |               |   `--METHOD_CALL -> ( [15:31]
        |   |               |       |--IDENT -> y [15:30]
        |   |               |       |--ELIST -> ELIST [15:33]
        |   |               |       |   `--EXPR -> EXPR [15:33]
        |   |               |       |       `--METHOD_CALL -> ( [15:33]
        |   |               |       |           |--IDENT -> y [15:32]
        |   |               |       |           |--ELIST -> ELIST [15:34]
        |   |               |       |           |   `--EXPR -> EXPR [15:34]
        |   |               |       |           |       `--STRING_LITERAL -> "y" [15:34]
        |   |               |       |           `--RPAREN -> ) [15:37]
        |   |               |       `--RPAREN -> ) [15:38]
        |   |               `--STRING_TEMPLATE_END -> }" [15:40]
        |   `--SEMI -> ; [15:42]
```

File: src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/grammar/java21/InputStringTemplateBasic.java [hunk 4]
```diff
@@ -0,0 +1,49 @@
...
+
+    // bit more complex example, multiple interpolations
+    String result4 = STR. "\{ x }"  + STR. "\{ y }";
```
Comment (nrmancuso) [inline src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/grammar/java21/InputStringTemplateBasic.java:18]:
```
        |--VARIABLE_DEF -> VARIABLE_DEF [18:4]
        |   |--MODIFIERS -> MODIFIERS [18:4]
        |   |--TYPE -> TYPE [18:4]
        |   |   `--IDENT -> String [18:4]
        |   |--IDENT -> result4 [18:11]
        |   |--ASSIGN -> = [18:19]
        |   |   `--EXPR -> EXPR [18:36]
        |   |       `--PLUS -> + [18:36]
        |   |           |--DOT -> . [18:24]
        |   |           |   |--IDENT -> STR [18:21]
        |   |           |   `--STRING_TEMPLATE_BEGIN -> "\{ [18:26]
        |   |           |       |--EMBEDDED_EXPRESSION -> EMBEDDED_EXPRESSION [18:30]
        |   |           |       |   `--IDENT -> x [18:30]
        |   |           |       `--STRING_TEMPLATE_END -> }" [18:32]
        |   |           `--DOT -> . [18:41]
        |   |               |--IDENT -> STR [18:38]
        |   |               `--STRING_TEMPLATE_BEGIN -> "\{ [18:43]
        |   |                   |--EMBEDDED_EXPRESSION -> EMBEDDED_EXPRESSION [18:47]
        |   |                   |   `--IDENT -> y [18:47]
        |   |                   `--STRING_TEMPLATE_END -> }" [18:49]
        |   `--SEMI -> ; [18:51]
```

File: src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/grammar/java21/InputStringTemplateBasic.java [hunk 5]
```diff
@@ -0,0 +1,49 @@
...
+            y(y("y")) + y(y("y"))
+            } there";
+
+    // multiple lines with many expressions
+    String result10 = STR. "hey \{
+            y(y("y")) + y(y("y"))
+            } there \{
+            y(y("y")) + y(y("y"))
+            + STR."x\{ x }x"
+            }";
```
Comment (nrmancuso) [inline src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/grammar/java21/InputStringTemplateBasic.java:43]:
```
        |--VARIABLE_DEF -> VARIABLE_DEF [38:4]
        |   |--MODIFIERS -> MODIFIERS [38:4]
        |   |--TYPE -> TYPE [38:4]
        |   |   `--IDENT -> String [38:4]
        |   |--IDENT -> result10 [38:11]
        |   |--ASSIGN -> = [38:20]
        |   |   `--EXPR -> EXPR [38:25]
        |   |       `--DOT -> . [38:25]
        |   |           |--IDENT -> STR [38:22]
        |   |           `--STRING_TEMPLATE_BEGIN -> "hey \{ [38:27]
        |   |               |--EMBEDDED_EXPRESSION -> EMBEDDED_EXPRESSION [39:22]
        |   |               |   `--PLUS -> + [39:22]
        |   |               |       |--METHOD_CALL -> ( [39:13]
        |   |               |       |   |--IDENT -> y [39:12]
        |   |               |       |   |--ELIST -> ELIST [39:15]
        |   |               |       |   |   `--EXPR -> EXPR [39:15]
        |   |               |       |   |       `--METHOD_CALL -> ( [39:15]
        |   |               |       |   |           |--IDENT -> y [39:14]
        |   |               |       |   |           |--ELIST -> ELIST [39:16]
        |   |               |       |   |           |   `--EXPR -> EXPR [39:16]
        |   |               |       |   |           |       `--STRING_LITERAL -> "y" [39:16]
        |   |               |       |   |           `--RPAREN -> ) [39:19]
        |   |               |       |   `--RPAREN -> ) [39:20]
        |   |               |       `--METHOD_CALL -> ( [39:25]
        |   |               |           |--IDENT -> y [39:24]
        |   |               |           |--ELIST -> ELIST [39:27]
        |   |               |           |   `--EXPR -> EXPR [39:27]
        |   |               |           |       `--METHOD_CALL -> ( [39:27]
        |   |               |           |           |--IDENT -> y [39:26]
        |   |               |           |           |--ELIST -> ELIST [39:28]
        |   |               |           |           |   `--EXPR -> EXPR [39:28]
        |   |               |           |           |       `--STRING_LITERAL -> "y" [39:28]
        |   |               |           |           `--RPAREN -> ) [39:31]
        |   |               |           `--RPAREN -> ) [39:32]
        |   |               |--STRING_TEMPLATE_MID -> } there \{ [40:12]
        |   |               |--EMBEDDED_EXPRESSION -> EMBEDDED_EXPRESSION [42:12]
        |   |               |   `--PLUS -> + [42:12]
        |   |               |       |--PLUS -> + [41:22]
        |   |               |       |   |--METHOD_CALL -> ( [41:13]
        |   |               |       |   |   |--IDENT -> y [41:12]
        |   |               |       |   |   |--ELIST -> ELIST [41:15]
        |   |               |       |   |   |   `--EXPR -> EXPR [41:15]
        |   |               |       |   |   |       `--METHOD_CALL -> ( [41:15]
        |   |               |       |   |   |           |--IDENT -> y [41:14]
        |   |               |       |   |   |           |--ELIST -> ELIST [41:16]
        |   |               |       |   |   |           |   `--EXPR -> EXPR [41:16]
        |   |               |       |   |   |           |       `--STRING_LITERAL -> "y" [41:16]
        |   |               |       |   |   |           `--RPAREN -> ) [41:19]
        |   |               |       |   |   `--RPAREN -> ) [41:20]
        |   |               |       |   `--METHOD_CALL -> ( [41:25]
        |   |               |       |       |--IDENT -> y [41:24]
        |   |               |       |       |--ELIST -> ELIST [41:27]
        |   |               |       |       |   `--EXPR -> EXPR [41:27]
        |   |               |       |       |       `--METHOD_CALL -> ( [41:27]
        |   |               |       |       |           |--IDENT -> y [41:26]
        |   |               |       |       |           |--ELIST -> ELIST [41:28]
        |   |               |       |       |           |   `--EXPR -> EXPR [41:28]
        |   |               |       |       |           |       `--STRING_LITERAL -> "y" [41:28]
        |   |               |       |       |           `--RPAREN -> ) [41:31]
        |   |               |       |       `--RPAREN -> ) [41:32]
        |   |               |       `--DOT -> . [42:17]
        |   |               |           |--IDENT -> STR [42:14]
        |   |               |           `--STRING_TEMPLATE_BEGIN -> "x\{ [42:18]
        |   |               |               |--EMBEDDED_EXPRESSION -> EMBEDDED_EXPRESSION [42:23]
        |   |               |               |   `--IDENT -> x [42:23]
        |   |               |               `--STRING_TEMPLATE_END -> }x" [42:25]
        |   |               `--STRING_TEMPLATE_END -> }" [43:12]
```

**Review by nrmancuso — COMMENTED** [review]
I am starting with String templates ( as opposed to text block templates), here are some examples:

**Comment by nrmancuso** [comment]
Need to add Java 21 compilation job to CI

File: src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/grammar/java21/InputStringTemplateBasic.java (hunk 2 above)
Comment (nrmancuso) [reply src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/grammar/java21/InputStringTemplateBasic.java:12]: Need to add a case with no embedded expression (like no x here)

Comment (romani) [reply src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/grammar/java21/InputStringTemplateBasic.java:12]: in my imagination, it bit more trrucrured:
```
`--STRING_TEMPLATE_BEGIN -> " [12:26]
        |   |               |--TEMPLATE_CONTENT "x"
        |   |               |--EMBEDED_BEGIN -> "\{
        |   |               |--EMBEDDED_EXPRESSION -> EMBEDDED_EXPRESSION [12:31]
        |   |               |   `--IDENT -> x [12:31]
        |   |               |--EMBEDED_END -> }
        |   |               |--TEMPLATE_CONTENT--x" [12:33]
        |   |               `--STRING_TEMPLATE_END -> " [12:33]
```

**Comment by nandorholozsnyak** [comment]
Hello there,
What is the status of this PR? I'm curious about the release :)

**Comment by nrmancuso** [comment]
> Hello there, What is the status of this PR? I'm curious about the release :)

Hi @nandorholozsnyak , grammar changes are rarely trivial, and require quite a bit of maintainer time. We can certainly cut a release as soon as this is merged if you would like, we do not need to wait for normal release cycle.

File: src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/grammar/java21/InputStringTemplateBasic.java (hunk 2 above)
Comment (nrmancuso) [reply src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/grammar/java21/InputStringTemplateBasic.java:12]: I also prefer your proposal, however this will be a bit more challenging to create. Let me see what I can do. However, the current implementation is more reflective of the actual java grammar.

**Comment by nandorholozsnyak** [comment]
> > Hello there, What is the status of this PR? I'm curious about the release :)
> 
> Hi @nandorholozsnyak , grammar changes are rarely trivial, and require quite a bit of maintainer time. We can certainly cut a release as soon as this is merged if you would like, we do not need to wait for normal release cycle. 

Hello,
I'm not familiar with your release cycle, I'm not pushing it to be released, but I guess there can be other projects where it can be a blocker of the String template usage.

Take your time and make sure it works properly :)

**Comment by romani** [comment]
@nandorholozsnyak , if you have time to contribute, please help us with https://github.com/checkstyle/checkstyle/issues/12542 , and people will not be blocked by new grammar usage

**Comment by nandorholozsnyak** [comment]
> @nandorholozsnyak , if you have time to contribute, please help us with #12542 , and people will not be blocked by new grammar usage any more .
> 
> Main point of PR to be merged, release can be done at any time, to ship to users sooner.

Hey @romani 
Thank you, I'll take a look on it. :)

File: src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/grammar/java21/InputStringTemplateBasic.java (hunk 2 above)
Comment (nrmancuso) [reply src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/grammar/java21/InputStringTemplateBasic.java:12]: Ok:
```
STRING_TEMPLATE_BEGIN -> " [12:26]
|--STRING_TEMPLATE_CONTENT -> x [12:27]
|--EMBEDDED_EXPRESSION_BEGIN -> \{ [12:28]
|--EMBEDDED_EXPRESSION -> EMBEDDED_EXPRESSION [12:31]
|   `--IDENT -> x [12:31]
|--EMBEDDED_EXPRESSION_END -> } [12:33]
|--STRING_TEMPLATE_CONTENT -> x [12:34]
`--STRING_TEMPLATE_END -> " [12:35]
```

Comment (romani) [reply src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/grammar/java21/InputStringTemplateBasic.java:12]: Looks good.

Comment (nrmancuso) [reply src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/grammar/java21/InputStringTemplateBasic.java:15]: This is the new AST for this code, all other examples in this PR have been edited:
```
        |--VARIABLE_DEF -> VARIABLE_DEF [12:4]
        |   |--MODIFIERS -> MODIFIERS [12:4]
        |   |--TYPE -> TYPE [12:4]
        |   |   `--IDENT -> String [12:4]
        |   |--IDENT -> x [12:11]
        |   |--ASSIGN -> = [12:13]
        |   |   `--EXPR -> EXPR [12:18]
        |   |       `--DOT -> . [12:18]
        |   |           |--IDENT -> STR [12:15]
        |   |           `--STRING_TEMPLATE_BEGIN -> " [12:19]
        |   |               |--STRING_TEMPLATE_CONTENT ->  [12:20]
        |   |               |--EMBEDDED_EXPRESSION_BEGIN -> \{ [12:20]
        |   |               |--EMBEDDED_EXPRESSION -> EMBEDDED_EXPRESSION [12:24]
        |   |               |--EMBEDDED_EXPRESSION_END -> } [12:24]
        |   |               |--STRING_TEMPLATE_CONTENT ->  [12:25]
        |   |               `--STRING_TEMPLATE_END -> " [12:25]
        |   `--SEMI -> ; [12:26]


```

Comment (nrmancuso) [reply src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/grammar/java21/InputStringTemplateBasic.java:15]: All other examples have been edited, this is the new AST for this code (it has moved down in the source code file):
```
        |--VARIABLE_DEF -> VARIABLE_DEF [15:4]
        |   |--MODIFIERS -> MODIFIERS [15:4]
        |   |--TYPE -> TYPE [15:4]
        |   |   `--IDENT -> String [15:4]
        |   |--IDENT -> result2 [15:11]
        |   |--ASSIGN -> = [15:19]
        |   |   `--EXPR -> EXPR [15:24]
        |   |       `--DOT -> . [15:24]
        |   |           |--IDENT -> STR [15:21]
        |   |           `--STRING_TEMPLATE_BEGIN -> " [15:26]
        |   |               |--STRING_TEMPLATE_CONTENT -> x [15:27]
        |   |               |--EMBEDDED_EXPRESSION_BEGIN -> \{ [15:28]
        |   |               |--EMBEDDED_EXPRESSION -> EMBEDDED_EXPRESSION [15:31]
        |   |               |   `--IDENT -> x [15:31]
        |   |               |--EMBEDDED_EXPRESSION_END -> } [15:33]
        |   |               |--STRING_TEMPLATE_CONTENT -> x [15:34]
        |   |               `--STRING_TEMPLATE_END -> " [15:35]
        |   `--SEMI -> ; [15:36]


```

File: src/test/java/com/puppycrawl/tools/checkstyle/grammar/java21/Java21AstRegressionTest.java [hunk 6]
```diff
@@ -0,0 +1,41 @@
...
+
+public class Java21AstRegressionTest extends AbstractTreeTestSupport {
+
+    @Override
+    protected String getPackageLocation() {
+        return "com/puppycrawl/tools/checkstyle/grammar/java21";
+    }
+
+    @Test
+    public void testBasicStringTemplate() throws Exception {
```
Comment (nrmancuso) [inline src/test/java/com/puppycrawl/tools/checkstyle/grammar/java21/Java21AstRegressionTest.java:34]: Need to add more complicated expressions and more cases like expr."" (not STR), and also cases with other template types.

File: src/xdocs/checks/coding/illegaltokentext.xml [hunk 7]
```diff
@@ -68,6 +68,8 @@
                     CHAR_LITERAL</a>
                 , <a href="../../apidocs/com/puppycrawl/tools/checkstyle/api/TokenTypes.html#TEXT_BLOCK_CONTENT">
                     TEXT_BLOCK_CONTENT</a>
+                , <a href="../../apidocs/com/puppycrawl/tools/checkstyle/api/TokenTypes.html#STRING_TEMPLATE_CONTENT">
+                    STRING_TEMPLATE_CONTENT</a>
                   .
```
Comment (nrmancuso) [inline src/xdocs/checks/coding/illegaltokentext.xml:73]: Need to add test for this check

File: src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/grammar/java21/InputStringTemplateBasic.java (hunk 1 above)
Comment (nrmancuso) [reply src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/grammar/java21/InputStringTemplateBasic.java:11]: @rnveach @romani I am not sure about this one, should we do the above, or like this:
```
        |   |       `--DOT -> . [15:24]
        |   |           |--IDENT -> STR [15:21]
        |   |           `--STRING_TEMPLATE_BEGIN -> "
        |   |               |--STRING_TEMPLATE_CONTENT ->
        |   |               `--STRING_TEMPLATE_END -> "

```

Comment (nrmancuso) [reply src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/grammar/java21/InputStringTemplateBasic.java:11]: I suppose it is still a template, I will update the code.

**Comment by nrmancuso** [comment]
Github, generate report

**Comment by nrmancuso** [comment]
Github, generate report

File: src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/grammar/java21/InputStringTemplateBasic.java (hunk 1 above)
Comment (romani) [reply src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/grammar/java21/InputStringTemplateBasic.java:11]:
```
        |   |--ASSIGN -> = [9:19]
        |   |   `--EXPR -> EXPR [9:24]
        |   |       `--DOT -> . [9:24]
        |   |           |--IDENT -> STR [9:21]
        |   |           `--STRING_LITERAL -> "" [9:25]
```
is consistent with what we do now.

```
        |   |       `--DOT -> . [15:24]
        |   |           |--IDENT -> STR [15:21]
        |   |           `--STRING_TEMPLATE_BEGIN -> "
        |   |               |--STRING_TEMPLATE_CONTENT ->
        |   |               `--STRING_TEMPLATE_END -> "
```
is to clear pointer it is String Template syntax.

if we reuse old tree, we might immediately need to update all our Checks to exclude this from consideration. and it will be hard to find by AST that it is String Template.

I  vote for STRING_TEMPLATE_BEGIN approach.

**Comment by romani** [comment]
>Need to add Java 21 compilation job to CI

Let's move it to separate PR and merge sooner.

**Comment by nrmancuso** [comment]
Link to report generation: https://github.com/nrmancuso/nrmancuso.github.io/actions/runs/7348187703

**Comment by nrmancuso** [comment]
Github, generate report

**Comment by rnveach** [comment]
11/19 files viewed.

While I am slowly going through this, have we looked at checks that aren't producing differences and maybe check if they should have updates? Just did a quick search on string, and a quick eye scan.

https://checkstyle.org/checks/coding/equalsavoidnull.html#EqualsAvoidNull
https://checkstyle.org/checks/coding/innerassignment.html#InnerAssignment
https://checkstyle.org/checks/coding/multiplestringliterals.html#MultipleStringLiterals
https://checkstyle.org/checks/coding/stringliteralequality.html#StringLiteralEquality

https://checkstyle.org/checks/misc/avoidescapedunicodecharacters.html#AvoidEscapedUnicodeCharacters

File: src/main/java/com/puppycrawl/tools/checkstyle/JavaAstVisitor.java [hunk 8]
```diff
@@ -1742,6 +1760,216 @@ public DetailAstImpl visitPrimitivePrimary(JavaLanguageParser.PrimitivePrimaryCo
...
+     * string template argument.
+     *
+     * @param ctx the TemplateArgumentContext to build AST from
+     * @return DetailAstImpl of string template argument
+     */
+    private static DetailAstImpl buildSimpleStringTemplateArgument(
+            JavaLanguageParser.TemplateArgumentContext ctx
+    ) {
+        final int startColumn = ctx.start.getCharPositionInLine();
+        final int endColumn = startColumn + ctx.getText().length() - 1;
```
Comment (rnveach) [inline src/main/java/com/puppycrawl/tools/checkstyle/JavaAstVisitor.java:1781]: is this tab safe? We have a property that declares how long a tab is in size. I thought the AST respected that.

Do we have a test that shows tab usage?

File: src/main/java/com/puppycrawl/tools/checkstyle/JavaAstVisitor.java [hunk 9]
```diff
@@ -2199,6 +2427,24 @@ private static void addLastSibling(DetailAstImpl self, DetailAstImpl sibling) {
...
+     * @param tokenType the token type of this DetailAstImpl
+     * @param text the text of this DetailAstImpl
+     * @param lineNumber the line number of this DetailAstImpl
+     * @param columnNumber the column number of this DetailAstImpl
+     * @return imaginary DetailAstImpl from given details
+     */
+    private static DetailAstImpl buildImaginaryWithDetails(
+            int tokenType, String text, int lineNumber, int columnNumber) {
+        final DetailAstImpl imaginary = createImaginary(tokenType);
+        imaginary.setText(text);
```
Comment (rnveach) [inline src/main/java/com/puppycrawl/tools/checkstyle/JavaAstVisitor.java:2442]: I understand why you called `createImaginary` but is it really needed in this case? `createImaginary` does `setText` but we overwrite it in the end. Seems better to just do the imaginary yourself here.

Maybe consider `createImaginary(int tokenType, String text) {`

File: src/main/java/com/puppycrawl/tools/checkstyle/JavaAstVisitor.java [hunk 10]
```diff
@@ -2199,6 +2427,24 @@ private static void addLastSibling(DetailAstImpl self, DetailAstImpl sibling) {
...
+    /**
+     * Builds an imaginary DetailAstImpl with the given token details.
+     *
+     * @param tokenType the token type of this DetailAstImpl
+     * @param text the text of this DetailAstImpl
+     * @param lineNumber the line number of this DetailAstImpl
+     * @param columnNumber the column number of this DetailAstImpl
+     * @return imaginary DetailAstImpl from given details
+     */
+    private static DetailAstImpl buildImaginaryWithDetails(
```
Comment (rnveach) [inline src/main/java/com/puppycrawl/tools/checkstyle/JavaAstVisitor.java:2439]: Going on the previous comment, why not just name all these `createImaginary` with different parameters to fill. It would make this almost like a builder method.

File: src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java [hunk 11]
```diff
@@ -6469,6 +6469,244 @@ public final class TokenTypes {
...
+     *     |--TYPE -&gt; TYPE
+     *     |   `--IDENT -&gt; String
+     *     |--IDENT -&gt; s
+     *     `--ASSIGN -&gt; =
+     *         `--EXPR -&gt; EXPR
+     *              `--DOT -&gt; .
+     *                  |--IDENT -&gt; STR
+     *                  `--STRING_TEMPLATE_BEGIN -&gt; "
+     *                      |--STRING_TEMPLATE_CONTENT -&gt; Hello,
+     *                      |--EMBEDDED_EXPRESSION_BEGIN -&gt; \{
```
Comment (rnveach) [inline src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java:6492]: I myself think this should be more nested over flat like this. While we don't do it like these everywhere, we do for block comments and object blocks. I think it makes it clearer the start and end.

I saw the discussion about this before this PR.

File: src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java [hunk 12]
```diff
@@ -6469,6 +6469,244 @@ public final class TokenTypes {
...
+     * </pre>
+     *
+     * @see #STRING_TEMPLATE_END
+     * @see #STRING_TEMPLATE_CONTENT
+     * @see #EMBEDDED_EXPRESSION_BEGIN
+     * @see #EMBEDDED_EXPRESSION
+     * @see #EMBEDDED_EXPRESSION_END
+     * @see #STRING_LITERAL
+     *
+     * @since 10.12.7
```
Comment (rnveach) [inline src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java:6507]: All versions need updated.

File: src/main/resources/com/puppycrawl/tools/checkstyle/grammar/java/JavaLanguageParser.g4 [hunk 13]
```diff
@@ -688,6 +688,7 @@ expression
 
 expr
     : primary                                                              #primaryExp
+    | expr DOT templateArgument                                            #templateExp
```
Comment (rnveach) [inline src/main/resources/com/puppycrawl/tools/checkstyle/grammar/java/JavaLanguageParser.g4:691]: Others below this have `bop=DOT`. Any reason this doesn't?

Also, I realize this works and mostly just curious, but how do you know this goes on the top versus the middle/bottom?

File: src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java (hunk 11 above)
Comment (nrmancuso) [reply src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java:6492]: Can you throw together an example so we can be on the same page?

File: src/main/resources/com/puppycrawl/tools/checkstyle/grammar/java/JavaLanguageParser.g4 (hunk 13 above)
Comment (nrmancuso) [reply src/main/resources/com/puppycrawl/tools/checkstyle/grammar/java/JavaLanguageParser.g4:691]: >Others below this have bop=DOT. Any reason this doesn't?

Alternatives with `bop=X` are all binary operators, that are handled by a similar method; we name the operator so that we can reference `bop` instead of having to know what the operator is (we don't care). In this case, we have no need to have such a reference. Plus, the `.` isn't a binary operator in this context.

>Also, I realize this works and mostly just curious, but how do you know this goes on the top versus the middle/bottom?

Left recursive rules are a bit tricky, but this MOSTLY follows operator precedence except in a few rare cases. I was not able to fully refactor our `primary` rule when I did ANTLR2 -> ANTLR4 due to some existing weird stuff. Because of this, the grammar would get a bit messier if I put this alternative where it belongs (in `primary`). So, I did the next best thing; made this alternative the first one after `primary` in the `expr` rule instead of the last alternative in the `primary` rule.

File: src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java (hunk 11 above)
Comment (rnveach) [reply src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java:6492]: Copied from the original discussion:
````
        |   |           `--STRING_TEMPLATE_BEGIN -> "x\{ [12:26]
        |   |               |--EMBEDDED_EXPRESSION -> EMBEDDED_EXPRESSION [12:31]
        |   |               |   `--IDENT -> x [12:31]
        |   |               `--STRING_TEMPLATE_END -> }x" [12:33]
````

Taken from other ASTs:
````
        |  |  |--BLOCK_COMMENT_BEGIN -> /* [2:0]
        |  |  |  |--COMMENT_CONTENT ->  [2:2]
        |  |  |  `--BLOCK_COMMENT_END -> */ [2:2]

        |  |  |--BLOCK_COMMENT_BEGIN -> /* [3:0]
        |  |  |  |--COMMENT_CONTENT -> *  [3:2]
        |  |  |  |  `--JAVADOC -> JAVADOC [3:3]
        |  |  |  |      |--TEXT ->  [3:3]
        |  |  |  |      `--EOF -> <EOF> [3:4]
        |  |  |  `--BLOCK_COMMENT_END -> */ [3:3]

        |  `--SLIST -> { [4:18]
        |      `--RCURLY -> } [5:4]
````

I am not really asking for you to change your PR if this is the way the group wants to go. I just think the other way makes the hierarchy clearer. There are other areas in our code that flattens it like this does, but like I said, I disagree with that layout. A clearer start/end, makes coding to handle the structure in a custom check easier. The difference between looping until `null` and looping until token type XYZ. I had some custom check have to do this kind of looping, and i thought this structure just complicated the coding.

Example:
````
        |--METHOD_DEF -> METHOD_DEF [4:4]
        |  |--IDENT -> method [4:9]
        |  |--LPAREN -> ( [4:15]
        |  |--PARAMETERS -> PARAMETERS [4:16]
        |  |--RPAREN -> ) [4:16]
````

File: src/main/resources/com/puppycrawl/tools/checkstyle/grammar/java/JavaLanguageParser.g4 (hunk 13 above)
Comment (rnveach) [reply src/main/resources/com/puppycrawl/tools/checkstyle/grammar/java/JavaLanguageParser.g4:691]: Thanks, it is clear now. I don't see how we will find out if the recursive rules matching fails except from user reporting.

File: src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java (hunk 11 above)
Comment (nrmancuso) [reply src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java:6492]: It is debatable for sure; my thought was that now all the content tokens are the same, instead of having beginning/middle/end that all have different delimiters. From a check update point of view, we can pretty much just add the STRING_TEMPLATE_CONTENT token and be done with it.

File: src/main/resources/com/puppycrawl/tools/checkstyle/grammar/java/JavaLanguageParser.g4 (hunk 13 above)
Comment (nrmancuso) [reply src/main/resources/com/puppycrawl/tools/checkstyle/grammar/java/JavaLanguageParser.g4:691]: I am confident in this update, chances of a false match are basically nil since we have introduced new tokens that are radically different than anything else.

File: src/main/java/com/puppycrawl/tools/checkstyle/JavaAstVisitor.java (hunk 8 above)
Comment (nrmancuso) [reply src/main/java/com/puppycrawl/tools/checkstyle/JavaAstVisitor.java:1781]: We do now, done

File: src/main/java/com/puppycrawl/tools/checkstyle/JavaAstVisitor.java (hunk 9 above)
Comment (nrmancuso) [reply src/main/java/com/puppycrawl/tools/checkstyle/JavaAstVisitor.java:2442]: This is a good point, let me think on this and I will update.

Comment (nrmancuso) [reply src/main/java/com/puppycrawl/tools/checkstyle/JavaAstVisitor.java]: Done

File: src/main/java/com/puppycrawl/tools/checkstyle/JavaAstVisitor.java (hunk 10 above)
Comment (nrmancuso) [reply src/main/java/com/puppycrawl/tools/checkstyle/JavaAstVisitor.java]: Yep, done

File: src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java (hunk 12 above)
Comment (nrmancuso) [reply src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java]: done

**Comment by romani** [comment]
why two commits with same message?

**Comment by nrmancuso** [comment]
> why two commits with same message?

This was a mistake, fixed.

**Comment by romani** [comment]
Checker is not green.

**Comment by rnveach** [comment]
@nrmancuso I'll look over again soon, but I saw no response to my comment at https://github.com/checkstyle/checkstyle/pull/13991#issuecomment-1872987684 .

**Comment by nrmancuso** [comment]
> @nrmancuso I'll look over again soon, but I saw no response to my comment at [#13991 (comment)](https://github.com/checkstyle/checkstyle/pull/13991#issuecomment-1872987684) .

I can create an issue for this; in the past we have only fixed NPEs in grammar updates

**Review by rnveach — APPROVED** [review]

File: src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java [hunk 14]
```diff
@@ -6469,6 +6469,244 @@ public final class TokenTypes {
...
+    /**
+     * A string template closing delimiter. This element ({@code "}) appears
+     * at the end of a string template.
+     * <p>For example:</p>
+     * <pre>
+     *     String s = STR."Hello, \{name}!";
+     * </pre>
+     * <p>parses as:</p>
+     * <pre>
+     * `--VARIABLE_DEF -&gt; VARIABLE_DEF
```
Comment (romani) [inline src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java:6521]: please remove "`--" in all cases to make tree be less wide horizontally 

https://github.com/checkstyle/checkstyle/blob/98208763e8199cf5dfa90bc3750ad0577ad1f903/src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java#L93-L95

File: src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java [hunk 15]
```diff
@@ -6469,6 +6469,244 @@ public final class TokenTypes {
...
+     * </pre>
+     *
+     * @see #STRING_TEMPLATE_END
+     * @see #STRING_TEMPLATE_CONTENT
+     * @see #EMBEDDED_EXPRESSION_BEGIN
+     * @see #EMBEDDED_EXPRESSION
+     * @see #EMBEDDED_EXPRESSION_END
+     * @see #STRING_LITERAL
+     *
+     * @since 10.12.8
```
Comment (romani) [inline src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java:6507]: 10.13.0

as this is new feature (new API tokens), plugins needs to be aware of new stuff.

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalTokenTextCheck.java [hunk 16]
```diff
@@ -113,6 +113,7 @@ public int[] getAcceptableTokens() {
             TokenTypes.STRING_LITERAL,
             TokenTypes.CHAR_LITERAL,
             TokenTypes.TEXT_BLOCK_CONTENT,
+            TokenTypes.STRING_TEMPLATE_CONTENT,
```
Comment (romani) [inline src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalTokenTextCheck.java:116]: please create separate issue on Check extension, we usually very transperent to users in release notes if some Check got new acceptable token to operate on.
So you will have 3 commits: minor, grammar, check update. All with different prefixes.

File: src/main/java/com/puppycrawl/tools/checkstyle/JavaAstVisitor.java [hunk 17]
```diff
@@ -1742,6 +1760,216 @@ public DetailAstImpl visitPrimitivePrimary(JavaLanguageParser.PrimitivePrimaryCo
...
+     * Builds a simple string template argument AST, which basically means that we
+     * transform a string literal into a string template AST because it is a
+     * string template argument.
+     *
+     * @param ctx the TemplateArgumentContext to build AST from
+     * @return DetailAstImpl of string template argument
+     */
+    private static DetailAstImpl buildSimpleStringTemplateArgument(
+            JavaLanguageParser.TemplateArgumentContext ctx
+    ) {
```
[the remark this answers is not in the document]
Comment (nrmancuso) [reply src/main/java/com/puppycrawl/tools/checkstyle/JavaAstVisitor.java]: Done

File: src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java (hunk 14 above)
Comment (nrmancuso) [reply src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java]: Done

File: src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java (hunk 15 above)
Comment (nrmancuso) [reply src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java]: Done

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalTokenTextCheck.java (hunk 16 above)
Comment (nrmancuso) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalTokenTextCheck.java:116]: Done

File: src/test/java/com/puppycrawl/tools/checkstyle/internal/AllChecksTest.java [hunk 18]
```diff
@@ -236,7 +237,8 @@ public class AllChecksTest extends AbstractModuleTestSupport {
         GOOGLE_TOKENS_IN_CONFIG_TO_IGNORE.put("IllegalTokenText", Stream.of(
                 // all other java tokens and text are allowed
                 "NUM_DOUBLE", "NUM_FLOAT", "NUM_INT", "NUM_LONG", "IDENT",
-                "COMMENT_CONTENT", "STRING_LITERAL", "CHAR_LITERAL", "TEXT_BLOCK_CONTENT")
+                "COMMENT_CONTENT", "STRING_LITERAL", "CHAR_LITERAL", "TEXT_BLOCK_CONTENT",
+                "STRING_TEMPLATE_CONTENT")
```
Comment (romani) [inline src/test/java/com/puppycrawl/tools/checkstyle/internal/AllChecksTest.java:241]: This update is strange.
https://checkstyle.org/styleguides/google-java-style-20180523/javaguide.html#s2.3.2-special-escape-sequences
https://checkstyle.org/google_style.html#a2.3.2
https://github.com/checkstyle/checkstyle/blob/253430250fe784998d1b9d8a1c1b54c452751154/src/main/resources/google_checks.xml#L54

Why we ignoring such tokens, as they can have content that we need to validate ?

Comment (romani) [reply src/test/java/com/puppycrawl/tools/checkstyle/internal/AllChecksTest.java:241]: We can definitely improve this in separate issue, just curious

Comment (nrmancuso) [reply src/test/java/com/puppycrawl/tools/checkstyle/internal/AllChecksTest.java:241]: I do not remember reasoning, but we have added all new syntax to this collection. Maybe it was due to not being explicitly mentioned in Googles style guide.

Comment (nrmancuso) [reply src/test/java/com/puppycrawl/tools/checkstyle/internal/AllChecksTest.java:241]: Issue created at https://github.com/checkstyle/checkstyle/issues/14291

Comment (romani) [reply src/test/java/com/puppycrawl/tools/checkstyle/internal/AllChecksTest.java:241]: https://github.com/checkstyle/checkstyle/pull/14292

File: src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java [hunk 19]
```diff
@@ -6469,6 +6469,244 @@ public final class TokenTypes {
...
+     */
+    public static final int STRING_TEMPLATE_BEGIN =
+            JavaLanguageLexer.STRING_TEMPLATE_BEGIN;
+
+    /**
+     * A string template closing delimiter. This element ({@code "}) appears
+     * at the end of a string template.
+     * <p>For example:</p>
+     * <pre>
+     *     String s = STR."Hello, \{name}!";
```
Comment (romani) [inline src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java:6517]: `String s = STR."Hello, \{firstName + lastName}!";`

File: src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java [hunk 20]
```diff
@@ -6469,6 +6469,244 @@ public final class TokenTypes {
...
+     * @since 10.13.0
+     */
+    public static final int EMBEDDED_EXPRESSION_BEGIN =
+            JavaLanguageLexer.EMBEDDED_EXPRESSION_BEGIN;
+
+    /**
+     * An expression embedded within a string template.
+     * <p>For example:</p>
+     * <pre>
+     *     String s = STR."Hello, \{name}!";
```
Comment (romani) [inline src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java:6635]: `String s = STR."Hello, \{getName("Mr. ")}!";`

File: src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java [hunk 21]
```diff
@@ -6469,6 +6469,244 @@ public final class TokenTypes {
...
+     */
+    public static final int EMBEDDED_EXPRESSION =
+            JavaLanguageLexer.EMBEDDED_EXPRESSION;
+
+    /**
+     * The closing delimiter of an embedded expression within a string
+     * template.
+     * <p>For example:</p>
+     * <pre>
+     *     String s = STR."Hello, \{name}!";
```
Comment (romani) [inline src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java:6675]: `String s = STR."Hello, \{getName("Mr. ")}!";`

File: src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java [hunk 22]
```diff
@@ -6469,6 +6469,244 @@ public final class TokenTypes {
...
+     */
+    public static final int STRING_TEMPLATE_END =
+            JavaLanguageLexer.STRING_TEMPLATE_END;
+
+    /**
+     * The (possibly empty) content of a string template. A given string
+     * template may have more than one node of this type.
+     * <p>For example:</p>
+     * <pre>
+     *     String s = STR."Hello, \{name}!";
```
Comment (romani) [inline src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java:6557]: `String s = STR."Hello, \{firstName + lastName}!";`

File: src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java [hunk 23]
```diff
@@ -6469,6 +6469,244 @@ public final class TokenTypes {
...
+     * @since 10.13.0
+     */
+    public static final int STRING_TEMPLATE_CONTENT =
+            JavaLanguageLexer.STRING_TEMPLATE_CONTENT;
+
+    /**
+     * The opening delimiter of an embedded expression within a string template.
+     * <p>For example:</p>
+     * <pre>
+     *     String s = STR."Hello, \{name}!";
```
Comment (romani) [inline src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java:6596]: `String s = STR."Hello, \{getName("Mr. ")}!";`

**Review by romani — CHANGES_REQUESTED** [review]
last items: 2 examples in tokens javadoc , not a single for all

File: src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java [hunk 24]
```diff
@@ -6469,6 +6469,244 @@ public final class TokenTypes {
     public static final int RECORD_PATTERN_COMPONENTS =
             JavaLanguageLexer.RECORD_PATTERN_COMPONENTS;
 
+    /**
+     * A string template opening delimiter. This element ({@code "}) appears
+     * at the beginning of a string template.
+     * <p>For example:</p>
+     * <pre>
+     *     String s = STR."Hello, \{name}!";
```
[the remark this answers is not in the document]
Comment (nrmancuso) [reply src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java]: done

File: src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java (hunk 19 above)
Comment (nrmancuso) [reply src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java]: done

File: src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java (hunk 21 above)
Comment (nrmancuso) [reply src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java]: Changed this one a bit to reuse the firstName, lastName concept but with a method call as suggested.

File: src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java (hunk 22 above)
Comment (nrmancuso) [reply src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java]: done

File: src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java (hunk 23 above)
Comment (nrmancuso) [reply src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java]: done

File: src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java (hunk 20 above)
Comment (romani) [reply src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java]: https://github.com/checkstyle/checkstyle/issues/14317

**Comment by NoSugarCoffee** [comment]
@nrmancuso  Is there any news for the text block template?
```
String name    = "Joan Smith";
String phone   = "555-123-4567";
String address = "1 Maple Drive, Anytown";
String json = STR."""
    {
        "name":    "\{name}",
        "phone":   "\{phone}",
        "address": "\{address}"
    }
    """;
```

**Comment by nrmancuso** [comment]
@NoSugarCoffee news is here: https://github.com/checkstyle/checkstyle/issues/14805

**Comment by NoSugarCoffee** [comment]
@nrmancuso It is clear and make sense，thanks
