### PR TITLE
Issue #10817: Fix IllegalTypeCheck on Record with configured member modifiers

### LINKED ISSUE #10817: NPE in IllegalTypeCheck when checking a record (Java 14)
Hello,

https://checkstyle.org/config_coding.html#IllegalType

I'm trying JDK 16 with language-level 16 I've run into an NPE. I've discovered this on Checkstyle 9.0, but the same problem is still unresolved on the `master` branch.

Since the build is configured to run on `1.8`, I had to modify the source+target language to allow for the reproducer test-case, which I've prepared here: https://github.com/fprochazka/checkstyle/commit/0e18223a4fd8e91cb3264fd970573f0e6e1c0a5d, it's probably not ideal, but IMHO it should pass a verifiable reproducer.

if you run the `IllegalTypeCheckTest` from my commit, you'll see the following errors: 

<details>
 <summary>InputIllegalTypeTestRecordsPass fail</summary>

```
com.puppycrawl.tools.checkstyle.api.CheckstyleException: Exception was thrown while processing /home/fprochazka/devel/libs/checkstyle/checkstyle/src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/illegaltype/InputIllegalTypeTestRecordsPass.java

	at com.puppycrawl.tools.checkstyle.Checker.processFiles(Checker.java:302)
	at com.puppycrawl.tools.checkstyle.Checker.process(Checker.java:221)
	at com.puppycrawl.tools.checkstyle.AbstractModuleTestSupport.getActualViolationsForFile(AbstractModuleTestSupport.java:442)
	at com.puppycrawl.tools.checkstyle.AbstractModuleTestSupport.verifyViolations(AbstractModuleTestSupport.java:416)
	at com.puppycrawl.tools.checkstyle.AbstractModuleTestSupport.verifyWithInlineConfigParser(AbstractModuleTestSupport.java:269)
	at com.puppycrawl.tools.checkstyle.checks.coding.IllegalTypeCheckTest.testValidateRecordsPass(IllegalTypeCheckTest.java:66)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:725)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:149)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:140)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:84)
	at org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(ExecutableInvoker.java:115)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:104)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:98)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$7(TestMethodTestDescriptor.java:214)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:210)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:135)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:66)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:151)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:35)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:108)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:88)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:67)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:52)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:96)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:75)
	at com.intellij.junit5.JUnit5IdeaTestRunner.startRunnerWithArgs(JUnit5IdeaTestRunner.java:71)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:235)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:54)
Caused by: java.lang.NullPointerException: Cannot invoke "com.puppycrawl.tools.checkstyle.api.DetailAST.getFirstChild()" because "modifiers" is null
	at com.puppycrawl.tools.checkstyle.checks.coding.IllegalTypeCheck.isContainVerifiableType(IllegalTypeCheck.java:516)
	at com.puppycrawl.tools.checkstyle.checks.coding.IllegalTypeCheck.isVerifiable(IllegalTypeCheck.java:502)
	at com.puppycrawl.tools.checkstyle.checks.coding.IllegalTypeCheck.visitVariableDef(IllegalTypeCheck.java:577)
	at com.puppycrawl.tools.checkstyle.checks.coding.IllegalTypeCheck.visitToken(IllegalTypeCheck.java:477)
	at com.puppycrawl.tools.checkstyle.TreeWalker.notifyVisit(TreeWalker.java:335)
	at com.puppycrawl.tools.checkstyle.TreeWalker.processIter(TreeWalker.java:406)
	at com.puppycrawl.tools.checkstyle.TreeWalker.walk(TreeWalker.java:273)
	at com.puppycrawl.tools.checkstyle.TreeWalker.processFiltered(TreeWalker.java:154)
	at com.puppycrawl.tools.checkstyle.api.AbstractFileSetCheck.process(AbstractFileSetCheck.java:87)
	at com.puppycrawl.tools.checkstyle.Checker.processFile(Checker.java:328)
	at com.puppycrawl.tools.checkstyle.Checker.processFiles(Checker.java:289)
	... 70 more
```

</details>

<details>
 <summary>InputIllegalTypeTestInnerRecordsPass fail</summary>

```
com.puppycrawl.tools.checkstyle.api.CheckstyleException: Exception was thrown while processing /home/fprochazka/devel/libs/checkstyle/checkstyle/src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/illegaltype/InputIllegalTypeTestInnerRecordsPass.java

	at com.puppycrawl.tools.checkstyle.Checker.processFiles(Checker.java:302)
	at com.puppycrawl.tools.checkstyle.Checker.process(Checker.java:221)
	at com.puppycrawl.tools.checkstyle.AbstractModuleTestSupport.getActualViolationsForFile(AbstractModuleTestSupport.java:442)
	at com.puppycrawl.tools.checkstyle.AbstractModuleTestSupport.verifyViolations(AbstractModuleTestSupport.java:416)
	at com.puppycrawl.tools.checkstyle.AbstractModuleTestSupport.verifyWithInlineConfigParser(AbstractModuleTestSupport.java:269)
	at com.puppycrawl.tools.checkstyle.checks.coding.IllegalTypeCheckTest.testValidateInnerRecordsPass(IllegalTypeCheckTest.java:74)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:725)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:149)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:140)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:84)
	at org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(ExecutableInvoker.java:115)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:104)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:98)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$7(TestMethodTestDescriptor.java:214)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:210)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:135)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:66)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:151)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:35)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:108)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:88)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:67)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:52)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:96)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:75)
	at com.intellij.junit5.JUnit5IdeaTestRunner.startRunnerWithArgs(JUnit5IdeaTestRunner.java:71)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:235)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:54)
Caused by: java.lang.NullPointerException: Cannot invoke "com.puppycrawl.tools.checkstyle.api.DetailAST.getFirstChild()" because "modifiers" is null
	at com.puppycrawl.tools.checkstyle.checks.coding.IllegalTypeCheck.isContainVerifiableType(IllegalTypeCheck.java:516)
	at com.puppycrawl.tools.checkstyle.checks.coding.IllegalTypeCheck.isVerifiable(IllegalTypeCheck.java:502)
	at com.puppycrawl.tools.checkstyle.checks.coding.IllegalTypeCheck.visitVariableDef(IllegalTypeCheck.java:577)
	at com.puppycrawl.tools.checkstyle.checks.coding.IllegalTypeCheck.visitToken(IllegalTypeCheck.java:477)
	at com.puppycrawl.tools.checkstyle.TreeWalker.notifyVisit(TreeWalker.java:335)
	at com.puppycrawl.tools.checkstyle.TreeWalker.processIter(TreeWalker.java:406)
	at com.puppycrawl.tools.checkstyle.TreeWalker.walk(TreeWalker.java:273)
	at com.puppycrawl.tools.checkstyle.TreeWalker.processFiltered(TreeWalker.java:154)
	at com.puppycrawl.tools.checkstyle.api.AbstractFileSetCheck.process(AbstractFileSetCheck.java:87)
	at com.puppycrawl.tools.checkstyle.Checker.processFile(Checker.java:328)
	at com.puppycrawl.tools.checkstyle.Checker.processFiles(Checker.java:289)
	... 70 more
```

</details>

The interesting part is IMHO this: 

```
java.lang.NullPointerException: Cannot invoke "com.puppycrawl.tools.checkstyle.api.DetailAST.getFirstChild()" because "modifiers" is null
	at com.puppycrawl.tools.checkstyle.checks.coding.IllegalTypeCheck.isContainVerifiableType(IllegalTypeCheck.java:516)
	at com.puppycrawl.tools.checkstyle.checks.coding.IllegalTypeCheck.isVerifiable(IllegalTypeCheck.java:502)
	at com.puppycrawl.tools.checkstyle.checks.coding.IllegalTypeCheck.visitVariableDef(IllegalTypeCheck.java:577)
	at com.puppycrawl.tools.checkstyle.checks.coding.IllegalTypeCheck.visitToken(IllegalTypeCheck.java:477)
	at com.puppycrawl.tools.checkstyle.TreeWalker.notifyVisit(TreeWalker.java:335)
	at com.puppycrawl.tools.checkstyle.TreeWalker.processIter(TreeWalker.java:406)
	at com.puppycrawl.tools.checkstyle.TreeWalker.walk(TreeWalker.java:273)
	at com.puppycrawl.tools.checkstyle.TreeWalker.processFiltered(TreeWalker.java:154)
	at com.puppycrawl.tools.checkstyle.api.AbstractFileSetCheck.process(AbstractFileSetCheck.java:87)
	at com.puppycrawl.tools.checkstyle.Checker.processFile(Checker.java:328)
	at com.puppycrawl.tools.checkstyle.Checker.processFiles(Checker.java:289)
```

My configuration of the check is baked into the comment in the tested source file.

If I change

```
memberModifiers = LITERAL_PUBLIC, LITERAL_PROTECTED, LITERAL_STATIC
```

to 

```
memberModifiers = (default)
```

it starts to pass

...

Am I configuring it incorrectly? IMHO it should not throw an NPE even when configured incorrectly.

### PR DESCRIPTION
**Pull request by Rahulkhinchi03**
Fixes #10817

Diff Regression config: https://gist.githubusercontent.com/Rahulkhinchi03/7b19d57cd13d1d2904ab523a61f7f300/raw/5784d380be13aec65a30e5042a18ddb25b20308a/config.xml

### CODE REVIEW

**Comment by Rahulkhinchi03** [comment]
@romani Kindly help me with the failing test cases!

File: src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/illegaltype/InputIllegalTypeRecordsWithMemberModifiersSpecified.java [hunk 1]
```diff
@@ -0,0 +1,28 @@
...
+
+//non-compiled with javac: Compilable with Java14
+package com.puppycrawl.tools.checkstyle.checks.coding.illegaltype;
+
+import java.lang.String;
+import java.util.UUID;
+
+public record InputIllegalTypeRecordsWithMemberModifiersSpecified(
+        UUID productId,
+        @Nullable String identifier
```
Comment (strkkk) [inline src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/illegaltype/InputIllegalTypeRecordsWithMemberModifiersSpecified.java:24]: please remove annotation

**Comment by strkkk** [comment]
@Rahulkhinchi03 run build on local machine (mvn clean verify) to see what is wrong

File: src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/illegaltype/InputIllegalTypeRecordsWithMemberModifiersSpecified.java [hunk 2]
```diff
@@ -0,0 +1,28 @@
...
+)
+{
+
+}
```
Comment (strkkk) [inline src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/illegaltype/InputIllegalTypeRecordsWithMemberModifiersSpecified.java:28]: new line missing

**Comment by Rahulkhinchi03** [comment]
[ERROR]   IllegalTypeCheckTest.testValidateRecordsWithConfiguredMemberModifiersPass:68->AbstractModuleTestSupport.verifyWithInlineConfigParser:267 » Checkstyle

I am getting this error. Can you please tell me what does it mean? @strkkk

File: src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/illegaltype/InputIllegalTypeRecordsWithMemberModifiersSpecified.java (hunk 2 above)
Comment (Rahulkhinchi03) [reply src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/illegaltype/InputIllegalTypeRecordsWithMemberModifiersSpecified.java:28]: How can I resolve this?

Comment (strkkk) [reply src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/illegaltype/InputIllegalTypeRecordsWithMemberModifiersSpecified.java]: it is not like this. you dont need to paste \n at the end, just have a new line

**Comment by strkkk** [comment]
> 
> 
> [ERROR] IllegalTypeCheckTest.testValidateRecordsWithConfiguredMemberModifiersPass:68->AbstractModuleTestSupport.verifyWithInlineConfigParser:267 » Checkstyle
> 
> I am getting this error. Can you please tell me what does it mean? @strkkk

run this test locally and check output

File: src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/illegaltype/InputIllegalTypeRecordsWithMemberModifiersSpecified.java (hunk 2 above)
Comment (Rahulkhinchi03) [reply src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/illegaltype/InputIllegalTypeRecordsWithMemberModifiersSpecified.java]: warning: CRLF will be replaced by LF

**Comment by Rahulkhinchi03** [comment]
> > [ERROR] IllegalTypeCheckTest.testValidateRecordsWithConfiguredMemberModifiersPass:68->AbstractModuleTestSupport.verifyWithInlineConfigParser:267 » Checkstyle
> > I am getting this error. Can you please tell me what does it mean? @strkkk
> 
> run this test locally and check output

com.puppycrawl.tools.checkstyle.api.CheckstyleException: Config comment not specified properly in InputIllegalTypeRecordsWithMemberModifiersSpecified.java

**Comment by Rahulkhinchi03** [comment]
@romani Kindly review my changes!

**Comment by strkkk** [comment]
@Rahulkhinchi03 you need to provide regression report for your fixed check. Here is manual how to do that with github actions  https://github.com/checkstyle/contribution/tree/master/checkstyle-tester#executing-generation
also you can check how it looks like in other bugfix prs, e.g. https://github.com/checkstyle/checkstyle/pull/10922

**Comment by Rahulkhinchi03** [comment]
GitHub, generate report

**Comment by Rahulkhinchi03** [comment]
@strkkk created the Diff Regression config.

**Comment by Rahulkhinchi03** [comment]
Kindly review my changes! @strkkk 
I have created the Diff Regression config.

**Review by strkkk — APPROVED** [review]

**Comment by Rahulkhinchi03** [comment]
@romani sir, kindly review my changes!

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalTypeCheck.java [hunk 3]
```diff
@@ -491,13 +491,13 @@ public void visitToken(DetailAST ast) {
...
-     * @param methodOrVariableDef METHOD_DEF or VARIABLE_DEF ast node.
+     * @param ast METHOD_DEF or VARIABLE_DEF ast node.
      * @return true if member is verifiable according to <b>memberModifiers</b> option.
      */
-    private boolean isVerifiable(DetailAST methodOrVariableDef) {
+    private boolean isVerifiable(DetailAST ast) {
         boolean result = true;
-        if (!memberModifiers.isEmpty()) {
-            final DetailAST modifiersAst = methodOrVariableDef
+        if (!memberModifiers.isEmpty() && ast.getType() != TokenTypes.RECORD_COMPONENT_DEF) {
```
Comment (romani) [inline src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalTypeCheck.java:499]: It is not clear why modifier is null.
We have modifiers on record https://github.com/checkstyle/checkstyle/blob/988cbe38621df6cf079c975fc9ca87b45a3c4af9/src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java#L5447

Records should have modifiers same as other types.

**Review by romani — CHANGES_REQUESTED** [review]
Can we have input with violation on record?

Items:

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalTypeCheck.java (hunk 3 above)
Comment (Rahulkhinchi03) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalTypeCheck.java:499]: You mean I need to change `TokenTypes.RECORD_COMPONENT_DEF -> TokenTypes.RECORD_DEF` ?

Comment (Rahulkhinchi03) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalTypeCheck.java:499]: @romani sir, can you please clarify what exactly I need to change?

Comment (Rahulkhinchi03) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalTypeCheck.java:499]: @romani  sir, can you please clarify what exactly I need to change?

**Comment by Rahulkhinchi03** [comment]
@romani sir, ping!

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalTypeCheck.java (hunk 3 above)
Comment (romani) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalTypeCheck.java:499]: I do not understand why we simply skip validation
https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java#L5513
It can have illegal type.

Please create input with violation on record component.

Comment (Rahulkhinchi03) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalTypeCheck.java:499]: @romani sir,
After changing 
public record InputIllegalTypeRecordsWithMemberModifiersSpecified
        (UUID productId, String identifier) 
-->
public record InputIllegalTypeRecordsWithMemberModifiersSpecified
        (HashSet productId, String identifier) {

This is failing and It says Violation lines for   (HashSet productId, String identifier) {expected to be empty.

File: src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/illegaltype/InputIllegalTypeRecordsWithMemberModifiersSpecified.java [hunk 4]
```diff
@@ -0,0 +1,26 @@
...
+*/
+
+//non-compiled with javac: Compilable with Java14
+package com.puppycrawl.tools.checkstyle.checks.coding.illegaltype;
+
+import java.lang.String;
+import java.util.UUID;
+
+public record InputIllegalTypeRecordsWithMemberModifiersSpecified
+        (HashSet productId, String identifier) {
```
Comment (romani) [inline src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/illegaltype/InputIllegalTypeRecordsWithMemberModifiersSpecified.java:25]: This should be violation

**Review by romani — CHANGES_REQUESTED** [review]
Please always add new test cases, the more district unique test cases the better.

File: src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/illegaltype/InputIllegalTypeRecordsWithMemberModifiersSpecified.java (hunk 4 above)
Comment (romani) [reply src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/illegaltype/InputIllegalTypeRecordsWithMemberModifiersSpecified.java:25]: Please add one more record absolutely same as in issue reported by user.

Comment (Rahulkhinchi03) [reply src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/illegaltype/InputIllegalTypeRecordsWithMemberModifiersSpecified.java:25]: Sure Sir.

**Comment by Rahulkhinchi03** [comment]
Github, rebase

File: src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/illegaltype/InputIllegalTypeRecordsWithMemberModifiersSpecified.java [hunk 5]
```diff
@@ -0,0 +1,26 @@
...
+
+//non-compiled with javac: Compilable with Java14
+package com.puppycrawl.tools.checkstyle.checks.coding.illegaltype;
+
+import java.lang.String;
+import java.util.UUID;
+
+public record InputIllegalTypeRecordsWithMemberModifiersSpecified
+        (UUID productId, String identifier) {
+} // ok
```
Comment (romani) [inline src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/illegaltype/InputIllegalTypeRecordsWithMemberModifiersSpecified.java:26]: Place comment on line where potential violation might be.
Previous line.

**Review by romani — CHANGES_REQUESTED** [review]
Items:

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalTypeCheck.java (hunk 3 above)
Comment (romani) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalTypeCheck.java:499]: This still worries me.
I probably need to debug this code to understand it

**Comment by Rahulkhinchi03** [comment]
Github, rebase

File: src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/illegaltype/InputIllegalTypeRecordsWithMemberModifiersSpecified.java (hunk 5 above)
Comment (Rahulkhinchi03) [reply src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/illegaltype/InputIllegalTypeRecordsWithMemberModifiersSpecified.java]: Done Changes!

**Comment by Rahulkhinchi03** [comment]
Github, rebase

**Comment by Rahulkhinchi03** [comment]
@romani sir, please review!

**Comment by romani** [comment]
Please do not resolve my review items, just reply "done" as you finish.

**Comment by Rahulkhinchi03** [comment]
\

> Please do not resolve my review items, just reply "done" as you finish.

Okay, I will do the same! Sorry for the inconvenience.

**Comment by Rahulkhinchi03** [comment]
@romani sir, all checks have been passed and I have resolved the changes.

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalTypeCheck.java (hunk 3 above)
Comment (romani) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalTypeCheck.java:499]: please make code like:

```
            case TokenTypes.RECORD_COMPONENT_DEF:
                visitComponentDef(ast);
                break;
```

```
visitComponentDef() {
    if (isContainVerifiableType(variableDef)) {
            checkClassName(variableDef);
        }
}
```

Comment (nmancus1) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalTypeCheck.java:499]: @romani condition in `visitComponentDef` if statement should be extended to check `memberModifiers` for `private` and `final` modifiers. The two following type declarations should be equivalent to this check, and we should expect violations on both with default config (how it works currently) and with any combination of `FINAL` and/or `LITERAL_PRIVATE`:

```java
import java.util.TreeSet;

class TestClass {
    private final TreeSet x;

    TestClass(TreeSet x) {
        this.x = x;
    }
}

record TestRecord(TreeSet x) {}

```

File: src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/illegaltype/InputIllegalTypeRecordsWithMemberModifiersSpecifiedTwo.java [hunk 6]
```diff
@@ -0,0 +1,26 @@
...
+*/
+
+//non-compiled with javac: Compilable with Java14
+package com.puppycrawl.tools.checkstyle.checks.coding.illegaltype;
+
+import java.lang.String;
+import java.util.*;
+
+public record InputIllegalTypeRecordsWithMemberModifiersSpecifiedTwo
+        (HashSet productId, String identifier) {  // violation
```
Comment (nmancus1) [inline src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/illegaltype/InputIllegalTypeRecordsWithMemberModifiersSpecifiedTwo.java:25]: Record components are basically `private final` fields. Violations for the record components in this test case should be the same as the following for the given configs:

```
➜  javac Test1.java

➜  cat Test1.java
import java.util.HashSet;

public class Test1 {
    private final HashSet productId; // violation
    private final String identifier;

    public Test1(HashSet productId, String identifier) {
        this.productId = productId;
        this.identifier = identifier;
    }
}

➜  cat config.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE module PUBLIC
    "-//Puppy Crawl//DTD Check Configuration 1.3//EN"
    "http://checkstyle.sourceforge.net/dtds/configuration_1_3.dtd">

<module name="Checker">
    <property name="charset" value="UTF-8"/>

    <module name="TreeWalker">
        <module name="IllegalType">
        </module>
    </module>
</module>                                                                                                                 

➜  java -jar checkstyle-9.1-all.jar -c config.xml Test1.java
Starting audit...
[ERROR] Test1.java:4:19: Usage of type 'HashSet' is not allowed. [IllegalType]
Audit done.
Checkstyle ends with 1 errors.

➜  cat config.xml 
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE module PUBLIC
    "-//Puppy Crawl//DTD Check Configuration 1.3//EN"
    "http://checkstyle.sourceforge.net/dtds/configuration_1_3.dtd">

<module name="Checker">
    <property name="charset" value="UTF-8"/>

    <module name="TreeWalker">
        <module name="IllegalType">
                      <property name="memberModifiers" value="FINAL"/>
        </module>
    </module>
</module>                                                                                                                

➜  java -jar checkstyle-9.1-all.jar -c config.xml Test1.java
Starting audit...
[ERROR] Test1.java:4:19: Usage of type 'HashSet' is not allowed. [IllegalType]
Audit done.
Checkstyle ends with 1 errors.

➜  cat config.xml                                           
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE module PUBLIC
    "-//Puppy Crawl//DTD Check Configuration 1.3//EN"
    "http://checkstyle.sourceforge.net/dtds/configuration_1_3.dtd">

<module name="Checker">
    <property name="charset" value="UTF-8"/>

    <module name="TreeWalker">
        <module name="IllegalType">
                      <property name="memberModifiers" value="FINAL, LITERAL_PRIVATE"/>
        </module>
    </module>
</module>%                                                                                                                 ➜  company java -jar checkstyle-9.1-all.jar -c config.xml Test1.java
Starting audit...
[ERROR] Test1.java:4:19: Usage of type 'HashSet' is not allowed. [IllegalType]
Audit done.
Checkstyle ends with 1 errors.

```

The config from this test case should not have any violations:

```

➜  cat config.xml                                           
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE module PUBLIC
    "-//Puppy Crawl//DTD Check Configuration 1.3//EN"
    "http://checkstyle.sourceforge.net/dtds/configuration_1_3.dtd">

<module name="Checker">
    <property name="charset" value="UTF-8"/>

    <module name="TreeWalker">
        <module name="IllegalType">
                      <property name="memberModifiers" value="LITERAL_PUBLIC, LITERAL_PROTECTED, LITERAL_STATIC"/>
        </module>
    </module>
</module>                                                                                                               

➜  java -jar checkstyle-9.1-all.jar -c config.xml Test1.java
Starting audit...
Audit done.

```

Comment (Rahulkhinchi03) [reply src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/illegaltype/InputIllegalTypeRecordsWithMemberModifiersSpecifiedTwo.java:25]: @nmancus1 I have changed the access specifier from 
```
public record InputIllegalTypeRecordsWithMemberModifiersSpecifiedTwo
        (HashSet productId, String identifier) {  // violation
}
```

-->

```
private final record InputIllegalTypeRecordsWithMemberModifiersSpecifiedTwo
        (HashSet productId,  // violation
         String identifier) {  
}
```

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalTypeCheck.java (hunk 3 above)
Comment (Rahulkhinchi03) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalTypeCheck.java:499]: @romani @nmancus1
After adding Romani sir's code:

```
case TokenTypes.RECORD_COMPONENT_DEF:
                visitComponentDef(ast);
                break;
```

```
  /**
     * Checks type of ComponentDef.
     *
     * @param variableDef to check.
     */
    private void visitComponentDef(DetailAST variableDef) {
        if (isContainVerifiableType(variableDef)) {
            checkClassName(variableDef);
        }
    }
```
and changing the access specifier from `PUBLIC RECORD`  to `PRIVATE FINAL RECORD`

I found no violation for HashSet so I removed  `// violation`

Comment (Rahulkhinchi03) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalTypeCheck.java:499]: After Adding Romani's code:

```
[ERROR] Failures: 
[ERROR]   IllegalTypeCheckTest.testArrayTypes:194->AbstractModuleTestSupport.verifyWithInlineConfigParser:270->AbstractModuleTestSupport.verifyViolations:427 Violation lines for C:\Users\ASUS\Desktop\OpenSource\checkstyle\src\test\resources\com\puppycrawl\tools\checkstyle\checks\coding\illegaltype\InputIllegalTypeArrays.java differ.
missing (4): 20, 22, 25, 30
---
expected   : [20, 22, 24, 25, 29, 30]
but was    : [24, 29]
[ERROR]   IllegalTypeCheckTest.testGenerics:232->AbstractModuleTestSupport.verifyWithInlineConfigParser:270->AbstractModuleTestSupport.verifyViolations:427 Violation lines for C:\Users\ASUS\Desktop\OpenSource\checkstyle\src\test\resources\com\puppycrawl\tools\checkstyle\checks\coding\illegaltype\InputIllegalTypeTestGenerics.java differ.
missing (5): 28, 29 [2 copies], 33, 68
---
expected   : [28, 29, 29, 32, 33, 33, 36, 36, 38, 40, 40, 42, 42, 46, 46, 55, 68]
but was    : [32, 33, 36, 36, 38, 40, 40, 42, 42, 46, 46, 55]
[ERROR]   IllegalTypeCheckTest.testIgnoreMethodNames:122->AbstractModuleTestSupport.verifyWithInlineConfigParser:270->AbstractModuleTestSupport.verifyViolations:427 Violation lines for C:\Users\ASUS\Desktop\OpenSource\checkstyle\src\test\resources\com\puppycrawl\tools\checkstyle\checks\coding\illegaltype\InputIllegalTypeTestIgnoreMethodNames.java differ.
missing (2): 23, 26
---
expected   : [23, 26, 34, 43, 60, 62]
but was    : [34, 43, 60, 62]
[ERROR]   IllegalTypeCheckTest.testIllegalTypeEnhancedInstanceof:327->AbstractModuleTestSupport.verifyWithInlineConfigParser:270->AbstractModuleTestSupport.verifyViolations:427 Violation lines for C:\Users\ASUS\Desktop\OpenSource\checkstyle\src\test\resources-noncompilable\com\puppycrawl\tools\checkstyle\checks\coding\illegaltype\InputIllegalTypeTestEnhancedInstanceof.java differ.
missing (4): 28, 31, 35, 41
---
expected   : [28, 31, 35, 40, 41]
but was    : [40]
[ERROR]   IllegalTypeCheckTest.testIllegalTypeNewArrayStructure:356->AbstractModuleTestSupport.verifyWithInlineConfigParser:270->AbstractModuleTestSupport.verifyViolations:427 Violation lines for C:\Users\ASUS\Desktop\OpenSource\checkstyle\src\test\resources\com\puppycrawl\tools\checkstyle\checks\coding\illegaltype\InputIllegalTypeNewArrayStructure.java differ.
missing (1): 26
---
expected   : [26]
but was    : []
[ERROR]   IllegalTypeCheckTest.testIllegalTypeRecordsAndCompactCtors:344->AbstractModuleTestSupport.verifyWithInlineConfigParser:270->AbstractModuleTestSupport.verifyViolations:427 Violation lines for C:\Users\ASUS\Desktop\OpenSource\checkstyle\src\test\resources-noncompilable\com\puppycrawl\tools\checkstyle\checks\coding\illegaltype\InputIllegalTypeRecordsAndCompactCtors.java differ.
missing (5): 27, 32, 35, 39, 48
---
expected   : [27, 31, 32, 35, 39, 40, 48]
but was    : [31, 40]
[ERROR]   IllegalTypeCheckTest.testLegalAbstractClassNames:153->AbstractModuleTestSupport.verifyWithInlineConfigParser:270->AbstractModuleTestSupport.verifyViolations:427 Violation lines for C:\Users\ASUS\Desktop\OpenSource\checkstyle\src\test\resources\com\puppycrawl\tools\checkstyle\checks\coding\illegaltype\InputIllegalTypeTestLegalAbstractClassNames.java differ.
missing (1): 26
---
expected   : [26, 34, 35, 60, 62]
but was    : [34, 35, 60, 62]
[ERROR]   IllegalTypeCheckTest.testMemberModifiers:288->AbstractModuleTestSupport.verifyWithInlineConfigParser:270->AbstractModuleTestSupport.verifyViolations:427 Violation lines for C:\Users\ASUS\Desktop\OpenSource\checkstyle\src\test\resources\com\puppycrawl\tools\checkstyle\checks\coding\illegaltype\InputIllegalTypeTestMemberModifiers.java differ.
missing (4): 22, 25, 39, 49
---
expected   : [22, 25, 32, 33, 39, 41, 49]
but was    : [32, 33, 41]
[ERROR]   IllegalTypeCheckTest.testPlainAndArrayTypes:207->AbstractModuleTestSupport.verifyWithInlineConfigParser:270->AbstractModuleTestSupport.verifyViolations:427 Violation lines for C:\Users\ASUS\Desktop\OpenSource\checkstyle\src\test\resources\com\puppycrawl\tools\checkstyle\checks\coding\illegaltype\InputIllegalTypeTestPlainAndArraysTypes.java differ.
missing (3): 20, 24, 36
---
expected   : [20, 24, 26, 35, 36]
but was    : [26, 35]
[ERROR]   IllegalTypeCheckTest.testSameFileNameFalsePositive:164->AbstractModuleTestSupport.verifyWithInlineConfigParser:270->AbstractModuleTestSupport.verifyViolations:427 Violation lines for C:\Users\ASUS\Desktop\OpenSource\checkstyle\src\test\resources\com\puppycrawl\tools\checkstyle\checks\coding\illegaltype\InputIllegalTypeSameFileNameFalsePositive.java differ.
missing (2): 28, 43
---
expected   : [28, 43]
but was    : []
[ERROR]   IllegalTypeCheckTest.testSameFileNameGeneral:180->AbstractModuleTestSupport.verifyWithInlineConfigParser:270->AbstractModuleTestSupport.verifyViolations:427 Violation lines for C:\Users\ASUS\Desktop\OpenSource\checkstyle\src\test\resources\com\puppycrawl\tools\checkstyle\checks\coding\illegaltype\InputIllegalTypeTestSameFileNameGeneral.java differ.
missing (6): 25, 39, 40, 42, 43, 44
---
expected   : [25, 29, 31, 39, 40, 42, 43, 44]
but was    : [29, 31]
[ERROR]   IllegalTypeCheckTest.testStarImports:260->AbstractModuleTestSupport.verifyWithInlineConfigParser:270->AbstractModuleTestSupport.verifyViolations:427 Violation lines for C:\Users\ASUS\Desktop\OpenSource\checkstyle\src\test\resources\com\puppycrawl\tools\checkstyle\checks\coding\illegaltype\InputIllegalTypeTestStarImports.java differ.
missing (1): 25
---
expected   : [25]
but was    : []
[ERROR]   IllegalTypeCheckTest.testStaticImports:272->AbstractModuleTestSupport.verifyWithInlineConfigParser:270->AbstractModuleTestSupport.verifyViolations:427 Violation lines for C:\Users\ASUS\Desktop\OpenSource\checkstyle\src\test\resources\com\puppycrawl\tools\checkstyle\checks\coding\illegaltype\InputIllegalTypeTestStaticImports.java differ.
missing (1): 28
---
expected   : [28, 30]
but was    : [30]
[ERROR]   IllegalTypeCheckTest.testValidateAbstractClassNamesSetToTrue:52->AbstractModuleTestSupport.verifyWithInlineConfigParser:270->AbstractModuleTestSupport.verifyViolations:427 Violation lines for C:\Users\ASUS\Desktop\OpenSource\checkstyle\src\test\resources\com\puppycrawl\tools\checkstyle\checks\coding\illegaltype\InputIllegalTypeTestAbstractClassNamesTrue.java differ.
missing (1): 44
---
expected   : [27, 44, 46, 50]
but was    : [27, 46, 50]
[INFO] 
[ERROR] Tests run: 3652, Failures: 14, Errors: 0, Skipped: 1
```

Comment (Rahulkhinchi03) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalTypeCheck.java:499]: Should I resolve all these error or stick to only the current issue?

Comment (nmancus1) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalTypeCheck.java:499]: Update to check should look something like this: https://github.com/checkstyle/checkstyle/commit/959d778801a28d1e40d3f1bc268ec820660b1df0

Comment (Rahulkhinchi03) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalTypeCheck.java:499]: After doing this, there will be no violations, right?

Comment (Rahulkhinchi03) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalTypeCheck.java:499]: @nmancus1 After doing like #959d778 I am getting no violations for HashSet, is it okay or are we expecting any violation?

Comment (nmancus1) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalTypeCheck.java:499]: Amend all test cases to have comparable class definition for each given record definition to show identical violations (or lack thereof) as detailed in https://github.com/checkstyle/checkstyle/pull/10958/files#r758611207 . Also, please read about record definitions and record components to better understand how they relate to class definitions athttps://openjdk.java.net/jeps/359.

Comment (Rahulkhinchi03) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalTypeCheck.java:499]: @nmancus1  Please check my changes and Kindly reply for the same:
https://gist.github.com/Rahulkhinchi03/73db12098dc8d808b750ab3bc7d3c76e

**Comment by Rahulkhinchi03** [comment]
Github, rebase

**Comment by Rahulkhinchi03** [comment]
Github, rebase

**Comment by Rahulkhinchi03** [comment]
Github, rebase

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalTypeCheck.java (hunk 3 above)
Comment (nmancus1) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalTypeCheck.java:501]: You should amend test cases to include an equivalent class definition. This will help you to convince reviewers (and yourself) that:

```java

class TestClass {
    private final TreeSet x; // <- this declaration

    TestClass(TreeSet x) {
        this.x = x;
    }
}

```

is treated the same, with any configuration, that:

```java

record TestRecord(
        TreeSet x // <- this record component is
) {}

```

So for member modifiers like `LITERAL_PUBLIC, LITERAL_PROTECTED, LITERAL_STATIC`, the above examples should produce no violations, since `TestClass.x` is `private final` and `TestRecord.x` has implied modifiers `final` and `private`. The above examples would produce violations for the default config, and should for member modifiers like `FINAL` and `LITERAL_PRIVATE` or any combination thereof.

Comment (Rahulkhinchi03) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalTypeCheck.java:501]: Thank you so much @nmancus1  for the easy explanation.
@nmancus1 Please help me with the coverage issue: branch coverage is 0.97%

Comment (Rahulkhinchi03) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalTypeCheck.java:501]: Also, I am getting an error of `javac14` that I cannot use` private` in the private final record

Comment (nmancus1) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalTypeCheck.java:501]: To start with, you should have two or three test input files that are the same code, with different configs (this will be necessary for coverage), to show that violations (or lack thereof) are the same for test input that **includes** the following:

```java

import java.util.TreeSet;

class TestClass {
    private final TreeSet x; // <- any 'violation' or 'ok' here

    TestClass(TreeSet x) {
        this.x = x;
    }
}

record TestRecord(
        TreeSet x // // <- should be identical to `violation' or 'ok' here, for any config
) {}


```

Comment (Rahulkhinchi03) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalTypeCheck.java:501]: I am sorry but It is quite complex for be as a beginner

Comment (nmancus1) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalTypeCheck.java:501]: See https://github.com/nmancus1/checkstyle/commit/a50a96ffba8b8d8a0fa942bf4f1a7399b636a2f5

Comment (Rahulkhinchi03) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalTypeCheck.java:501]: Thanks a lot! @nmancus1 I understood now where my mistake was.

Comment (Rahulkhinchi03) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalTypeCheck.java:501]: branches covered ratio is 0.99, but expected minimum is 1.00

Comment (Rahulkhinchi03) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalTypeCheck.java:501]: I am still getting this issue @nmancus1 
`branches covered ratio is 0.99, but expected minimum is 1.00
`

Even after changing everything

Comment (nmancus1) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalTypeCheck.java:501]: Push your changes so that I can help; note that you do not need to modify the `isVerifiable` method in any way now, this method does not deal with record components at all anymore.

**Comment by Rahulkhinchi03** [comment]
Github, rebase

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalTypeCheck.java [hunk 7]
```diff
@@ -491,13 +493,13 @@ public void visitToken(DetailAST ast) {
...
-     * @param methodOrVariableDef METHOD_DEF or VARIABLE_DEF ast node.
+     * @param ast METHOD_DEF or VARIABLE_DEF ast node.
      * @return true if member is verifiable according to <b>memberModifiers</b> option.
      */
-    private boolean isVerifiable(DetailAST methodOrVariableDef) {
+    private boolean isVerifiable(DetailAST ast) {
         boolean result = true;
         if (!memberModifiers.isEmpty()) {
-            final DetailAST modifiersAst = methodOrVariableDef
+            final DetailAST modifiersAst = ast
```
Comment (nmancus1) [inline src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalTypeCheck.java:502]: Now these changes are not related to issue we are solving. So, you must either:

1. Revert these changes
2. Make these as a separate commit, something like `minor: refactor...`

I suggest (1), to help ease review in this PR; the less changes, the easier the review process, and increased confidence on reviewer's part of changes in contributor's PR.

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalTypeCheck.java [hunk 8]
```diff
@@ -569,10 +586,10 @@ private void visitParameterDef(DetailAST parameterDef) {
...
 
     /**
-     * Checks type of given variable.
-     *
-     * @param variableDef variable to check.
-     */
+         * Checks type of given variable.
+         *
+         * @param variableDef variable to check.
+         */
```
Comment (nmancus1) [inline src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalTypeCheck.java:592]: Please revert this.

Comment (Rahulkhinchi03) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalTypeCheck.java:592]: Done Changes

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalTypeCheck.java (hunk 7 above)
Comment (Rahulkhinchi03) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalTypeCheck.java:502]: Okay, I am doing it.

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalTypeCheck.java (hunk 8 above)
Comment (romani) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalTypeCheck.java:592]: Not done

Comment (Rahulkhinchi03) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalTypeCheck.java:592]: Sir, It is done and I am just pushing my code in a minute.

**Comment by Rahulkhinchi03** [comment]
Github, rebase

**Comment by Rahulkhinchi03** [comment]
Github, rebase

**Comment by Rahulkhinchi03** [comment]
@romani sir and @nmancus1, please review my changes

File: src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/illegaltype/InputIllegalTypeRecordsWithMemberModifiersSpecifiedTwo.java (hunk 6 above)
Comment (romani) [reply src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/illegaltype/InputIllegalTypeRecordsWithMemberModifiersSpecifiedTwo.java]: this is not exactly same as class fields.
Class fields can be HashSet but Ctor argument is Set:
```
public class Test1 {
    private final HashSet productId; // violation
    private final String identifier;

    public Test1(Set productId, String identifier) {
        this.productId = (HashSet)productId;
        this.identifier = identifier;
    }
}
```
so such Class does not expose HashSet requirements outside, and do "bad" stuff completely internally. So it is fine. 

"records" do expose illegal type outside and almost force all user to use illegal type.

We need to work/behave as on records as we behave on constructors.
if 
```
    public Test1(HashSet productId, String identifier) { // violation
        this.productId = (HashSet)productId;
        this.identifier = identifier;
    }
```
then
```
     record Test1(HashSet productId, String identifier); /// vilation
```

this should remove special treat consideration of FINAL and PRIVATE from code.

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalTypeCheck.java (hunk 8 above)
Comment (romani) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalTypeCheck.java]: resolved

**Comment by romani** [comment]
@Rahulkhinchi03 , please consider https://github.com/checkstyle/checkstyle/pull/10958#discussion_r759963865

File: src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/illegaltype/InputIllegalTypeRecordsWithMemberModifiersSpecifiedTwo.java (hunk 6 above)
Comment (Rahulkhinchi03) [reply src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/illegaltype/InputIllegalTypeRecordsWithMemberModifiersSpecifiedTwo.java]: @romani sir, I am getting no violation when I am using:
```
    public Test1(HashSet productId, String identifier) { // violation
        this.productId = (HashSet)productId;
        this.identifier = identifier;
    }
```

Comment (Rahulkhinchi03) [reply src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/illegaltype/InputIllegalTypeRecordsWithMemberModifiersSpecifiedTwo.java]: Okay Done.

**Comment by Rahulkhinchi03** [comment]
Github, rebase

**Comment by Rahulkhinchi03** [comment]
Github, rebase

**Comment by Rahulkhinchi03** [comment]
@romani sir, I cant understand the failing test cases: ` (Job MacOS JDK13 verify)`

File: src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/illegaltype/InputIllegalTypeRecordsWithMemberModifiersSpecifiedTwo.java (hunk 6 above)
Comment (nmancus1) [reply src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/illegaltype/InputIllegalTypeRecordsWithMemberModifiersSpecifiedTwo.java]: > We need to work/behave as on records as we behave on constructors.

This was my first thought as well, but this check does not check constructors parameters at all:

```java
    private void visitParameterDef(DetailAST parameterDef) {
        final DetailAST grandParentAST = parameterDef.getParent().getParent();

        if (grandParentAST.getType() == TokenTypes.METHOD_DEF && isCheckedMethod(grandParentAST)) {
            checkClassName(parameterDef);
        }
    }

```

Example:

```bash
        |--CTOR_DEF -> CTOR_DEF [4:4]
...
        |   |--PARAMETERS -> PARAMETERS [4:16]
        |   |   `--PARAMETER_DEF -> PARAMETER_DEF [4:16]
...
        |--METHOD_DEF -> METHOD_DEF [8:4]
...
        |   |--PARAMETERS -> PARAMETERS [8:16]
        |   |   `--PARAMETER_DEF -> PARAMETER_DEF [8:16]
...


```

This check relies on the given class's fields to put violations on illegal types, not constructor parameters. To me, this means that we should check record components as the fields they represent (`private final ...`), because this is how check currently operates on classes.

> so such Class does not expose HashSet requirements outside, and do "bad" stuff completely internally

This check does not have idea of "levels" of access modifiers; it only checks that if token has specified access modifiers (if `memberModifier` property is used) then we verify that it does not declare an illegal type. So, there is no concept of "outside" or "inside" to this check.

So, we have to make a decision on how to treat record components, and what implied modifiers that they carry. If we do not, they will not be checked at all if `memberModifiers` property is used at all. I can think of a few different solutions:

1. use example above (treat them as `private final`)
2. treat them as `public`
3. always check them, regardless of specified `memberModifiers` property as long as token is specified in config or default
4. let record components "inherit" access modifier of record declaration

Comment (Rahulkhinchi03) [reply src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/illegaltype/InputIllegalTypeRecordsWithMemberModifiersSpecifiedTwo.java]: So Do I need to change anything? @nmancus1 @romani

Comment (Rahulkhinchi03) [reply src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/illegaltype/InputIllegalTypeRecordsWithMemberModifiersSpecifiedTwo.java]: Do I need to revert changes again? @romani @nmancus1

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalTypeCheck.java [hunk 9]
```diff
@@ -525,6 +527,21 @@ private boolean isContainVerifiableType(DetailAST modifiers) {
...
+     * Checks a record component definition. Record components are private
+     * final fields, so we check code in a similar manner as we do for
+     * private final class members.
+     *
+     * @param recordComponentDef the record component definition to check.
+     */
+    private void visitRecordComponentDef(DetailAST recordComponentDef) {
+        if (memberModifiers.isEmpty()
+                || memberModifiers.contains(TokenTypes.LITERAL_PRIVATE)
+                || memberModifiers.contains(TokenTypes.FINAL)) {
```
Comment (romani) [inline src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalTypeCheck.java:540]: I do not think this conditions are required.
See my comment above that it should be validated  like ctor

**Review by romani — CHANGES_REQUESTED** [review]
Please fix CI

Items

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalTypeCheck.java (hunk 9 above)
Comment (Rahulkhinchi03) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalTypeCheck.java:540]: @romani sir, should I push my previous changes CONDITIONS again instead of this?
Please checkout: https://github.com/Rahulkhinchi03/checkstyle/commit/7731e7cfa2c300bb36d4ba13f233075ca230b9e1

**Comment by Rahulkhinchi03** [comment]
Github, rebase

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalTypeCheck.java (hunk 9 above)
Comment (Rahulkhinchi03) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalTypeCheck.java]: Done!

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalTypeCheck.java (hunk 3 above)
Comment (Rahulkhinchi03) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalTypeCheck.java]: > 

Using this code, I am getting violation error in file ` InputIllegalTypeRecordsAndCompactCtor`,

1. Should I use this code only and resolve these errors too?
2. Or Should I use: 
 ```
private void visitRecordComponentDef(DetailAST recordComponentDef) {
        if (memberModifiers.isEmpty()) {
            checkClassName(recordComponentDef);
        }
    }
```

Using point 2, I am getting no error.

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalTypeCheck.java (hunk 9 above)
Comment (Rahulkhinchi03) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalTypeCheck.java]:
```
case TokenTypes.RECORD_COMPONENT_DEF:
                visitComponentDef(ast);
                break;
```

```
  /**
     * Checks type of ComponentDef.
     *
     * @param variableDef to check.
     */
    private void visitComponentDef(DetailAST variableDef) {
        if (isContainVerifiableType(variableDef)) {
            checkClassName(variableDef);
        }
    }
```
Using this code , I am getting violation error in file ` InputIllegalTypeRecordsAndCompactCtor`,



1. Should I use this code only and resolve these errors too?
2. Or Should I use: 
 ```
private void visitRecordComponentDef(DetailAST recordComponentDef) {
        if (memberModifiers.isEmpty()) {
            checkClassName(recordComponentDef);
        }
    }
```

Using point 2, I am getting no error.

File: src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/illegaltype/InputIllegalTypeRecordsWithMemberModifiersSpecifiedTwo.java (hunk 6 above)
Comment (Rahulkhinchi03) [reply src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/illegaltype/InputIllegalTypeRecordsWithMemberModifiersSpecifiedTwo.java]: @romani sir, I updated the `SET in CTOR` and type cast `HashSet` in my recent changes.
https://github.com/checkstyle/checkstyle/pull/10958/files#diff-ca66a50cfe72a8a6786eac504d6efe1f7a3f6f79bb3428da3d07ae82330b4429R56-R58

**Comment by Rahulkhinchi03** [comment]
@romani sir, please review my changes.

**Comment by Rahulkhinchi03** [comment]
@romani  sir, please review my changes.

**Comment by Rahulkhinchi03** [comment]
@romani sir, please review my changes.

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalTypeCheck.java [hunk 10]
```diff
@@ -525,6 +527,19 @@ private boolean isContainVerifiableType(DetailAST modifiers) {
...
 
+    /**
+     * Checks a record component definition. Record components are private
+     * final fields, so we check code in a similar manner as we do for
+     * private final class members.
+     *
+     * @param recordComponentDef the record component definition to check.
+     */
+    private void visitRecordComponentDef(DetailAST recordComponentDef) {
+        if (memberModifiers.isEmpty()) {
```
Comment (romani) [inline src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalTypeCheck.java:538]: this looks strange.
Lets remove this condition and update javadoc for this property `memberModifiers`. 
from `This property does not affect method calls nor method references. ` to `This property does not affect method calls nor method references nor record components. `

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalTypeCheck.java [hunk 11]
```diff
@@ -525,6 +527,19 @@ private boolean isContainVerifiableType(DetailAST modifiers) {
         return result;
     }
 
+    /**
+     * Checks a record component definition. Record components are private
+     * final fields, so we check code in a similar manner as we do for
+     * private final class members.
```
Comment (romani) [inline src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalTypeCheck.java:533]:
```
* final fields, so we do not consider memberModifiers field.
```

File: src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/illegaltype/InputIllegalTypeRecordsWithMemberModifiersDefault.java [hunk 12]
```diff
@@ -0,0 +1,63 @@
+/*
+IllegalType
+validateAbstractClassNames = (default)false
+illegalClassNames = (default)HashMap, HashSet, LinkedHashMap, LinkedHashSet, TreeMap, TreeSet, \
+                    java.util.HashMap, java.util.HashSet, java.util.LinkedHashMap, \
+                    java.util.LinkedHashSet, java.util.TreeMap, java.util.TreeSet
+legalAbstractClassNames = (default)
+ignoredMethodNames = (default)getEnvironment, getInitialContext
+illegalAbstractClassNameFormat = (default)^(.*[.])?Abstract.*$
+memberModifiers = FINAL
```
Comment (romani) [inline src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/illegaltype/InputIllegalTypeRecordsWithMemberModifiersDefault.java:10]: it is not default, please make it default.

**Review by romani — CHANGES_REQUESTED** [review]
please make a test without RCOND_COMPONENT_DEF in tokens to prove that no violation happens.

items:

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalTypeCheck.java (hunk 9 above)
Comment (romani) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalTypeCheck.java]: see comment at https://github.com/checkstyle/checkstyle/pull/10958#discussion_r762465306

File: src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/illegaltype/InputIllegalTypeRecordsWithMemberModifiersSpecifiedTwo.java (hunk 6 above)
Comment (romani) [reply src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/illegaltype/InputIllegalTypeRecordsWithMemberModifiersSpecifiedTwo.java]: > but this check does not check constructor parameters at all

it is separate new issue.
Check is very general, it tries to catch illegal classes in all places. It does validation of Method arguments. 

Please see proposal to update javadoc at https://github.com/checkstyle/checkstyle/pull/10958#discussion_r762465306 to make it clear that modifiers arenot considered for RECORD_COMPONENT_DEF

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalTypeCheck.java (hunk 10 above)
Comment (Rahulkhinchi03) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalTypeCheck.java:538]: @romani sir, I added your condition:
```
    /**
     * Checks a record component definition. Record components are private
     * final fields, so we do not consider memberModifiers field. This
     * property does not affect method calls nor method references
     * nor record components.
     *
     * @param variableDef the record component definition to check.
     */
    private void visitComponentDef(DetailAST variableDef) {
            if (isContainVerifiableType(variableDef)) {
                checkClassName(variableDef);
            }
    }
```

And all my test case for this Issue has been passed BUT I have got one error from another file then this issue:
File Name: InputIllegalTypeRecordsAndCompactCtors.java
Error:
expected   : [27, 31, 32, 35, 39, 40, 48]
but was    : [31, 32, 35, 40, 48]

Should I resolve these errors too? These are not related to this issue.

File: src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/illegaltype/InputIllegalTypeRecordsWithMemberModifiersSpecifiedTwo.java (hunk 6 above)
Comment (Rahulkhinchi03) [reply src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/illegaltype/InputIllegalTypeRecordsWithMemberModifiersSpecifiedTwo.java]: @nmancus1 I think we can create a new issue regarding this?

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalTypeCheck.java (hunk 3 above)
Comment (Rahulkhinchi03) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalTypeCheck.java]: @nmancus1 I am again getting the branch and line overage issue. I only updated the Java Doc.

Comment (Rahulkhinchi03) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalTypeCheck.java]: @nmancus1  I am again getting the branch and line overage issue. I only updated the Java Doc and Added Romani sir's Code so I was getting an error and I updated to https://github.com/checkstyle/checkstyle/pull/10958#discussion_r762512351 

```
    /**
     * Checks a record component definition. Record components are private
     * final fields, so we do not consider memberModifiers field.
     *
     * @param recordComponentDef the record component definition to check.
     */
    private void visitRecordComponentDef(DetailAST recordComponentDef) {
            if (isContainVerifiableType(recordComponentDef)) {
                checkClassName(recordComponentDef);
            }
    }
```

To be precise:  `checkClassName(recordComponentDef);` This line is red and not in coverage

**Comment by Rahulkhinchi03** [comment]
I updated the java Doc property for memberModifier and also removed the condition. Now, I am getting branches and lines coverage issues.
Specifically for these line: `checkClassName(recordComponentDef);`

Code:
```
    /**
     * Checks a record component definition. Record components are private
     * final fields, so we do not consider memberModifiers field. 
     *
     * @param variableDef the record component definition to check.
     */
    private void visitRecordComponentDef(DetailAST recordComponentDef) {
            if (isContainVerifiableType(recordComponentDef)) {
                checkClassName(recordComponentDef);
            }
    }
```

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalTypeCheck.java (hunk 10 above)
Comment (Rahulkhinchi03) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalTypeCheck.java:538]: Can we use this condition?
```
    private void visitRecordComponentDef(DetailAST recordComponentDef) {
        if (!memberModifiers.isEmpty()) {
            return;
        }
        checkClassName(recordComponentDef);
    }
```

**Comment by romani** [comment]
Please push your changes to GitHub to let me see them.

**Comment by Rahulkhinchi03** [comment]
Github, rebase

File: src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/illegaltype/InputIllegalTypeRecordsWithMemberModifiersDefault.java (hunk 12 above)
Comment (Rahulkhinchi03) [reply src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/illegaltype/InputIllegalTypeRecordsWithMemberModifiersDefault.java]: Done

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalTypeCheck.java (hunk 11 above)
Comment (Rahulkhinchi03) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalTypeCheck.java:533]: Done

Comment (Rahulkhinchi03) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalTypeCheck.java:533]: I will surely do it when I push changes again.

**Comment by Rahulkhinchi03** [comment]
@romani sir, changes pushed.

**Comment by Rahulkhinchi03** [comment]
@romani  sir, changes pushed.

**Comment by Rahulkhinchi03** [comment]
@romani  sir, changes pushed.

**Comment by Rahulkhinchi03** [comment]
@romani sir, please review my changes.

File: src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/illegaltype/InputIllegalTypeRecordsAndCompactCtors.java [hunk 13]
```diff
@@ -24,7 +24,7 @@
 
 public class InputIllegalTypeRecordsAndCompactCtors {
     record MyTestRecord
-            (LinkedHashMap<Integer, Integer> linkedHashMap) { // violation
+            (LinkedHashMap<Integer, Integer> linkedHashMap) { // OK
```
Comment (romani) [inline src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/illegaltype/InputIllegalTypeRecordsAndCompactCtors.java:28]: It should be violation

File: src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/illegaltype/InputIllegalTypeRecordsWithMemberModifiersDefault.java [hunk 14]
```diff
@@ -0,0 +1,63 @@
...
+        private final String identifier; // ok
+
+        public IdentifiersPairEquivalent(UUID productId, String identifier) {
+            this.productId = productId;
+            this.identifier = identifier;
+        }
+    }
+
+    public record IdentifiersPair2(
+        HashSet x, // ok
```
Comment (romani) [inline src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/illegaltype/InputIllegalTypeRecordsWithMemberModifiersDefault.java:45]: It should be violation.
Why is it ok ?

**Review by romani — CHANGES_REQUESTED** [review]
Items:

File: src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/illegaltype/InputIllegalTypeRecordsWithMemberModifiersDefault.java (hunk 14 above)
Comment (Rahulkhinchi03) [reply src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/illegaltype/InputIllegalTypeRecordsWithMemberModifiersDefault.java:45]: I first made it violation but I was getting an error that it is not violation with the given condition

File: src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/illegaltype/InputIllegalTypeRecordsAndCompactCtors.java (hunk 13 above)
Comment (Rahulkhinchi03) [reply src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/illegaltype/InputIllegalTypeRecordsAndCompactCtors.java:28]: I think the condition is not working with these violations.

File: src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/illegaltype/InputIllegalTypeRecordsWithMemberModifiersDefault.java (hunk 14 above)
Comment (romani) [reply src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/illegaltype/InputIllegalTypeRecordsWithMemberModifiersDefault.java:45]: Please update expected list in Test.
It should be violation.

File: src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/illegaltype/InputIllegalTypeRecordsAndCompactCtors.java (hunk 13 above)
Comment (romani) [reply src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/illegaltype/InputIllegalTypeRecordsAndCompactCtors.java:28]: We need to keep violation. Code should be updated.

File: src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/illegaltype/InputIllegalTypeRecordsWithMemberModifiersDefault.java (hunk 14 above)
Comment (Rahulkhinchi03) [reply src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/illegaltype/InputIllegalTypeRecordsWithMemberModifiersDefault.java:45]: 45 is an expected list but it is still showing that it is not an error. I added the expected List in the Test but still it says that it shouldn't be the violation for this line.

Comment (Rahulkhinchi03) [reply src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/illegaltype/InputIllegalTypeRecordsWithMemberModifiersDefault.java:45]: aff

Comment (Rahulkhinchi03) [reply src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/illegaltype/InputIllegalTypeRecordsWithMemberModifiersDefault.java:45]: I updated the ExpectedList in Test and also added  `HashSet x, // violation`
But I am still getting an error.

File: src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/illegaltype/InputIllegalTypeRecordsAndCompactCtors.java (hunk 13 above)
Comment (Rahulkhinchi03) [reply src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/illegaltype/InputIllegalTypeRecordsAndCompactCtors.java:28]: Can we use LinkedHashUp as a Parameter?

File: src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/illegaltype/InputIllegalTypeRecordsWithMemberModifiersDefault.java (hunk 14 above)
Comment (Rahulkhinchi03) [reply src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/illegaltype/InputIllegalTypeRecordsWithMemberModifiersDefault.java:45]: @nmancus1 can you please help me with this?

Comment (nmancus1) [reply src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/illegaltype/InputIllegalTypeRecordsWithMemberModifiersDefault.java:45]: Please see https://github.com/checkstyle/checkstyle/pull/10958#discussion_r762661072 

You need to make changes in the check to align with behavior specified by @romani at https://github.com/checkstyle/checkstyle/pull/10958#discussion_r762466240.

Comment (Rahulkhinchi03) [reply src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/illegaltype/InputIllegalTypeRecordsWithMemberModifiersDefault.java:45]: @nmancus1 like this?
```
 private void visitRecordComponentDef(DetailAST recordComponentDef) {
        if (memberModifiers.contains(TokenTypes.RECORD_COMPONENT_DEF)) {
            checkClassName(recordComponentDef);
        }
    }
```

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalTypeCheck.java (hunk 11 above)
Comment (Rahulkhinchi03) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalTypeCheck.java]: Done

**Comment by Rahulkhinchi03** [comment]
Github, rebase

**Comment by Rahulkhinchi03** [comment]
Github, rebase

**Comment by Rahulkhinchi03** [comment]
Github, rebase

**Comment by Rahulkhinchi03** [comment]
@nmancus1 @romani sir,
I ran the coverage and found 100% but now it is showing branch coverage is 98% only.

**Comment by Rahulkhinchi03** [comment]
@romani sir, please review my changes!

**Comment by Rahulkhinchi03** [comment]
@romani  sir, please review my changes!

**Comment by Rahulkhinchi03** [comment]
Github, rebase

**Comment by Rahulkhinchi03** [comment]
@romani sir,
I ran the coverage and found 100% but now it is showing branch coverage is 98% only. I updated the code. Please review my changes!

**Comment by Rahulkhinchi03** [comment]
Github, rebase

**Comment by Rahulkhinchi03** [comment]
@romani  sir,
I ran the coverage and found 100% but now it is showing branch coverage is 98% only. I updated the code. Please review my changes!

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalTypeCheck.java [hunk 15]
```diff
@@ -525,6 +527,18 @@ private boolean isContainVerifiableType(DetailAST modifiers) {
...
     }
 
+    /**
+     * Checks a record component definition. Record components are private
+     * final fields, so we do not consider memberModifiers field.
+     *
+     * @param recordComponentDef the record component definition to check.
+     */
+    public void visitRecordComponentDef(DetailAST recordComponentDef) {
+        if (recordComponentDef.getType() == TokenTypes.RECORD_COMPONENT_DEF) {
```
Comment (nmancus1) [inline src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalTypeCheck.java:537]: Explain why we need this condition.

Comment (Rahulkhinchi03) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalTypeCheck.java:537]: We know that the RECORD_COMPONENT_DEF can catch illegal types from any place so we need a condition that can check to be it public, private, protected, final, We need a check which can check RECORD_COMPONENT-DEF type.

So if  whatever the type is of recordComponentDef, if it is equal to the token, we defined, then checkClassName(recordComponentDef);

Comment (nmancus1) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalTypeCheck.java:537]: Let me rephrase; how is this condition different than the precondition required to reach this method?

Comment (Rahulkhinchi03) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalTypeCheck.java:537]: In previous conditions, we were specifically checking for private and final member modifiers but Romani sir said that It not only check private and final but anything. So we have to consider them like constructors.

This condition is different from the pre-defined condition because before we were only checking the fields of the record components but now with this condition, we are checking every field and not specific to any particular field.

Comment (Rahulkhinchi03) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalTypeCheck.java:537]: So we had an option to how to treat these member modifiers and with your options that we can check public or private/final or we can check them for all the specified memberModifiers property

Comment (Rahulkhinchi03) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalTypeCheck.java:537]: Please guide me If It is wrong.

Comment (nmancus1) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalTypeCheck.java:537]: Please take some time, and read the documentation for `DetailAST#getType` and `TokenTypes`. Then, generate a coverage report https://github.com/checkstyle/checkstyle/wiki/How-to-run-certain-phases-and-validations to see what line is failing if you have not done this already. After that, try to understand why the code that is not covered is failing.

Comment (Rahulkhinchi03) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalTypeCheck.java:537]: Sure, thanks for the link.
@nmancus1 but every line is covered when I ran code coverage in my local environment. It's 100%

Comment (nmancus1) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalTypeCheck.java:537]: Then your local branch is not in sync with this PR branch.

Comment (Rahulkhinchi03) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalTypeCheck.java:537]: @nmancus1 I think this will work better?
 ```
 public void visitRecordComponentDef(DetailAST recordComponentDef) {
       checkClassName(recordComponentDef);
    }
```

**Comment by Rahulkhinchi03** [comment]
Github, rebase

**Comment by romani** [comment]
Github, rebase

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalTypeCheck.java [hunk 16]
```diff
@@ -525,6 +527,16 @@ private boolean isContainVerifiableType(DetailAST modifiers) {
...
     }
 
+    /**
+     * Checks a record component definition. Record components are private
+     * final fields, so we do not consider memberModifiers field.
+     *
+     * @param recordComponentDef the record component definition to check.
+     */
+    public void visitRecordComponentDef(DetailAST recordComponentDef) {
+        checkClassName(recordComponentDef);
```
Comment (romani) [inline src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalTypeCheck.java:537]: Simply use this method in "case"

File: src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalTypeCheckTest.java [hunk 17]
```diff
@@ -330,7 +329,6 @@ public void testIllegalTypeRecordsAndCompactCtors() throws Exception {
 
     @Test
     public void testIllegalTypeNewArrayStructure() throws Exception {
-
```
Comment (romani) [inline src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalTypeCheckTest.java:333]: Restore changes unrelated to your issue

File: src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/illegaltype/InputIllegalTypeRecordsAndCompactCtors.java [hunk 18]
```diff
@@ -36,7 +36,7 @@ record MyTestRecord2(String string) implements Cloneable { // violation
         }
     }
 
-    record MyTestRecord3(String str, TreeSet treeSet) { // violation
+    record MyTestRecord3(String str, Set treeSet) { // OK
         void foo(HashMap<Integer, Integer> hashMap) { // violation
```
Comment (romani) [inline src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/illegaltype/InputIllegalTypeRecordsAndCompactCtors.java:40]: Restore this line, it should not be charged

**Review by romani — CHANGES_REQUESTED** [review]
Items:

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalTypeCheck.java (hunk 16 above)
Comment (Rahulkhinchi03) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalTypeCheck.java:537]: So I should delete this method here and update it in case?

Comment (Rahulkhinchi03) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalTypeCheck.java:537]: But in case we are using (DetailAST ast) so how can I use (DetailASR recordComponentDef) in CASE?

Comment (Rahulkhinchi03) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalTypeCheck.java:537]: @romani sir, Can we use this condition?
```
public void visitRecordComponentDef(DetailAST recordComponentDef) {
        if (recordComponentDef.getType() == TokenTypes.RECORD_COMPONENT_DEF) {
            checkClassName(recordComponentDef);
        }
```

Comment (romani) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalTypeCheck.java:537]:
```
case TokenTypes.RECORD_COMPONENT_DEF:
                checkClassName(ast);
```

Comment (Rahulkhinchi03) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalTypeCheck.java:537]: Thanks Sir!
Should I delete this method now?

**Comment by Rahulkhinchi03** [comment]
Github, rebase

File: src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/illegaltype/InputIllegalTypeRecordsAndCompactCtors.java (hunk 18 above)
Comment (Rahulkhinchi03) [reply src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/illegaltype/InputIllegalTypeRecordsAndCompactCtors.java]: Done!

File: src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalTypeCheckTest.java (hunk 17 above)
Comment (Rahulkhinchi03) [reply src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalTypeCheckTest.java]: Done!

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalTypeCheck.java (hunk 16 above)
Comment (Rahulkhinchi03) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalTypeCheck.java]: Done!

**Review by romani — APPROVED** [review]
Ok by me.
I extended list of reviewers, as PR was not clear .

**Comment by Rahulkhinchi03** [comment]
Github, rebase

File: src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/illegaltype/InputIllegalTypeRecordsWithMemberModifiersDefault.java [hunk 19]
```diff
@@ -0,0 +1,63 @@
...
+        private final String identifier; // ok
+
+        public IdentifiersPairEquivalent(UUID productId, String identifier) {
+            this.productId = productId;
+            this.identifier = identifier;
+        }
+    }
+
+    public record IdentifiersPair2(
+        HashSet x, // violation
```
Comment (nmancus1) [inline src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/illegaltype/InputIllegalTypeRecordsWithMemberModifiersDefault.java:45]: @romani what is the policy for violation messages in input files? Do we require violation messages on all, or only when conditions are more complex or check has multiple messages?

Comment (romani) [reply src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/illegaltype/InputIllegalTypeRecordsWithMemberModifiersDefault.java:45]: When message could be different from Check.
If Check has single message - no need to print it. But no harm to have it if scecific  case is confusing

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalTypeCheck.java (hunk 15 above)
Comment (nmancus1) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalTypeCheck.java]: Resolved

**Review by nmancus1 — APPROVED** [review]

File: src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/illegaltype/InputIllegalTypeRecordsWithMemberModifiersDefault.java (hunk 19 above)
Comment (Rahulkhinchi03) [reply src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/illegaltype/InputIllegalTypeRecordsWithMemberModifiersDefault.java:45]: @romani sir, I had one doubt.
You said first that we can only use `Set` in CTOR and not `HashSet` but then you said me to revert changes. wasn't that `// ok`

Comment (romani) [reply src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/illegaltype/InputIllegalTypeRecordsWithMemberModifiersDefault.java:45]: We can use any type at any place.
Check should detect illegally config type at required place and place violation on it.

In test we need all possible combinations.
So do not touch existing tests and just deal with existing.

**Comment by Rahulkhinchi03** [comment]
@pbludov please review my changes!

**Review by pbludov — APPROVED** [review]

**Comment by Rahulkhinchi03** [comment]
@strkkk kindly review my changes!

**Review by strkkk — APPROVED** [review]
