### PR TITLE
Issue #12345: fix NoWhitespaceAfterCheck false positive

### LINKED ISSUE #12345: False positive in NoWhiteSpaceAfter
hi,

starting with ~~8.45~~ 8.44, checkstyle generates a false positive for this code

```
public class Demo {

    Object o;

    void some() {
        Object oo = new Object[4];
        this.o = ((Object[]) oo)[1];
    }
}
```
This leads to message like "There is a whitespace after 'o'"

```
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
        "-//Checkstyle//DTD Checkstyle Configuration 1.3//EN"
        "https://checkstyle.org/dtds/configuration_1_3.dtd">
<module name="Checker">
  <module name="TreeWalker">
    <module name="NoWhitespaceAfter">
    </module>
  </module>
</module>
```
produces this output using commandline / latest release 10.3.4
```
Starting audit...
[ERROR] ...\Demo.java:7:33: 'o' is followed by whitespace. [NoWhitespaceAfter]
Audit done.
Checkstyle ends with 1 errors.
```

### PR DESCRIPTION
**Pull request by strkkk**
Closes #12345

Diff Regression config: https://gist.githubusercontent.com/strkkk/26466254f89c32d8f1a6bd53b6f5b251/raw/e31682f867c2d357b605523c1a80cee50fab9c18/config_single.xml

### CODE REVIEW

**Comment by strkkk** [comment]
Github, generate report

**Review by romani — CHANGES_REQUESTED** [review]
Please add this case to Inputs
https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/e708e25_2022143653/reports/diff/openjdk17/index.html#A43
https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/e708e25_2022143653/reports/diff/openjdk17/index.html#A21

Please address Checker failures.

**Comment by strkkk** [comment]
> Please add this case to Inputs https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/e708e25_2022143653/reports/diff/openjdk17/index.html#A43 https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/e708e25_2022143653/reports/diff/openjdk17/index.html#A21
> 
> Please address Checker failures.

done

**Comment by strkkk** [comment]
CI failures seem unrelated and jist some infra issues

**Comment by rnveach** [comment]
@strkkk 
> CI failures seem unrelated 

Rebase for new travis fixes.

**Comment by strkkk** [comment]
Github, rebase

**Comment by strkkk** [comment]
it looks like rebase action is broken
```
Collecting information about PR #12372 of checkstyle/checkstyle...
Base branch for PR #12372 is master
fatal: detected dubious ownership in repository at '/github/workspace'
To add an exception for this directory, call:

	git config --global --add safe.directory /github/workspace
```

it looks like recent github feature with workspaces broke it

**Comment by strkkk** [comment]
error-prone check failed for some infra issue

**Comment by rnveach** [comment]
I set it to re-run but it has been queued for a bit now.

**Review by romani — APPROVED** [review]
Ok to merge , but we need to rebase to make sure CI is green, we changed it a lot recently

**Comment by strkkk** [comment]
rebased

**Comment by rnveach** [comment]
CI is missing like 43 runs.

File: src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/nowhitespaceafter/InputNoWhitespaceAfterTestDefault.java [hunk 1]
```diff
@@ -308,3 +308,30 @@ Object foo() {
     int someStuff8
     []; // violation
 }
+
+class QualifiedAssignment {
```
Comment (nrmancuso) [inline src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/nowhitespaceafter/InputNoWhitespaceAfterTestDefault.java:312]: Please create new test input so that we do not add to work required at https://github.com/checkstyle/checkstyle/issues/11163

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/NoWhitespaceAfterCheck.java [hunk 2]
```diff
@@ -569,11 +568,24 @@ private static DetailAST getIdentLastToken(DetailAST ast) {
...
      * @return dot preceding the left bracket
      */
-    private static DetailAST getPrecedingDot(DetailAST leftBracket) {
-        final DetailAST referencedClassDot =
-                leftBracket.getParent().findFirstToken(TokenTypes.DOT);
+    private static Optional<DetailAST> getPrecedingDot(DetailAST leftBracket) {
         final DetailAST referencedMemberDot = leftBracket.findFirstToken(TokenTypes.DOT);
-        return Optional.ofNullable(referencedMemberDot).orElse(referencedClassDot);
+        final Optional<DetailAST> result = Optional.ofNullable(referencedMemberDot);
+        return result.or(() -> getReferencedClassDot(leftBracket));
```
Comment (nrmancuso) [inline src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/NoWhitespaceAfterCheck.java:574]: Can we inline return value?

**Review by nrmancuso — CHANGES_REQUESTED** [review]
Items:

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/NoWhitespaceAfterCheck.java (hunk 2 above)
Comment (nrmancuso) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/NoWhitespaceAfterCheck.java:574]: Also, can we use `orElseGet` to avoid unnecessary method call?

File: src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/nowhitespaceafter/InputNoWhitespaceAfterTestDefault.java (hunk 1 above)
Comment (strkkk) [reply src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/nowhitespaceafter/InputNoWhitespaceAfterTestDefault.java]: done

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/NoWhitespaceAfterCheck.java (hunk 2 above)
Comment (strkkk) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/NoWhitespaceAfterCheck.java:574]: I am not sure it will look better.
Method returns Optional, so it really looks ugly when you try to combine it from 2 nullable variables. Therefore I decided it is better to make a separate method.

Comment (nrmancuso) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/NoWhitespaceAfterCheck.java:574]: Ok, that makes sense.

**Comment by nrmancuso** [comment]
From https://app.circleci.com/pipelines/github/checkstyle/checkstyle?branch=pull%2F12372:

CircleCI is not running on this branch due to sanctions.

@strkkk @rnveach @romani @pbludov FYI: 

>If you come across the above error, preventing your builds from running on CircleCI, your account may have recently been restricted as part of our compliance with U.S. export control laws and sanctions.

>Our recent actions to restrict certain user accounts were taken to comply with U.S. trade control laws imposed by the U.S. Treasury Department’s Office of Foreign Assets Controls (OFAC) and U.S. Commerce Department’s Bureau of Industry and Security (BIS), which restrict what CircleCI services can be made available to users in certain countries and territories.  These include:

>the Crimea, Donetsk Oblast, and Luhansk regions of Ukraine,
Belarus
Cuba
Iran
North Korea
Russia
Syria  

From https://support.circleci.com/hc/en-us/articles/360043679453-CircleCI-Terms-of-Service-Violation-Sanctioned-Country

**Review by nrmancuso — APPROVED** [review]

**Comment by nrmancuso** [comment]
Hm, interesting that CI started running in this PR after pushing up https://github.com/checkstyle/checkstyle/pull/12455

**Comment by strkkk** [comment]
@nrmancuso please either merge or assign next reviewer :)
