### PR TITLE
Issue #6558: make tests work reliably on Windows with LF line endings

### LINKED ISSUE #6558: Tests do not work properly on Windows with LF line endings
If Git is used without modifying line endings on checkout (e. g. `autocrlf=input`), you have
Linux line endings on Windows too.
The CS tests assume that on Windows the files have Windows line endings.

I personally hate it when a VCS mangles files automagically.
I have globally set `autocrlf` to `input` just to remind me to change line ending to LF if I have it at CRLF accidentally on some file, but I don't like to have Git automatically change line endings on checkout, besides that it wastes space on my local disk.

In #6511 @rnveach mentioned that the website of CS requires to use `autocrlf` with `true`.
With this the problem of course does not happen.
But I'd suggest to instead fix these incompatibilities in the tests and then maybe require instead not to have `autocrlf` at `false` for CS instead? For the result in the repository this would mean the same whether it is set to `true` or `input`, which is line endings in the repository are LF. And for most users this should be the case anyway.

With the changes I propose, the tests work properly on Windows, whether someone has linux line endings or windows line endings doesn't matter anymore. You could (should?) actually also add another build job that runs with `autocrlf` set to `input` or `false` on the Windows build machines to make sure it stays like that in the future.

Followup of #6511

### PR DESCRIPTION
**Pull request by Vampire**
Fixes #6558

### CODE REVIEW

**Comment by romani** [comment]
@Vampire , ply rebase to latest code

**Comment by Vampire** [comment]
Done

File: src/test/java/com/puppycrawl/tools/checkstyle/grammar/comments/AllBlockCommentsTest.java [hunk 1]
```diff
@@ -48,8 +51,16 @@ protected String getPackageLocation() {
...
         final DefaultConfiguration checkConfig =
                 createModuleConfig(BlockCommentListenerCheck.class);
+        final String path = getPath("InputFullOfBlockComments.java");
+        if (new FileText(new File(path), StandardCharsets.UTF_8.name())
+                .getFullText().chars().anyMatch(character -> character == '\r')) {
+            lineSeparator = "\r\n";
+        }
+        else {
+            lineSeparator = "\n";
+        }
```
Comment (romani) [inline src/test/java/com/puppycrawl/tools/checkstyle/grammar/comments/AllBlockCommentsTest.java]: sounds like util method to be reused.

File: src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalTokenCheckTest.java [hunk 2]
```diff
@@ -79,20 +83,29 @@ public void testCommentContentToken()
...
+            lineSeparator = "\r\n";
+        }
+        else {
+            lineSeparator = "\n";
+        }
         final String[] expected = {
             "3:3: " + getCheckMessage(MSG_KEY,
                         JavadocUtil.escapeAllControlChars(
-                            "*" + System.lineSeparator()
+                            "*" + lineSeparator
```
[the remark this answers is not in the document]
Comment (Vampire) [reply src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalTokenCheckTest.java]: Well, it for one still depends on whether you will set the attributes, so that LF is enforced on checkout or whether you set the attributes so that the user can still decide how he wants the files checked out, but they get normalized to LF on checkin automatically.
I thought we agreed on the latter but I might be mistaken.

Also I'm not sure about this exact location, there are also some tests where output from checkstyle is verified that is generated with the system default line separator and then needs to be normalized for the tests. I think this is not such a case, but like it is currently we still support having the files checked out with CRLF or LF and the tests just work.

File: src/test/java/com/puppycrawl/tools/checkstyle/api/FileTextTest.java [hunk 3]
```diff
@@ -101,7 +100,7 @@ public void testLineColumnAfterCopyConstructor() throws IOException {
         assertNull("LineBreaks not null", Whitebox.getInternalState(copy, "lineBreaks"));
         final LineColumn lineColumn = copy.lineColumn(100);
         assertEquals("Invalid line", 3, lineColumn.getLine());
-        if (System.getProperty("os.name").toLowerCase(Locale.ENGLISH).startsWith("windows")) {
+        if (fileText.getFullText().chars().anyMatch(character -> character == '\r')) {
```
[the remark this answers is not in the document]
Comment (Vampire) [reply src/test/java/com/puppycrawl/tools/checkstyle/api/FileTextTest.java]: That would then actually be `48 - 2 * lineSeparator.length()`.
Alternatively I now changed it to `if ("\r\n".equals(getLineSeparatorForFile(filepath, charset))) {`.
If you prefer the first variant, tell me and I'll change it.

File: src/test/java/com/puppycrawl/tools/checkstyle/AbstractPathTestSupport.java [hunk 4]
```diff
@@ -63,7 +61,7 @@ protected final String getResourcePath(String filename) {
     protected static String readFile(String filename) throws IOException {
         return new String(Files.readAllBytes(
                 Paths.get(filename)), StandardCharsets.UTF_8)
-                .replaceAll(CRLF_REGEX, LF_REGEX);
+                .replaceAll(CRLF_REGEX, "");
```
[the remark this answers is not in the document]
Comment (Vampire) [reply src/test/java/com/puppycrawl/tools/checkstyle/AbstractPathTestSupport.java]: Do you actually mean
```java
XxxxUtil.toLfLineEnd(new String(Files.readAllBytes(
	                Paths.get(filename)), StandardCharsets.UTF_8));
```
?
Would maybe the constant rename I suggested above already make it clear enough?

File: src/test/java/com/puppycrawl/tools/checkstyle/AbstractPathTestSupport.java [hunk 5]
```diff
@@ -27,9 +27,7 @@
 
 public abstract class AbstractPathTestSupport {
 
-    protected static final String LF_REGEX = "\\\\n";
-
-    protected static final String CRLF_REGEX = "\\\\r\\\\n";
+    protected static final String CRLF_REGEX = "\\\\r(?=\\\\n)|\\r(?=\\n)";
```
[the remark this answers is not in the document]
Comment (Vampire) [reply src/test/java/com/puppycrawl/tools/checkstyle/AbstractPathTestSupport.java]: This regex is used to normalize files that were generated with the platform default line separator (right side of the `|` replacing `\r\n` by `\n`) and parse tree dumps (left side of the `|` replacing `\\r\\n` by `\\n`, so the literal characters `\r\n` by `\n`).

Comment is added.
Maybe renaming `CRLF_REGEX` to `CR_FOLLOWED_BY_LF_REGEX` would make it more clear?

File: src/test/java/com/puppycrawl/tools/checkstyle/grammar/comments/AllBlockCommentsTest.java (hunk 1 above)
Comment (Vampire) [reply src/test/java/com/puppycrawl/tools/checkstyle/grammar/comments/AllBlockCommentsTest.java]: Indeed, refactored and replaced all four occurrences.

**Comment by Vampire** [comment]
> please remove from appveyor.yml definition of special git checkout of sources.
> It will prove that it works.

I'm not familiar with AppVeyor, you mean the two lines containing `core.autocrlf` I guess?
I removed those.
Is each build be done in a fresh VM like a docker image so that the setting did not persist from a former build?

> Please remove such request from http://checkstyle.sourceforge.net/beginning_development.html#Before_development

Done

**Comment by Vampire** [comment]
Seems the TeamCity configuration is broken maybe with a version update or something.

**Comment by romani** [comment]
TC is relaunched. Codecov  could be ignored, main coverage validation is in Travis

File: src/test/java/com/puppycrawl/tools/checkstyle/AbstractPathTestSupport.java (hunk 4 above)
[the remark this answers is not in the document]
Comment (romani) [reply src/test/java/com/puppycrawl/tools/checkstyle/AbstractPathTestSupport.java]: > Do you actually mean

yes

> Would maybe the constant rename I suggested above already make it clear enough?

My subjective opinion. It will not be clear.
```
(new String(Files.readAllBytes(
	                Paths.get(filename)), StandardCharsets.UTF_8)
	                .replaceAll(CR_FOLLOWED_BY_LF_REGEX, ""))
```
vs 
```
XxxxUtil.toLfLineEnd(new String(Files.readAllBytes(
	                Paths.get(filename)), StandardCharsets.UTF_8));
```

@rnveach and @pbludov , please vote.

File: src/test/java/com/puppycrawl/tools/checkstyle/AbstractPathTestSupport.java (hunk 5 above)
[the remark this answers is not in the document]
Comment (romani) [reply src/test/java/com/puppycrawl/tools/checkstyle/AbstractPathTestSupport.java]: please change 
`and \\r\\n to \\n` to 
`and \\r\\n to \\n (for parse tree dump files)`

File: src/test/java/com/puppycrawl/tools/checkstyle/AbstractPathTestSupport.java [hunk 6]
```diff
@@ -51,6 +54,19 @@ protected final String getPath(String filename) throws IOException {
                 .getCanonicalPath();
     }
 
+    protected static String getLineSeparatorForFile(String filepath, Charset charset)
```
Comment (romani) [inline src/test/java/com/puppycrawl/tools/checkstyle/AbstractPathTestSupport.java]: The older I become the more I dislike `protected`.
 
move it to Utils - https://github.com/checkstyle/checkstyle/blob/master/src/test/java/com/puppycrawl/tools/checkstyle/internal/utils/CheckUtil.java to make such context-less method/function to be accessible to others if required.

File: src/test/java/com/puppycrawl/tools/checkstyle/api/FileTextTest.java (hunk 3 above)
[the remark this answers is not in the document]
Comment (romani) [reply src/test/java/com/puppycrawl/tools/checkstyle/api/FileTextTest.java]: looks good.

File: appveyor.yml [hunk 7]
```diff
@@ -48,7 +46,6 @@ install:
       }
   - cmd: SET M2_HOME=C:\maven\apache-maven-3.2.5
   - cmd: SET PATH=%M2_HOME%\bin;%JAVA_HOME%\bin;%PATH%
-  - cmd: git config --global core.autocrlf
```
Comment (romani) [inline appveyor.yml]: lets restore this line, it just print value of config, to be sure in what mode code is checkouted.
We do not need "--global" as we chekouted repo config to be printed, irrespective of what is global in appveyor.

File: src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalTokenCheckTest.java (hunk 2 above)
[the remark this answers is not in the document]
Comment (romani) [reply src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalTokenCheckTest.java]: > so that LF is enforced on checkout 

yes, we need to enforce this by ".gitattributes" file. So user should not bother about any action on clone. Git will do all for user, sources will be "\n", build will work fine out of the box.
If user do extra override in configuration ... he do know what he is doing, it mean he is advanced  user, he will resolve all problems. 

> I thought we agreed on the latter but I might be mistaken.

no, at least as for me.
All other looks like took neutral position. 

> but like it is currently we still support having the files checked out with CRLF or LF and the tests just work.

As windows text editors / IDEs do not have problems with linux line ending. I would rather enforce single lineend - "\n" for all files except for "*.bat,*.ps"(first one is almost in repo - #6750).  
So code state will be more predictable on all OSs.
Checkstyle is already over-ruled with thousands of CI rule/checks/validations .... so contributor is already accustomed that code need to be consistent/exact/pristine even is very-very-very tiny aspect of it.

**Comment by romani** [comment]
fyi, interesting activity to remove win line-ends from checkstyle maven plugin code - https://github.com/apache/maven-checkstyle-plugin/pull/16

**Comment by romani** [comment]
jenkins is hanging ... should be ignored.

PR is reassigned to @pbludov  and @rnveach  to attract their attention and reply.

**Comment by rnveach** [comment]
@romani What about the addition to `.gitattributes` discussed at https://github.com/checkstyle/checkstyle/issues/6558#issuecomment-489362683 .
I would like to see this addition and that it will solve @Vampire 's problems so I can review it so my concerns can be checked.
Without this change, I believe allowing LF endings won't matter as Windows will still require `autocrlf` to work with.

File: src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalTokenCheckTest.java (hunk 2 above)
[the remark this answers is not in the document]
Comment (Vampire) [reply src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalTokenCheckTest.java]: > > so that LF is enforced on checkout
> 
> yes, we need to enforce this by ".gitattributes" file. So user should not bother about any action on clone. Git will do all for user, sources will be "\n", build will work fine out of the box.
> If user do extra override in configuration ... he do know what he is doing, it mean he is advanced user, he will resolve all problems.

Well, there wouldn't be any problem if the test just support it.
And he cannot resolve it in that case short of changing the test that could already support it without a problem.
And also that he has such a setting doesn't mean that he is andvanced, just that he can follow probably stupid advices from StackOverflow or similar.
But if you really want it that way, you need to do the `.gitattributes` change first I think.

> > I thought we agreed on the latter but I might be mistaken.
> 
> no, at least as for me.
> All other looks like took neutral position.

Ah, sorry, remembered wrongly.
Actually we didn't agree yet.
You asked whether I agree and I asked whether I can say "no", but we didn't continue on that part.
Imho it should still be sufficient to force the normalization on commit and let the user decide what lineending he wants to have locally.

> As windows text editors / IDEs do not have problems with linux line ending. I would rather enforce single lineend - "\n" for all files except for "_.bat,_.ps"(first one is almost in repo - #6750).

I'd rather say "many", not the implied "all".
But yeah, if you really want it like that, fine.

> Checkstyle is already over-ruled with thousands of CI rule/checks/validations .... so contributor is already accustomed that code need to be consistent/exact/pristine even is very-very-very tiny aspect of it.

contributors, yes
But this does not only hit contributors but also users that just want to build the sources. :-)

**Comment by romani** [comment]
@Vampire , this PR is very controversial.
But looks like maintainers do not share with you position on that user/contributor should have option to choose lineends he like and expect projects do all builds/CI-steps on his local.

What I see as approached to proceed:
1) We accept your code that allow execution of tests on windows lineends. BUT you provide also fix (in the same PR) for enforcing lineends to LF (gitattributes file, doc, ci update).
2) we close this PR, and wait for somebody to fix this issue by enforcing lineends to LF (gitattributes file, doc, ci update)

@Vampire , what if your choice ?

File: src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalTokenCheckTest.java (hunk 2 above)
[the remark this answers is not in the document]
Comment (romani) [reply src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalTokenCheckTest.java]: > But if you really want it that way, you need to do the .gitattributes change first I think.

if we make it first, we will not accept your update for tests. 

> I can say "no", but we didn't continue on that part.

please look https://github.com/checkstyle/checkstyle/pull/6559#issuecomment-502420662 

> but also users that just want to build the sources. :-)

if they are interesting in build, they can skip tests.

**Comment by romani** [comment]
@Vampire , please reply.
If no actions(code changes) till end of July, we will close PR.

**Comment by romani** [comment]
one more vote in favor of sources build-able on any OS(with line ends) - https://github.com/apache/maven-checkstyle-plugin/commit/a7f6a5df28b85c0778bbda306a685e7c57891481#commitcomment-34469685

it sounds like legacy rule, BUT we also release unintentionally sources as zip also - https://github.com/checkstyle/checkstyle/releases/tag/checkstyle-8.23 (automatically done by github).
BUT in such ZIP file, we have linux lines-ends:
```
file checkstyle-checkstyle-8.23/src/main/java/com/puppycrawl/tools/checkstyle/filters/SuppressFilterElement.java
checkstyle-checkstyle-8.23/src/main/java/com/puppycrawl/tools/checkstyle/filters/SuppressFilterElement.java: ASCII text
```

@Vampire ,  please continue this PR. If you lost interest, please let us also know.

**Comment by Vampire** [comment]
Hey, as I said in some ticket (iirc), I was on a longer vacation throughout July, so I didn't have a chance to do anything. I'm back now and trying to catch up.

> 1. We accept your code that allow execution of tests on windows lineends. BUT you provide also fix (in the same PR) for enforcing lineends to LF (gitattributes file, doc, ci update).
> 2. we close this PR, and wait for somebody to fix this issue by enforcing lineends to LF (gitattributes file, doc, ci update)

Why do those actions have to be done together?
They are totally separate tasks.
One makes the build working properly with windows lineends, the other enforces linux lineends.
In other PRs you always insistet on narrow scope for the changes.

If you want it, I can of course add the gitattributes entry if you tell me how you want it to be set and the change in the docs to not recommend / require the one setting anymore.
But I still think this is a separate task that should be done independently. :-)

**Comment by romani** [comment]
Thanks a coming back.

Sure, let's make git attributes first and then update for any line ends in second PR.

With contributors from outside team, I have no guarantee that after merge you he continue, and live proved this to me many many times, so we demand all to be done at one PR.

>In other PRs you always insistet on narrow scope for the changes.

Yes, when I sure that if I loose contributor after merge, I can release and somebody else can continue.

**Comment by romani** [comment]
>if you tell me how you want it to be set and the change in the docs to not recommend / require the one setting anymore.

By any reasonable means, just to avoid `autocrlf` setup before clone, you already did this in your PR. So let's move such change to separate PR, make it work on CI and @rnveach side, and after merge your change (this PR) that will allow to clone in any mode ( your approach).

**Comment by Vampire** [comment]
> With contributors from outside team, I have no guarantee that after merge you he continue, and live proved this to me many many times, so we demand all to be done at one PR.
> Yes, when I sure that if I loose contributor after merge, I can release and somebody else can continue.

Ah, well, I forgot I have the change in documentation and CI inside this PR.
I didn't have it in originally and only added it on your request.
Without these changes this PR was self-contained and adhere to those rules. :-)

> By any reasonable means, just to avoid autocrlf setup before clone, you already did this in your PR. So let's move such change to separate PR, make it work on CI and @rnveach side, and after merge your change (this PR) that will allow to clone in any mode ( your approach).

Sooo, what lines do you want me to add to `.gitattributes`?

**Comment by romani** [comment]
> Sooo, what lines do you want me to add to .gitattributes?

Lets start with 
```
# All files are default to LF
* text eol=lf

# Windows files always have CRLF line endings on checkout.
*.bat text eol=crlf
*.psh text eol=crlf
```
if build failed for some Input files for CRLF expected, lets add full path to such file in this config.

**Comment by Vampire** [comment]
That is not a good idea.
While `text` is not necessary, as `eol` sets it implicitly already, this will conditionless enable eol-normalization on all files and mark all files as text files.
Including any binary files like PNGs that are most likely destroyed by this action.

As a little recap:
- `text=auto` lets Git guess whether a file is text or not and if it thinks it is text, converts line endings to LF on checkin in the repository, but it does not control worktree line endings, those are controlled by the `core.eol` config variable on client side
- `eol=lf` implicitly also sets `text` which will mark the file as text file conditionless and do the conversion
- to my knowledge, there is no way to say "guess whether this file is text and if it is text, have LF in the worktree"

So there are multiple options which all have their drawbacks:

- `* eol=lf` and then list all binary files / extensions with `-text` or `binary` (which also includes `-diff` and `-merge`)
  but if you forget to list some binary type, it eventually gets unrecoverably destroyed by checkin normalization
- `* text=auto` and let the user decide how he wants his worktree line endings
- `* text=auto` to capture not listed text files and list all text files / extensions like `*.java eol=lf`, `*.bat eol=crlf`
- List all files / file types in the repository explicitly, not having anything for `*` and mark them as `eol=lf` or `-text` and have some test or check that ensures all file types are listed so that a new file type must be added to `.gitattributes`
- Any other idea?

**Comment by romani** [comment]
> but if you forget to list some binary type, it eventually gets unrecoverably destroyed by checkin normalization

We have CI to not forget, if any new binary file appear (for site purposes), it will be verified manually, it might be a problem after side deploy (if even happened, we will resolve this), but it will not be a problem for contributors.
I am in favor of `* eol=lf` approach.

==

all extensions:
```
~/java/github/romani/checkstyle [master|✔] 
14:12 $ find . -type f -a -not -name '\.*' ! -path '*.git*' | sed 's/^.*\.//' | grep -v "/" | sort | uniq
antlr
apache20
bat
css
dtd
g
g4
gif
header
html
ico
java
javadoc
jpeg
jpg
js
md
pl
png
prefs
properties
sh
sql
translation
translations
txt
vm
words
xml
xsd
yml
```

**Comment by Vampire** [comment]
> We have CI to not forget

How will CI know?
Except for my last proposal where every file type needs to be listed explicitly and CI can check that.
Otherwise CI will not know which files are binary and which are not to check whether the binary files are listed.

> if any new binary file appear (for site purposes), it will be verified manually

I't is not my intention to offend or accuse anyone with the next statement and I include myself with its meaning: Manually translated means it **will** be forgotten sooner or later.

> it might be a problem after side deploy (if even happened, we will resolve this),

I don't know what "side deploy" means, but whatever it means, if the eol normalization crippled the file on checkin, it is unrecoverably destroyed. It cannot be resolved, except the one that checked in the file still has the original file somewhere before it was destroyed by Git (one of the reasons I usually don't like any VCS changing my files)

> but it will not be a problem for contributors.

Besides "Why not?", it can become a problem for anyone who adds some binary file.

> I am in favor of * eol=lf approach.

Whatever you like, I just want to make sure that you understand the risk and the near 100% probability that with that you *will* have problems with destroyed files sooner or later, especially as the change will be recorded as done by me in Git, so I want to be able to say that I did all I could to prevent this. :-D

**Comment by romani** [comment]
as we agreed before ... lets split this into two PRs
1) update in .gitattributes + windows CI + doc . Should be merged first.
2) update in tests to work even contributros would like to have its own decision on lineends. Rebased on "1)" and also passed CI and review.

**Comment by Vampire** [comment]
We cannot split it in two PRs.
If I change the windows CI and gitattributes, the build will fail without my changes,
as then you have LF on Windows which is exactly what the rest of this PR fixes.
(Also https://github.com/checkstyle/checkstyle/issues/6558#issuecomment-491814506)

**Comment by Vampire** [comment]
What is werckers problem?

**Comment by romani** [comment]
>We cannot split it in two PRs (that pass CI).

Not good, I thought it was possible, the only reason I agreed.
do you know what will be a problem?

**Comment by Vampire** [comment]
> Not good, I thought it was possible, the only reason I agreed.

The only reason you agreed to what?
You said I should just add the gitattributes to the PR to finally get it approved hopefully.
I brought up the topic to split it in two, as I was too long out of the topic.

> do you know what will be a problem?

All the things in my PR?
I have locally LF on Windows.
All that I did in this PR (originally) was to make this properly work.
So with the additional gitattributes changes, the Windows CI should have the same problems I had, so you could accept my original PR first and as second step the gitattributes and doc changes, or you can accept them together. But first only changing line endings will not work, as for that you need exactly my other changes in this PR.

**Comment by Vampire** [comment]
Failing CI is a download problem of Groovy from Maven Central, not problems of my changes

**Comment by romani** [comment]
this PR was doomed to be problematic ...
I do not have Windows to experience and verify problem and I reviewing this PR.

@rnveach , we need you here.

----

If we force all files to be LF in repo, and we will remove from test code all like `System.getProperty("line.separator")`, expected tree files will be also have LF.
 Some occasional test my use CRLF, and same in expected file, but this will well known files, so we can hard code lineend.
Can we work like this ? or I miss smth ?

**Comment by romani** [comment]
ok, looks like, i got it, we have `System.getProperty("line.separator")` in our main code, so main code is generating not stable output

File: src/test/java/com/puppycrawl/tools/checkstyle/AbstractPathTestSupport.java (hunk 4 above)
[the remark this answers is not in the document]
Comment (romani) [reply src/test/java/com/puppycrawl/tools/checkstyle/AbstractPathTestSupport.java]: @Vampire , looks like in this PR, only you and me.
Please update code to use util method, I already forgot a trick of your regexp.

File: src/test/java/com/puppycrawl/tools/checkstyle/internal/utils/CheckUtil.java [hunk 8]
```diff
@@ -349,4 +351,16 @@ public static String getJavadocTokenText(int[] tokens, int... subtractions) {
         return result.toString();
     }
 
+    public static String getLineSeparatorForFile(String filepath, Charset charset)
+            throws IOException {
+        final String result;
+        if (new FileText(new File(filepath), charset.name())
+                .getFullText().chars().anyMatch(character -> character == '\r')) {
+            result = "\r\n";
```
Comment (romani) [inline src/test/java/com/puppycrawl/tools/checkstyle/internal/utils/CheckUtil.java]: please move this to constant of this Util class, and reuse it FileTextTest.java

File: src/test/java/com/puppycrawl/tools/checkstyle/AbstractPathTestSupport.java (hunk 4 above)
[the remark this answers is not in the document]
Comment (Vampire) [reply src/test/java/com/puppycrawl/tools/checkstyle/AbstractPathTestSupport.java]: There is no big trick, really.
The regexp is simply a `\r` followed by a `\n` or a `\\r` followed by a `\\n`.
The `\n` and `\\n` are matched by positive lookahead, so are not part of the match, so if you replace, you only replace the `\r` or `\\r`.
But yeah, I'll add such a utility method.

File: src/test/java/com/puppycrawl/tools/checkstyle/internal/utils/CheckUtil.java [hunk 9]
```diff
@@ -349,4 +351,16 @@ public static String getJavadocTokenText(int[] tokens, int... subtractions) {
         return result.toString();
     }
 
+    public static String getLineSeparatorForFile(String filepath, Charset charset)
+            throws IOException {
+        final String result;
+        if (new FileText(new File(filepath), charset.name())
+                .getFullText().chars().anyMatch(character -> character == '\r')) {
```
Comment (romani) [inline src/test/java/com/puppycrawl/tools/checkstyle/internal/utils/CheckUtil.java]: do we need to read whole file text ?
can we read only first line https://stackoverflow.com/questions/24666805/java-only-read-first-line-of-a-file/46239829 ? or smth similar to https://stackoverflow.com/a/45168182/1015848 ?

File: src/test/java/com/puppycrawl/tools/checkstyle/AbstractPathTestSupport.java (hunk 4 above)
[the remark this answers is not in the document]
Comment (Vampire) [reply src/test/java/com/puppycrawl/tools/checkstyle/AbstractPathTestSupport.java]: done

**Comment by Vampire** [comment]
> this PR was doomed to be problematic ...

Like every code change in any project. :-D

> I do not have Windows to experience and verify problem and I reviewing this PR.

Well, I think you don't need Windows.
You can probably just set `line.separator` to `\r\n` with the files being checked out with lf lineends and you probably have the same problems I think.

> ATTENTION: As update in `.gitattributes` is not related to such update, and requested only to prevent CRLF lineneds in files from windows contributors, lets move update of such file in separate commit (of the same PR, it could reference same issue), to let future engineer revert it easily if start to cause more problems. Probably in future we will have a special Check for lineends verification so it will be validated on different level.

Only the `.gitattributes` change or also the appveyor config and documentation?

File: src/test/java/com/puppycrawl/tools/checkstyle/internal/utils/CheckUtil.java (hunk 9 above)
Comment (Vampire) [reply src/test/java/com/puppycrawl/tools/checkstyle/internal/utils/CheckUtil.java]: Those approaches can of course not be used.
They read the first line until the line separator but do not include the line separator.
But I can of course easily stop at an `\n`.
The method is heuristic anyway.
Like I have it now, if you have 1000 LF in a file and one CRLF, it will be recognized as CRLF.
When I stop at the first LF, then it only works properly if the first line separator is CRLF, but that might be ok for the use-case.

**Comment by romani** [comment]
> Only the .gitattributes change 

only `.gitattributes`  
this update is not required for the rest change, and it was proposed as lack of CI tools (Check, bash script in CI) to verify it.
Am I right ?

File: src/test/java/com/puppycrawl/tools/checkstyle/internal/utils/CheckUtil.java (hunk 8 above)
Comment (Vampire) [reply src/test/java/com/puppycrawl/tools/checkstyle/internal/utils/CheckUtil.java]: What exactly do you mean? The `"\r\n"`?

File: src/test/java/com/puppycrawl/tools/checkstyle/internal/utils/CheckUtil.java (hunk 9 above)
Comment (Vampire) [reply src/test/java/com/puppycrawl/tools/checkstyle/internal/utils/CheckUtil.java]: changed to that

File: src/test/java/com/puppycrawl/tools/checkstyle/internal/utils/CheckUtil.java (hunk 8 above)
Comment (Vampire) [reply src/test/java/com/puppycrawl/tools/checkstyle/internal/utils/CheckUtil.java]: If yes, done

**Comment by Vampire** [comment]
> only `.gitattributes`
> this update is not required for the rest change, and it was proposed as lack of CI tools (Check, bash script in CI) to verify it.
> Am I right ?

Neither are the documentation and the appveyor config change.
They were as the gitattributes change only added upon your request.
Even without thouse changes you can have LF on Windows (if you just cloned without reading contributor documentation).
And that is what the rest of the changes makes work, that all works properly if you have LF files checked out on Windows.

File: src/test/java/com/puppycrawl/tools/checkstyle/internal/utils/CheckUtil.java (hunk 8 above)
Comment (romani) [reply src/test/java/com/puppycrawl/tools/checkstyle/internal/utils/CheckUtil.java]: yes

File: src/test/java/com/puppycrawl/tools/checkstyle/internal/utils/CheckUtil.java (hunk 9 above)
Comment (romani) [reply src/test/java/com/puppycrawl/tools/checkstyle/internal/utils/CheckUtil.java]: ok, it is test code, it can inefficient a bit.

Comment (Vampire) [reply src/test/java/com/puppycrawl/tools/checkstyle/internal/utils/CheckUtil.java]: Do you think it is still inefficient? o_O

**Comment by romani** [comment]
@rnveach , It would be awesome to finish this PR.

**Comment by rnveach** [comment]
@romani I tested this PR and I am satisfied with my concerns.
Git gave me a warning that it would convert my CRLFs to LFs.
````
N:\checkstyle>git add .
warning: CRLF will be replaced by LF in src/main/java/com/puppycrawl/tools/check
style/Example.java.
The file will have its original line endings in your working directory
````
I examined the commit, deleted the file and did a reset and couldn't give CRLFs to stay.
I did the same thing with an existing file and saw the same result.

One thing I wanted to note is that unless you delete the file and do a reset, git command line left the file as is with CRLFs. That could cause issues like the changes made in this PR.

File: .gitattributes [hunk 10]
```diff
@@ -1,7 +1,16 @@
...
+*.ico binary
+*.jpeg binary
+*.jpg binary
+*.png binary
+
+# Test resources that need specific eol
 /src/test/resources/com/puppycrawl/tools/checkstyle/checks/newlineatendoffile/InputNewlineAtEndOfFileCrlf.java eol=crlf
 /src/test/resources/com/puppycrawl/tools/checkstyle/checks/newlineatendoffile/InputNewlineAtEndOfFileCr.java -text
-/src/test/resources/com/puppycrawl/tools/checkstyle/checks/newlineatendoffile/InputNewlineAtEndOfFileNewlineAtEndLf.txt eol=lf
-/src/test/resources/com/puppycrawl/tools/checkstyle/grammar/InputNewlineCrAtEndOfFile.java -text
```
Comment (rnveach) [inline .gitattributes]: Why is this one removed but the one 2 lines above stays?

File: src/test/java/com/puppycrawl/tools/checkstyle/AbstractPathTestSupport.java [hunk 11]
```diff
@@ -27,9 +27,15 @@
...
 
-    protected static final String LF_REGEX = "\\\\n";
-
-    protected static final String CRLF_REGEX = "\\\\r\\\\n";
+    // we are using positive lookahead here, to convert \r\n to \n
+    // and \\r\\n to \\n (for parse tree dump files),
+    // by replacing the full match with the empty string
+    private static final String CR_FOLLOWED_BY_LF_REGEX = "(?x)"
+            + "\\\\r     # BACKSLASH_R \n"
+            + "(?=\\\\n) # followed by BACKSLASH_N (not part of the match) \n"
```
Comment (rnveach) [inline src/test/java/com/puppycrawl/tools/checkstyle/AbstractPathTestSupport.java]: I assume `#` are comments. Why are they embedded in the string and not a true java comment?

File: src/test/java/com/puppycrawl/tools/checkstyle/AbstractPathTestSupport.java [hunk 12]
```diff
@@ -69,9 +75,11 @@ protected final String getResourcePath(String filename) {
...
      */
     protected static String readFile(String filename) throws IOException {
-        return new String(Files.readAllBytes(
-                Paths.get(filename)), StandardCharsets.UTF_8)
-                .replaceAll(CRLF_REGEX, LF_REGEX);
+        return toLfLineEnd(new String(Files.readAllBytes(
+                Paths.get(filename)), StandardCharsets.UTF_8));
     }
 
+    protected static String toLfLineEnd(String text) {
```
Comment (rnveach) [inline src/test/java/com/puppycrawl/tools/checkstyle/AbstractPathTestSupport.java]: `toLfLineEnd` => `toLfLineEnding`

File: src/test/java/com/puppycrawl/tools/checkstyle/internal/AllChecksTest.java [hunk 13]
```diff
@@ -253,14 +254,18 @@ public void testAllModulesWithDefaultConfiguration() throws Exception {
...
                 // ImportControlCheck must have the import control configuration file to avoid
                 // violation.
                 moduleConfig.addAttribute("file", getPath(
                         "InputAllChecksImportControl.xml"));
             }
-            checker = createChecker(moduleConfig);
+            else if (module.equals(NewlineAtEndOfFileCheck.class)) {
+                // Line separator must be newline to not fail test
+                // for example on windows with LF line endings.
+                moduleConfig.addAttribute("lineSeparator", "lf");
```
Comment (rnveach) [inline src/test/java/com/puppycrawl/tools/checkstyle/internal/AllChecksTest.java]: Newline defaults to allow LF, CRLF, CR. I don't see why this is required now.

**Comment by rnveach** [comment]
> Conflict
> src/test/java/com/puppycrawl/tools/checkstyle/AbstractPathTestSupport.java

Rebased.

**Comment by romani** [comment]
all CIs passed, merged.
