### PR TITLE
Issue #8895: FinalLocalVariable: NPE in records

### LINKED ISSUE #8895: FinalLocalVariable: NPE in records
Check documentation: https://checkstyle.org/config_coding.html#FinalLocalVariable

problem was detected during https://github.com/checkstyle/contribution/commit/529fc836f88e0f88148ab7760a5ec7ba4d100715
`**/resources-noncompilable/**/checks/metrics/cyclomaticcomplexity/InputCyclomaticComplexityRecords.java` is name of file in our repo that cause problem.

```
$ cat MyRecord2.java 
//non-compiled with javac: Compilable with Java14

public record MyRecord2(boolean t, boolean f) {
    public MyRecord2 { // violation
        int a = 1;
        int b = 1;
        int c = 1;
        int d = 1;
        int n = 8;
        if (a == 1) { // 2, if
        } else if (a == b // 3, if
                && a == c) { // 4, && operator
            if (c == 2) { // 5, if
            }
        } else if (a == d) { // 6, if
            try {
            } catch (Exception e) { // 7, catch
            }
        } else {
            switch (n) {
                case 1: // 8, case
                    break;
                case 2: // 9, case
                    break;
                case 3: // 10, case
                    break;
                default:
                    break;
            }
        }
        d = a < 0 ? -1 : 1; // 11, ternary operator
    }
}

$ cat config.xml 
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
          "-//Puppy Crawl//DTD Check Configuration 1.3//EN"
          "http://www.puppycrawl.com/dtds/configuration_1_3.dtd">

<module name="Checker">
    <module name="TreeWalker">
       <module name="FinalLocalVariable"/>
    </module>
</module>

$ java -jar checkstyle-8.36.2-all.jar -c config.xml MyRecord2.java
Starting audit...
com.puppycrawl.tools.checkstyle.api.CheckstyleException: Exception was thrown while processing MyRecord2.java
	at com.puppycrawl.tools.checkstyle.Checker.processFiles(Checker.java:311)
	at com.puppycrawl.tools.checkstyle.Checker.process(Checker.java:221)
	at com.puppycrawl.tools.checkstyle.Main.runCheckstyle(Main.java:408)
	at com.puppycrawl.tools.checkstyle.Main.runCli(Main.java:331)
	at com.puppycrawl.tools.checkstyle.Main.execute(Main.java:190)
	at com.puppycrawl.tools.checkstyle.Main.main(Main.java:125)
Caused by: java.lang.NullPointerException
	at com.puppycrawl.tools.checkstyle.checks.coding.FinalLocalVariableCheck.findFirstUpperNamedBlock(FinalLocalVariableCheck.java:781)
	at com.puppycrawl.tools.checkstyle.checks.coding.FinalLocalVariableCheck.isSameVariables(FinalLocalVariableCheck.java:800)
	at com.puppycrawl.tools.checkstyle.checks.coding.FinalLocalVariableCheck.access$700(FinalLocalVariableCheck.java:142)
	at com.puppycrawl.tools.checkstyle.checks.coding.FinalLocalVariableCheck$ScopeData.findFinalVariableCandidateForAst(FinalLocalVariableCheck.java:863)
	at com.puppycrawl.tools.checkstyle.checks.coding.FinalLocalVariableCheck.getFinalCandidate(FinalLocalVariableCheck.java:444)
	at com.puppycrawl.tools.checkstyle.checks.coding.FinalLocalVariableCheck.visitToken(FinalLocalVariableCheck.java:304)
	at com.puppycrawl.tools.checkstyle.TreeWalker.notifyVisit(TreeWalker.java:340)
	at com.puppycrawl.tools.checkstyle.TreeWalker.processIter(TreeWalker.java:451)
	at com.puppycrawl.tools.checkstyle.TreeWalker.walk(TreeWalker.java:278)
	at com.puppycrawl.tools.checkstyle.TreeWalker.processFiltered(TreeWalker.java:151)
	at com.puppycrawl.tools.checkstyle.api.AbstractFileSetCheck.process(AbstractFileSetCheck.java:87)
	at com.puppycrawl.tools.checkstyle.Checker.processFile(Checker.java:337)
	at com.puppycrawl.tools.checkstyle.Checker.processFiles(Checker.java:298)
	... 5 more
Checkstyle ends with 1 errors
```

after fix we should remove this exclude from contribution repo.

### PR DESCRIPTION
**Pull request by anhminhtran235**
Fix #8895 

As described [here](https://github.com/checkstyle/checkstyle/issues/8895#issuecomment-711096332), adding `&& astTraverse.getType() != TokenTypes.COMPACT_CTOR_DEF` solves the problem.

Diff Regression config: https://gist.githubusercontent.com/anhminhtran235/c74908614e3465fade5de3c1d33fad5e/raw/ec75fe33dd75befe6b23185b9521c93cebb1c18b/check.xml
Diff Regression projects: https://gist.githubusercontent.com/romani/cbc85ed26b809064dc260a246666743a/raw/a515faeb85836d1bb9987855cadc23fd3b63abfc/gistfile1.txt

### CODE REVIEW

**Comment by anhminhtran235** [comment]
@romani A code coverage check gave an error. I read 'Details' but not sure what went wrong. I think my code decreases code coverage? How do I fix it?

**Comment by strkkk** [comment]
@anhminhtran235 nevermind codecov issue. Please add diff regression report to show that issue is resolved.

How to create regression report https://github.com/checkstyle/contribution/tree/master/checkstyle-tester#report-generation
Make sure that files from issue description is included

**Comment by anhminhtran235** [comment]
GitHub, generate report

**Comment by strkkk** [comment]
@anhminhtran235 links should point to "raw" version of the file, see examples in docs.

**Comment by anhminhtran235** [comment]
GitHub, generate report

**Comment by anhminhtran235** [comment]
@strkkk Fixed links. By the way, I'm not quite sure if my check.xml and projects-to-test-on.properties is set up correctly. Basically, I only add `<module name="FinalLocalVariable" />` to check.xml:
```
<module name="TreeWalker">
         <!-- Example of checkstyle Check usage -->
         <!-- PLEASE CHANGE IT TO CHECK YOU ARE TESTING !!!! -->
         <module name="FinalLocalVariable" />
```
The projects-to-test-on.properties is the same.

File: src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/finallocalvariable/InputFinalLocalVariableCheckRecords.java [hunk 1]
```diff
@@ -0,0 +1,12 @@
...
+
+/* Config:
+ * None
+ */
+public record InputFinalLocalVariableCheckRecords(boolean t, boolean f) {
+    public InputFinalLocalVariableCheckRecords { // ok
+        int a = 0;
+        a = 1;
+    }
+}
```
Comment (pbludov) [inline src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/finallocalvariable/InputFinalLocalVariableCheckRecords.java:12]: Please add a positive test case, something like inner record with
```java
    record bad(int i) {
        public bad {
            int a = 0; // violation
        }
    }
```

File: src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/finallocalvariable/InputFinalLocalVariableCheckRecords.java [hunk 2]
```diff
@@ -0,0 +1,12 @@
+//non-compiled with javac: Compilable with Java14
+package com.puppycrawl.tools.checkstyle.checks.coding.finallocalvariable;
+
+/* Config:
+ * None
```
Comment (pbludov) [inline src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/finallocalvariable/InputFinalLocalVariableCheckRecords.java:5]: None -> default

**Review by pbludov — CHANGES_REQUESTED** [review]

File: src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/finallocalvariable/InputFinalLocalVariableCheckRecords.java (hunk 1 above)
Comment (anhminhtran235) [reply src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/finallocalvariable/InputFinalLocalVariableCheckRecords.java:18]: fixed

File: src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/finallocalvariable/InputFinalLocalVariableCheckRecords.java (hunk 2 above)
Comment (anhminhtran235) [reply src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/finallocalvariable/InputFinalLocalVariableCheckRecords.java]: fixed

File: src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/finallocalvariable/InputFinalLocalVariableCheckRecords.java [hunk 3]
```diff
@@ -0,0 +1,19 @@
...
+ */
+public record InputFinalLocalVariableCheckRecords(boolean t, boolean f) {
+    public InputFinalLocalVariableCheckRecords {
+        int a = 0; // ok
+        a = 1;
+    }
+
+    record bad(int i) {
+        public bad {
+            int b = 0;
```
Comment (pbludov) [inline src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/finallocalvariable/InputFinalLocalVariableCheckRecords.java:15]: The test expects violation at  "15:17", please move `// violation` comment to line 15

**Review by pbludov — CHANGES_REQUESTED** [review]
One minor change please

File: src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/finallocalvariable/InputFinalLocalVariableCheckRecords.java (hunk 3 above)
Comment (anhminhtran235) [reply src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/finallocalvariable/InputFinalLocalVariableCheckRecords.java]: Fixed. You're right. I thought 17 is the line number. Thank you

**Review by pbludov — APPROVED** [review]

File: src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/finallocalvariable/InputFinalLocalVariableCheckRecords.java (hunk 3 above)
Comment (anhminhtran235) [reply src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/finallocalvariable/InputFinalLocalVariableCheckRecords.java]: I'm not sure what went wrong with [regression report](https://github.com/checkstyle/checkstyle/pull/8913#issuecomment-715557963). Do you have any suggestions?

**Comment by anhminhtran235** [comment]
@romani @strkkk I'm not sure how to set up `projects-to-test-on.properties` for [my regression report](https://github.com/checkstyle/checkstyle/pull/8913#issuecomment-715557963). Could you guys guide me?

**Comment by pbludov** [comment]
> @romani @strkkk I'm not sure how to set up `projects-to-test-on.properties` for [my regression report](https://github.com/checkstyle/checkstyle/pull/8913#issuecomment-715557963). Could you guys guide me?

Your config has some spaces before `<?xml version="1.0"?>`. This is not a valid XML file.

**Comment by anhminhtran235** [comment]
> Your config has some spaces before `<?xml version="1.0"?>`. This is not a valid XML file.

@pbludov Fixed. Other than that, is there anything else I need to fix?

**Comment by anhminhtran235** [comment]
GitHub, generate report

**Comment by anhminhtran235** [comment]
"`differences found: 0`". Does that mean I did something wrong?

**Comment by romani** [comment]
@anhminhtran235 , please uncomment more/all projects at https://gist.githubusercontent.com/anhminhtran235/ca175bbacbdf28dbd17ebc131e098407/raw/3f5b2582d6b15029161c2a9ca759678a4842fef5/projects-to-test-on.properties and regenerate report.

**Comment by anhminhtran235** [comment]
@romani Uncommented most projects

**Comment by anhminhtran235** [comment]
GitHub, generate report

**Comment by anhminhtran235** [comment]
GitHub, generate report

**Comment by anhminhtran235** [comment]
GitHub, generate report

**Comment by anhminhtran235** [comment]
GitHub, generate report

**Comment by anhminhtran235** [comment]
GitHub, generate report

**Comment by anhminhtran235** [comment]
GitHub, generate report

**Comment by romani** [comment]
@anhminhtran235 , no need to ask twice for report, you can see status at https://github.com/checkstyle/checkstyle/actions , and you can see a progress or make decision on what to do. You can ask us to review. If report takes a lot of time might need to reduce amount projects in config.

**Comment by anhminhtran235** [comment]
@romani Thanks for the link. It's very helpful. The reports took quite a long time. Is there any way I can stop a report from processing? Also, should I reduce the amount of reports and tell Github to generate another report now?

**Comment by anhminhtran235** [comment]
Reduced the number of projects

**Comment by anhminhtran235** [comment]
GitHub, generate report

**Comment by anhminhtran235** [comment]
@romani The regression report keeps failing. I have disabled most projects, but it still takes too long. Could you please disable unnecessary projects for me once so I know the correct way to do it in the future? Thank you.

**Comment by romani** [comment]
GitHub, generate report

**Comment by romani** [comment]
@anhminhtran235 , please send PR for https://github.com/checkstyle/contribution/issues/519

**Comment by romani** [comment]
GitHub, generate report

**Review by romani — APPROVED** [review]

**Comment by anhminhtran235** [comment]
@romani I have a question. What exactly diff regression report is for? And how do we look at the diff regression report and confirm that the bug has actually been fixed?

**Comment by romani** [comment]
Bug is fixed, you prove it by UT.
Diff report shows how validation is changing on vast range of sources. Such report usually shows unexpected side effects of code modification, that our Input test base does not have. You will see it in action next time.

**Comment by anhminhtran235** [comment]
I see. Thank you for your explanation.

**Review by strkkk — APPROVED** [review]

**Comment by strkkk** [comment]
Interesting that fix fixed some other NPEs in files without records. I guess it is because TokenUtil.isOfType has null check inside it.
