### PR TITLE
Issue #13086: fix InnerAssignmentCheck In SwitchRuleAndExpression

### LINKED ISSUE #13086: InnerAssignmentCheck failed for one line code in Java 14 switch expression
I have read check documentation: https://checkstyle.org/config_coding.html#InnerAssignment
I have downloaded the latest checkstyle from: https://checkstyle.org/cmdline.html#Download_and_Run
I have executed the cli and showed it below, as cli describes the problem better than 1,000 words

```bash
/var/tmp $ javac TestInnerAssignmentCheck.java

/var/tmp $ cat config.xml
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
        "-//Checkstyle//DTD Checkstyle Configuration 1.3//EN"
        "https://checkstyle.org/dtds/configuration_1_3.dtd">
<module name="Checker">
  <module name="TreeWalker">
    <module name="InnerAssignment"/>
  </module>
</module>

/var/tmp $ cat TestInnerAssignmentCheck.java
public class TestInnerAssignmentCheck {
    private boolean flag;

    void getOperation(final String operation) {
        switch (operation) {
            case "Y" -> flag = true;  // violation 
            case "N" -> {
                flag = false;
            }
            default -> throw new UnsupportedOperationException();
        }
    }
}

/var/tmp $ RUN_LOCALE="-Duser.language=en -Duser.country=US"
/var/tmp $ java $RUN_LOCALE -jar checkstyle-10.11.0-all.jar -c config.xml TestInnerAssignmentCheck.java
Starting audit...
[ERROR] /Users/hael/Code/Learn/Tools/checkstyle/TestInnerAssignmentCheck.java:6:30:
     Inner assignments should be avoided. [InnerAssignment]
Audit done.
Checkstyle ends with 1 errors.
```

---

**Describe what you expect in detail.**

Checkstyle behaves differently between one line code and code block for Java 14's Switch Expression. In the given code above, checkstyle will complain about `case "Y" -> flag = true;` but not `case "N" -> {flag = false;}`. I'm afraid that it's because `flag = true;` is equivalent to `return flag = true;`? But the return value is not used here in the switch expression, we just want to do the value assignment. 

Expected: no violations on such code.

### PR DESCRIPTION
**Pull request by mahfouz72**
Resolves #13086 :

Diff Regression config: https://gist.githubusercontent.com/mahfouz72/70e0fb4b76668949fd9e0fd3744deddd/raw/0b035184445fee1009e49543af7b1daa6b52f79f/innerass.xml

Diff Regression projects: https://gist.githubusercontent.com/mahfouz72/297d7353d2d0bcec178e1b098109cd9e/raw/546dcdbdff363110fa265ea80d70e36f079c6ee8/projects-to-test-on.properties

### CODE REVIEW

**Comment by mahfouz72** [comment]
Github, generate report

**Comment by mahfouz72** [comment]
Github, generate report

**Comment by mahfouz72** [comment]
report is good

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/InnerAssignmentCheck.java [hunk 1]
```diff
@@ -101,6 +101,7 @@ public class InnerAssignmentCheck
             TokenTypes.RESOURCE_SPECIFICATION,
         },
         {TokenTypes.EXPR, TokenTypes.LAMBDA},
+        {TokenTypes.EXPR, TokenTypes.SWITCH_RULE, TokenTypes.LITERAL_SWITCH, TokenTypes.SLIST},
```
Comment (romani) [inline src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/InnerAssignmentCheck.java:104]: Why we need TokenTypes.SLIST ? And TokenTypes.LITERAL_SWITCH

**Review by romani — CHANGES_REQUESTED** [review]
Question

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/InnerAssignmentCheck.java (hunk 1 above)
Comment (mahfouz72) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/InnerAssignmentCheck.java:104]: To make sure that we are in normal Switch context not Switch Expression. if it is  `{TokenTypes.EXPR, TokenTypes.SWITCH_RULE}` only then we will have no violation if the assignment is in switch expression
ex 
```java
    public void test2(int mode) {
        int x = 0;
        x = switch (mode) {
            case 2 -> {
                yield x = 2; 
            }
            case 1 -> x = 1;  // this will be ok
            default -> throw new UnsupportedOperationException();
        };
    }
``` 

Switch Expression AST:
```
        |--EXPR -> EXPR [8:10]
        |       |   `--ASSIGN -> = [8:10]   <<---
        |       |       |--IDENT -> x [8:8]
        |       |       `--LITERAL_SWITCH -> switch [8:12]   <<---
        |       |           |--LPAREN -> ( [8:19]
        |       |           |--EXPR -> EXPR [8:20]
        |       |           |   `--IDENT -> mode [8:20]
        |       |           |--RPAREN -> ) [8:24]
        |       |           |--LCURLY -> { [8:26]
        |       |           |--SWITCH_RULE -> SWITCH_RULE [9:12]   <<---
        |       |           |   |--LITERAL_CASE -> case [9:12]
        |       |           |   |   `--EXPR -> EXPR [9:17]
        |       |           |   |       `--NUM_INT -> 1 [9:17]
        |       |           |   |--LAMBDA -> -> [9:19]
        |       |           |   |--EXPR -> EXPR [9:24]         <<---
        |       |           |   |   `--ASSIGN -> = [9:24]
        |       |           |   |       |--IDENT -> x [9:22]
        |       |           |   |       `--NUM_INT -> 1 [9:26]
        |       |           |   `--SEMI -> ; [9:27]
        |       |           `--RCURLY -> } [10:8]
```
switch rule AST

```
        `--SLIST -> { [6:33]          <<---
        |       |--LITERAL_SWITCH -> switch [7:8]   <<---
        |       |   |--LPAREN -> ( [7:15]
        |       |   |--EXPR -> EXPR [7:16]
        |       |   |   `--IDENT -> mode [7:16]
        |       |   |--RPAREN -> ) [7:20]
        |       |   |--LCURLY -> { [7:22]
        |       |   |--SWITCH_RULE -> SWITCH_RULE [8:12]          <<---
        |       |   |   |--LITERAL_CASE -> case [8:12]
        |       |   |   |   `--EXPR -> EXPR [8:17]
        |       |   |   |       `--NUM_INT -> 1 [8:17]
        |       |   |   |--LAMBDA -> -> [8:19]
        |       |   |   |--EXPR -> EXPR [8:24]       <<---
        |       |   |   |   `--ASSIGN -> = [8:24]
        |       |   |   |       |--IDENT -> x [8:22]
        |       |   |   |       `--NUM_INT -> 1 [8:26]
        |       |   |   `--SEMI -> ; [8:27]
        |       |   `--RCURLY -> } [9:8]

```

File: src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/innerassignment/InputInnerAssignmentSwitchAndSwitchExpression.java [hunk 2]
```diff
@@ -0,0 +1,51 @@
...
+    }
+
+    public void test2(int mode) {
+        int x = 0;
+        x = switch (mode) {
+            case 2 -> {
+                yield x = 2; // violation
+            }
+            case 1 -> x = 1;  // violation
+            default -> throw new UnsupportedOperationException();
```
Comment (nrmancuso) [inline src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/innerassignment/InputInnerAssignmentSwitchAndSwitchExpression.java:28]: Please add inner assignment to default branch, and create another method with the same pattern, but with switch labeled statement groups. Also, add an example with multiple case constants in one or more labels.

**Review by nrmancuso — CHANGES_REQUESTED** [review]
Please review documentation to see if we need to update there as well.

Item:

**Comment by mahfouz72** [comment]
Github, generate site

File: src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/innerassignment/InputInnerAssignmentSwitchAndSwitchExpression.java (hunk 2 above)
Comment (mahfouz72) [reply src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/innerassignment/InputInnerAssignmentSwitchAndSwitchExpression.java]: done and updated documentation to add examples with switch

**Comment by nrmancuso** [comment]
@mahfouz72 please generate a regression report against openjdk21

**Review by nrmancuso — APPROVED** [review]

**Comment by mahfouz72** [comment]
Github, generate report

**Comment by mahfouz72** [comment]
Github, generate report

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/InnerAssignmentCheck.java (hunk 1 above)
Comment (mahfouz72) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/InnerAssignmentCheck.java:104]: @romani ping

**Review by romani — APPROVED** [review]
Ok to merge

File: src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/InnerAssignmentCheckTest.java [hunk 3]
```diff
@@ -99,6 +99,7 @@ public void testInnerAssignmentNotInLoopContext() throws Exception {
     public void testTokensNotNull() {
         final InnerAssignmentCheck check = new InnerAssignmentCheck();
         assertWithMessage("Acceptable tokens should not be null")
+
```
Comment (rnveach) [inline src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/InnerAssignmentCheckTest.java:102]: remove unnecessary change.

File: src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/innerassignment/InputInnerAssignmentSwitchAndSwitchExpression.java [hunk 4]
```diff
@@ -0,0 +1,85 @@
...
+            }
+            case 1, 3, 5 -> x = 1;
+        }
+    }
+
+    public void test3(int mode) {
+        int x = 0;
+        x = switch (mode) {
+            case 2 -> {
+                yield x = 2; // violation
```
Comment (rnveach) [inline src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/innerassignment/InputInnerAssignmentSwitchAndSwitchExpression.java:35]: So why does this create violations but something like test 2 doesn't? Is this because it is basically nested inside an assignment already?

Is there somewhere (official?) that shows what inner assignments are in this case?

What if we had a case like (also add it):
````
System.out.println(switch (mode) {
            case 2 -> {
                yield x = 2;
````

This wouldn't be an exception?

File: src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/innerassignment/InputInnerAssignmentSwitchAndSwitchExpression.java [hunk 5]
```diff
@@ -0,0 +1,85 @@
...
+            }
+            case 1 -> x = 1;
+        }
+    }
+
+    public void test2(int mode) {
+        int x = 0;
+        switch(mode) {
+            case 2, 4, 6 -> {
+                x = 2;
```
Comment (rnveach) [inline src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/innerassignment/InputInnerAssignmentSwitchAndSwitchExpression.java:25]: Create another test method like:
````
   public void test2(int mode) {
        int x = 0;
        switch(mode) {
            case 2, 4, 6 -> {
                x = y = 2;
````

I would expect a violation here.

File: src/xdocs-examples/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/innerassignment/Example2.java [hunk 6]
```diff
@@ -0,0 +1,47 @@
...
+<module name="Checker">
+  <module name="TreeWalker">
+    <module name="InnerAssignment"/>
+  </module>
+</module>
+*/
+
+package com.puppycrawl.tools.checkstyle.checks.coding.innerassignment;
+
+//non-compiled with javac: Compilable with Java14
```
Comment (rnveach) [inline src/xdocs-examples/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/innerassignment/Example2.java:11]: @romani @nrmancuso Do we check that these files are compilable with different java versions? I don't remember seeing this before with examples.
Shouldn't this also be before the package?

**Review by rnveach — CHANGES_REQUESTED** [review]
There is not really any descriptions update in this PR.
https://checkstyle.org/checks/coding/innerassignment.html#Description
> Except for the loop idioms, all assignments should occur in their own top-level statement to increase readability. 

Is this wording technically not correct anymore? I wouldn't really consider cases to be top level statements.

**Comment by rnveach** [comment]
> Diff Regression projects: https://gist.githubusercontent.com/mahfouz72/297d7353d2d0bcec178e1b098109cd9e/raw/546dcdbdff363110fa265ea80d70e36f079c6ee8/projects-to-test-on.properties

We normally provide regression on all projects. Even if no others have this form of code, it will show this doesn't impact older code.

File: src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/InnerAssignmentCheckTest.java (hunk 3 above)
Comment (mahfouz72) [reply src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/InnerAssignmentCheckTest.java]: done. it was by mistake

File: src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/innerassignment/InputInnerAssignmentSwitchAndSwitchExpression.java (hunk 4 above)
Comment (mahfouz72) [reply src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/innerassignment/InputInnerAssignmentSwitchAndSwitchExpression.java:38]: > So why does this create violations but something like test 2 doesn't

because this is an assignment inside expressions ( switch expressions ), while test2 is an assignment inside normal switch statements

> Is there somewhere (official?)

I didn't find any but what I know from our docs is that inner assignments are the assignments inside expressions. So basically the assignments inside switch expressions `x = switch(){....} `  should be avoided

> What if we had a case like (also add it):

Yes, violation and added

File: src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/innerassignment/InputInnerAssignmentSwitchAndSwitchExpression.java (hunk 5 above)
Comment (mahfouz72) [reply src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/innerassignment/InputInnerAssignmentSwitchAndSwitchExpression.java:25]: added in the same method

File: src/xdocs-examples/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/innerassignment/Example2.java (hunk 6 above)
Comment (mahfouz72) [reply src/xdocs-examples/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/innerassignment/Example2.java]: I put it before the package

**Comment by mahfouz72** [comment]
> We normally provide regression on all projects. Even if no others have this form of code, it will show this doesn't impact older code. Please update the file.

Yes this is only to generate another report I generated two

all projects:  https://github.com/checkstyle/checkstyle/pull/14804#issuecomment-2060099135
java 21: https://github.com/checkstyle/checkstyle/pull/14804#issuecomment-2066948221

**Comment by mahfouz72** [comment]
> Is this wording technically not correct anymore?

I don't see anything wrong. Can you please point to an example that you think violates this wording

`x = switch(..){ case 1 -> x = 3} `  (assignment is not in its own top level (nested inside another assignment)  so violation
`switch(..){ case 1 -> x = 3} `  ( I guess this is considered  as a top-level so no violation )

File: src/xdocs-examples/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/innerassignment/Example2.java (hunk 6 above)
Comment (nrmancuso) [reply src/xdocs-examples/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/innerassignment/Example2.java]: @rnveach We only compile with the specified version.

**Comment by nrmancuso** [comment]
> There is not really any descriptions update in this PR. https://checkstyle.org/checks/coding/innerassignment.html#Description
> 
> > Except for the loop idioms, all assignments should occur in their own top-level statement to increase readability.
> 
> Is this wording technically not correct anymore? I wouldn't really consider cases to be top level statements.

I think this still holds for switch expressions; the only assignment happening should be to a variable declared outside(top level) of the switch expression, from a value yielded by the switch expression.

File: src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/innerassignment/InputInnerAssignmentSwitchAndSwitchExpression.java (hunk 4 above)
Comment (nrmancuso) [reply src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/innerassignment/InputInnerAssignmentSwitchAndSwitchExpression.java:38]: >Is there somewhere (official?) that shows what inner assignments are in this case?

Doubt it. A better way to describe what this check does is "place violations (mostly) anywhere that assigned values are used directly". Ideally, we should only do one thing at a time; assign a value, or use it, not both.

Comment (rnveach) [reply src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/innerassignment/InputInnerAssignmentSwitchAndSwitchExpression.java:38]: > yield x = 2;

Just to confirm, since I am not use to this syntax, is this the same as `x = 2; yield x;`?
If we had `y = 2` before this line would that be a violation too?

@nrmancuso @romani Are we ok that test8 is a violation for this check?

**Comment by rnveach** [comment]
I think I need some clarification then on what is a "top level statement" is.

I tried google. The first thing said `Top-level statements allows you to write executable code directly at the root of a file, eliminating the need for wrapping your code in a class or method. `. However that seems to be a C# link. Then I got a reddit for Java help where someone replied to the poster to clarify this exact statement and it was never answered.

I always considered this check to mean something like "the statement must only contain the assignment itself", but then the whole switch is considered a single statement (unless I have the Java grammar wrong).

File: src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/innerassignment/InputInnerAssignmentSwitchAndSwitchExpression.java (hunk 4 above)
Comment (mahfouz72) [reply src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/innerassignment/InputInnerAssignmentSwitchAndSwitchExpression.java:38]: > Just to confirm, since I am not use to this syntax, is this the same as `x = 2; yield x;`?

Yes I think So

> If we had `y = 2` before this line would that be a violation too?

this will have no violation due to https://github.com/checkstyle/checkstyle/blob/405db25d46c4cb9ac561f91e04c59aebac50baf6/src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/InnerAssignmentCheck.java#L94

Comment (nrmancuso) [reply src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/innerassignment/InputInnerAssignmentSwitchAndSwitchExpression.java:38]: Yes, assigned values are used directly in all three cases.

**Comment by romani** [comment]
>but then the whole switch is considered a single statement (unless I have the Java grammar wrong).

It is probably very confusing to consider switch expressions as statement. It better to think of this like inlined function in such cases.

Detect that we have is that we report violation on switch that statement like.

**Comment by rnveach** [comment]
I am not calling into question what we print out as violations. My whole comments was the documentation and is it clear enough on what we say this check does.

**Comment by romani** [comment]
https://checkstyle.org/checks/coding/innerassignment.html#Description

I don't know how to improve our doc, we have have not very strict target of vali
