### PR TITLE
Issue #11268: Fix false negative in RedundantModifierCheck

### LINKED ISSUE #11268: False Negative: RedundantModifierCheck
I have read check documentation: https://checkstyle.sourceforge.io/config_modifier.html#RedundantModifier
I have downloaded the latest checkstyle from: https://checkstyle.org/cmdline.html#Download_and_Run
I have executed the cli and showed it below, as cli describes the problem better than 1,000 words

```bash
/var/tmp $ javac Test.java

/var/tmp $ cat config.xml
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
        "-//Checkstyle//DTD Checkstyle Configuration 1.3//EN"
        "https://checkstyle.org/dtds/configuration_1_3.dtd">
<module name="Checker">
    <module name="TreeWalker">
        <module name="RedundantModifier"/>
    </module>
</module>

/var/tmp $ cat Test.java
package tmp;

public interface Test {
    public static interface foo { // violation for 'static', no violation for 'public'
    }

    public static enum someEnum { // violation for both
    }

    public static class someClass { // violation for both
    }

    public static record someRecord() { // violation for none, will be fixed in #11259
    }

    public static @interface someAnnInterface { // violation for none
    }
}


/var/tmp $ RUN_LOCALE="-Duser.language=en -Duser.country=US"
/var/tmp $ java $RUN_LOCALE -jar checkstyle-9.3-all.jar -c config.xml Test.java
Starting audit...
[ERROR] /var/tmp/Test.java:4:12: Redundant 'static' modifier. [RedundantModifier]
[ERROR] /var/tmp/Test.java:7:5: Redundant 'public' modifier. [RedundantModifier]
[ERROR] /var/tmp/Test.java:7:12: Redundant 'static' modifier. [RedundantModifier]
[ERROR] /var/tmp/Test.java:10:5: Redundant 'public' modifier. [RedundantModifier]
[ERROR] /var/tmp/Test.java:10:12: Redundant 'static' modifier. [RedundantModifier]
Audit done.
Checkstyle ends with 5 errors.

```
---

**Describe what you expect in detail.**
```
Starting audit...
[ERROR] /var/tmp/Test.java:4:5: Redundant 'public' modifier. [RedundantModifier]
[ERROR] /var/tmp/Test.java:4:12: Redundant 'static' modifier. [RedundantModifier]
[ERROR] /var/tmp/Test.java:7:5: Redundant 'public' modifier. [RedundantModifier]
[ERROR] /var/tmp/Test.java:7:12: Redundant 'static' modifier. [RedundantModifier]
[ERROR] /var/tmp/Test.java:10:5: Redundant 'public' modifier. [RedundantModifier]
[ERROR] /var/tmp/Test.java:10:12: Redundant 'static' modifier. [RedundantModifier]
[ERROR] /var/tmp/Test.java:13:5: Redundant 'public' modifier. [RedundantModifier]
[ERROR] /var/tmp/Test.java:13:12: Redundant 'static' modifier. [RedundantModifier]
[ERROR] /var/tmp/Test.java:16:5: Redundant 'public' modifier. [RedundantModifier]
[ERROR] /var/tmp/Test.java:16:12: Redundant 'static' modifier. [RedundantModifier]
Audit done.
Checkstyle ends with 10 errors.
```
Every member class or interface declaration in the body of an interface declaration is implicitly public and static. See [JLS](https://docs.oracle.com/javase/specs/jls/se17/html/jls-9.html#jls-9.5) for more info. Comments in code specify the current behavior.

### PR DESCRIPTION
**Pull request by Vyom-Yadav**
Resolves #11268
Diff Regression config: https://gist.githubusercontent.com/Vyom-Yadav/98dceb63a79f4833e85fff9b2e1464a6/raw/2984d7a7e418099c61e407c3dd56748ba5cada87/my_checks.xml

---

Diff Report: https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/e6cae19_2022205859/reports/diff/index.html
Website: https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/e6cae19_2022054921/config_modifier.html#RedundantModifier

### CODE REVIEW

**Comment by Vyom-Yadav** [comment]
Github, generate report

**Comment by Vyom-Yadav** [comment]
Github, generate site

**Comment by Vyom-Yadav** [comment]
Link to check: https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/e6cae19_2022054921/config_modifier.html#RedundantModifier

File: src/test/resources/com/puppycrawl/tools/checkstyle/checks/modifier/redundantmodifier/InputRedundantModifierNestedDef.java [hunk 1]
```diff
@@ -15,4 +15,16 @@
     interface MyInnerInterface {
         public strictfp class MyInnerClass {} // violation
     }
+
+    public static class testClass { // 2 violations
+    }
+
+    public abstract static @interface testAnnotatedInterface { // 3 violations
```
Comment (strkkk) [inline src/test/resources/com/puppycrawl/tools/checkstyle/checks/modifier/redundantmodifier/InputRedundantModifierNestedDef.java:22]: what about cases like
```
interface A { // top level
   interface B {
       static interface C {} // will be violation?
   }
}
```

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/modifier/RedundantModifierCheck.java [hunk 2]
```diff
@@ -61,7 +62,7 @@
  * Interfaces by definition are abstract so the {@code abstract}
  * modifier on the interface is redundant.
  * </p>
- * <p>Classes inside of interfaces by definition are public and static,
+ * <p>Type declarations inside of interfaces by definition are public and static,
```
Comment (strkkk) [inline src/main/java/com/puppycrawl/tools/checkstyle/checks/modifier/RedundantModifierCheck.java:65]: here it is `Type declarations` but above it is mentioned that they are nested. I think it should be mentioned here as well.

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/modifier/RedundantModifierCheck.java [hunk 3]
```diff
@@ -48,7 +48,8 @@
  * Final modifier on methods of final and anonymous classes.
  * </li>
  * <li>
- * Inner {@code interface} declarations that are declared as {@code static}.
+ * Type declarations nested under {@code interface} that are declared
+ * as {@code public} or {@code static}.
```
Comment (strkkk) [inline src/main/java/com/puppycrawl/tools/checkstyle/checks/modifier/RedundantModifierCheck.java:52]: Annotations should be mentioned somewhere as well, since you have added this token into list of acceptable tokens

**Review by strkkk — CHANGES_REQUESTED** [review]

File: src/test/resources/com/puppycrawl/tools/checkstyle/checks/modifier/redundantmodifier/InputRedundantModifierNestedDef.java (hunk 1 above)
Comment (Vyom-Yadav) [reply src/test/resources/com/puppycrawl/tools/checkstyle/checks/modifier/redundantmodifier/InputRedundantModifierNestedDef.java:22]: > will be violation?

Yes.

The level of nesting doesn't matter, as long as it is nested inside an interface, it is public and static implicitly.

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/modifier/RedundantModifierCheck.java (hunk 3 above)
Comment (Vyom-Yadav) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/modifier/RedundantModifierCheck.java:52]: Done

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/modifier/RedundantModifierCheck.java (hunk 2 above)
Comment (Vyom-Yadav) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/modifier/RedundantModifierCheck.java]: Done

File: src/test/resources/com/puppycrawl/tools/checkstyle/checks/modifier/redundantmodifier/InputRedundantModifierNestedDef.java (hunk 1 above)
Comment (strkkk) [reply src/test/resources/com/puppycrawl/tools/checkstyle/checks/modifier/redundantmodifier/InputRedundantModifierNestedDef.java:22]: please extend test inputs to show this

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/modifier/RedundantModifierCheck.java [hunk 4]
```diff
@@ -58,12 +59,12 @@
...
  * <p>
- * Interfaces by definition are abstract so the {@code abstract}
- * modifier on the interface is redundant.
+ * {@code interface} and {@code @interface} by definition are abstract so the {@code abstract}
+ * modifier is redundant on them.
  * </p>
- * <p>Classes inside of interfaces by definition are public and static,
- * so the {@code public} and {@code static} modifiers
- * on the inner classes are redundant. On the other hand, classes
+ * <p>Type declarations nested under an interface and an annotated interface by definition
```
Comment (strkkk) [inline src/main/java/com/puppycrawl/tools/checkstyle/checks/modifier/RedundantModifierCheck.java:65]: `annotated interface` please change it to `{@code interface} and {@code @interface}` as above

**Comment by Vyom-Yadav** [comment]
```
[INFO] --- maven-checkstyle-plugin:3.1.2:check (default-cli) @ hibernate-search-v5migrationhelper-engine ---

[INFO] There is 1 error reported by Checkstyle 10.0-SNAPSHOT with checkstyle.xml ruleset.

[ERROR] src/main/java/org/hibernate/search/query/dsl/RangeMatchingContext.java:[28,9] (modifier) RedundantModifier: Redundant 'public' modifier.
```
Will send a PR

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/modifier/RedundantModifierCheck.java (hunk 4 above)
Comment (Vyom-Yadav) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/modifier/RedundantModifierCheck.java]: Done

File: src/test/resources/com/puppycrawl/tools/checkstyle/checks/modifier/redundantmodifier/InputRedundantModifierNestedDef.java (hunk 1 above)
Comment (Vyom-Yadav) [reply src/test/resources/com/puppycrawl/tools/checkstyle/checks/modifier/redundantmodifier/InputRedundantModifierNestedDef.java:22]: Done

**Review by strkkk — APPROVED** [review]

**Comment by romani** [comment]
It took we awhile to understand what is FN, please update message to not use abbreviation.

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/modifier/RedundantModifierCheck.java [hunk 5]
```diff
@@ -225,36 +228,53 @@
...
+            case TokenTypes.RESOURCE:
                 processResources(ast);
-            }
+                break;
+            case TokenTypes.CLASS_DEF:
+            case TokenTypes.VARIABLE_DEF:
+            case TokenTypes.ANNOTATION_FIELD_DEF:
+                break;
+            default:
+                throw new IllegalStateException("Unexpected value: " + ast.getType());
```
Comment (nmancus1) [inline src/main/java/com/puppycrawl/tools/checkstyle/checks/modifier/RedundantModifierCheck.java:259]: Can we do `Unexpected token type: …` here?

**Review by nmancus1 — CHANGES_REQUESTED** [review]
Few items:

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/modifier/RedundantModifierCheck.java (hunk 5 above)
Comment (Vyom-Yadav) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/modifier/RedundantModifierCheck.java]: Done

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/modifier/RedundantModifierCheck.java [hunk 6]
```diff
@@ -48,7 +48,8 @@
  * Final modifier on methods of final and anonymous classes.
  * </li>
  * <li>
- * Inner {@code interface} declarations that are declared as {@code static}.
+ * Type declarations nested under {@code interface} and {@code @interface} that are declared
```
[the remark this answers is not in the document]
Comment (Vyom-Yadav) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/modifier/RedundantModifierCheck.java]: Let's be explicit, I used "declaration", is it fine?

[the remark this answers is not in the document]
Comment (nmancus1) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/modifier/RedundantModifierCheck.java]: >  we could go with "interfaces" too

Let's do this.

[the remark this answers is not in the document]
Comment (Vyom-Yadav) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/modifier/RedundantModifierCheck.java]: Done.

File: src/test/java/com/puppycrawl/tools/checkstyle/checks/modifier/RedundantModifierCheckTest.java [hunk 7]
```diff
@@ -149,12 +151,29 @@ public void testGetAcceptableTokens() {
...
             .that(actual)
             .isEqualTo(expected);
     }
 
+    @Test
+    public void testWrongTokenType() {
+        final RedundantModifierCheck obj = new RedundantModifierCheck();
+        final DetailAstImpl ast = new DetailAstImpl();
+        ast.initialize(TokenTypes.LITERAL_NULL, "null");
+        try {
```
[the remark this answers is not in the document]
Comment (Vyom-Yadav) [reply src/test/java/com/puppycrawl/tools/checkstyle/checks/modifier/RedundantModifierCheckTest.java:166]: I will modify this after pbludov's confirmation.

[the remark this answers is not in the document]
Comment (Vyom-Yadav) [reply src/test/java/com/puppycrawl/tools/checkstyle/checks/modifier/RedundantModifierCheckTest.java]: Done.

**Review by pbludov — APPROVED** [review]

File: src/test/java/com/puppycrawl/tools/checkstyle/checks/modifier/RedundantModifierCheckTest.java (hunk 7 above)
[the remark this answers is not in the document]
Comment (nmancus1) [reply src/test/java/com/puppycrawl/tools/checkstyle/checks/modifier/RedundantModifierCheckTest.java]: Resolved.

Issue opened at https://github.com/checkstyle/checkstyle/issues/11315 to prevent inconsistency in the future.

**Review by nmancus1 — APPROVED** [review]

**Comment by romani** [comment]
Github, generate report

**Comment by Vyom-Yadav** [comment]
Github, generate report

**Comment by romani** [comment]
https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/d2462be_2022055925/reports/diff/pmd/index.html#A1
false positive ?
```
rivanov@p5510:/var/tmp$ cat Test.java 
class Inner{
    @Test.varr int i;
}
public class Test {
  public static @interface varr { }
}
rivanov@p5510:/var/tmp$ javac Test.java 
rivanov@p5510:/var/tmp$ cat Test.java 
class Inner{
    @Test.varr int i;
}
public class Test {
  static @interface varr { }
}
rivanov@p5510:/var/tmp$ javac Test.java 
rivanov@p5510:/var/tmp$ cat Test.java 
class Inner{
    @Test.varr int i;
}
public class Test {
  private static @interface varr { }
}
rivanov@p5510:/var/tmp$ javac Test.java 
Test.java:2: error: varr has private access in Test
    @Test.varr int i;
         ^
1 error

```

removal of public, means package private, so visible in same folder for all. We never know if all usage are some folder.

**Comment by Vyom-Yadav** [comment]
@romani Violation is for static and not for public.

**Review by romani — APPROVED** [review]
