### PR TITLE
Issue #8710: add check for private method javadoc to config

### LINKED ISSUE #8710: Checkstyle: Javadoc not required on private method
Identified at https://github.com/checkstyle/checkstyle/pull/7932#discussion_r471834347 ,

All methods should have a javadoc in main code, including private methods. Somehow our config is broken that it is not reporting this.

### PR DESCRIPTION
**Pull request by strkkk**
Closes #8710 

Warnings corrected as well.

### CODE REVIEW

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/OneStatementPerLineCheck.java [hunk 1]
```diff
@@ -288,12 +294,21 @@ private void checkLambda(DetailAST ast, DetailAST currentStatement) {
...
+     * Checks that given node is a resource.
+     *
+     * @param ast semicolon to check
+     * @return true if node is a resource
+     */
     private static boolean isResource(DetailAST ast) {
-        return ast != null
-            && (ast.getType() == TokenTypes.RESOURCES
-                 || ast.getType() == TokenTypes.RESOURCE_SPECIFICATION);
+        return TokenUtil.isOfType(ast, TokenTypes.RESOURCES, TokenTypes.RESOURCE_SPECIFICATION);
```
Comment (strkkk) [inline src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/OneStatementPerLineCheck.java:304]: this one is not required, but just added it as a small enhancement

**Comment by strkkk** [comment]
Semaphore failure is not related with code changes

**Comment by rnveach** [comment]
> We should review the scopes of the other Missing checks to ensure they match their other.

Was this done?

File: config/checkstyle_checks.xml [hunk 2]
```diff
@@ -551,6 +551,11 @@
     <module name="JavadocMethod">
       <property name="validateThrows" value="true"/>
     </module>
+    <module name="JavadocMethod">
+      <property name="id" value="privateMethodsJavadoc"/>
```
Comment (rnveach) [inline config/checkstyle_checks.xml:555]: Why 2 instances of the same check? Really we just lost the setting of private when we changed the default value for the scope.

Also, default scope is already private. It was the Missing method which was the issue.
https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocMethodCheck.java#L375

File: config/checkstyle_checks.xml [hunk 3]
```diff
@@ -565,6 +570,11 @@
     <module name="MissingJavadocMethod">
       <property name="allowMissingPropertyJavadoc" value="true"/>
     </module>
+    <module name="MissingJavadocMethod">
+      <property name="id" value="missingPrivateMethodsJavadoc"/>
+      <property name="allowMissingPropertyJavadoc" value="true"/>
+      <property name="scope" value="private"/>
```
Comment (rnveach) [inline config/checkstyle_checks.xml:576]: Same.

**Comment by romani** [comment]
Github, rebase

**Comment by romani** [comment]
Github, rebase

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/OneStatementPerLineCheck.java (hunk 1 above)
Comment (romani) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/OneStatementPerLineCheck.java:304]: @strkkk , please move this in separate commit, "minor: refactor ....." to keep it off javadoc beutification

**Comment by romani** [comment]
@strkkk , there is conflict, please resolve.
code need to be rebased to pass CI

File: config/checkstyle_checks.xml (hunk 3 above)
Comment (strkkk) [reply config/checkstyle_checks.xml:576]: Here we need a second instance since check can accept only one scope. Default is public, so one more instance of check is added with same properties but different scope

File: config/checkstyle_checks.xml (hunk 2 above)
Comment (strkkk) [reply config/checkstyle_checks.xml:555]: removed

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/OneStatementPerLineCheck.java (hunk 1 above)
Comment (strkkk) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/OneStatementPerLineCheck.java:304]: I removed this

**Comment by strkkk** [comment]
> Was this done?

I have added same check for MissingJavadocType

File: config/checkstyle_checks.xml (hunk 3 above)
Comment (rnveach) [reply config/checkstyle_checks.xml:577]: `private` should already include `public`. Only 1 scope should be needed in this case.
https://checkstyle.org/property_types.html#Scope

> Using a specific scope means not only will that modifier be examined, but also all the modifiers listed above it in the previous list. Specifying public means only items with public modifiers are checked. Specifying protected means only public and protected modifiers are checked.

**Comment by rnveach** [comment]
> I have added same check for MissingJavadocType

Confirmed, scopes are different in documentation.
https://checkstyle.org/config_javadoc.html#JavadocType_Properties
https://checkstyle.org/config_javadoc.html#MissingJavadocType_Properties

File: config/checkstyle_checks.xml (hunk 3 above)
Comment (strkkk) [reply config/checkstyle_checks.xml:573]: I didn't know that. I have made changes

**Review by rnveach — APPROVED** [review]

**Comment by rnveach** [comment]
Github, rebase

**Comment by rnveach** [comment]
@strkkk Github or me can't rebase this PR. Please rebase this PR so I can merge it if @romani doesn't review it.

**Comment by strkkk** [comment]
> Github or me can't rebase this PR

This is because there were changes in github actions in master branch, rebase wont work in this case. I will rebase manually later.

**Comment by strkkk** [comment]
@rnveach done

**Comment by rnveach** [comment]
Thanks.

**Review by romani — APPROVED** [review]
Ok to merge
