### PR TITLE
Issue #7329: remove class loading in JavadocMethod

### LINKED ISSUE #7329: Remove class loading from JavadocMethod
part of #7116 .

We need to remove from Check any attempt to use classloader to validate source code.
Checkstyle cannot make this reliably and it is whole tool limitation for now - https://checkstyle.org/writingchecks.html#Limitations

**Migration Notes:**
properties `allowMissingThrowsTags`, `allowUndeclaredRTE`  and `allowThrowsTagsForSubclasses`, `logLoadErrors`, `suppressLoadErrors` should be just removed from configs. 
Behavior will change as there will be less violations in code, such properties did not work well so their removal should be ok, as there will be less false-positives. **Throws will not be validated by default !!** 
If you need to validate `@throws` please enable property `validateThrows` but please read documentation as there some limitations.

### PR DESCRIPTION
**Pull request by rnveach**
fixes #7329 , #7380

My plan to diminish class loading is to remove pieces at a time. I will work from the inside out identifying pieces as I go which can be removed and what can stay. Suppressions will be needed as I go as the code may be in an incomplete form.

This PR breaks class loading in the check by removing the most inner piece for it to function. Differences were created in the tests.

**Regressions**:
minor, not ideal, but user have workaround by placing each exception on its own line - not ideal, but it is ok -   https://romani.github.io/7329/diff/Hbase/index.html#A37 , is somebody complained, will be resolved as bug later on.

### CODE REVIEW

**Comment by rnveach** [comment]
Regression: http://rveach.no-ip.org/checkstyle/regression/reports/276/

There are some additions as well as mostly removals.

http://rveach.no-ip.org/checkstyle/regression/reports/276/openjdk10/index.html#A56
Seems class loading was needed to determine if a fully qualified class matches the short class name.

**Comment by rnveach** [comment]
@romani appveyor is showing a success for the build while its ouput shows errors.
https://ci.appveyor.com/project/Checkstyle/checkstyle/builds/28075194/job/1rhn45kgs3orqh7w

**Comment by rnveach** [comment]
https://github.com/checkstyle/checkstyle/pull/7193#issuecomment-541425536

**Comment by romani** [comment]
>Seems class loading was needed to determine if a fully qualified class matches the short class name.
I assume we should still support this.

Ideally, yes, please try to make a logic to convert both names to short name and then do match. It might create some false-nagatives, but we do not care, they will not bother user.

>We also document exceptions that are not listed as being thrown.
Do we still need to support this?

Let's remove this from javadoc. Such issue should not block this PR.

**Comment by romani** [comment]
Ping, let's move appveyor to separate issue, and finish, Check refactoring.
If fixing regression with false positives is complicated, I am ok to make change to simply skip validation ( so we will introduce bug in purpose). As it will result in false negatives, nobody will be affected heavily. We will resolve intensionally introduced bug later on.

It will be good to pack all classpath breaking compatibilities in one release.

**Comment by romani** [comment]
@rnveach , ping.
Please find time to finish this PR.
lets keep it as with all other PRs, if no actions till end of month, we need to close PR, we can reopen it when we have time to work on it.

**Comment by romani** [comment]
@rnveach , ping.
do you think we can finish this PR this month ? Do you  need help ?
Please let me know how can I help you finish this update.

**Comment by romani** [comment]
> We also document exceptions that are not listed as being thrown.
Do we still need to support this?

We should not raise problems on this, as we can not reliably diagnose what exceptions are thrown by reading only method code.
As result all such violations should not be raised, there should not be any new violations after this refactoring. There will be bunch of false-negative, but we will resolve this in separate issue(s).

**Comment by romani** [comment]
I just pushed big update to remove all loading
Issues that found in regression report were added to Inputs and supported.

I will provide new regression soon.

**Comment by rnveach** [comment]
> config: disable Strata project, as I do not know where their config i…

https://github.com/OpenGamma/Strata/blob/4c9d6fc7e466dbac3f4a0781541d5d1b69b1da78/modules/pom.xml#L115
https://github.com/OpenGamma/Strata/blob/4c9d6fc7e466dbac3f4a0781541d5d1b69b1da78/modules/pom.xml#L733

https://maven.apache.org/plugins/maven-checkstyle-plugin/checkstyle-mojo.html
> Default value is: sun_checks.xml.

**Comment by romani** [comment]
They use config from some artifact, it is too much to fork few repositories and hacking their configs.

**Comment by rnveach** [comment]
````
[INFO] --- maven-checkstyle-plugin:3.1.0:checkstyle (run-checkstyle) @ strata-collect ---
[DEBUG] Configuring mojo org.apache.maven.plugins:maven-checkstyle-plugin:3.1.0:checkstyle from plugin realm ClassRealm[plugin>org.apache.maven.plugins:maven-checkstyle-plugin:3.1.0, parent: sun.misc.Launcher$AppClassLoader@1b6d3586]
[DEBUG] Configuring mojo 'org.apache.maven.plugins:maven-checkstyle-plugin:3.1.0:checkstyle' with basic configurator -->
[DEBUG]   (f) cacheFile = /media/checkstyle/work/Strata/modules/collect/target/checkstyle-cachefile
[DEBUG]   (f) checkstyleRulesHeader = <?xml version="1.0"?>
<!DOCTYPE module PUBLIC "-//Checkstyle//DTD Checkstyle Configuration 1.3//EN"
        "https://checkstyle.org/dtds/configuration_1_3.dtd">

[DEBUG]   (f) configLocation = checkstyle/checkstyle-main-v8.26.xml
[DEBUG]   (f) consoleOutput = true
[DEBUG]   (f) enableFilesSummary = true
[DEBUG]   (f) enableRSS = false
[DEBUG]   (f) enableRulesSummary = true
[DEBUG]   (f) enableSeveritySummary = true
[DEBUG]   (f) encoding = UTF-8
[DEBUG]   (f) excludes = module-info.java
[DEBUG]   (f) failsOnError = true
[DEBUG]   (f) headerLocation = LICENSE.txt
[DEBUG]   (f) includeResources = false
[DEBUG]   (f) includeTestResources = false
[DEBUG]   (f) includeTestSourceDirectory = false
[DEBUG]   (f) includes = **\/*.java
[DEBUG]   (f) inputEncoding = UTF-8
[DEBUG]   (f) linkXRef = true
[DEBUG]   (f) omitIgnoredModules = false
[DEBUG]   (f) outputDirectory = /media/checkstyle/work/Strata/modules/collect/target/site
[DEBUG]   (f) outputEncoding = UTF-8
[DEBUG]   (f) outputFile = /media/checkstyle/work/Strata/modules/collect/target/checkstyle-result.xml
[DEBUG]   (f) outputFileFormat = xml
[DEBUG]   (f) plugin = Component Descriptor: role: 'org.apache.maven.plugin.Mojo', implementation: 'org.apache.maven.plugins.checkstyle.CheckstyleViolationCheckMojo', role hint: 'org.apache.maven.plugins:maven-checkstyle-plugin:3.1.0:check'
role: 'org.apache.maven.plugin.Mojo', implementation: 'org.apache.maven.plugins.checkstyle.CheckstyleReport', role hint: 'org.apache.maven.plugins:maven-checkstyle-plugin:3.1.0:checkstyle'
role: 'org.apache.maven.plugin.Mojo', implementation: 'org.apache.maven.plugins.checkstyle.CheckstyleAggregateReport', role hint: 'org.apache.maven.plugins:maven-checkstyle-plugin:3.1.0:checkstyle-aggregate'
role: 'org.apache.maven.plugin.Mojo', implementation: 'org.apache.maven.plugins.checkstyle.HelpMojo', role hint: 'org.apache.maven.plugins:maven-checkstyle-plugin:3.1.0:help'
---
[DEBUG]   (f) project = MavenProject: com.opengamma.strata:strata-collect:2.6.9-SNAPSHOT @ /media/checkstyle/work/Strata/modules/collect/pom.xml
[DEBUG]   (f) resourceIncludes = **/*.properties
[DEBUG]   (f) resources = [Resource {targetPath: null, filtering: false, FileSet {directory: /media/checkstyle/work/Strata/modules/collect/src/main/resources, PatternSet [includes: {}, excludes: {com/opengamma/strata/collect/version.properties}]}}, Resource {targetPath: null, filtering: true, FileSet {directory: /media/checkstyle/work/Strata/modules/collect/src/main/resources, PatternSet [includes: {com/opengamma/strata/collect/version.properties}, excludes: {}]}}, Resource {targetPath: META-INF, filtering: false, FileSet {directory: /media/checkstyle/work/Strata/modules/collect/../.., PatternSet [includes: {LICENSE.txt, NOTICE.txt}, excludes: {}]}}]
[DEBUG]   (f) rulesFiles = /media/checkstyle/work/Strata/modules/collect/target/checkstyle-rules.xml
[DEBUG]   (f) skip = false
[DEBUG]   (f) suppressionsFileExpression = checkstyle.suppressions.file
[DEBUG]   (f) testResources = [Resource {targetPath: null, filtering: false, FileSet {directory: /media/checkstyle/work/Strata/modules/collect/src/test/resources, PatternSet [includes: {}, excludes: {}]}}, Resource {targetPath: META-INF, filtering: false, FileSet {directory: /media/checkstyle/work/Strata/modules/collect/../.., PatternSet [includes: {LICENSE.txt, NOTICE.txt}, excludes: {}]}}]
[DEBUG]   (f) xrefLocation = /media/checkstyle/work/Strata/modules/collect/target/site/xref
[DEBUG] -- end configuration --
[DEBUG] executeCheckstyle start headerLocation : LICENSE.txt
[DEBUG] Added 105 source files found in '/media/checkstyle/work/Strata/modules/collect/src/main/java'.
[DEBUG] No resources found in this project.
[DEBUG] No test resources found in this project.
[DEBUG] Added 105 files to process.
[DEBUG] Adding the outputDirectory file:/media/checkstyle/work/Strata/modules/collect/target/classes/ to the Checkstyle class path
[DEBUG] request.getConfigLocation() checkstyle/checkstyle-main-v8.26.xml
[DEBUG] The resource 'checkstyle/checkstyle-main-v8.26.xml' was not found with resourceLoader org.codehaus.plexus.resource.loader.JarResourceLoader.
[DEBUG] The resource 'checkstyle/checkstyle-main-v8.26.xml' was found as jar:file:/home/ricky/.m2/repository/com/opengamma/build-config/2.6.0/build-config-2.6.0.jar!/checkstyle/checkstyle-main-v8.26.xml.
[DEBUG] headerLocation LICENSE.txt
[DEBUG] JarResourceLoader : trying to load "jar:file:/home/ricky/.m2/repository/com/puppycrawl/tools/checkstyle/8.26/checkstyle-8.26.jar"
[DEBUG] JarResourceLoader : trying to load "jar:file:/home/ricky/.m2/repository/com/opengamma/build-config/2.6.0/build-config-2.6.0.jar"
[DEBUG] The resource 'LICENSE.txt' was not found with resourceLoader org.codehaus.plexus.resource.loader.JarResourceLoader.
[DEBUG] URLResourceLoader: No valid URL 'LICENSE.txt'
[DEBUG] URLResourceLoader: No valid URL 'LICENSE.txt'
[DEBUG] The resource 'LICENSE.txt' was not found with resourceLoader org.codehaus.plexus.resource.loader.URLResourceLoader.
[DEBUG] The resource 'LICENSE.txt' was not found with resourceLoader org.codehaus.plexus.resource.loader.FileResourceLoader.
[DEBUG] Unable to process header location: LICENSE.txt
[DEBUG] Checkstyle will throw exception if ${checkstyle.header.file} is used
[DEBUG] Added '/media/checkstyle/work/Strata/modules/collect/src/main/resources' as a source directory.
[DEBUG] Added '/media/checkstyle/work/Strata/modules/collect/src/main/resources' as a source directory.
[DEBUG] Added '/media/checkstyle/work/Strata/modules/collect/../..' as a source directory.
[INFO] Starting audit...
Audit done.
````

> [DEBUG] The resource 'checkstyle/checkstyle-main-v8.26.xml' was found as jar:file:/home/ricky/.m2/repository/com/opengamma/build-config/2.6.0/build-config-2.6.0.jar!/checkstyle/checkstyle-main-v8.26.xml.

https://github.com/OpenGamma/OG-Tools/blob/master/build-config/src/main/resources/checkstyle/checkstyle-main-v8.26.xml

**Comment by romani** [comment]
Please push commit :) it your branch also

**Comment by romani** [comment]
All CIs are passing, @rnveach please review. Update is big, I kind of not sure if some split can help. When I rollback change for certain project, I usually do this without revert, as search for certain commit in not convenient.

**Comment by romani** [comment]
all commits are squashed, @rnveach , please review.

**Comment by romani** [comment]
rebased, failures from "codecov.io" could be ignored, we do not use such service any more.

**Comment by romani** [comment]
@rnveach , ready for review. Failures of codecov should be ignored.

**Comment by rnveach** [comment]
> fixes #7329

Originally this PR does not fix the issue. It is to be a multi-staged PR. See https://github.com/rnveach/checkstyle/commits/issue_7116 for all staged commits planned.

> BUT it is actually not a correct form of @throws, as only one class name is expected by specification - https://docs.oracle.com/javase/8/docs/technotes/tools/windows/javadoc.html#CHDCHAHD

Same documentation says:
> If this class is not fully specified, then the javadoc command uses the search order to look up this class.

I take "fully specified" to mean full classpath, otherwise a partial class name doesn't make any sense.

> http://rveach.no-ip.org/checkstyle/regression/reports/276/
> https://romani.github.io/7329/diff/index.html

New report shows alot of differences over old report. Is this from new changes in JavadocMethod outside this PR?

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocMethodCheck.java [hunk 1]
```diff
@@ -173,23 +140,11 @@
  * &lt;module name="JavadocMethod"/&gt;
  * </pre>
  * <p>
- * To configure the check for {@code public} scope and to allow documentation
- * of undeclared RuntimeExceptions:
+ * To configure the check for for {@code public} scope, ignoring any missing param tags is:
```
Comment (rnveach) [inline src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocMethodCheck.java]: > for for

Only 1 for needed.

File: src/xdocs/config_javadoc.xml [hunk 2]
```diff
@@ -778,28 +728,14 @@ public int checkReturnTag(final int aTagIndex,
...
-        </p>
-        <source>
-&lt;module name="JavadocMethod"&gt;
-  &lt;property name="scope" value="public"/&gt;
-  &lt;property name="allowUndeclaredRTE" value="true"/&gt;
-&lt;/module&gt;
-        </source>
-
         <p>
           To configure the check for for <code>public</code>
```
Comment (rnveach) [inline src/xdocs/config_javadoc.xml]: another `for for`

**Comment by romani** [comment]
> I take "fully specified" to mean full classpath, otherwise a partial class name doesn't make any sense.

yes fully qualified name single name or short name, but not a list of class names like `IllegalStateExcepton, IOException`.

> New report shows alot of differences over old report. Is this from new changes in JavadocMethod outside this PR?

You did only some functionality removal, I did far further deletion for it more violations disappear is expected. I did review of my report, looks ok, not ideal, but ok.

> Originally leaving in properties was to make regression CI and this PR easier to manage.

yes, but it is better cut ones to affect users/plugins ones. Nobody react on our deprecation of properties, till it works and build is passing, nobody looks in details of our release.

File: src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadocmethod/InputJavadocMethodExtraThrows.java [hunk 3]
```diff
@@ -0,0 +1,46 @@
...
+            throw new IllegalArgumentException("cannot have char with code 0");
+        }
+        // here is NPE possible
+        properties.isEmpty();
+    }
+
+    /**
+     * Extra throws in javadoc it is ok
+     * @param properties some value
+     * @throws java.lang.IllegalArgumentException when argument is wrong // ok
```
Comment (rnveach) [inline src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadocmethod/InputJavadocMethodExtraThrows.java]: http://rveach.no-ip.org/checkstyle/regression/reports/276/openjdk10/index.html#A56
http://rveach.no-ip.org/checkstyle/regression/reports/276/openjdk10/xref/src/java.base/share/classes/jdk/internal/org/xml/sax/EntityResolver.java.html#L139
Original regression said this would be a new violation. Did something change that I missed?

**Comment by rnveach** [comment]
> but not a list of class names like IllegalStateExcepton, IOException.

Agreed. Confused this with old regression.

> You did only some functionality removal, I did far further deletion for it more violations disappear is expected. I did review of my report, looks ok, not ideal, but ok.

There should be no more differences over my report and yours. Further removals should have been just logic I left in and was planning to remove later. Removing class loading was suppose to be the only change that caused differences.

> Nobody react on our deprecation of properties

I meant specifically to make the PR and review easier. Its done now so doesn't matter.

File: src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadocmethod/InputJavadocMethodExtraThrows.java (hunk 3 above)
Comment (romani) [reply src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadocmethod/InputJavadocMethodExtraThrows.java]:
```
132      * @exception java.io.IOException A Java-specific IO exception,
133      *            possibly the result of creating a new InputStream
134      *            or Reader for the InputSource.
135      * @see org.xml.sax.InputSource
136      */
137     public abstract InputSource resolveEntity (String publicId,
138                                                String systemId)
139         throws SAXException, IOException;
```

yes but it is case when method throws  and javadoc throws mean the same by one is using shohrt name and another use fully qualified name. 
it is covered by new method `isClassNamesSame` (not very robust implementation, but it is ok), so no violation anymore, as classes are the same.

File: src/xdocs/config_javadoc.xml (hunk 2 above)
Comment (romani) [reply src/xdocs/config_javadoc.xml]: done

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocMethodCheck.java (hunk 1 above)
Comment (romani) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocMethodCheck.java]: done

**Comment by romani** [comment]
wercker is passing on my local for xwiki, not sure what is problem on wercker.
@rnveach , please continue to review.

**Comment by romani** [comment]
rebased to resolve pitest.

**Comment by romani** [comment]
regression is full of false-negatives it is understandable to have a concern on this .....
But we need to bring this Check to reality that we validate only sources.

I did implementation of simple `throw` detection https://github.com/romani/checkstyle/commit/01835e1dffda33fbdb655fa36a555ff46504c822
here is report for it - https://checkstyle.sourceforge.io/reports/7116-detect-throw/diff/
and now Check starting to work close to properly, but there is huge size of new violations (good violations). So far I did not found any false-positive, but effect is huge. 
Do you want this to be part of this PR ?

**Comment by rnveach** [comment]
Since it is fixing functionality we lost from class loading, I am fine with it in this same commit and keeping your fix. Does it make sense to split this into 2 commits so I can clearly see what code is related to removing class loading and what is new additions to bring back runtime throws?

**Comment by romani** [comment]
new issue was created, as it looks like separate issue.
fixes are merged to this branch.

**Comment by rnveach** [comment]
I can't approve my own PR, but it looks good to me.

**Comment by romani** [comment]
@pbludov , please do final review.
I am starting to describe migration notes I think I need to add example of base exception class to documentation, to clearly declare limitation.

File: src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadocmethod/InputJavadocMethodExtraThrows.java [hunk 4]
```diff
@@ -0,0 +1,112 @@
...
+     * Extra throws in javadoc it is ok.
+     * @param properties some value
+     * @throws IllegalArgumentException when argument is wrong // ok
+     * @throws NullPointerException indicates null was passed // ok
+     */
+    public InputJavadocMethodExtraThrows(String properties) {
+        if (properties.charAt(0) == 0) {
+            throw new IllegalArgumentException("cannot have char with code 0");
+        }
+        // here is NPE possible
```
Comment (pbludov) [inline src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadocmethod/InputJavadocMethodExtraThrows.java]: Actually, NPE will be not here, but in the first line of this method.

Comment (romani) [reply src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadocmethod/InputJavadocMethodExtraThrows.java]: extra statement is removed.

**Comment by romani** [comment]
@rnveach and @pbludov , please review one more time.
I removed one more property - `allowMissingThrowsTags` as it lost meaning. it is good to not validate throws by default as user need to understand side effect (inability to recognize child and parent exception class).

documentation now looks like:
image

**Comment by rnveach** [comment]
> inability to recognize child and parent exception class

This could be suppressed via xpath if they specify parent/child relationship in query, but this check isn't supported.

> I removed one more property - allowMissingThrowsTags

Since google/sun use this check, does it impact them and our coverage table?

File: src/xdocs/config_javadoc.xml [hunk 5]
```diff
@@ -814,6 +736,47 @@ public int checkReturnTag(final int aTagIndex,
   &lt;property name="excludeScope" value="protected"/&gt;
 &lt;/module&gt;
         </source>
+
+        <p>
+          To configure the check to validate <code>throws</code> tags, you can use following config.
+          ATTENTION: checkstyle do not have information about hierarchy of exception types so usage
```
Comment (rnveach) [inline src/xdocs/config_javadoc.xml]: `checkstyle` => `Checkstyle`.
`do not` => `does not`

File: src/xdocs/config_javadoc.xml [hunk 6]
```diff
@@ -814,6 +736,47 @@ public int checkReturnTag(final int aTagIndex,
...
+          specify both types base and exact type in javadoc.
+        </p>
+        <source>
+&lt;module name="JavadocMethod"&gt;
+  &lt;property name="validateThrows" value="true"/&gt;
+&lt;/module&gt;
+        </source>
+        <source>
+/**
+ * Actually throwed is child class of class that is declared in throws.
```
Comment (rnveach) [inline src/xdocs/config_javadoc.xml]: `Actually throwed` => `Actual exception thrown`

File: src/xdocs/config_javadoc.xml [hunk 7]
```diff
@@ -814,6 +736,47 @@ public int checkReturnTag(final int aTagIndex,
...
+ * It is limitation of checkstyle (as we do not know type hierarchy).
```
Comment (rnveach) [inline src/xdocs/config_javadoc.xml]: `is limitation` => `is a limitation`

**Comment by romani** [comment]
>  does it impact them and our coverage table?

as `throws` validation was disabled in google, so it is stay the same.
 sun coverage report is incomplete.

File: src/xdocs/config_javadoc.xml [hunk 8]
```diff
@@ -814,6 +736,47 @@ public int checkReturnTag(final int aTagIndex,
...
+ * Code and javadoc is valid BUT checkstyle can not distinguish it.
```
Comment (rnveach) [inline src/xdocs/config_javadoc.xml]: `Code and javadoc is valid` => `Javadoc is valid not declaring {@link FileNotFoundException}`.

I don't see why original was specifying code when it is all about the javadoc.

File: src/xdocs/config_javadoc.xml [hunk 9]
```diff
@@ -814,6 +736,47 @@ public int checkReturnTag(final int aTagIndex,
...
+ * @throws IOException if some problem
+ */
+public void doSomething8(File file) throws IOException {
+    if (file == null) {
+        throw new FileNotFoundException(); // violation
+    }
+}
+
+/**
+ * Special throw type referencing in javadoc even first is parent of second type
```
Comment (rnveach) [inline src/xdocs/config_javadoc.xml]: Instead of `Special` wouldn't it make more sense to say `Exact`? Also this line is missing a period on the end.

File: src/xdocs/config_javadoc.xml [hunk 10]
```diff
@@ -814,6 +736,47 @@ public int checkReturnTag(final int aTagIndex,
...
+ * It is limitation of checkstyle (as we do not know type hierarchy).
+ * This javadoc is valid for checkstyle.
```
Comment (rnveach) [inline src/xdocs/config_javadoc.xml]: Is it valid only for Checkstyle or will javadoc tool be ok with it too? If tool is ok with it, we should specify that too.

Comment (romani) [reply src/xdocs/config_javadoc.xml]: yes it is ok by tool.
```
$ javadoc src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadocmethod/InputJavadocMethodExtraThrows.java
Loading source file src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadocmethod/InputJavadocMethodExtraThrows.java...
Constructing Javadoc information...
Standard Doclet version 1.8.0_162
Building tree for all the packages and classes...
Generating ./com/puppycrawl/tools/checkstyle/checks/javadoc/javadocmethod/InputJavadocMethodExtraThrows.html...
Generating ./com/puppycrawl/tools/checkstyle/checks/javadoc/javadocmethod/package-frame.html...
Generating ./com/puppycrawl/tools/checkstyle/checks/javadoc/javadocmethod/package-summary.html...
Generating ./com/puppycrawl/tools/checkstyle/checks/javadoc/javadocmethod/package-tree.html...
Generating ./constant-values.html...
Building index for all the packages and classes...
Generating ./overview-tree.html...
Generating ./index-all.html...
Generating ./deprecated-list.html...
Building index for all classes...
Generating ./allclasses-frame.html...
Generating ./allclasses-noframe.html...
Generating ./index.html...
Generating ./help-doc.html...
```
output:
image

Comment (romani) [reply src/xdocs/config_javadoc.xml]: done.

File: src/xdocs/config_javadoc.xml (hunk 9 above)
Comment (romani) [reply src/xdocs/config_javadoc.xml]: done

File: src/xdocs/config_javadoc.xml (hunk 8 above)
Comment (romani) [reply src/xdocs/config_javadoc.xml]: done

File: src/xdocs/config_javadoc.xml (hunk 7 above)
Comment (romani) [reply src/xdocs/config_javadoc.xml]: done

File: src/xdocs/config_javadoc.xml (hunk 6 above)
Comment (romani) [reply src/xdocs/config_javadoc.xml]: done

File: src/xdocs/config_javadoc.xml (hunk 5 above)
Comment (romani) [reply src/xdocs/config_javadoc.xml]: done

**Comment by rnveach** [comment]
Looks good to me.

File: src/xdocs/config_javadoc.xml (hunk 8 above)
Comment (romani) [reply src/xdocs/config_javadoc.xml]: I removed `@link` as it require import (jdk11 failure and TC faliure)
