### PR TITLE
Issue #15967: fix yield fails indentation in switch with forceStrictCondition

### LINKED ISSUE #15967: `yield` fails Indentation check in switch expressions
I have read check documentation: https://checkstyle.sourceforge.io/checks/misc/indentation.html
I have downloaded the latest cli from: https://checkstyle.org/cmdline.html#Download_and_Run
I have executed the cli and showed it below, as cli describes the problem better than 1,000 words

```bash
$ javac IndentationFoo.java
$

```

```bash
$ cat checkstyle-foo.xml 
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC "-//Puppy Crawl//DTD Check Configuration 1.3//EN"
        "https://checkstyle.org/dtds/configuration_1_3.dtd">
<module name="Checker">
    <module name="TreeWalker">
        <module name="Indentation">
            <property name="forceStrictCondition" value="true"/>
        </module>
    </module>
</module>
```

```bash
$ cat IndentationFoo.java 
import java.time.DayOfWeek;
import java.time.LocalDate;

public class IndentationFoo {
    public static void main(final String[] args) {
        final DayOfWeek today = LocalDate.now().getDayOfWeek();
        final boolean isWeekend = switch (today) {
            case SATURDAY:
            System.out.println("Saturday"); // Warning: expected indentation: 16
            yield true; // Warning: expected indentation: 16.
            case SUNDAY:
                System.out.println("Sunday"); // (no warning)
                yield true; // Warning: expected indentation: 12
            default:
yield false; // Warning: expected indentation: 12
        };
        System.out.println("isWeekend = " + isWeekend);
    }
}
```

```bash
$ java -jar checkstyle-10.20.1-all.jar -c checkstyle-foo.xml IndentationFoo.java 
Starting audit...
[ERROR] IndentationFoo.java:9:13: 'block' child has incorrect indentation level 12, expected level should be 16. [Indentation]
[ERROR] IndentationFoo.java:10:13: 'yield' has incorrect indentation level 12, expected level should be 16. [Indentation]
[ERROR] IndentationFoo.java:13:17: 'yield' has incorrect indentation level 16, expected level should be 12. [Indentation]
[ERROR] IndentationFoo.java:15:1: 'yield' has incorrect indentation level 0, expected level should be 12. [Indentation]
Audit done.
Checkstyle ends with 4 errors.

```
---

The Indentation check rejects all `yield` statements in switch expressions when `forceStrictCondition` is set to true. In the example above, it rejects anything that is not 12, saying 12 is the correct level. If you set the indentation level to 12, it rejects it saying it should be 16. 

This is also inconsistent with the required indentation level for other statements, which require an indentation of 16. 

I would expect 16 to be accepted as the correct indentation for all of these statements.

### PR DESCRIPTION
**Pull request by mohitsatr**
fixes #15967

### CODE REVIEW

**Comment by mohitsatr** [comment]
Github, generate report for Indentation/all-examples-in-one

**Comment by mohitsatr** [comment]
Github, generate report for Indentation/all-examples-in-one

**Comment by mohitsatr** [comment]
Github, generate report for Indentation/all-examples-in-one

**Comment by mohitsatr** [comment]
Github, generate report for Indentation/all-examples-in-one

**Comment by mohitsatr** [comment]
Github, generate report for Indentation/all-examples-in-one

**Comment by mohitsatr** [comment]
Github, generate report for Indentation/Example2

**Comment by mohitsatr** [comment]
@romani check out regression report https://github.com/checkstyle/checkstyle/pull/16131#issuecomment-2576696245
for commit https://github.com/checkstyle/checkstyle/commit/3e7d5725ca45c29dd648e9f327c747f0d6dbc36f

basically it resolves the original problem for which issue is raised. there is just one false positive [case](https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/3e7d5725ca45c29dd648e9f327c747f0d6dbc36f_2025035608/reports/diff/openjdk21/index.html#A2)
i have been playing with it and looks like it requires more than a simple code change as there are more diffs in subsequent reports. I think we should raise separate issue for that case. what do you think?

**Comment by mohitsatr** [comment]
@romani please check out regression report https://github.com/checkstyle/checkstyle/pull/16131#issuecomment-2576696245
for commit https://github.com/checkstyle/checkstyle/commit/3e7d5725ca45c29dd648e9f327c747f0d6dbc36f

basically it resolves the original problem for which issue is raised. there is just one false positive [case](https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/3e7d5725ca45c29dd648e9f327c747f0d6dbc36f_2025035608/reports/diff/openjdk21/index.html#A2)
i have been playing with it and looks like it requires more than a simple code change as there are more diffs in subsequent reports. I think we should raise separate issue for that case. what do you think?

latest diff reports : https://github.com/checkstyle/checkstyle/pull/16131#issuecomment-2585557293
https://github.com/checkstyle/checkstyle/pull/16131#issuecomment-2585574305
problem arises when `switch` appears as a condition in `if`
```
if (switch(today) {
   . .. .
    }
)
```
ps: please ignore diff reports which are not linked in this comment

**Comment by mohitsatr** [comment]
Github, generate report for Indentation/all-examples-in-one

File: src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/indentation/indentation/InputIndentationYieldForceStrict.java [hunk 1]
```diff
@@ -0,0 +1,54 @@
...
+            case 0: //indent:12 exp:12
+            System.out.println("Saturday"); //indent:12 exp:16 warn
+            yield true; //indent:12 exp:16 warn
+            case 1: //indent:12 exp:12
+                System.out.println("Sunday"); //indent:16 exp:16
+                yield true; //indent:16 exp:16
+            default: //indent:12 exp:12
+    yield true; //indent:4 exp:16 warn
+        }; //indent:8 exp:8
+    } //indent:4 exp:4
```
Comment (romani) [inline src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/indentation/indentation/InputIndentationYieldForceStrict.java:36]: @mohitsatr , please make one more version of this block with indenation 16 and we should see no violations on such lines.

We need to show by example that user request is addressed and work in both ways.
please do the same for `isWeekDay` to show that if user follow reported expectations, there will be no violations.

**Review by romani — CHANGES_REQUESTED** [review]
items:

**Review by romani — APPROVED** [review]
good to merge !!

thanks a lot !

**Comment by nrmancuso** [comment]
@romani please reply to comment at https://github.com/checkstyle/checkstyle/pull/16131#issuecomment-2586057373

@mohitsatr please rebase on the latest master branch

**Comment by romani** [comment]
yes, lets create separate issue on this case, we can improve lateron on this.

**Comment by mohitsatr** [comment]
> lets create separate issue on this case

That case existed even before the new changes. With these changes, we’ve just replaced one incorrect message with another. We can leave it as it is for now. If anyone encounters a problem, they can raise the issue. what do you think ?

**Comment by romani** [comment]
I am ok to not create issue

**Comment by romani** [comment]
Github, generate report for Indentation/all-examples-in-one

**Review by nrmancuso — APPROVED** [review]
Let’s do it
