### PR TITLE
Issue #6988: Sort XPath Results in Document Order

### LINKED ISSUE #6988: Xpath results are not sorted in document order
Current xpath implementation works well (I hope:) ), but I faced one problem, 
When you want to access xpath results by index `[index]` and you care about ordering of the results, but results are sorted in alphabetic order. Logically results should ordered as they appear in document

**XML Path Language (XPath)** [link](https://www.w3.org/TR/1999/REC-xpath-19991116/#dt-document-order)

> There is an ordering, document order, defined on all the nodes in the document corresponding to the order in which the first character of the XML representation of each node occurs in the XML representation of the document after expansion of general entities. Thus, the root node will be the first node. Element nodes occur before their children. Thus, document order orders element nodes in order of the occurrence of their start-tag in the XML (after expansion of entities). The attribute nodes and namespace nodes of an element occur before the children of the element. The namespace nodes are defined to occur before the attribute nodes. The relative order of namespace nodes is implementation-dependent. The relative order of attribute nodes is implementation-dependent. Reverse document order is the reverse of document order.

**XSLT 2.0 and XPath 2.0 Programmer's Reference by Michael Kay, page 492**

> The nodes in a sequence can always be sorted into document order. For elements from the same document, document order is the same as the order of the start tags in the original source. In terms of the tree structure, a node is ordered after its preceding siblings, and these are ordered after their parent node.

The following test demonstrates such situation with sorting and indexing

Example
```
/var/tmp $ cat InputXpathMapperAst.java
package com.puppycrawl.tools.checkstyle.xpath.xpathmapper;

public class InputXpathMapperAst {

    /**
     * Returns if current node has children.
     * @return if current node has children
     */
    public void callSomeMethod() {
        int variable = 123;
        String another = "HelloWorld";
        String[] array = new String[3];
        for (String cycle : array) {

        }
    }

    /**
     * Returns if current node has children.
     * @return if current node has children
     */
    public String getSomeMethod() {
        return "HelloWorld";
    }
}
```
```
/var/tmp $ java -jar checkstyle-8.24-SNAPSHOT-all.jar -J InputXpathMapperAst.java
...
    |   `--SLIST -> { [9:33]
    |       |--VARIABLE_DEF -> VARIABLE_DEF [10:8]
    |       |   |--MODIFIERS -> MODIFIERS [10:8]
    |       |   |--TYPE -> TYPE [10:8]
    |       |   |   `--LITERAL_INT -> int [10:8]
    |       |   |--IDENT -> variable [10:12]
    |       |   `--ASSIGN -> = [10:21]
    |       |       `--EXPR -> EXPR [10:23]
    |       |           `--NUM_INT -> 123 [10:23]
    |       |--SEMI -> ; [10:26]
    |       |--VARIABLE_DEF -> VARIABLE_DEF [11:8]
    |       |   |--MODIFIERS -> MODIFIERS [11:8]
    |       |   |--TYPE -> TYPE [11:8]
    |       |   |   `--IDENT -> String [11:8]
    |       |   |--IDENT -> another [11:15]
    |       |   `--ASSIGN -> = [11:23]
    |       |       `--EXPR -> EXPR [11:25]
    |       |           `--STRING_LITERAL -> "HelloWorld" [11:25]
    |       |--SEMI -> ; [11:37]
    |       |--VARIABLE_DEF -> VARIABLE_DEF [12:14]
    |       |   |--MODIFIERS -> MODIFIERS [12:14]
    |       |   |--TYPE -> TYPE [12:14]
    |       |   |   `--ARRAY_DECLARATOR -> [ [12:14]
    |       |   |       |--IDENT -> String [12:8]
    |       |   |       `--RBRACK -> ] [12:15]
    |       |   |--IDENT -> array [12:17]
    |       |   `--ASSIGN -> = [12:23]
    |       |       `--EXPR -> EXPR [12:25]
    |       |           `--LITERAL_NEW -> new [12:25]
    |       |               |--IDENT -> String [12:29]
    |       |               `--ARRAY_DECLARATOR -> [ [12:35]
    |       |                   |--EXPR -> EXPR [12:36]
    |       |                   |   `--NUM_INT -> 3 [12:36]
    |       |                   `--RBRACK -> ] [12:37]
    |       |--SEMI -> ; [12:38]
    |       |--LITERAL_FOR -> for [13:8]
    |       |   |--LPAREN -> ( [13:12]
    |       |   |--FOR_EACH_CLAUSE -> FOR_EACH_CLAUSE [13:13]
    |       |   |   |--VARIABLE_DEF -> VARIABLE_DEF [13:13]
    |       |   |   |   |--MODIFIERS -> MODIFIERS [13:13]
    |       |   |   |   |--TYPE -> TYPE [13:13]
    |       |   |   |   |   `--IDENT -> String [13:13]
    |       |   |   |   `--IDENT -> cycle [13:20]
    |       |   |   |--COLON -> : [13:26]
    |       |   |   `--EXPR -> EXPR [13:28]
    |       |   |       `--IDENT -> array [13:28]
    |       |   |--RPAREN -> ) [13:33]
    |       |   `--SLIST -> { [13:35]
    |       |       `--RCURLY -> } [15:8]
    |       `--RCURLY -> } [16:4]
...

```

XpathMapperTest
```
@Test
public void testOrdering() throws Exception {
    final String xpath = 
       "(//METHOD_DEF[./IDENT[@text='callSomeMethod']]/SLIST/*)[1]";
    final RootNode rootNode = getRootNode("InputXpathMapperAst.java");
    final DetailAST[] actual = convertToArray(getXpathItems(xpath, rootNode));
    final DetailAST expectedVariableDefNode = getSiblingByType(
           rootNode.getUnderlyingNode(), TokenTypes.CLASS_DEF)
            .findFirstToken(TokenTypes.OBJBLOCK)
            .findFirstToken(TokenTypes.METHOD_DEF)
            .findFirstToken(TokenTypes.SLIST)
            .getFirstChild();
    final DetailAST[] expected = {expectedVariableDefNode};
    assertArrayEquals("Result nodes differ from expected", expected, actual);
}
```

As you can see first result must be `VARIABLE_DEF [10:8]`, because it appears earlier in document
But our xpath returns `for [13:8]`, simply because of lexicographic order

I think problem is in [here](https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/xpath/AbstractNode.java#L147), maybe this method should be rewritten based on line/column and tree level
```
 @Override
    public int compareOrder(NodeInfo nodeInfo) {
        return getLocalPart().compareTo(nodeInfo.getLocalPart());
    }
```

@rnveach @romani

### PR DESCRIPTION
**Pull request by gaurabdg**
Resolves #6988 

Extending the work and implementing @rnveach's sort criteria discussed in PR #7485.
Example from: https://github.com/checkstyle/checkstyle/pull/7485#discussion_r373855071

```
$ cat test.java

public class test {
    void method() {
    }
}
```
Before:
```
$  java -jar checkstyle-8.29-all.jar -b "//CLASS_DEF/*" test.java 
CLASS_DEF -> CLASS_DEF [1:0]
|--IDENT -> test [1:13]
---------
CLASS_DEF -> CLASS_DEF [1:0]
|--LITERAL_CLASS -> class [1:7]
---------
CLASS_DEF -> CLASS_DEF [1:0]
|--MODIFIERS -> MODIFIERS [1:0]
---------
CLASS_DEF -> CLASS_DEF [1:0]
`--OBJBLOCK -> OBJBLOCK [1:18]
```
After:
```
$ java -jar checkstyle-8.31-SNAPSHOT-all.jar -b "//CLASS_DEF/*" test.java
CLASS_DEF -> CLASS_DEF [1:0]
|--MODIFIERS -> MODIFIERS [1:0]
---------
CLASS_DEF -> CLASS_DEF [1:0]
|--LITERAL_CLASS -> class [1:7]
---------
CLASS_DEF -> CLASS_DEF [1:0]
|--IDENT -> test [1:13]
---------
CLASS_DEF -> CLASS_DEF [1:0]
`--OBJBLOCK -> OBJBLOCK [1:18]
```
Diff Report: https://gaurabdg.github.io/checkstyle-tester-reports/regression/XPathSort/diff/

### CODE REVIEW

**Comment by romani** [comment]
@timurt , please review first

**Comment by gaurabdg** [comment]
@timurt @rnveach Can you please review it? Thanks.

File: src/main/java/com/puppycrawl/tools/checkstyle/xpath/ElementNode.java [hunk 1]
```diff
@@ -81,6 +81,23 @@ public ElementNode(AbstractNode root, AbstractNode parent, DetailAST detailAst)
         createChildren();
     }
 
+    /**
+     * Compares current object with specified for order.
+     * @param other another {@code NodeInfo} object
+     * @return number representing order of current object to specified one
+     */
+    @Override
+    public int compareOrder(NodeInfo other) {
```
Comment (rnveach) [inline src/main/java/com/puppycrawl/tools/checkstyle/xpath/ElementNode.java]: @gaurabdg @timurt How often is `compareOrder` called for different queries? Is it a big impact that we have to calculate the depth each time it is called?

File: src/main/java/com/puppycrawl/tools/checkstyle/xpath/ElementNode.java [hunk 2]
```diff
@@ -81,6 +81,23 @@ public ElementNode(AbstractNode root, AbstractNode parent, DetailAST detailAst)
...
+        int result = 0;
+        if (other != null) {
+            result = getRootDepth(this) - getRootDepth(other);
+        }
+        if (result == 0 && other instanceof ElementNode) {
```
Comment (rnveach) [inline src/main/java/com/puppycrawl/tools/checkstyle/xpath/ElementNode.java]: Shouldn't this line be part of `if (other != null) {`?

File: src/test/java/com/puppycrawl/tools/checkstyle/xpath/ElementNodeTest.java [hunk 3]
```diff
@@ -58,6 +58,14 @@ public void init() throws Exception {
         rootNode = new RootNode(rootAst);
     }
 
+    @Test
+    public void testCompareOrderWrongInstance() throws Exception {
+        final String xpath = "//OBJBLOCK";
+        final List<NodeInfo> nodes = getXpathItems(xpath, rootNode);
+        final int result = nodes.get(0).compareOrder(null);
```
Comment (rnveach) [inline src/test/java/com/puppycrawl/tools/checkstyle/xpath/ElementNodeTest.java]: Why is there a check for `null`? Does this not happen naturally?

File: src/main/java/com/puppycrawl/tools/checkstyle/xpath/ElementNode.java (hunk 1 above)
Comment (gaurabdg) [reply src/main/java/com/puppycrawl/tools/checkstyle/xpath/ElementNode.java]: @rnveach I can kind of cache the depth value for each node, as the two compared nodes least common ancestor is very near(because this ordering is required for xpath queries for nearby nodes mostly)  and will save a lot of computations.

File: src/main/java/com/puppycrawl/tools/checkstyle/xpath/ElementNode.java (hunk 2 above)
Comment (gaurabdg) [reply src/main/java/com/puppycrawl/tools/checkstyle/xpath/ElementNode.java]: Spotbugs gave a warning for unchecked casting for that line, so to resolve that I put the check just before that, but I'll put them together now.

File: src/test/java/com/puppycrawl/tools/checkstyle/xpath/ElementNodeTest.java (hunk 3 above)
Comment (gaurabdg) [reply src/test/java/com/puppycrawl/tools/checkstyle/xpath/ElementNodeTest.java]: No, naturally such a case doesn't arise, so this was added to achieve 100% branch coverage.

File: src/main/java/com/puppycrawl/tools/checkstyle/xpath/ElementNode.java (hunk 2 above)
Comment (gaurabdg) [reply src/main/java/com/puppycrawl/tools/checkstyle/xpath/ElementNode.java]: done

File: src/main/java/com/puppycrawl/tools/checkstyle/xpath/ElementNode.java (hunk 1 above)
Comment (gaurabdg) [reply src/main/java/com/puppycrawl/tools/checkstyle/xpath/ElementNode.java]: Done

**Comment by gaurabdg** [comment]
@rnveach `if (parentDepth == -1)` is having a survived mutation of `removed conditional - replaced equality check with true → SURVIVED`.
The `if` statement only speeds up the process of depth calculation by checking if the parent nodes depth already has been calculated and using that result instead of computing the depth again in a brute force manner.
So, the reason of the surviving mutation is that the check doesn't break the code since the output will be the same if the mutation is hardcoded with always `true` as it only **_speeds_** up the computation, not alter the logic.

So I am adding it to the ignored list to pass the build

File: src/test/java/com/puppycrawl/tools/checkstyle/xpath/ElementNodeTest.java (hunk 3 above)
Comment (rnveach) [reply src/test/java/com/puppycrawl/tools/checkstyle/xpath/ElementNodeTest.java]: If `null` isn't natural and doc doesn't say it can send a null then why do we have a check for it. I assume the branch was the null check? If it can never be null then the check is pointless and can be removed.

File: .ci/pitest.sh [hunk 4]
```diff
@@ -215,6 +215,14 @@ pitest-utils)
   checkPitestReport "${ignoredItems[@]}"
   ;;
 
+pitest-xpath)
+  mvn -e -P$1 clean test org.pitest:pitest-maven:mutationCoverage;
+  declare -a ignoredItems=(
+  "ElementNode.java.html:<td class='covered'><pre><span  class='survived'>            if (parentDepth == -1) {</span></pre></td></tr>"
```
Comment (rnveach) [inline .ci/pitest.sh]: We are not expecting new items as we are trying to shrink the list. Let me review this before giving more guidance.

File: src/main/java/com/puppycrawl/tools/checkstyle/xpath/ElementNode.java (hunk 1 above)
Comment (rnveach) [reply src/main/java/com/puppycrawl/tools/checkstyle/xpath/ElementNode.java]: So I was right with my concern that it is called many times for 1 query?

File: .ci/pitest.sh (hunk 4 above)
Comment (rnveach) [reply .ci/pitest.sh]: > removed conditional - replaced equality check with true → SURVIVED.

Just on the face, it looks like our tests don't see the benefit of the cache and goes back to directly recounting all the nodes. I don't see any way to make this matter under a normal condition. You will need to create a test specifically for this. Like make 2 nodes, have the parent node have a depth of 9 and count the depth of the child. Since there are only 2 nodes, it will have a count of 2 if recounted, but the actual count will be 10.

File: src/main/java/com/puppycrawl/tools/checkstyle/xpath/ElementNode.java (hunk 1 above)
Comment (gaurabdg) [reply src/main/java/com/puppycrawl/tools/checkstyle/xpath/ElementNode.java]: Yes, it will be called for each xpath result ordering

File: src/test/java/com/puppycrawl/tools/checkstyle/xpath/ElementNodeTest.java (hunk 3 above)
Comment (gaurabdg) [reply src/test/java/com/puppycrawl/tools/checkstyle/xpath/ElementNodeTest.java]: the `if (other instanceof ElementNode)` is required by Spotbugs otherwise it will throw an `unchecked cast` error for `((ElementNode) other).indexAmongSiblings`. So, I have replaced `null` with `rootNode` object instead to fail it and cover the branch.

Comment (gaurabdg) [reply src/test/java/com/puppycrawl/tools/checkstyle/xpath/ElementNodeTest.java]: Done

File: .ci/pitest.sh (hunk 4 above)
Comment (gaurabdg) [reply .ci/pitest.sh]: Done, created a new UT.

**Comment by gaurabdg** [comment]
@romani @timurt @rnveach please review

**Comment by rnveach** [comment]
@timurt ping

**Comment by gaurabdg** [comment]
@timurt sir, can you please review? Thanks.

**Comment by timurt** [comment]
@gaurabdg
sorry, forget to submit review, please see my comments

File: src/main/java/com/puppycrawl/tools/checkstyle/xpath/ElementNode.java [hunk 5]
```diff
@@ -75,12 +78,30 @@ public ElementNode(AbstractNode root, AbstractNode parent, DetailAST detailAst)
         this.parent = parent;
         this.root = root;
         this.detailAst = detailAst;
+        nodeDepth = -1;
```
[the remark this answers is not in the document]
Comment (gaurabdg) [reply src/main/java/com/puppycrawl/tools/checkstyle/xpath/ElementNode.java]: @timurt @rnveach I didn't know whether to touch other modules or not. It can be done and will be more efficient. So, shall I create a `depth` attribute of `DetailASTImpl` class and pass on `this.depth + 1` while creating child nodes? Let me know what should be done, meanwhile I'll add the tests

[the remark this answers is not in the document]
Comment (timurt) [reply src/main/java/com/puppycrawl/tools/checkstyle/xpath/ElementNode.java]: @rnveach @gaurabdg 
No, I am saying about creating `depth` attribute for `AbstractNode` class, 
So my suggestion is to initialize `depth` attribute during Xpath tree creation process instead of lazy calculations. 

For example constructor of the `ElementNode` could be smth like
```
 public ElementNode(AbstractNode root, AbstractNode parent, DetailAST detailAst) {
        super(root.getTreeInfo());
        this.parent = parent;
        this.root = root;
        this.detailAst = detailAst;
        this.nodeDepth = parent.nodeDepth + 1; // <-- You can use parent's height
        text = TokenUtil.getTokenName(detailAst.getType());
        indexAmongSiblings = parent.getChildren().size();
        createTextAttribute();
        createChildren();
    }
```

Xpath tree construction is recursive DFS, so height of every child of the node is larger by one than the parent height

What do you think about it?

[the remark this answers is not in the document]
Comment (gaurabdg) [reply src/main/java/com/puppycrawl/tools/checkstyle/xpath/ElementNode.java]: @timurt I understand what you are saying and also agree. But the tree contruction is happening and being returned as `DetailAST` right? So, `the depth+1` passing needs to happen there.
Also, while recursively browsing the code for tree generation I see the `RootNode` is being passed on to here, at `XPathUtil`
```
    /**
     * Returns xpath query results on file as string.
     *
     * @param xpath query to evaluate
     * @param file file to run on
     * @return all results as string separated by delimiter
     * @throws CheckstyleException if some parsing error happens
     * @throws IOException if an error occurs
     */
    public static String printXpathBranch(String xpath, File file) throws CheckstyleException,
            IOException {
        final XPathEvaluator xpathEvaluator = new XPathEvaluator();
        try {
            final RootNode rootNode = new RootNode(JavaParser.parseFile(file,
                JavaParser.Options.WITH_COMMENTS));
            final XPathExpression xpathExpression = xpathEvaluator.createExpression(xpath);
            final XPathDynamicContext xpathDynamicContext =
                xpathExpression.createDynamicContext(rootNode);
            final List<Item<?>> matchingItems = xpathExpression.evaluate(xpathDynamicContext);
            return matchingItems.stream()
                .map(item -> ((AbstractNode) item).getUnderlyingNode())
                .map(AstTreeStringPrinter::printBranch)
                .collect(Collectors.joining(DELIMITER));
        }
        catch (XPathException ex) {
            final String errMsg = String.format(Locale.ROOT,
                "Error during evaluation for xpath: %s, file: %s", xpath, file.getCanonicalPath());
            throw new CheckstyleException(errMsg, ex);
        }
    }
```
So, is the tree is gettng created by the saxon libraries? It would be really helpful if you could tell me about the tree creation flow.

[the remark this answers is not in the document]
Comment (timurt) [reply src/main/java/com/puppycrawl/tools/checkstyle/xpath/ElementNode.java]: @gaurabdg 
We have two trees:
- one is AST tree with `DetailAST` objects, used by almost all checks to validate rules
- another one is Xpath tree with classes implementing `NodeInfo`(*saxon*) interface, this tree is used only for querying nodes using xpath queries

Xpath tree nodes have reference to corresponding AST tree nodes

Construction of the xpath tree starts with `RootNode`, as argument `RootNode` constructor takes root `DetailAst` object, and recursively traverse AST tree and creates corresponding Xpath nodes

For example for `SuppressionXpathFilter`, we create `RootNode` [here](https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/filters/XpathFilterElement.java#L235), 
Violation event [TreeWalkerAuditEvent](https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/TreeWalkerAuditEvent.java#L49) itself contains reference to `rootAst`, so we can create Xpath tree from it

is it clear? I know it is not obvious, so please ask questions

[the remark this answers is not in the document]
Comment (gaurabdg) [reply src/main/java/com/puppycrawl/tools/checkstyle/xpath/ElementNode.java]: @timurt Thanks a lot for clarifying. I will ask as and when required while implementing the new approach.

File: src/test/java/com/puppycrawl/tools/checkstyle/xpath/XpathMapperTest.java [hunk 6]
```diff
@@ -946,7 +946,7 @@ public void testQueryElementPrecedingTwo() throws Exception {
         final DetailAST expectedPackageDefNode = getSiblingByType(rootNode.getUnderlyingNode(),
                 TokenTypes.PACKAGE_DEF);
         final DetailAST expectedAnnotationsNode = expectedPackageDefNode.getFirstChild();
-        final DetailAST[] expected = {expectedAnnotationsNode, expectedPackageDefNode};
+        final DetailAST[] expected = {expectedPackageDefNode, expectedAnnotationsNode};
         assertThat("Result nodes differ from expected", actual, equalTo(expected));
     }
```
[the remark this answers is not in the document]
Comment (gaurabdg) [reply src/test/java/com/puppycrawl/tools/checkstyle/xpath/XpathMapperTest.java]: @timurt Many such document order tests are present in `XpathMapperTest`. Do we still need to add tests here?

[the remark this answers is not in the document]
Comment (timurt) [reply src/test/java/com/puppycrawl/tools/checkstyle/xpath/XpathMapperTest.java]: @gaurabdg yes,
this test should be a little bit different than the other ones, 

This test should query many results (you can achieve that using `*` in your xpath query) and then check that all results are sorted in document order

You can ignore token types of the results, but check their line and column numbers are in increasing sequence

Something like this
```
        final DetailAST[] actual = convertToArray(getXpathItems(xpath, rootNode));
        for (int i = 1; i < actual.length; i++) {
            final DetailAST current = actual[i];
            final DetailAST previous = actual[i - 1];

            assertWithMessage("Line number is not in document order")
                    .that(previous.getLineNo())
                    .isGreaterThan(current.getLineNo());

            if (current.getLineNo() == previous.getLineNo()) {
                assertWithMessage("Column number is not in document order")
                        .that(previous.getColumnNo())
                        .isLessThan(current.getColumnNo());
            }
        }
```

File: src/test/java/com/puppycrawl/tools/checkstyle/xpath/ElementNodeTest.java [hunk 7]
```diff
@@ -58,6 +58,14 @@ public void init() throws Exception {
...
+        assertEquals(0, result, "Expected result wrong");
+    }
+
```
[the remark this answers is not in the document]
Comment (gaurabdg) [reply src/test/java/com/puppycrawl/tools/checkstyle/xpath/ElementNodeTest.java]: @timurt what is the second test exactly?
I added an ordering test like this, as you requested:
```
    @Test
    public void testNodeOrdering() throws Exception {
        final String xpath = "//METHOD_DEF[./IDENT[@text='callSomeMethod']]/SLIST/*";
        final List<NodeInfo> nodes = getXpathItems(xpath, rootNode);
        boolean result = nodes
                .stream()
                .sorted(NodeInfo::compareOrder)
                .collect(Collectors.toList())
                .equals(nodes);
        assertTrue(result, "Ordering Incorrect");
    }
```
Let me know if theres anything else to add.

[the remark this answers is not in the document]
Comment (timurt) [reply src/test/java/com/puppycrawl/tools/checkstyle/xpath/ElementNodeTest.java]: @gaurabdg 
tests to cover different cases for `compareOrder` method
Smth like:

1. compare order between parent node and child node
```
ElementNode parent = ...
ElementNode child = ..
assertEquals(-*x*, parent.compareTo(child));
assertEquals(*x*, child.compareTo(parent));
```

2. compare order between two sibling nodes of same parent node
```
ElementNode parent = ...
ElementNode childOne = ...
ElementNode childTwo = ...
assertEquals(-*x*, childOne.compareTo(childTwo));
assertEquals(*x*, childTwo.compareTo(childOne));
```

[the remark this answers is not in the document]
Comment (gaurabdg) [reply src/test/java/com/puppycrawl/tools/checkstyle/xpath/ElementNodeTest.java]: Okay, siblings one is done in the example provided. I'll create the parent-child test

**Comment by gaurabdg** [comment]
@timurt Made all changes requested by you. Please review.

File: src/test/java/com/puppycrawl/tools/checkstyle/xpath/ElementNodeTest.java [hunk 8]
```diff
@@ -58,6 +59,61 @@ public void init() throws Exception {
         rootNode = new RootNode(rootAst);
     }
 
+    @Test
+    public void testNodeOrdering() throws Exception {
```
Comment (timurt) [inline src/test/java/com/puppycrawl/tools/checkstyle/xpath/ElementNodeTest.java]: I am not sure `ElementNodeTest` is appropriate class for this method, please move it to `XpathMapperTest`

File: src/test/java/com/puppycrawl/tools/checkstyle/xpath/ElementNodeTest.java [hunk 9]
```diff
@@ -58,6 +59,61 @@ public void init() throws Exception {
...
+        final String xpath = "//METHOD_DEF[./IDENT[@text='callSomeMethod']]/SLIST/*";
+        final List<NodeInfo> nodes = getXpathItems(xpath, rootNode);
+        final boolean result = nodes
```
Comment (timurt) [inline src/test/java/com/puppycrawl/tools/checkstyle/xpath/ElementNodeTest.java]: I executed this test with different `compareOrder` method implementation, it always passes, it is not ok

As far as I understand this `depth` approach, it should be fully correlate with line/column ordering. 
It means for all nodes in `getXpathItems(xpath, rootNode);` the following condition is true:
`node[i].lineNumber < node[j].lineNumber or (node[i].lineNumber = node[j].lineNumber and node[i].columnNumber < node[j].columnNumber)` where *i < j*.
It is easier to write because all `NodeInfo` subclasses implement `getLineNumber(), getColumnNumber()` using real `DetailAst` values.

There is more difficult way to write this test:
- get results from `getXpathItems(xpath, rootNode);`
- convert them to `DetailAST[]` using `convertToArray(List<NodeInfo> nodes)` method
- get `rootAst` from `RootNode` 
- traverse `rootAst` with DFS and check that all elements `DetailAST[]` appear in exact same order

Comment (gaurabdg) [reply src/test/java/com/puppycrawl/tools/checkstyle/xpath/ElementNodeTest.java]: Okay, I'll make the changes

**Comment by gaurabdg** [comment]
@timurt @romani Please review

File: src/test/java/com/puppycrawl/tools/checkstyle/xpath/XpathMapperTest.java [hunk 10]
```diff
@@ -45,6 +48,65 @@ protected String getPackageLocation() {
...
+            else {
+                assertWithMessage("Line number is not in document order")
+                    .that(curr.getLineNumber())
+                    .isGreaterThan(prev.getLineNumber());
+            }
+        }
+    }
+
+    @Test
+    public void testParentChildOrdering() throws Exception {
```
Comment (timurt) [inline src/test/java/com/puppycrawl/tools/checkstyle/xpath/XpathMapperTest.java]: @gaurabdg 
`XpathMapperTest` should contain tests those test different xpath queries, like you did in `testNodeOrdering()`

Here you test `compareOrder` method of `ElementNode` class and there is no xpath query, so I would suggest to move this test to `ElementNodeTest`

File: src/test/java/com/puppycrawl/tools/checkstyle/xpath/XpathMapperTest.java [hunk 11]
```diff
@@ -45,6 +48,65 @@ protected String getPackageLocation() {
...
+        parentAST.setType(TokenTypes.METHOD_DEF);
+
+        final AbstractNode parentNode = new ElementNode(rootNode, rootNode, parentAST);
+        final AbstractNode childNode = new ElementNode(rootNode, parentNode, detailAST);
+        assertEquals(-1, parentNode.compareOrder(childNode), "Incorrect ordering value");
+        assertEquals(1, childNode.compareOrder(parentNode), "Incorrect ordering value");
+    }
+
+    @Test
+    public void testSiblingsOrdering() throws Exception {
```
Comment (timurt) [inline src/test/java/com/puppycrawl/tools/checkstyle/xpath/XpathMapperTest.java]: same here

File: src/test/java/com/puppycrawl/tools/checkstyle/xpath/XpathMapperTest.java (hunk 10 above)
Comment (gaurabdg) [reply src/test/java/com/puppycrawl/tools/checkstyle/xpath/XpathMapperTest.java]: Okay, sure

File: src/test/java/com/puppycrawl/tools/checkstyle/xpath/XpathMapperTest.java (hunk 11 above)
Comment (gaurabdg) [reply src/test/java/com/puppycrawl/tools/checkstyle/xpath/XpathMapperTest.java]: Done, @timurt please review

**Comment by gaurabdg** [comment]
@timurt Can you help with the wercker build error?

**Comment by timurt** [comment]
@gaurabdg 

> Can you help with the wercker build error?

As far as I know problem is on `master` branch. Please wait until issue resolved and then rebase on updated `master`

**Comment by gaurabdg** [comment]
@timurt What should be done next?

**Comment by timurt** [comment]
@rnveach please review

File: src/test/java/com/puppycrawl/tools/checkstyle/xpath/XpathMapperTest.java [hunk 12]
```diff
@@ -45,6 +46,28 @@ protected String getPackageLocation() {
         return "com/puppycrawl/tools/checkstyle/xpath/xpathmapper";
     }
 
+    @Test
+    public void testNodeOrdering() throws Exception {
+        final String xpath = "//METHOD_DEF[./IDENT[@text='callSomeMethod']]/SLIST/*";
```
Comment (pbludov) [inline src/test/java/com/puppycrawl/tools/checkstyle/xpath/XpathMapperTest.java:51]: This test fails for the xpath "//METHOD_DEF/SLIST/*"

File: src/main/java/com/puppycrawl/tools/checkstyle/xpath/ElementNode.java (hunk 1 above)
Comment (pbludov) [reply src/main/java/com/puppycrawl/tools/checkstyle/xpath/ElementNode.java:91]: The order of cousins will be wrong. Consider
```
CLASS_DEF
   METHOD_DEF1
       VARIABLE_DEF1-1
       VARIABLE_DEF1-2
   METHOD_DEF2
       VARIABLE_DEF2-1
       VARIABLE_DEF2-2
```
The list of nodes for the xpath "//VARIABLE_DEF" will be VARIABLE_DEF1-1, VARIABLE_DEF2-1,VARIABLE_DEF2-2,VARIABLE_DEF1-2.

We still need some sort of recursion here. When the `depth` is different, the result is clear.
When the `depth` matches, there should be a check for order for the parent nodes (in case both nodes do not belong to the same parent).

File: src/test/java/com/puppycrawl/tools/checkstyle/xpath/XpathMapperTest.java (hunk 12 above)
Comment (gaurabdg) [reply src/test/java/com/puppycrawl/tools/checkstyle/xpath/XpathMapperTest.java:51]: Yes, you are right, I'll revert back to the recursion routine.

Comment (pbludov) [reply src/test/java/com/puppycrawl/tools/checkstyle/xpath/XpathMapperTest.java:51]: How about more depth?
```
CLASS_DEF0
  CLASS_DEF1
     METHOD_DEF1-1
         VARIABLE_DEF1-1-1
         VARIABLE_DEF1-1-2
     METHOD_DEF1-2
         VARIABLE_DEF1-2-1
         VARIABLE_DEF1-2-2
  CLASS_DEF2
     METHOD_DEF2-1
         VARIABLE_DEF2-1-1
         VARIABLE_DEF2-1-2
     METHOD_DEF2-2
         VARIABLE_DEF2-2-1
         VARIABLE_DEF2-2-2
```
Now all `VARIABLE_DEF`s are on 4th depth, their parents on 3rd depth.
We can not just compare order of `METHOD_DEF`s, we should go up till a common parent node.

Comment (gaurabdg) [reply src/test/java/com/puppycrawl/tools/checkstyle/xpath/XpathMapperTest.java]: @pbludov When the depth is same I have computed their common ancestor's `indexAmongSiblings`. Since the children to be compared are at the same level each call will have a time complexity of `O(heightOfTree)` i.e., logarithmic time and hence won't be much heavy.

Comment (gaurabdg) [reply src/test/java/com/puppycrawl/tools/checkstyle/xpath/XpathMapperTest.java]: @pbludov Please review.

Comment (gaurabdg) [reply src/test/java/com/puppycrawl/tools/checkstyle/xpath/XpathMapperTest.java]: > How about more depth?
> 
> ```
> CLASS_DEF0
>   CLASS_DEF1
>      METHOD_DEF1-1
>          VARIABLE_DEF1-1-1
>          VARIABLE_DEF1-1-2
>      METHOD_DEF1-2
>          VARIABLE_DEF1-2-1
>          VARIABLE_DEF1-2-2
>   CLASS_DEF2
>      METHOD_DEF2-1
>          VARIABLE_DEF2-1-1
>          VARIABLE_DEF2-1-2
>      METHOD_DEF2-2
>          VARIABLE_DEF2-2-1
>          VARIABLE_DEF2-2-2
> ```
> 
> Now all `VARIABLE_DEF`s are on 4th depth, their parents on 3rd depth.
> We can not just compare order of `METHOD_DEF`s, we should go up till a common parent node.

Yes, I realized this case and deleted my comment just after a while and implemented this way.

**Comment by rnveach** [comment]
@timurt 
> @rnveach please review

PR is still assigned to you and you have no approved PR. Is there something blocking you or are you done? In that case, you should approve the PR and assign it to me.

**Comment by timurt** [comment]
@rnveach I approved and assigned to you, sorry

File: src/main/java/com/puppycrawl/tools/checkstyle/xpath/ElementNode.java [hunk 13]
```diff
@@ -77,10 +77,45 @@ public ElementNode(AbstractNode root, AbstractNode parent, DetailAST detailAst)
...
+    /**
+     * Compares current object with specified for order.
+     * @param other another {@code NodeInfo} object
+     * @return number representing order of current object to specified one
+     */
+    @Override
+    public int compareOrder(NodeInfo other) {
+        int result = 0;
+        if (other instanceof ElementNode) {
+            result = getDepth() - ((AbstractNode) other).getDepth();
```
Comment (rnveach) [inline src/main/java/com/puppycrawl/tools/checkstyle/xpath/ElementNode.java:94]: We check instance to be ElementNode but do a cast to AbstractNode. Shouldn't both be the same class?

Comment (gaurabdg) [reply src/main/java/com/puppycrawl/tools/checkstyle/xpath/ElementNode.java]: @rnveach Yes, you are right, I forgot to change after a few changes in other code.
I've corrected it.

Comment (rnveach) [reply src/main/java/com/puppycrawl/tools/checkstyle/xpath/ElementNode.java]: @gaurabdg It looks like IntelliJ wants both to be `AbstractNode`. I don't see any parts of the code requiring it be `ElementNode`.
https://teamcity.jetbrains.com/viewLog.html?buildId=2866738&tab=Inspection&buildTypeId=Checkstyle_IdeaInspectionsPullRequest

Comment (gaurabdg) [reply src/main/java/com/puppycrawl/tools/checkstyle/xpath/ElementNode.java]: Done.

**Comment by rnveach** [comment]
@gaurabdg please run `mvn verify` before pushing. CI is still failing,
> [checkstyle] [ERROR] /home/travis/build/checkstyle/checkstyle/src/main/java/com/puppycrawl/tools/checkstyle/xpath/ElementNode.java:27:8: Unused import - net.sf.saxon.functions.Abs. [UnusedImports]

**Comment by gaurabdg** [comment]
> @gaurabdg please run `mvn verify` before pushing. CI is still failing,
> 
> > [checkstyle] [ERROR] /home/travis/build/checkstyle/checkstyle/src/main/java/com/puppycrawl/tools/checkstyle/xpath/ElementNode.java:27:8: Unused import - net.sf.saxon.functions.Abs. [UnusedImports]
> 
> and pitest
> 
> > `+AbstractNode.java.html:<td class='uncovered'><pre><span  class='survived'>        return getLocalPart().compareTo(nodeInfo.getLocalPart());</span></pre></td></tr>`

I am extremely sorry, I did it in a hurry.
