### PR TITLE
Issue #15159: RedundantModifierCheck should violate final modifier on…

### LINKED ISSUE #15159: RedundantModifer Should Violate Final Modifer on Unnamed Variables if jdkVersion GTE 22
child of #14942 

Check documentation: https://checkstyle.org/checks/modifier/redundantmodifier.html#RedundantModifier

---

```
PS D:\CS\test> cat config.xml
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
          "-//Checkstyle//DTD Checkstyle Configuration 1.3//EN"
          "https://checkstyle.org/dtds/configuration_1_3.dtd">

<module name="Checker">
  <module name="TreeWalker">
    <module name="RedundantModifier"/>
    <property name="jdkVersion" value="21"/>
  </module>
</module>
PS D:\CS\test> cat src/Test.java
public class Test {
    void m(Object o) throws Exception {
        try (final var a = lock()) {  // violation , resource is effective final
        }

        if (o instanceof R(final int _)) { // expected violation, unnamed pattern variable is effective final

        }

        final int _ = sideEffect(); // expected violation, unnamed variable is effective final
    }
    AutoCloseable lock() { return null; }
    record R(int x) { }
    int sideEffect() { return 0; }
}
PS D:\CS\test> java  -jar checkstyle-10.17.0-all.jar -c config.xml  src/Test.java                                           
Starting audit...
[ERROR] D:\CS\test\src\Test.java:3:14: Redundant 'final' modifier. [RedundantModifier]
Audit done.
Checkstyle ends with 1 errors.
PS D:\CS\test> 
```

---

[JLS](https://docs.oracle.com/javase/specs/jls/se22/html/jls-6.html#jls-6.3) :

> If a declaration does not include an identifier, but instead includes the keyword _ (underscore), then the entity cannot be referred to by name. The following kinds of entity may be declared using an underscore:

Like resources, unnamed variables are effectively final which means that whether the unnamed variable has final modifier or not. the variable can't be reassigned. I expect a violation on the redundant modifer check on unnamed variables.

---
**Describe what you want in detail.**

We should update `RedundantModifer`  to violate the `final` modifier on unnamed variables if `jdkVersion` is >= 22. If a user is on old Java versions (below Java 9). the final modifier will not be redundant because `_` is a normal identifier in this case. 

Example:

```
PS D:\CS\test> cat config.xml
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
          "-//Checkstyle//DTD Checkstyle Configuration 1.3//EN"
          "https://checkstyle.org/dtds/configuration_1_3.dtd">

<module name="Checker">
  <module name="TreeWalker">
    <module name="RedundantModifier"/>
    <property name="jdkVersion" value="8"/>
  </module>
</module>
PS D:\CS\test> cat src/Test.java
public class Test {
    void m(Object o) throws Exception {
        final int _ = sideEffect(); // ok, jdkVersion is 8. underscore can be used as normal identifier so final is not redundant
    }
    AutoCloseable lock() { return null; }
    record R(int x) { }
    int sideEffect() { return 0; }
}
PS D:\CS\test> java  -jar checkstyle-10.17.0-all.jar -c config.xml  src/Test.java                                           
Starting audit...
Audit done.
Checkstyle ends with 0 errors.

```

**Note**: This update also includes `final` modifier on unnamed lambda parameters and unnamed catch parameters.

### PR DESCRIPTION
**Pull request by mahfouz72**
closes #15159 

Diff Regression config: https://gist.githubusercontent.com/mahfouz72/afd57aa6e51ca161b7927acd959e5211/raw/bcf25b79718c2480283ab52d6662b42814056edb/check.xml
Diff Regression patch config: https://gist.githubusercontent.com/mahfouz72/33967bf86e4a29cafa429771b0e95808/raw/927d953c15bc189188acdacd0f7530cf2cc15135/check_patch.xml

### CODE REVIEW

**Comment by mahfouz72** [comment]
javac 21 job and javac on local outputs are not consistent

running command locally :



---

Job URL:  https://app.circleci.com/pipelines/github/checkstyle/checkstyle/27299/workflows/a4aaa25c-0a96-4d6a-ab70-78aa5000d897/jobs/664816

```
src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/modifier/redundantmodifier/InputRedundantModifierFinalUnnamedVariables.java:29: error: illegal start of expression
            case Point(final int a, final int _) when a == 0 -> { }
                       ^
src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/modifier/redundantmodifier/InputRedundantModifierFinalUnnamedVariables.java:29: error: <identifier> expected
            case Point(final int a, final int _) when a == 0 -> { }
```

**Comment by nrmancuso** [comment]
@mahfouz72 please show java versions and vendors for both CI execution and local, this is critical to help us understand what is going on here. We should also take a look at the grammar and see what it specifies.

**Comment by romani** [comment]
Github, generate report for RedundantModifier/all-examples-in-one

**Comment by mahfouz72** [comment]
@nrmancuso

Grammer:

> SwitchLabel:
> case [CaseConstant](https://docs.oracle.com/javase/specs/jls/se21/html/jls-14.html#jls-CaseConstant) {, [CaseConstant](https://docs.oracle.com/javase/specs/jls/se21/html/jls-14.html#jls-CaseConstant)}
> case null [, default]
> case [CasePattern](https://docs.oracle.com/javase/specs/jls/se21/html/jls-14.html#jls-CasePattern) [[Guard](https://docs.oracle.com/javase/specs/jls/se21/html/jls-14.html#jls-Guard)]
> default
> 
> CasePattern:
> [Pattern](https://docs.oracle.com/javase/specs/jls/se21/html/jls-14.html#jls-Pattern)
> 
> Pattern:
> [TypePattern](https://docs.oracle.com/javase/specs/jls/se21/html/jls-14.html#jls-TypePattern)
> [RecordPattern](https://docs.oracle.com/javase/specs/jls/se21/html/jls-14.html#jls-RecordPattern)
> 
> TypePattern:
> [LocalVariableDeclaration](https://docs.oracle.com/javase/specs/jls/se21/html/jls-14.html#jls-LocalVariableDeclaration)
> 
> RecordPattern:
> [ReferenceType](https://docs.oracle.com/javase/specs/jls/se21/html/jls-4.html#jls-ReferenceType) ( [[PatternList](https://docs.oracle.com/javase/specs/jls/se21/html/jls-14.html#jls-PatternList)] )
> PatternList:
> [Pattern](https://docs.oracle.com/javase/specs/jls/se21/html/jls-14.html#jls-Pattern) {, [Pattern](https://docs.oracle.com/javase/specs/jls/se21/html/jls-14.html#jls-Pattern) }
> 
> LocalVariableDeclaration:
> {[VariableModifier](https://docs.oracle.com/javase/specs/jls/se21/html/jls-8.html#jls-VariableModifier)} [LocalVariableType](https://docs.oracle.com/javase/specs/jls/se21/html/jls-14.html#jls-LocalVariableType) [VariableDeclaratorList](https://docs.oracle.com/javase/specs/jls/se21/html/jls-8.html#jls-VariableDeclaratorList)
> VariableModifier:
> [Annotation](https://docs.oracle.com/javase/specs/jls/se21/html/jls-9.html#jls-Annotation)
> final

I think the code is valid based on grammer. I used SDK 21 to run the code, CI execution uses also Release 21
```
    do
      javac --release 21 --enable-preview -d target "${file}"
    done
```

**Comment by mahfouz72** [comment]
github, generate report

File: src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/modifier/redundantmodifier/InputRedundantModifierFinalUnnamedVariables.java [hunk 1]
```diff
@@ -0,0 +1,33 @@
...
+         CTOR_DEF, CLASS_DEF, ENUM_DEF, RESOURCE
+jdkVersion = (default)21
+
+
+*/
+
+//non-compiled with javac: Compilable with Java21
+package com.puppycrawl.tools.checkstyle.checks.modifier.redundantmodifier;
+
+public class InputRedundantModifierFinalUnnamedVariables {
```
Comment (nrmancuso) [inline src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/modifier/redundantmodifier/InputRedundantModifierFinalUnnamedVariables.java:13]: Please add a test case with a switch statement, with pattern matching, which uses unnamed variables (like `case final Integer _ -> System.out.println("Integer");`).

Thinking back, we may have missed this test case in other PRs.

**Review by nrmancuso — CHANGES_REQUESTED** [review]
Item:

File: src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/modifier/redundantmodifier/InputRedundantModifierFinalUnnamedVariables.java (hunk 1 above)
Comment (mahfouz72) [reply src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/modifier/redundantmodifier/InputRedundantModifierFinalUnnamedVariables.java:13]: You forgot that we took almost 3 days discussing the problem with javac 21 with this example

Comment (mahfouz72) [reply src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/modifier/redundantmodifier/InputRedundantModifierFinalUnnamedVariables.java:13]: This example will not compile by javac21 although it is 100% valid according to java grammar (It compiles locally on java version. 22). probably a bug that were solved

Comment (nrmancuso) [reply src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/modifier/redundantmodifier/InputRedundantModifierFinalUnnamedVariables.java:13]: You did not mention this in our discussion/your examples. You only mentioned record patterns.

Comment (nrmancuso) [reply src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/modifier/redundantmodifier/InputRedundantModifierFinalUnnamedVariables.java:13]: Compiles fine for me:
```
➜  src javac --version
javac 21.0.3

➜  src cat Test.java 
public class Test {
    void m(Object o) {
        switch (o) {
            case final Integer _ -> System.out.println("Integer");
            case String _ -> System.out.println("String");
            default -> System.out.println("Unknown");
        }
    }
}

➜  src javac --enable-preview --release 21 Test.java
Note: Test.java uses preview features of Java SE 21.
Note: Recompile with -Xlint:preview for details.

```

Comment (mahfouz72) [reply src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/modifier/redundantmodifier/InputRedundantModifierFinalUnnamedVariables.java:13]: Yes sorry, I thought we had this bug with both examples but yes it works for pattern variables. The bug was in record pattern only. 

Done.

**Review by nrmancuso — APPROVED** [review]

File: config/pmd.xml [hunk 2]
```diff
@@ -372,7 +372,8 @@
       | //ClassDeclaration[@SimpleName='SarifLogger']//MethodDeclaration[@Name='escape']
       | //ClassDeclaration[@SimpleName='LeftCurlyCheck'
         or @SimpleName='FinalLocalVariableCheck'
-        or @SimpleName='NPathComplexityCheck']
+        or @SimpleName='NPathComplexityCheck'
+        or @SimpleName='RedundantModifierCheck']
```
Comment (rnveach) [inline config/pmd.xml:376]: Suppression was added, but no reason why.

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/modifier/RedundantModifierCheck.java [hunk 3]
```diff
@@ -64,6 +64,10 @@
  * {@code strictfp} modifier when using JDK 17 or later. See reason at
  * <a href="https://openjdk.org/jeps/306">JEP 306</a>
  * </li>
+ * <li>
+ * {@code final} modifier on unnamed variables and unnamed pattern variables
+ * when using JDK 21 or later.
```
Comment (rnveach) [inline src/main/java/com/puppycrawl/tools/checkstyle/checks/modifier/RedundantModifierCheck.java:69]: Question: Is this 21 preview or actually 21?

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/modifier/RedundantModifierCheck.java [hunk 4]
```diff
@@ -317,6 +329,18 @@ public void visitToken(DetailAST ast) {
         }
     }
 
+    /**
+     * Check if the variable is unnamed.
+     *
+     * @param variableAst ast node st node of type {@link TokenTypes#VARIABLE_DEF}
```
Comment (rnveach) [inline src/main/java/com/puppycrawl/tools/checkstyle/checks/modifier/RedundantModifierCheck.java:335]: > ast node st node 

This doesn't make sense to me.

File: src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/modifier/redundantmodifier/InputRedundantModifierFinalUnnamedVariablesWithOldVersion.java [hunk 5]
```diff
@@ -0,0 +1,41 @@
+/*
+RedundantModifier
+tokens = (default)METHOD_DEF, VARIABLE_DEF, ANNOTATION_FIELD_DEF, INTERFACE_DEF, \
+         CTOR_DEF, CLASS_DEF, ENUM_DEF, RESOURCE
+jdkVersion = 8
+
+
+*/
+
+//non-compiled with javac: Compilable with Java21
```
Comment (rnveach) [inline src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/modifier/redundantmodifier/InputRedundantModifierFinalUnnamedVariablesWithOldVersion.java:10]: This is an akward test. It is only compilable by 21, but we set the Java version to 8.

I would split this into 2 tests. One which is actually like Java 8 (I understand we still compile with 11), and the other which is 21. The 21 tests needs a reason it is 21 while we set the Java version to something else.

I am sure we did this with the other PR. If you want to create a separate PR fix, it would be appreciated.

**Review by rnveach — CHANGES_REQUESTED** [review]

File: config/pmd.xml (hunk 2 above)
Comment (mahfouz72) [reply config/pmd.xml:376]: It goes under the already existing reason, comment above the suppressions.

> The methods visitToken/leaveToken are a big SWITCH block with a number of IF blocks.
             If we split the block to several methods it will damage the readability.

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/modifier/RedundantModifierCheck.java (hunk 3 above)
Comment (mahfouz72) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/modifier/RedundantModifierCheck.java:69]: 21 was a first preview

File: src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/modifier/redundantmodifier/InputRedundantModifierFinalUnnamedVariablesWithOldVersion.java (hunk 5 above)
Comment (mahfouz72) [reply src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/modifier/redundantmodifier/InputRedundantModifierFinalUnnamedVariablesWithOldVersion.java:10]: > One which is actually like Java 8 (I understand we still compile with 11),

variables named `_` compiles only on Java 8 and below and on Java 21 and below. So we have no other option to used java21 in files that have `_` in them.

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/modifier/RedundantModifierCheck.java (hunk 4 above)
Comment (mahfouz72) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/modifier/RedundantModifierCheck.java:335]: done

File: config/pmd.xml (hunk 2 above)
Comment (rnveach) [reply config/pmd.xml:376]: The one which lists
> Main, PackageObjectFactory, RequireThisCheck, HandlerFactory,
VariableDeclarationUsageDistanceCheck,

?

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/modifier/RedundantModifierCheck.java (hunk 3 above)
Comment (rnveach) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/modifier/RedundantModifierCheck.java:69]: So then like another PR, shouldn't this say 22 or specifically mention 21 previous and released in 22?

File: src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/modifier/redundantmodifier/InputRedundantModifierFinalUnnamedVariablesWithOldVersion.java (hunk 5 above)
Comment (rnveach) [reply src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/modifier/redundantmodifier/InputRedundantModifierFinalUnnamedVariablesWithOldVersion.java:10]: ok.

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/modifier/RedundantModifierCheck.java (hunk 3 above)
Comment (rnveach) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/modifier/RedundantModifierCheck.java:69]: @nrmancuso @romani Does this create an issue as the logic in the check also actually says 21. We have no preview property.

Comment (nrmancuso) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/modifier/RedundantModifierCheck.java:69]: @rnveach good point, I think it makes sense to use the Java version when the feature was officially released

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/modifier/RedundantModifierCheck.java [hunk 6]
```diff
@@ -300,8 +307,13 @@ public void visitToken(DetailAST ast) {
             case TokenTypes.RECORD_DEF:
                 checkForRedundantModifier(ast, TokenTypes.FINAL, TokenTypes.LITERAL_STATIC);
                 break;
-            case TokenTypes.CLASS_DEF:
             case TokenTypes.VARIABLE_DEF:
+            case TokenTypes.PATTERN_VARIABLE_DEF:
+                if (jdkVersion >= JDK_21 && isUnnamedVariable(ast)) {
+                    checkForRedundantModifier(ast, TokenTypes.FINAL);
```
Comment (rnveach) [inline src/main/java/com/puppycrawl/tools/checkstyle/checks/modifier/RedundantModifierCheck.java:313]: Should/does this cover lambda parameters, catch parameters, and resources, which can be unnamed?
https://github.com/checkstyle/checkstyle/pull/15480
https://github.com/checkstyle/checkstyle/pull/15358
https://github.com/checkstyle/checkstyle/issues/15484

File: config/pmd.xml (hunk 2 above)
Comment (mahfouz72) [reply config/pmd.xml:376]: comment 
```
      <!-- Main, PackageObjectFactory, RequireThisCheck, HandlerFactory,
             VariableDeclarationUsageDistanceCheck,
             are big and should not be split without a good reason.  (This is for classReportLevel)
             
             The methods visitToken/leaveToken are a big SWITCH block with a number of IF blocks.
             If we split the block to several methods it will damage the readability. (This is for methodReportLevel, it doesn't list specific classes, it just says a method name which is visit or leave token)
```
supression
```
//ClassDeclaration[@SimpleName='Main'
        or @SimpleName='PackageObjectFactory' or @SimpleName='RequireThisCheck'
        or @SimpleName='VariableDeclarationUsageDistanceCheck'
        or @SimpleName='HandlerFactory']    ( First comment)
        ....
        
              | //ClassDeclaration[@SimpleName='LeftCurlyCheck'
        or @SimpleName='FinalLocalVariableCheck'
        or @SimpleName='NPathComplexityCheck'
        or @SimpleName='RedundantModifierCheck']
             //MethodDeclaration[@Name='visitToken']  (Second comment)
```

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/modifier/RedundantModifierCheck.java (hunk 6 above)
Comment (mahfouz72) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/modifier/RedundantModifierCheck.java:313]: Good point, This check already covers resources whether it is named or unnamed (BTW it isn't listed in the doc, in "The check validates" section maybe we should add it to this list in another PR)


but we need to support unnamed lambda parameters and  unnamed catch parameters

```
cat src/Test.java
import java.util.function.Function;

public class Test {
    
    void m() {
        try (final var a = lock();) { // violation

        } catch (final Exception e) {

        }

        try (final var _ = lock();) { // violation

        } catch (final Exception _) {

        }
    }

    void m2() {
        Function<Integer, Integer> f = (final Integer _) -> {
            return 5;
        };
    }

    AutoCloseable lock() {
        return null;
    }
}
D:\CS\test
java  -jar checkstyle-10.17.0-all.jar -c config.xml src/Test.java
Starting audit...
[ERROR] D:\CS\test\src\Test.java:6:14: Redundant 'final' modifier. [RedundantModifier]
[ERROR] D:\CS\test\src\Test.java:12:14: Redundant 'final' modifier. [RedundantModifier]
Audit done.
Checkstyle ends with 2 errors.
```

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/modifier/RedundantModifierCheck.java (hunk 3 above)
Comment (mahfouz72) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/modifier/RedundantModifierCheck.java]: done to 22. accordingly default changed to 22 also

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/modifier/RedundantModifierCheck.java (hunk 6 above)
Comment (mahfouz72) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/modifier/RedundantModifierCheck.java]: Done

**Comment by mahfouz72** [comment]
github, generate report

**Comment by mahfouz72** [comment]
github, generate report

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/modifier/RedundantModifierCheck.java [hunk 7]
```diff
@@ -317,6 +338,45 @@ public void visitToken(DetailAST ast) {
...
+     * Check if the variable is unnamed.
+     *
+     * @param ast node of type {@link TokenTypes#VARIABLE_DEF}
+     *     or {@link TokenTypes#PATTERN_VARIABLE_DEF}
+     *     or {@link TokenTypes#PARAMETER_DEF}
+     * @return true if the variable is unnamed
+     */
+    private static boolean isUnnamedVariable(DetailAST ast) {
+        return "_".equals(ast.findFirstToken(TokenTypes.IDENT)
+                .getText());
```
Comment (romani) [inline src/main/java/com/puppycrawl/tools/checkstyle/checks/modifier/RedundantModifierCheck.java:377]: `        return "_".equals(ast.findFirstToken(TokenTypes.IDENT).getText());`


may be in future we can make check that hint that wrapped code can be single line.

Comment (romani) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/modifier/RedundantModifierCheck.java:377]: alternative formatting is:
```
"_".equals(
    ast.findFirstToken(TokenTypes.IDENT).getText());
```

File: config/pmd.xml (hunk 2 above)
Comment (romani) [reply config/pmd.xml:376]: I am ok with suppression

**Review by romani — CHANGES_REQUESTED** [review]
items:

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/modifier/RedundantModifierCheck.java (hunk 7 above)
Comment (mahfouz72) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/modifier/RedundantModifierCheck.java]: @romani done

File: config/pmd.xml (hunk 2 above)
Comment (rnveach) [reply config/pmd.xml:376]: Suppression is not the issue. We declare with the suppression why we are suppressing it.

We add in the name of the class and the reason. Since the class name was never added, I can't tell why we are suppressing it, if it is agreeable, and what we would need to do in the future if we ever wanted to resolve it. The comments before it all have class names listed as we pointed to.

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/modifier/RedundantModifierCheck.java (hunk 6 above)
Comment (rnveach) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/modifier/RedundantModifierCheck.java]: Please clarify what done means here. We added support for specific cases?

I ask because you mentioned lambda and catch but did not mention resources.

File: config/pmd.xml (hunk 2 above)
Comment (mahfouz72) [reply config/pmd.xml:376]: From what I see in the comment above suppression I think it was agreed on before that we can suppress violations in visit/leave Token if it has a big switch block regardless of the name of the class.

I can add the name of this check if you want but we didn't do this before with this specific case (visitToken method), if the suppressed method was anything other than this I would feel different.

Comment (mahfouz72) [reply config/pmd.xml:376]: Do you want comment like this?

```

             The methods visitToken/leaveToken "in LeftCurlyCheck,  FinalLocalVariableCheck, NPathComplexityCheck and RedundantModifierCheck are a big SWITCH block with a number of IF blocks.
             If we split the block to several methods it will damage the readability.
```

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/modifier/RedundantModifierCheck.java (hunk 6 above)
Comment (mahfouz72) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/modifier/RedundantModifierCheck.java]: done means that we add support for redundant final on unnamed lambda parameter and unnamed catch parameter, resource is already supported

**Comment by mahfouz72** [comment]
I think failure in https://app.circleci.com/jobs/github/checkstyle/checkstyle/673440 is unrelated.

```
Starting a Gradle Daemon (subsequent builds will be faster)
Executing Gradle on JVM versions 16 and lower has been deprecated. This will fail with an error in Gradle 9.0. Use JVM 17 or greater to execute Gradle. Projects can continue to use older JVM versions via toolchains. Consult the upgrading guide for further information:
```

File: config/pmd.xml (hunk 2 above)
Comment (rnveach) [reply config/pmd.xml:376]: Ok, I changed my mind and am going to drop this.

> visit/leave Token if it has a big switch block regardless of the name of the class.

I know see what you mean by this. I don't think the way we organized these reasons here is very straightforward, but you are correct that we give a blanket statement based on method name.

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/modifier/RedundantModifierCheck.java (hunk 6 above)
Comment (rnveach) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/modifier/RedundantModifierCheck.java]: @mahfouz72 Can you updated regression with the new tokens added. I didn't see them listed at https://github.com/checkstyle/checkstyle/pull/15492#issuecomment-2307027002

Comment (rnveach) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/modifier/RedundantModifierCheck.java]: I also don't see new tokens at https://github.com/checkstyle/checkstyle/pull/15492/files#diff-9b10f3ecc777d61ee2044e7753ec6d50ea673d2d88ede4e44c87cc99f58ae733

**Comment by mahfouz72** [comment]
github, generate report

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/modifier/RedundantModifierCheck.java (hunk 6 above)
Comment (mahfouz72) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/modifier/RedundantModifierCheck.java]: > Can you updated regression with the new tokens added

I generated another report but the workflow seems to be canceled I will regenerate now.

Comment (mahfouz72) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/modifier/RedundantModifierCheck.java]: > I also don't see new tokens at 

@rnveach done, because there was `(default)` the new default tokens were loaded even if we don't add them to the list in the config comment

Comment (mahfouz72) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/modifier/RedundantModifierCheck.java]: > @mahfouz72 Can you updated regression with the new tokens added. I didn't see them listed at [#15492 (comment)](https://github.com/checkstyle/checkstyle/pull/15492#issuecomment-2307027002)

https://github.com/checkstyle/checkstyle/pull/15492#issuecomment-2307569944

**Review by romani — APPROVED** [review]
Ok to merge

**Review by rnveach — APPROVED** [review]
