### PR TITLE
Issue #8399: fix NPE for SuperClone and SuperFinalize checks

### LINKED ISSUE #8399: super::clone breaks SuperCloneCheck
https://checkstyle.org/config_coding.html#SuperClone
https://checkstyle.org/config_coding.html#SuperFinalize

```
/var/tmp $ javac --release 11 A.java
# This only works in Java 11+

/var/tmp $ cat config.xml
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
          "-//Puppy Crawl//DTD Check Configuration 1.3//EN"
          "http://www.puppycrawl.com/dtds/configuration_1_3.dtd">

<module name="Checker">
  <property name="charset" value="UTF-8" />

  <module name="TreeWalker">
    <module name="SuperCloneCheck" />
  </module>
</module>


/var/tmp $ cat A.java
class A {
  @FunctionalInterface
  public interface CheckedSupplier<R, E extends Exception> {
    R get() throws E;
  }

  public Object clone() {
    CheckedSupplier<Object, CloneNotSupportedException> r = super::clone; // NPE consuming this
    try {
      return r.get();
    } catch (CloneNotSupportedException e) {
      throw new RuntimeException(e);
    }
  }
}
 
/var/tmp $ RUN_LOCALE="-Duser.language=en -Duser.country=US"
/var/tmp $ java $RUN_LOCALE -jar checkstyle-8.34-all.jar -c config.xml YOUR_FILE.java
Starting audit...
com.puppycrawl.tools.checkstyle.api.CheckstyleException: Exception was thrown while processing A.java
	at com.puppycrawl.tools.checkstyle.Checker.processFiles(Checker.java:311)
	at com.puppycrawl.tools.checkstyle.Checker.process(Checker.java:221)
	at com.puppycrawl.tools.checkstyle.Main.runCheckstyle(Main.java:408)
	at com.puppycrawl.tools.checkstyle.Main.runCli(Main.java:331)
	at com.puppycrawl.tools.checkstyle.Main.execute(Main.java:190)
	at com.puppycrawl.tools.checkstyle.Main.main(Main.java:125)
Caused by: java.lang.NullPointerException
	at com.puppycrawl.tools.checkstyle.checks.coding.AbstractSuperCheck.hasArguments(AbstractSuperCheck.java:142)
	at com.puppycrawl.tools.checkstyle.checks.coding.AbstractSuperCheck.isSuperCall(AbstractSuperCheck.java:106)
	at com.puppycrawl.tools.checkstyle.checks.coding.AbstractSuperCheck.visitToken(AbstractSuperCheck.java:85)
	at com.puppycrawl.tools.checkstyle.TreeWalker.notifyVisit(TreeWalker.java:340)
	at com.puppycrawl.tools.checkstyle.TreeWalker.processIter(TreeWalker.java:451)
	at com.puppycrawl.tools.checkstyle.TreeWalker.walk(TreeWalker.java:278)
	at com.puppycrawl.tools.checkstyle.TreeWalker.processFiltered(TreeWalker.java:151)
	at com.puppycrawl.tools.checkstyle.api.AbstractFileSetCheck.process(AbstractFileSetCheck.java:87)
	at com.puppycrawl.tools.checkstyle.Checker.processFile(Checker.java:337)
	at com.puppycrawl.tools.checkstyle.Checker.processFiles(Checker.java:298)
	... 5 more
Checkstyle ends with 1 errors.

```

---------------

**Describe what you expect in detail.**
I'm unsure if the built in check should pass when you make a reference to the superclass implementation. I was looking at extending `AbstractSuperCheck` to force calling `super.close()` in implementations of `close`. In my case it is normal and common to do stuff like `IOUtils.close(super::close, other, stuff, here);`. So, at least for me, it'd be best if `AbstractSuperCheck` considered a reference to the superclass implementation to pass. Or if it could be configured to do so.

--------------

### PR DESCRIPTION
**Pull request by strkkk**
Resolves #8399 
Reg report (no diff) https://strkkk.github.io/checkstyle/8399/index.html

Diff Regression projects: https://raw.githubusercontent.com/checkstyle/contribution/master/checkstyle-tester/projects-to-test-on.properties
Diff Regression config: https://raw.githubusercontent.com/strkkk/strkkk.github.io/master/checkstyle/check.xml
Diff Regression patch config: https://raw.githubusercontent.com/strkkk/strkkk.github.io/master/checkstyle/check.xml

### CODE REVIEW

File: src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/superfinalize/InputSuperFinalizeMethodReference.java [hunk 1]
```diff
@@ -0,0 +1,19 @@
...
+
+    @Override
+    protected void finalize() throws Throwable {
+        CheckedConsumer<Throwable> r = super::finalize;
+        r.get();
+    }
+}
+
+class ClassWithFinalizer {
+    protected void finalize() throws Throwable {
```
Comment (romani) [inline src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/superfinalize/InputSuperFinalizeMethodReference.java:17]: please add `//violation` comment and comment over class for Check config.

One day in future we will read config and expected violations from Input file.

Comment (strkkk) [reply src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/superfinalize/InputSuperFinalizeMethodReference.java]: done

File: src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/superclone/InputSuperCloneMethodReference.java [hunk 2]
```diff
@@ -0,0 +1,21 @@
...
+import java.util.ArrayList;
+
+/** Config = default */
+public class InputSuperCloneMethodReference extends ArrayList {
+
+    public interface CheckedSupplier<R, E extends Exception> {
+        R get() throws E;
+    }
+
+    public Object clone() {
```
Comment (romani) [inline src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/superclone/InputSuperCloneMethodReference.java:12]: please put `// ok` here, after merge of Nick's PR, it will be required to have at least one ok or violation comment.

Comment (strkkk) [reply src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/superclone/InputSuperCloneMethodReference.java]: done

**Comment by strkkk** [comment]
test

**Comment by strkkk** [comment]
diff report

**Comment by strkkk** [comment]
single report

**Comment by strkkk** [comment]
diff report

**Comment by strkkk** [comment]
diff report

**Comment by strkkk** [comment]
single report
