### PR TITLE
Issue #14344: Fix GenericWhitespace Check ignoring exception to the '>' rule for succeeding whitespaces

### LINKED ISSUE #14344: GenericWhitespace Check ignores exception to the ">" rule for succeeding whitespaces
Detected at [#14341](https://github.com/checkstyle/checkstyle/pull/14341).
Affects PR #14364 

([Documentation](https://checkstyle.org/checks/whitespace/genericwhitespace.html))

**Test.java**
```java
import java.util.ArrayList;
import java.util.List;

public class Test {
  List a = new ArrayList<> (); // violation expected
}
```

**config.xml**
```xml
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
        "-//Checkstyle//DTD Checkstyle Configuration 1.3//EN"
        "https://checkstyle.org/dtds/configuration_1_3.dtd">
<module name="Checker">
  <module name="TreeWalker">
    <module name="GenericWhitespace"/>
  </module>
</module>
```

**Actual:**
```
java -jar checkstyle-10.12.7-all.jar -c config.xml Test.java
Starting audit...
Audit done.
```

**Expected:** violation on line 5.
`Test.java:5:26: '>' is followed by whitespace. [GenericWhitespace]`

### Explanation:
- As per the documentation, right angle bracket (`>`) should not be followed by whitespace for diamond operators and when preceding method name or constructor.
- In `List a = new ArrayList<> ();` the right angle bracket (`>`) precedes the constructor, and is also part of the diamond operator (`<>`), hence shouldn't be followed by the whitespace.
- The exact example is provided provided in the [documentation](https://checkstyle.org/checks/whitespace/genericwhitespace.html#Example2-code), showcasing that it is incorrect style and should throw a violation, but this is ignored by the Check. (Also evident in the [referenced PR](https://github.com/checkstyle/checkstyle/pull/14341#issuecomment-1907645027))

### PR DESCRIPTION
**Pull request by sktpy**
Resolves #14344 

Reasoning for the changes are mentioned in the corresponding review comments of mine. <hr>

**Regression:** ([Report](https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/28c7818_2024125529/reports/diff/index.html))
Differences found (expected).
- **Added violations**(71): Example (rest occurrences are similar). ([Line 123](https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/28c7818_2024125529/reports/diff/spotbugs/xref/home/runner/work/checkstyle/checkstyle/.ci-temp/contribution/checkstyle-tester/repositories/spotbugs/spotbugs/src/main/java/edu/umd/cs/findbugs/Plugin.java.html#L123))
```java
componentPlugins = new DualKeyHashMap<> ();
//                                    ^
//  '>' is followed by whitespace  ---+
```
This added violation was not detected before (a false negative, reasoning in the description of the Issue this PR resolves)
- **Removed violations**(3): Example (rest occurrences are similar). ([Line 78](https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/28c7818_2024125529/reports/diff/openjdk17/xref/home/runner/work/checkstyle/checkstyle/.ci-temp/contribution/checkstyle-tester/repositories/openjdk17/test/langtools/tools/javac/annotations/typeAnnotations/newlocations/AllLocations.java.html#L78))
```java
return new <@BG Inner<@BH Integer>> @BI Inner<@BJ Inner<@BK Integer>>(null);
//         ^
//         +---  '<' is preceded with whitespace.
```
This removed violation is a false positive which was detected as a violation before because generics enclosing Annotations that were succeeding `new` keyword weren't detected as the cases where they should be preceded with a whitespace.
These cases are now detected properly in the fix ([See comment](https://github.com/checkstyle/checkstyle/pull/14497/files?diff=unified&w=0#r1493341026)). 

Diff Regression config: https://gist.githubusercontent.com/sktpy/44a31ea4e946a0755fa3e331fd65de98/raw/50e5257788a0f001f2ad184b1a7cbac7910e8b5b/check.xml

### CODE REVIEW

**Comment by sktpy** [comment]
GitHub, generate report

**Comment by sktpy** [comment]
GitHub, generate report

File: src/it/java/com/google/checkstyle/test/chapter4formatting/rule462horizontalwhitespace/GenericWhitespaceTest.java [hunk 1]
```diff
@@ -54,6 +54,7 @@ public void testWhitespaceAroundGenerics() throws Exception {
             "14:46: " + getCheckMessage(messages, msgPreceded, ">"),
             "15:33: " + getCheckMessage(messages, msgFollowed, "<"),
             "15:33: " + getCheckMessage(messages, msgPreceded, "<"),
+            "15:46: " + getCheckMessage(messages, msgFollowed, ">"),
```
Comment (sktpy) [inline src/it/java/com/google/checkstyle/test/chapter4formatting/rule462horizontalwhitespace/GenericWhitespaceTest.java:57]: All the similar additions in expected violations is due to following:
In this instance the extra violation is in the following line:
https://github.com/checkstyle/checkstyle/blob/9842608983cf00c1927d5e5bfcffdb05f4936afb/src/it/resources/com/google/checkstyle/test/chapter4formatting/rule462horizontalwhitespace/InputWhitespaceAroundGenerics.java#L15
Earlier check didn't considered the whitespace between `>` `(` as a violation, this is now correctly identified in the fix.

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/GenericWhitespaceCheck.java [hunk 2]
```diff
@@ -219,7 +219,10 @@ else if (line[after] == ' ') {
      */
     private void processSingleGeneric(DetailAST ast, int[] line, int after) {
         final char charAfter = Character.toChars(line[after])[0];
-        if (isGenericBeforeMethod(ast) || isGenericBeforeCtor(ast)) {
+        if (isGenericBeforeMethod(ast)
+                // isGenericBeforeNew() needn't be checked as the ast which satisfies it,
+                // will also satisfy isGenericBeforeCtorInvocation().
```
Comment (sktpy) [inline src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/GenericWhitespaceCheck.java:224]: This is because `isGenericBeforeCtorInvocation()` encompasses the first-operand of the and-statement in `isGenericBeforeNew()` as the first-operand of its or-statement.
Inclusion of both will result in mutant.

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/GenericWhitespaceCheck.java [hunk 3]
```diff
@@ -230,16 +233,38 @@ else if (!isCharacterValidAfterGenericEnd(charAfter)) {
...
+     * <ol>
+     *     <li>{@code new <String>Object();}</li>
+     *     <li>{@code new <String>Outer.Inner();}</li>
+     *     <li>{@code new <@A Outer>@B Inner();}</li>
+     * </ol>
+     *
+     * @param ast ast
+     * @return true if generic after {@code LITERAL_NEW}
+     */
+    private static boolean isGenericAfterNew(DetailAST ast) {
```
Comment (sktpy) [inline src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/GenericWhitespaceCheck.java:262]: Method name change from `isGenericBeforeCtor()` to `isGenericAfterNew()`, this describes method's behaviour more accurately, as it only identified the cases where generic existed after `new` keyword.
The method didn't identified cases where generic preceded constructor invocation `()` which was the cause for the false negative.

The method now also identifies a new similar case for Annotations (case 3.)

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/GenericWhitespaceCheck.java [hunk 4]
```diff
@@ -274,25 +299,29 @@ private void processStart(DetailAST ast) {
...
+        // Handles 3 cases as in:
         //
         //   public static <T> Callable<T> callable(Runnable task, T result)
         //                 ^           ^
-        //      ws reqd ---+           +--- whitespace NOT required
+        //   1. ws reqd ---+        2. +--- whitespace NOT required
         //
+        //   new <String>Object()
+        //       ^
+        //    3. +--- ws required
```
Comment (sktpy) [inline src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/GenericWhitespaceCheck.java:311]: Added this example in the comments as earlier `isGenericBeforeCtor()` (now `isGenericAfterNew()`) was added to be used in this method for identifying the cases where a preceding whitespace was required, but comment was not updated to showcase this new detection.

File: src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/whitespace/genericwhitespace/InputGenericWhitespaceBeforeRecordHeader.java [hunk 5]
```diff
@@ -0,0 +1,12 @@
...
+GenericWhitespace
+
+
+*/
+
+//non-compiled with javac: Compilable with Java16
+package com.puppycrawl.tools.checkstyle.checks.whitespace.genericwhitespace;
+
+public class InputGenericWhitespaceBeforeRecordHeader {
+    record Session<T>() {}
```
Comment (sktpy) [inline src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/whitespace/genericwhitespace/InputGenericWhitespaceBeforeRecordHeader.java:11]: **Disclaimer:** Contains some off-topic observations.

The purpose of this input and the corresponding test is to kill the mutation which survived after the changes in Check.
Surviving mutation  was replacing `charAfter == '('` with `false`  in the following line:
https://github.com/checkstyle/checkstyle/blob/9842608983cf00c1927d5e5bfcffdb05f4936afb/src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/GenericWhitespaceCheck.java#L347 <hr>
#### Why this didn't survived before:
Before the fix, check didn't identified all the cases where generic was present before constructor invocation, which meant some `CTOR` cases where `>` was succeeded with `(` weren't filtered through the following `if` statement:
https://github.com/checkstyle/checkstyle/blob/9842608983cf00c1927d5e5bfcffdb05f4936afb/src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/GenericWhitespaceCheck.java#L222
Such cases killed the above mutation.
Due to the fix, all the possible existing cases where `>` could be succeeded by `(` were filtered through the if statement which made the mutant survive.

So after a bit of mutant hunting to find a valid input where `>` could be succeeded by `(` but wasn't before Method or Ctor, found out that such valid input exist for generic before record header, which was able to kill the mutant.

As of now, we don't have clear definition in the documentation on how to handle whitespace for generic that is before a record header, current check does not count space between `>` and `(` of record header as a violation, will open an Issue shortly for discussing if it should, based on the decision of the discussion, will update the Check accordingly and strengthen the test inputs for the records in a separate PR.

Funny thing is that if there is supposed to be violation for the case above, this will revive the mutant, as we will now be filtering the killing input in the if statement(this in my knowledge makes for all possible cases where generic can be preceded by `(`), which will mean that the affected operand could be safely removed if no regressions are found and no one is aware of such input.

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/GenericWhitespaceCheck.java [hunk 6]
```diff
@@ -230,16 +233,38 @@ else if (!isCharacterValidAfterGenericEnd(charAfter)) {
...
+     *     <li>{@code new ArrayList<>();}</li>
+     *     <li>{@code new Outer.Inner<>();}</li>
+     * </ol>
      *
      * @param ast ast
-     * @return true if generic before a constructor invocation
+     * @return true if generic is before constructor invocation
      */
-    private static boolean isGenericBeforeCtor(DetailAST ast) {
+    private static boolean isGenericBeforeCtorInvocation(DetailAST ast) {
```
Comment (sktpy) [inline src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/GenericWhitespaceCheck.java:245]: Identifies cases where `>` should not be followed by whitespace.

**Comment by sktpy** [comment]
Failing checks in CI are unrelared. ([Cirrus](https://github.com/checkstyle/checkstyle/pull/14497/checks?check_run_id=21682946958),  [YAML Validation for site.xml](https://app.circleci.com/pipelines/github/checkstyle/checkstyle/1/workflows/910446fc-a050-4abe-8ddc-a4e4d298f977/jobs/518406/artifacts))

File: src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/genericwhitespace/InputGenericWhitespaceDefault.java [hunk 7]
```diff
@@ -19,8 +19,8 @@ void meth()
     {
         List<Integer> x = new ArrayList<Integer>();
         List<List<Integer>> y = new ArrayList<List<Integer>>();
-        List < Integer > a = new ArrayList < Integer > (); // 6 violations
-        List < List < Integer > > b = new ArrayList < List < Integer > > (); // 14 violations
+        List < Integer > a = new ArrayList < Integer > (); // 7 violations
+        List < List < Integer > > b = new ArrayList < List < Integer > > (); // 15 violations
     }
```
Comment (romani) [inline src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/genericwhitespace/InputGenericWhitespaceDefault.java:24]: Please add to input code with double `>>` like https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/28c7818_2024125529/reports/diff/elasticsearch/index.html#A1
To have single violation on it.

And add https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/28c7818_2024125529/reports/diff/Hbase/index.html#A1

And https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/28c7818_2024125529/reports/diff/Hbase/index.html#A3

**Review by romani — CHANGES_REQUESTED** [review]
Please extend inputs by a bit more cases.
We need to not rely on regression too much in future, so we collecting all different types of how code can be written.

File: src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/genericwhitespace/InputGenericWhitespaceDefault.java (hunk 7 above)
Comment (sktpy) [reply src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/genericwhitespace/InputGenericWhitespaceDefault.java:24]: [Done](https://github.com/checkstyle/checkstyle/blob/0eaeb24626e64991d308fa5739cf8decc18d9b2b/src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/genericwhitespace/InputGenericWhitespaceBeforeCtorInvocation.java#L31-L41)

File: src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/genericwhitespace/InputGenericWhitespaceBeforeCtorInvocation.java [hunk 8]
```diff
@@ -0,0 +1,62 @@
...
+import java.util.ArrayList;
+import java.util.List;
+
+import static java.lang.annotation.ElementType.TYPE_USE;
+
+public class InputGenericWhitespaceBeforeCtorInvocation {
+    List<String> music = new ArrayList<>();
+    List todo = new ArrayList<> (); // violation, ''>' is followed by whitespace.'
+
+    Gen<String, Integer> eel = new Gen<String, Integer > (); // 2 violations
```
Comment (romani) [inline src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/genericwhitespace/InputGenericWhitespaceBeforeCtorInvocation.java:19]: plase reuse this patter to share messages for all violations
https://github.com/checkstyle/checkstyle/commit/e46f933d31fa30385146ef08bb9e2f725d7fc206#diff-a277946d953ad41bfa49f4012b6fd8bd41c6ac618fa61fa23784d7d675908418R38

**Review by romani — CHANGES_REQUESTED** [review]
items:

File: src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/genericwhitespace/InputGenericWhitespaceDefault.java (hunk 7 above)
Comment (romani) [reply src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/genericwhitespace/InputGenericWhitespaceDefault.java:24]: >283     this.regionsToReopen = Collections.synchronizedMap
284                            (new HashMap<String, HRegionInfo> ());

I did not find in `(new ....` in your Inputs.

Comment (sktpy) [reply src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/genericwhitespace/InputGenericWhitespaceDefault.java:24]: > I did not find in (new .... in your Inputs. please add

https://github.com/checkstyle/checkstyle/blob/0eaeb24626e64991d308fa5739cf8decc18d9b2b/src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/genericwhitespace/InputGenericWhitespaceBeforeCtorInvocation.java#L39

File: src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/genericwhitespace/InputGenericWhitespaceBeforeCtorInvocation.java (hunk 8 above)
Comment (sktpy) [reply src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/genericwhitespace/InputGenericWhitespaceBeforeCtorInvocation.java:19]: Just to clarify, I need to remove inline violation message "`// 2 violations`", place it in the next line, and replace it with "`// 2 violations above:`" ?

Comment (sktpy) [reply src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/genericwhitespace/InputGenericWhitespaceBeforeCtorInvocation.java:19]: Should I do this for all the input files or just for `BeforeCtorInvocation` and `AfterNew` inputs? I think it would be counterproductive for lines with too many violation like this:
https://github.com/checkstyle/checkstyle/blob/0eaeb24626e64991d308fa5739cf8decc18d9b2b/src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/genericwhitespace/InputGenericWhitespaceDefault.java#L23

Comment (romani) [reply src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/genericwhitespace/InputGenericWhitespaceBeforeCtorInvocation.java:19]: It would be awesome but, we can do it in separate PR, to not grow this update more than required.

Comment (sktpy) [reply src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/genericwhitespace/InputGenericWhitespaceBeforeCtorInvocation.java]: Done.

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/GenericWhitespaceCheck.java (hunk 2 above)
Comment (romani) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/GenericWhitespaceCheck.java:224]: @sktpy , please remove this comment, I  do not understand it. isGenericBeforeNew is not existing.

Comment (sktpy) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/GenericWhitespaceCheck.java]: Done.
Previously `isGenericBeforeCtor()` (which is now called `isGenericBeforeNew()`) was checked here, but since it can now be covered with `isGenericBeforeCtorInvocation()`, had added that comment just in case that if logic gets changed in future in a way that `isGenericBeforeCtorInvocation()` wouldn't be able to satisfy ast which satisfies `isGenericBeforeNew()`

**Review by romani — APPROVED** [review]
ok to merge

**Review by rnveach — APPROVED** [review]
