### PR TITLE
Issue #15082:LITERAL_WHEN token should have EXPR child

### LINKED ISSUE #15082: CASE_GROUP and LITERAL_WHEN token should have EXPR child
_Originally posted by @rnveach in https://github.com/checkstyle/checkstyle/issues/15044#issuecomment-2181774032_

Expressions used in `switch` are not caught by BooleanExpressionComplexity.
 
```
        switch (obj) {
            case ColoredPoint(boolean a, boolean b, boolean _) // line 4
                    when (a ^ (a || b) ^ (b || a) & (a | b)) -> {  // expected violation

                if (a ^ (a || b) ^ (b || a) & (a | b)) { }   // violation
                boolean c = (a ^ (a || b) ^ (b || a) & (a | b));   // violation

            }
```

This is the issue. [We only check the count when we finish an expression](https://github.com/checkstyle/checkstyle/blob/11dcd180e71dabf6cee355c240c562df7fb70d29/src/main/java/com/puppycrawl/tools/checkstyle/checks/metrics/BooleanExpressionComplexityCheck.java#L261). However, this `when` isn't an expression.

```
        |      |  |  |--LITERAL_CASE -> case [4:12]
        |      |  |  |  `--PATTERN_DEF -> PATTERN_DEF [5:20]
        |      |  |  |      `--LITERAL_WHEN -> when [5:20]
        |      |  |  |          |--RECORD_PATTERN_DEF -> RECORD_PATTERN_DEF [4:17]
...
        |      |  |  |          |--LPAREN -> ( [5:25]
        |      |  |  |          |--BXOR -> ^ [5:39]   <-- no expression
...
        |      |  |  |          `--RPAREN -> ) [5:59]
```

the same problem is for `case` with `&&` or any other expression like operator:
```
        switch (o) {
            case String s && s.length() > 4: // guarded pattern, `PATTERN_DEF`
                break;
```

According to the JLS (unless I am looking at the wrong area), this guard says it is an expression. Is this a bug in our grammar that we are missing an expression token?
https://docs.oracle.com/javase/specs/jls/se22/html/jls-14.html#jls-14.11.1

>SwitchLabel:
case [CaseConstant](https://docs.oracle.com/javase/specs/jls/se22/html/jls-14.html#jls-CaseConstant) {, [CaseConstant](https://docs.oracle.com/javase/specs/jls/se22/html/jls-14.html#jls-CaseConstant)}
case null [, default]
case [CasePattern](https://docs.oracle.com/javase/specs/jls/se22/html/jls-14.html#jls-CasePattern) {, [CasePattern](https://docs.oracle.com/javase/specs/jls/se22/html/jls-14.html#jls-CasePattern)} [[Guard](https://docs.oracle.com/javase/specs/jls/se22/html/jls-14.html#jls-Guard)]
default
CaseConstant:
[ConditionalExpression](https://docs.oracle.com/javase/specs/jls/se22/html/jls-15.html#jls-ConditionalExpression)
CasePattern:
[Pattern](https://docs.oracle.com/javase/specs/jls/se22/html/jls-14.html#jls-Pattern)
Guard:
when [Expression](https://docs.oracle.com/javase/specs/jls/se22/html/jls-15.html#jls-Expression)

Edit: It does look like our grammar does say expression.
https://github.com/checkstyle/checkstyle/blob/11dcd180e71dabf6cee355c240c562df7fb70d29/src/main/resources/com/puppycrawl/tools/checkstyle/grammar/java/JavaLanguageParser.g4#L913-L914

Edit 2: It looks like it is an issue using `expr` over `expression` in the grammar.
https://github.com/checkstyle/checkstyle/blob/11dcd180e71dabf6cee355c240c562df7fb70d29/src/main/resources/com/puppycrawl/tools/checkstyle/grammar/java/JavaLanguageParser.g4#L683-L687
            
examples of EXPR in our tree:
https://checkstyle.sourceforge.io/apidocs/com/puppycrawl/tools/checkstyle/api/TokenTypes.html#SLIST
https://checkstyle.sourceforge.io/apidocs/com/puppycrawl/tools/checkstyle/api/TokenTypes.html#EXPR
location of EXPR is odd when comparing to ASSIGN:
```
  `--SLIST -> {
      |--EXPR -> EXPR
      |   `--ASSIGN -> =
```
vs
```
 |--VARIABLE_DEF -> VARIABLE_DEF
 ...
 |   |--IDENT -> x
 |   `--ASSIGN -> =
 |       `--EXPR -> EXPR
 |           `--MINUS -> -
```

### PR DESCRIPTION
**Pull request by nrmancuso**
Closes #15082.

Link to report workflow: https://github.com/nrmancuso/checkstyle-diff-report-generator/actions/runs/9614065671

Projects file: projects-to-test-on.properties
Patch branch: issue-15082

https://checkstyle-reports.s3.us-east-2.amazonaws.com/reports/issue-15082/2024-06-21-T-15-06-41/part1/index.html

No diff.

https://checkstyle-reports.s3.us-east-2.amazonaws.com/reports/issue-15082/2024-06-21-T-15-06-41/part4/index.html

We will need to explore BooleanExpressionComplexity in https://github.com/checkstyle/checkstyle/issues/15044

https://checkstyle-reports.s3.us-east-2.amazonaws.com/reports/issue-15082/2024-06-21-T-15-06-41/part5/index.html

No diff

https://checkstyle-reports.s3.us-east-2.amazonaws.com/reports/issue-15082/2024-06-21-T-15-06-41/part3/index.html

We will need to explore UnnecessaryParentheses in https://github.com/checkstyle/checkstyle/issues/14972, looks like we fixed some false positives and false negatives

https://checkstyle-reports.s3.us-east-2.amazonaws.com/reports/issue-15082/2024-06-21-T-15-06-41/part2/index.html

No diff

https://checkstyle-reports.s3.us-east-2.amazonaws.com/reports/issue-15082/2024-06-21-T-15-06-41/part6/index.html

No diff

https://checkstyle-reports.s3.us-east-2.amazonaws.com/reports/issue-15082/2024-06-21-T-15-06-41/sevntu-check-regression_part_1/index.html

No diff

https://checkstyle-reports.s3.us-east-2.amazonaws.com/reports/issue-15082/2024-06-21-T-15-06-41/sevntu-check-regression_part_2/index.html

No diff

https://checkstyle-reports.s3.us-east-2.amazonaws.com/reports/issue-15082/2024-06-21-T-15-06-41/antlr-report-checkstyle/index.html

All expected diffs

### CODE REVIEW

File: src/test/java/com/puppycrawl/tools/checkstyle/JavaAstVisitorTest.java [hunk 1]
```diff
@@ -164,6 +165,42 @@ public void testOrderOfVisitMethodsAndProductionRules() throws Exception {
...
+     * The reason we have this test is that we forgot to add the imaginary 'EXPR' node
+     * to a production rule in the parser grammar (we should have used 'expression'
+     * instead of 'expr'). This test is a reminder to question the usage of the 'expr' parser
+     * rule in the parser grammar when we update the count to make sure we are not missing
+     * an imaginary 'EXPR' node in the AST.
+     *
+     * @throws IOException if file does not exist
+     */
+    @Test
+    public void countExprUsagesInParserGrammar() throws IOException {
```
Comment (nrmancuso) [inline src/test/java/com/puppycrawl/tools/checkstyle/JavaAstVisitorTest.java:178]: Hopefully we can prevent this in the future. I had considered using a custom check for this, and a few other things that included individual suppressions, but really we should not need to get this crazy. As long as we can explain why we increase the number of expected usages of the `expr` rule, we should be fine. I placed a comment directly above this value so that we will notice updates to this number and catch it in review.

File: src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/grammar/antlr4/ExpectedAntlr4AstRegressionCaseDefault.txt [hunk 2]
```diff
@@ -71,14 +72,15 @@ COMPILATION_UNIT -> COMPILATION_UNIT [2:0]
...
         |       |   |   |   |       |   |   `--IDENT -> s [10:25]
-        |       |   |   |   |       |   `--GT -> > [10:41]
-        |       |   |   |   |       |       |--METHOD_CALL -> ( [10:38]
-        |       |   |   |   |       |       |   |--DOT -> . [10:31]
-        |       |   |   |   |       |       |   |   |--IDENT -> s [10:30]
-        |       |   |   |   |       |       |   |   `--IDENT -> length [10:32]
-        |       |   |   |   |       |       |   |--ELIST -> ELIST [10:39]
-        |       |   |   |   |       |       |   `--RPAREN -> ) [10:39]
-        |       |   |   |   |       |       `--NUM_INT -> 6 [10:43]
+        |       |   |   |   |       |   `--EXPR -> EXPR [10:41]
```
Comment (nrmancuso) [inline src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/grammar/antlr4/ExpectedAntlr4AstRegressionCaseDefault.txt:75]: All diffs in AST files are expected, we have just added a new `EXPR` node parent to each.

**Review by nrmancuso — COMMENTED** [review]
Comments:

File: src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/grammar/java19/ExpectedJava19PatternsTrickyWhenUsage.txt [hunk 3]
```diff
@@ -141,9 +142,10 @@ COMPILATION_UNIT -> COMPILATION_UNIT [2:0]
 |       |       |   |       |   |           |   |--TYPE -> TYPE [20:17]
 |       |       |   |       |   |           |   |   `--IDENT -> Integer [20:17]
 |       |       |   |       |   |           |   `--IDENT -> when [20:25]
-|       |       |   |       |   |           `--GE -> >= [20:40]
-|       |       |   |       |   |               |--IDENT -> when [20:35]
-|       |       |   |       |   |               `--NUM_INT -> 0 [20:43]
+|       |       |   |       |   |           `--EXPR -> EXPR [20:40]
+|       |       |   |       |   |               `--GE -> >= [20:40]
+|       |       |   |       |   |                   |--IDENT -> when [20:35]
```
Comment (rnveach) [inline src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/grammar/java19/ExpectedJava19PatternsTrickyWhenUsage.txt:147]: I see a concern and will put it in a new issue.

**Review by rnveach — APPROVED** [review]
My concerns are being addressed in new issues.

**Review by mahfouz72 — APPROVED** [review]
Thank a lot for the quick fix!

**Comment by romani** [comment]
This PR needs laptop time.
Pattern changed, and I don't see why it should.

File: src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/grammar/java19/ExpectedJava19PatternsTrickyWhenUsage.txt (hunk 3 above)
Comment (romani) [reply src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/grammar/java19/ExpectedJava19PatternsTrickyWhenUsage.txt:147]: https://github.com/checkstyle/checkstyle/blob/d951e083e6f631937374678adfbeafc67fe45424/src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/grammar/java19/InputJava19PatternsTrickyWhenUsage.java#L18-L22

File: src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/grammar/java21/ExpectedUnnamedVariableSwitch.txt [hunk 4]
```diff
@@ -715,13 +716,14 @@ COMPILATION_UNIT -> COMPILATION_UNIT [2:0]
...
-        |       |   |       |   |   |               |   `--IDENT -> String [84:55]
-        |       |   |       |   |   |               `--IDENT -> s [84:62]
+        |       |   |       |   |   |       `--EXPR -> EXPR [84:44]
+        |       |   |       |   |   |           `--LITERAL_INSTANCEOF -> instanceof [84:44]
+        |       |   |       |   |   |               |--IDENT -> o2 [84:41]
+        |       |   |       |   |   |               `--PATTERN_VARIABLE_DEF -> PATTERN_VARIABLE_DEF [84:55]
+        |       |   |       |   |   |                   |--MODIFIERS -> MODIFIERS [84:55]
+        |       |   |       |   |   |                   |--TYPE -> TYPE [84:55]
+        |       |   |       |   |   |                   |   `--IDENT -> String [84:55]
+        |       |   |       |   |   |                   `--IDENT -> s [84:62]
```
Comment (romani) [inline src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/grammar/java21/ExpectedUnnamedVariableSwitch.txt:726]: https://github.com/checkstyle/checkstyle/blob/d951e083e6f631937374678adfbeafc67fe45424/src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/grammar/java21/InputUnnamedVariableSwitch.java#L84C42-L84C73

**Review by romani — APPROVED** [review]
ok to merge.
