### PR TITLE
Issue #18644: Fix SummaryJavadoc forbiddenSummaryFragments for tab-formatted code

### LINKED ISSUE #18644: False-negative: SummaryJavadoc:forbiddenSummaryFragments for tab-formatted code
I have read check documentation: https://checkstyle.sourceforge.io/checks/javadoc/summaryjavadoc.html#forbiddenSummaryFragments
I have downloaded the latest checkstyle from: https://checkstyle.org/cmdline.html#Download_and_Run
I have executed the cli and showed it below, as cli describes the problem better than 1,000 words

```
E:\temp\CheckstyleReport>type config.xml
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
          "-//Puppy Crawl//DTD Check Configuration 1.3//EN"
          "https://checkstyle.org/dtds/configuration_1_3.dtd">
<module name="Checker">
  <module name="TreeWalker">
    <module name="SummaryJavadoc">
      <property name="forbiddenSummaryFragments"
        value="^@return the *|^This method returns |^A [{]@code [a-zA-Z0-9]+[}]( is a )|^[a-z]"/>
    </module>
  </module>
</module>

E:\temp\CheckstyleReport>type Test.java
class Test {
        /**
         * adds an element to the list.
         *
         * @param element the element to add
         */
        public void add(String element) {}
}

E:\temp\CheckstyleReport>set RUN_LOCALE="-Duser.language=en -Duser.country=US"

E:\temp\CheckstyleReport>java %RUN_LOCALE% -jar checkstyle-13.0.0-all.jar -c config.xml Test.java
Starting audit...
Audit done.

E:\temp\CheckstyleReport>
```
**Describe what you expect in detail.**
Since Javadoc summary starts from lowercase and since `forbiddenSummaryFragments` has a pattern part `^[a-z]` I'd assume there should be reported a violation.

However it's not reported (NOTE: the file is tab-formatted).

---

### PR DESCRIPTION
**Pull request by pirzada-ahmadfaraz**
Fixes #18644

## Summary

The `JAVADOC_MULTILINE_TO_SINGLELINE_PATTERN` regex in `SummaryJavadocCheck` only matched spaces before asterisks (`\n +(\*)`), not tabs. When Javadoc continuation lines used tabs (e.g., `\t * text`), the pattern failed to match, leaving the asterisk in the processed string.

This caused `forbiddenSummaryFragments` patterns like `^[a-z]` to fail because the string started with `*` instead of the actual summary text.

## Changes

- Changed the pattern from `\n +(\*)` to `\n[ \t]+(\*)` to match both spaces and tabs before the asterisk
- Added test case with tab-formatted Javadoc to verify the fix

## Test

The new test `testForbiddenFragmentsTabFormatted` verifies that `forbiddenSummaryFragments = ^[a-z]` correctly detects a violation when the Javadoc summary starts with a lowercase letter in tab-formatted code.

### CODE REVIEW

File: src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/summaryjavadoc/InputSummaryJavadocForbiddenFragmentsTabFormatted.java [hunk 1]
```diff
@@ -0,0 +1,27 @@
...
+
+*/
+
+
+package com.puppycrawl.tools.checkstyle.checks.javadoc.summaryjavadoc;
+
+public class InputSummaryJavadocForbiddenFragmentsTabFormatted {
+	// violation below, 'Forbidden summary fragment'
+	/**
+	 * adds an element to the list.
```
Comment (romani) [inline src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/summaryjavadoc/InputSummaryJavadocForbiddenFragmentsTabFormatted.java:16]: if there is TAB, it is not visible, use text to hint this.


`* this line has tab before asterisk.`

**Comment by pirzada-ahmadfaraz** [comment]
Hey @romani, I've added a note explaining the tab indentation before the package statement:

```java
// Note: This file uses tab indentation. The Javadoc continuation lines
// have tab characters before the asterisks (e.g., "\t *" not " *").
```

Let me know if you'd prefer the hint in a different format.

Also, the CI failures seem to be infrastructure-related (Docker build failures, etc.) rather than test failures - the tests pass locally. Could you re-trigger the CI when you get a chance?

**Comment by romani** [comment]
not and infra problems.

Please [read](https://github.com/checkstyle/checkstyle/blob/master/.github/CONTRIBUTING.md#getting-started) and watch videos at [Starting_Development](https://checkstyle.org/beginning_development.html#Starting_Development).
Please make CI green. watch all videos, they explains how to investigate CI failures.

**Comment by pirzada-ahmadfaraz** [comment]
@romani all good?

**Comment by romani** [comment]
Github, generate report for SummaryJavadoc/all-examples-in-one

**Comment by pirzada-ahmadfaraz** [comment]
@romani updates on this?

**Comment by romani** [comment]
@pirzada-ahmadfaraz  , in next PR please trigger this diff report your self and write comment to explicitly state that you reviewed all in it and all is valid changes.

it will speed up PR acceptance, see you in other PR.
Thanks a lot for your help.
