### PR TITLE
Issue #14937: Removed PER_MODULE_TESTS_RULES_LIST from XdocsPagesTest

### LINKED ISSUE #14937: Migrate google style guide tests to follow chapter wise testing
Currently the google style guide tests are implemented as `Per Module Testing` approach. We need to migrate these tests to use `Chapter Wise Testing` approach.

#### What is Per Module Testing?
The testing approach in which every modules used in a rule will have its special test file. All of these different test files will test different areas of the rule to ensure that we follow the rule correctly. 

#### What is Per Module Testing?
The testing approach in which there will be only one test file which will combine all the different modules used for the corresponding rule and ensure we follow the rule correctly. We combine different modules into single test and test the rule as whole.

The support to test `Chapter wise testing`'s documentation was added in this PR: https://github.com/checkstyle/checkstyle/pull/14925

#### Final Goal:
Migrate all google tests to chapter wise testing by combining different modules into single test file and update the coverage page accordingly. 

Following sections needs to be migrated:

- [x] 2.1 File name
- [x] 2.3.1 Whitespace characters
- [x] 2.3.2 Special escape sequences
- [x] 2.3.3 Non-ASCII characters
- [x] 3 Source file structure
- [x] 3.2 Package statement
- [x] 3.3.1 No wildcard imports
- [x] 3.3.2 No line-wrapping
- [x] 3.3.3 Ordering and spacing
- [x] 3.4.1 Exactly one top-level class declaration
- [x] 3.4.2.1 Overloads: never split
- [x] 4.1.1 Use of optional braces
- [x] 4.1.2 Nonempty blocks: K & R style
- [x] 4.1.3 Empty blocks: may be concise
- [x] 4.2 Block indentation: +2 spaces
- [x] 4.3 One statement per line
- [x] 4.4 Column limit: 100
- [x] 4.5.1 Where to break
- [x] 4.5.2 Indent continuation lines at least +4 spaces
- [x] 4.6.1 Vertical Whitespace
- [x] 4.6.2 Horizontal whitespace
- [x] 4.8.2.1 One variable per declaration
- [x] 4.8.2.2 Declared when needed
- [x] 4.8.3.2 No C-style array declarations
- [x] 4.8.4.1 Indentation
- [x] 4.8.4.2 Fall-through: commented
- [x] 4.8.4.3 Presence of the default label
- [x] 4.8.6.1 Block comment style
- [x] 4.8.7 Modifiers
- [x] 4.8.8 Numeric Literals
- [x] 5.2.1 Package names
- [x] 5.2.2 Class names
- [x] 5.2.3 Method names
- [x] 5.2.5 Non-constant field names
- [x] 5.2.6 Parameter names
- [x] 5.2.7 Local variable names
- [x] 5.2.8 Type variable names
- [x] 5.3 Camel case: defined
- [x] 6.2 Caught exceptions: not ignored
- [x] 6.4 Finalizers: not used
- [x] 7.1.1 General form
- [x] 7.1.2 Paragraphs
- [x] 7.1.3 Block tags
- [x] 7.2 The summary fragment
- [x] 7.3 Where Javadoc is used
- [x] 7.3.1 Exception: self-explanatory methods
- [x] 7.3.2 Exception: overrides
- [x] 7.3.4 Non-required Javadoc

### PR DESCRIPTION
**Pull request by Zopsss**
Closes #14937 

Removed the `PER_MODULE_TESTS_RULES_LIST` used in migration of sections to chapter wise testing

### CODE REVIEW

File: src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsPagesTest.java [hunk 1]
```diff
@@ -226,14 +226,6 @@ public class XdocsPagesTest {
     private static final Set<String> GOOGLE_MODULES = Collections.unmodifiableSet(
         CheckUtil.getConfigGoogleStyleModules());
 
-    // Contains all the sections which are not migrated to chapter wise testing
-    // in google style documentation.
-    // This list will be removed once all the sections are migrated.
-    // until https://github.com/checkstyle/checkstyle/issues/14937
```
Comment (rnveach) [inline src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsPagesTest.java:232]: Looks like this shouldn't be a minor commit. I assume this closes the issue also, so the first post should say so.

**Review by rnveach — CHANGES_REQUESTED** [review]

File: src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsPagesTest.java (hunk 1 above)
Comment (romani) [reply src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsPagesTest.java:232]: Prefix should be referencing #14937 .

This PR will close this issue

**Review by rdiachenko — APPROVED** [review]
lgtm

File: src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsPagesTest.java (hunk 1 above)
Comment (romani) [reply src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsPagesTest.java:232]: We have strange 4.8.5.2

https://github.com/checkstyle/checkstyle/blob/b16e96a757ccee5be66fabb8e666823ca3cb558a/src/it/java/com/google/checkstyle/test/chapter4formatting/rule4852classannotations/ClassAnnotationsTest.java#L36
Vs
https://checkstyle.org/google_style.html#a4.8.5

@Zopsss , please clarify what is going on

**Comment by Zopsss** [comment]
GitHub, generate site

File: src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsPagesTest.java (hunk 1 above)
Comment (Zopsss) [reply src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsPagesTest.java:232]: > We have strange 4.8.5.2

4.8.5.2 was converted to whole config testing, I took this section as an example when I was implementing `verifyWithWholeConfig` to show that how this method works in our tests. 

> Vs
> https://checkstyle.org/google_style.html#a4.8.5

This section was divided into smaller sections like 4.8.5.1, 4.8.5.2, 4.8.5.3 so there is no test for 4.8.5 but there are tests for its subsections, here's the how current website looks like:

https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/a0c4884_2024024517/google_style.html#a4.8.5

Comment (Zopsss) [reply src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsPagesTest.java:232]: > Prefix should be referencing https://github.com/checkstyle/checkstyle/issues/14937 .

Done, renamed the commit and PR

Comment (romani) [reply src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsPagesTest.java:232]: Ok, please create 4..8.5.1 Type-use annotations in table.

We need all paragraphs.
Please recheck that all paragraphs are present.

Comment (rnveach) [reply src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsPagesTest.java:232]: @romani Depending on what you consider a paragraph to be present, there could be more missing.

For example, we have 2.2 and then 2.3.1. While if you look at other similar numbered sections, we have 3.3 and 3.3.1 . It looks like we are missing 2.3 in this instance.
https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/a0c4884_2024024517/styleguides/google-java-style-20220203/javaguide.html#s2.3-special-characters

7.3.3 is also missing.

5.1's text mentions 5.2, but it's text is different from the label. `of` versus `by`.

I see these as a separate issue and should not be handled in this PR.

**Review by rnveach — APPROVED** [review]

File: src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsPagesTest.java (hunk 1 above)
Comment (romani) [reply src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsPagesTest.java:232]: I agree, will do separately https://github.com/checkstyle/checkstyle/issues/15217

**Review by romani — APPROVED** [review]
