### PR TITLE
Issue #8237: fixing no whitespace violation in empty constructors

### LINKED ISSUE #8237: WhitespaceAround ignores empty constructor whitespaces
Check documentation: https://checkstyle.org/config_whitespace.html#WhitespaceAround
```
>javac Test.java
>cat Test.java 
package com.example;

public class Test {
    private Test(){} // Does not worn about absent space between ")" and "{"
}

>cat config.xml 
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
        "-//Puppy Crawl//DTD Check Configuration 1.3//EN"
        "http://www.puppycrawl.com/dtds/configuration_1_3.dtd">
<module name="Checker">
    <module name="TreeWalker">
        <module name="WhitespaceAround">
            <property name="allowEmptyConstructors" value="true"/>
        </module>
    </module>
</module>
>java $RUN_LOCALE -jar checkstyle-8.32-all.jar -c config.xml Test.java
Starting audit...
Audit done
```
Expected: violation on the 4th line (constructor declaration). There should be space between `){`

Note, that this violation works Ok without `allowEmptyConstructors` option, but an extra violation is reported about empty constructors:
```
>cat config.xml 
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
        "-//Puppy Crawl//DTD Check Configuration 1.3//EN"
        "http://www.puppycrawl.com/dtds/configuration_1_3.dtd">
<module name="Checker">
    <module name="TreeWalker">
        <module name="WhitespaceAround">
        </module>
    </module>
</module>

>java $RUN_LOCALE -jar checkstyle-8.32-all.jar -c config.xml Test.java
Starting audit...
[ERROR] /Users/pavel/tmp/17/Test.java:4:19: '{' is not followed by whitespace. [WhitespaceAround]
[ERROR] /Users/pavel/tmp/17/Test.java:4:19: '{' is not preceded with whitespace. [WhitespaceAround]
[ERROR] /Users/pavel/tmp/17/Test.java:4:20: '}' is not preceded with whitespace. [WhitespaceAround]
Audit done.
Checkstyle ends with 3 errors.
```

I tested on Chekcstyle 8.32

### PR DESCRIPTION
**Pull request by Vyom-Yadav**
Resolves #8237: fixing no whitespace violation in empty constructors
Diff Regression projects: https://gist.githubusercontent.com/Vyom-Yadav/91807e6244cff60698d9e33e32ba2d51/raw/85355576c05c80e8b08752a62ba3a4076909d266/projects-to-test-on.properties
Diff Regression config: https://gist.githubusercontent.com/Vyom-Yadav/98dceb63a79f4833e85fff9b2e1464a6/raw/896bb68507934031a5ab4b785e093b7a31e684a8/my_checks.xml
Diff Regression patch config: https://gist.githubusercontent.com/Vyom-Yadav/273327b9c6cd6963b7dade792bc2c9c2/raw/88c882407bd3891076de4461f058b6ccc7fa8630/patch_config.xml
Report label: Final report.

### CODE REVIEW

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/WhitespaceAroundCheck.java [hunk 1]
```diff
@@ -901,6 +903,21 @@ private boolean isEmptyCtorBlock(DetailAST ast, int parentType) {
...
+     * constructor checked from SLIST token.
+     *
+     * @param ast the {@code DetailAST} to test.
+     * @return {@code true} if {@code ast} makes up part of a
+     *          constructor block.
+     */
+    private static boolean isCtorBlockCheckedFromSlist(DetailAST ast) {
+        return ast.getType() == TokenTypes.SLIST
+                && (ast.getParent().getType() == TokenTypes.CTOR_DEF
+                || ast.getParent().getType() == TokenTypes.COMPACT_CTOR_DEF);
```
Comment (Vyom-Yadav) [inline src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/WhitespaceAroundCheck.java:917]: @romani The pitest is failing but I think we would have to ignore it, reason-
Pitest is failing when `removed conditional - replaced equality check with true → SURVIVED` for both the lines 915 and 916
Now this will fail every time as when either one of them is replaced with `true` and it is a Constructor block, there are no other possibilities. What I mean is-
 ```
ast.getType() == TokenTypes.SLIST → true 
```
Then while visiting a `SLIST` token of a constructor, it can't be anything other than true, and this method is only concerned about constructors.

**Comment by Vyom-Yadav** [comment]
Github, generate report

**Comment by Vyom-Yadav** [comment]
The reports look fine to me.

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/WhitespaceAroundCheck.java (hunk 1 above)
Comment (rnveach) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/WhitespaceAroundCheck.java:917]: Pitest failure can't be "ignored". It must either be suppressed with a reason why it can't be fixed or the code must be changed to be satisfied.

If I understand the argument, if the parent is always a CTOR, then the current AST is always a SLIST. If this is the case then it seems we can drop the SLIST check and keep the other 2. If you are unsure, you can always use regression to prove it won't create any differences. See https://github.com/checkstyle/checkstyle/issues/7797 step 3+ for how to do that if you are unfamiliar.

**Comment by romani** [comment]
@Vyom-Yadav , please add tests to cover 
https://app.circleci.com/pipelines/github/checkstyle/checkstyle/5135/workflows/0e399517-6cfc-4d96-b43d-a1269be90cb3/jobs/76137
https://76137-12499251-gh.circle-artifacts.com/3/target/pit-reports/202103050525/com.puppycrawl.tools.checkstyle.checks.whitespace/WhitespaceAroundCheck.java.html#grouporg.pitest.mutationtest.report.html.SourceFile@6e22b712_915

**Review by romani — CHANGES_REQUESTED** [review]
pitest coverage should be 100%
please move  all distinct cases from diff report to UTs inputs
example - https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/noWhitespaceAroundEmptyCtor_2021065551/reports/diff/apache-ant/index.html#A1
diff report should not have cases that are not covered by unit tests.

**Comment by Vyom-Yadav** [comment]
Github, generate report

**Comment by Vyom-Yadav** [comment]
@romani Done

**Comment by Vyom-Yadav** [comment]
Github, generate report

**Comment by Vyom-Yadav** [comment]
> https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/noWhitespaceAroundEmptyCtor_2021101731/reports/diff/index.html

There were some problems, now fixed. I will highlight the final reports.

**Comment by Vyom-Yadav** [comment]
Github, generate report

**Comment by Vyom-Yadav** [comment]
> https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/noWhitespaceAroundEmptyCtor_2021124744/reports/diff/index.html

Final Report.

File: src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/whitespace/whitespacearound/InputWhitespaceAroundAllowEmptyCompactCtors.java [hunk 2]
```diff
@@ -63,6 +63,18 @@ record MyRecord6() {
     }
 
     record TestRecord7() {
-        public TestRecord7 {} // ok
+        public TestRecord7{} // violation, no WS before '{'
     }
```
Comment (romani) [inline src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/whitespace/whitespacearound/InputWhitespaceAroundAllowEmptyCompactCtors.java:67]: Please keep existing input java code unchanged. If need more case create new method/classes.
We can change only content of trailing comments

File: src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/whitespace/whitespacearound/InputWhitespaceAroundAllowEmptyCompactCtors.java [hunk 3]
```diff
@@ -63,6 +63,18 @@ record MyRecord6() {
...
+    class foo {
+        public foo() {}
+    }
+
+    class foo2 {
+        public foo2(){} // violation, no WS before '{'
+    }
+    class foo3 {
+            public foo3(){System.out.println();} // violation, no WS before '{'
+                                                 // and '}' and after '{'
```
Comment (romani) [inline src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/whitespace/whitespacearound/InputWhitespaceAroundAllowEmptyCompactCtors.java:78]: Please change comment to make it more clear

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/WhitespaceAroundCheck.java [hunk 4]
```diff
@@ -901,6 +903,20 @@ private boolean isEmptyCtorBlock(DetailAST ast, int parentType) {
...
+     * Test if the given {@code DetailAST} is a part of an
+     * empty constructor.
+     *
+     * @param ast the {@code DetailAST} to test.
+     * @return {@code true} if {@code ast} makes up part of an
+     *          empty constructor block.
+     */
+    private static boolean isEmptyCtorBlock(DetailAST ast) {
+        return (ast.getParent().getType() == TokenTypes.CTOR_DEF
+                || ast.getParent().getType() == TokenTypes.COMPACT_CTOR_DEF)
```
Comment (romani) [inline src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/WhitespaceAroundCheck.java:916]: +4 spaces in indentation, to visually see priority of execution

**Review by romani — CHANGES_REQUESTED** [review]
Items:

File: src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/whitespace/whitespacearound/InputWhitespaceAroundAllowEmptyCompactCtors.java (hunk 2 above)
Comment (Vyom-Yadav) [reply src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/whitespace/whitespacearound/InputWhitespaceAroundAllowEmptyCompactCtors.java:67]: I moved them out of the main class. I guess you were asking for this and not a new input file.

File: src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/whitespace/whitespacearound/InputWhitespaceAroundAllowEmptyCompactCtors.java (hunk 3 above)
Comment (Vyom-Yadav) [reply src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/whitespace/whitespacearound/InputWhitespaceAroundAllowEmptyCompactCtors.java]: done

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/WhitespaceAroundCheck.java (hunk 4 above)
Comment (Vyom-Yadav) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/WhitespaceAroundCheck.java]: done

**Comment by Vyom-Yadav** [comment]
@romani ping

**Comment by Vyom-Yadav** [comment]
@romani ping

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/WhitespaceAroundCheck.java [hunk 5]
```diff
@@ -800,6 +801,7 @@ private static boolean isAnonymousInnerClassEnd(int currentType, char nextChar)
     private boolean isEmptyBlock(DetailAST ast, int parentType) {
         return isEmptyMethodBlock(ast, parentType)
                 || isEmptyCtorBlock(ast, parentType)
+                && !isEmptyCtorBlock(ast)
```
Comment (pbludov) [inline src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/WhitespaceAroundCheck.java:804]: `isEmptyCtorBlock  && !isEmptyCtorBlock` looks impossible. Please merge this two methods into one.

**Review by pbludov — CHANGES_REQUESTED** [review]

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/WhitespaceAroundCheck.java (hunk 5 above)
Comment (Vyom-Yadav) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/WhitespaceAroundCheck.java:804]: `isEmptyCtorBlock && !isEmptyCtorBlock` cannot be merged into one as-
```
public class foo {
    public foo() {}
}
```
`isNotRelevantSituation` method has to be false for the tokens to be examined. If we merge them into one then we would have to remove it from `isNotRelevantSituation` and would have to add conditions in `shouldCheckSeparationFromPreviousToken` and `shouldCheckSeparationFromNextToken`. Moreover while writing these conditions in `shouldCheckSeparation...` methods we cannot use
`isEmptyCtorBlock(DetailAST ast, int parentType)` as we have to examine `SLIST` and `RCURLY` tokens separately. 

I agree that in the current solution `isEmptyCtorBlock(DetailAST ast, int parentType)` is returning true whereas `!isEmptyCtorBlock(DetailAST ast)` is returning false for the same condition. 

**What can be done-**

- `isEmptyCtorBlock(DetailAST ast, int parentType)` can be completely removed. 
- A new method `isEmptyCtorBlockCheckedFromRcurly(DetailAST ast)` can be added. 
- `isEmptyCtorBlock(DetailAST ast)` can be renamed to `isEmptyCtorBlockCheckedFromSlist(DetailAST ast)`
- Finally instead of `isEmptyCtorBlock && !isEmptyCtorBlock`, 
```!isEmptyCtorBlockCheckedFromSlist && isEmptyCtorBlockCheckedFromRcurly``` can be added.

**What I suggest-**
As these methods can't be merged into one, separating them will be good but won't result in a DRY code, 
`isEmptyBlock(DetailAST ast, int parentType, int match)` already checks for `RCURLY` token.

While `isEmptyCtorBlock && !isEmptyCtorBlock` always returns false for `SLIST` token but conditions have been added to 
`shouldCheckSeparationFromNextToken` to prevent any bad behaviour.

Rest I'll proceed as you say.

Comment (pbludov) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/WhitespaceAroundCheck.java:804]: Thank you for the detailed explanation.

>     * Finally instead of `isEmptyCtorBlock && !isEmptyCtorBlock`,
>       `!isEmptyCtorBlockCheckedFromSlist && isEmptyCtorBlockCheckedFromRcurly` can be added.

This option will be most clear for the next ones who will change the code in the future.

**Comment by Vyom-Yadav** [comment]
Github, generate report

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/WhitespaceAroundCheck.java (hunk 5 above)
Comment (Vyom-Yadav) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/WhitespaceAroundCheck.java]: Done.

**Review by pbludov — APPROVED** [review]

**Comment by Vyom-Yadav** [comment]
@romani @rnveach Kindly complete review.
