### PR TITLE
Issue #10945: fix wrap check for annotation array

### LINKED ISSUE #10945: OperatorWrap with token ASSIGN too strict for annotations
I have read check documentation: https://checkstyle.sourceforge.io/config_whitespace.html#OperatorWrap
I have downloaded the latest checkstyle from: https://checkstyle.org/cmdline.html#Download_and_Run
I have executed the cli and showed it below, as cli describes the problem better than 1,000 words

```bash
/var/tmp $ javac OperatorWrapExample.java

/var/tmp $ cat config.xml
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
        "-//Checkstyle//DTD Checkstyle Configuration 1.3//EN"
        "https://checkstyle.org/dtds/configuration_1_3.dtd">
<module name="Checker">
  <module name="TreeWalker">
    <module name="OperatorWrap">
      <property name="tokens" value="ASSIGN"/>
    </module>
  </module>
</module>

/var/tmp $ cat OperatorWrapExample.java
@Annotation(example = {
        "foo",
        "bar"
})
public class OperatorWrapExample {

    public String[] array = {
            "foo",
            "bar"
    };
}

@interface Annotation {
    String[] example();
}

/var/tmp $ RUN_LOCALE="-Duser.language=en -Duser.country=US"
/var/tmp $ java $RUN_LOCALE -jar checkstyle-9.1-all.jar -c config.xml OperatorWrapExample.java
Starting audit...
[ERROR] I:\_tmp\_checkstyle\OperatorWrapExample.java:1:21: '=' should be on a new line. [OperatorWrap]
Audit done.
Checkstyle ends with 1 errors.
```

---

In the above example, the array field allows the first element to be on a new line. If the same is done for an annotation, Checkstyle complains. The only way to "fix" this is to put the first element on the same line as the `= {`. I expect the same behaviour in annotations as in other code.

### PR DESCRIPTION
**Pull request by strkkk**
Closes #10945, fixed wrapping for assign of annotation array

Diff Regression config: https://gist.githubusercontent.com/strkkk/31749e0743553a606f69fdfc6670d780/raw/2d7b9780d1fee9def8b7671b8a96e2490021575f/confg.xml

### CODE REVIEW

**Comment by strkkk** [comment]
Github, generate report

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/OperatorWrapCheck.java [hunk 1]
```diff
@@ -423,12 +423,7 @@ private static DetailAST getRightNode(DetailAST node) {
             result = adjustParens(rightNode, DetailAST::getPreviousSibling);
         }
 
-        // The ARRAY_INIT AST is confusing. It should be
-        // ARRAY_INIT
-        // |--LCURLY (first child)
-        // `--RCURLY (last child)
-        // but there is no LCURLY for ARRAY_INIT
```
Comment (strkkk) [inline src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/OperatorWrapCheck.java:430]: @pbludov I removed your comment since condition is changed and it is not about only ARRAY_INIT anymore. Is it ok or comment should be changed?

**Comment by romani** [comment]
Looks good. I reviewed all projects in report.

Please add in input:
Few arrays https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/34d14ed_2021151032/reports/diff/apache-struts/index.html#A13

Array as not first item https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/34d14ed_2021151032/reports/diff/hibernate-orm/index.html#A1

Array in nested annotation https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/34d14ed_2021151032/reports/diff/hibernate-orm/index.html#A4
https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/34d14ed_2021151032/reports/diff/infinispan/index.html#A5

**Review by pbludov — APPROVED** [review]

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/OperatorWrapCheck.java (hunk 1 above)
Comment (pbludov) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/OperatorWrapCheck.java:430]: Yes, of course. The comment itself is also confusing. Changing `ARRAY_INIT` is very difficult and doesn't make sense.

**Comment by strkkk** [comment]
> Please add in input:

@romani done

**Review by romani — APPROVED** [review]

**Comment by romani** [comment]
Wercker restarted
