### PR TITLE
Fix #7187: RightCurlyCheck false positives fixed. 

### LINKED ISSUE #7187: RightCurlyCheck: False Positive with SAME or ALONE_OR_SINGLELINE
https://checkstyle.org/config_blocks.html#RightCurly

`RightCulryCheck.java` gives false positives in case of `RightCurlyOption.SAME` and `RightCurlyOptioon.ALONE_OR_SINGLELINE` in case of tokens like `CLASS_DEF`, `METHOOD_DEF`, `ANNOOTATION_DEF` etc.

```
$ javac YOUR_FILE.java

$ cat test_config_same.xml

<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
          "-//Puppy Crawl//DTD Check Configuration 1.3//EN"
          "http://www.puppycrawl.com/dtds/configuration_1_3.dtd">

<module name="Checker">
    <property name="charset" value="UTF-8"/>

    <module name="TreeWalker">
            <module name="RightCurly">
             <property name="tokens" 
        value="LITERAL_TRY, LITERAL_CATCH, LITERAL_FINALLY, LITERAL_IF, 
                    LITERAL_ELSE, CLASS_DEF, METHOD_DEF, CTOR_DEF, 
                    LITERAL_FOR, LITERAL_WHILE, LITERAL_DO, 
                    STATIC_INIT, INSTANCE_INIT"/>
            <property name="option" value="same"/>
    </module>
    </module>
</module>

$ cat test_config_alone_or_single.xml

<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
          "-//Puppy Crawl//DTD Check Configuration 1.3//EN"
          "http://www.puppycrawl.com/dtds/configuration_1_3.dtd">

<module name="Checker">
    <property name="charset" value="UTF-8"/>

    <module name="TreeWalker">
            <module name="RightCurly">
             <property name="tokens" 
                    value="LITERAL_TRY, LITERAL_CATCH, LITERAL_FINALLY, LITERAL_IF, 
                               LITERAL_ELSE, CLASS_DEF, METHOD_DEF, CTOR_DEF, 
                               LITERAL_FOR, LITERAL_WHILE, LITERAL_DO, 
                               STATIC_INIT, INSTANCE_INIT"/>
            <property name="option" value="alone_or_singleline"/>
    </module>
    </module>
</module>

$ cat TestClass.java

public class TestClass {

	public TestClass() {}; //violation
	
	public void doSomething(){}; //violation
}; //violation

$ java -Duser.language=en -Duser.country=US -jar checkstyle-8.26-all.jar \
            -c test_config_same.xml TestClass.java

Starting audit...
[ERROR] /TestClass.java:3:29: '}' at column 22 should be alone on a line. [RightCurly]
[ERROR] /TestClass.java:5:35: '}' at column 28 should be alone on a line. [RightCurly]
[ERROR] /TestClass.java:6:1: '}' at column 1 should be alone on a line. [RightCurly]
Audit done.
Checkstyle ends with 3 errors.

$ java -Duser.language=en -Duser.country=US -jar checkstyle-8.26-all.jar \
     -c test_config_alone_or_single.xml TestClass.java

Starting audit...
[ERROR] /TestClass.java:3:29: '}' at column 22 should be alone on a line. [RightCurly]
[ERROR] /TestClass.java:5:35: '}' at column 28 should be alone on a line. [RightCurly]
[ERROR] /TestClass.java:6:1: '}' at column 1 should be alone on a line. [RightCurly]
Audit done.
Checkstyle ends with 3 errors.
```

As can seen above in case of `RightCurlyOption.SAME` and `RightCurlyOption.ALONE_OR_SINGLELINE` a violation is raised which should not be the case.

### PR DESCRIPTION
**Pull request by sd1998**
Fix for issue #7187.
This PR is blocker for PR #7039 .
 
RightCurlyCheck false positives fixed.  For various tokens like `CLASS_DEF`, `METHOD_DEF` etc.

Regression report: 
https://sd1998.github.io/checkstyle-regression/Fix-7187/index.html

Base Config:
https://sd1998.github.io/checkstyle-regression/Fix-7187/base_config.xml

Patch Config:
https://sd1998.github.io/checkstyle-regression/Fix-7187/patch_config.xml

Report repository:
https://github.com/sd1998/checkstyle-regression/tree/master/Fix-7187

### CODE REVIEW

**Comment by rnveach** [comment]
@sd1998 There are pitest and test failures in CI.

**Comment by romani** [comment]
There are still CI problems, please fix.
Humans do review after CI. If you do not know how to resolve CI issues, please let us know

**Comment by sd1998** [comment]
@romani Yes the issue only lie with branch coverage I will add more examples to fix it.

**Comment by romani** [comment]
please rebase over latest master and provide fixes for code coverage (jacoco and pitest)

**Comment by romani** [comment]
@sd1998 , please find time to finish this PR.

**Comment by sd1998** [comment]
@romani I have fixed all the Travis CI issue the only one remaining is the one corresponding to Issue not being approved yet.

**Comment by sd1998** [comment]
@romani I have fixed all the Travis CI issue the only one remaining is the one corresponding to Issue not being approved yet.

**Comment by romani** [comment]
@sd1998 , please update issue to strictly follow template, I need to make sure that you used our CLI to reproduce issue.

**Comment by sd1998** [comment]
@romani All CI failures have been resolved.

**Comment by romani** [comment]
@pbludov , please do first review

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/blocks/RightCurlyCheck.java [hunk 1]
```diff
@@ -241,14 +241,24 @@ private static boolean shouldBeAloneOnLineWithAloneOption(Details details,
...
+     *         option is used.
      */
     private static boolean shouldBeAloneOnLineWithNotAloneOption(Details details,
                                                                  String targetSrcLine) {
         return shouldBeAloneOnLineWithAloneOption(details, targetSrcLine)
                 && !isSingleLineBlock(details);
     }
 
+    /**
+     * Checks weather right curly is followed by a semicolon.
```
Comment (pbludov) [inline src/main/java/com/puppycrawl/tools/checkstyle/checks/blocks/RightCurlyCheck.java]: `Checks whether the right curly is followed by a semicolon.`

File: src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/rightcurly/InputRightCurlyAloneOrSingleline.java [hunk 2]
```diff
@@ -209,4 +209,21 @@ public void codeAfterLastRightCurly() {
         }; // violation
         for (int i = 0; i < 1; i++) { new Object(); }; // violation
     }
+
+    public void testMethod() {}; //violation
+
+    public void testMethod1() {
+    }; //violation
```
Comment (pbludov) [inline src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/rightcurly/InputRightCurlyAloneOrSingleline.java]: It is not clear, how to avoid the violation for `alone or singleline`.
Please add
```
    public void testMethod1() {
    }
    ; // OK
```
Or how it should be.

**Comment by romani** [comment]
@pbludov , it is better to keep issues assigned to you, outside contibutors can not change assignee of issue (it is special permission in github).

**Comment by romani** [comment]
@pbludov, please periodically pin contributors, it helps to finish PR.

@sd1998, I see some changes, did you address review comments ? It is better to reply "done" to each point to give us signal that you are ready, and it is not just some intermediate changes.

Hint: to fix Teamcity , please rebase to latest master, fix for it already merged

**Comment by romani** [comment]
@sd1998 , ping.

File: src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/rightcurly/InputRightCurlyAloneOrSingleline.java (hunk 2 above)
Comment (romani) [reply src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/rightcurly/InputRightCurlyAloneOrSingleline.java]: done

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/blocks/RightCurlyCheck.java (hunk 1 above)
Comment (romani) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/blocks/RightCurlyCheck.java]: done.

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/blocks/RightCurlyCheck.java [hunk 3]
```diff
@@ -241,14 +241,24 @@ private static boolean shouldBeAloneOnLineWithAloneOption(Details details,
      * @param details details for validation.
      * @param targetSrcLine A string with contents of rcurly's line
      * @return true, if right curly should be alone on line
-     *         when ALONE_OR_SINGLELINE or SAME option is used.
+     *         when ALONE_OR_SINGLELINE or SAME
+     *         option is used.
```
Comment (rnveach) [inline src/main/java/com/puppycrawl/tools/checkstyle/checks/blocks/RightCurlyCheck.java]: This looks like an unnecessary change.

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/blocks/RightCurlyCheck.java [hunk 4]
```diff
@@ -241,14 +241,24 @@ private static boolean shouldBeAloneOnLineWithAloneOption(Details details,
...
         return shouldBeAloneOnLineWithAloneOption(details, targetSrcLine)
                 && !isSingleLineBlock(details);
     }
 
+    /**
+     * Checks whether the right curly is followed by a semicolon.
+     * @param details details for validation.
+     * @return true if the block ends with a semicolon.
+     */
+    private static boolean endsWithSemicolon(Details details) {
```
Comment (rnveach) [inline src/main/java/com/puppycrawl/tools/checkstyle/checks/blocks/RightCurlyCheck.java]: Shouldn't this method go after the only method that calls it?

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/blocks/RightCurlyCheck.java [hunk 5]
```diff
@@ -241,14 +241,24 @@ private static boolean shouldBeAloneOnLineWithAloneOption(Details details,
...
     private static boolean shouldBeAloneOnLineWithNotAloneOption(Details details,
                                                                  String targetSrcLine) {
         return shouldBeAloneOnLineWithAloneOption(details, targetSrcLine)
                 && !isSingleLineBlock(details);
     }
 
+    /**
+     * Checks whether the right curly is followed by a semicolon.
+     * @param details details for validation.
+     * @return true if the block ends with a semicolon.
```
Comment (rnveach) [inline src/main/java/com/puppycrawl/tools/checkstyle/checks/blocks/RightCurlyCheck.java]: Main description says `right curly` while return says `block`. Can we synchronize the descriptions.

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/blocks/RightCurlyCheck.java (hunk 4 above)
Comment (rnveach) [inline src/main/java/com/puppycrawl/tools/checkstyle/checks/blocks/RightCurlyCheck.java]: What about making this method start with a boolean type name?
Like `isSemicolonOnEnd`?

File: src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/rightcurly/InputRightCurlyAloneOrSingleline.java [hunk 6]
```diff
@@ -209,4 +209,25 @@ public void codeAfterLastRightCurly() {
...
+
+    public class TestClass {}; //violation
```
Comment (rnveach) [inline src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/rightcurly/InputRightCurlyAloneOrSingleline.java]: Why is this a violation? The method is singleline, shouldn't that take precedence over alone?

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/blocks/RightCurlyCheck.java [hunk 7]
```diff
@@ -306,7 +315,7 @@ private static boolean isSingleLineBlock(Details details) {
             nextToken = Details.getNextToken(doWhileSemi);
         }
         return rcurly.getLineNo() == lcurly.getLineNo()
-                && rcurly.getLineNo() != nextToken.getLineNo();
+                && (rcurly.getLineNo() != nextToken.getLineNo() || endsWithSemicolon(details));
```
Comment (rnveach) [inline src/main/java/com/puppycrawl/tools/checkstyle/checks/blocks/RightCurlyCheck.java]: Maybe I am just not understanding why the semicolon plays a role in this logic.

Comment (sd1998) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/blocks/RightCurlyCheck.java]: @rnveach The semicolon plays a role here because if the condition is `rcurly.getLineNo() != nextToken.getLineNo()` then for cases such as `public class TestClass {};` it will result in a violation because in this case the `nextToken` which is the semicolon is on the same line as `rcurly` thus to be able to account for cases where the `CLASS_DEF` or `METHOD_DEF` end with a semicolon `(rcurly.getLineNo() != nextToken.getLineNo() || endsWithSemicolon(details))` has to be used.

File: src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/rightcurly/InputRightCurlyAloneOrSingleline.java (hunk 6 above)
Comment (sd1998) [reply src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/rightcurly/InputRightCurlyAloneOrSingleline.java]: @rnveach Not a violation. I have fixed it.

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/blocks/RightCurlyCheck.java (hunk 4 above)
Comment (sd1998) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/blocks/RightCurlyCheck.java]: Done.

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/blocks/RightCurlyCheck.java (hunk 5 above)
Comment (sd1998) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/blocks/RightCurlyCheck.java]: Done.

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/blocks/RightCurlyCheck.java (hunk 4 above)
Comment (sd1998) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/blocks/RightCurlyCheck.java]: Done.

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/blocks/RightCurlyCheck.java (hunk 3 above)
Comment (sd1998) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/blocks/RightCurlyCheck.java]: Done.

**Comment by sd1998** [comment]
@romani I have made the change.

File: src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/rightcurly/InputRightCurlyAloneOrSingleline.java (hunk 6 above)
Comment (rnveach) [reply src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/rightcurly/InputRightCurlyAloneOrSingleline.java]: @sd1998 The same thing is at line 224 for the nested class.
> `public TestClass2() {}; //violation`

Is this isn't a violation, please look over the inputs and make sure all violations say violation and ones that aren't a violation don't say it.

**Comment by romani** [comment]
@sd1998 , please address unresolved items from @rnveach .

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/blocks/RightCurlyCheck.java (hunk 7 above)
Comment (rnveach) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/blocks/RightCurlyCheck.java]: Your reason just details alot of the code but I am questioning the higher level reasoning. The method is called `isSingleLine`. Semicolon has no bearing on if a block is a single line or not. So I don't understand why we are checking semicolon in this method.

Maybe the issue is the name of the method as it is already checking the next token. If this is so, maybe it should be renamed to something like `isSingleLineBlockAlone` and have the javadoc updated.

Please confirm.

Comment (sd1998) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/blocks/RightCurlyCheck.java]: @rnveach Yes the method should be renamed to `isSingleLineBlockAlone` I will make the change.

Comment (sd1998) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/blocks/RightCurlyCheck.java]: @rnveach I think it should be named as `isSingleLineBlockAndAloneOnLine` because it performs both the checks (i.e. Checking weather the block is on a single line and weather the block is alone on line)

File: src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/rightcurly/InputRightCurlyAloneOrSingleline.java (hunk 6 above)
Comment (sd1998) [reply src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/rightcurly/InputRightCurlyAloneOrSingleline.java]: Done

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/blocks/RightCurlyCheck.java (hunk 7 above)
Comment (sd1998) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/blocks/RightCurlyCheck.java]: I have changes the method name to `isBlockAloneOnSingleLine` and have updated the javadoc accordingly if any change is required in this please let me know.

File: src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/rightcurly/InputRightCurlyLeft.java [hunk 8]
```diff
@@ -195,4 +195,21 @@ public void codeAfterLastRightCurly() {
         public Thread newThread(final Runnable r) {
             return new Thread(r);
         }}; // violation
+
+    public void testMethod() {}; //violation
```
Comment (romani) [inline src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/rightcurly/InputRightCurlyLeft.java]: InputRightCurlyLeft.java is used in many tests and different config, we can not use "violation" comment as it is not always true.
Unfortunately old tests reused same inputs .... as we discovered later on it is not very maintainable approach.

Please do simple update:
move your tests code to separate Input file, that will be dedicated to exactly one test method.
please put in Input brief config in comment, good example - https://github.com/checkstyle/checkstyle/blob/master/src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/emptylineseparator/InputEmptyLineSeparatorClassDefinitionAndCommentNotSeparatedFromPackage.java

Please apply this to all other tests Inputs you changed. You can update existing Input only if it is used only in one test method.

Comment (sd1998) [reply src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/rightcurly/InputRightCurlyLeft.java]: Done

**Comment by romani** [comment]
I pushed minor changes:
```
$ git diff
diff --git a/src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/rightcurly/InputRightCurlyAloneBlocksWithSemi.java b/src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/rightcurly/InputRightCurlyAloneBlocksWithSemi.java
index 1a14310..0f5c7c9 100644
--- a/src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/rightcurly/InputRightCurlyAloneBlocksWithSemi.java
+++ b/src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/rightcurly/InputRightCurlyAloneBlocksWithSemi.java
@@ -1,5 +1,5 @@
 /*
- * Config = default
+ * Config:
  * option = alone
  * tokens = CLASS_DEF, METHOD_DEF, CTOR_DEF
  */
diff --git a/src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/rightcurly/InputRightCurlyAloneOrSingleLineBlocksWithSemi.java b/src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/rightcurly/InputRightCurlyAloneOrSingleLineBlocksWithSemi.java
index 30a31ea..4b6e22d 100644
--- a/src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/rightcurly/InputRightCurlyAloneOrSingleLineBlocksWithSemi.java
+++ b/src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/rightcurly/InputRightCurlyAloneOrSingleLineBlocksWithSemi.java
@@ -1,5 +1,5 @@
 /*
- * Config = default
+ * Config:
  * option = alone_or_singleline
  * tokens = CLASS_DEF, METHOD_DEF, CTOR_DEF
  */
diff --git a/src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/rightcurly/InputRightCurlySameBlocksWithSemi.java b/src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/rightcurly/InputRightCurlySameBlocksWithSemi.java
index 73d7bb2..dfb0e91 100644
--- a/src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/rightcurly/InputRightCurlySameBlocksWithSemi.java
+++ b/src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/rightcurly/InputRightCurlySameBlocksWithSemi.java
@@ -1,5 +1,5 @@
 /*
- * Config = default
+ * Config:
  * option = same
  * tokens = CLASS_DEF, METHOD_DEF, CTOR_DEF
  */

```
