### PR TITLE
Issue #8879: fix local variable detection in resource node

### LINKED ISSUE #8879: LocalFinalVariableName false-positive
cat config.xml
```xml
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
        "-//Checkstyle//DTD Checkstyle Configuration 1.3//EN"
        "https://checkstyle.org/dtds/configuration_1_3.dtd">
<module name="Checker">
  <module name="TreeWalker">
    <module name="LocalFinalVariableName"/>
  </module>
</module>
```

cat Test.java
```java
import java.util.concurrent.Semaphore;

public class Test {
	private static final Lock LOCK = new Lock();

	public void foo() {
		LOCK.lock();
		try (LOCK) { // violation
		}
	}
}

class Lock implements AutoCloseable {
	private final Semaphore semaphore;

	public Lock() {
		this.semaphore = new Semaphore(1);
	}

	public void lock() {
		try {
			semaphore.acquire();
		} catch (InterruptedException exception) {
			Thread.currentThread().interrupt();
		}
	}

	public void unlock() {
		semaphore.release();
	}

	@Override
	public void close() {
		unlock();
	}
}
```

java -Duser.language=en -Duser.country=US -jar checkstyle-8.36.2-all.jar -c config.xml Test.java
```
Starting audit...
[ERROR] /home/boris/Test.java:8:22: Name 'LOCK' must match pattern '^[a-z][a-zA-Z0-9]*$'. [LocalFinalVariableName]
Audit done.
Checkstyle ends with 1 errors.
```

---------------

`try (LOCK)` should be valid and no warning should be emitted.

### PR DESCRIPTION
**Pull request by strkkk**
Closes #8879 

Issue is in common method for local variable definition detection, thus several checks are affected.

Diff Regression projects: https://gist.githubusercontent.com/nmancus1/e3988f8092d919b5cbe70f5359c4d9e8/raw/a0f6f5860f8025c19868061dee6e0e40960b992f/projects-to-test-on.properties

Diff Regression config: https://gist.githubusercontent.com/strkkk/ac73db2366737f5a2d9ac0b3a39e81fa/raw/88d42f4621b0802ae77b8bc50e20d437afa5b763/8879.xml

Reg report (checks that invoke this method directly or via isClassDeclarationDef method)
https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/8879_local_variable_false_positive_2020151659/reports/diff/index.html

It shows that some other false positives have been fixed and also one NPE

### CODE REVIEW

**Comment by strkkk** [comment]
GitHub, generate report

**Review by pbludov — APPROVED** [review]
I'm OK to merge.
Interesting, that we have [NPE](https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/8879_local_variable_false_positive_2020151659/reports/diff/checkstyle/index.html) on master

File: src/main/java/com/puppycrawl/tools/checkstyle/utils/ScopeUtil.java [hunk 1]
```diff
@@ -266,7 +266,7 @@ public static boolean isLocalVariableDef(DetailAST node) {
         }
 
         if (node.getType() == TokenTypes.RESOURCE) {
-            localVariableDef = true;
+            localVariableDef = node.getChildCount() != 1;
```
Comment (pbludov) [inline src/main/java/com/puppycrawl/tools/checkstyle/utils/ScopeUtil.java:269]: Should it be `node.getChildCount() > 1` ?

Comment (strkkk) [reply src/main/java/com/puppycrawl/tools/checkstyle/utils/ScopeUtil.java]: Good catch, fixed

File: src/test/java/com/puppycrawl/tools/checkstyle/utils/ScopeUtilTest.java [hunk 2]
```diff
@@ -166,7 +166,18 @@ public void testIsLocalVariableDefUnexpected() {
 
     @Test
     public void testIsLocalVariableDefResource() {
-        assertTrue(ScopeUtil.isLocalVariableDef(getNode(TokenTypes.RESOURCE)), "invalid result");
+        final DetailAstImpl resourceTwoChildren = getNode(TokenTypes.RESOURCE);
+        final DetailAstImpl modifiers = new DetailAstImpl();
+        modifiers.setType(TokenTypes.MODIFIERS);
```
Comment (romani) [inline src/test/java/com/puppycrawl/tools/checkstyle/utils/ScopeUtilTest.java:171]: Can we avoid this type of tests ? 
We did do much to avoid this level of fakes that make no good to code.

**Review by romani — CHANGES_REQUESTED** [review]
Item:

File: src/test/java/com/puppycrawl/tools/checkstyle/utils/ScopeUtilTest.java (hunk 2 above)
Comment (strkkk) [reply src/test/java/com/puppycrawl/tools/checkstyle/utils/ScopeUtilTest.java:171]: This method checks node, so we need to provide a node to test. Another way is to parse some file, navigate to node and check result.
I do not like the way test is written, but it is common approach for this util class.
I suggest to create separate issue for refactoring of this test class to avoid using fake nodes.

**Comment by strkkk** [comment]
> Is there any ideas why we missed this?
Whole idea of running no-exception validations is to catch exception like this.

There is not so much code that uses such syntax as new try-with-resources
```
try (variable) {
}
```
so checks are happy.

**Comment by rnveach** [comment]
> There is not so much code that uses such syntax as new try-with-resources

Report is using master so this isn't a new file. History of the file says it was created in May.
https://github.com/checkstyle/checkstyle/commits/dabe0ff1576239d5623807f787bedea1020bbb23/src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/grammar/java9/InputAdvanceJava9TryWithResources.java

The file has been here long enough, if we have no exception testing for each CI run on master checkstyle, then this should have been caught.
From what I am seeing, https://github.com/checkstyle/checkstyle/blob/master/.ci/wercker.sh#L269-L283 , we have this test.

Do we know which specific check caused the exception?

**Comment by rnveach** [comment]
@romani 
> Is there any ideas why we missed this?

File is located in non-compilable. We ignore this folder for groovy. See https://github.com/checkstyle/contribution/blob/master/checkstyle-tester/projects-for-wercker.properties#L10 .

This is running with launch groovy which takes in to account ignored folders. See https://github.com/checkstyle/checkstyle/blob/master/.ci/wercker.sh#L279

The only way to catch these ignored folders is to run regression manually, removing all ignored folders, testing specifically for this.

File: src/test/java/com/puppycrawl/tools/checkstyle/utils/ScopeUtilTest.java (hunk 2 above)
Comment (romani) [reply src/test/java/com/puppycrawl/tools/checkstyle/utils/ScopeUtilTest.java:171]: what force you to create this test ?
We had several bad cases of test to satisfy pitest coverage that it split in several groups, so some cases claimed to be not reachable.

Comment (strkkk) [reply src/test/java/com/puppycrawl/tools/checkstyle/utils/ScopeUtilTest.java:171]: I am not the one who created this test, it was like this before. I modified the logic, and result for such dummy node (with no children) is changed. This will never happen in real life. Other conditions (1 child, 2+ children) are covered by test cases for checks, which is not good since it is indirect test.
So I added new cases to check changed logic directly.

**Comment by romani** [comment]
@rnveach , thanks a lot.
@strkkk, please review https://github.com/checkstyle/contribution/pull/508 , I found one more exception in other Check on another file.

File: src/test/java/com/puppycrawl/tools/checkstyle/utils/ScopeUtilTest.java (hunk 2 above)
Comment (strkkk) [reply src/test/java/com/puppycrawl/tools/checkstyle/utils/ScopeUtilTest.java:171]: one more note - there is no need for this test case. Pitest will pass because this condition is tested indirectly by test cases for several checks. 
@romani if this is fine, I can remove it. If not, such test case should be kept to test this util method directly.

Comment (romani) [reply src/test/java/com/puppycrawl/tools/checkstyle/utils/ScopeUtilTest.java:171]: Please remove this test, we need to keep pure UT only as very very last resort to satisfy coverage

**Review by romani — APPROVED** [review]
Ok to merge.
Removal of pure UT method is preferable

**Comment by strkkk** [comment]
@romani sorry I was wrong, this ugly test case is required to satisfy pitest. I will bring it back and merge.
