### PR TITLE
Issue #11061: False negative around TokenTypes.LOR in UnnecessaryParenthesesCheck

### LINKED ISSUE #11061: UnnecessaryParentheses: false negative
https://checkstyle.org/config_coding.html#UnnecessaryParentheses

````
$ cat TestClass.java
public class TestClass {
     public boolean isUsed() {
        return used
                || (this.filePattern != null && this.filePattern.trim().length() == 0 // line 4
                || this.messagePattern != null && this.messagePattern.trim().length() == 0
                || this.checkPattern != null && this.checkPattern.trim().length() == 0);
     }
}

$ cat TestConfig.xml
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
          "-//Puppy Crawl//DTD Check Configuration 1.3//EN"
          "https://checkstyle.org/dtds/configuration_1_3.dtd">

<module name="Checker">
    <property name="charset" value="UTF-8"/>

    <module name="TreeWalker">
<module name="UnnecessaryParentheses"/>
    </module>
</module>

$ java -jar checkstyle-9.2-all.jar -c TestConfig.xml TestClass.java
Starting audit...
Audit done.
````

I am expecting a violation on line 4 since the code equates to the same without the parenthesis as with.

Proof:
````
public class BooleanTest {

	public static void main(String[] args) {
		for (boolean a : new boolean[] { true, false }) {
			for (boolean b : new boolean[] { true, false }) {
				for (boolean c : new boolean[] { true, false }) {
					for (boolean d : new boolean[] { true, false }) {
						for (boolean e : new boolean[] { true, false }) {
							final boolean one = a || (b && c || d && e);
							final boolean two = a || b && c || d && e;

							if (one != two) {
								throw new IllegalStateException(a + ", " + b + ", " + c + ", " + d + ", " + e);
							}
						}
					}
				}
			}
		}

		System.out.println("Yes");
	}

}

Outputs:
"Yes"
````

### PR DESCRIPTION
**Pull request by Vyom-Yadav**
Resolves #11061:  UnnecessaryParentheses: false negative
Diff Regression config: https://gist.githubusercontent.com/Vyom-Yadav/98dceb63a79f4833e85fff9b2e1464a6/raw/5b2e5d76bc8d10c8f0e3619697156e49d80ab85f/my_checks.xml
Final Report(clean) - https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/cd3cb0c_2021122340/reports/diff/index.html

### CODE REVIEW

**Comment by Vyom-Yadav** [comment]
Github, generate report

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnnecessaryParenthesesCheck.java [hunk 1]
```diff
@@ -508,7 +512,7 @@ public void leaveToken(DetailAST ast) {
             else if (TokenUtil.isOfType(type, ASSIGNMENTS)) {
                 assignDepth--;
             }
-            else if (isSurrounded(ast) && checkAroundOperators(ast)) {
+            else if (isSurrounded(ast) && unnecessaryParenAroundOperators(ast)) {
```
Comment (Vyom-Yadav) [inline src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnnecessaryParenthesesCheck.java:515]: Condition is more clear to read, is surrounded, and has unnecessary parens then log an error message.

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnnecessaryParenthesesCheck.java [hunk 2]
```diff
@@ -571,19 +575,22 @@ else if (ast.getParent().getType() == TokenTypes.LITERAL_RETURN) {
...
      *
      * @param ast the {@code DetailAST} to check if it is surrounded by
-     *        parentheses.
+     *        unnecessary parentheses.
      * @return {@code true} if the expression is surrounded by
-     *         parentheses.
+     *         unnecessary parentheses.
      */
-    private static boolean checkAroundOperators(DetailAST ast) {
+    private static boolean unnecessaryParenAroundOperators(DetailAST ast) {
```
Comment (Vyom-Yadav) [inline src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnnecessaryParenthesesCheck.java:585]: The name was a bit misleading as well as the Javadoc, edited them to make more sense.

File: src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/unnecessaryparentheses/InputUnnecessaryParenthesesIfStatement.java [hunk 3]
```diff
@@ -155,8 +155,25 @@ public void checkBooleanStatements() {
...
+        if ((v || x) & // ok
+                (w || y)) {
+        }
+        if (a && v || (w || z) && u || y) { // ok
+        }
+        if (a && x || (y || z) || vy && u) { // violation
+        }
+    }
 }
-
```
Comment (Vyom-Yadav) [inline src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/unnecessaryparentheses/InputUnnecessaryParenthesesIfStatement.java:162]: Unnecessary extra line removed

File: src/main/resources/com/puppycrawl/tools/checkstyle/meta/checks/coding/UnnecessaryParenthesesCheck.xml [hunk 4]
```diff
@@ -42,7 +42,7 @@
  raised as check is not "type aware".
  &lt;/p&gt;</description>
          <properties>
-            <property default-value="EXPR,IDENT,NUM_DOUBLE,NUM_FLOAT,NUM_INT,NUM_LONG,STRING_LITERAL,LITERAL_NULL,LITERAL_FALSE,LITERAL_TRUE,ASSIGN,BAND_ASSIGN,BOR_ASSIGN,BSR_ASSIGN,BXOR_ASSIGN,DIV_ASSIGN,MINUS_ASSIGN,MOD_ASSIGN,PLUS_ASSIGN,SL_ASSIGN,SR_ASSIGN,STAR_ASSIGN,LAMBDA,TEXT_BLOCK_LITERAL_BEGIN,LAND,LITERAL_INSTANCEOF,GT,LT,GE,LE,EQUAL,NOT_EQUAL,UNARY_MINUS,UNARY_PLUS,INC,DEC,LNOT,BNOT,POST_INC,POST_DEC"
+            <property default-value="EXPR,IDENT,NUM_DOUBLE,NUM_FLOAT,NUM_INT,NUM_LONG,STRING_LITERAL,LITERAL_NULL,LITERAL_FALSE,LITERAL_TRUE,ASSIGN,BAND_ASSIGN,BOR_ASSIGN,BSR_ASSIGN,BXOR_ASSIGN,DIV_ASSIGN,MINUS_ASSIGN,MOD_ASSIGN,PLUS_ASSIGN,SL_ASSIGN,SR_ASSIGN,STAR_ASSIGN,LAMBDA,TEXT_BLOCK_LITERAL_BEGIN,LAND,LOR,LITERAL_INSTANCEOF,GT,LT,GE,LE,EQUAL,NOT_EQUAL,UNARY_MINUS,UNARY_PLUS,INC,DEC,LNOT,BNOT,POST_INC,POST_DEC"
```
Comment (rnveach) [inline src/main/resources/com/puppycrawl/tools/checkstyle/meta/checks/coding/UnnecessaryParenthesesCheck.xml:45]: Do we have to be concerned since LOR and LAND are not both required if one is set? What happens if I include 1 and not the other. Will this cause the issue described at https://github.com/checkstyle/checkstyle/issues/11061#issuecomment-998473171 ?

**Review by rnveach — APPROVED** [review]

File: src/main/resources/com/puppycrawl/tools/checkstyle/meta/checks/coding/UnnecessaryParenthesesCheck.xml (hunk 4 above)
Comment (Vyom-Yadav) [reply src/main/resources/com/puppycrawl/tools/checkstyle/meta/checks/coding/UnnecessaryParenthesesCheck.xml:45]: If the user drops a token they will drop the cases related to that token. There might be false negatives but there won't be any false positives.

**Comment by nmancus1** [comment]
From https://github.com/checkstyle/checkstyle/issues/11061#issuecomment-1001207356 :

We should update documentation to reflect that this check now supports some operator precedence: https://checkstyle.sourceforge.io/config_coding.html#UnnecessaryParentheses

**Comment by Vyom-Yadav** [comment]
> We should update documentation to reflect that this check now supports some operator precedence: https://checkstyle.sourceforge.io/config_coding.html#UnnecessaryParentheses

Updated documentation.

**Comment by Vyom-Yadav** [comment]
Github, rebase

**Comment by Vyom-Yadav** [comment]
Github, rebase

**Comment by nmancus1** [comment]
Github, generate site

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnnecessaryParenthesesCheck.java [hunk 5]
```diff
@@ -46,9 +46,8 @@
  * </pre>
  * <p>
  * The check is not "type aware", that is to say, it can't tell if parentheses
- * are unnecessary based on the types in an expression.  It also doesn't know
- * about operator precedence and associativity; therefore it won't catch
- * something like
+ * are unnecessary based on the types in an expression. The check is partially aware about
+ * operator precedence but unaware about operator associativity. It won't catch cases like-
```
Comment (nmancus1) [inline src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnnecessaryParenthesesCheck.java:50]: `like -` -> `such as:` Existing documentation uses colon when preceding examples.

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnnecessaryParenthesesCheck.java [hunk 6]
```diff
@@ -66,6 +65,29 @@
  * and <em>r</em> were {@code boolean} still there will be no violation
  * raised as check is not "type aware".
  * </p>
+ * <p>
+ * The partial support for operator precedence includes cases of the following type-
```
Comment (nmancus1) [inline src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnnecessaryParenthesesCheck.java:69]: `type-` -> `type:`, similar to above.

File: src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/unnecessaryparentheses/InputUnnecessaryParenthesesIfStatement.java [hunk 7]
```diff
@@ -130,7 +130,7 @@ public void checkBooleanStatements() {
         if (( // violation
                 a!=(b==c) && (a // violation
                         && (b==c))) // violation
-                 || (a || a!=(b<=c))     // ok
+                 || (a || a!=(b<=c))     // violation
```
Comment (nmancus1) [inline src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/unnecessaryparentheses/InputUnnecessaryParenthesesIfStatement.java:133]: Please add to comment which parenthesis are unnecessary since there are two sets of unnecessary parenthesis on this line, maybe something like `violation, outer parenthesis are unnecessary`.

**Review by nmancus1 — CHANGES_REQUESTED** [review]
Few minor items:

File: src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/unnecessaryparentheses/InputUnnecessaryParenthesesIfStatement.java (hunk 7 above)
Comment (rnveach) [reply src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/unnecessaryparentheses/InputUnnecessaryParenthesesIfStatement.java:133]: Unless the test specifically requires specific lines, I found in previous PRs that it makes where the violation is clearer if the `()`s are on different lines.

Comment (Vyom-Yadav) [reply src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/unnecessaryparentheses/InputUnnecessaryParenthesesIfStatement.java]: Yes, that is better, changed it to that format.

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnnecessaryParenthesesCheck.java (hunk 6 above)
Comment (Vyom-Yadav) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnnecessaryParenthesesCheck.java]: Done

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnnecessaryParenthesesCheck.java (hunk 5 above)
Comment (Vyom-Yadav) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnnecessaryParenthesesCheck.java]: Done

Comment (nmancus1) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnnecessaryParenthesesCheck.java]: Resolved

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnnecessaryParenthesesCheck.java (hunk 6 above)
Comment (nmancus1) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnnecessaryParenthesesCheck.java]: Resolved

File: src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/unnecessaryparentheses/InputUnnecessaryParenthesesIfStatement.java (hunk 7 above)
Comment (nmancus1) [reply src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/unnecessaryparentheses/InputUnnecessaryParenthesesIfStatement.java]: Resolved

**Review by nmancus1 — APPROVED** [review]

File: src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/unnecessaryparentheses/InputUnnecessaryParenthesesIfStatement.java [hunk 8]
```diff
@@ -155,8 +156,28 @@ public void checkBooleanStatements() {
                 && (Integer.valueOf(d) instanceof Integer) == true) { // ok
             return;
         }
-    }
-
 
+        boolean x = false, y = true, z = false;
```
Comment (romani) [inline src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/unnecessaryparentheses/InputUnnecessaryParenthesesIfStatement.java:160]: please move all new cases(that you adding only) to new Input files, we already agreed to keep Input size not above 120 lines.
We have enormous amount of bad examples, but lets not grow it further.

**Review by romani — CHANGES_REQUESTED** [review]
minor item:

File: src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/unnecessaryparentheses/InputUnnecessaryParenthesesIfStatement.java (hunk 8 above)
Comment (Vyom-Yadav) [reply src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/unnecessaryparentheses/InputUnnecessaryParenthesesIfStatement.java]: My bad, I forgot about it, as I was touching that file, I extracted some inputs to the new file I made to get under the limit and removed a suppression.

**Review by romani — APPROVED** [review]

**Review by strkkk — APPROVED** [review]
