### PR TITLE
Issue #10962: fix NPE in EqualsAvoidNullCheck

### LINKED ISSUE #10962: NPE in EqualsAvoidNull check when accessing string from base class with 'this' qualifier
Checkstyle ends with a NPE when a derived class accesses an String variable from a base class when the variable is accessed via 'this' qualifier. The check runs fine when the 'this.' is omitted.

This error appeared first in the Checkstyle version 8.29 we currently use but can be reprodued with the latest 9.1 version. 
It appears on the checkstyle command line (as in the sample below), withing the checkstyle maven plugin and in the checkstyle Eclipse plugin.

**The below command sequence demonstrates the error:**
```
C:\Temp\test>type AbstractBaseClass.java 
package com.fsp.test;

public abstract class AbstractBaseClass
{
   protected String stringFromBaseClass = "ABC";
}

C:\Temp\test>type DerivedClass.java 
package com.fsp.test;

public class DerivedClass extends AbstractBaseClass
{
   public DerivedClass()
   {
      if ( this.stringFromBaseClass.equals("JKHKJ") ) System.out.println("Hello");
   }
}

C:\Temp\test>type checkstyle-config.xml 
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE module PUBLIC "-//Puppy Crawl//DTD Check Configuration 1.3//EN" "http://www.puppycrawl.com/dtds/configuration_1_3.dtd">
<module name="Checker">
  <property name="fileExtensions" value="java"/>
  <module name="TreeWalker">
    <module name="EqualsAvoidNull"/>
  </module>
</module>

C:\Temp\test>java -Duser.language=en -Duser.country=US -jar c:\temp\checkstyle-9.1-all.jar -c checkstyle-config.xml  AbstractBaseClass.java DerivedClass.java 
Starting audit...
com.puppycrawl.tools.checkstyle.api.CheckstyleException: Exception was thrown while processing DerivedClass.java
	at com.puppycrawl.tools.checkstyle.Checker.processFiles(Checker.java:302)
	at com.puppycrawl.tools.checkstyle.Checker.process(Checker.java:221)
	at com.puppycrawl.tools.checkstyle.Main.runCheckstyle(Main.java:409)
	at com.puppycrawl.tools.checkstyle.Main.runCli(Main.java:332)
	at com.puppycrawl.tools.checkstyle.Main.execute(Main.java:191)
	at com.puppycrawl.tools.checkstyle.Main.main(Main.java:126)
Caused by: java.lang.NullPointerException
	at com.puppycrawl.tools.checkstyle.checks.coding.EqualsAvoidNullCheck.getFieldType(EqualsAvoidNullCheck.java:545)
	at com.puppycrawl.tools.checkstyle.checks.coding.EqualsAvoidNullCheck.isStringFieldOrVariableFromThisInstance(EqualsAvoidNullCheck.java:481)
	at com.puppycrawl.tools.checkstyle.checks.coding.EqualsAvoidNullCheck.isCalledOnStringFieldOrVariable(EqualsAvoidNullCheck.java:439)
	at com.puppycrawl.tools.checkstyle.checks.coding.EqualsAvoidNullCheck.checkMethodCall(EqualsAvoidNullCheck.java:356)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1080)
	at com.puppycrawl.tools.checkstyle.checks.coding.EqualsAvoidNullCheck.traverseFieldFrameTree(EqualsAvoidNullCheck.java:339)
	at com.puppycrawl.tools.checkstyle.checks.coding.EqualsAvoidNullCheck.traverseFieldFrameTree(EqualsAvoidNullCheck.java:336)
	at com.puppycrawl.tools.checkstyle.checks.coding.EqualsAvoidNullCheck.traverseFieldFrameTree(EqualsAvoidNullCheck.java:336)
	at com.puppycrawl.tools.checkstyle.checks.coding.EqualsAvoidNullCheck.finishTree(EqualsAvoidNullCheck.java:242)
	at com.puppycrawl.tools.checkstyle.TreeWalker.notifyEnd(TreeWalker.java:319)
	at com.puppycrawl.tools.checkstyle.TreeWalker.walk(TreeWalker.java:274)
	at com.puppycrawl.tools.checkstyle.TreeWalker.processFiltered(TreeWalker.java:154)
	at com.puppycrawl.tools.checkstyle.api.AbstractFileSetCheck.process(AbstractFileSetCheck.java:87)
	at com.puppycrawl.tools.checkstyle.Checker.processFile(Checker.java:328)
	at com.puppycrawl.tools.checkstyle.Checker.processFiles(Checker.java:289)
	... 5 more
Checkstyle ends with 1 errors.
```

### PR DESCRIPTION
**Pull request by strkkk**
Closes #10962 

Diff Regression config: https://gist.githubusercontent.com/strkkk/31749e0743553a606f69fdfc6670d780/raw/9b153902a204a5e9b1a7b0445cfa6b7715499e30/confg.xml

Report (clean) https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/a921658_2021160443/reports/diff/index.html

### CODE REVIEW

File: src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/equalsavoidnull/InputEqualsAvoidNullSuperClass.java [hunk 1]
```diff
@@ -0,0 +1,26 @@
...
+
+public abstract class InputEqualsAvoidNullSuperClass {
+   protected String stringFromBaseClass = "ABC";
+}
+
+class DerivedClass extends InputEqualsAvoidNullSuperClass {
+   protected String classField = "DEF";
+
+    void m1() {
+        if (this.stringFromBaseClass.equals("JKHKJ")) { // ok
```
Comment (strkkk) [inline src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/equalsavoidnull/InputEqualsAvoidNullSuperClass.java:18]: this case is ok because this field is from superclass and we cannot get its type

**Review by romani — APPROVED** [review]
Good

**Review by pbludov — APPROVED** [review]

**Comment by pbludov** [comment]
Of course, the report is empty. A protected non-constant field is such a bad pattern that no one uses it.
