### PR TITLE
Issue #12809: Improve performance of lambda processing

### LINKED ISSUE #12809: Improve performance of lambda processing
Hi 👋 

I've been profiling checkstyle lately and noticed that the processing of lambdas is the most expensive part of the grammar in a project of us (that I unfortunately can't share). Funny enough, I noticed that our checkstyle tasks for the test code seems to take longer than the main source although there are only ~400 tests vs ~2000 main sources. (With 65.000 vs. 130.000 lines of code respectively). A common pattern in the slowest test files is this sort of pseudo-code that creates the test scenarios.
```
buildScenario(s -> s
	.withPrerequisite(
		prerequisite -> prerequisite.ref(prerequisiteRef)
	)
	.withUser(user -> user
		.sessionRef(userRef)
		.withUserItem(itemId, item -> item
			.withAmount(0)
		)
	)
);
```

The thing that stands out in the tests is the usage of (nested) functional interfaces as shown above. ~7000 in tests vs. ~2500 in the main sources.

image

I've originally opened https://github.com/antlr/antlr4/issues/4164 but they sent me here to fix/optimize the grammar. I've been playing around with the grammar file and came up with this, which would essentially inline what `lambdaExpression` does - with the addition to use `expr` rather than `expression`:
```patch
--- a/src/main/resources/com/puppycrawl/tools/checkstyle/grammar/java/JavaLanguageParser.g4
+++ b/src/main/resources/com/puppycrawl/tools/checkstyle/grammar/java/JavaLanguageParser.g4
@@ -720,7 +720,7 @@ expr
         | BAND_ASSIGN | BOR_ASSIGN | BXOR_ASSIGN | SR_ASSIGN | BSR_ASSIGN
         | SL_ASSIGN | MOD_ASSIGN)
       expr                                                                 #binOp
-    | lambdaExpression                                                     #lambdaExp
+    | lambdaParameters LAMBDA (expr | block)                               #lambdaExp
     ;
```
With this I get 100% performance improvement, but obviously certain checks fail with these changes because I haven't adjusted them to the new reality locally....

Since the grammar is not really intuitive I don't know if I did something wrong. For example I don't understand why `expression` is used originally instead of `expr` in `lambdaBody`.

It would be great if you could take this over and check if that's a viable solution. Or if there are any other ways to optimize the lambda processing.

Cheers,
Christoph

### PR DESCRIPTION
**Pull request by nrmancuso**
Closes #12809 

-------------------------
Reports:

AST regression test report:
https://nrmancuso.github.io/reports/issue-12809/2023-03-18-T-00-03-28/antlr-report/index.html

 - Difference is in stack trace of non-compilable files only

Check regression reports:
https://nrmancuso.github.io/reports/issue-12809/2023-03-18-T-00-03-28/part2-report/index.html

https://nrmancuso.github.io/reports/issue-12809/2023-03-18-T-00-03-28/part4-report/index.html

https://nrmancuso.github.io/reports/issue-12809/2023-03-18-T-00-03-28/sevntu-check-regression_part_1-report/index.html

https://nrmancuso.github.io/reports/issue-12809/2023-03-18-T-00-03-28/part6-report/index.html

https://nrmancuso.github.io/reports/issue-12809/2023-03-18-T-00-03-28/part3-report/index.html

https://nrmancuso.github.io/reports/issue-12809/2023-03-18-T-00-03-28/sevntu-check-regression_part_2-report/index.html

https://nrmancuso.github.io/reports/issue-12809/2023-03-18-T-00-03-28/part5-report/index.html

https://nrmancuso.github.io/reports/issue-12809/2023-03-18-T-00-03-28/part1-report/index.html

 - No differences

### CODE REVIEW

**Comment by rnveach** [comment]
@nrmancuso should we developer our own certified method of testing performance?

https://github.com/rnveach/checkstyle/commits/more_audits

**Comment by dreis2211** [comment]
@nrmancuso I find it hard to see if there is anything changing when you force-push. Should I retest this? And is there anything missing that blocks this from moving out of the `Draft` status?

**Comment by nrmancuso** [comment]
@dreis2211 you are good, next step for you is to use it after we release :) I have some reports to generate and share and a few other odds and ends here.

File: src/main/java/com/puppycrawl/tools/checkstyle/JavaAstVisitor.java [hunk 1]
```diff
@@ -1495,7 +1481,21 @@ public DetailAstImpl visitSimpleMethodCall(JavaLanguageParser.SimpleMethodCallCo
 
     @Override
     public DetailAstImpl visitLambdaExp(JavaLanguageParser.LambdaExpContext ctx) {
-        return flattenedTree(ctx);
+        final DetailAstImpl lambda = create(ctx.LAMBDA());
+        lambda.addChild(visit(ctx.lambdaParameters()));
+
+        final DetailAstImpl rightHandLambdaChild;
+        if (ctx.block() != null) {
```
Comment (dreis2211) [inline src/main/java/com/puppycrawl/tools/checkstyle/JavaAstVisitor.java:1488]: Isn't calling `ctx.block()` twice an overhead?

Comment (nrmancuso) [reply src/main/java/com/puppycrawl/tools/checkstyle/JavaAstVisitor.java]: Yes, cleaned this up

Comment (nrmancuso) [reply src/main/java/com/puppycrawl/tools/checkstyle/JavaAstVisitor.java]: @dreis2211 please resolve this item if you are good.

**Comment by nrmancuso** [comment]
@dreis2211 this should be final iteration of code, feel free to test for performance again

>@nrmancuso should we developer our own certified method of testing performance?

@rnveach this is a good idea, but I am not sure how to execute it. When I make grammar changes, I sometimes analyze the grammar using the ANTLR tool, but from a holistic perspective, I am not sure how to do this.

File: src/main/java/com/puppycrawl/tools/checkstyle/JavaAstVisitor.java [hunk 2]
```diff
@@ -103,6 +103,16 @@ public final class JavaAstVisitor extends JavaLanguageParserBaseVisitor<DetailAs
     /** String representation of the right shift operator. */
     private static final String RIGHT_SHIFT = ">>";
 
+    /**
+     * The tokens here are technically expressions, but should
+     * not return an EXPR token as their root.
+     */
+    private static final int[] EXPRESSIONS_WITH_NO_EXPR_ROOT = {
```
Comment (nrmancuso) [inline src/main/java/com/puppycrawl/tools/checkstyle/JavaAstVisitor.java:110]: Made this a static field so that we do not have to create array with each method call.

File: src/main/java/com/puppycrawl/tools/checkstyle/JavaAstVisitor.java [hunk 3]
```diff
@@ -2160,6 +2164,28 @@ public DetailAstImpl visit(ParseTree tree) {
...
+     * Builds an expression node. This is used to build the root of an expression with
+     * an imaginary {@code EXPR} node.
+     *
+     * @param exprNode expression to build node for
+     * @return expression DetailAstImpl node
+     */
+    private DetailAstImpl buildExpressionNode(ParseTree exprNode) {
+        final DetailAstImpl expression = visit(exprNode);
+
+        final DetailAstImpl exprRoot;
```
Comment (nrmancuso) [inline src/main/java/com/puppycrawl/tools/checkstyle/JavaAstVisitor.java:2177]: Cleaned up this code a bit, but this is basically what was in the visitExpression method.

**Comment by dreis2211** [comment]
Performance looks good still

File: src/main/java/com/puppycrawl/tools/checkstyle/JavaAstVisitor.java (hunk 1 above)
Comment (dreis2211) [reply src/main/java/com/puppycrawl/tools/checkstyle/JavaAstVisitor.java]: Can't really resolve it, because you force-pushed and made this outdated. Looks good though

**Review by rnveach — APPROVED** [review]

**Review by romani — APPROVED** [review]
ok to merge
