### PR TITLE
Issue #15939: false-positive for text-block-literal at indentation fix

### LINKED ISSUE #15939: `lineWrappingIndentation` falsely detects incorrect indentation for text blocks
I have read check documentation: https://checkstyle.sourceforge.io/checks/misc/indentation.html
I have downloaded the latest checkstyle from: https://checkstyle.org/cmdline.html#Download_and_Run
I have executed the cli and showed it below, as cli describes the problem better than 1,000 words

```bash
/var/tmp $ javac A.java

/var/tmp $ cat checkstyle.xml
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
        "-//Checkstyle//DTD Checkstyle Configuration 1.3//EN"
        "https://checkstyle.org/dtds/configuration_1_3.dtd">

<module name="Checker">

    <property name="charset" value="UTF-8"/>

    <property name="severity" value="${org.checkstyle.google.severity}" default="warning"/>

    <property name="fileExtensions" value="java, properties, xml"/>

    <module name="SuppressWarningsFilter"/>

    <module name="TreeWalker">
        <module name="SuppressWarningsHolder"/>

        <module name="Indentation">
            <property name="lineWrappingIndentation" value="4"/>
            <property name="forceStrictCondition" value="true"/>
        </module>
    </module>
</module>

/var/tmp $ cat A.java
public class A {
    private static final String EXAMPLE = """
        Example string""";
}


/var/tmp $ RUN_LOCALE="-Duser.language=en -Duser.country=US"
/var/tmp $ java $RUN_LOCALE -jar checkstyle-10.20.1-all.jar -c checkstyle.xml A.java
Starting audit...
[WARN] A.java:3:23: '"""' has incorrect indentation level 22, expected level should be 8. [Indentation]
Audit done.
```

For Windows users, please use `type` instead of `cat` and run

```cmd
set RUN_LOCALE="-Duser.language=en -Duser.country=US"
java %RUN_LOCALE% -jar checkstyle-10.20.1-all.jar -c checkstyle.xml A.java
```

in place of the last 2 commands above.

---

**Describe what you expect in detail.**
The indentation is correct, so no warning should be reported. Note that the warning can be suppressed by adding `@SuppressWarnings("checkstyle:indentation")` to the declaration, given that `SuppressWarningsFilter` is configured.

It seems to me that Checkstyle wants the ending `"""` on a new line. This is not a notational request, though; it'd be a different string as an extra new line character would be added.

See [JEP 378](https://openjdk.org/jeps/378) for more information on text blocks.

### PR DESCRIPTION
**Pull request by mohitsatr**
resolves #15939 

main point:
>Whitespaces on the end line of the text block are not part of the string and there is nothing visible before the end of the text block. It should be indented by this check because it is code and it starts the line.

```xml
$ cat testconfig.xml 
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
        "-//Checkstyle//DTD Checkstyle Configuration 1.3//EN"
        "https://checkstyle.org/dtds/configuration_1_3.dtd">

<module name="Checker">

    <property name="charset" value="UTF-8"/>

    <property name="severity" value="${org.checkstyle.google.severity}" default="warning"/>

    <property name="fileExtensions" value="java, properties, xml"/>

    <module name="SuppressWarningsFilter"/>

    <module name="TreeWalker">
        <module name="SuppressWarningsHolder"/>

        <module name="Indentation">
            <property name="lineWrappingIndentation" value="4"/>
            <property name="forceStrictCondition" value="true"/>
        </module>
    </module>
</module>
```

```java
public class Test {
    private static final String EXAMPLE = """
                Example string
        EXample2
            example3
        """;    
} 
```
```
java -jar checkstyle-10.21.1-SNAPSHOT-all.jar -c testconfig.xml Test.java
Starting audit...
Audit done.
```
this implementation completely ignores `TEXT_BLOCK_LITERAL_BEGIN/END/CONTENT`

### CODE REVIEW

**Comment by romani** [comment]
@mohitsatr , please proceed with finishing this PR.
Direction is good, If you need some answer to your concerns please state them again, I can not spot them.

Just make CI pass, run regression diff report.

**Comment by mohitsatr** [comment]
Github, generate report

**Comment by mohitsatr** [comment]
Github, generate report for Indentation/all-examples-in-one

**Comment by romani** [comment]
@mohitsatr , we expect only removal of violations, please investigate why they changed.

**Comment by mohitsatr** [comment]
Github, generate report for Indentation/Example1

**Comment by romani** [comment]
This is suspicious https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/f406eea9d33fe73dda1621f577f6d1af1fc90823_2024053241/reports/diff/checkstyle/index.html#A7 message changed.

Please add it to inputs

**Comment by mohitsatr** [comment]
Github, generate report for Indentation/all-examples-in-one

**Comment by mohitsatr** [comment]
save yourself from scrolling 
https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/5c0ac47fb19e4230fbb93ede0bc8fcd7ee8b33dd_2024061859/reports/diff/openjdk21/index.html#A13191

**Review by rnveach — CHANGES_REQUESTED** [review]
https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/5c0ac47fb19e4230fbb93ede0bc8fcd7ee8b33dd_2024061859/reports/diff/apache-struts/index.html#A1
This is a false negative. Whitespaces on the end line of the text block are not part of the string and there is nothing visible before the end of the text block. It should be indented by this check because it is code and it starts the line.

https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/5c0ac47fb19e4230fbb93ede0bc8fcd7ee8b33dd_2024061859/reports/diff/camunda/index.html#A3
Similar to this, but this is the start of the text block.

**Comment by romani** [comment]
@mohitsatr , 

>This is a false negative

Please create new issue for this, it will be separate update. We need to remove false positives sooner.

**Comment by rnveach** [comment]
There is no issue until this PR is merged. Better to fix it now then have this go out as a bad fix.

**Comment by romani** [comment]
There is an issue https://github.com/checkstyle/checkstyle/issues/15939

So we do step back in support of it to ignore it completely, to avoid annoying users, next step will be to fix new issue with all details on how it should work, I think there will be discussion.

After this issue, users should rely on manual indentation for text blocks, or use formatter of their preferences.
As CS be ready to validate proper indentation, it will start to placing violation back such code. But a way more will be known on how it should be.

**Comment by rnveach** [comment]
And there is a problem https://github.com/checkstyle/checkstyle/pull/16058#pullrequestreview-2525855058 .

Your replacing one issue for another and your "discussion" on this is creating a problem on something that doesn't exist. Nothing has been said this problem can't be fixed now or admins can't assist. It is better to provide a proper fix than a broken one.

**Comment by mohitsatr** [comment]
Github, generate report for Indentation/all-examples-in-one

**Comment by rnveach** [comment]
@mohitsatr Basically you should be verifying the text block starts the line to process it. If something is before the node, then we know it doesn't start the line.

You may want to look at https://github.com/checkstyle/checkstyle/blob/befb825a3127883f8c4bb8e3d4291259727a7ab4/src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/AbstractExpressionHandler.java#L177-L179 .

**Comment by mohitsatr** [comment]
Github, generate report for Indentation/all-examples-in-one

File: src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/indentation/indentation/InputIndentationTextBlock.java [hunk 1]
```diff
@@ -0,0 +1,97 @@
...
+    private static final String GO = """//indent:4 exp:4
+    GO                                   //indent:4 exp:4
+""";//indent:0 exp:8 warn
+
+    public void textBlockNoIndent() { //indent:4 exp:4
+        String content = (""" //indent:8 exp:8
+                -----1234\r //indent:16 exp:16
+                filename="deleteme.txt"\r //indent:16 exp:16
+                -----1234--\r //indent:16 exp:16
+                """); //indent:16 exp:12 warn
```
Comment (romani) [inline src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/indentation/indentation/InputIndentationTextBlock.java:25]: please out above or below "functionally same" code with correct indentation, to let clearly state what is expected form of indentation.

Comment (mohitsatr) [reply src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/indentation/indentation/InputIndentationTextBlock.java]: done

File: src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/indentation/indentation/InputIndentationTextBlock.java [hunk 2]
```diff
@@ -0,0 +1,97 @@
...
+ */                                                                           //indent:1 exp:1
+
+
+public class InputIndentationTextBlock { //indent:0 exp:0
+    private static final String EXAMPLE = """//indent:4 exp:4
+        Example string""";//indent:8 exp:8
+
+    private static final String GO = """//indent:4 exp:4
+    GO                                   //indent:4 exp:4
+""";//indent:0 exp:8 warn
```
[the remark this answers is not in the document]
Comment (mohitsatr) [reply src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/indentation/indentation/InputIndentationTextBlock.java]: done

**Comment by mohitsatr** [comment]
> Should we add this to xdoc examples? as handling of `"""` is very nuanced

I didn't understand this. are you asking whether we should mention how we are handling the logic for """(ending).

**Comment by mohitsatr** [comment]
If the `TEXT-BLOCK-BEGIN` is in the `firstNodeOnLine` map, we can be certain it is the first node on the line. However, if the `TEXT-BLOCK-END` appears in the `firstNodeOnLine`, we cannot be sure that it is the first node on the line.

The `firstNodeOnLine` hashmap is specifically designed to store AST nodes that start a line. Ideally, the `TEXT-BLOCK-END` should be present in the `firstNodeOnLine` only if it starts the line. However, since text-blocks-literals can span multiple lines, the `TEXT-BLOCK-END` can bypass our current logic and end up in the `firstNodeOnLine`  without being verified as the first node on the line.

`shouldProcessTextBlockLiteral` method is responsible for checking whether `TEXT-BLOCK-END`  starts a line or not.

**Comment by romani** [comment]
@mohitsatr , please fix CI failure

**Comment by mohitsatr** [comment]
it is expecting some line terminator  :
```
error: illegal text block open delimiter sequence, missing line terminator
    private static final String EXAMPLE = """                 //indent:4 exp:4
```
?

**Comment by romani** [comment]
Try to compile by jdk21

**Comment by romani** [comment]
https://stackoverflow.com/a/57853218/1015848

**Comment by mohitsatr** [comment]
> so some input files should be exceptional

how ? using suppression ?

**Comment by romani** [comment]
No. Instead of `verifyWarns(` use regular `verify` method.

**Comment by mohitsatr** [comment]
Github, generate report for Indentation/all-examples-in-one

**Review by romani — APPROVED** [review]
thanks a lot.

it is hard to review  all diff, but i  did spot checking for about 30 violations, no problems is found.

it is good step forward.

**Comment by nrmancuso** [comment]
Let’s allow @rnveach to finish review since he left items above

**Review by rnveach — APPROVED** [review]

**Review by nrmancuso — APPROVED** [review]
