### PR TITLE
Issue #5362: Fix new keyword and their children not checked correctly.

### LINKED ISSUE #5362: IndentationCheck: problem with content of anonymous class
`/var/tmp $ javac ManageHightPower.java`:

```
No output. Success.
```

`/var/tmp $ cat ManageHighPower.java`:

```
package com.android.tv.settings.device.apps.specialaccess;

public class ManageHighPower {

    private final StringBuffer mFilter =
            new StringBuffer(
                    new CharSequence() {
                        @Override                              // line 8
                        public char charAt(int index) {
                            return 'A';
                        }

                        public int length() {
                            return 1;
                        }

                        public CharSequence subSequence(int start, int end) {
                            return this;
                        }

                        public String toString() {
                            return "Foo";
                        }
                    });
}
```

`/var/tmp $ cat config.xml`:

```
<!DOCTYPE module PUBLIC "-//Puppy Crawl//DTD Check Configuration 1.3//EN" "http://www.puppycrawl.com/dtds/configuration_1_3.dtd">
<module name="Checker">
      <module name="TreeWalker">
          <module name="Indentation">
              <property name="severity" value="error"/>
              <property name="basicOffset" value="4"/>
              <property name="throwsIndent" value="8"/>
              <property name="lineWrappingIndentation" value="8"/>
          </module>
      </module>
</module>
```

`/var/tmp $ java -Duser.language=en -Duser.country=US -jar checkstyle-8.5-all.jar -c config.xml ManageHighPower.java`:

```
Starting audit...
[ERROR] .../ManageHighPower.java:8: 'method def modifier' has incorrect indentation level 24, expected level should be one of the following: 12, 16, 20. [Indentation]
[ERROR] .../ManageHighPower.java:10: 'method def' child has incorrect indentation level 28, expected level should be one of the following: 16, 20, 24. [Indentation]
[ERROR] .../ManageHighPower.java:11: 'method def rcurly' has incorrect indentation level 24, expected level should be one of the following: 12, 16, 20. [Indentation]
[ERROR] .../ManageHighPower.java:13: 'method def modifier' has incorrect indentation level 24, expected level should be one of the following: 12, 16, 20. [Indentation]
[ERROR] .../ManageHighPower.java:14: 'method def' child has incorrect indentation level 28, expected level should be one of the following: 16, 20, 24. [Indentation]
[ERROR] .../ManageHighPower.java:15: 'method def rcurly' has incorrect indentation level 24, expected level should be one of the following: 12, 16, 20. [Indentation]
[ERROR] .../ManageHighPower.java:17: 'method def modifier' has incorrect indentation level 24, expected level should be one of the following: 12, 16, 20. [Indentation]
[ERROR] .../ManageHighPower.java:18: 'method def' child has incorrect indentation level 28, expected level should be one of the following: 16, 20, 24. [Indentation]
[ERROR] .../ManageHighPower.java:19: 'method def rcurly' has incorrect indentation level 24, expected level should be one of the following: 12, 16, 20. [Indentation]
[ERROR] .../ManageHighPower.java:21: 'method def modifier' has incorrect indentation level 24, expected level should be one of the following: 12, 16, 20. [Indentation]
[ERROR] .../ManageHighPower.java:22: 'method def' child has incorrect indentation level 28, expected level should be one of the following: 16, 20, 24. [Indentation]
[ERROR] .../Desktop/ManageHighPower.java:23: 'method def rcurly' has incorrect indentation level 24, expected level should be one of the following: 12, 16, 20. [Indentation]
[ERROR] .../ManageHighPower.java:24: 'object def rcurly' has incorrect indentation level 20, expected level should be one of the following: 8, 12, 16. [Indentation]
Audit done.
Checkstyle ends with 13 errors.
```

---------------

I expected the indention to be correct without any warnings.

--------------

### PR DESCRIPTION
**Pull request by Abhishek-kumar09**
Fixes #5362 
Diff Regression projects: https://raw.githubusercontent.com/checkstyle/contribution/master/checkstyle-tester/projects-to-test-on.properties
Diff Regression config: https://gist.githubusercontent.com/Abhishek-kumar09/0745ecf11934e0214b9187f9d4896e4a/raw/7e9f169832e45c826fb99e72b3ff08f32765243a/my_check.xml

### CODE REVIEW

File: src/test/resources/com/puppycrawl/tools/checkstyle/checks/indentation/indentation/InputIndentationCorrectIfAndParameter.java [hunk 1]
```diff
@@ -114,14 +116,15 @@ void fooMethodWithIf(String stringStringStringStringLooooongString, //indent:6 e
...
+            new SecondClassLongNam7("loooooooooong"). //indent:12 exp:14,16 warn
             getInteger(new InputIndentationCorrectIfAndParameter(), "lg")), "l") //indent:12 exp:12
             || conditionThird(2048) || conditionFourth(new //indent:12 exp:12
             SecondClassLongNam7("Looooooooooooooo" //indent:12 exp:12
               + "o").gB(new InputIndentationCorrectIfAndParameter(), false))|| //indent:14 exp:>=12
               conditionFifth(true, new SecondClassLongNam7(getString(2048, "L" //indent:14 exp:>=12
               + "ooooooooooooooooooooooooooooooooooooooooooong")).gB( //indent:14 exp:>=12
-              new InputIndentationCorrectIfAndParameter(),true))||co(false,new //indent:14 exp:>=12
+              new InputIndentationCorrectIfAndParameter(),true))//indent:14 exp:16,18 warn
+                || co(false, new //indent:16 exp:16
```
Comment (Abhishek-kumar09) [inline src/test/resources/com/puppycrawl/tools/checkstyle/checks/indentation/indentation/InputIndentationCorrectIfAndParameter.java:127]: Had to change the pre-written file because it is more than 100 chars per lines due to addition of "warn" comment.

**Comment by Abhishek-kumar09** [comment]
Github, generate report

File: src/test/resources/com/puppycrawl/tools/checkstyle/checks/indentation/indentation/InputIndentationNewChildren.java [hunk 2]
```diff
@@ -0,0 +1,39 @@
...
+ * forceStrictCondition = false                                               //indent:1 exp:1
+ * lineWrappingIndentation = 8                                                //indent:1 exp:1
+ * tabWidth = 4                                                               //indent:1 exp:1
+ * throwsIndent = 8                                                           //indent:1 exp:1
+ *                                                                            //indent:1 exp:1
+ */                                                                           //indent:1 exp:1
+
+package com.puppycrawl.tools.checkstyle.checks.indentation.indentation; //indent:0 exp:0
+
+public class InputIndentationNewChildren { //indent:0 exp:0
```
Comment (romani) [inline src/test/resources/com/puppycrawl/tools/checkstyle/checks/indentation/indentation/InputIndentationNewChildren.java:17]: Please add in name of class "correct", it is very valuable to keep such inputs.

As indentation is part of Google style please add  case from issue to Input of ITs, issue was reported by Google team, so we need to prove that it is ok  for Google style also

**Review by romani — CHANGES_REQUESTED** [review]
Item:

**Comment by romani** [comment]
Please generate for Guava separate report with Config from Google style.
https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/anonymous_class_2020092045/reports/diff/guava/index.html#A2 to make sure we have no violation on this line.

All other projects can stay on default config.

**Comment by Abhishek-kumar09** [comment]
Github, generate report

**Comment by romani** [comment]
>Google style on Guava:

Looks good.

**Comment by Abhishek-kumar09** [comment]
Please verify these, are these all correct: https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/anonymous_class_2020092045/reports/diff/android-launcher/index.html

File: src/test/resources/com/puppycrawl/tools/checkstyle/checks/indentation/indentation/InputIndentationNewChildren.java (hunk 2 above)
Comment (romani) [reply src/test/resources/com/puppycrawl/tools/checkstyle/checks/indentation/indentation/InputIndentationNewChildren.java]: @Abhishek-kumar09 , please do not forget to reply done on comments

**Comment by romani** [comment]
> Please verify these, are these all correct

looks good.

**Review by romani — APPROVED** [review]

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/NewHandler.java [hunk 3]
```diff
@@ -43,26 +48,57 @@ public NewHandler(IndentationCheck indentCheck,
 
     @Override
     public void checkIndentation() {
-        final DetailAST type = getMainAst().getFirstChild();
-        if (type != null) {
-            checkExpressionSubtree(type, getIndent(), false, false);
+        final DetailAST firstChild = getMainAst().getFirstChild();
+        final DetailAST mainAst = getMainAst();
```
Comment (strkkk) [inline src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/NewHandler.java:52]:
```
final DetailAST mainAst = getMainAst();
final DetailAST firstChild = mainAst.getFirstChild();
```

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/NewHandler.java [hunk 4]
```diff
@@ -43,26 +48,57 @@ public NewHandler(IndentationCheck indentCheck,
...
+
+        // if new is on the line start and it is not the part of assignment.
+        if (isOnStartOfLine(mainAst)
+                && !getMainAst().getParent().getParent().getText().equals(ASSIGNMENT)) {
```
Comment (strkkk) [inline src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/NewHandler.java:56]: `getMainAst()` you have this variable in scope, no need for method call

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/NewHandler.java [hunk 5]
```diff
@@ -43,26 +48,57 @@ public NewHandler(IndentationCheck indentCheck,
...
     @Override
     protected IndentLevel getIndentImpl() {
-        final IndentLevel result;
+        IndentLevel result;
         // if our expression isn't first on the line, just use the start
         // of the line
         if (getLineStart(getMainAst()) == getMainAst().getColumnNo()) {
             result = super.getIndentImpl();
+
+            if (getMainAst().getParent().getParent().getText().equals(ASSIGNMENT)) {
```
Comment (strkkk) [inline src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/NewHandler.java:94]: `getMainAst()`
I counted 4 invocations of this method, please extract to variable

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/NewHandler.java [hunk 6]
```diff
@@ -43,26 +48,57 @@ public NewHandler(IndentationCheck indentCheck,
...
+    public IndentLevel getSuggestedChildIndent(AbstractExpressionHandler child) {
+        final IndentLevel childIndent;
+        if (child.getMainAst().getType() == TokenTypes.OBJBLOCK) {
+            childIndent = new IndentLevel(getIndent(), getBasicOffset());
+        }
+        else {
+            childIndent = new IndentLevel(getIndent(),
+                    getIndentCheck().getLineWrappingIndentation());
+        }
+        return childIndent;
```
Comment (strkkk) [inline src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/NewHandler.java:83]: As for me, it will look a bit better with something like
```
final int offset;
if (child.getMainAst().getType() == TokenTypes.OBJBLOCK) {
            offset= getBasicOffset();
        }
        else {
            offset= getIndentCheck().getLineWrappingIndentation());
        }
return new IndentLevel(getIndent(), offset);
```

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/NewHandler.java (hunk 3 above)
Comment (strkkk) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/NewHandler.java:52]: Also, you can move initialization of firstChild lower, closer to its first usage

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/NewHandler.java (hunk 4 above)
Comment (strkkk) [inline src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/NewHandler.java:56]: `getParent().getParent().getText().equals(ASSIGNMENT)`
why dont check its type? Like `getMainAst().getParent().getParent().getType() == TokenTypes.ASSIGN`?

**Review by strkkk — CHANGES_REQUESTED** [review]
several items

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/NewHandler.java (hunk 4 above)
Comment (Abhishek-kumar09) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/NewHandler.java:56]: Earlier It was giving error, when I compared. Type was showing VARIABLE_DEF, but now its all correct. I don't know how, Maybe I did some there. Now its fine. Thank you very much.

Comment (Abhishek-kumar09) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/NewHandler.java]: New diff report: https://abhishek-kumar09.github.io/checkstyleDiffReportTempContribition/

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/NewHandler.java [hunk 7]
```diff
@@ -39,33 +42,75 @@ public NewHandler(IndentationCheck indentCheck,
...
+    /**
+     * Is NewKeyword is placed after an Assignment.
+     *
+     * @return is new keyWord is follwed by Assignment.
+     */
+    private boolean isNewKeywordFollowedByAssign() {
+        return mainAst.getParent().getParent().getType() == TokenTypes.ASSIGN;
+    }
+
+    private int getLineWrappingIndent() {
```
Comment (strkkk) [inline src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/NewHandler.java:110]: javadoc

**Review by strkkk — CHANGES_REQUESTED** [review]

**Review by strkkk — APPROVED** [review]

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/NewHandler.java [hunk 8]
```diff
@@ -39,33 +42,81 @@ public NewHandler(IndentationCheck indentCheck,
...
 
-        final DetailAST lparen = getMainAst().findFirstToken(TokenTypes.LPAREN);
+        final DetailAST lparen = mainAst.findFirstToken(TokenTypes.LPAREN);
         checkLeftParen(lparen);
     }
 
+    @Override
+    public IndentLevel getSuggestedChildIndent(AbstractExpressionHandler child) {
+        final int offset;
+        if (child.getMainAst().getType() == TokenTypes.OBJBLOCK) {
```
Comment (nmancus1) [inline src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/NewHandler.java:73]: This is a good candidate for `TokenUtil.isOfType()`.

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/NewHandler.java [hunk 9]
```diff
@@ -39,33 +42,81 @@ public NewHandler(IndentationCheck indentCheck,
...
+            result = new IndentLevel(getLineStart(mainAst));
         }
+
         return result;
     }
 
+    /**
+     * Is NewKeyword is placed after an Assignment.
+     *
+     * @return is new keyWord is follwed by Assignment.
```
Comment (nmancus1) [inline src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/NewHandler.java:104]: `Is NewKeyword is placed after an Assignment.`
This is a bit confusing.  Maybe `Checks if the 'new' keyword is followed by an assignment`?

`@return is new keyWord is follwed by Assignment.` -> `@return true if new keyword is followed by assignment`

**Review by nmancus1 — CHANGES_REQUESTED** [review]
Indentation is tedious work; good attention to detail @Abhishek-kumar09 .  Just a couple of minor items:

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/NewHandler.java (hunk 9 above)
Comment (nmancus1) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/NewHandler.java:104]: Also, travis failure is from `follwed`.  As @romani has said, spelling check CI is the most difficult of all to pass :)

Comment (Abhishek-kumar09) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/NewHandler.java:104]: >  spelling check CI is the most difficult of all to pass :)

Well said ;)

**Comment by nmancus1** [comment]
> Abhishek-kumar09 requested a review from nmancus1 2 minutes ago

Please respond to each item with 'done' or something similar, no need to re-request review :)

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/NewHandler.java (hunk 8 above)
Comment (Abhishek-kumar09) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/NewHandler.java]: Done

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/NewHandler.java (hunk 9 above)
Comment (Abhishek-kumar09) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/NewHandler.java]: Done

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/NewHandler.java (hunk 8 above)
Comment (nmancus1) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/NewHandler.java]: Resolved.

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/NewHandler.java (hunk 9 above)
Comment (nmancus1) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/NewHandler.java]: Resolved.

**Comment by nmancus1** [comment]
@romani I approve once CI is green, there are no other reviewers left to ping in queue.
