### PR TITLE
Issue #12817: fix switch-expression Indentation when appears on the start of the …

### LINKED ISSUE #12817: Incorrect Indentation errors for expression switches with google_checks.xml
```bash
$ javac -fullversion
javac full version "20-ea+35-2342"
$ javac T.java

$ wget https://raw.githubusercontent.com/checkstyle/checkstyle/d02e867225c3eaa43dc681c2827ce89799dee88f/src/main/resources/google_checks.xml

$ cat T.java
class T {
  void doSomething(int i) {
    String s =
        switch (i) {
          case 1 -> "one";
          case 2 -> "two";
          default -> throw new AssertionError();
        };
  }
}
$ RUN_LOCALE="-Duser.language=en -Duser.country=US"
$ java -jar checkstyle-10.8.1-all.jar -c google_checks.xml T.java
Starting audit...
[WARN] /tmp/tmp.zK57404080/T.java:4:9: 'switch' has incorrect indentation level 8, expected level should be 4. [Indentation]
[WARN] /tmp/tmp.zK57404080/T.java:5:11: 'case' child has incorrect indentation level 10, expected level should be 6. [Indentation]
[WARN] /tmp/tmp.zK57404080/T.java:6:11: 'case' child has incorrect indentation level 10, expected level should be 6. [Indentation]
[WARN] /tmp/tmp.zK57404080/T.java:7:11: 'case' child has incorrect indentation level 10, expected level should be 6. [Indentation]
[WARN] /tmp/tmp.zK57404080/T.java:8:9: 'switch rcurly' has incorrect indentation level 8, expected level should be 4. [Indentation]
Audit done.
```

**Describe what you expect in detail.**

I expected no errors to be produced, because the input is formatted in a way that complies with the [Google Java Style Guide](https://google.github.io/styleguide/javaguide.html)

### PR DESCRIPTION
**Pull request by mohitsatr**
fixes #12817 

New module config: https://gist.githubusercontent.com/mohitsatr/937e10572dd412961b61c77577619dff/raw/7a47240f8793e7335adbd81c2806b375f0394815/google_checks_indentation.xml
Diff Regression projects: https://gist.githubusercontent.com/mohitsatr/68b0817ac52ff7773d35585ee12fc1cc/raw/9ba8e4fb324e1daf589874c6992f2aa87b03079a/list-of-projects.properties

### CODE REVIEW

**Comment by mohitsatr** [comment]
Github, generate report for indentation/all-examples-in-one

**Comment by mohitsatr** [comment]
Github, generate report

**Comment by romani** [comment]
I like fact that no changes except for one project.
 
> [camunda](https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/49517b4_2025060506/reports/diff/camunda/index.html) ( ±1196, -479, +717 )

this very scary difference.
lets handle it a bit differently. please try to guess what indentation is used in this project and make config that suites it, so we will use single config diff report run, so we should have less violations.
But main point will be even violation become different, or stay, we will see if it is correct or not.

**Comment by mohitsatr** [comment]
it's quite weird. I tested it locally with same config and it passes without any problem.

**Comment by mohitsatr** [comment]
Github, generate report for Indentation/Example1

**Comment by mohitsatr** [comment]
Github, generate report

**Comment by mohitsatr** [comment]
Github, generate report

**Comment by mohitsatr** [comment]
Github, generate report

**Comment by mohitsatr** [comment]
@romani report is ready.

File: src/test/java/com/puppycrawl/tools/checkstyle/checks/indentation/IndentationCheckTest.java [hunk 1]
```diff
@@ -50,6 +50,7 @@
 /**
  * Unit test for IndentationCheck.
  */
+// -@cs[JavaNCSS] testing phase.
 public class IndentationCheckTest extends AbstractModuleTestSupport {
```
Comment (romani) [inline src/test/java/com/puppycrawl/tools/checkstyle/checks/indentation/IndentationCheckTest.java:54]: Please move this suppression to external suppression file.
https://github.com/checkstyle/checkstyle/blob/master/config/suppressions.xml

**Review by romani — CHANGES_REQUESTED** [review]
Last minor:

File: src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/indentation/indentation/InputIndentationSwitchOnStartOfLine.java [hunk 2]
```diff
@@ -0,0 +1,37 @@
...
+ * This test-input is intended to be checked using following configuration: //indent:1 exp:1
+ * basicOffset = 2                                                          //indent:1 exp:1
+ * braceAdjustment = 2                                                      //indent:1 exp:1
+ * caseIndent = 2                                                           //indent:1 exp:1
+ * tabWidth = 4                                                             //indent:1 exp:1
+ * lineWrappingIndentation = 4                                              //indent:1 exp:1
+ * throwsIndent = 4                                                         //indent:1 exp:1
+ */                                                                         //indent:1 exp:1
+
+public class InputIndentationSwitchOnStartOfLine {                          //indent:0 exp:0
```
Comment (romani) [inline src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/indentation/indentation/InputIndentationSwitchOnStartOfLine.java:15]: Please make copy of this input to Google style folder Inputs.

User reported issue on Google style, we need add it to Google style test suite also.
In general we can have validation on any config .

**Review by romani — CHANGES_REQUESTED** [review]
Itet

File: src/test/java/com/puppycrawl/tools/checkstyle/checks/indentation/IndentationCheckTest.java (hunk 1 above)
Comment (romani) [reply src/test/java/com/puppycrawl/tools/checkstyle/checks/indentation/IndentationCheckTest.java:54]: Please add few cases with violations in both Inputs to show that we are keeping doing validation.

**Comment by romani** [comment]
Just curious, how much violations are on camunda , if just run Indentation validation of config that you have in PR description.
I think we can use `New module config: {{URI to new_module_config.xml}}` to get this.

**Comment by mohitsatr** [comment]
I'm having some difficulties specifying violations in google test suit.

Screenshot from 2025-03-10 08-06-39

Screenshot from 2025-03-10 08-07-30

image

every other test-case function has not specified any expected violation in them, so i was just following them.
could be due to the asteriks(*) in the input files ?
I could use full violation message here, but message comment exceeds the 100 line length.

File: src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/indentation/indentation/InputIndentationSwitchOnStartOfLine.java (hunk 2 above)
Comment (mohitsatr) [reply src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/indentation/indentation/InputIndentationSwitchOnStartOfLine.java:15]: https://github.com/checkstyle/checkstyle/pull/16418#issuecomment-2709294397 ??

**Comment by Zopsss** [comment]
Can you try to debug to see what are the unexpected violations? If they're about line length limit then try to trim violation messages to:

```
// violation 'case' child * level 10, expected * 12
```

**Comment by Zopsss** [comment]
> Can you try to debug to see what are the unexpected violations? If they're about line length limit then try to trim violation messages to:
> 
> ```
> // violation 'case' child * level 12, expected * 10
> ```

**Comment by mohitsatr** [comment]
@Zopsss I figured it out. regexp was not catching it because (`""`) were missing.
`// violation "'case' child * level 8, expected * 10"`

But now 

Screenshot from 2025-03-11 09-34-00

Screenshot from 2025-03-11 09-34-19

as you can, full message causes line-length issue, but it is not accepting shortened message either.

**Comment by Zopsss** [comment]
Add `.` at the end of your message and please always push changes to let us see the whole code

**Comment by mohitsatr** [comment]
@Zopsss `.` at the end does not help either. please check the code

**Comment by mohitsatr** [comment]
okay figured it out.

**Comment by mohitsatr** [comment]
i feel like there should be a page on the website about how to specify violations in input files, with different formats. we could also add how to write test functions. It'd make really easy for newcomers and time-saving as well. and we could avoid many repetitive questions on this . @romani what do you think, should i open an issue ?

**Comment by mohitsatr** [comment]
> Just curious, how much violations are on camunda , if just run Indentation validation of config that you have in PR description. I think we can use `New module config: {{URI to new_module_config.xml}}` to get this. But we need list of projects to be only camunda.

let's try

File: src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/indentation/indentation/InputIndentationSwitchOnStartOfLine.java (hunk 2 above)
Comment (mohitsatr) [reply src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/indentation/indentation/InputIndentationSwitchOnStartOfLine.java:15]: done

**Comment by mohitsatr** [comment]
Github, generate report

**Comment by mohitsatr** [comment]
did I do something wrong in the configs/project file ?

**Comment by mohitsatr** [comment]
Github, generate report

**Comment by mohitsatr** [comment]
Github, generate report

**Comment by romani** [comment]
>should i open an issue ?

Please create issue and feel free to send PR to resolve it, as look like know all pain points

**Comment by mohitsatr** [comment]
@romani is this https://github.com/checkstyle/checkstyle/pull/16418#issuecomment-2720888779 what we wanted ?

File: src/it/resources-noncompilable/com/google/checkstyle/test/chapter4formatting/rule4841indentation/InputSwitchOnStartOfTheLine.java [hunk 3]
```diff
@@ -0,0 +1,47 @@
+// non-compiled with javac: Compilable with Java17
+
+package com.google.checkstyle.test.chapter4formatting.rule42blockindentation;
+
+/**some javadoc.*/
+public class InputSwitchOnStartOfTheLine {
+  String testMethod1(int i) {
+    String s =
+        switch (i) {
+          case 1 -> "one";
```
Comment (romani) [inline src/it/resources-noncompilable/com/google/checkstyle/test/chapter4formatting/rule4841indentation/InputSwitchOnStartOfTheLine.java:10]: please make copy of correct to
...Correct.java files

see examples: https://github.com/checkstyle/checkstyle/tree/main/src/it/resources/com/google/checkstyle/test/chapter4formatting/rule4841indentation

in this case formatter will confirm that no violation from Checkstyle means no violation from java google formatter

**Review by romani — CHANGES_REQUESTED** [review]
>is this https://github.com/checkstyle/checkstyle/pull/16418#issuecomment-2720888779 what we wanted ?

unfortunately too much violation to take use from it, but yes conceptually it is.
I just tried to find config that will produce minimal amount of violations, to let it reviewable by humans.

----


very good.

last request:

File: src/it/resources-noncompilable/com/google/checkstyle/test/chapter4formatting/rule4841indentation/InputSwitchOnStartOfTheLine.java (hunk 3 above)
Comment (mohitsatr) [reply src/it/resources-noncompilable/com/google/checkstyle/test/chapter4formatting/rule4841indentation/InputSwitchOnStartOfTheLine.java:10]: the file is already in the right location in resources-noncompilable section. trying to put it in https://github.com/checkstyle/checkstyle/tree/main/src/it/resources/com/google/checkstyle/test/chapter4formatting/rule4841indentationhere trigger IDEA errors about switch expression not being compartiable with java11.

Comment (romani) [reply src/it/resources-noncompilable/com/google/checkstyle/test/chapter4formatting/rule4841indentation/InputSwitchOnStartOfTheLine.java:10]: Keep same top folder, but name file ..... Correct.java, to let CI run formatting on it.

Comment (mohitsatr) [reply src/it/resources-noncompilable/com/google/checkstyle/test/chapter4formatting/rule4841indentation/InputSwitchOnStartOfTheLine.java:10]: done

**Review by rdiachenko — APPROVED** [review]
lgtm
