### PR TITLE
Issue #11220: False positive in MissingSwitchDefault with pattern in switch label

### LINKED ISSUE #11220: False positive in `MissingSwitchDefault` with pattern in switch label
After https://github.com/checkstyle/checkstyle/pull/11100#issue-1087470400:

I have read check documentation: https://checkstyle.sourceforge.io/config_coding.html#MissingSwitchDefault
I have downloaded the latest checkstyle from: https://checkstyle.org/cmdline.html#Download_and_Run
I have executed the cli and showed it below, as cli describes the problem better than 1,000 words

```bash

➜  company javac --enable-preview --release 17 Test.java                    
Note: Test.java uses preview features of Java SE 17.
Note: Recompile with -Xlint:preview for details.

➜  cat config.xml                                                   
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
        "-//Checkstyle//DTD Checkstyle Configuration 1.3//EN"
        "https://checkstyle.org/dtds/configuration_1_3.dtd">
<module name="Checker">
    <module name="TreeWalker">
        <module name="MissingSwitchDefault">
        </module>
    </module>
</module>

➜  cat Test.java                                                    
public class Test {
    static void test4(Object o) {
        switch (o) { // ok
            case null, String s -> System.out.println("String, including null");
            default -> System.out.println("something else");
        }

        switch (o) { // ok
            case null, String s: System.out.println("String, including null"); break;
            default: System.out.println("something else");
        }

        // The following switch statements are equivalent:

        switch(o) {
            case null: default: // ok
                System.out.println("The rest (including null)");
        }

        switch(o) { // false positive, should be ok
            case null, default ->
                System.out.println("The rest (including null)");
        }

        switch(o) { // false positive, should be ok
            case null, default:
                throw new UnsupportedOperationException("not supported!");
        }
    }
}

➜  java -jar checkstyle-9.3-SNAPSHOT-all.jar -c config.xml Test.java
Starting audit...
[ERROR] Test.java:20:9: switch without "default" clause. [MissingSwitchDefault]
[ERROR] Test.java:25:9: switch without "default" clause. [MissingSwitchDefault]
Audit done.
Checkstyle ends with 2 errors.


```

I would expect Checkstyle to find no violations in this code example.

### PR DESCRIPTION
**Pull request by nmancus1**
Closes #11220 

Report label: all projects

Diff Regression config: https://gist.githubusercontent.com/nmancus1/3db3e23a5063857160d7d92cbdfa1bfe/raw/b8fc9b284c6604bf0862f237f030794bfb0a7800/config.xml

Diff Regression projects: https://raw.githubusercontent.com/checkstyle/contribution/e34312d61da0b073f31339cfbf385f289b721fed/checkstyle-tester/projects-to-test-on-for-github-action.properties

Final report: https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/f5590ec_2022232703/reports/diff/index.html

Only diffs are in openjdk17, in noncompilable files. I am not sure if we should add files filters for these files, though, since they are how I confirmed logic of check update. I think that they might be valuable in the future for similar reasons.

Blocked until https://github.com/checkstyle/checkstyle/pull/11100

Only last commit is under review.

Example of compile error on new enum value:
```
$ cat Test.java 
public class Test {
enum Color { RED, GREEN, BLUE, MY_COLOR }

/**
 * In the case of switch expressions, the compiler requires
 * that they are exhaustive, so this check does not enforce
 * a default label. This code would still compile with a
 * default label, but it is unnecessary so this check does
 * not enforce it.
 */
static int showSwitchExpressionExhaustiveness(Color color) {
    switch (color) {
        case RED: System.out.println("RED"); break;
        case BLUE: System.out.println("BLUE"); break;
        case GREEN: System.out.println("GREEN"); break;
        // Check will require default label below, compiler
        // does not enforce a switch statement with constants
        // to be complete.
        //default: System.out.println("Something else");
    }

    // Check will not require default label in switch
    // expression below, because code will not compile
    // if all possible values are not handled. If the
    // 'Color' enum is extended, code will fail to compile.
    return switch (color) {
        case RED:
            yield 1;
        case GREEN:
            yield 2;
        case BLUE:
            yield 3;
    };
}

  }

$ javac --enable-preview --release 17 Test.java 
Test.java:26: error: the switch expression does not cover all possible input values
    return switch (color) {
           ^
1 error

```

### CODE REVIEW

**Comment by nmancus1** [comment]
Github, generate report

**Comment by nmancus1** [comment]
Github, generate report

**Comment by nmancus1** [comment]
Github, generate report

**Comment by nmancus1** [comment]
Github, generate report

**Comment by nmancus1** [comment]
Github, generate report

**Comment by nmancus1** [comment]
Github, generate report

**Comment by nmancus1** [comment]
Github, generate report

**Comment by nmancus1** [comment]
Github, generate report

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/MissingSwitchDefaultCheck.java [hunk 1]
```diff
@@ -116,33 +124,86 @@
...
         return found;
     }
 
+    /**
+     * Checks if the case group or its sibling contain the 'default' switch.
+     *
+     * @param caseGroupAst first case group to check.
+     * @return true if 'default' switch found.
+     */
+    private static boolean containsDefaultLabel(DetailAST caseGroupAst) {
```
Comment (nmancus1) [inline src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/MissingSwitchDefaultCheck.java]: Changed the name of this method to be consistent with language from the JLS: https://docs.oracle.com/javase/specs/jls/se17/preview/specs/patterns-switch-jls.html

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/MissingSwitchDefaultCheck.java [hunk 2]
```diff
@@ -127,22 +139,71 @@ public void visitToken(DetailAST ast) {
      * @param caseGroupAst first case group to check.
      * @return true if 'default' switch found.
      */
-    private static boolean containsDefaultSwitch(DetailAST caseGroupAst) {
```
Comment (nmancus1) [inline src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/MissingSwitchDefaultCheck.java:130]: Changed the name of this method to be consistent with language from the JLS: https://docs.oracle.com/javase/specs/jls/se17/preview/specs/patterns-switch-jls.html

This language is also used throughout the check for consistency.

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/MissingSwitchDefaultCheck.java [hunk 3]
```diff
@@ -168,4 +229,25 @@ private static boolean isSwitchExpression(DetailAST ast) {
...
+    /**
+     * Iterates through siblings of an ast node, evaluating given predicate for each
+     * sibling and returns the first matching node. This operation includes
+     * evaluation of the given node.
+     *
+     * @param ast the ast to check self and siblings of
+     * @param predicate the expression to evaluate
+     * @return first matching node, or null if matching node is not present
+     */
+    private static DetailAST findAstByPredicate(DetailAST ast, Predicate<DetailAST> predicate) {
```
Comment (nmancus1) [inline src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/MissingSwitchDefaultCheck.java:241]: It made sense to extract the logic of finding a particular ast by some predicate, almost all private methods in this check have similar logic now that we can have syntax like `case null, default:`. We just check all case label elements for each case.

File: src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/missingswitchdefault/InputMissingSwitchDefaultCaseLabelElements.java [hunk 4]
```diff
@@ -0,0 +1,91 @@
...
+        switch(o) { // ok
+            case null, default:
+                throw new UnsupportedOperationException("not supported!");
+        }
+    }
+
+    void m2(String s) {
+        switch (s) { // ok
+            case "a": throw new AssertionError("Wrong branch.");
+            case default: break;
```
Comment (nmancus1) [inline src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/missingswitchdefault/InputMissingSwitchDefaultCaseLabelElements.java:84]: `default` case label

**Review by nmancus1 — COMMENTED** [review]
Comments:

**Comment by nmancus1** [comment]
Github, generate report

File: src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/missingswitchdefault/InputMissingSwitchDefault.java [hunk 5]
```diff
@@ -49,5 +49,9 @@ public void nestedSwitch2() {
             }
             default: break;
         }
+
+        switch(i) { // violation
```
Comment (nmancus1) [inline src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/missingswitchdefault/InputMissingSwitchDefault.java:53]: Needed to add this for coverage, but will not compile after Java 17.

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/MissingSwitchDefaultCheck.java (hunk 3 above)
Comment (pbludov) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/MissingSwitchDefaultCheck.java:212]: Why not `TokenUtil#findFirstTokenByPredicate` ?

Comment (nmancus1) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/MissingSwitchDefaultCheck.java:212]: > Why not `TokenUtil#findFirstTokenByPredicate` ?

Because I completely forgot about it :) Thank you.

**Comment by nmancus1** [comment]
Github, generate report

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/MissingSwitchDefaultCheck.java (hunk 3 above)
Comment (nmancus1) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/MissingSwitchDefaultCheck.java]: Done.

**Review by pbludov — APPROVED** [review]

File: src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/missingswitchdefault/InputMissingSwitchDefault.java (hunk 5 above)
Comment (romani) [reply src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/missingswitchdefault/InputMissingSwitchDefault.java:53]: we do not need sources that are not compilable. Whole idea of Input file compilations is to make sure that we never executes on weird files and AST is always predictable. We removed a lot of code from Checks after enforcement of compilation.

Please share problems with coverage.

File: src/xdocs/config_coding.xml [hunk 6]
```diff
@@ -4233,7 +4233,8 @@ abstract class AbstractExample { // OK
           protected against later changes, e.g. introduction of new types in an
           enumeration type. Note that the compiler requires switch expressions
           to be exhaustive, so this check does not enforce default branches on
-          such expressions.
+          such expressions. Switch blocks containing pattern case label elements
+          are also required to be exhaustive, and require no default label.
```
Comment (romani) [inline src/xdocs/config_coding.xml:4237]: I and probably users need more details on this.
Even original switch do not require default. Requirement for default is style or best practice concern.

**Review by romani — CHANGES_REQUESTED** [review]
items:

File: src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/missingswitchdefault/InputMissingSwitchDefault.java (hunk 5 above)
Comment (nmancus1) [reply src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/missingswitchdefault/InputMissingSwitchDefault.java:53]: This syntax compiles in all Java versions before Java 17. We have this test case (empty switch) in google style test, but not in actual unit tests for this check.

Comment (romani) [reply src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/missingswitchdefault/InputMissingSwitchDefault.java:53]: False alarm, it in compiled file now. I thought it is non compiled.

File: src/xdocs/config_coding.xml (hunk 6 above)
Comment (nmancus1) [reply src/xdocs/config_coding.xml]: A few more details added here, and I have greatly expanded the examples section.

**Comment by nmancus1** [comment]
Github, generate site

**Comment by nmancus1** [comment]
GitHub, rebase

**Comment by nmancus1** [comment]
Link to exact check documentation: https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/b89b1d1_2022170715/config_coding.html#MissingSwitchDefault

File: src/xdocs/config_coding.xml (hunk 6 above)
Comment (nmancus1) [reply src/xdocs/config_coding.xml]: Link to exact check documentation: https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/b89b1d1_2022170715/config_coding.html#MissingSwitchDefault

Comment (romani) [reply src/xdocs/config_coding.xml]: >Note that the compiler requires switch expressions to be exhaustive

I do not know what it means, can you place link to more detailed explanation of exhaustive

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/MissingSwitchDefaultCheck.java [hunk 7]
```diff
@@ -65,13 +68,72 @@
...
+ * }
+ *
+ * enum Color { RED, GREEN, BLUE }
+ *
+ * /**
+ *  * In the case of switch expressions, the compiler requires
+ *  * that they are exhaustive, so this check does not enforce
+ *  * a default label. This code would still compile with a
+ *  * default label, but it is unnecessary so this check does
+ *  * not enforce it.
```
Comment (romani) [inline src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/MissingSwitchDefaultCheck.java:126]: This absolutely same as we have default in regular switch .
To catch unexpected extending of  enum. Does complier place compilation error on such enum if enum extended for new element?

**Review by romani — CHANGES_REQUESTED** [review]
Item:

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/MissingSwitchDefaultCheck.java (hunk 7 above)
Comment (romani) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/MissingSwitchDefaultCheck.java:126]: Please update example and doc to mention fact that missed element will trigger compilation error. So Check activity is not required.

Comment (nmancus1) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/MissingSwitchDefaultCheck.java:126]: This is shown in existing example:

```
/**
 * In the case of switch expressions, the compiler requires
 * that they are exhaustive, so this check does not enforce
 * a default label. This code would still compile with a
 * default label, but it is unnecessary so this check does
 * not enforce it.
 */

```

Comment (romani) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/MissingSwitchDefaultCheck.java:126]: It is not clear.
You are too smart on jdk syntax terminology, most users are not operating by such terminology.

Comment (nmancus1) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/MissingSwitchDefaultCheck.java]: Updated examples and documentation.

File: src/xdocs/config_coding.xml (hunk 6 above)
Comment (nmancus1) [reply src/xdocs/config_coding.xml]: Updated wording and provided relevant link.

**Comment by romani** [comment]
Github, generate site

**Comment by nmancus1** [comment]
Documentation needs an update to make hyperlink, I will do this ASAP

**Comment by nmancus1** [comment]
Github, generate site

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/MissingSwitchDefaultCheck.java (hunk 7 above)
Comment (nmancus1) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/MissingSwitchDefaultCheck.java]: https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/8d658f0_2022035457/config_coding.html#MissingSwitchDefault

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/MissingSwitchDefaultCheck.java [hunk 8]
```diff
@@ -38,7 +39,15 @@
  * introduction of new types in an enumeration type. Note that
  * the compiler requires switch expressions to be exhaustive,
  * so this check does not enforce default branches on
- * such expressions.
+ * such expressions. Also, switch statements that use pattern or null
+ * labels are checked by the compiler for completeness (exhaustiveness), so
```
Comment (romani) [inline src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/MissingSwitchDefaultCheck.java:43]: switch statement - Check do validation
switch expression - Check does no validation.
`.... Also, switch expression that use pattern or null labels are checked by the compiler for completeness/exhaustiveness (example: it is compile error if any enum value is missed), so`

please fix other places statement -> expression.

**Review by romani — CHANGES_REQUESTED** [review]
item:

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/MissingSwitchDefaultCheck.java (hunk 8 above)
Comment (romani) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/MissingSwitchDefaultCheck.java:43]: > switch expression - Check does no validation.

if this is true, we probably can state simple like this.

Comment (nmancus1) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/MissingSwitchDefaultCheck.java:43]: >switch expression... we probably can state simple like this. At the begining, and keep all other details following.

Good idea, I agree.

> switch statement - Check do validation

> please fix other places where you have statement -> expression.

This is not accurate; the check will not validate switch statements that use pattern or null labels (as described in documentation in this PR), since the compiler does this. In fact, as described in the javadocs in my new example, it would cause a compiler error if a default clause were added, in the case of totality. Example:

```

➜  src cat Test.java
public class Test {

    void method(String s) {
        switch (s) {
            case Object o:
                System.out.println("Object!");
            default:
                System.out.println("default!");
        }
    }
}
➜  src javac --enable-preview --release 17 Test.java
Test.java:7: error: switch has both a total pattern and a default label
            default:
                   ^
Note: Test.java uses preview features of Java SE 17.
Note: Recompile with -Xlint:preview for details.
1 error


```

Compiler enforcing exhaustiveness for switch statement with pattern label:

```
➜  src cat Test.java                                
import java.util.ArrayList;
import java.util.List;

public class Test {

    void method(List<String> l) {
        switch (l) {
            case ArrayList ar:
                System.out.println("arraylist!");
        }
    }
}
➜  src javac --enable-preview --release 17 Test.java
Test.java:7: error: the switch statement does not cover all possible input values
        switch (l) {
        ^
Note: Test.java uses preview features of Java SE 17.
Note: Recompile with -Xlint:preview for details.
1 error


```

Similarly, also consider:

```
➜  src cat Test.java                                
import java.util.ArrayList;
import java.util.List;

public class Test {

    void method(List<String> l) {
        switch (l) {
            case null:
                System.out.println("arraylist!");
        }
    }
}
➜  src javac --enable-preview --release 17 Test.java
Test.java:7: error: the switch statement does not cover all possible input values
        switch (l) {
        ^
Note: Test.java uses preview features of Java SE 17.
Note: Recompile with -Xlint:preview for details.
1 error

```

Comment (nmancus1) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/MissingSwitchDefaultCheck.java]: Ok, I made language a lot more clear and went into details in the examples.

**Comment by romani** [comment]
GitHub, generate web site

**Comment by nmancus1** [comment]
Github, rebase

**Review by romani — APPROVED** [review]
Ok to merge

File: src/main/resources/com/puppycrawl/tools/checkstyle/meta/checks/coding/MissingSwitchDefaultCheck.xml [hunk 9]
```diff
@@ -17,7 +17,9 @@
  introduction of new types in an enumeration type. Note that
  the compiler requires switch expressions to be exhaustive,
  so this check does not enforce default branches on
- such expressions.
+ such expressions. Also, switch statements that use pattern or null
```
Comment (rnveach) [inline src/main/resources/com/puppycrawl/tools/checkstyle/meta/checks/coding/MissingSwitchDefaultCheck.xml:20]: @romani Am I missing something that this file looks manually changed and isn't using the description in the javadoc and xdoc?

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/MissingSwitchDefaultCheck.java [hunk 10]
```diff
@@ -35,10 +36,23 @@
...
+ * <p>
+ * This check does not validate any switch expressions. Rationale:
+ * the compiler requires switch expressions to be exhaustive. This means
+ * that all possible inputs must be covered.
+ * </p>
+ * <p>
+ * This check does not validate switch statements that use pattern or null
+ * labels. Rationale: switch statements that use pattern or null labels are
+ * checked by the compiler for exhaustiveness. This means that all possible
+ * inputs must be covered.
```
[the remark this answers is not in the document]
Comment (nmancus1) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/MissingSwitchDefaultCheck.java:50]: > Why not combine these 2 paragraphs into 1? They both talk about it needing to be exhaustive and all inputs covered.

The idea is to make it very obvious that conditions for switch expressions and switch statements are different.

> To confirm, if all inputs are not covered this will result in a compile error, correct? Unless you disagree, maybe that point can also be added.

This is explained in comments in code below to make basic check description language as simple as possible.

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/MissingSwitchDefaultCheck.java [hunk 11]
```diff
@@ -35,10 +36,23 @@
...
  * the code is protected against later changes, e.g.
- * introduction of new types in an enumeration type. Note that
- * the compiler requires switch expressions to be exhaustive,
- * so this check does not enforce default branches on
- * such expressions.
+ * introduction of new types in an enumeration type.
+ * </p>
+ * <p>
+ * This check does not validate any switch expressions. Rationale:
+ * the compiler requires switch expressions to be exhaustive. This means
```
[the remark this answers is not in the document]
Comment (nmancus1) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/MissingSwitchDefaultCheck.java]: Done.

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/MissingSwitchDefaultCheck.java [hunk 12]
```diff
@@ -65,15 +79,81 @@
  *  default: // OK
  *    break;
  * }
- * return switch (option) { // OK, the compiler requires switch expression to be exhaustive
```
[the remark this answers is not in the document]
Comment (nmancus1) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/MissingSwitchDefaultCheck.java:68]: I moved it to new `Example of correct code which does not require default labels` section, it belongs there now.

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/MissingSwitchDefaultCheck.java [hunk 13]
```diff
@@ -65,15 +79,81 @@
...
+ *    sealed interface S permits A, B, C {}
+ *    final class A implements S {}
+ *    final class B implements S {}
+ *    record C(int i) implements S {}  // Implicitly final
+ *
+ *    /**
+ *     * The completeness of a switch statement can be
+ *     * determined by the contents of the permits clause
+ *     * of interface S. No default label or default case
+ *     * label is allowed by the compiler in this situation, so
```
[the remark this answers is not in the document]
Comment (nmancus1) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/MissingSwitchDefaultCheck.java:104]: https://github.com/checkstyle/checkstyle/pull/11221/files#r789078911

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/MissingSwitchDefaultCheck.java (hunk 12 above)
[the remark this answers is not in the document]
Comment (rnveach) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/MissingSwitchDefaultCheck.java:68]: Sorry, I missed this.

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/MissingSwitchDefaultCheck.java (hunk 10 above)
[the remark this answers is not in the document]
Comment (nmancus1) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/MissingSwitchDefaultCheck.java:50]: Admittedly, all requirements for compilation of switch statements are a bit complicated right now. This is probably due to Java encouraging exhaustiveness for **all** switch statements in the future.

From https://openjdk.java.net/jeps/420:

`Future compilers of the Java language may emit warnings for legacy switch statements that are not exhaustive.`

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/MissingSwitchDefaultCheck.java (hunk 13 above)
[the remark this answers is not in the document]
Comment (rnveach) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/MissingSwitchDefaultCheck.java:104]: I am not finding this in the 17 language specification.
https://docs.oracle.com/javase/specs/

File: src/main/resources/com/puppycrawl/tools/checkstyle/meta/checks/coding/MissingSwitchDefaultCheck.xml (hunk 9 above)
Comment (rnveach) [reply src/main/resources/com/puppycrawl/tools/checkstyle/meta/checks/coding/MissingSwitchDefaultCheck.xml]: @nmancus1 Are you manually modifying this file?

Comment (nmancus1) [reply src/main/resources/com/puppycrawl/tools/checkstyle/meta/checks/coding/MissingSwitchDefaultCheck.xml]: >  Are you manually modifying this file?

No.

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/MissingSwitchDefaultCheck.java (hunk 13 above)
[the remark this answers is not in the document]
Comment (nmancus1) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/MissingSwitchDefaultCheck.java:104]: https://openjdk.java.net/jeps/420

[the remark this answers is not in the document]
Comment (rnveach) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/MissingSwitchDefaultCheck.java:104]: Thanks I am not having luck googling it. I wanted to read what exactly is `case default`.

[the remark this answers is not in the document]
Comment (rnveach) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/MissingSwitchDefaultCheck.java:104]: Closing.

File: src/main/resources/com/puppycrawl/tools/checkstyle/meta/checks/coding/MissingSwitchDefaultCheck.xml (hunk 9 above)
Comment (romani) [reply src/main/resources/com/puppycrawl/tools/checkstyle/meta/checks/coding/MissingSwitchDefaultCheck.xml]: Such files are updated by test that generate meta data

**Comment by romani** [comment]
GitHub, generate web site

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/MissingSwitchDefaultCheck.java (hunk 10 above)
[the remark this answers is not in the document]
Comment (romani) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/MissingSwitchDefaultCheck.java:50]: It might be complicated wording will be if we combine. I tried to combine and it became hard to read.

**Review by rnveach — APPROVED** [review]
