### PR TITLE
Issue #7812: OneTopLevelClass: Improve data structure efficiency

### LINKED ISSUE #7812: OneTopLevelClass: Improve data structure efficiency
From https://github.com/checkstyle/checkstyle/pull/7790#discussion_r389439081

In PR #7790 we changed `OneTopLevelClass` to log violations using the DetailAST node itself, rather than just the line number. However that is a very minimal change to the check functionality and was more focused on the changes to unit/integration/regression testing, where we now log the column number as well.

There is a bit of inefficiency in the way this check works. In particular, the problem is that we are using a `TreeMap` to store our (potential) violations. Some observations:
1. Although a `TreeMap` can help us to maintain that the nodes are in the correct order, there is no need to do this as the AST traversal in `beginTree` should already visit all of the nodes in the correct order. As long as we store the nodes in a way that preserves this "traversal order", that is sufficient for our purposes.
2. There is no longer a need to store the type name together with the node, as we can simply derive the type name from the node itself.

Hence, I am suggesting to replace the usage of `SortedMap` and `TreeMap` with a more appropriate data structure such as `Queue<DetailAST>`. This will reduce the runtime of `beginTree` from O(m + n log n) to just O(m) for m nodes and n violations, and also removes the redundant string storage for type name.

Open to more ideas on even better ways to implement this, maybe just use the node given in `finishTree` and traverse it again?

### PR DESCRIPTION
**Pull request by wltan**
Fix #7812: OneTopLevelClass: Improve data structure efficiency

Even though this is not really important, I feel that I should at least tie up the loose end from https://github.com/checkstyle/checkstyle/pull/7790#discussion_r389439081. Right now using a `SortedMap` just to store a redundant line number is an awkward implementation, no matter how you look at it.

Regression: https://wltan.github.io/checkstyle-reports/2020-03-26/onetoplevel-detailast-regression/diff/

### CODE REVIEW

**Comment by romani** [comment]
@rnveach , please review this PR first, looks like you were at the beginning of discussion.

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/design/OneTopLevelClassCheck.java [hunk 1]
```diff
@@ -126,41 +113,49 @@
...
-            }
-
-            for (Map.Entry<DetailAST, String> entry
-                    : lineNumberTypeMap.entrySet()) {
-                log(entry.getKey(), MSG_KEY, entry.getValue());
+        DetailAST currentNode = rootAST;
+        boolean firstTypeSkipped = false;
+        while (currentNode != null) {
+            if (isTypeDef(currentNode) && !isPublic(currentNode)) {
+                if (publicTypeFound || firstTypeSkipped) {
```
Comment (rnveach) [inline src/main/java/com/puppycrawl/tools/checkstyle/checks/design/OneTopLevelClassCheck.java]: @romani 
> Checks that each top-level class, interface or enum resides in a source file of its own.

If we have 2 public classes in the same file, shouldn't we produce a violation on one of them since there is more than 1 top level class?

````
$ cat TestClass.java
public class TestClass1 {
    void method() {
    }
}
public class TestClass2 {
    void method() {
    }
}

$ cat TestConfig.xml
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
          "-//Puppy Crawl//DTD Check Configuration 1.3//EN"
          "https://checkstyle.org/dtds/configuration_1_3.dtd">

<module name="Checker">
    <property name="charset" value="UTF-8"/>

    <module name="TreeWalker">
<module name="OneTopLevelClassCheck" />
    </module>
</module>

$ java -jar checkstyle-8.30-all.jar -c TestConfig.xml TestClass.java
Starting audit...
Audit done.
````

Shouldn't we expect a violation on line 5?

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/design/OneTopLevelClassCheck.java [hunk 2]
```diff
@@ -126,41 +113,49 @@
...
-                if (isPublic(currentNode)) {
-                    publicTypeFound = true;
-                }
-                else {
-                    final String typeName = currentNode
-                            .findFirstToken(TokenTypes.IDENT).getText();
-                    lineNumberTypeMap.put(currentNode, typeName);
-                }
+            if (isTypeDef(currentNode) && isPublic(currentNode)) {
+                publicTypeFound = true;
```
Comment (rnveach) [inline src/main/java/com/puppycrawl/tools/checkstyle/checks/design/OneTopLevelClassCheck.java]: Now the code is trimmed down to a bare 2 methods, both look like they pretty much do the same thing. `beginTree` only checks for a public type and `finishTree` does the final violations. Other than that they both do the same thing and scan all the siblings connected to the root.

I question if we should just merge the 2 methods together and remove all the fields, and see if we can do the AST sibling scan only once. What is the benefit now of keeping them in different methods?

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/design/OneTopLevelClassCheck.java [hunk 3]
```diff
@@ -126,41 +113,49 @@
...
 
+    /**
+     * Checks if an AST node is a type definition.
+     * @param node AST node to check.
+     * @return true if the node is a type (class, enum, interface) definition.
+     */
+    public static boolean isTypeDef(DetailAST node) {
+        return node.getType() == TokenTypes.CLASS_DEF
+                || node.getType() == TokenTypes.ENUM_DEF
+                || node.getType() == TokenTypes.INTERFACE_DEF;
```
[the remark this answers is not in the document]
Comment (wltan) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/design/OneTopLevelClassCheck.java]: Opened issue #7957 for this

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/design/OneTopLevelClassCheck.java (hunk 1 above)
Comment (wltan) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/design/OneTopLevelClassCheck.java]: \>1 public type will give a compile error, but I do agree that the current behavior is counterintuitive.

If you want, I can fix it here or open another issue.

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/design/OneTopLevelClassCheck.java (hunk 2 above)
Comment (wltan) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/design/OneTopLevelClassCheck.java]: I've managed to squash everything into one pass, so now there's only one method and no instance fields.

The only side effect is that our first type is stored somewhere and we only check if it is a violation at the end of the loop. The UTs aren't affected, so it should be all good. Might do another regression report later.

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/design/OneTopLevelClassCheck.java (hunk 1 above)
Comment (rnveach) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/design/OneTopLevelClassCheck.java]: Sorry, I didn't realize it is not compilable.

**Comment by rnveach** [comment]
With no instance fields, this check needs to be changed from FileStatefulCheck to StatelessCheck.

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/design/OneTopLevelClassCheck.java (hunk 2 above)
Comment (rnveach) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/design/OneTopLevelClassCheck.java]: New regression is required.

**Comment by rnveach** [comment]
CI needs to pass.

**Comment by wltan** [comment]
> With no instance fields, this check needs to be changed from FileStatefulCheck to StatelessCheck.

Done

> CI needs to pass.

I had a redundant condition previously. Pitest should be ok now.

Travis is failing due to the referenced issue not being approved. Not much I can do about that short of removing the reference (probably not a good idea).

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/design/OneTopLevelClassCheck.java (hunk 2 above)
Comment (wltan) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/design/OneTopLevelClassCheck.java]: Updated.

New: https://wltan.github.io/checkstyle-reports/2020-03-26/onetoplevel-detailast-regression/diff/
Old: https://wltan.github.io/checkstyle-reports/2020-03-19/onetoplevel-detailast-regression/diff/

**Comment by rnveach** [comment]
Issue approval is our side. @romani I am fine with this change.

**Comment by romani** [comment]
@rnveach , please resolve all your review items to make me sure are satisfied.
Travis is failing as issue is not approved, looks like I need to approve issue.

**Comment by romani** [comment]
@wltan , as issue is about performance, please provide numbers of how performance i improving.

**Comment by romani** [comment]
issue is approved.
@strkkk , please do review before me as you are in context of problem.

**Comment by wltan** [comment]
> @wltan , as issue is about performance, please provide numbers of how performance i improving.

Is there any specific tool that we need to use? Will [JMH](https://openjdk.java.net/projects/code-tools/jmh/) be appropriate?

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/design/OneTopLevelClassCheck.java (hunk 3 above)
[the remark this answers is not in the document]
Comment (strkkk) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/design/OneTopLevelClassCheck.java:149]: actually, this method can be useful for some other checks and can be moved to some util class

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/design/OneTopLevelClassCheck.java [hunk 4]
```diff
@@ -125,42 +106,49 @@
...
+            log(firstType, MSG_KEY, typeName);
         }
     }
 
+    /**
+     * Checks if an AST node is a type definition.
+     * @param node AST node to check.
+     * @return true if the node is a type (class, enum, interface) definition.
+     */
+    public static boolean isTypeDef(DetailAST node) {
```
Comment (strkkk) [inline src/main/java/com/puppycrawl/tools/checkstyle/checks/design/OneTopLevelClassCheck.java:146]: why public?

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/design/OneTopLevelClassCheck.java [hunk 5]
```diff
@@ -125,42 +106,49 @@
 
     @Override
     public void beginTree(DetailAST rootAST) {
-        publicTypeFound = false;
-        lineNumberTypeMap.clear();
-
         DetailAST currentNode = rootAST;
+        boolean publicTypeFound = false;
+        DetailAST firstType = null;
```
Comment (strkkk) [inline src/main/java/com/puppycrawl/tools/checkstyle/checks/design/OneTopLevelClassCheck.java:111]: can it be changed to something like
```
DetailAST firstType = TokenUtil.findFirstTokenByPredicate(rootAST, this::isTypeDef)
```
? 
It will look better as current logic

**Comment by strkkk** [comment]
> as issue is about performance, please provide numbers of how performance i improving.

I found no mention of performance in original issue, just complexity. I think we  can skip some performance report requirement, it is not clear how to do it and some good input data is required for this. As for me, it does not worth it.

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/design/OneTopLevelClassCheck.java (hunk 4 above)
Comment (wltan) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/design/OneTopLevelClassCheck.java]: Should be private, fixed

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/design/OneTopLevelClassCheck.java (hunk 5 above)
Comment (wltan) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/design/OneTopLevelClassCheck.java:111]: We are iterating through siblings of `rootAST` as we are dealing with top-level declarations. `findFirstTokenByPredicate` will iterate through children of `rootAST` which is not what we want.

Trying `TokenUtil.findFirstTokenByPredicate(rootAST.getParent(), this::isTypeDef)` leads to some null pointer exceptions, presumably due to how `rootAST`'s parent is being handled.
