### PR TITLE
Issue #9071: New keyword throwing unresolvable indentation errors

### LINKED ISSUE #9071: Unresolvable 'new' Indentation Rule conflict introduced in 8.38
The following code snippet exists in my codebase and passes Checkstyle using 8.37 rules.  When run against the 8.38 rules, I get violations due to updated indentation rules in the release: "'operator new' has incorrect indentation level 24, expected level should be one of the following: 28, 32."

```
                redirectAttributes.addFlashAttribute("globalMessage",
                        new GenericResponse(ResponseStatus.ERROR, messages.getMessage("data.trigger.enable.failure",
                        new Object[] { ERROR_MSG })));
```

I changed the indentation level to 28, and got this Checkstyle rule violation:
"'new' has incorrect indentation level 28, expected level should be 24."
```
                redirectAttributes.addFlashAttribute("globalMessage",
                        new GenericResponse(ResponseStatus.ERROR, messages.getMessage("data.trigger.enable.failure",
                            new Object[] { ERROR_MSG })));
```

I also tried changing the indentation level to 32, and got this Checkstyle rule violation:
"'new' has incorrect indentation level 32, expected level should be 24."
```
                redirectAttributes.addFlashAttribute("globalMessage",
                        new GenericResponse(ResponseStatus.ERROR, messages.getMessage("data.trigger.enable.failure",
                                new Object[] { ERROR_MSG })));
```

[checkstyle.xml.zip](https://github.com/checkstyle/checkstyle/files/5622635/checkstyle.xml.zip)

### PR DESCRIPTION
**Pull request by Abhishek-kumar09**
---
- [ ] Have to make a PR to [pgjdbc](https://github.com/pgjdbc/pgjdbc) with commit: https://github.com/Abhishek-kumar09/pgjdbc/commit/62980e9bbc06a227b3d1f7ad4bbc6ae936aea0a3 once this PR is merged.
---

New Keyword was being checked at multiple times, one inside its own handler and one by the lineWrappingHandler.
Changed code to give all the powers to only newHandler.

Fixes #9071 
Diff Regression projects: https://gist.githubusercontent.com/Abhishek-kumar09/717190a7e2e06f4747b9c622692d4b99/raw/ce18e37ba0f30ce85d3f929a5821fa4178557232/projects-to-test-on.properties
Diff Regression config: https://gist.githubusercontent.com/Abhishek-kumar09/0745ecf11934e0214b9187f9d4896e4a/raw/2143ba7f21dcafb998019a1ca2c0ee3f1c510646/my_check.xml

### CODE REVIEW

**Comment by Abhishek-kumar09** [comment]
@romani Please approve issue #9071

**Comment by Abhishek-kumar09** [comment]
Github, generate report

**Comment by Abhishek-kumar09** [comment]
GIthub, generate report

**Comment by Abhishek-kumar09** [comment]
Github, generate report

File: src/it/resources/com/google/checkstyle/test/chapter4formatting/rule4841indentation/ClassWithChainedMethods.java [hunk 1]
```diff
@@ -24,7 +24,7 @@ public static void main(String[] args) { //indent:2 exp:2
     .length(); //indent:4 exp:>=8 warn
 
     int length2 =  //indent:4 exp:4
-    new ClassWithChainedMethods("param1","param2") //indent:4 exp:>=8 warn
+    new ClassWithChainedMethods("param1","param2") //indent:4 exp:4
```
Comment (romani) [inline src/it/resources/com/google/checkstyle/test/chapter4formatting/rule4841indentation/ClassWithChainedMethods.java:27]: it should be violation.

File: src/test/resources/com/puppycrawl/tools/checkstyle/checks/indentation/indentation/InputIndentationCustomAnnotation.java [hunk 2]
```diff
@@ -83,8 +83,8 @@
         @Override //indent:8 exp:8
         public String toString() { //indent:8 exp:8
             return //indent:12 exp:12
-                    new String( //indent:20 exp:20
-                            new StringBuilder("Hello") //indent:28 exp:28
+                    new String( //indent:20 exp:12,16 warn
```
Comment (romani) [inline src/test/resources/com/puppycrawl/tools/checkstyle/checks/indentation/indentation/InputIndentationCustomAnnotation.java:86]: linewrapping is 4.
So should be `//indent:20 exp: 16 warn`

we should not suggest indentation of `12` as it will be violation.

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/LineWrappingHandler.java [hunk 3]
```diff
@@ -69,6 +69,16 @@ public static LineWrappingOptions ofBoolean(boolean val) {
 
     }
 
+    /**
+     * The list of ignored token types for being checked by lineWrapping indentation
+     * inside {@code checkIndentation()}.
```
Comment (romani) [inline src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/LineWrappingHandler.java:74]: is it because they have their own handlers ?

File: src/test/java/com/puppycrawl/tools/checkstyle/checks/indentation/IndentationCheckTest.java [hunk 4]
```diff
@@ -668,8 +668,8 @@ public void testInvalidMethodWithChecker()
             "110:15: " + getCheckMessage(MSG_ERROR, "operator new", 14, 16),
             "113:11: " + getCheckMessage(MSG_CHILD_ERROR, "method call", 10, 12),
             "118:15: " + getCheckMessage(MSG_ERROR, "operator new", 14, 16),
-            "122:11: " + getCheckMessage(MSG_ERROR, "new", 10, 12),
-            "126:11: " + getCheckMessage(MSG_ERROR, "new", 10, 12),
+            "122:11: " + getCheckMessage(MSG_ERROR, "operator new", 10, 12),
```
Comment (romani) [inline src/test/java/com/puppycrawl/tools/checkstyle/checks/indentation/IndentationCheckTest.java:671]: diff report is heavily polluted by such update

can we avoid such wording update ?

**Review by romani — CHANGES_REQUESTED** [review]
items:

File: src/test/resources/com/puppycrawl/tools/checkstyle/checks/indentation/indentation/InputIndentationCustomAnnotation.java (hunk 2 above)
Comment (Abhishek-kumar09) [reply src/test/resources/com/puppycrawl/tools/checkstyle/checks/indentation/indentation/InputIndentationCustomAnnotation.java:86]: Yes, but earlier it was explictly coded like that to follow the current indent of parent, and then lineWrpping also (multi-indents) so left that logic.
In some cases it is good for code readability too, to indent new keyword just down its parent.
Though I could change the logic to strictly follow only lineWrapping.

File: src/it/resources/com/google/checkstyle/test/chapter4formatting/rule4841indentation/ClassWithChainedMethods.java (hunk 1 above)
Comment (Abhishek-kumar09) [reply src/it/resources/com/google/checkstyle/test/chapter4formatting/rule4841indentation/ClassWithChainedMethods.java:27]: Yes, it is suspicious. This file when I checked against the same config, thowed 17 errror (including above). But this is showing only 3 errors. 
Maybe it is only catching `warns` and not `errors` and since code for checking `new` is entirely  moved to its handler, The handler throws errors and doesn't being caught under the `warns` categories.
See the test logic: https://github.com/checkstyle/checkstyle/blob/820e08ba250eca642319f1ec74fef08848d784eb/src/it/java/com/google/checkstyle/test/chapter4formatting/rule4841indentation/IndentationTest.java#L139-L152

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/LineWrappingHandler.java (hunk 3 above)
Comment (Abhishek-kumar09) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/LineWrappingHandler.java:74]: Yes, they do interuptions with the dedicated handlers, like here in this issue.
So if everything is covered inside the handler, then no need to explicitly check it against the lineWrappingHandler.

File: src/test/java/com/puppycrawl/tools/checkstyle/checks/indentation/IndentationCheckTest.java (hunk 4 above)
Comment (Abhishek-kumar09) [reply src/test/java/com/puppycrawl/tools/checkstyle/checks/indentation/IndentationCheckTest.java:671]: I guess no.
Since Inside the newHandler the message is `new operator` and inside linewrapping it was only `new`.
Though its our choice to choose between `new` or `new operator`, but the diff report will still be polluted for once atleast.

File: src/it/resources/com/google/checkstyle/test/chapter4formatting/rule4841indentation/ClassWithChainedMethods.java (hunk 1 above)
Comment (Abhishek-kumar09) [reply src/it/resources/com/google/checkstyle/test/chapter4formatting/rule4841indentation/ClassWithChainedMethods.java:27]: see `getLinesWithWarn(filePath); ` on line 150.

**Comment by Abhishek-kumar09** [comment]
> 
@Abhishek-kumar09 , please make a comment in issue with strict following issue template and execution of same code on different version of checkstyle. Please minimize users code to keep what is matter only (keep structure of code).

Done

File: src/test/resources/com/puppycrawl/tools/checkstyle/checks/indentation/indentation/InputIndentationCustomAnnotation.java (hunk 2 above)
Comment (Abhishek-kumar09) [reply src/test/resources/com/puppycrawl/tools/checkstyle/checks/indentation/indentation/InputIndentationCustomAnnotation.java:86]: But yes, there is some problem...Corrected Now.
Done.

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/LineWrappingHandler.java (hunk 3 above)
Comment (romani) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/LineWrappingHandler.java:74]: please mention a reason in javadoc, to be more explicit

File: src/test/resources/com/puppycrawl/tools/checkstyle/checks/indentation/indentation/InputIndentationCustomAnnotation.java (hunk 2 above)
Comment (romani) [reply src/test/resources/com/puppycrawl/tools/checkstyle/checks/indentation/indentation/InputIndentationCustomAnnotation.java]: now it is much better.
```
        checkConfig.addAttribute("lineWrappingIndentation", "4");
        checkConfig.addAttribute("forceStrictCondition", "true");
```
so warn after update is good.

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/LineWrappingHandler.java (hunk 3 above)
Comment (Abhishek-kumar09) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/LineWrappingHandler.java]: done

File: src/it/resources/com/google/checkstyle/test/chapter4formatting/rule4841indentation/ClassWithChainedMethods.java (hunk 1 above)
Comment (romani) [reply src/it/resources/com/google/checkstyle/test/chapter4formatting/rule4841indentation/ClassWithChainedMethods.java:27]: please make comment `//indent:4 exp:8 warn`

we did not make it enforced to keep comment aligned with actual violation.
It is enforced in `it` folder, but not in `test` folder. It is one of future GSoC projects to make our UTs be more behavior focused and comments in Input actually define expected violation.

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/LineWrappingHandler.java (hunk 3 above)
Comment (romani) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/LineWrappingHandler.java]: please make javadoc links to such classes, wedo not have that much of them, it make sense to reference.

File: src/test/java/com/puppycrawl/tools/checkstyle/checks/indentation/IndentationCheckTest.java (hunk 4 above)
Comment (romani) [reply src/test/java/com/puppycrawl/tools/checkstyle/checks/indentation/IndentationCheckTest.java:797]: https://github.com/checkstyle/checkstyle/blob/432bafd49ed9d801f44a04ad710cc9372538e588/src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/NewHandler.java#L42-L47

> inside linewrapping it was only new

can you share exact line where it is defined ?

Comment (romani) [reply src/test/java/com/puppycrawl/tools/checkstyle/checks/indentation/IndentationCheckTest.java:797]: please help to remove this word from message in scope of https://github.com/checkstyle/checkstyle/issues/9113
it will simplify regression report review.
You can place update for message in this PR as separate commit so it will be easy to regenerate report.

Unfortunately Indentation Check is so complicated and so many variations of code could be so we rely of diff report too much, as  our test have only very basic set of inputs.
Current diff report is unmanageable, too much changes.

Comment (romani) [reply src/test/java/com/puppycrawl/tools/checkstyle/checks/indentation/IndentationCheckTest.java:797]: please help to remove this word from message in scope of https://github.com/checkstyle/checkstyle/issues/9113
it will simplify regression report review.
You can place update for message in this PR as separate commit so it will be easy to regenerate report.

Unfortunately Indentation Check is so complicated and so many variations of code could be so we rely of diff report too much, as  our test have only very basic set of inputs.
Current diff report is unmanageable, too much changes.

**Comment by romani** [comment]
@Abhishek-kumar09 , sorry for delay .... please review my comment above.

File: src/it/resources/com/google/checkstyle/test/chapter4formatting/rule4841indentation/ClassWithChainedMethods.java (hunk 1 above)
Comment (Abhishek-kumar09) [reply src/it/resources/com/google/checkstyle/test/chapter4formatting/rule4841indentation/ClassWithChainedMethods.java]: Corrected!, actually the checkConfig here is only `Indentation`, and I thought it is following the default indentation profile, and I checked it against cli on terminal and everything was fine.

But later on further debugging, founded that it was just another config with different properties and indentation attributes. 
Checked it only cli, and got the same result, then further found  that the problem was caused be chained method calls where the new is not the direct child of assign which was not covered in the current code logic.
Now Corrected!

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/LineWrappingHandler.java (hunk 3 above)
Comment (Abhishek-kumar09) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/LineWrappingHandler.java]: Done

File: src/test/java/com/puppycrawl/tools/checkstyle/checks/indentation/IndentationCheckTest.java (hunk 4 above)
Comment (Abhishek-kumar09) [reply src/test/java/com/puppycrawl/tools/checkstyle/checks/indentation/IndentationCheckTest.java:797]: Doing it, `operator new` to `new`
Generating the report at this point.

**Comment by Abhishek-kumar09** [comment]
Github, generate report

**Comment by Abhishek-kumar09** [comment]
Github, generate report

**Comment by Abhishek-kumar09** [comment]
Above two reports are with `forceStrictCondition` true.
Checkstyle report with default Indentation profile. (`forceStrictCOndition false`): 
https://abhishek-kumar09.github.io/checkstyleDiffReportTempContribition/

**Comment by Abhishek-kumar09** [comment]
Github, generate report

**Comment by nmancus1** [comment]
@Abhishek-kumar09 wercker is failing on `./.ci/wercker.sh no-error-pgjdbc`.

**Comment by Abhishek-kumar09** [comment]
image
Getting this error while running diff report generation on pgjdbc, any idea

**Comment by nmancus1** [comment]
>Getting this error while running diff report generation on pgjdbc, any idea

All project lives just have five pipes `|` even if they are empty.  Example:

`Vavr|git|https://github.com/vavr-io/vavr|v0.9.0||`

You don't have to run the diff report though, you can issue the command above and view the Checkstyle report.

**Comment by Abhishek-kumar09** [comment]
Github, rebase

File: src/test/java/com/puppycrawl/tools/checkstyle/checks/indentation/IndentationCheckTest.java (hunk 4 above)
Comment (Abhishek-kumar09) [reply src/test/java/com/puppycrawl/tools/checkstyle/checks/indentation/IndentationCheckTest.java]: Done

**Comment by romani** [comment]
@Abhishek-kumar09  , sorry for long delay in reply.
All you changes are good, at least it is good leap forward. 

please generate regression on more then one project, to let me validate regression.

**Comment by Abhishek-kumar09** [comment]
Github, generate report

**Comment by Abhishek-kumar09** [comment]
These are the earlier reports in one place to have a easy look: No major changes since then,
Diff report:
forceStrictCondition true.

   before the change: operator new to new: https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/new_to_del_2020202056/reports/diff/index.html
     
   after the change: operator new to new:
   https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/new_to_del_2020205544/reports/diff/index.html

 forceStrictCondition false.
 google style on guava:
 https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/new_to_del_2020084441/reports/diff/index.html

**Comment by Abhishek-kumar09** [comment]
Github, generate report

**Review by romani — APPROVED** [review]
Good enough, thanks a lot for your work.

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/NewHandler.java [hunk 5]
```diff
@@ -42,19 +42,20 @@
...
     public void checkIndentation() {
         // if new is on the line start and it is not the part of assignment.
-        if (isOnStartOfLine(mainAst)
-                && !isNewKeywordFollowedByAssign()) {
+        if (isOnStartOfLine(mainAst)) {
             final int columnNo = expandedTabsColumnNo(mainAst);
             final IndentLevel level = getIndentImpl();
 
-            if (columnNo < level.getFirstIndentLevel()) {
+            final boolean isForceStrictCond = getIndentCheck().isForceStrictCondition();
```
Comment (pbludov) [inline src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/NewHandler.java:56]: `isForceStrictCond` is a bad name for a variable. Why not `isForceStrictCondition` or `forceStrictCondition`?
If a line does not fit, you can add overload to `isAcceptable` method. Something like `IndentLevel.isAcceptable(int indent, boolean isForceStrictCondition)`. Then it will add a bit of readability.

File: src/test/java/com/puppycrawl/tools/checkstyle/checks/indentation/IndentationCheckTest.java [hunk 6]
```diff
@@ -1011,16 +1011,46 @@ public void testNewKeyword() throws Exception {
...
+        checkConfig.addAttribute("forceStrictCondition", "true");
+        checkConfig.addAttribute("lineWrappingIndentation", "8");
+        checkConfig.addAttribute("tabWidth", "4");
+        checkConfig.addAttribute("throwsIndent", "8");
+        final String[] expected = CommonUtil.EMPTY_STRING_ARRAY;
+        verifyWarns(checkConfig, getPath("InputIndentationNew.java"), expected);
+    }
+
+    @Test
+    public void testValidNewKeywordWithForceStrictCond() throws Exception {
```
Comment (pbludov) [inline src/test/java/com/puppycrawl/tools/checkstyle/checks/indentation/IndentationCheckTest.java:1027]: shortening again

File: src/test/java/com/puppycrawl/tools/checkstyle/checks/indentation/IndentationCheckTest.java [hunk 7]
```diff
@@ -1011,16 +1011,46 @@ public void testNewKeyword() throws Exception {
...
         checkConfig.addAttribute("lineWrappingIndentation", "8");
         checkConfig.addAttribute("tabWidth", "4");
         checkConfig.addAttribute("throwsIndent", "8");
         final String[] expected = CommonUtil.EMPTY_STRING_ARRAY;
-        verifyWarns(checkConfig, getPath("InputIndentationValidNewChildren.java"), expected);
+        verifyWarns(checkConfig, getPath("InputIndentationNew.java"), expected);
+    }
+
+    @Test
+    public void testInvalidNewKeywordWithForceStrictCond() throws Exception {
```
Comment (pbludov) [inline src/test/java/com/puppycrawl/tools/checkstyle/checks/indentation/IndentationCheckTest.java:1040]: shortening again

**Review by pbludov — CHANGES_REQUESTED** [review]
One minor please

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/NewHandler.java (hunk 5 above)
Comment (Abhishek-kumar09) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/NewHandler.java]: Done.

File: src/test/java/com/puppycrawl/tools/checkstyle/checks/indentation/IndentationCheckTest.java (hunk 6 above)
Comment (Abhishek-kumar09) [reply src/test/java/com/puppycrawl/tools/checkstyle/checks/indentation/IndentationCheckTest.java]: Done

File: src/test/java/com/puppycrawl/tools/checkstyle/checks/indentation/IndentationCheckTest.java (hunk 7 above)
Comment (Abhishek-kumar09) [reply src/test/java/com/puppycrawl/tools/checkstyle/checks/indentation/IndentationCheckTest.java]: Done

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/LambdaHandler.java [hunk 8]
```diff
@@ -124,8 +124,7 @@ public void checkIndentation() {
      */
     private boolean isNonAcceptableIndent(int astColumnNo, IndentLevel level) {
         return astColumnNo < level.getFirstIndentLevel()
-            || getIndentCheck().isForceStrictCondition()
-               && !level.isAcceptable(astColumnNo);
+            || !level.isAcceptable(astColumnNo, getIndentCheck().isForceStrictCondition());
```
Comment (Abhishek-kumar09) [inline src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/LambdaHandler.java:127]: Some code changes in Lambda handler, Will share a regression report to check everything is fine for lambda too, seperately.

Comment (Abhishek-kumar09) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/LambdaHandler.java:127]: Did regression report, and didn't find any changes.
forceStrictTrue: https://abhishek-kumar09.github.io/Issue3135/
forceStrict False: https://abhishek-kumar09.github.io/IndentaionReport/

Comment (romani) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/LambdaHandler.java:127]: now IDEA do not like this code - https://teamcity.jetbrains.com/viewLog.html?buildId=3266967&tab=Inspection&buildTypeId=Checkstyle_IdeaInspectionsPullRequest
```
src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation
IndentLevel.java (1)
94: isAcceptable() 'public' method isAcceptable() with 'boolean' parameter 
```

Comment (pbludov) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/LambdaHandler.java:127]: It is sad. @Abhishek-kumar09, Please undo the new method.

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/NewHandler.java (hunk 5 above)
Comment (romani) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/NewHandler.java]: Please undo new method

**Comment by strkkk** [comment]
@Abhishek-kumar09 there is a merge conflicts now, please take a look.
Please also squash commits

**Comment by Abhishek-kumar09** [comment]
It closes two issues #9071 #9113

**Comment by nmancus1** [comment]
@Abhishek-kumar09 wercker is failing on `./.ci/wercker.sh no-error-pgjdbc` with:

```
> Task :postgresql:checkstyleTest
[ant:checkstyle] [ERROR] /pipeline/source/.ci-temp/pgjdbc/pgjdbc/src/test/java/org/postgresql/test/jdbc2/optional/OptionalTestSuite.java:19:9: 'annotation array initialization' child has incorrect indentation level 8, expected level should be one of the following: 2, 4. [Indentation]
[ant:checkstyle] [ERROR] /pipeline/source/.ci-temp/pgjdbc/pgjdbc/src/test/java/org/postgresql/test/jdbc2/optional/OptionalTestSuite.java:20:9: 'annotation array initialization' child has incorrect indentation level 8, expected level should be one of the following: 2, 4. [Indentation]
[ant:checkstyle] [ERROR] /pipeline/source/.ci-temp/pgjdbc/pgjdbc/src/test/java/org/postgresql/test/jdbc2/optional/OptionalTestSuite.java:21:9: 'annotation array initialization' child has incorrect indentation level 8, expected level should be one of the following: 2, 4. [Indentation]
[ant:checkstyle] [ERROR] /pipeline/source/.ci-temp/pgjdbc/pgjdbc/src/test/java/org/postgresql/test/jdbc2/optional/OptionalTestSuite.java:22:9: 'annotation array initialization' child has incorrect indentation level 8, expected level should be one of the following: 2, 4. [Indentation]
[ant:checkstyle] [ERROR] /pipeline/source/.ci-temp/pgjdbc/pgjdbc/src/test/java/org/postgresql/test/jdbc2/optional/OptionalTestSuite.java:23:9: 'annotation array initialization' child has incorrect indentation level 8, expected level should be one of the following: 2, 4. [Indentation]
[ant:checkstyle] [ERROR] /pipeline/source/.ci-temp/pgjdbc/pgjdbc/src/test/java/org/postgresql/test/jdbc2/optional/OptionalTestSuite.java:24:9: 'annotation array initialization' child has incorrect indentation level 8, expected level should be one of the following: 2, 4. [Indentation]
[ant:checkstyle] [ERROR] /pipeline/source/.ci-temp/pgjdbc/pgjdbc/src/test/java/org/postgresql/test/jdbc2/optional/OptionalTestSuite.java:25:9: 'annotation array initialization' child has incorrect indentation level 8, expected level should be one of the following: 2, 4. [Indentation]

```

**Review by pbludov — APPROVED** [review]

**Comment by Abhishek-kumar09** [comment]
Github, rebase

**Comment by Abhishek-kumar09** [comment]
https://github.com/checkstyle/checkstyle/pull/9079#issuecomment-752046529
> You don't have to run the diff report though, you can issue the command above and receive this output:

@nmancus Would you please provide detailed command. It seems that I don't know the command and how to use it. Thanks.

**Comment by nmancus1** [comment]
`./.ci/wercker.sh no-error-pgjdbc`

**Comment by Abhishek-kumar09** [comment]
Github, rebase

**Comment by romani** [comment]
semaphore CI is relaunched.

**Comment by Abhishek-kumar09** [comment]
Github, generate report
