### PR TITLE
Issue #13680: Simplify requirement for what we consider a setter method in ClassAndPropertiesSettersJavadocScraper

### LINKED ISSUE #13680: Simplify requirement for what we consider a setter method in ClassAndPropertiesSettersJavadocScraper
Noticed at https://github.com/checkstyle/checkstyle/pull/13678#issuecomment-1702760681
```
[INFO] Running com.puppycrawl.tools.checkstyle.internal.XdocsPagesTest
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 1.181 s <<< FAILURE! -- in com.puppycrawl.tools.checkstyle.internal.XdocsPagesTest
[ERROR] com.puppycrawl.tools.checkstyle.internal.XdocsPagesTest -- Time elapsed: 1.181 s <<< ERROR!
java.lang.NullPointerException
```

The problem was noticed with MatchXpathCheck's `setQuery()`. The current implementation of `isSetterMethod()` returns `false` for that setter. In particular at:
```java
                // Maximum nodes allowed in a body of setter
                final int setterBodySize = 3;
                if (slist != null && slist.getChildCount() == setterBodySize) {
                    final DetailAST expr = slist.getFirstChild();
                    setterMethod = expr.getFirstChild().getType() == TokenTypes.ASSIGN;
                }
```

The `slist` has 4 children:
Screenshot from 2023-09-01 15-52-07

### PR DESCRIPTION
**Pull request by stoyanK7**
Resolves #13680 

---
- Simplifies `isSetterMethod()` to only check if the method name starts with `set`
- Ensures that we do not get `NullPointerException` if a Javadoc is missing but a better message

### CODE REVIEW

**Comment by stoyanK7** [comment]
Expected failure with a better error message:
https://dev.azure.com/romanivanovjr/romanivanovjr/_build/results?buildId=16311&view=logs&j=eb841e9f-6e1e-5c29-3ad5-74ec2c658069&t=a9b761e6-b8d5-50cf-467a-54967189cab2&l=1655
```
[ERROR]   XdocsPagesTest.generateXdocContent:309 » Parse Macro execution failed: MatchXpathCheck: Failed to find javadoc for property 'query'
```

**Comment by stoyanK7** [comment]
A successful job with simpler `isSetterMethod` implementation
https://dev.azure.com/romanivanovjr/romanivanovjr/_build/results?buildId=16312&view=logs&j=eb841e9f-6e1e-5c29-3ad5-74ec2c658069

File: src/main/java/com/puppycrawl/tools/checkstyle/site/SiteUtil.java [hunk 1]
```diff
@@ -452,9 +452,19 @@ public static Map<String, DetailNode> getPropertiesJavadocs(Set<String> properti
...
         final Map<String, DetailNode> javadocs = new LinkedHashMap<>(unmodifiableJavadocs);
-        properties.forEach(property -> {
+
+        for (String property : properties) {
             javadocs.putIfAbsent(property, SUPER_CLASS_PROPERTIES_JAVADOCS.get(property));
-        });
+
+            if (javadocs.get(property) == null
+                    && !TOKENS.equals(property)
+                    && !JAVADOC_TOKENS.equals(property)) {
```
Comment (nrmancuso) [inline src/main/java/com/puppycrawl/tools/checkstyle/site/SiteUtil.java:461]: Please extract logic to some descriptively named variable. `isMissingPropertyJavadoc`?

**Review by nrmancuso — CHANGES_REQUESTED** [review]
Minor item:

File: src/main/java/com/puppycrawl/tools/checkstyle/site/SiteUtil.java (hunk 1 above)
Comment (stoyanK7) [reply src/main/java/com/puppycrawl/tools/checkstyle/site/SiteUtil.java:461]: !isPropertyJavadocScraped  ?

Comment (nrmancuso) [reply src/main/java/com/puppycrawl/tools/checkstyle/site/SiteUtil.java:461]: On second thought,

>Failed to find javadoc for property 'query'

shouldn't this be `Failed to find setter javadoc for property 'query'`?

So `isPropertySetterJavadocFound`?

File: src/main/java/com/puppycrawl/tools/checkstyle/site/SiteUtil.java [hunk 2]
```diff
@@ -452,9 +452,20 @@ public static Map<String, DetailNode> getPropertiesJavadocs(Set<String> properti
...
                 ClassAndPropertiesSettersJavadocScraper.getJavadocsForModuleOrProperty();
         final Map<String, DetailNode> javadocs = new LinkedHashMap<>(unmodifiableJavadocs);
-        properties.forEach(property -> {
+
+        for (String property : properties) {
             javadocs.putIfAbsent(property, SUPER_CLASS_PROPERTIES_JAVADOCS.get(property));
-        });
+
+            final boolean isPropertySetterJavadocNotFound = javadocs.get(property) == null
+                        && !TOKENS.equals(property) && !JAVADOC_TOKENS.equals(property);
```
Comment (nrmancuso) [inline src/main/java/com/puppycrawl/tools/checkstyle/site/SiteUtil.java:460]: I will be surprised if something doesn't flag this, there should not be a negative in a boolean name.
```suggestion
            final boolean isPropertySetterJavadocFound = javadocs.get(property) != null
                       || TOKENS.equals(property) || JAVADOC_TOKENS.equals(property);
```

**Review by nrmancuso — CHANGES_REQUESTED** [review]
Item:

File: src/main/java/com/puppycrawl/tools/checkstyle/site/SiteUtil.java (hunk 2 above)
Comment (nrmancuso) [reply src/main/java/com/puppycrawl/tools/checkstyle/site/SiteUtil.java:460]: Either way: @stoyanK7, do you agree that proposed change is easier to understand and reason about?

Comment (nrmancuso) [reply src/main/java/com/puppycrawl/tools/checkstyle/site/SiteUtil.java:460]: Or, even better:
```suggestion
            final boolean isPropertySetterJavadocFound = javadocs.containsKey(property) 
            || TOKENS.equals(property) || JAVADOC_TOKENS.equals(property);
```

I didn't realize this was a map for a second, since we didn't have name like `valueForKey` :)

Comment (stoyanK7) [reply src/main/java/com/puppycrawl/tools/checkstyle/site/SiteUtil.java:460]: > Or, even better:

Sounds good. What about this additional check on the top?
```java
            if (!javadocs.containsKey(property)
                    && SUPER_CLASS_PROPERTIES_JAVADOCS.containsKey(property)) {
                javadocs.put(property, SUPER_CLASS_PROPERTIES_JAVADOCS.get(property));
            }

            final boolean isPropertySetterJavadocFound = javadocs.containsKey(property)
                       || TOKENS.equals(property) || JAVADOC_TOKENS.equals(property);
            if (!isPropertySetterJavadocFound) {
```

Without it `javadocs.containsKey(property) ` would still return `true` with the value being `null`

Comment (nrmancuso) [reply src/main/java/com/puppycrawl/tools/checkstyle/site/SiteUtil.java:460]: Ah yes, I like this, makes this somewhat hidden condition more obvious

File: src/main/java/com/puppycrawl/tools/checkstyle/site/SiteUtil.java (hunk 1 above)
Comment (stoyanK7) [reply src/main/java/com/puppycrawl/tools/checkstyle/site/SiteUtil.java]: Done.

File: src/main/java/com/puppycrawl/tools/checkstyle/site/SiteUtil.java (hunk 2 above)
Comment (stoyanK7) [reply src/main/java/com/puppycrawl/tools/checkstyle/site/SiteUtil.java]: Done.

**Comment by romani** [comment]
It is not our practice to accept just some code.
If you fix my problem with usage of property macros in Check please add it to your commit to prove what for you fo changes and it works after your changes.

We do not have tests for macroses but generated xdoc files controls implementation, so it is kind of test for them.

**Comment by stoyanK7** [comment]
Done. Added macro usage.

File: src/main/java/com/puppycrawl/tools/checkstyle/site/SiteUtil.java [hunk 3]
```diff
@@ -452,9 +452,24 @@ public static Map<String, DetailNode> getPropertiesJavadocs(Set<String> properti
...
-        properties.forEach(property -> {
-            javadocs.putIfAbsent(property, SUPER_CLASS_PROPERTIES_JAVADOCS.get(property));
-        });
+
+        for (String property : properties) {
+            final DetailNode superClassPropertyJavadoc = SUPER_CLASS_PROPERTIES_JAVADOCS
+                    .get(property);
+            if (superClassPropertyJavadoc != null) {
+                javadocs.putIfAbsent(property, superClassPropertyJavadoc);
+            }
```
Comment (romani) [inline src/main/java/com/puppycrawl/tools/checkstyle/site/SiteUtil.java:461]: why we do this put in a loop ? can we do it outside ones

**Review by romani — CHANGES_REQUESTED** [review]
item:

File: src/main/java/com/puppycrawl/tools/checkstyle/site/SiteUtil.java (hunk 3 above)
Comment (stoyanK7) [reply src/main/java/com/puppycrawl/tools/checkstyle/site/SiteUtil.java:461]: Like in a different method?

Comment (romani) [reply src/main/java/com/puppycrawl/tools/checkstyle/site/SiteUtil.java:461]: my bad, I misread a code

**Comment by stoyanK7** [comment]
Failing CI is due to 403 error: https://dev.azure.com/romanivanovjr/romanivanovjr/_build/results?buildId=16345&view=logs&j=6a833393-c551-5000-0916-5000fd3b86e7&t=bdbbd129-77f0-5d73-ce7d-db58d34c8358&l=21
```
BUILD_REASON:PullRequest
cmd: ./.ci/test-spelling-unknown-words.sh
Retrieve cached english.words from checkstyle.sourceforge.io
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  1757    0  1757    0     0   6514      0 --:--:-- --:--:-- --:--:--  6531
curl: (22) The requested URL returned error: 403

```

File: src/main/java/com/puppycrawl/tools/checkstyle/site/SiteUtil.java (hunk 3 above)
Comment (romani) [reply src/main/java/com/puppycrawl/tools/checkstyle/site/SiteUtil.java:461]: please make it code formatted like:
```
final DetailNode superClassPropertyJavadoc = 
   SUPER_CLASS_PROPERTIES_JAVADOCS.get(property);

```

**Review by nrmancuso — APPROVED** [review]

File: src/main/java/com/puppycrawl/tools/checkstyle/site/SiteUtil.java (hunk 3 above)
Comment (romani) [reply src/main/java/com/puppycrawl/tools/checkstyle/site/SiteUtil.java]: confusion happens while reading this code due to combining validation and data-enrichment in same loop.
please split into two loops:
```
properties.forEach(property -> {
            javadocs.putIfAbsent(property, SUPER_CLASS_PROPERTIES_JAVADOCS.get(property));
        });
```
and 
```
properties.forEach(property -> {
           .... validation isPropertySetterJavadocFound
        });
```

**Comment by romani** [comment]
https://checkstyle.sourceforge.io/version/6.18/ is not working, looks like https://checkstyle.sourceforge.io too.
this failure will not block us, we might need to consider to move known words to git repo due to high usage
