### PR TITLE
Issue #11031: Fixed false negative about concatenated strings in StringLiteralEqualityCheck

### LINKED ISSUE #11031: StringLiteralEquality FN about String literal expression
I have read check documentation: https://checkstyle.sourceforge.io/config_coding.html#StringLiteralEquality
I have downloaded the latest checkstyle from: https://checkstyle.org/cmdline.html#Download_and_Run
I have executed the cli and showed it below, as cli describes the problem better than 1,000 words

```bash
/var/tmp $ javac Test.java
/var/tmp $ cat config.xml
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
          "-//Checkstyle//DTD Checkstyle Configuration 1.3//EN"
          "https://checkstyle.org/dtds/configuration_1_3.dtd">

<module name="Checker">
  <property name="severity" value="error"/>
  <property name="fileExtensions" value="java, properties, xml"/>
  <module name="TreeWalker">    
    <module name="StringLiteralEquality"/>
  </module>
</module>

/var/tmp $ cat Test.java
class Test {
    public void foo() {
        String status = "pending";
        if (status == "do" + "ne") {} // violation
    }
}

/var/tmp $ RUN_LOCALE="-Duser.language=en -Duser.country=US"
/var/tmp $ java $RUN_LOCALE -jar checkstyle-X.XX-all.jar -c config.xml Test.java
Starting audit...
Audit done.
```

---

**Describe what you expect in detail.**

---
Hi, I found a false negative about the rule StringLiteralEquality. At line 4, it is obvious that right value is string literal, but no violation report. I think this is resulted by string literal expression. Thanks for your consideration.

### PR DESCRIPTION
**Pull request by Vyom-Yadav**
Resolves #11031: StringLiteralEquality FN about String literal expression
Diff Regression config: https://gist.githubusercontent.com/Vyom-Yadav/98dceb63a79f4833e85fff9b2e1464a6/raw/62103529e941c23abb7b23b61df366427b0fbf02/my_checks.xml
Final Report (clean): https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/8479596_2021003141/reports/diff/index.html

### CODE REVIEW

**Comment by Vyom-Yadav** [comment]
Github, generate report

**Review by romani — APPROVED** [review]
ok to merge

**Review by strkkk — CHANGES_REQUESTED** [review]
report shows a lot of false positives e.g.
https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/2c63ab3_2021181551/reports/diff/hibernate-orm/xref/home/runner/work/checkstyle/checkstyle/contribution/checkstyle-tester/repositories/hibernate-orm/hibernate-core/src/main/java/org/hibernate/cache/internal/StandardQueryCache.java.html#L275

https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/2c63ab3_2021181551/reports/diff/sevntu-checkstyle/xref/home/runner/work/checkstyle/checkstyle/contribution/checkstyle-tester/repositories/sevntu-checkstyle/sevntu-checks/src/test/resources/com/github/sevntu/checkstyle/checks/coding/InputTernaryPerExpressionCountCheck.java.html#L58
and others.

they are all with ternary operator. Please fix it and extend test inputs

**Comment by Vyom-Yadav** [comment]
@strkkk All those cases revolve around checking whether a String is null or not. `==null` is a better way to check for nullity than using `equals()`. The check behavior (without this concatenation patch) gives an error for-
```
if("asd" == null) { // violation
} 
```
```
Starting audit...
[ERROR] /TestP/Test.java:1:10: Literal Strings should be compared using equals(), not '=='. [StringLiteralEquality]
Audit done.
Checkstyle ends with 1 errors.                      
```
Though the condition `"asd" == null` is always `false`, this check is not about evaluating boolean conditions so all cases involving `null` should be suppressed. Though this issue is found in the diff report of this patch, it is not a part of the original issue and a new issue should be made regarding this, that issue should be resolved first, and then work should be continued in this PR.

**Comment by romani** [comment]
>Starting audit...

Please place what version of checkstyle you use, share whole command.

**Comment by Vyom-Yadav** [comment]
@romani Updated

**Comment by strkkk** [comment]
@Vyom-Yadav you are right, these are not false positives but buggy code. Anyway, test inputs should have this examples.

I am not sure if it is ok to have this violations (null checks for literals) in this check. I think it is better to have a new one.
@romani what do you think? to detect cases like 
```
gripe += (((" -- " + e.getMessage()) != null) ? e.getMessage() : " [no message in exception]");
```
because now we report that it should compare strings with `equals`, but in reality it is just a bug and null check should be removed.

**Comment by romani** [comment]
it is NOT bug in Check, separate issue, we can use "equals" here, it might be not ideal advice but user can.
image

BUT it is very useful side effect of Check, as it finding weird/wrong code :).

But I agree lets have this case in our Inputs.

**Comment by Vyom-Yadav** [comment]
@romani @strkkk Added required test cases.

**Comment by romani** [comment]
Github, generate report

**Review by romani — APPROVED** [review]
ok to merge as only test is updated from my last review.

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/StringLiteralEqualityCheck.java [hunk 1]
```diff
@@ -112,12 +112,35 @@
...
+    /**
+     * Checks whether string literal or text block literals are concatenated.
+     *
+     * @param ast ast
+     * @return {@code true} if string literal or text block literals are concatenated
+     */
+    private static boolean areStringsConcatenated(DetailAST ast) {
+        DetailAST plusAst = ast.findFirstToken(TokenTypes.PLUS);
+        boolean result = false;
+        while (plusAst != null) {
```
Comment (strkkk) [inline src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/StringLiteralEqualityCheck.java:133]: I think there is no need to check all nested plus tokens. you can check only top level token. In case any of its operands is string, type of other operand is irrelevant, string concatenation always results in string type. 
Therefore nested plus signs checks can be removed. What do you think?

Comment (Vyom-Yadav) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/StringLiteralEqualityCheck.java:133]: Initially, I also thought the same but doing so will miss cases like-
```
String s = "a";
String p = "b";
if (s != s + "p" + p) { // violation
}
```
Relevant AST-
```
|--EXPR -> EXPR
    `--NOT_EQUAL -> !=
        |--IDENT -> s
        `--PLUS -> +
            |--PLUS -> +
            |   |--IDENT -> s
            |   `--STRING_LITERAL -> "p"
            `--IDENT -> p
```
As top-level `PLUS` does not contain any `STRING_LITERAL`

Comment (strkkk) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/StringLiteralEqualityCheck.java:133]: is there a violation now?
I see test input
```
if ((s += "asd") != s + "p" + p) { // violation
```
but it is not 100% clear what violation is produced by second part of expression, but not first one.
Can you please add your example to make it 100% clear?

Comment (Vyom-Yadav) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/StringLiteralEqualityCheck.java:133]: > is there a violation now? I see test input
> 
> ```
> if ((s += "asd") != s + "p" + p) { // violation
> ```
> 
> but it is not 100% clear what violation is produced by second part of expression, but not first one. Can you please add your example to make it 100% clear?

The violation is being produced by the second part i.e. `s + "p" + p` but yes the test case is not clear, added the one I mentioned above.

**Review by strkkk — APPROVED** [review]

**Comment by pbludov** [comment]
Interesting that there is no false positives in the report.

```java
"str" + foo == null ? "null" : foo
```
is actually
```java
("str" + foo) == null ? "null" : foo
```

This one is just insane:
https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/8479596_2021003141/reports/diff/apache-struts/xref/home/runner/work/checkstyle/checkstyle/contribution/checkstyle-tester/repositories/apache-struts/core/src/main/java/com/opensymphony/xwork2/DefaultActionInvocation.java.html#L317

**Review by pbludov — APPROVED** [review]

**Comment by Vyom-Yadav** [comment]
@pbludov Can you assign the next reviewer?
