### PR TITLE
Issue #10208: Javadoc parser/grammar doesn't report the correct lines…

### LINKED ISSUE #10208: Javadoc parser/grammar doesn't report the correct lines in Javadoc AST.
Identified at https://github.com/checkstyle-antlr4/checkstyle-antlr4/issues/15, ANTLR doesn't support the `\r` (pre-OSX macos) line ending any longer, and has no plans to add support. Therefore, when parsing a Javadoc in a file that uses the `\r` line ending, the line number never increases in the Javadoc:

```java

public  class Test {
    /**
     * This is a javadoc comment.
     * More info, on another line.
     */
    void doStuff() {

    }
}


```

Unix utilities do not play well with `\r`, which renders as `^M` with `cat`:

```bash

➜  src cat -v Test.java 
public  class Test {^M    /**^M     * This is a javadoc comment.^M     * More info, on another line.^M     */^M    void doStuff() {^M^M    }^M}^M%

➜  src java -jar checkstyle-8.44-all.jar -J Test.java
CLASS_DEF -> CLASS_DEF [1:0]
|--MODIFIERS -> MODIFIERS [1:0]
|   `--LITERAL_PUBLIC -> public [1:0]
|--LITERAL_CLASS -> class [1:8]
|--IDENT -> Test [1:14]
`--OBJBLOCK -> OBJBLOCK [1:19]
    |--LCURLY -> { [1:19]
    |--METHOD_DEF -> METHOD_DEF [6:4]
    |   |--MODIFIERS -> MODIFIERS [6:4]
    |   |--TYPE -> TYPE [6:4]
    |   |   |--BLOCK_COMMENT_BEGIN -> /* [2:4]
    |   |   |   |--COMMENT_CONTENT -> *\r     * This is a javadoc comment.\r     * More info, on another line.\r      [2:6]
    |   |   |   |   `--JAVADOC -> JAVADOC [2:7] // ok
    |   |   |   |       |--NEWLINE -> \r [2:7] // ok
    |   |   |   |       |--LEADING_ASTERISK ->      * [2:8] // wrong, should be 3
    |   |   |   |       |--TEXT ->  This is a javadoc comment. [2:14] // wrong, should be 3
    |   |   |   |       |--NEWLINE -> \r [2:41] // wrong, should be 3
    |   |   |   |       |--LEADING_ASTERISK ->      * [2:42]  // wrong, should be 4
    |   |   |   |       |--TEXT ->  More info, on another line. [2:48]  // wrong, should be 4
    |   |   |   |       |--NEWLINE -> \r [2:76]  // wrong, should be 4
    |   |   |   |       |--TEXT ->       [2:77] // wrong, should be 5
    |   |   |   |       `--EOF -> <EOF> [2:82] // wrong, should be 5
    |   |   |   `--BLOCK_COMMENT_END -> */ [5:5]
    |   |   `--LITERAL_VOID -> void [6:4]
    |   |--IDENT -> doStuff [6:9]
    |   |--LPAREN -> ( [6:16]
    |   |--PARAMETERS -> PARAMETERS [6:17]
    |   |--RPAREN -> ) [6:17]
    |   `--SLIST -> { [6:19]
    |       `--RCURLY -> } [8:4]
    `--RCURLY -> } [9:0]

```

As you can see, the Javadoc starts on line 2, but then the line number never advances within that Javadoc AST. This is because the `consume()` function in ANTLR's interpreter doesn't recognize the `\r` alone as a line ending any longer (it only looks for `\n`, which covers the other two line endings). We should be able to handle any line ending that Java supports, which is `\r`, `\n`, and `\r\n`. 

I would expect the Javadoc AST to track line numbers correctly. Similar issue was originally reported at https://github.com/checkstyle/checkstyle/issues/2329, and problem was also noted at https://github.com/checkstyle/checkstyle/issues/2329#issuecomment-311235254.

### PR DESCRIPTION
**Pull request by nmancus1**
Closes #10208.

The solution for this problem is to simply override the `consume()` method by extending ANTLR's `LexerATNSimulator` class. 

Coverage was failing on windows CI: https://cirrus-ci.com/task/4889423054635008?logs=verify_without_checkstyle#L1115 .
See https://github.com/checkstyle/checkstyle/pull/10216/files#r661525006

--------------------
Diff Regression projects: https://gist.githubusercontent.com/nmancus1/e1b889f51f6af5006490bbb090ee2aa9/raw/269ea9929caddf3234107c4bb0f7e9f43ea487a1/javadoc-projects.properties

Diff Regression config: https://gist.githubusercontent.com/nmancus1/d64e87c8b48a549790e39d1d67a9fc77/raw/dbf57d82765fe330bed0eecde62b134b2163e34d/config.xml

### Javadoc Check Regression Report

https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/c310d75_2021143728/reports/diff/index.html

Report is clean.

### CODE REVIEW

File: src/main/java/com/puppycrawl/tools/checkstyle/grammar/CrAwareLexerSimulator.java [hunk 1]
```diff
@@ -0,0 +1,77 @@
...
+            line++;
+            charPositionInLine = 0;
+        }
+        else if (currentChar == '\r') {
+            final int nextChar = input.LA(2);
+            if (nextChar != '\n') {
+                line++;
+                charPositionInLine = 0;
+            }
+        }
```
Comment (nmancus1) [inline src/main/java/com/puppycrawl/tools/checkstyle/grammar/CrAwareLexerSimulator.java:71]: The fix is here; we just needed to check for lone '\r' line endings while consuming input from the character stream.

File: src/main/resources/com/puppycrawl/tools/checkstyle/grammar/javadoc/JavadocLexer.g4 [hunk 2]
```diff
@@ -65,6 +67,16 @@ import java.util.*;
...
+      /**
+       * We need to create a different constructor in order to use our
+       * own implementation of the LexerATNSimulator. This is the
+       * reason for the unused 'crAwareConstructor' argument.
+       */
+      public JavadocLexer(CharStream input, boolean crAwareConstructor) {
+        super(input);
+        _interp = new CrAwareLexerSimulator(this, _ATN, _decisionToDFA, _sharedContextCache);
+      }
+
```
Comment (nmancus1) [inline src/main/resources/com/puppycrawl/tools/checkstyle/grammar/javadoc/JavadocLexer.g4:79]: We have to make a new constructor since ANTLR no longer supports the creation of abstract Lexers/ Parsers.

File: src/test/resources/com/puppycrawl/tools/checkstyle/grammar/javadoc/InputDosLineEndingAsNewlineMultiline.javadoc [hunk 3]
```diff
@@ -0,0 +1,7 @@
+* line 0
+* Checks that commentContent starts with '*' javadoc comment identifier.
+    *&lt;property name="ignorePattern" value="^ *\* *[^ ]+$"/&gt*
+* This * is not a leading *
+* @return true if commentContent starts with '*' javadoc comment identifier
+* line 5
+    * line 6
```
Comment (nmancus1) [inline src/test/resources/com/puppycrawl/tools/checkstyle/grammar/javadoc/InputDosLineEndingAsNewlineMultiline.javadoc:7]: Needed this for test coverage.

File: src/test/resources/com/puppycrawl/tools/checkstyle/grammar/javadoc/expectedJavadocWithCrAsNewlineAst.txt [hunk 4]
```diff
@@ -1,20 +1,20 @@
...
+|--NEWLINE -> \r [3:28]
+|--LEADING_ASTERISK -> * [4:0]
+|--WS ->   [4:1]
+|--JAVADOC_TAG -> JAVADOC_TAG [4:2]
+|   |--RETURN_LITERAL -> @return [4:2]
+|   |--WS ->   [4:9]
+|   `--DESCRIPTION -> DESCRIPTION [4:10]
+|       |--TEXT -> true if commentContent starts with '*' javadoc comment identifier [4:10]
+|       `--NEWLINE -> \r [4:75]
+`--EOF -> <EOF> [5:0]
```
Comment (nmancus1) [inline src/test/resources/com/puppycrawl/tools/checkstyle/grammar/javadoc/expectedJavadocWithCrAsNewlineAst.txt:20]: This was the test from https://github.com/checkstyle/checkstyle/issues/2329, but now it shows the correct line numbers.

**Comment by nmancus1** [comment]
Github, generate report

File: .ci/jsoref-spellchecker/whitelist.words [hunk 5]
```diff
@@ -72,6 +72,7 @@ ATest
 atid
 ation
 atlassian
+atn
```
Comment (nmancus1) [inline .ci/jsoref-spellchecker/whitelist.words:75]: We are going to need to add these for the upgrade to ATNLR4 anyway, I don't think we will be able to get around it.

File: src/test/java/com/puppycrawl/tools/checkstyle/grammar/CrAwareLexerTest.java [hunk 6]
```diff
@@ -0,0 +1,83 @@
...
+
+package com.puppycrawl.tools.checkstyle.grammar;
+
+import static com.google.common.truth.Truth.assertWithMessage;
+
+import org.antlr.v4.runtime.CharStream;
+import org.antlr.v4.runtime.CharStreams;
+import org.junit.jupiter.api.Test;
+
+public class CrAwareLexerTest {
```
Comment (nmancus1) [inline src/test/java/com/puppycrawl/tools/checkstyle/grammar/CrAwareLexerTest.java:28]: I was forced to add these fake tests because windows CI will fail otherwise.

File: config/suppressions.xml [hunk 7]
```diff
@@ -649,4 +649,8 @@
   <suppress id="ImportControlTest"
             files="[\\/]src[\\/]test[\\/]java[\\/]com[\\/]puppycrawl[\\/]tools[\\/]checkstyle[\\/]xpath[\\/]XpathQueryGeneratorTest.java"/>
 
+  <!-- This file requires disallowed imports from 'org.antlr.v4.runtime' -->
+  <suppress id="ImportControlMain"
+            files="[\\/]src[\\/]main[\\/]java[\\/]com[\\/]puppycrawl[\\/]tools[\\/]checkstyle[\\/]grammar[\\/]CrAwareLexerSimulator.java"/>
```
Comment (rnveach) [inline config/suppressions.xml:654]: Why not set the package to allow this?

File: src/test/resources/com/puppycrawl/tools/checkstyle/grammar/javadoc/InputCrAsNewlineMultiline.javadoc [hunk 8]
```diff
@@ -0,0 +1 @@
+* line 0* Checks that commentContent starts with '*' javadoc comment identifier.    *&lt;property name="ignorePattern" value="^ *\* *[^ ]+$"/&gt** This * is not a leading ** @return true if commentContent starts with '*' javadoc comment identifier* line 5    * line 6
```
Comment (rnveach) [inline src/test/resources/com/puppycrawl/tools/checkstyle/grammar/javadoc/InputCrAsNewlineMultiline.javadoc:1]: Doesn't this file need to be added to the git attributes? Are you sure it didn't change the line endings?

**Review by rnveach — COMMENTED** [review]
I am assuming you'll be using this new class in your new Java grammar as well?

File: src/test/resources/com/puppycrawl/tools/checkstyle/grammar/javadoc/InputCrAsNewlineMultiline.javadoc (hunk 8 above)
Comment (nmancus1) [reply src/test/resources/com/puppycrawl/tools/checkstyle/grammar/javadoc/InputCrAsNewlineMultiline.javadoc:1]: I think that you only need to set git attributes for windows line endings. git did not complain when I committed the file as it normally would with windows line endings. On fresh checkout:

```bash

➜  checkstyle git:(issue-10208) cat /home/nick/IdeaProjects/checkstyle/src/test/resources/com/puppycrawl/tools/checkstyle/grammar/javadoc/InputCrAsNewlineMultiline.javadoc
➜  checkstyle git:(issue-10208) cat -v /home/nick/IdeaProjects/checkstyle/src/test/resources/com/puppycrawl/tools/checkstyle/grammar/javadoc/InputCrAsNewlineMultiline.javadoc
* line 0^M* Checks that commentContent starts with '*' javadoc comment identifier.^M    *&lt;property name="ignorePattern" value="^ *\* *[^ ]+$"/&gt*^M* This * is not a leading *^M* @return true if commentContent starts with '*' javadoc comment identifier^M* line 5^M    * line 6^M%           

```

File: src/test/resources/com/puppycrawl/tools/checkstyle/grammar/javadoc/InputDosLineEndingAsNewlineMultiline.javadoc (hunk 3 above)
Comment (nmancus1) [reply src/test/resources/com/puppycrawl/tools/checkstyle/grammar/javadoc/InputDosLineEndingAsNewlineMultiline.javadoc:7]: @rnveach I need to add this one to git attributes, though, thanks for bringing this up.

File: config/suppressions.xml (hunk 7 above)
Comment (nmancus1) [reply config/suppressions.xml:654]: Good idea, done.

File: src/test/resources/com/puppycrawl/tools/checkstyle/grammar/javadoc/InputCrAsNewlineMultiline.javadoc (hunk 8 above)
Comment (nmancus1) [reply src/test/resources/com/puppycrawl/tools/checkstyle/grammar/javadoc/InputCrAsNewlineMultiline.javadoc:1]: Added both for good measure.

**Review by pbludov — APPROVED** [review]

**Review by rnveach — APPROVED** [review]
