### PR TITLE
Issue #3132: fixed not checked split line new array

### LINKED ISSUE #3132: Indentation: split line new array not checked
```
$ cat TestClass.java
public class TestClass //indent:0 exp:0
{ //indent:0 exp:0
    int[][] array10b //indent:4 exp:4
= new int[][] { //indent:0 // line 4
                new int[] { 1, 2, 3}, //indent:18
                new int[] { 1, 2, 3}, //indent:18
    }; //indent:4
} //indent:0 exp:0


$ cat TestConfig.xml
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
          "-//Puppy Crawl//DTD Check Configuration 1.3//EN"
          "http://www.puppycrawl.com/dtds/configuration_1_3.dtd">

<module name="Checker">
    <property name="charset" value="UTF-8"/>

    <module name="TreeWalker">
<property name="tabWidth" value="4"/>

    <module name="Indentation">
      <property name="arrayInitIndent" value="4"/>
      <property name="basicOffset" value="4"/>
      <property name="braceAdjustment" value="0"/>
      <property name="lineWrappingIndentation" value="4"/>
    </module>
    </module>
</module>

$ java -jar checkstyle-6.17-all.jar -c TestConfig.xml TestClass.java
Starting audit...
Audit done.
```

I was expecting some type of violation on line 4, like requiring it to be at column 4 or 8, as it doesn't fit at column 0.
##

### PR DESCRIPTION
**Pull request by plan3d**
Resolves #3132

Indent-strict: https://gist.githubusercontent.com/romani/82a313d3a8de5becbf7fb54767d434ef/raw/b297c3de497f6f63458ef2e198fab2f879e25f2b/pull-9758.xml

Diff Regression config: https://gist.githubusercontent.com/romani/82a313d3a8de5becbf7fb54767d434ef/raw/de70b01eb659ee0513387b003a1968ada966ece6/pull-9758-indent2.xml

Diff Regression projects: https://gist.githubusercontent.com/romani/db8ebee721f2a387e1d4b81a55f2d5f1/raw/8e4a96fdad2654d55808851ae59553b58f5e782f/pull-9758-only-guava.properties

only jdk: https://gist.githubusercontent.com/romani/c539071f4b33eb8e2f451c14a0d4480b/raw/b6e9c3c275d0a941e7c10f558ba52c2e4f55a58f/pull-9758.properties

projects old: https://gist.githubusercontent.com/suniti0804/1d7bd7fbc50bf6c93896fbe2bbbf2c4a/raw/f71611ef97d0737b6d8bb1c1253cab18b9342429/projects-to-test-on-for-github-action.properties

unactive Diff-Regression-projects: https://gist.githubusercontent.com/plan3d/ca91d8262d18c4c84f6b62fa1cb4bebc/raw/55f3df0043861c1c5c0eaf2ee7868b2b211d8771/projects-to-test-on.properties

### CODE REVIEW

**Comment by plan3d** [comment]
Github, generate report

**Comment by Abhishek-kumar09** [comment]
@plan3d Generate report with `forceStrictCondition` = true

**Comment by plan3d** [comment]
Github, generate report

**Comment by plan3d** [comment]
Github, generate report

**Comment by plan3d** [comment]
Github, generate report

**Comment by plan3d** [comment]
Github, generate report

**Comment by Abhishek-kumar09** [comment]
Please make a diff report with StrictCondition false

**Comment by plan3d** [comment]
> https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/5512a35_2021063713/reports/diff/index.html

See first report :-)

**Comment by Abhishek-kumar09** [comment]
@pbludov @strkkk  https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/5512a35_2021063713/reports/diff/checkstyle/index.html#A2

Is this be eligible for the clean code practice or it is important to enforce the linewrapping indentation here? Just confused.

**Comment by strkkk** [comment]
To be honest, I do not have an idea is correct indentation in such weird case.
I would say that we can leave it as it is now and fix it if someone will complain about it (which is unlikely imo)

**Comment by Abhishek-kumar09** [comment]
What I would suggest in this case that instead of having the indent as `parent+lineWrapping` we can use parent indent only without lineWrapping.

In that case the issue underlying would also solve, and there will be no much difference for `forceStrictCondition` false.

SO the check should not allow any indent lesser than their parent indent.

so: 
```java
	int a
	[]; // is valid

	int a
[]; // not valid

	int a
		[]; // valid
```

**Review by pbludov — APPROVED** [review]

**Review by strkkk — APPROVED** [review]

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/MemberDefHandler.java [hunk 1]
```diff
@@ -51,13 +53,38 @@ public void checkIndentation() {
             checkType();
         }
         final DetailAST firstNode = getMainAst();
-        final DetailAST lastNode = getVarDefStatementSemicolon(firstNode);
+        DetailAST lastNode = getVarDefStatementSemicolon(firstNode);
 
-        if (lastNode != null && !isArrayDeclaration(firstNode)) {
+        if (lastNode != null) {
+            lastNode = getArrayInitNode(firstNode).orElse(lastNode);
```
Comment (rnveach) [inline src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/MemberDefHandler.java:59]: Seems very weird we get `getVarDefStatementSemicolon` first and then if it has a value, throw it away if `getArrayInitNode` provides us with a better result.

Why aren't we looking at `getArrayInitNode` first and then rely on `getVarDefStatementSemicolon` if the first is null?

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/MemberDefHandler.java [hunk 2]
```diff
@@ -51,13 +53,38 @@ public void checkIndentation() {
...
+     * @param firstNode Node to begin searching
+     * @return array init node
+     */
+    private static Optional<DetailAST> getArrayInitNode(DetailAST firstNode) {
+        Optional<DetailAST> result = Optional.empty();
+        final DetailAST assign = firstNode.findFirstToken(TokenTypes.ASSIGN);
+        if (assign != null) {
+            final DetailAST expr = assign.findFirstToken(TokenTypes.EXPR);
+            if (expr == null) {
+                result = Optional.ofNullable(assign.findFirstToken(TokenTypes.ARRAY_INIT));
```
Comment (rnveach) [inline src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/MemberDefHandler.java:76]: I am not very good with Optionals but there are alot of `null` checks in this method which is what optionals is to prevent.

This whole method cant be converted into 1 big optional that doesn't make things complex?

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/MemberDefHandler.java [hunk 3]
```diff
@@ -51,13 +53,38 @@ public void checkIndentation() {
...
         }
     }
 
+    /**
+     * Finds the array init node.
+     *
+     * @param firstNode Node to begin searching
+     * @return array init node
+     */
+    private static Optional<DetailAST> getArrayInitNode(DetailAST firstNode) {
```
Comment (rnveach) [inline src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/MemberDefHandler.java:70]: I noticed nothing is checking lines and what starts the line, etc...

Shouldn't there be some check to first identify if `=` starts the line or not?
Why do we need to look at the `expr` and `array_init` if `=` is starting the line?

**Comment by plan3d** [comment]
@rnveach Thank you for your review! I will implement your suggestions and provide a new version

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/MemberDefHandler.java (hunk 3 above)
Comment (plan3d) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/MemberDefHandler.java:70]: The problem was that the line starting with `=` was skipped because `lastNode != null && !isArrayDeclaration(firstNode)` was false. With my changes `checkWrappingIndentation` is called and checks line wraps.

File: src/test/resources/com/puppycrawl/tools/checkstyle/checks/indentation/indentation/InputIndentationNewHandler.java [hunk 4]
```diff
@@ -20,4 +20,11 @@ public void test() { //indent:4 exp:4
         } catch (Exception e) { //indent:8 exp:8
         } //indent:8 exp:8
     } //indent:4 exp:4
+
+    int[][] array10b //indent:4 exp:4
+= new int[][] { //indent:0 exp:8 warn
```
Comment (romani) [inline src/test/resources/com/puppycrawl/tools/checkstyle/checks/indentation/indentation/InputIndentationNewHandler.java:25]: it is very good to use case from issue.

but please use values from regression report like:
https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/b8cb762_2021143007/reports/diff/android-launcher/index.html#A1
https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/b8cb762_2021143007/reports/diff/android-launcher/index.html#A2
https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/b8cb762_2021143007/reports/diff/apache-ant/index.html#A1

we should not reply on diff report to catch specific type of code structure.
We should see same diff in UT validation, diff report will same as UT but with huge amount of violations of the same type.

**Review by romani — CHANGES_REQUESTED** [review]
items:

File: src/test/resources/com/puppycrawl/tools/checkstyle/checks/indentation/indentation/InputIndentationNewHandler.java (hunk 4 above)
Comment (plan3d) [reply src/test/resources/com/puppycrawl/tools/checkstyle/checks/indentation/indentation/InputIndentationNewHandler.java:25]: Thank you for your review! I added more code to the test resources. I also added method `additionalOffsets` to `LineWrappingHandler` to accept https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/b8cb762_2021143007/reports/diff/apache-ant/index.html#A1 which is in my opinion correctly indented.

**Comment by plan3d** [comment]
Github, generate report

**Comment by plan3d** [comment]
Github, generate report

File: src/test/resources/com/puppycrawl/tools/checkstyle/checks/indentation/indentation/InputIndentationNewHandler.java (hunk 4 above)
Comment (romani) [reply src/test/resources/com/puppycrawl/tools/checkstyle/checks/indentation/indentation/InputIndentationNewHandler.java:25]: to make it valid (no violation) forceStrictCondition should FALSE.

with forceStrictCondition is TRUE - there should be violation.

**Comment by romani** [comment]
@plan3d , please rebase and resolve conflict to be ready for merge.

File: src/test/resources/com/puppycrawl/tools/checkstyle/checks/indentation/indentation/InputIndentationNewWithForceStrictCondition.java [hunk 5]
```diff
@@ -17,11 +17,50 @@
...
+
+	void test() throws IOException  { //indent:4 exp:4
         BufferedReader bf =  //indent:8 exp:8
                 new BufferedReader(  //indent:16 exp:16
                 new InputStreamReader(System.in) {  //indent:16 exp:24 warn
                     int a = 0; //indent:20 exp:28,32,36 warn
                 }); //indent:16 exp:24,28,32 warn
+
+        String[] tmp1 = new String[42 //indent:8 exp:8
+                                   + bf.toString().length()]; //indent:35 exp:16,35
```
Comment (romani) [inline src/test/resources/com/puppycrawl/tools/checkstyle/checks/indentation/indentation/InputIndentationNewWithForceStrictCondition.java:37]: it should be violation 
because `checkConfig.addAttribute("forceStrictCondition", "true");` for this Input

**Review by romani — CHANGES_REQUESTED** [review]
items:

File: src/test/resources/com/puppycrawl/tools/checkstyle/checks/indentation/indentation/InputIndentationNewWithForceStrictCondition.java (hunk 5 above)
Comment (plan3d) [reply src/test/resources/com/puppycrawl/tools/checkstyle/checks/indentation/indentation/InputIndentationNewWithForceStrictCondition.java:37]: In my opinion 35 is also a valid indentation. From https://www.oracle.com/java/technologies/javase/codeconventions-indentation.html in "4.2 Wrapping Lines", fourth point: "Align the new line with the beginning of the expression at the same level on the previous line." In this case the expression begins at position 35 after the `[`.
@romani If you prefer 16 to be the only valid value I can change my code :-)

Comment (romani) [reply src/test/resources/com/puppycrawl/tools/checkstyle/checks/indentation/indentation/InputIndentationNewWithForceStrictCondition.java:37]: We have Check implementation that can satisfy multiple style guides, you reference sun style (one of many style guides). For this style config should be `checkConfig.addAttribute("forceStrictCondition", "false");`.

But in this particular Test/input we have `checkConfig.addAttribute("forceStrictCondition", "true");` so it mean indentation should be strictly at required position.
You can create another Input+test methods where  `checkConfig.addAttribute("forceStrictCondition", "false");` and this code will be without violation.
https://checkstyle.org/config_misc.html#Indentation

**Review by romani — CHANGES_REQUESTED** [review]
comment https://github.com/checkstyle/checkstyle/pull/9758/files#r657134812 should be addressed.

@plan3d , please find time to finish PR.

**Comment by plan3d** [comment]
Sorry for the delay, last weeks I had a lot of things to do. I hope to finish the PR during next week.

File: src/test/resources/com/puppycrawl/tools/checkstyle/checks/indentation/indentation/InputIndentationNewWithForceStrictCondition.java (hunk 5 above)
Comment (romani) [reply src/test/resources/com/puppycrawl/tools/checkstyle/checks/indentation/indentation/InputIndentationNewWithForceStrictCondition.java:37]: I still do not see violation on this line

thee should be "wan" trailing comment and update in UT method in expected array

**Comment by romani** [comment]
@plan3d , still not done, please recheck that you pushed your latest code.

**Comment by romani** [comment]
@plan3d , gentle reminder  to finish PR.

**Comment by plan3d** [comment]
Sorry again for the delay, I rebased the branch and removed method `additionalOffsets`. Please review!

**Comment by romani** [comment]
@plan3d , please rebase to latest code
Please address review item https://github.com/checkstyle/checkstyle/pull/9758#discussion_r680574270

File: src/test/resources/com/puppycrawl/tools/checkstyle/checks/indentation/indentation/InputIndentationNewWithForceStrictCondition.java (hunk 5 above)
Comment (plan3d) [reply src/test/resources/com/puppycrawl/tools/checkstyle/checks/indentation/indentation/InputIndentationNewWithForceStrictCondition.java]: Line 37 is now treated as violation

**Comment by plan3d** [comment]
@romani branch was rebased on current master branch and review item is done

**Comment by romani** [comment]
Github, generate report

File: src/test/resources/com/puppycrawl/tools/checkstyle/checks/indentation/indentation/InputIndentationNewWithForceStrictCondition.java [hunk 6]
```diff
@@ -17,11 +17,50 @@
...
+
+	void test() throws IOException  { //indent:4 exp:4
         BufferedReader bf =  //indent:8 exp:8
                 new BufferedReader(  //indent:16 exp:16
                 new InputStreamReader(System.in) {  //indent:16 exp:24 warn
                     int a = 0; //indent:20 exp:28,32,36 warn
                 }); //indent:16 exp:24,28,32 warn
+
+        String[] tmp1 = new String[42 //indent:8 exp:8
+                                   + bf.toString().length()]; //indent:35 exp:16 warn
```
Comment (romani) [inline src/test/resources/com/puppycrawl/tools/checkstyle/checks/indentation/indentation/InputIndentationNewWithForceStrictCondition.java:37]: please add to each statement/block with "warn", same by content but without warn.
To show  that here is code with correct indentation (no warn) and here is "same"  code but with violation.

File: src/test/resources/com/puppycrawl/tools/checkstyle/checks/indentation/indentation/InputIndentationNewHandler.java (hunk 4 above)
Comment (romani) [reply src/test/resources/com/puppycrawl/tools/checkstyle/checks/indentation/indentation/InputIndentationNewHandler.java:25]: I do not see in Inputs case like 
https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/b8cb762_2021143007/reports/diff/android-launcher/index.html#A2

please add.

**Review by romani — CHANGES_REQUESTED** [review]
see old review item far in past, and reply done to it, i still see missed items.
new items:
(see) above

File: src/test/resources/com/puppycrawl/tools/checkstyle/checks/indentation/indentation/InputIndentationNewWithForceStrictCondition.java (hunk 6 above)
Comment (plan3d) [reply src/test/resources/com/puppycrawl/tools/checkstyle/checks/indentation/indentation/InputIndentationNewWithForceStrictCondition.java:37]: Added statements without warn

**Comment by plan3d** [comment]
Added more test input examples

File: src/test/resources/com/puppycrawl/tools/checkstyle/checks/indentation/indentation/InputIndentationNewHandler.java (hunk 4 above)
Comment (plan3d) [reply src/test/resources/com/puppycrawl/tools/checkstyle/checks/indentation/indentation/InputIndentationNewHandler.java:25]: See new commit https://github.com/checkstyle/checkstyle/commit/6d04f1645f82fadbdf5496d2b60d38810612e575

**Comment by romani** [comment]
Github, generate report

**Comment by romani** [comment]
Github, generate report

**Comment by romani** [comment]
Github, generate report

**Comment by romani** [comment]
Github, generate report

**Comment by romani** [comment]
Github, generate report

**Comment by romani** [comment]
Github, generate report

**Review by romani — APPROVED** [review]
I am ok to merge, one step forward without easy to catch regressions.

Next reviewer, please beware that PR is abandoned, so if you really see something to improve, do it your self of close PR.
