### PR TITLE
Issue #11015: Fixed false negative about ternary operator in SimplifyBooleanExpressionCheck

### LINKED ISSUE #11015: SimplifyBooleanExpression: A false negative about ternary operator
I have read check documentation: https://checkstyle.sourceforge.io/config_coding.html#SimplifyBooleanExpression
I have downloaded the latest checkstyle from: https://checkstyle.org/cmdline.html#Download_and_Run
I have executed the cli and showed it below, as cli describes the problem better than 1,000 words

```bash
/var/tmp $ javac Test.java
/var/tmp $ cat config.xml
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
          "-//Checkstyle//DTD Checkstyle Configuration 1.3//EN"
          "https://checkstyle.org/dtds/configuration_1_3.dtd">

<module name="Checker">
  <property name="severity" value="error"/>
  <property name="fileExtensions" value="java, properties, xml"/>
  <module name="TreeWalker">    
    <module name="SimplifyBooleanExpression"/>
  </module>
</module>

/var/tmp $ cat Test.java
public class Test {
    public boolean fun() {
        return false;
    }
    public boolean foo() {
        boolean tag = fun() ? true : false;  // should report a warning here
        // boolean tag = func() == true; // can be detected
        return tag;
    }
}

/var/tmp $ RUN_LOCALE="-Duser.language=en -Duser.country=US"
/var/tmp $ java $RUN_LOCALE -jar checkstyle-9.2-all.jar -c ./config.xml Test.java

#[[PLACE YOUR OUTPUT HERE]]
Starting audit...
Audit done.
```
---
**Describe what you expect in detail.**
---
I have just found a false negative about the rule SimplifyBooleanExpression. Please refer to the below simplfied case. Here, I think `fun() ? true : false`  at line 6 is similar to `func() == true`. They all can be simplified into `func()`.

### PR DESCRIPTION
**Pull request by Vyom-Yadav**
Resolves #11015: SimplifyBooleanExpression: A false negative about ternary operator
Diff Regression config: https://gist.githubusercontent.com/Vyom-Yadav/98dceb63a79f4833e85fff9b2e1464a6/raw/f2165f24391044b23b73a312a7d05179ed70b188/my_checks.xml
Final report (clean) - https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/8b38dbc_2021055812/reports/diff/index.html
Website - https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/6db4c58_2021130029/config_coding.html#SimplifyBooleanExpression

### CODE REVIEW

**Comment by Vyom-Yadav** [comment]
Github, generate report

**Comment by strkkk** [comment]
@Vyom-Yadav I think such cases should not produce violations - https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/2286531_2021065928/reports/diff/lombok-ast/xref/home/runner/work/checkstyle/checkstyle/contribution/checkstyle-tester/repositories/lombok-ast/src/template/lombok/ast/template/TemplateProcessor.java.html#L739
https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/2286531_2021065928/reports/diff/spring-integration/xref/home/runner/work/checkstyle/checkstyle/contribution/checkstyle-tester/repositories/spring-integration/spring-integration-redis/src/main/java/org/springframework/integration/redis/outbound/RedisStoreWritingMessageHandler.java.html#L362

lets make it as stupid as possible and only detect cases with literals in both sides of colon.

Please also add cases like https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/2286531_2021065928/reports/diff/lombok-ast/xref/home/runner/work/checkstyle/checkstyle/contribution/checkstyle-tester/repositories/lombok-ast/test/resources/alias/ZComplex1.java.html#L32 and https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/2286531_2021065928/reports/diff/lombok-ast/xref/home/runner/work/checkstyle/checkstyle/contribution/checkstyle-tester/repositories/lombok-ast/test/resources/idempotency/C003_SimpleExpressions.java.html#L51
 in test inputs

**Comment by Vyom-Yadav** [comment]
> https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/2286531_2021065928/reports/diff/lombok-ast/xref/home/runner/work/checkstyle/checkstyle/contribution/checkstyle-tester/repositories/lombok-ast/src/template/lombok/ast/template/TemplateProcessor.java.html#L739

@strkkk But this can be written as `cma != null && cma.isStatic()`, similarly for other cases.

> lets make it as stupid as possible and only detect cases with literals in both sides of colon or if literal is before question mark.

For real? But then what will be the benefit of it? Just saying, I don't have any problem not evaluating such cases.

**Comment by strkkk** [comment]
> But this can be written as `cma != null && cma.isStatic()`, similarly for other cases.
> For real? But then what will be the benefit of it? Just saying, I don't have any problem not evaluating such cases.

I understand that. I am afraid that such cases can bring more issues because users will argue that their way is clearer than `cma != null && cma.isStatic()` (we had situations like this before). I prefer to avoid such things and detect cases that will not bring questions.
If there will be demand from users, we can make it smarter by detecting cases with methods, but for now it is better to avoid additional complication.

**Comment by Vyom-Yadav** [comment]
Github, generate report

**Comment by Vyom-Yadav** [comment]
> I understand that. I am afraid that such cases......

@strkkk Ok then what about a property that allows raising an error in cases like [this one](https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/2286531_2021065928/reports/diff/lombok-ast/xref/home/runner/work/checkstyle/checkstyle/contribution/checkstyle-tester/repositories/lombok-ast/src/template/lombok/ast/template/TemplateProcessor.java.html#L739). Also I modified it to raise errors only in cases like-
`true ? a() : b()`, `a? true : false`

**Comment by strkkk** [comment]
Report looks good to me. Please fix ci issues.
> Ok then what about a property that allows raising an error in cases like 

if we want this, I suggest to create and issue to discuss this enhancement. It is without doubt out of scope of this issue. Personally I do not think it is a good way, but I might be wrong.

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/SimplifyBooleanExpressionCheck.java [hunk 1]
```diff
@@ -48,18 +49,22 @@
...
- *     if (a == b) {}; // OK
- *     if (a == false) {}; // violation, can be simplified to !a
+ *     if (a == true) {};    // violation, can be simplified to a
+ *     if (a == b) {};       // OK
+ *     if (a == false) {};   // violation, can be simplified to !a
  *     if (!(a != true)) {}; // violation, can be simplified to a
  *
  *     e = (a || b) ? c : d; // OK
- *     e = (a || false) ? c : d; // violation, can be simplified to a
+ *     e = (a || false) ? c : d;     // violation, can be simplified to a
```
Comment (strkkk) [inline src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/SimplifyBooleanExpressionCheck.java:60]: please revert this indentation changes, they are not related to issue and do not seem necessary

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/SimplifyBooleanExpressionCheck.java [hunk 2]
```diff
@@ -105,17 +128,39 @@
...
-            case TokenTypes.NOT_EQUAL:
-            case TokenTypes.EQUAL:
-            case TokenTypes.LNOT:
-            case TokenTypes.LOR:
-            case TokenTypes.LAND:
-                log(parent, MSG_KEY);
-                break;
-            default:
-                break;
+        if (TokenUtil.isOfType(parent, UNACCEPTABLE_PARENT_OF_TRUE_OR_FALSE)
```
Comment (strkkk) [inline src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/SimplifyBooleanExpressionCheck.java:131]: to be honest, previous way is more readable. It clearly shows how tokens are handled. You can just add one more case to switch with if condition. It will be clearer imo

File: src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/simplifybooleanexpression/InputSimplifyBooleanExpression.java [hunk 3]
```diff
@@ -87,4 +87,24 @@ boolean b() {
...
+        boolean f = a == b ? false : c > 1; // ok
+        boolean q = c > 1 ? (c < 15
+                ? false : b) // ok
+                : a != b;
+        boolean v = c > 0 ? true :
+                c < 0 ? false : true; // violation
+        boolean g = (c > 0 ? true : c < 0)
+                ? false : false; // violation
+        Boolean value = null;
+        boolean temp = value != null ? value : false; // ok
```
Comment (strkkk) [inline src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/simplifybooleanexpression/InputSimplifyBooleanExpression.java:108]: please add violation cases like
`true ? a() : b()`
`true ? 1 : 2`
`a() ? true : true`

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/SimplifyBooleanExpressionCheck.java [hunk 4]
```diff
@@ -48,18 +49,22 @@
...
  *     e = (a || b) ? c : d; // OK
- *     e = (a || false) ? c : d; // violation, can be simplified to a
+ *     e = (a || false) ? c : d;     // violation, can be simplified to a
  *     e = (a &amp;&amp; b) ? c : d; // OK
  *
- *  }
+ *     int s = 12;
+ *     boolean m = s > 1 ? true : false; // violation, can be simplified to s > 1
+ *     boolean f = a == b
+ *             ? false : s > 1; // OK
```
Comment (strkkk) [inline src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/SimplifyBooleanExpressionCheck.java:66]: it is better to change ok example to one from report `var == null ? false : var.someMethod()`

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/SimplifyBooleanExpressionCheck.java [hunk 5]
```diff
@@ -105,17 +128,39 @@
...
+     * @param ast ast
+     * @param parentAst parentAst
+     * @return {@code true} if expression with ternary operator can be simplified
+     */
+    private static boolean canExprWithTernaryOperatorBeSimplified(
+            DetailAST ast, DetailAST parentAst) {
+        final DetailAST nextSibling = ast.getNextSibling();
+
+        return TokenUtil.isOfType(parentAst.getFirstChild(), TRUE_AND_FALSE_TOKEN)
+                || isSecResultantExprLiteralTrueOrFalse(nextSibling);
```
Comment (strkkk) [inline src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/SimplifyBooleanExpressionCheck.java:150]: `isSecResultantExprLiteralTrueOrFalse` -> `isBooleanLiteral`

Comment (strkkk) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/SimplifyBooleanExpressionCheck.java:150]: In general, you can extract check for literals and make code look like
```
return isBooleanLiteral(parentAst.getFirstChild()) || nextSibling != null && isBooleanLiteral(nextSibling.getNextSibling();
```

**Review by strkkk — CHANGES_REQUESTED** [review]

**Comment by strkkk** [comment]
@Vyom-Yadav btw, there is a same method that can be extracted and reused
https://github.com/checkstyle/checkstyle/blob/5bceb5dccf260e338345ba33a5b5154175973979/src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/SimplifyBooleanReturnCheck.java#L226-L229

it is for https://github.com/checkstyle/checkstyle/pull/11020#discussion_r767134904

**Comment by Vyom-Yadav** [comment]
Github, generate report

**Comment by Vyom-Yadav** [comment]
Gtihub, generate site

**Comment by Vyom-Yadav** [comment]
Github, generate report

**Comment by Vyom-Yadav** [comment]
Github, generate site

**Comment by Vyom-Yadav** [comment]
https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/8b38dbc_2021053600/config_coding.html#SimplifyBooleanExpression

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/SimplifyBooleanExpressionCheck.java (hunk 1 above)
Comment (Vyom-Yadav) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/SimplifyBooleanExpressionCheck.java]: The examples look better now imo.
Before - https://checkstyle.sourceforge.io/config_coding.html#SimplifyBooleanExpression
After - https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/8b38dbc_2021053600/config_coding.html#SimplifyBooleanExpression
https://github.com/checkstyle/checkstyle/pull/9136#discussion_r571714853

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/SimplifyBooleanExpressionCheck.java (hunk 2 above)
Comment (Vyom-Yadav) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/SimplifyBooleanExpressionCheck.java]: done

File: src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/simplifybooleanexpression/InputSimplifyBooleanExpression.java (hunk 3 above)
Comment (Vyom-Yadav) [reply src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/simplifybooleanexpression/InputSimplifyBooleanExpression.java:108]: done

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/SimplifyBooleanExpressionCheck.java (hunk 4 above)
Comment (Vyom-Yadav) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/SimplifyBooleanExpressionCheck.java]: done

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/SimplifyBooleanExpressionCheck.java (hunk 5 above)
Comment (Vyom-Yadav) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/SimplifyBooleanExpressionCheck.java]: done

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/SimplifyBooleanExpressionCheck.java (hunk 1 above)
Comment (strkkk) [reply src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/SimplifyBooleanExpressionCheck.java]: minor commit is ok

File: src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/SimplifyBooleanExpressionCheck.java [hunk 6]
```diff
@@ -113,9 +116,28 @@ public void visitToken(DetailAST ast) {
...
+     * Checks if a token type is a literal true or false.
+     *
+     * @param tokenType the TokenType
+     * @return true iff tokenType is LITERAL_TRUE or LITERAL_FALSE
+     */
+    private static boolean isBooleanLiteralType(final int tokenType) {
+        final boolean isTrue = tokenType == TokenTypes.LITERAL_TRUE;
+        final boolean isFalse = tokenType == TokenTypes.LITERAL_FALSE;
+        return isTrue || isFalse;
+    }
```
Comment (strkkk) [inline src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/SimplifyBooleanExpressionCheck.java:142]: I meant not to copy-paste method from other check here, but to extract it to some common util class to reuse

**Review by strkkk — CHANGES_REQUESTED** [review]
Please fix xwiki ci issue

File: src/main/java/com/puppycrawl/tools/checkstyle/utils/CheckUtil.java [hunk 7]
```diff
@@ -589,4 +589,16 @@ private static int lastIndexOfNonWhitespace(String line) {
         }
         return length;
     }
+
+    /**
+     * Checks if a token type is a literal true or false.
+     *
+     * @param tokenType the TokenType
+     * @return true iff tokenType is LITERAL_TRUE or LITERAL_FALSE
```
Comment (strkkk) [inline src/main/java/com/puppycrawl/tools/checkstyle/utils/CheckUtil.java:597]: `iff`` -> if, please do me a favor and correct this typo as a part of extraction commit

**Comment by Vyom-Yadav** [comment]
Github, generate site

**Comment by Vyom-Yadav** [comment]
XWiki PR - https://github.com/xwiki/xwiki-platform/pull/1731

**Comment by strkkk** [comment]
> wercker is failing on which project?

it is a well-known failure in sevntu. You can try to rebase your PR to latest master, there were some exclusions added to avoid these failures.

**Comment by Vyom-Yadav** [comment]
@strkkk Rebased, all checks are successfully passing.

**Review by strkkk — APPROVED** [review]

File: src/main/java/com/puppycrawl/tools/checkstyle/utils/CheckUtil.java [hunk 8]
```diff
@@ -589,4 +589,16 @@ private static int lastIndexOfNonWhitespace(String line) {
...
         return length;
     }
+
+    /**
+     * Checks if a token type is a literal true or false.
+     *
+     * @param tokenType the TokenType
+     * @return true if tokenType is LITERAL_TRUE or LITERAL_FALSE
+     */
+    public static boolean isBooleanLiteralType(final int tokenType) {
```
Comment (pbludov) [inline src/main/java/com/puppycrawl/tools/checkstyle/utils/CheckUtil.java:599]: Why `CheckUtil`? We have `TokenUtil` for such methods. Please move.

**Review by pbludov — CHANGES_REQUESTED** [review]
One change please.

File: src/main/java/com/puppycrawl/tools/checkstyle/utils/CheckUtil.java (hunk 8 above)
Comment (Vyom-Yadav) [reply src/main/java/com/puppycrawl/tools/checkstyle/utils/CheckUtil.java]: Done.

**Review by pbludov — APPROVED** [review]

**Comment by romani** [comment]
Github, generate report

**Review by romani — APPROVED** [review]
thanks a lot for fix
